import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 诊断学 学习指导与习题集（第4版）— 第二章 一般检查 题库提取
 * 来源：《诊断学学习指导与习题集》第4版（人民卫生出版社，主编：万学红、卢雪峰）
 *
 * == 统计报告 ==
 * - 名词解释：25 题
 * - A1 型题（单句型最佳选择题）：45 题
 * - A2 型题（病例型最佳选择题）：14 题
 * - 问答题（简答）：12 题
 * - B 型配伍题（共用备选答案）：6 组、共 21 个成员
 * - 独立题合计：96 题（不含 B 型组成员）
 * - 缺失答案：0 题
 * - 无法提取：0 题
 * - 说明：原书 PDF 含较多 OCR 排版乱码，已按医学语义恢复正确用字，常见映射包括——“发钳/发生甘/发生钳”应为“发绀”、“蒙古膜/墨膜/勃膜/黠膜”应为“黏膜”、“险/脸颊/险裂”应为“睑/眼裂”、“眼险”应为“眼睑”、“软牌/软膊”应为“软腭”、“硬腾”应为“硬腭”、“紫癫”应为“紫癜”、“黄瘟/黄痘”应为“黄疸”、“白癫风/白痴风”应为“白癜风”、“斑磨/斑摩”应为“斑疹”、“玫瑰磨/政瑰彦/玫瑰菇”应为“玫瑰疹”、“麻彦/麻磨”应为“麻疹”、“尊麻彦/草麻彦”应为“荨麻疹”、“蜘蛛痞/血管痞”应为“蜘蛛痣/血管痣”、“胡萝卡”应为“胡萝卜”、“服行/脏行”应为“跛行”、“间歇性服行”应为“间歇性跛行”、“凄管/瘦管”应为“瘘管”、“癫痕”应为“瘢痕”、“向倭病”应为“佝偻病”、“髓关节”应为“髋关节”、“脊髓瘸”应为“脊髓痨”、“瘟疮/座疮”应为“痤疮”、“东柱/束柱”应为“汞柱”、“回级”应为“Ⅳ级”、“湿眼音”应为“湿啰音”、“mrn”应为“mm”、“凄虫症”应为“蛔虫症”、“历史增量斑”等。A1 型题第 8 题答案键原为“C 桡动脉搏动”等。B 型题第 1 组（紫癜/淤斑/出血点）选项“直径 2～3mm”“直径 6mm”为诱选项，未被任何成员使用。所有题目均做轻度改写并重排选项，数值与临床细节保留原值。
 *
 * 解析内容位于 answer.content 数组的第二个元素。
 */

const topic = "general-examination";
const chapterLabel = "第二章";
const locatorBase =
  "《诊断学学习指导与习题集》第4版 第二章 一般检查 习题（PDF 第111–121页）";
const promptNote =
  "题干改写；原题来自用户提供的题集，未经第三方授权审核";
const answerNotice =
  "答案依据上传题集整理并改写，尚未与权威教材交叉核对";

const kp = `kp-diagnosis-general-examination`;

/** 名词解释（term） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-general-examination-ch2-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：生命体征",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "生命体征",
        "生命体征是评价生命活动存在与否及其质量的指标，包括体温、脉搏、呼吸和血压，为体格检查时必须检查的项目。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：消瘦",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "消瘦",
        "消瘦是指体重减轻至低于正常的 10% 时而表现出的状态。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：恶病质",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "恶病质",
        "长期患慢性消耗性疾病（如肿瘤、结核病或甲亢等）的病人，可表现为明显消瘦的外观，严重者称为恶病质。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肥胖",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肥胖",
        "肥胖是指体内中性脂肪积聚过多、体重增加，当超过标准体重的 20% 以上者。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：意识",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "意识",
        "意识是大脑功能活动的综合表现，即对环境的知觉状态。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：慢性面容",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "慢性面容",
        "慢性面容表现为面色灰暗或苍白，面容憔悴，双目无神，见于慢性消耗性疾病如肝硬化、严重结核病等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：二尖瓣面容",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "二尖瓣面容",
        "二尖瓣面容表现为面色晦暗、双颊紫红、口唇轻度发绀，见于风湿性心瓣膜病二尖瓣狭窄。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：满月面容",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "满月面容",
        "满月面容表现为面如满月，皮肤发红，常有痤疮，女性可有小须（胡须）；见于肾上腺皮质功能亢进及长期应用糖皮质激素的病人。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：自主体位",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["自主体位", "自主体位指病人可以自由活动而不受限制的体位。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：被动体位",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["被动体位", "被动体位指病人不能自己调整或变换肢体位置的体位。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：强迫体位",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["强迫体位", "强迫体位是指为了减轻疾病的痛苦，病人被迫采取的体位。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：角弓反张位",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "角弓反张位",
        "角弓反张位指病人颈及脊背肌肉强直，出现头向后仰，胸腹前凸，背过伸，躯干呈弓形；见于破伤风及小儿脑膜炎。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：蹒跚步态",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "蹒跚步态",
        "蹒跚步态指走路时身体左右摇摆似鸭状步态，见于佝偻病、大骨节病、进行性肌营养不良及双侧先天性髋关节脱位等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：共济失调步态",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "共济失调步态",
        "共济失调步态指起步时一脚高抬、骤然垂落，且双目向下注视，两脚间距很宽以防身体倾斜，闭目时则不能保持平衡；见于脊髓痨病人。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term015",
    order: 15,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：慌张步态",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "慌张步态",
        "慌张步态指起步后小步急速趋行、身体前倾的步态，见于震颤性麻痹（帕金森病）病人。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term016",
    order: 16,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：间歇性跛行",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "间歇性跛行",
        "间歇性跛行指步行中因下肢突发性酸痛、乏力，病人被迫停止行进，稍休息后方能继续行进；见于高血压、动脉硬化病人。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term017",
    order: 17,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：发绀",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "发绀",
        "发绀指皮肤呈青紫色，常出现于口唇、耳廓、面颊及肢端；见于还原血红蛋白增多或异常血红蛋白血症。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term018",
    order: 18,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：黄染（黄疸）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["黄疸", "皮肤黏膜发黄称为黄染（黄疸）。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term019",
    order: 19,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：白癜风",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白癜风",
        "白癜风为多形性、大小不等的色素脱失斑片，发生后可逐渐扩大但进展缓慢，无自觉症状，亦不引起生理功能改变；见于白癜风病人，有时偶见于甲状腺功能亢进、肾上腺皮质功能减退及恶性贫血病人。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term020",
    order: 20,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：斑疹",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "斑疹",
        "斑疹表现为局部皮肤发红，一般不凸出皮肤表面，见于斑疹伤寒、丹毒、风湿性多形性红斑等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term021",
    order: 21,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：玫瑰疹",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "玫瑰疹",
        "玫瑰疹为一种鲜红色圆形斑疹，直径 2～3mm，为病灶周围血管扩张所致。检查时拉紧附近皮肤或以手指按压可使皮疹消退，松开时又复出现，多出现于胸腹部，为伤寒和副伤寒的特征性皮疹。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term022",
    order: 22,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：紫癜",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["紫癜", "皮下出血 3～5mm 称为紫癜。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term023",
    order: 23,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：蜘蛛痣",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["蜘蛛痣", "蜘蛛痣为皮肤小动脉末端分支性扩张形成的血管痣，形态似蜘蛛。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term024",
    order: 24,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肝掌",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["肝掌", "肝掌为慢性肝病病人手掌鱼际、小鱼际处发红，加压后褪色。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-term025",
    order: 25,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：水肿",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "水肿",
        "皮下组织的细胞内及组织间隙内液体积聚过多称为水肿。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1 型题（a1-single），选项已随机重排，correctChoiceIndex 指向新顺序 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-general-examination-ch2-a1001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一项不属于一般检查的内容？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "皮肤黏膜",
      "神经反射",
      "面容表情",
      "生命体征",
      "意识状态",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "神经反射",
        "一般检查包括性别、年龄、生命体征、发育与体型、营养状态、意识状态、面容表情、体位姿式、步态、皮肤、淋巴结等；神经反射不属于一般检查。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某些疾病的发生与性别相关，下列疾病中多发于女性的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "食管癌",
      "系统性红斑狼疮",
      "肝癌",
      "胃癌",
      "血友病",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "系统性红斑狼疮",
        "系统性红斑狼疮多发于育龄期女性，在不同疾病中与性别相关的易感性最为突出。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于体温的测量方法，下列叙述正确的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "口测法适用于婴幼儿及神志不清者",
      "肛测法较口测法低 0.3～0.5℃",
      "腋测法正常值为 36～37℃",
      "腋测法测量体温时腋窝有汗液也不必擦干",
      "肛测法不用于小儿及神志不清者",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腋测法正常值为 36～37℃",
        "腋测法正常值约为 36～37℃，测量前应先擦干腋窝汗液；口测法不适用于婴幼儿及神志不清者，肛测法较口测法高 0.3～0.5℃且适用于小儿。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列对正常人体温生理波动的认识，错误的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "老年人体温略低",
      "24 小时体温波动一般不超过 2℃",
      "妇女在月经期前或妊娠中体温略高",
      "运动或进食后体温略高",
      "体温早晨略低、下午略高",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "24 小时体温波动一般不超过 2℃",
        "正常人 24 小时内体温波动一般不超过 1℃，故“不超过 2℃”的说法错误。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "正常人在静息状态下的呼吸频率是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "11～16 次/分",
      "11～18 次/分",
      "12～24 次/分",
      "12～20 次/分",
      "11～20 次/分",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["12～20 次/分", "正常人静息状态下呼吸频率为 12～20 次/分。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一项可引起呼吸过缓？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["贫血", "发热", "颅内压增高", "心功能不全", "甲亢"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颅内压增高",
        "颅内压增高可抑制呼吸中枢致呼吸减慢，其他选项多引起呼吸增快。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "临床上体温每升高 1℃，呼吸每分钟大约增加",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["5 次/分", "10 次/分", "2 次/分", "4 次/分", "6 次/分"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["4 次/分", "体温每升高 1℃，呼吸约增加 4 次/分。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "体格检查中，检查脉搏一般触摸哪一条动脉？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "颞动脉搏动",
      "面动脉搏动",
      "桡动脉搏动",
      "肱动脉搏动",
      "股动脉搏动",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["桡动脉搏动", "检查脉搏通常触摸桡动脉的搏动。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "正常成年人的脉率范围是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "60～80 次/分",
      "60～72 次/分",
      "80～90 次/分",
      "60～100 次/分",
      "72～100 次/分",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["60～100 次/分", "正常成人脉率为 60～100 次/分。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列情况中，一般不出现脉搏增快的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["心力衰竭", "贫血", "甲状腺功能减退", "休克", "发热"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甲状腺功能减退",
        "甲状腺功能减退时代谢率降低、心率偏慢，一般不出现脉搏增快。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于奇脉，下列叙述正确的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "指节律正常而强弱交替出现的脉搏",
      "见于急性心肌梗死",
      "平静吸气时脉搏明显减弱甚至消失的现象",
      "脉搏骤起骤落",
      "见于甲状腺功能亢进",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "平静吸气时脉搏明显减弱甚至消失的现象",
        "奇脉指平静吸气时脉搏明显减弱甚至消失，常见于心包积液、缩窄性心包炎等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于血压的测量，下列叙述正确的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "测量时听到第一声响时的汞柱数值为收缩压",
      "测量时被测上肢裸露、肘部高于心脏水平",
      "测量时声音突然变小而低沉为舒张压",
      "正常人两上肢血压可相差 12～20mmHg",
      "正常人下肢血压较上肢高 10～20mmHg",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "测量时听到第一声响时的汞柱数值为收缩压",
        "测量血压时听到的第一声搏动音（Korotkoff 音）时的汞柱数值为收缩压，声音突然变小而低沉时的数值为舒张压；被测上臂应约与心脏水平同高。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一项不属于判断身体发育状况的指标？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["年龄", "第二性征", "肌肉发育情况", "身高", "体重"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌肉发育情况",
        "判断身体发育状况的指标主要有身高、体重、年龄及第二性征等，肌肉发育情况不属于其中的判断指标。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "判断人体营养状态最简便而快速的方法是查看",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "身高",
      "面部脂肪分布情况",
      "体重",
      "前臂屈侧或上臂背侧下 1/3 皮下脂肪的充盈程度",
      "腹部脂肪分布情况",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前臂屈侧或上臂背侧下 1/3 皮下脂肪的充盈程度",
        "判断营养状态最简便快速的方法是观察前臂屈侧或上臂背侧下 1/3 皮下脂肪的充盈程度。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1015",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一项不属于判断营养状况的指标？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["体重", "皮肤", "毛发", "皮下脂肪", "肌肉发育情况"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "体重",
        "营养状况主要依据皮肤、毛发、皮下脂肪及肌肉发育等情况综合判断，体重不属于其中的判断指标。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1016",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肥胖是指体重超过标准体重的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["15%", "10%", "20%", "25%", "5%"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["20%", "体重超过标准体重的 20% 以上可诊断为肥胖。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1017",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于原发性肥胖的特点，下列哪一项不正确？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "无内分泌疾病",
      "有遗传倾向",
      "全身脂肪分布不均匀",
      "摄入热量过多所致",
      "青少年病人可有外生殖器发育迟缓",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "全身脂肪分布不均匀",
        "原发性肥胖的脂肪分布常较均匀，分化型肥胖（向心性）才多见于继发性；故“全身脂肪分布不均匀”不是原发性肥胖的特点。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1018",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于单纯性肥胖的叙述，正确的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "多由某些内分泌疾病引起",
      "常有一定的遗传倾向",
      "表现为向心性肥胖",
      "全身脂肪分布不均",
      "青少年期没有生殖器发育迟缓",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常有一定的遗传倾向",
        "单纯性肥胖常与遗传因素有关，一般不伴内分泌疾病，脂肪分布较均匀。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1019",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "临床上检查意识状态的方法通常多采用",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["听诊", "嗅诊", "问诊", "叩诊", "触诊"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["问诊", "检查意识状态主要通过问诊了解其反应与对环境的知觉情况。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1020",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "甲状腺功能亢进的面容特征是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "面容憔悴，目光暗淡",
      "面色灰褐，额部有褐色色素沉着",
      "面色苍白，表情疲惫",
      "面容惊愕，眼裂增宽，目光闪亮",
      "面色苍白，颜面水肿",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "面容惊愕，眼裂增宽，目光闪亮",
        "甲亢面容表现为面容惊愕、眼裂增宽、眼球突出、目光闪亮而有神。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1021",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一项不符合甲状腺功能亢进的面容表现？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "眼球突出",
      "瞬目减少",
      "目光无神",
      "眼裂增大",
      "面容呈惊愕状",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "目光无神",
        "甲亢面容为目光闪亮有神，而非目光无神，故“目光无神”不符合甲亢面容。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1022",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "甲状腺功能减退（黏液性水肿）的面容是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "面色灰褐，额部有褐色色素沉着",
      "神情淡漠，反应迟钝，瞬目减少",
      "面色苍黄，颜面水肿，目光呆滞",
      "面色苍白，表情疲惫",
      "面容惊愕，目光闪亮",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "面色苍黄，颜面水肿，目光呆滞",
        "甲状腺功能减退为黏液性水肿面容，表现面色苍黄、颜面水肿、目光呆滞等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1023",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "风心病二尖瓣狭窄的典型面容是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "面色苍白，表情疲惫",
      "表情淡漠，反应迟钝",
      "面色灰暗，双颊发红，口唇发绀",
      "面色灰褐，额部有褐色色素沉着",
      "面容惊愕，目光闪亮",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "面色灰暗，双颊发红，口唇发绀",
        "二尖瓣面容表现为面色晦暗、双颊紫红、口唇轻度发绀，为风湿性心瓣膜病二尖瓣狭窄的典型表现。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1024",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "急性腹膜炎的病人多采用哪种体位？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "强迫仰卧位",
      "被动体位",
      "强迫坐位",
      "自动体位",
      "强迫俯卧位",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "强迫仰卧位",
        "急性腹膜炎病人常呈屈膝仰卧的强迫仰卧位，以松驰腹肌、减轻疼痛。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1025",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胆道蛔虫症急性发作时的体位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["坐位", "强迫蹲位", "强迫仰卧位", "辗转体位", "强迫停立位"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "辗转体位",
        "胆道蛔虫症发作时疼痛剧烈，病人常呈辗转反侧的辗转体位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1026",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "急性左心功能不全的病人常取的体位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["辗转体位", "强迫坐位", "自动体位", "强迫仰卧位", "强迫蹲位"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "强迫坐位",
        "急性左心功能不全（肺水肿）时，病人常取强迫坐位（端坐呼吸）以减轻回心血量、缓解呼吸困难。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1027",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胸膜疾患的病人常采用的体位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["自动体位", "强迫俯卧位", "强迫仰卧位", "强迫侧卧位", "强迫坐位"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "强迫侧卧位",
        "一侧胸膜炎或胸腔积液时，病人多向患侧卧（强迫侧卧位），以限制患侧活动、减轻疼痛。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1028",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "震颤麻痹（帕金森病）病人走动时的步态是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["跨阔步态", "慌张步态", "蹒跚步态", "醉酒步态", "剪刀步态"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "慌张步态",
        "震颤麻痹（帕金森病）病人起步后小步急速趋行、身体前倾，呈慌张步态。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1029",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "贫血病人出现皮肤及黏膜苍白时，较为可靠的检查部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "睑结膜",
      "耳廓皮肤",
      "面颊、皮肤及上腭黏膜",
      "手背皮肤及口腔黏膜",
      "颈部皮肤、舌面",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "睑结膜",
        "检查贫血所致苍白较可靠的部位是睑结膜，因其黏膜薄、血管丰富且不受色素沉着影响。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1030",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列部位中，发绀一般不常出现于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["耳廓", "腹部", "唇", "舌", "肢端"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腹部",
        "发绀常见于口唇、耳廓、面颊及肢端等毛细血管丰富处，一般不出现于腹部。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1031",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "黄疸早期或轻微出现时常首见于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["手掌、脚掌", "躯干", "耳廓", "巩膜、软腭黏膜", "四肢肢端"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "巩膜、软腭黏膜",
        "黄疸早期或轻微时首先出现于巩膜及（软）腭部黏膜，因这些部位组织弹性纤维与胆红素亲和力较高而更为明显。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1032",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "体格检查中对黄疸的鉴别判断，正确的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "皮肤黄染仅在手掌、足底",
      "皮肤有黄染肯定是黄疸",
      "巩膜黄染仅出现在角膜缘周围",
      "巩膜均匀黄染",
      "巩膜有黄染肯定为黄疸",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "巩膜均匀黄染",
        "真性黄疸的巩膜黄染呈均匀分布、连续，可与胡萝卜素血症、球结膜下脂肪等所致的黄染相鉴别。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1033",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "过多食用含胡萝卜素的食物可使皮肤黄染，但一般不发生于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["手掌", "足底", "鼻部及双颊部", "巩膜和口腔黏膜", "前额"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "巩膜和口腔黏膜",
        "大量食用含胡萝卜素食物引起皮肤黄染时，因胆红素并不增高，巩膜及口腔黏膜一般不发生黄染。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1034",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "检查皮肤弹性常取的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["眼睑部", "腹部", "躯干", "手背或上臂内侧", "胫前"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "手背或上臂内侧",
        "检查皮肤弹性常取手背或上臂内侧等皮肤较薄松弛处，捏起皮肤观察其回弹情况。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1035",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "玫瑰疹多出现在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["面部", "胸腹部", "背部", "四肢", "生殖器"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["胸腹部", "玫瑰疹多出现于胸腹部。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1036",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "玫瑰疹对下列哪种疾病具有诊断意义？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["丹毒", "风湿热", "猩红热", "伤寒", "麻疹"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["伤寒", "玫瑰疹为伤寒、副伤寒的特征性皮疹，对伤寒的诊断有意义。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1037",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "伤寒或副伤寒的特征性皮疹是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["荨麻疹", "丘疹", "玫瑰疹", "斑丘疹", "斑疹"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["玫瑰疹", "伤寒、副伤寒的特征性皮疹为玫瑰疹。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1038",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "蜘蛛痣最常见的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["下胸部", "背部", "四肢", "颈面部", "腰部"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["颈面部", "蜘蛛痣多分布于颈面部、上肢、肩背部及前胸等上腔静脉分布区。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1039",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于蜘蛛痣的描述，不正确的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "是皮肤小动脉末端扩张所致",
      "多分布于颈部、上臂及肩背部等处",
      "大小不等",
      "是雌激素增高所致",
      "多见于下腔静脉分布区",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多见于下腔静脉分布区",
        "蜘蛛痣多分布于颈部、上臂及肩背部等上腔静脉分布区，并非多见于下腔静脉分布区，故该说法不正确。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1040",
    order: 40,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "人体浅表淋巴结的直径通常在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["0.5～1.0cm", "0.2～0.5cm", "1.0～1.5cm", "0.1～0.5cm", "0.2～0.3cm"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["0.2～0.5cm", "人体浅表淋巴结的正常直径多在 0.2～0.5cm。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1041",
    order: 41,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "腹股沟淋巴结收集淋巴的区域是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["躯干下部", "腹壁", "乳腺", "下肢及会阴部", "胸壁"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["下肢及会阴部", "腹股沟淋巴结主要收集下肢及会阴部的淋巴回流。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1042",
    order: 42,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "局限性淋巴结肿大可见于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["白血病", "系统性红斑狼疮", "淋巴瘤", "恶性肿瘤淋巴结转移", "丝虫病"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "恶性肿瘤淋巴结转移",
        "恶性肿瘤淋巴结转移属局限性淋巴结肿大的常见原因；白血病、淋巴瘤等多引起全身性淋巴结肿大。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1043",
    order: 43,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肺癌最易向下列哪一组淋巴结转移？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "左侧锁骨上窝淋巴结",
      "下颌下淋巴结",
      "颈部淋巴结",
      "右侧锁骨上窝淋巴结",
      "腹股沟淋巴结",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "右侧锁骨上窝淋巴结",
        "肺癌常经肺门淋巴道转移，最易累及同侧（右侧）锁骨上窝淋巴结。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1044",
    order: 44,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "易向左锁骨上淋巴结转移的疾病是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["食管癌", "肺癌", "结肠癌", "乳腺癌", "胃癌"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胃癌",
        "胃癌常经胸导管转移至左锁骨上窝淋巴结（Virchow 淋巴结），故称魏尔啸淋巴结，对胃癌诊断意义较大。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a1045",
    order: 45,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于慢性淋巴结肿大，下列叙述正确的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "艾滋病导致的淋巴结肿大不属于慢性淋巴结肿大",
      "药物热时导致的淋巴结肿大属于慢性淋巴结肿大",
      "肿瘤性淋巴结肿大不属于慢性淋巴结肿大",
      "淋巴结结核导致的淋巴结肿大不属于慢性淋巴结肿大",
      "系统性红斑狼疮导致的淋巴结肿大属于慢性淋巴结肿大",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "系统性红斑狼疮导致的淋巴结肿大属于慢性淋巴结肿大",
        "慢性淋巴结肿大病因包括感染性（淋巴结结核、艾滋病等）及非感染性（药物热、结缔组织病等）；系统性红斑狼疮等所致淋巴结肿大多呈慢性经过，属慢性淋巴结肿大。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A2 型题（病例型最佳选择题，questionKind 亦为 a1-single），选项已随机重排 */
const a2Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-general-examination-ch2-a2001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某女性病人，面色晦暗，双颊紫红，口唇轻度发绀，该病人属于何种面容？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["肝病面容", "二尖瓣面容", "慢性面容", "肾病面容", "病危面容"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "二尖瓣面容",
        "面色晦暗、双颊紫红、口唇轻度发绀为二尖瓣面容的典型表现，提示二尖瓣狭窄。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男，74 岁，因劳累后气短、心悸 1 周入院。查体：颊部紫红色，口唇发绀，心尖部闻及舒张期杂音。该病人可能出现的面容是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["贫血病容", "肾病面容", "满月面容", "二尖瓣面容", "肝病面容"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "二尖瓣面容",
        "心尖部舒张期杂音提示二尖瓣狭窄，伴颊部紫红、口唇发绀，符合二尖瓣面容。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某肾病病人长期用药治疗，检查见面部饱满、皮肤发红、伴痤疮，该病人属于何种面容？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["肾病面容", "满月面容", "急性病容", "甲亢面容", "二尖瓣面容"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "满月面容",
        "病人长期用药（如糖皮质激素）以致面部饱满、皮肤发红伴痤疮，为满月面容，提示肾上腺皮质功能亢进等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男，64 岁，近日有呼吸困难、咳嗽、下肢水肿。查体见呼吸急促、不能平卧、精神焦虑，该病人的体位可能是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "强迫侧卧位",
      "辗转体位",
      "强迫俯卧位",
      "强迫坐位",
      "强迫蹲位",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "强迫坐位",
        "病人呼吸急促、不能平卧、需端坐呼吸，提示急性左心功能不全，多取强迫坐位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男，65 岁，咳嗽、咳痰 18 年，气促 4 年，下肢水肿半个月，诊断为慢性支气管炎、阻塞性肺气肿、肺源性心脏病、心功能Ⅳ级。该病人多采取何种体位？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["自动体位", "端坐呼吸", "强迫仰卧位", "被动体位", "强迫侧卧位"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "端坐呼吸",
        "肺源性心脏病伴心功能不全、严重呼吸困难者，多取端坐呼吸（强迫坐位）以缓解症状。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某病人气促，诊断为右侧大量胸腔积液，该病人多采用何种体位？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["强迫坐位", "自动体位", "左侧卧位", "右侧卧位", "被动体位"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "右侧卧位",
        "大量胸腔积液时病人多取患侧卧位（右侧卧位），以减轻呼吸受限与疼痛。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男，70 岁，既往有高血压病史。近 1 个月常在步行中突发下肢酸痛乏力，稍作休息后又能继续行走。该病人可能出现的步态是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "共济失调步态",
      "蹒跚步态",
      "慌张步态",
      "跨阔步态",
      "间歇性跛行",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "间歇性跛行",
        "步行中突发下肢酸痛乏力、休息后缓解的间歇性跛行，多见于高血压、动脉硬化致下肢缺血病人。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "女，27 岁，过多食用胡萝卜致血中胡萝卜素含量增加，其皮肤黄染多出现的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["口腔黏膜", "躯干", "手掌、足底、前额", "耳廓", "巩膜"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "手掌、足底、前额",
        "胡萝卜素血症的皮肤黄染多见于手掌、足底及前额等部位，巩膜及黏膜不发黄。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男，30 岁，左颈部淋巴结无痛性肿大 1 个月，体温 36℃，左颈后可触及 3cm×3cm 无痛性肿大淋巴结。下列关于其淋巴结检查方法的叙述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "由浅入深滑动触诊",
      "触诊时让被检查者头部稍高，或偏向检查侧的对侧",
      "检查时注意淋巴结的部位、大小、硬度、压痛及活动度等",
      "可站在被检查者背后，手指紧贴检查部位",
      "颈部检查完后还要检查其他部位",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "触诊时让被检查者头部稍高，或偏向检查侧的对侧",
        "触诊颈部淋巴结时应嘱病人头稍低，或偏向检查侧以放松该部肌肉，而非“头部稍高、偏向对侧”，故该项错误。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男，58 岁，上腹隐痛 10 年，体重减轻，半年来有黑便，体检发现左锁骨上窝 2cm×2cm 淋巴结 2 个。检查其左锁骨上淋巴结的正确手法是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "头稍向左偏屈，左手触诊，手法同 A",
      "头向后伸，右手触诊，手法同 B",
      "头向前屈，右手触诊左锁骨上由浅触摸至锁骨后深部",
      "头稍向右偏屈，右手触诊，手法同 B",
      "头向前屈，左手触诊左锁骨上由浅触摸至锁骨后深部",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "头向前屈，右手触诊左锁骨上由浅触摸至锁骨后深部",
        "检查左锁骨上淋巴结时，嘱病人头向前屈，检查者用右手（对侧手）由浅入深触摸左锁骨上窝，直至锁骨后深部。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男，55 岁，上腹部无规律性疼痛、消瘦 1 年入院，胃镜示胃小弯处有一 2cm×2cm 大小溃疡，边缘不整齐、有坏死、少量渗血。检查体表淋巴结，对诊断意义最大的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["颈前、颈后", "腋下", "锁骨上窝", "腹股沟", "枕后"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "锁骨上窝",
        "胃部恶性肿瘤易转移至左锁骨上窝淋巴结（Virchow 淋巴结），故对诊断意义最大。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "女，53 岁，因咳嗽、痰中带血 1 个月入院，无发热，胸片示右肺门密度增高影，血常规正常，血沉 150mm/h。该病人若出现浅表淋巴结肿大，最先肿大的组群可能是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "右颈后淋巴结群",
      "左锁骨上窝淋巴结群",
      "右锁骨上窝淋巴结群",
      "右颏下淋巴结群",
      "左颈前淋巴结群",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "右锁骨上窝淋巴结群",
        "右肺门病变怀疑肿瘤者，最先肿大的浅表淋巴结组群多为右锁骨上窝淋巴结群。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "女，20 岁，干咳、痰中带血、低热半个月余，体检发现右上肺闻及湿啰音，PPD(+++)。若该病人出现浅表淋巴结肿大，最先肿大的组群可能是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["枕部淋巴结", "耳后淋巴结", "颈部淋巴结", "颏下淋巴结", "颌下淋巴结"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈部淋巴结",
        "右上肺湿啰音伴低热、干咳、PPD(+++) 提示肺结核，结核病人浅表淋巴结最先易肿大者常为颈部淋巴结。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-a2014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男，21 岁，左颈部有 3 个肿大的淋巴结，质地稍硬，其中一个坏死、破溃并形成瘘管。该病人可能性较大的疾病是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "急性淋巴结炎",
      "淋巴瘤",
      "恶性肿瘤淋巴结转移",
      "淋巴结结核",
      "慢性淋巴结炎",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "淋巴结结核",
        "淋巴结多发、质地稍硬、互相粘连并坏死破溃形成瘘管，符合淋巴结结核（尤其是溃疡、瘘管形成）的特点。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 问答题（short-answer） */
const shortAnswerItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-general-examination-ch2-sa001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "生命体征包括哪几项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["生命体征包括体温、脉搏、呼吸和血压四项。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-sa002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "体温测量误差的常见原因是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "体温测量误差常见原因有：（1）测量前未将体温计的水银（汞）柱甩到 36℃以下；（2）采用腋测法时肢体未能将体温计夹紧；（3）检测局部存在有冷热物品或刺激。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-sa003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "成人发育正常的指标有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "成人发育正常的指标有：（1）头部的长度为身高的 1/8～1/7；（2）胸围为身高的 1/2；（3）双上肢展开后，左右指端的距离与身高基本一致；（4）坐高等于下肢的长度。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-sa004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述常见的异常营养状态及临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "异常营养状态及临床意义：（1）营养不良：体重低于标准体重的 10% 以上称消瘦，极度消瘦称恶病质。常见于摄食及消化障碍（如食管、胃肠道、肝、胆、胰腺病变，严重的恶心呕吐所致摄食障碍，消化液或酶的生成减少造成的消化吸收不良），也见于消耗增多（如活动性结核病、恶性肿瘤等）。（2）营养过度：指体内脂肪过多积聚引起体重增加，超过标准体重 20% 以上，或体重指数（BMI）≥28（我国）为肥胖，但男女有别；主要原因为摄食过多，也与内分泌、遗传、生活方式、运动及精神因素等有关。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-sa005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "常见的典型异常步态有哪几种？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "典型异常步态有：慌张步态、跨阔步态、醉酒步态、剪刀步态、蹒跚步态、共济失调步态、间歇性跛行。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-sa006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "黄疸引起皮肤黏膜黄染的特点有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "黄疸引起皮肤、黏膜黄染的特点有：（1）黄疸首先出现于巩膜、硬腭后部及软腭黏膜上，随着血中胆红素浓度的继续增高、黏膜黄染更明显时，才会出现皮肤黄染；（2）巩膜黄染是连续的，近角巩膜缘处黄染轻、黄色淡，远角巩膜处黄染重、黄色深。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-sa007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "临床上常见的皮疹有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["临床上常见皮疹有：斑疹、玫瑰疹、丘疹、斑丘疹、荨麻疹。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-sa008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "何为肝掌？常见于何种病人？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "慢性肝病病人手掌鱼际、小鱼际肌处皮肤常发红、加压后褪色，称为肝掌，常见于急、慢性肝炎或肝硬化病人。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-sa009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "水肿分几度？如何分？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "水肿分为轻、中、重三度。轻度：仅见于眼睑、眶下软组织、胫骨前、踝部皮下组织，指压后可见组织轻度下陷、平复较快。中度：全身组织均可见明显水肿，指压后出现明显的或较深的组织下陷、平复较慢。重度：全身组织严重水肿，身体低位皮肤紧张发亮，甚至有液体渗出，此外胸腔、腹膜腔可见积液，外阴部严重水肿。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-sa010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述表浅淋巴结的检查顺序。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "表浅淋巴结检查的一般顺序为：耳前、耳后、乳突区、枕骨下区、颏下、颌下、颈后三角、颈前三角、锁骨上窝、腋窝、滑车上、腹股沟、腘窝。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-sa011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "全身性淋巴结肿大见于哪些疾病？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "全身淋巴结肿大见于：（1）感染性疾病：①病毒感染，如传染性单核细胞增多症、艾滋病等；②细菌感染，如布鲁菌病、血行播散型肺结核、麻风病等；③螺旋体感染，如梅毒、鼠咬热、钩端螺旋体病等；④原虫与寄生虫感染，如黑热病、丝虫病等。（2）非感染性疾病：①结缔组织病，如系统性红斑狼疮、干燥综合征、结节病等；②血液系统疾病，如急、慢性白血病，淋巴瘤，恶性组织细胞病等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-sa012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述淋巴结肿大的临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "淋巴结肿大的临床意义：（1）全身淋巴结肿大可遍及全身、大小不等、无粘连，见于淋巴瘤、急性或慢性白血病、传染性单核细胞增多症等。（2）局限性淋巴结肿大见于：①非特异性淋巴结炎，由引流区域的急、慢性炎症所引起，初起时柔软、有压痛、表面光滑、无粘连，肿大至一定程度即停止；慢性炎症时淋巴结较硬，最终可缩小或消退。②淋巴结结核，肿大淋巴结常发生在颈部血管周围，多发性、大小不等、质地稍硬，可相互粘连，或与周围组织粘连。③恶性肿瘤淋巴结转移，淋巴结质地坚硬或有橡皮样感，一般无压痛，与周围组织粘连、不易推动。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 型配伍题（共用备选答案，members 无 choices，correctChoiceIndex 指向 sharedChoices 下标） */

// 第 1 组：1–3 题共用备选答案（皮下出血大小）
const b001SharedChoices = [
  "直径 2～3mm",
  "直径 5mm 以上",
  "直径不超过 2mm",
  "直径 3～5mm",
  "直径 6mm",
];

const b001Members: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-general-examination-ch2-b001m1",
    order: 1,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "紫癜",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["直径 3～5mm", "皮下出血直径为 3～5mm 者称为紫癜。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b001m2",
    order: 2,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "淤斑",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["直径 5mm 以上", "皮下出血直径在 5mm 以上者称为淤斑。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b001m3",
    order: 3,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "出血点",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["直径不超过 2mm", "皮下出血直径不超过 2mm 者称为出血点。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

// 第 2 组：4–6 题共用备选答案（水肿最先出现部位）
const b002SharedChoices = [
  "腹腔",
  "下肢",
  "外阴",
  "眼睑",
  "胸腔",
];

const b002Members: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-general-examination-ch2-b002m1",
    order: 1,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "肾性水肿最先出现的部位",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["眼睑", "肾性水肿因水分较多、组织疏松，常最先出现于眼睑（晨起明显）。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b002m2",
    order: 2,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "心性水肿最先出现的部位",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["下肢", "心源性水肿受重力影响，常最先出现于身位下垂的下肢（踝部）。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b002m3",
    order: 3,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "肝性水肿最先出现的部位",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["腹腔", "肝性水肿（肝硬化）以门静脉高压、腹水为主，常最先表现为腹腔积液（腹水）。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

// 第 3 组：7–10 题共用备选答案（淋巴结触诊特点）
const b003SharedChoices = [
  "淋巴瘤",
  "非特异性淋巴结炎",
  "恶性肿瘤转移至淋巴结",
  "正常淋巴结",
  "淋巴结结核",
];

const b003Members: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-general-examination-ch2-b003m1",
    order: 1,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "直径多为 0.2～0.5cm，质地柔软，表面光滑，与毗邻组织无粘连，不易触及，亦无压痛",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["正常淋巴结", "直径 0.2～0.5cm、柔软光滑无粘连无压痛者符合正常淋巴结的特点。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b003m2",
    order: 2,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "颈部淋巴结肿大，质地中等，表面光滑无粘连，有轻微压痛，口服甲硝唑后淋巴结肿痛消失",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["非特异性淋巴结炎", "轻微压痛、抗感染（甲硝唑）后肿痛消失，符合非特异性（炎症性）淋巴结炎特点。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b003m3",
    order: 3,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "颈部多发性质地稍硬、大小不等、互相粘连，有时可见瘘管和瘢痕的淋巴结肿大",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["淋巴结结核", "多发性、质地稍硬、互相粘连并可见瘘管瘢痕者，符合淋巴结结核特点。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b003m4",
    order: 4,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "锁骨上扪及质地坚硬、表面光滑、与周围粘连不易推动、无压痛的淋巴结肿大",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["恶性肿瘤转移至淋巴结", "质地坚硬、无压痛并与周围粘连不易推动者，常为恶性肿瘤淋巴结转移。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

// 第 4 组：11–14 题共用备选答案（皮疹类型）
const b004SharedChoices = [
  "荨麻疹",
  "斑丘疹",
  "丘疹",
  "玫瑰疹",
  "斑疹",
];

const b004Members: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-general-examination-ch2-b004m1",
    order: 1,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "丹毒、斑疹伤寒病人，局部皮肤发红，一般不突出皮肤表面",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["斑疹", "局部发红、不凸出皮肤表面的皮损为斑疹，见于丹毒、斑疹伤寒等。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b004m2",
    order: 2,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "麻疹、药物疹、湿疹病人，除局部颜色改变外，病灶凸出皮肤表面",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["丘疹", "局部除颜色改变外并隆起于皮肤表面者为丘疹，见于麻疹、药物疹、湿疹等。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b004m3",
    order: 3,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "过敏反应时稍隆起皮肤表面的苍白色或红色的局限性水肿",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["荨麻疹", "过敏反应所致隆起于皮肤表面的苍白色或红色局限性水肿为荨麻疹。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b004m4",
    order: 4,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "伤寒和副伤寒病人的一种鲜红色圆形斑疹，按压可使其消退、松开又复出现，多见于胸腹部",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["玫瑰疹", "鲜红色圆形、压之退色又复现、多见于胸腹部的皮损为玫瑰疹，是伤寒、副伤寒的特征性皮疹。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

// 第 5 组：15–17 题共用备选答案（脱屑类型）
const b005SharedChoices = [
  "大水疱样脱屑",
  "银白色鳞状脱屑",
  "全身片状剥脱性脱屑",
  "片状脱屑",
  "米糠样脱屑",
];

const b005Members: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-general-examination-ch2-b005m1",
    order: 1,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "麻疹",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["米糠样脱屑", "麻疹疹退后常遗留米糠样脱屑。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b005m2",
    order: 2,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "猩红热",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["片状脱屑", "猩红热疹退后可呈片状脱屑（如手套、袜套样）。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b005m3",
    order: 3,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "银屑病",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["银白色鳞状脱屑", "银屑病的典型表现之一为银白色鳞状脱屑。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

// 第 6 组：18–21 题共用备选答案（皮下结节）
const b006SharedChoices = [
  "痛风结节",
  "风湿小结",
  "猪绦虫囊蚴结节",
  "结节性多动脉炎皮下结节",
  "Osler 小结",
];

const b006Members: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-general-examination-ch2-b006m1",
    order: 1,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "指尖、足趾、大小鱼际肌腱部位存在粉红色有压痛的小结节",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["Osler 小结", "指尖、足趾、大小鱼际等处粉红色有压痛的小结节为 Osler 小结，见于感染性心内膜炎。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b006m2",
    order: 2,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "位于关节附近、长骨伸侧，无压痛，圆形硬质小结节",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["风湿小结", "位于关节附近、长骨伸侧、无压痛的圆形硬质小结节为风湿小结。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b006m3",
    order: 3,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "位于皮下肌肉表面，豆状、硬韧、可推动的小结节，无压痛",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["猪绦虫囊蚴结节", "皮下肌肉表面豆状、硬韧、可推动且无压痛的小结节，符合猪绦虫囊蚴（囊尾蚴）结节的特点。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b006m4",
    order: 4,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "沿末梢动脉分布的结节",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: ["结节性多动脉炎皮下结节", "沿末梢动脉走行分布的皮下结节，为结节性多动脉炎的特点。"],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B 型配伍题（b1 共用备选答案） */
const b1Groups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-diagnosis-general-examination-ch2-b001",
    order: 1,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: b001SharedChoices,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: b001Members,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b002",
    order: 2,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: b002SharedChoices,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: b002Members,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b003",
    order: 3,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: b003SharedChoices,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: b003Members,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b004",
    order: 4,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: b004SharedChoices,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: b004Members,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b005",
    order: 5,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: b005SharedChoices,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: b005Members,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-general-examination-ch2-b006",
    order: 6,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: b006SharedChoices,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: b006Members,
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...a2Items,
  ...shortAnswerItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] =
  b1Groups;