import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 诊断学 学习指导与习题集（第4版）— 第四篇实验诊断 第五章 常用肾脏功能实验室检测 题库提取
 * 来源：《诊断学学习指导与习题集》第4版（人民卫生出版社，主编：万学红、卢雪峰）
 *
 * == 统计报告 ==
 * - 名词解释：5 题
 * - A1 型题（单句型最佳选择题）：16 题
 * - 问答题（简答）：6 题
 * - B1 型共用备选答案配伍题：1 组、共 3 个成员（金标准=菊粉清除率；远曲小管功能=昼夜尿比密试验；远端肾小管酸化=氯化铵负荷试验）
 * - A2 型题：0 题（本章无 A2 型题）
 * - 独立题合计：27 题（不含 B 组成员）
 * - 缺失答案：0 题
 * - 无法可靠提取：0 题
 * - 说明：本章 OCR 错字多，已按医学语义恢复，如：血肌酐/内生肌酐清除率/尿素氮/肾小球滤过率/尿β2-微球蛋白/氯化铵负荷试验/菊粉清除率/对氨基马尿酸盐清除试验/酚红排泄试验/莫氏（昼夜尿比密）试验/血尿酸 等；检验数值与单位按医学常理恢复（血清肌酐 µmol/L、尿素氮/血尿素 mmol/L、内生肌酐清除率 ml/min、尿渗量 mOsm/(kg·H₂O)、血尿素氮分期阈值 <9/>9/>20mmol/L、血肌酐分期阈值 <178/>178/>445µmol/L 等），未捏造。所有题目均做轻度改写并重排选项，数值与临床细节保留原值。
 *
 * 解析内容位于 answer.content 数组的第二个元素。
 */

const topic = "lab-renal";
const chapterLabel = "第四篇实验诊断 第五章";
const locatorBase =
  "《诊断学学习指导与习题集》第4版 第四篇实验诊断 第五章 常用肾脏功能实验室检测 习题（PDF 第289–292页）";
const promptNote =
  "题干改写；原题来自用户提供的题集，未经第三方授权审核";
const answerNotice =
  "答案依据上传题集整理并改写，尚未与权威教材交叉核对";

const kp = `kp-diagnosis-${topic}`;

/** 名词解释（term） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-lab-renal-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肾清除率",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肾清除率",
        "肾清除率系指双肾于单位时间内，能将若干毫升血浆中所含的某物质全部加以清除而言。它是衡量肾脏清除某物质能力的重要指标。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肾小管性酸中毒",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肾小管性酸中毒",
        "肾小管性酸中毒是由于肾小管分泌氢离子或重吸收碳酸氢离子的功能减退，使尿酸化功能失常，而产生的一种代谢性酸中毒。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：内生肌酐清除率（endogenous creatinine clearance rate, Ccr）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "内生肌酐清除率",
        "内生肌酐清除率（Ccr）指肾在单位时间内把若干毫升血液中的内生肌酐全部清除出去，称为内生肌酐清除率。它是反映肾小球滤过功能的常用、灵敏指标。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：尿渗量（urine osmol, Uosm）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "尿渗量",
        "尿渗量（Uosm）系指尿内全部溶质的微粒总数量而言，它受溶质离子数量的影响，能真正反映肾浓缩和稀释功能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肾小球滤过率",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肾小球滤过率",
        "肾小球滤过率（GFR）是指单位时间内（分钟）经肾小球滤出的血浆液体量，称为肾小球滤过率。它是评估总肾功能的直接指标之一。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1 型题（单选，questionKind a1-single） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-lab-renal-a1001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于肾功能检测的叙述，正确的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "氯化铵试验可检测远端肾单位的浓缩功能",
      "尿β₂-微球蛋白是检测近端肾小管受损的灵敏指标",
      "血清pH可准确反映肾小管的酸碱平衡功能",
      "尿比重比尿渗量更能反映肾浓缩功能",
      "对氨基马尿酸盐清除试验反映近端肾小管的排泄功能",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "尿β₂-微球蛋白是检测近端肾小管受损的灵敏指标",
        "尿β₂-微球蛋白经肾小球滤过后绝大部分被近端肾小管重吸收分解，故尿中β₂-微球蛋白增多是检测近端肾小管受损的灵敏指标；其余叙述均不恰当。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "氯化铵负荷（酸负荷）试验主要用于诊断哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "以上都不是",
      "高钾性酸中毒",
      "混合性酸中毒",
      "近端肾小管酸中毒",
      "远端肾小管酸中毒",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "远端肾小管酸中毒",
        "氯化铵负荷试验通过给予外源性酸负荷使体内酸量增加，观察尿液酸化能力。若远端肾小管排氢障碍不能使尿液酸化，即为阳性，主要用于诊断远端肾小管酸中毒。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "尿渗量测定是检测下列哪项功能？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "远端肾小管排泌功能",
      "近端肾单位最大吸收功能",
      "肾小球滤过功能",
      "远端肾小管浓缩稀释功能",
      "近端肾小管排泌功能",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "远端肾小管浓缩稀释功能",
        "尿渗量反映尿内溶质微粒的总数量，能真正反映肾脏（远端肾小管）的浓缩和稀释功能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "病人因水肿伴恶心、呕吐就诊。查 Hb 80g/L，BP 156/110mmHg，尿蛋白（＋），颗粒管型 2～3 个/HPF，尿比重 1.010～1.012；若查出血肌酐 900µmol/L，24 小时尿量 600ml，则其肾功能状况最可能是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肾小球滤过轻度受损",
      "肾小管重吸收功能受损",
      "肾脏可代偿",
      "肾小球滤过功能明显受损",
      "肾小管排泌功能受损",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肾小球滤过功能明显受损",
        "血肌酐显著升高（900µmol/L）、少尿（24 小时尿量仅 600ml），提示肾小球滤过功能明显受损，已超出肾脏代偿范围。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某病人当血浆肌酐和尿素氮开始升高时，内生肌酐清除率至少已降至多少？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["70%", "10%", "20%", "50%", "30%"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "50%",
        "当内生肌酐清除率至少降至 50% 以下时，血浆肌酐和尿素氮才开始升高。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列除哪项外，均可出现血清尿素氮增高而血清肌酐正常？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "甲状腺功能亢进",
      "上消化道出血",
      "高蛋白饮食",
      "慢性肾衰竭代偿期",
      "大面积烧伤",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "慢性肾衰竭代偿期",
        "上消化道出血、大面积烧伤、甲状腺功能亢进及高蛋白饮食等可使尿素的生成增多，致血清尿素氮增高而血清肌酐正常；慢性肾衰竭代偿期一般血尿素氮、血肌酐均升高，故为除外项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "等渗尿是指尿渗量为下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "500mOsm/(kg·H₂O)",
      "1000mOsm/(kg·H₂O)",
      "300mOsm/(kg·H₂O)",
      "100mOsm/(kg·H₂O)",
      "700mOsm/(kg·H₂O)",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "300mOsm/(kg·H₂O)",
        "等渗尿是指尿渗量接近血浆渗量（约 300mOsm/(kg·H₂O)）的尿液。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "内生肌酐清除率的正常值为下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "150～170ml/min",
      "60～90ml/min",
      "120～150ml/min",
      "50～70ml/min",
      "80～120ml/min",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "80～120ml/min",
        "正常成人内生肌酐清除率参考值为 80～120ml/min。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "各种肾炎中，肾功能损害最早在下列哪项检查中反映出来？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "血肌酐升高",
      "自由水清除率",
      "酚红排泄试验",
      "内生肌酐清除率",
      "尿比密减低",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "内生肌酐清除率",
        "内生肌酐清除率是反映肾小球滤过功能的早期敏感指标，在血肌酐尚未明显升高时即可出现降低。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "慢性肾功能不全尿毒症期，血肌酐（Cr）应为下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["＞278µmol/L", "＞1800µmol/L", "＞445µmol/L", "＞470µmol/L", "＞178µmol/L"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "＞445µmol/L",
        "慢性肾功能不全尿毒症期血肌酐明显升高，＞445µmol/L。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "正常成人尿渗量与血浆渗量的比值为下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "(6～8.5)∶1",
      "(4～6.5)∶1",
      "(5～7.5)∶1",
      "(2～3.5)∶1",
      "(3～4.5)∶1",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "(3～4.5)∶1",
        "正常成人尿/血浆渗量比值约为 (3～4.5)∶1（24 小时尿渗量与血浆渗量之比约 3～4.5）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "正常人禁水 8 小时后尿渗量＜600mOsm/(kg·H₂O)，表明哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肾脏内分泌功能受损",
      "肾小管酸中毒",
      "肾衰竭失代偿期",
      "肾浓缩功能障碍",
      "肾小球滤过功能受损",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肾浓缩功能障碍",
        "正常人禁水 8 小时后尿渗量应＞600mOsm/(kg·H₂O)；若＜600mOsm/(kg·H₂O)，提示肾浓缩功能障碍。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "对血尿酸的临床意义，下列描述正确的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "血尿酸降低，见于肾小球滤过功能受损",
      "血尿酸升高，表明肾小管重吸收功能受损",
      "血尿酸升高，见于使用大剂量糖皮质激素",
      "血尿酸升高，表明肝功能严重受损",
      "血尿酸比血肌酐和尿素氮更能反映早期肾小球滤过功能损伤",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血尿酸比血肌酐和尿素氮更能反映早期肾小球滤过功能损伤",
        "尿酸大部分经肾小球滤过排出，滤过减少时血尿酸升高早于血肌酐和尿素氮，故血尿酸能更敏感地反映早期肾小球滤过功能损伤。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "莫氏试验（昼夜尿比密试验）主要观察下列哪些指标？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "尿渗量和尿比密",
      "尿渗量和尿Na（钠）",
      "尿量和尿渗量",
      "尿量和尿比密",
      "尿比密和尿Na（钠）",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "尿量和尿比密",
        "莫氏试验（昼夜尿比密试验）主要观察 24 小时昼、夜各次尿量与尿比密的变化，用于判断肾浓缩稀释功能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1015",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "正常人 24 小时夜尿量不应超过下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["850ml", "650ml", "450ml", "750ml", "550ml"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "750ml",
        "正常人 24 小时夜尿量不应超过 750ml（约占总尿量的 1/4～1/3）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-a1016",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "正常人昼尿量与夜尿量之比为下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "(4～5)∶1",
      "(6～7)∶1",
      "(2～3)∶1",
      "(3～4)∶1",
      "(5～6)∶1",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "(3～4)∶1",
        "正常成人 24 小时尿量中，昼/夜尿量之比约为 (3～4)∶1。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 问答题（short-answer） */
const shortAnswerItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-lab-renal-sa001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述血尿素氮升高的临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血尿素氮升高的临床意义",
        "血中尿素氮增高见于：①器质性肾功能损害：各种原发性肾小球肾炎、肾盂肾炎、间质性肾炎、肾肿瘤、多囊肾等所致的慢性肾衰竭；急性肾衰竭时肾功能 GFR 下降至 50% 以下时，BUN 升高。②肾前性少尿：如严重脱水、大量腹腔积液、心力衰竭、肝肾综合征等导致血容量不足、肾血流量减少灌注不足致少尿。③蛋白质分解或摄入过多：如急性传染病、高热、上消化道大出血、大面积烧伤、严重创伤、大手术后和甲状腺功能亢进、高蛋白饮食等，但血肌酐一般不升高。④血 BUN 可作为肾衰竭透析充分性指标。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-sa002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "常见的远端肾功能试验有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常见的远端肾功能试验",
        "常见的远端肾功能试验有：昼夜尿比密试验、尿渗量（尿渗透压）测定等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-sa003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "测定肾小球滤过功能的试验有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "测定肾小球滤过功能的试验",
        "测定肾小球滤过功能的试验有：血清肌酐测定、内生肌酐清除率测定、血尿素氮测定、血尿酸测定、肾小球滤过率测定、血β₂-微球蛋白的测定等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-sa004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "根据内生肌酐清除率可将肾功能损害程度分为几期？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "根据内生肌酐清除率（Ccr）的肾功能分期",
        "根据 Ccr 一般可将肾功能分为 4 期：第 1 期肾衰竭代偿期 Ccr 51～80ml/min；第 2 期肾衰竭失代偿期 Ccr 50～20ml/min；第 3 期肾衰竭期 Ccr 19～10ml/min；第 4 期尿毒症期或终末期肾衰竭 Ccr <10ml/min。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-sa005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "根据血肌酐将慢性肾衰竭分为几期？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "根据血肌酐的慢性肾衰竭分期",
        "肾衰竭代偿期，血肌酐＜178µmol/L；肾衰竭失代偿期，血肌酐＞178µmol/L；肾衰竭期，血肌酐明显升高，＞445µmol/L。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-sa006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "根据血尿素氮将慢性肾衰竭分为几期？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "根据血尿素氮的慢性肾衰竭分期",
        "肾衰竭代偿期，血 BUN <9mmol/L；肾衰竭失代偿期，血 BUN >9mmol/L；肾衰竭期，血 BUN >20mmol/L。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 型题（共用备选答案，questionKind b1；成员无 choices，correctChoiceIndex 指向 sharedChoices 下标） */

// 第 1 组：B1（1–3 题共用备选答案；原书标注 [B2型题]、共用备选答案）
const b001SharedChoices = [
  "Ccr（内生肌酐清除率）",
  "对氨基马尿酸盐清除试验",
  "氯化铵负荷试验",
  "昼夜尿比密试验",
  "菊粉清除率",
];

const b001Members: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-lab-renal-b001m1",
    order: 1,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "作为肾小球滤过率检测的金标准",
    correctChoiceIndex: 4,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "菊粉清除率",
        "菊粉不被肾小管重吸收、排泌，可自由从肾小球滤过，故菊粉清除率是测定肾小球滤过率的金标准。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-b001m2",
    order: 2,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "测定肾远曲小管功能的是",
    correctChoiceIndex: 3,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "昼夜尿比密试验",
        "昼夜尿比密试验用于判断肾远曲小管的浓缩与稀释功能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-renal-b001m3",
    order: 3,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "用于判断远端肾小管酸化功能的是",
    correctChoiceIndex: 2,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "氯化铵负荷试验",
        "氯化铵负荷试验通过外源酸负荷观察尿液酸化能力，用于判断远端肾小管酸化功能，阳性见于远端肾小管酸中毒。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-diagnosis-lab-renal-b001",
    order: 1,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: b001SharedChoices,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: b001Members,
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortAnswerItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];