import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 诊断学 学习指导与习题集（第4版）— 第四篇实验诊断 第四章 排泄物、分泌物及体液检测 题库提取（补充）
 * 来源：《诊断学学习指导与习题集》第4版（人民卫生出版社，主编：万学红、卢雪峰）
 *
 * 说明：本文件为 existing `extracted-diagnostics-lab-bodyfluids.ts` 的题型补齐文件，仅补充该文件
 * 缺失的题型——A1 型题后续（精液、前列腺液小节）、A2 型病例型最佳选择题、问答题（简答）、以及
 * B1 型共用备选答案配伍题。不得与既有文件中的任何 id 重复。
 *
 * == 统计报告 ==
 * - A1 型题补充（单句型最佳选择题）：14 题（精液 11 题、前列腺液 3 题，接续既有文件第 177 题之后）
 * - A2 型题（病例型最佳选择题）：12 题（尿液 7、粪便 3、脑脊液 2），均按单句最佳选择题映射为 questionKind: "a1-single"
 * - 问答题（简答）：21 题（尿液 3、粪便 3、痰液 2、脑脊液 4、浆膜腔积液 3、阴道分泌物 2、精液 2、前列腺液 2）
 * - B1 型共用备选答案配伍题：24 组、共 48 个成员（尿液 6 组、粪便 6 组、痰液 4 组、脑脊液 8 组）
 * - 独立题补充合计：47 题（不含 B 型组成员）
 * - 无法可靠提取：未知答案
 * - 说明：OCR 错字已按医学语义清洗，如 黄疸/酮体/铜绿假单胞菌/磷脂酰胆碱小体/庸酰/砜类/聩唑 等；
 *   检验数值与单位保留原值（×10⁹/L、mmol/L、µmol/L、mg/L、×10⁶/L、g/L、ml/24h 等），未捏造。
 *   个别细节（如脑脊液 B 型配伍中新型隐球菌/病毒性脑膜炎蛋白含量答案）按上传题集参考答案整理，
 *   与常见教材表述可能不符，已在题内注记并维持 unverified，未擅自改为教材口径。
 *
 * 解析内容位于 answer.content 数组的第二个元素。
 */

const topic = "lab-bodyfluids";
const chapterLabel = "第四篇实验诊断 第四章";
const locatorBase =
  "《诊断学学习指导与习题集》第4版 第四篇实验诊断 第四章 排泄物、分泌物及体液检测 习题（PDF 第256–288页）";
const promptNote =
  "题干改写；原题来自用户提供的题集，未经第三方授权审核";
const answerNotice =
  "答案依据上传题集整理并改写，尚未与权威教材交叉核对";

const kp = `kp-diagnosis-${topic}`;

/** A1 补充（精液、前列腺液） */
const a1SupplementItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1178",
    order: 178,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "精液标本采集最妥善的方法是下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "手淫法",
      "避孕套（安全套）法",
      "体外射精法",
      "电震动法",
      "前列腺按摩法",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "手淫法",
        "手淫法采集是精液标本最妥善的方法，能获取完整射精，减少污染与部分丢失。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1179",
    order: 179,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "精液液化不完全最常见于下列哪种病变？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "尿道炎",
      "前列腺炎",
      "膀胱炎",
      "肾炎",
      "阴道炎",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前列腺炎",
        "精液的液化依赖前列腺分泌的液化酶等；前列腺炎时液化因子减少，可致精液液化不完全或液化延迟。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1180",
    order: 180,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与精液液化有关的酶是下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "转氨酶",
      "溶菌酶",
      "凝固酶",
      "纤溶酶",
      "淀粉酶",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "纤溶酶",
        "精液中前列腺分泌的纤溶酶（纤维蛋白溶解酶）参与精液凝固块的液化过程，与精液液化密切相关。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1181",
    order: 181,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "健康男性射精后 30～60 分钟内，精子活动率（%）至少应大于下列哪个数值？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "30",
      "40",
      "50",
      "60",
      "70",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "60",
        "健康男性射精后 30～60 分钟内精子活动率一般应大于 60%；若明显低于此值常提示生育能力降低。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1182",
    order: 182,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "异常形态精子数量增多的常见原因，不包括下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "精索静脉曲张",
      "睾丸、附睾功能异常",
      "应用雌激素",
      "放射线损伤",
      "尿道炎",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "尿道炎",
        "精子形态异常增多常见于精索静脉曲张、睾丸附睾功能异常、应用雌激素及放射线损伤等；尿道炎一般不直接引起异常形态精子增多。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1183",
    order: 183,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一项不属于 WHO 精液常规检查的常规参数？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "精液量",
      "精浆生化成分（如精浆果糖）",
      "总精子数",
      "精子计数（浓度）",
      "前向运动力",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "精浆生化成分（如精浆果糖）",
        "WHO 精液常规检查的常规参数包括精液量、精子计数、总精子数、精子活力（前向运动力）与形态等；精浆生化（果糖、锌等）属于精浆功能检查，不属常规基础参数。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1184",
    order: 184,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于精液标本的采集，不正确的是下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "最妥善的方法为手淫法",
      "标本采集后应立即送检",
      "标本采集应在禁欲 4～5 天后进行",
      "标本温度应稳定在 20～40℃",
      "一次检查结果即可确诊生育能力",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "一次检查结果即可确诊生育能力",
        "精子生成受多种因素影响、波动较大，一次检查结果不足以作为生育能力确定的依据，必要时应复查。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1185",
    order: 185,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "一般不会造成少精症的是下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "精索静脉曲张",
      "睾丸炎症、畸形、萎缩",
      "理化因素损伤",
      "弓形体感染",
      "输精管、精囊缺陷",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "弓形体感染",
        "少精症常见于精索静脉曲张、睾丸炎/畸形/萎缩、理化因素损伤及输精管、精囊缺陷等；弓形体感染一般不作为少精症的常见原因。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1186",
    order: 186,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "精液中为精子提供能量的是下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "蔗糖",
      "葡萄糖",
      "果糖",
      "麦芽糖",
      "糖原",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "果糖",
        "精囊液分泌的果糖是精子活动的主要能量来源，果糖含量降低可反映精囊功能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1187",
    order: 187,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "精液中出现较多未成熟生殖细胞，最可能提示下列哪种情况？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "阴囊炎",
      "精囊阻塞",
      "睾丸曲细精管受影响",
      "睾丸炎",
      "前列腺炎",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "睾丸曲细精管受影响",
        "精液中出现较多未成熟生殖细胞提示生精过程异常，常见于睾丸曲细精管等生精微环境受损。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1188",
    order: 188,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "精浆液中最主要的成分是下列哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "前列腺液",
      "尿道旁腺液",
      "尿道球腺液",
      "精囊液",
      "输精管液",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "精囊液",
        "精浆的主要成分来自精囊液（约占射精量的较大比例），其分泌的果糖等对精子营养与活动有重要意义；其次是前列腺液等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1189",
    order: 189,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "前列腺液磷脂酰胆碱小体减少或消失，见于下列哪种疾病？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "前列腺炎",
      "前列腺癌",
      "精囊腺炎",
      "前列腺脓肿",
      "前列腺良性增生",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前列腺炎",
        "前列腺炎时磷脂酰胆碱小体减少或消失，同时可见白细胞增多；卵磷脂小体减少是前列腺炎的特点之一。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1190",
    order: 190,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "正常前列腺液镜检时可见到大量下列哪种成分？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "草酸钙结晶",
      "磷脂酰胆碱小体",
      "上皮细胞",
      "中性粒细胞",
      "夏科-莱登结晶",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "磷脂酰胆碱小体",
        "正常前列腺液中富含磷脂酰胆碱（卵磷脂）小体；其减少提示前列腺炎症等病变。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a1191",
    order: 191,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "磷脂酰胆碱小体减少常见于下列哪种疾病？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "精囊炎",
      "附睾炎",
      "前列腺炎",
      "尿道旁腺炎",
      "尿道球腺炎",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前列腺炎",
        "磷脂酰胆碱小体减少是前列腺炎症的主要表现之一，前列腺炎时卵磷脂小体减少或消失并伴白细胞增多。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A2 病例型最佳选择题（映射为 a1-single） */
const a2Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a2-001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男性，16 岁。因进食蚕豆后突然出现血尿，面色苍白、疲倦、精神差，无发热、咳嗽。血液检查：WBC 7.3×10⁹/L，Hb 78g/L，RBC 2.65×10¹²/L，PLT 256×10⁹/L；尿镜检：尿蛋白(+)，RBC 0～3/HPF，WBC 0～5/HPF。尿隐血试验阳性。其最可能的诊断是？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "血型不合输血引起的血红蛋白尿",
      "新生儿溶血引起的血红蛋白尿",
      "剧烈运动引起的血红蛋白尿",
      "6-磷酸葡萄糖脱氢酶缺陷引起的血红蛋白尿",
      "急性尿毒症引起的血红蛋白尿",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "6-磷酸葡萄糖脱氢酶缺陷引起的血红蛋白尿",
        "进食蚕豆后诱发、血红蛋白明显下降伴尿隐血阳性，符合葡萄糖-6-磷酸脱氢酶（G6PD）缺陷致溶血（蚕豆病）引起的血红蛋白尿。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a2-002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男性，65 岁。近期尿频，伴多食、多汗、疲倦、消瘦，无明显发热，甲状腺无肿大，血压正常；心电图、X 线等检查正常。尿糖(++++)，空腹血糖 12.6 mmol/L，血脂：胆固醇 6.2 mmol/L，肝肾功能无异常。此病人糖尿最可能是？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "应激性糖尿",
      "代谢性糖尿",
      "摄入性糖尿",
      "内分泌性糖尿",
      "其他糖尿",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "代谢性糖尿",
        "空腹血糖明显增高（12.6 mmol/L）伴尿糖强阳性及多食、消瘦等，提示糖尿病，属于血糖增高性（代谢性）糖尿。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a2-003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "女性，32 岁。体温 37.6～38.5℃，无咳嗽；生化检查肝功能、血糖、血脂、肾功能正常，尿素 9.6 mmol/L，肌酐 163 µmol/L，血尿酸 563 µmol/L；血 WBC 12.6×10⁹/L，中性粒细胞 82%；尿蛋白(+++)，RBC(+/HPF)，WBC(+～++/HPF)，管型 3～8/LPF。该管型质地厚、有切迹和扭曲，呈灰色，折光性较强。该管型最可能是？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "细胞管型",
      "颗粒管型",
      "蜡样管型",
      "脂肪管型",
      "细菌管型",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "蜡样管型",
        "该管型质地厚、有切迹和扭曲、灰色、折光性较强的特点符合蜡样管型，多见于肾小管严重病变。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a2-004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男性，36 岁。主诉浑浊白色小便 10 余天，偶有发热，腹股沟淋巴结稍大；血 WBC 10.3×10⁹/L，中性粒细胞 62%，嗜酸性粒细胞 12%，单核细胞 6%，淋巴细胞 20%；尿液呈乳白色、混浊，离心后未变清，加热后混浊度更明显，可见脂肪微粒。该尿液混浊的原因最可能是？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "草酸钙结晶",
      "磷酸盐结晶",
      "蛋白质",
      "脓细胞",
      "乳糜尿",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "乳糜尿",
        "尿呈乳白色、离心不清、加热后更混浊并可见脂肪微粒，符合乳糜尿（淋巴回流受阻）；血嗜酸性粒细胞增高提示丝虫感染可能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a2-005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男性，18 岁。发热 1 周后出现眼睑及双下肢水肿、尿少；尿常规：WBC(++/HPF)，RBC(+/HPF)，尿蛋白(+++)，可见颗粒管型。该病人的蛋白尿类型是？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "生理性蛋白尿",
      "假性蛋白尿",
      "病理性蛋白尿",
      "体位性蛋白尿",
      "肾前性蛋白尿",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "病理性蛋白尿",
        "发热后出现水肿、明显蛋白尿伴红细胞与颗粒管型，提示肾脏器质性病变所致的病理性蛋白尿。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a2-006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "女性，35 岁。发热 3 天来院，主诉尿频、尿急，皮肤黏膜无水肿；尿检 WBC(+++/HPF)，RBC(++/HPF)，尿蛋白(+)，未见管型。最可能的诊断是？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "慢性肾炎",
      "急性尿道炎",
      "肾病综合征",
      "糖尿病性肾病",
      "狼疮性肾病",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "急性尿道炎",
        "尿频尿急伴白细胞、红细胞增多而未见管型，水肿不明显，最符合急性尿道炎等泌尿道感染表现。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a2-007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "女性，26 岁。近日发现“红色尿”就诊；尿检 RBC(++++/HPF)，WBC(+/HPF)，蛋白(++)；红细胞形态完整、未见红细胞碎片，未见管型。该病人的血尿可能为？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "非肾源性血尿",
      "混合性血尿",
      "肾小球性血尿",
      "非均一性红细胞血尿",
      "肾、输尿管性血尿",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "非肾源性血尿",
        "红细胞形态完整、未见碎片及管型，提示红细胞多来自尿路而非肾小球，符合非肾源性（非肾小球性）血尿。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a2-008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "患儿男，8 岁。发热、无咳嗽，腹泻、腹痛就诊；血 WBC 15.3×10⁹/L，中性粒细胞 72%；粪便检查：黏液脓性便，便中带血，镜下 WBC(++++/HPF)，RBC(++/HPF)，未见寄生虫及虫卵。最可能的是？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "细菌性痢疾",
      "阿米巴痢疾",
      "霍乱",
      "肠伤寒",
      "胃肠炎",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细菌性痢疾",
        "黏液脓血便、白细胞满视野且未查到阿米巴等，伴发热，最符合细菌性痢疾。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a2-009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男性，76 岁。间歇性低热，无咳嗽，体质衰弱、消瘦、食欲正常，呈贫血貌，偶有腹部隐痛；血 WBC 5.3×10⁹/L，中性粒细胞 62%，Hb 89g/L，RBC 3.05×10¹²/L，血沉增快；大便次数增多，粪便镜检未见寄生虫及虫卵，粪便隐血试验长期连续阳性。最可能的是？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "消化道溃疡",
      "胃出血",
      "十二指肠球部出血",
      "消化道恶性肿瘤",
      "痔疮出血",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "消化道恶性肿瘤",
        "老年患者长期持续粪便隐血阳性、隐匿消化道出血致贫血、消瘦，最需警惕消化道恶性肿瘤。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a2-010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男性，28 岁。腹泻、便血、腹痛半年；血 WBC 15.3×10⁹/L，中性粒细胞 72%；粪便：脓性黏液便，血中带脓，有腥臭味，镜下 WBC(++/HPF)，RBC(++++/HPF)，偶见夏科-莱登结晶，未见寄生虫及虫卵。最可能的是？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "细菌性痢疾",
      "阿米巴痢疾",
      "霍乱",
      "肠伤寒",
      "胃肠炎",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阿米巴痢疾",
        "病程迁延半年、脓性黏液便中带血伴腥臭味、红细胞多于白细胞并见夏科-莱登结晶，且未查到寄生虫及虫卵，最符合阿米巴痢疾。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a2-011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男性，48 岁。头痛、发热入院；脑脊液呈毛玻璃样，蛋白质浓度增高但不明显，葡萄糖减少，氯化物明显减少，ADA（腺苷脱氨酶）明显增高。最可能的诊断是？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "结核性脑膜炎",
      "蛛网膜下腔出血",
      "化脓性脑膜炎",
      "新型隐球菌脑膜炎",
      "脑型血吸虫病",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结核性脑膜炎",
        "脑脊液毛玻璃样、氯化物明显减少、蛋白增高不明显、ADA 明显增高符合结核性脑膜炎特点。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-a2-012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男性，39 岁。头痛、呕吐、意识障碍入院；脑脊液检查：外观混浊，蛋白质 1000 mg/L，葡萄糖 0.5 mmol/L，细胞总数 3000×10⁶/L，中性粒细胞占 96%。应首先考虑的诊断为？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "椎管梗阻",
      "蛛网膜下腔出血",
      "病毒性脑膜炎",
      "化脓性脑膜炎",
      "结核性脑膜炎",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "化脓性脑膜炎",
        "脑脊液混浊、蛋白明显增高、糖明显降低、细胞总数显著增高以中性粒细胞为主，符合化脓性脑膜炎。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 问答题（short-answer） */
const shortAnswerItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：尿管型（管型）形成的条件是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "尿管型形成的条件",
        "管型的形成需具备 4 个条件：①原尿中有清蛋白、T-H 蛋白增多，作为构成管型的基质；②肾小管有浓缩和酸化尿液的能力，浓缩使成管蛋白浓度增高，酸化促进蛋白质进一步变性凝聚；③尿流缓慢，造成局部性尿液淤积，有足够停留时间使各成分凝聚；④具有可供交替使用的肾单位，利于管型的形成与排泄——处于休息状态肾单位的尿液淤积、有足够时间形成管型，当该肾单位重新排尿时管型随尿排出。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：尿液 hCG 检查的目的是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "尿液 hCG 检查的目的",
        "尿液 hCG 检查的目的包括：①诊断早孕；②监测孕早期反应（异位妊娠、流产等）；③监测滋养层肿瘤；④作为 Down 综合征三联试验的诊断指标之一。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：尿液检测的目的是什么？其有哪些局限性？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "尿液检测的目的与局限",
        "目的：①协助泌尿系统疾病的诊断、病情观察和疗效观察；②协助其他系统疾病的诊断；③职业病防治；④用药的监护；⑤健康人群的普查。局限性：①检查结果易受饮食影响；②尿液各种成分变异和波动范围大；③易被污染；④与其他成分相互干扰。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述粪便隐血试验（FOBT）的临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "粪便隐血试验的临床意义",
        "①FOBT 是粪便检查最常用的筛查项目，可作为消化道恶性肿瘤普查的一种筛查指标，其连续检查对早期发现结肠癌、胃癌等恶性肿瘤有重要价值；②当 FOBT 阳性时应及时检查出血源，若未查到出血源则可能为假阳性，应于 3～6 个月后重新检查，直至查到出血源或排除出血；③FOBT 简便、价廉、对病人无危害，建议对 50 岁以上人群每年或两年做一次愈创木脂法 FOBT 筛查；由于部分胃肠道出血呈间歇性，为降低误诊率，须对同一病人的不同标本检查 3～6 次。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：当粪便隐血试验（FOBT）呈阳性时，应采取哪些方法进一步诊断？其意义是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "FOBT 阳性后的进一步诊断",
        "FOBT 阳性后的进一步诊断方法与意义：①体格检查——局部视诊（寻找痔疮、肛门周围组织或局部病变），肛门指诊（检查是否有息肉）；②实验室检查——肿瘤标志物（筛查消化道肿瘤）；③器械检查——结肠镜（检查良、恶性肿瘤、感染性疾病、憩室炎和血管发育异常等），胃镜（检查胃十二指肠溃疡、肿瘤、裂孔疝或食管静脉曲张），小肠镜（检查腹部疾病、Meckel 憩室炎、血管发育异常等）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：粪便标本采集的注意事项有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "粪便标本采集的注意事项",
        "①标本要新鲜，不得混有尿液、消毒剂和污水等，以免破坏有形成分和病原体；②应选取含黏液、脓液和血液等病理成分的部分，肉眼无异常的粪便可于其表面和深处多部位采集；③及时送检，于标本采集后 1 小时内完成检查，否则可因消化酶、酸碱度变化及细菌作用等因素导致有形成分破坏；④采集容器应清洁、干燥、有盖，不吸水、不渗漏，细菌学检查须采用灭菌有盖容器；⑤任何标本均视为潜在的高危病原菌感染源，采集时应使用合适器具移取标本，避免感染或污染环境。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述痰液量变化的临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "痰液量变化的临床意义",
        "呼吸系统疾病病人痰量增多，可为 50～100 ml/24h，且依病种和病情而异；急性呼吸系统感染较慢性炎症痰量少，病毒感染较细菌感染痰量少。痰量明显增多常见于支气管扩张、肺脓肿、肺水肿、肺空洞性改变和慢性支气管炎，有时甚至超过 100 ml/24h。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：痰液气味变化对临床诊断有一定价值，请简述痰液气味变化的临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "痰液气味变化的临床意义",
        "血腥气味见于各种原因所致的呼吸道出血，如肺癌、肺结核等；粪臭味见于膈下脓肿与肺相通时、肠梗阻、腹膜炎等；特殊臭味见于肺脓肿、晚期肺癌、化脓性支气管炎或支气管扩张等；大蒜味见于砷中毒、有机磷杀虫剂中毒等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：为什么细菌性脑膜炎病人脑脊液氯化物降低？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细菌性脑膜炎脑脊液氯化物降低的原因",
        "①细菌或真菌感染，特别是化脓性、结核性和隐球菌性脑膜炎的急性期及慢性感染的急性发作期，氯化物与葡萄糖同时降低，其中结核性脑膜炎降低最明显——因细菌或真菌分解葡萄糖产生乳酸使脑脊液呈酸性，导致氯化物浓度降低，同时蛋白质增高也引起氯化物减少；②在细菌性脑膜炎后期，脑膜明显炎症浸润或粘连，局部有氯化物附着，使脑脊液氯化物降低，并伴蛋白质明显增高。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：脑脊液葡萄糖浓度降低的原因是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑脊液葡萄糖降低的原因",
        "①细菌或破坏的细胞释放出的葡萄糖分解酶使糖无氧酵解增强；②中枢神经系统代谢紊乱，使血糖向脑脊液转送障碍，导致脑脊液葡萄糖降低。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述脑脊液的生理作用。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑脊液的生理作用",
        "脑脊液的生理作用包括：①保护脑和脊髓免受外力震荡损伤；②调节颅内压的变化；③参与脑组织的物质代谢；④供给脑、脊髓营养物质并排出代谢产物；⑤调节神经系统碱储备，维持正常 pH 等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述脑脊液新鲜性出血与陈旧性出血的鉴别。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "新鲜性出血与陈旧性出血的鉴别",
        "新鲜性出血：外观混浊、易凝；离心后上清液无色透明；红细胞形态无变化；上清液隐血试验多为阴性；白细胞不增高。陈旧性出血：外观清晰透明、不易凝；离心后上清液呈红色、黄褐色或柠檬色；红细胞皱缩；隐血试验阳性；白细胞继发性或反应性增高。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：什么是中间型积液？其形成的原因有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中间型积液及其形成原因",
        "有些浆膜腔积液既有渗出液特点又有漏出液性质，称为“中间型积液”。其形成原因：①漏出液继发感染；②漏出液长期滞留于浆膜腔，致使积液浓缩；③漏出液混有大量血液。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述不同浆膜腔积液的原因。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "不同浆膜腔积液的原因",
        "胸腔积液主要病因为结核性胸膜炎和恶性肿瘤，且有以恶性肿瘤为主的发展趋势；腹腔积液主要病因为肝硬化、肿瘤和结核性腹膜炎等，占 90% 以上；心包积液主要病因为结核性、非特异性和肿瘤性，结核性仍占首位但呈逐年降低趋势，而肿瘤性呈逐年上升趋势。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short015",
    order: 15,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：浆膜腔积液检查的适应证有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "浆膜腔积液检查的适应证",
        "浆膜腔积液检查的适应证：①新发生的浆膜腔积液；②已有浆膜腔积液且突然增多或伴有发热者；③需进行诊断性或治疗性穿刺者。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short016",
    order: 16,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述子宫颈（阴道）脱落细胞学检查的目的。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "子宫颈（阴道）脱落细胞学检查的目的",
        "①子宫颈癌的筛查、早期诊断、疗效观察和预后判断；②良性病变的诊断与鉴别诊断；③了解卵巢功能，评估雌激素水平。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short017",
    order: 17,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述阴道清洁度的临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阴道清洁度的临床意义",
        "阴道清洁度是判断阴道炎症和生育期妇女卵巢功能的指标。①与女性激素周期变化有关：排卵前期雌激素水平逐渐增高，阴道上皮增生、糖原增多、阴道杆菌随之繁殖、pH 下降、杂菌消失，阴道趋于清洁；当卵巢功能不足（如经前及绝经后）时出现相反结果，易感染杂菌，导致阴道不清洁。②用于诊断阴道炎：Ⅲ度提示阴道炎、子宫颈炎等；Ⅳ度提示炎症加重，如滴虫性阴道炎、淋球菌性阴道炎、细菌性阴道病等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short018",
    order: 18,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：精液检查的目的是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "精液检查的目的",
        "①评价男性生殖力，检查男性不育症的原因及疗效观察；②辅助诊断男性生殖系统疾病，如炎症、结核、肿瘤等；③法医学鉴定；④婚前检查；⑤为人类精子库和人工授精筛选优质精子。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short019",
    order: 19,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt:
      "问答题：简述受精与精子活动率、活动力的关系，以及精子活动率和活动力降低的常见原因。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "受精与精子活动率、活动力的关系及降低原因",
        "受精与精子活动率、活动力密切相关；活动力低下的精子难以抵达输卵管与卵子结合完成受精，且精子活动率降低常伴活动力低下。精子活动率小于 40% 且活动力低下，为男性不育症的主要原因之一。常见原因：①精索静脉曲张，因血流不畅导致阴囊温度增高及睾丸组织缺氧和 CO₂ 蓄积，使精子活动力降低；②生殖系统感染；③应用某些抗代谢药物、抗疟药、雌激素等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short020",
    order: 20,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：前列腺液检查的主要目的是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前列腺液检查的主要目的",
        "前列腺液检查主要用于前列腺的炎症、结石、结核和肿瘤的辅助诊断，也可用于性传播疾病的诊断等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-lab-bodyfluids-sup-short021",
    order: 21,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：前列腺炎病人的前列腺液有什么变化？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前列腺炎的前列腺液变化",
        "前列腺炎的诊断依靠前列腺液的显微镜检查和微生物学检查。白细胞增多、前列腺颗粒细胞增多和磷脂酰胆碱小体减少是前列腺炎的特点。细菌性前列腺炎可有特异性 IgA、IgG 抗体增高，可维持 6～12 个月；急性或慢性细菌性前列腺炎可见大肠埃希菌。非细菌性前列腺炎的发生率为细菌性前列腺炎的 8 倍。前列腺液 pH 增高（如增高至 7.7～8.0 以上）对诊断慢性前列腺炎有参考价值，治疗好转后前列腺液 pH 也恢复正常。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

// ================= B1 共用备选答案配伍题（24 组、48 成员） =================

const bGroups: readonly AssessmentItemGroupDefinition[] = [
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...a1SupplementItems,
  ...a2Items,
  ...shortAnswerItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];