import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 诊断学 学习指导与习题集（第4版）— 第四章 颈部检查 题库提取
 * 来源：《诊断学学习指导与习题集》第4版（人民卫生出版社，主编：万学红、卢雪峰）
 *
 * == 统计报告 ==
 * - 名词解释：4 题
 * - A1 型题（单句型最佳选择题）：9 题
 * - A2 型题（病例型最佳选择题）：4 题
 * - 问答题（简答）：5 题
 * - B 型配伍题（共用备选答案）：2 组、共 10 个成员
 * - 独立题合计：22 题（不含 B 型组成员）
 * - 缺失答案：0 题
 * - 无法提取：0 题
 * - 说明：原书含少量排版乱码（如“唇发生甘”应为“口唇发绀”、“下顿骨/下颁角”应为“下颌骨/下颌角”、“额下”应为“颏下”、罗马数字“皿度”应为“III 度”等），已按医学语义恢复为主题所指内容；所有题目均做轻度改写并重排选项，数值与临床细节保留原值。
 *
 * 解析内容位于 answer.content 数组的第二个元素。
 */

const topic = "neck";
const chapterLabel = "第四章";
const locatorBase =
  "《诊断学学习指导与习题集》第4版 第四章 颈部检查 习题（PDF 第132–136页）";
const promptNote =
  "题干改写；原题来自用户提供的题集，未经第三方授权审核";
const answerNotice =
  "答案依据上传题集整理并改写，尚未与权威教材交叉核对";

const kp = `kp-diagnosis-${topic}`;

/** 名词解释（term） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-neck-ch4-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：颈前三角与颈后三角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈前三角与颈后三角",
        "颈前三角为胸锁乳突肌的内缘、下颌骨下缘与前正中线之间的区域；颈后三角为胸锁乳突肌的后缘、锁骨上缘与斜方肌前缘之间的区域。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肝颈静脉回流征",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝颈静脉回流征",
        "当右心衰竭引起肝淤血肿大时，用手压迫肝脏可使颈静脉怒张更加明显，称为肝颈静脉回流征阳性。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：Oliver 征",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Oliver 征",
        "主动脉弓动脉瘤时，由于心脏收缩时瘤体膨大将气管压向后下，因而每随心脏搏动可以触到气管的向下拽动。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：颈静脉怒张",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈静脉怒张",
        "正常人立位或坐位时颈外静脉常不显露，平卧时可稍见充盈，充盈的水平仅限于锁骨上缘至下颌角距离的下 2/3 以内。若取 30°～45° 的半卧位时颈静脉充盈度超过正常水平，称为颈静脉怒张。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1 型题（a1-single），选项已随机重排，correctChoiceIndex 指向新顺序 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-neck-ch4-a1001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列疾病中，最容易发生颈静脉怒张的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "慢性缩窄性心包炎",
      "急性左心衰竭",
      "胸腔积液",
      "肝硬化",
      "急性广泛前壁心肌梗死",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "慢性缩窄性心包炎",
        "缩窄性心包炎使心包增厚缩窄、心室舒张充盈受限，致体循环静脉淤血，最易引起颈静脉怒张。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-a1002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "甲状腺肿大超过胸锁乳突肌外缘，则应将其称为哪种分度？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["II 度肿大", "I 度肿大", "III 度肿大", "V 度肿大", "IV 度肿大"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "III 度肿大",
        "甲状腺肿大分为三度，超过胸锁乳突肌外缘者为 III 度肿大。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-a1003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "成年男性与女性颈部外形较为明显的区别是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "男性颈部直立，两侧对称",
      "男性静坐时颈部血管可显露",
      "男性甲状软骨较突出",
      "男性颈部较细长",
      "男性转头时可见胸锁乳突肌突出",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "男性甲状软骨较突出",
        "成年男性甲状软骨向前突出形成喉结，与女性颈部外形相比，此为其较明显的区别。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-a1004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在肿大的甲状腺与其他颈前包块的鉴别中，最重要的是哪一项依据？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "甲状腺可随吞咽动作向上移动",
      "甲状腺表面光滑",
      "甲状腺肿大，质地不太硬",
      "甲状腺位于甲状软骨下方",
      "甲状腺肿大的程度多在胸锁乳突肌以内",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甲状腺可随吞咽动作向上移动",
        "甲状腺因与喉部软骨相连，可随吞咽动作向上移动，这是将其与其他颈前包块相鉴别的最重要特征。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-a1005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "诊断甲状腺功能亢进的特征性改变是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "甲状腺可随吞咽动作上下移动",
      "触诊有震颤或听诊能听到血管杂音",
      "甲状腺质地较柔软",
      "甲状腺出现结节改变",
      "甲状腺弥漫、对称肿大",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "触诊有震颤或听诊能听到血管杂音",
        "甲状腺触诊有震颤或听诊闻及「嗡鸣」样血管杂音，为甲状腺功能亢进的特征性改变。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-a1006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可借以鉴别桥本甲状腺炎与甲状腺癌的要点是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "甲状腺是否有血管杂音",
      "甲状腺是否为结节状",
      "是否伴有颈总动脉搏动",
      "甲状腺的大小",
      "甲状腺的质地",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "是否伴有颈总动脉搏动",
        "桥本甲状腺炎肿大的甲状腺常仍能触及颈总动脉搏动，甲状腺癌因肿瘤推移遮盖常致颈总动脉搏动摸不到，故可借此鉴别两者。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-a1007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于颈静脉的检查，下列叙述错误的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "颈静脉怒张一般不会见于右心衰竭",
      "颈静脉怒张可见于心包积液",
      "正常人立位或坐位时颈外静脉常不显露",
      "若取 30°～45° 的半卧位时颈静脉充盈度超过正常水平，称为颈静脉怒张",
      "正常人平卧时稍见充盈，充盈水平仅限于锁骨上缘至下颌角距离的下 2/3 以内",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈静脉怒张一般不会见于右心衰竭",
        "右心衰竭致体循环静脉淤血，正是引起颈静脉怒张的常见原因，故「一般不会见于右心衰竭」的说法错误。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-a1008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "判断颈部包块的性质，下列叙述错误的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "淋巴结肿大，质地较硬，且伴有纵隔、胸腔或腹腔病变的症状或体征，应诊断为淋巴结结核",
      "若颈部包块弹性大又无全身症状，应考虑囊肿的可能",
      "淋巴结肿大，质地不硬，有轻度压痛时，可能为非特异性淋巴结炎",
      "颈部包块为边界欠清，质硬，不活动，可能为转移癌",
      "除颈部淋巴结肿大外，还有全身性、无痛性淋巴结肿大，可见于淋巴瘤",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "淋巴结肿大，质地较硬，且伴有纵隔、胸腔或腹腔病变的症状或体征，应诊断为淋巴结结核",
        "淋巴结质地较硬并伴纵隔、胸腔或腹腔病变者，常提示转移性恶性肿瘤，不能据此一律诊断为淋巴结结核，故该说法错误。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-a1009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于颈部的姿势与运动，下列叙述错误的是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "先天性斜颈者，健侧胸锁乳突肌粗短",
      "正常人坐位时颈部直立，伸屈、转动自如",
      "头不能抬起见于严重消耗性疾病晚期",
      "斜颈可见于颈肌外伤",
      "颈部强直为脑膜受刺激的特征",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "先天性斜颈者，健侧胸锁乳突肌粗短",
        "先天性斜颈者病变侧（患侧）胸锁乳突肌粗短、挛缩使头偏向患侧，故「健侧胸锁乳突肌粗短」的说法错误。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A2 型题（病案型最佳选择题，questionKind 亦为 a1-single），选项已随机重排 */
const a2Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-neck-ch4-a2001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "一小儿玩耍时突然烦躁不安、口唇发绀，呈吸气性呼吸困难，并出现「三凹征」。该情况最可能的原因是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "气管异物",
      "自发性气胸",
      "急性支气管炎",
      "大量胸腔积液",
      "呼吸衰竭",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "气管异物",
        "小儿玩耍时突发发绀、吸气性呼吸困难伴三凹征，提示气管异物等引起的急性上气道梗阻。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-a2002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "女性，37 岁，患风心病二尖瓣狭窄，1 周前感冒后出现呼吸困难、咳嗽、水肿，查体可见颈静脉怒张。该病人最可能发生了下列哪种情况？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "上腔静脉阻塞",
      "右心衰竭",
      "主动脉瓣关闭不全",
      "左心衰竭",
      "下腔静脉阻塞",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "右心衰竭",
        "二尖瓣狭窄以左心受累为主，病程进展可继发右心衰竭；在呼吸困难、咳嗽、水肿基础上出现颈静脉怒张，提示右心衰竭、体循环淤血。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-a2003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男性，38 岁，3 年前患结核性渗出性心包炎，近 1～2 个月来呼吸困难、腹胀、水肿，X 线示左、右心缘变直及心包钙化。该病人最可能出现的体征是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "颈动脉搏动增强",
      "颈静脉怒张",
      "颈静脉塌陷",
      "颈部血管杂音",
      "颈动脉搏动消失",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈静脉怒张",
        "心包钙化提示缩窄性心包炎，其舒张期充盈受限致体循环淤血，故最可能出现颈静脉怒张。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-a2004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "女性，35 岁，多食、多汗、消瘦、心悸半年，查体见眼球突出、心率增快。该病人颈部检查最可能出现的体征是哪一项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "甲状腺肿大有结节感，不规则、质地硬",
      "甲状腺肿大，质地柔软，触诊有震颤，听诊闻及「嗡鸣」样血管杂音",
      "Oliver 征",
      "颈静脉怒张",
      "甲状腺结节性肿大，无震颤和杂音",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甲状腺肿大，质地柔软，触诊有震颤，听诊闻及「嗡鸣」样血管杂音",
        "多食、多汗、消瘦、心悸伴突眼、心率增快为甲状腺功能亢进表现，其最常见颈部体征为质地柔软、有震颤并闻及血管杂音的甲状腺肿大。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 问答题（short-answer） */
const shortAnswerItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-neck-ch4-sa001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述甲状腺的检查方法。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甲状腺的检查包括视诊、触诊与听诊：（1）视诊：观察甲状腺的大小及对称性，嘱被检查者做吞咽动作，可见甲状腺随吞咽动作向上移动；不易辨认时嘱被检查者两手放于枕后、头向后仰再观察。（2）触诊：包括峡部与侧叶。峡部检查：检查者站于受检查者前面用拇指、或站于后面用示指，从胸骨上切迹向上触摸，感到气管前软组织并判断有无增厚，嘱吞咽可见其下滑动，判断有无增大和肿块。侧叶检查分前面触诊与后面触诊：前面触诊时一手拇指施压一侧甲状软骨将气管推向对侧，另一手示、中指在对侧胸锁乳突肌后缘由后向前推挤甲状腺侧叶，拇指在其前缘触诊，配合吞咽重复检查；后面触诊时一手的中、示指压一侧甲状软骨将气管推向对侧，另一手拇指在对侧胸锁乳突肌后缘向前推挤甲状腺，示、中指在其前缘触诊，配合吞咽重复检查。两侧分别完成。（3）听诊：触到甲状腺肿大时，将钟型听诊器直接放于肿大的甲状腺上，如听到低调连续性静脉「嗡鸣」音，对诊断甲状腺功能亢进症很有帮助；弥漫性甲状腺肿伴功能亢进者还可听到收缩期动脉杂音。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-sa002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述甲状腺肿大的分度。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甲状腺肿大可分为三度：I 度——不能看出肿大但能触及者；II 度——能看到肿大又能触及，但在胸锁乳突肌以内者；III 度——超过胸锁乳突肌外缘者。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-sa003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述气管移位的检查方法及其临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "检查时让病人取舒适坐位或仰卧位，使颈部处于自然正中位置，医师将示指与环指分别置于两侧胸锁关节上，再将中指置于气管之上，观察中指是否位于示指与环指中间；或以中指置于气管与两侧胸锁乳突肌之间的间隙，据两侧间隙是否等宽判断气管有无偏移。根据气管偏移方向判断病变性质：大量胸腔积液、积气、纵隔肿瘤及单侧甲状腺肿大可将气管推向健侧；而肺不张、肺硬化、胸膜粘连可将气管拉向患侧。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-sa004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "颈部淋巴结肿大见于哪些疾病？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈部淋巴结肿大见于：①急、慢性颈淋巴结炎；②颈淋巴结结核；③艾滋病性颈淋巴结肿大；④淋巴瘤；⑤转移性恶性肿瘤。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-sa005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "甲状腺肿大见于哪些疾病？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甲状腺肿大见于：①甲状腺功能亢进；②单纯性甲状腺肿；③甲状腺癌；④慢性淋巴性甲状腺炎（桥本甲状腺炎）；⑤甲状旁腺腺瘤。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 型配伍题（共用备选答案，members 无 choices，correctChoiceIndex 指向 sharedChoices 下标） */

// 第 1 组：1–5 题共用备选答案
const b001SharedChoices = [
  "颈静脉搏动",
  "颈动脉异常搏动",
  "随吞咽移动的颈前区肿物",
  "颌下和颏下明显红肿",
  "颈部淋巴结肿大、质中、无压痛",
];

const b001Members: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-neck-ch4-b001m1",
    order: 1,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "甲状腺肿大",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "随吞咽移动的颈前区肿物",
        "甲状腺随吞咽动作向上移动，故甲状腺肿大表现为随吞咽移动的颈前区肿物。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-b001m2",
    order: 2,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "主动脉瓣关闭不全",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈动脉异常搏动",
        "主动脉瓣关闭不全时血液反流，收缩压高、舒张压低、脉压增大，可见颈动脉异常搏动。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-b001m3",
    order: 3,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "三尖瓣关闭不全",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈静脉搏动",
        "三尖瓣关闭不全时收缩期血液经关闭不全的三尖瓣反流至右房并传至颈静脉，可出现明显的颈静脉搏动。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-b001m4",
    order: 4,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "淋巴结结核",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈部淋巴结肿大、质中、无压痛",
        "淋巴结结核常表现为颈部淋巴结肿大，质地中等、无明显压痛。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-b001m5",
    order: 5,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "颌下间隙蜂窝织炎",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颌下和颏下明显红肿",
        "颌下间隙蜂窝织炎常表现为颌下、颏下区域明显红肿。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

// 第 2 组：6–10 题共用备选答案
const b002SharedChoices = [
  "甲状腺癌",
  "甲状旁腺腺瘤",
  "甲状腺功能亢进",
  "单纯性甲状腺肿",
  "桥本甲状腺炎",
];

const b002Members: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-diagnosis-neck-ch4-b002m1",
    order: 1,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt:
      "肿大的甲状腺质地柔软，触诊时可有震颤，或能听到「嗡鸣」样血管杂音",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甲状腺功能亢进",
        "甲状腺质地柔软、有震颤并闻及血管杂音，为甲状腺功能亢进的特征性表现。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-b002m2",
    order: 2,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "腺体肿大很突出，可为弥漫性，也可为结节性，无震颤和杂音",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单纯性甲状腺肿",
        "单纯性甲状腺肿可呈弥漫性或结节性肿大，腺体肿大较突出但无震颤和杂音。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-b002m3",
    order: 3,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "肿大的甲状腺有结节感，不规则、质地硬",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甲状腺癌",
        "甲状腺有结节感、不规则、质地硬，符合甲状腺癌的触诊特点。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-b002m4",
    order: 4,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "甲状腺呈弥漫性或结节性肿大，可以触到颈总动脉搏动",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "桥本甲状腺炎",
        "桥本甲状腺炎甲状腺呈弥漫性或结节性肿大，常仍可触到颈总动脉搏动，此点可助鉴别甲状腺癌。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-b002m5",
    order: 5,
    knowledgePointId: kp,
    questionKind: "b1",
    status: "available",
    prompt: "甲状腺突出，有甲状旁腺功能亢进的症状",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甲状旁腺腺瘤",
        "甲状旁腺腺瘤常致腺体肿大突出并出现甲状旁腺功能亢进的症状。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B 型配伍题（b1 共用备选答案） */
const b1Groups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-diagnosis-neck-ch4-b001",
    order: 1,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: b001SharedChoices,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: b001Members,
    sourceIds: [],
  },
  {
    id: "ext-diagnosis-neck-ch4-b002",
    order: 2,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: b002SharedChoices,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: b002Members,
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...a2Items,
  ...shortAnswerItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] =
  b1Groups;