// AUTO-GENERATED by scripts/generate-qb-course.ts — 请勿手改。改动请重跑生成器。
import type { CourseDefinition } from "@/types/learning";
import { buildQbCourseAssessmentData } from "@/lib/qb-course-transform";
import {
  pharmacologyExtractedItems,
  pharmacologyExtractedGroups,
} from "./pharmacology/index"; // 注意：{subject}.ts（现有课程）与 {subject}/（提取目录）同名，显式指向 index

const chapters = [
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch01-introduction",
    "slug": "pharmacology-ch01-introduction",
    "order": 1,
    "indexLabel": "第1章",
    "title": "第1章 药理学总论—绪言",
    "focus": "题库：第1章 药理学总论—绪言（6 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch01-introduction"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch02-pharmacokinetics",
    "slug": "pharmacology-ch02-pharmacokinetics",
    "order": 2,
    "indexLabel": "第2章",
    "title": "第2章 药物代谢动力学",
    "focus": "题库：第2章 药物代谢动力学（37 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch02-pharmacokinetics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch03-pharmacodynamics",
    "slug": "pharmacology-ch03-pharmacodynamics",
    "order": 3,
    "indexLabel": "第3章",
    "title": "第3章 药物效应动力学",
    "focus": "题库：第3章 药物效应动力学（13 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch03-pharmacodynamics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch04-effect-factors",
    "slug": "pharmacology-ch04-effect-factors",
    "order": 4,
    "indexLabel": "第4章",
    "title": "第4章 影响药物效应的因素",
    "focus": "题库：第4章 影响药物效应的因素（8 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch04-effect-factors"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch05-efferent-nervous-system",
    "slug": "pharmacology-ch05-efferent-nervous-system",
    "order": 5,
    "indexLabel": "第5章",
    "title": "第5章 传出神经系统药理概论",
    "focus": "题库：第5章 传出神经系统药理概论（6 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch05-efferent-nervous-system"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch06-cholinergic-agonists",
    "slug": "pharmacology-ch06-cholinergic-agonists",
    "order": 6,
    "indexLabel": "第6章",
    "title": "第6章 胆碱受体激动药",
    "focus": "题库：第6章 胆碱受体激动药（4 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch06-cholinergic-agonists"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch07-anticholinesterases",
    "slug": "pharmacology-ch07-anticholinesterases",
    "order": 7,
    "indexLabel": "第7章",
    "title": "第7章 抗胆碱酯酶药和胆碱酯酶复活药",
    "focus": "题库：第7章 抗胆碱酯酶药和胆碱酯酶复活药（7 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch07-anticholinesterases"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch08-muscarinic-antagonists",
    "slug": "pharmacology-ch08-muscarinic-antagonists",
    "order": 8,
    "indexLabel": "第8章",
    "title": "第8章 胆碱受体阻断药",
    "focus": "题库：第8章 胆碱受体阻断药（7 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch08-muscarinic-antagonists"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch09-nicotinic-antagonists",
    "slug": "pharmacology-ch09-nicotinic-antagonists",
    "order": 9,
    "indexLabel": "第9章",
    "title": "第9章 胆碱受体阻断药",
    "focus": "题库：第9章 胆碱受体阻断药（5 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch09-nicotinic-antagonists"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch10-adrenoceptor-agonists",
    "slug": "pharmacology-ch10-adrenoceptor-agonists",
    "order": 10,
    "indexLabel": "第10章",
    "title": "第10章 肾上腺素受体激动药",
    "focus": "题库：第10章 肾上腺素受体激动药（19 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch10-adrenoceptor-agonists"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch11-adrenoceptor-antagonists",
    "slug": "pharmacology-ch11-adrenoceptor-antagonists",
    "order": 11,
    "indexLabel": "第11章",
    "title": "第11章 肾上腺素受体阻断药",
    "focus": "题库：第11章 肾上腺素受体阻断药（11 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch11-adrenoceptor-antagonists"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch12-cns-pharmacology",
    "slug": "pharmacology-ch12-cns-pharmacology",
    "order": 12,
    "indexLabel": "第12章",
    "title": "第12章 中枢神经系统药理学概论",
    "focus": "题库：第12章 中枢神经系统药理学概论（6 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch12-cns-pharmacology"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch13-general-anesthetics",
    "slug": "pharmacology-ch13-general-anesthetics",
    "order": 13,
    "indexLabel": "第13章",
    "title": "第13章 全身麻醉药",
    "focus": "题库：第13章 全身麻醉药（3 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch13-general-anesthetics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch14-local-anesthetics",
    "slug": "pharmacology-ch14-local-anesthetics",
    "order": 14,
    "indexLabel": "第14章",
    "title": "第14章 局部麻醉药",
    "focus": "题库：第14章 局部麻醉药（10 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch14-local-anesthetics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch15-sedatives-hypnotics",
    "slug": "pharmacology-ch15-sedatives-hypnotics",
    "order": 15,
    "indexLabel": "第15章",
    "title": "第15章 镇静催眠药",
    "focus": "题库：第15章 镇静催眠药（4 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch15-sedatives-hypnotics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch16-antiepileptics",
    "slug": "pharmacology-ch16-antiepileptics",
    "order": 16,
    "indexLabel": "第16章",
    "title": "第16章 抗癫痫药和抗惊厥药",
    "focus": "题库：第16章 抗癫痫药和抗惊厥药（7 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch16-antiepileptics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch17-cns-degenerative-drugs",
    "slug": "pharmacology-ch17-cns-degenerative-drugs",
    "order": 17,
    "indexLabel": "第17章",
    "title": "第17章 治疗中枢神经系统退行性疾病药",
    "focus": "题库：第17章 治疗中枢神经系统退行性疾病药（5 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch17-cns-degenerative-drugs"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch18-antipsychotics",
    "slug": "pharmacology-ch18-antipsychotics",
    "order": 18,
    "indexLabel": "第18章",
    "title": "第18章 抗精神失常药",
    "focus": "题库：第18章 抗精神失常药（13 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch18-antipsychotics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch19-analgesics",
    "slug": "pharmacology-ch19-analgesics",
    "order": 19,
    "indexLabel": "第19章",
    "title": "第19章 镇痛药",
    "focus": "题库：第19章 镇痛药（8 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch19-analgesics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch20-antipyretic-analgesics",
    "slug": "pharmacology-ch20-antipyretic-analgesics",
    "order": 20,
    "indexLabel": "第20章",
    "title": "第20章 解热镇痛抗炎药",
    "focus": "题库：第20章 解热镇痛抗炎药（9 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch20-antipyretic-analgesics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch21-ion-channel-calcium-blockers",
    "slug": "pharmacology-ch21-ion-channel-calcium-blockers",
    "order": 21,
    "indexLabel": "第21章",
    "title": "第21章 离子通道概论及钙通道阻滞药",
    "focus": "题库：第21章 离子通道概论及钙通道阻滞药（7 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch21-ion-channel-calcium-blockers"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch22-antiarrhythmics",
    "slug": "pharmacology-ch22-antiarrhythmics",
    "order": 22,
    "indexLabel": "第22章",
    "title": "第22章 抗心律失常药",
    "focus": "题库：第22章 抗心律失常药（17 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch22-antiarrhythmics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch23-renin-angiotensin-drugs",
    "slug": "pharmacology-ch23-renin-angiotensin-drugs",
    "order": 23,
    "indexLabel": "第23章",
    "title": "第23章 作用于肾素-血管紧张素系统的药物",
    "focus": "题库：第23章 作用于肾素-血管紧张素系统的药物（5 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch23-renin-angiotensin-drugs"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch24-diuretics",
    "slug": "pharmacology-ch24-diuretics",
    "order": 24,
    "indexLabel": "第24章",
    "title": "第24章 利尿药",
    "focus": "题库：第24章 利尿药（16 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch24-diuretics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch25-antihypertensives",
    "slug": "pharmacology-ch25-antihypertensives",
    "order": 25,
    "indexLabel": "第25章",
    "title": "第25章 抗高血压药",
    "focus": "题库：第25章 抗高血压药（9 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch25-antihypertensives"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch26-heart-failure-drugs",
    "slug": "pharmacology-ch26-heart-failure-drugs",
    "order": 26,
    "indexLabel": "第26章",
    "title": "第26章 治疗心力衰竭的药物",
    "focus": "题库：第26章 治疗心力衰竭的药物（32 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch26-heart-failure-drugs"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch27-lipid-lowering-drugs",
    "slug": "pharmacology-ch27-lipid-lowering-drugs",
    "order": 27,
    "indexLabel": "第27章",
    "title": "第27章 调血脂药与抗动脉粥样硬化药",
    "focus": "题库：第27章 调血脂药与抗动脉粥样硬化药（12 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch27-lipid-lowering-drugs"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch28-antianginal-drugs",
    "slug": "pharmacology-ch28-antianginal-drugs",
    "order": 28,
    "indexLabel": "第28章",
    "title": "第28章 抗心绞痛药",
    "focus": "题库：第28章 抗心绞痛药（12 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch28-antianginal-drugs"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch29-blood-hematopoietic-drugs",
    "slug": "pharmacology-ch29-blood-hematopoietic-drugs",
    "order": 29,
    "indexLabel": "第29章",
    "title": "第29章 作用于血液及造血系统的药物",
    "focus": "题库：第29章 作用于血液及造血系统的药物（16 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch29-blood-hematopoietic-drugs"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch30-autacoids",
    "slug": "pharmacology-ch30-autacoids",
    "order": 30,
    "indexLabel": "第30章",
    "title": "第30章 影响自体活性物质的药物",
    "focus": "题库：第30章 影响自体活性物质的药物（5 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch30-autacoids"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch31-respiratory-drugs",
    "slug": "pharmacology-ch31-respiratory-drugs",
    "order": 31,
    "indexLabel": "第31章",
    "title": "第31章 作用于呼吸系统的药物",
    "focus": "题库：第31章 作用于呼吸系统的药物（10 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch31-respiratory-drugs"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch32-gastrointestinal-drugs",
    "slug": "pharmacology-ch32-gastrointestinal-drugs",
    "order": 32,
    "indexLabel": "第32章",
    "title": "第32章 作用于消化系统的药物",
    "focus": "题库：第32章 作用于消化系统的药物（8 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch32-gastrointestinal-drugs"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch33-uterine-drugs",
    "slug": "pharmacology-ch33-uterine-drugs",
    "order": 33,
    "indexLabel": "第33章",
    "title": "第33章 子宫平滑肌兴奋药和抑制药",
    "focus": "题库：第33章 子宫平滑肌兴奋药和抑制药（8 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch33-uterine-drugs"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch34-sex-hormone-contraceptives",
    "slug": "pharmacology-ch34-sex-hormone-contraceptives",
    "order": 34,
    "indexLabel": "第34章",
    "title": "第34章 性激素类药及避孕药",
    "focus": "题库：第34章 性激素类药及避孕药（7 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch34-sex-hormone-contraceptives"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch35-adrenocortical-hormones",
    "slug": "pharmacology-ch35-adrenocortical-hormones",
    "order": 35,
    "indexLabel": "第35章",
    "title": "第35章 肾上腺皮质激素类药物",
    "focus": "题库：第35章 肾上腺皮质激素类药物（10 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch35-adrenocortical-hormones"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch36-thyroid-hormones-antithyroid",
    "slug": "pharmacology-ch36-thyroid-hormones-antithyroid",
    "order": 36,
    "indexLabel": "第36章",
    "title": "第36章 甲状腺激素及抗甲状腺药",
    "focus": "题库：第36章 甲状腺激素及抗甲状腺药（9 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch36-thyroid-hormones-antithyroid"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch37-insulin-antidiabetics",
    "slug": "pharmacology-ch37-insulin-antidiabetics",
    "order": 37,
    "indexLabel": "第37章",
    "title": "第37章 胰岛素及其他降血糖药",
    "focus": "题库：第37章 胰岛素及其他降血糖药（11 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch37-insulin-antidiabetics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch38-antiosteoporosis-drugs",
    "slug": "pharmacology-ch38-antiosteoporosis-drugs",
    "order": 38,
    "indexLabel": "第38章",
    "title": "第38章 抗骨质疏松药",
    "focus": "题库：第38章 抗骨质疏松药（11 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch38-antiosteoporosis-drugs"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch39-antimicrobial-overview",
    "slug": "pharmacology-ch39-antimicrobial-overview",
    "order": 39,
    "indexLabel": "第39章",
    "title": "第39章 抗菌药物概述",
    "focus": "题库：第39章 抗菌药物概述（8 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch39-antimicrobial-overview"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch40-beta-lactam-antibiotics",
    "slug": "pharmacology-ch40-beta-lactam-antibiotics",
    "order": 40,
    "indexLabel": "第40章",
    "title": "第40章 β-内酰胺类抗生素",
    "focus": "题库：第40章 β-内酰胺类抗生素（14 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch40-beta-lactam-antibiotics"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch41-macrolides-lincosamides-polypeptides",
    "slug": "pharmacology-ch41-macrolides-lincosamides-polypeptides",
    "order": 41,
    "indexLabel": "第41章",
    "title": "第41章 大环内酯类、林可霉素类及多肽类抗生素",
    "focus": "题库：第41章 大环内酯类、林可霉素类及多肽类抗生素（7 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch41-macrolides-lincosamides-polypeptides"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch42-aminoglycosides",
    "slug": "pharmacology-ch42-aminoglycosides",
    "order": 42,
    "indexLabel": "第42章",
    "title": "第42章 氨基苷类抗生素",
    "focus": "题库：第42章 氨基苷类抗生素（11 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch42-aminoglycosides"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch43-tetracyclines-chloramphenicol",
    "slug": "pharmacology-ch43-tetracyclines-chloramphenicol",
    "order": 43,
    "indexLabel": "第43章",
    "title": "第43章 四环素类及氯霉素类",
    "focus": "题库：第43章 四环素类及氯霉素类（9 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch43-tetracyclines-chloramphenicol"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch44-synthetic-antimicrobials",
    "slug": "pharmacology-ch44-synthetic-antimicrobials",
    "order": 44,
    "indexLabel": "第44章",
    "title": "第44章 人工合成抗菌药",
    "focus": "题库：第44章 人工合成抗菌药（9 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch44-synthetic-antimicrobials"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch45-antiviral-antifungal",
    "slug": "pharmacology-ch45-antiviral-antifungal",
    "order": 45,
    "indexLabel": "第45章",
    "title": "第45章 抗病毒药和抗真菌药",
    "focus": "题库：第45章 抗病毒药和抗真菌药（7 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch45-antiviral-antifungal"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch46-antituberculosis-antileprosy",
    "slug": "pharmacology-ch46-antituberculosis-antileprosy",
    "order": 46,
    "indexLabel": "第46章",
    "title": "第46章 抗结核药及抗麻风病药",
    "focus": "题库：第46章 抗结核药及抗麻风病药（11 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch46-antituberculosis-antileprosy"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch47-antiparasitic",
    "slug": "pharmacology-ch47-antiparasitic",
    "order": 47,
    "indexLabel": "第47章",
    "title": "第47章 抗寄生虫药",
    "focus": "题库：第47章 抗寄生虫药（6 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch47-antiparasitic"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch48-antitumor",
    "slug": "pharmacology-ch48-antitumor",
    "order": 48,
    "indexLabel": "第48章",
    "title": "第48章 抗恶性肿瘤药",
    "focus": "题库：第48章 抗恶性肿瘤药（9 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch48-antitumor"
    ]
  },
  {
    "id": "chapter-pharmacology-qb-pharmacology-ch49-immunomodulators",
    "slug": "pharmacology-ch49-immunomodulators",
    "order": 49,
    "indexLabel": "第49章",
    "title": "第49章 影响免疫功能的药物",
    "focus": "题库：第49章 影响免疫功能的药物（11 题）",
    "knowledgePointIds": [
      "kp-pharmacology-ch49-immunomodulators"
    ]
  }
] as const;
const knowledgePoints = [
  {
    "id": "kp-pharmacology-ch01-introduction",
    "slug": "pharmacology-ch01-introduction",
    "order": 1,
    "title": "第1章 药理学总论—绪言",
    "note": "题库章节：第1章 药理学总论—绪言。底稿 6 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch01-introduction-term001",
      "ext-pharmacology-ch01-introduction-term002",
      "ext-pharmacology-ch01-introduction-fill001",
      "ext-pharmacology-ch01-introduction-fill002",
      "ext-pharmacology-ch01-introduction-a1001",
      "ext-pharmacology-ch01-introduction-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch02-pharmacokinetics",
    "slug": "pharmacology-ch02-pharmacokinetics",
    "order": 1,
    "title": "第2章 药物代谢动力学",
    "note": "题库章节：第2章 药物代谢动力学。底稿 37 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch02-pharmacokinetics-term001",
      "ext-pharmacology-ch02-pharmacokinetics-term002",
      "ext-pharmacology-ch02-pharmacokinetics-term003",
      "ext-pharmacology-ch02-pharmacokinetics-term004",
      "ext-pharmacology-ch02-pharmacokinetics-term005",
      "ext-pharmacology-ch02-pharmacokinetics-term006",
      "ext-pharmacology-ch02-pharmacokinetics-term007",
      "ext-pharmacology-ch02-pharmacokinetics-term008",
      "ext-pharmacology-ch02-pharmacokinetics-term009",
      "ext-pharmacology-ch02-pharmacokinetics-term010",
      "ext-pharmacology-ch02-pharmacokinetics-fill001",
      "ext-pharmacology-ch02-pharmacokinetics-fill002",
      "ext-pharmacology-ch02-pharmacokinetics-fill003",
      "ext-pharmacology-ch02-pharmacokinetics-fill004",
      "ext-pharmacology-ch02-pharmacokinetics-fill005",
      "ext-pharmacology-ch02-pharmacokinetics-fill006",
      "ext-pharmacology-ch02-pharmacokinetics-fill007",
      "ext-pharmacology-ch02-pharmacokinetics-fill008",
      "ext-pharmacology-ch02-pharmacokinetics-a1001",
      "ext-pharmacology-ch02-pharmacokinetics-a1002",
      "ext-pharmacology-ch02-pharmacokinetics-a1003",
      "ext-pharmacology-ch02-pharmacokinetics-a1004",
      "ext-pharmacology-ch02-pharmacokinetics-a1005",
      "ext-pharmacology-ch02-pharmacokinetics-a1006",
      "ext-pharmacology-ch02-pharmacokinetics-a1007",
      "ext-pharmacology-ch02-pharmacokinetics-a1008",
      "ext-pharmacology-ch02-pharmacokinetics-a1009",
      "ext-pharmacology-ch02-pharmacokinetics-a1010",
      "ext-pharmacology-ch02-pharmacokinetics-a1011",
      "ext-pharmacology-ch02-pharmacokinetics-a1012",
      "ext-pharmacology-ch02-pharmacokinetics-a1013",
      "ext-pharmacology-ch02-pharmacokinetics-a1014",
      "ext-pharmacology-ch02-pharmacokinetics-a1015",
      "ext-pharmacology-ch02-pharmacokinetics-short001",
      "ext-pharmacology-ch02-pharmacokinetics-short002",
      "ext-pharmacology-ch02-pharmacokinetics-short003",
      "ext-pharmacology-ch02-pharmacokinetics-short004"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch03-pharmacodynamics",
    "slug": "pharmacology-ch03-pharmacodynamics",
    "order": 1,
    "title": "第3章 药物效应动力学",
    "note": "题库章节：第3章 药物效应动力学。底稿 13 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch03-pharmacodynamics-term001",
      "ext-pharmacology-ch03-pharmacodynamics-term002",
      "ext-pharmacology-ch03-pharmacodynamics-term003",
      "ext-pharmacology-ch03-pharmacodynamics-term004",
      "ext-pharmacology-ch03-pharmacodynamics-fill001",
      "ext-pharmacology-ch03-pharmacodynamics-fill002",
      "ext-pharmacology-ch03-pharmacodynamics-fill003",
      "ext-pharmacology-ch03-pharmacodynamics-a1001",
      "ext-pharmacology-ch03-pharmacodynamics-a1002",
      "ext-pharmacology-ch03-pharmacodynamics-a1003",
      "ext-pharmacology-ch03-pharmacodynamics-a1004",
      "ext-pharmacology-ch03-pharmacodynamics-short001",
      "ext-pharmacology-ch03-pharmacodynamics-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch04-effect-factors",
    "slug": "pharmacology-ch04-effect-factors",
    "order": 1,
    "title": "第4章 影响药物效应的因素",
    "note": "题库章节：第4章 影响药物效应的因素。底稿 8 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch04-effect-factors-term001",
      "ext-pharmacology-ch04-effect-factors-term002",
      "ext-pharmacology-ch04-effect-factors-term003",
      "ext-pharmacology-ch04-effect-factors-term004",
      "ext-pharmacology-ch04-effect-factors-a1001",
      "ext-pharmacology-ch04-effect-factors-a1002",
      "ext-pharmacology-ch04-effect-factors-short001",
      "ext-pharmacology-ch04-effect-factors-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch05-efferent-nervous-system",
    "slug": "pharmacology-ch05-efferent-nervous-system",
    "order": 1,
    "title": "第5章 传出神经系统药理概论",
    "note": "题库章节：第5章 传出神经系统药理概论。底稿 6 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch05-efferent-nervous-system-term001",
      "ext-pharmacology-ch05-efferent-nervous-system-term002",
      "ext-pharmacology-ch05-efferent-nervous-system-fill001",
      "ext-pharmacology-ch05-efferent-nervous-system-fill002",
      "ext-pharmacology-ch05-efferent-nervous-system-a1001",
      "ext-pharmacology-ch05-efferent-nervous-system-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch06-cholinergic-agonists",
    "slug": "pharmacology-ch06-cholinergic-agonists",
    "order": 1,
    "title": "第6章 胆碱受体激动药",
    "note": "题库章节：第6章 胆碱受体激动药。底稿 4 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch06-cholinergic-agonists-term001",
      "ext-pharmacology-ch06-cholinergic-agonists-fill001",
      "ext-pharmacology-ch06-cholinergic-agonists-a1001",
      "ext-pharmacology-ch06-cholinergic-agonists-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch07-anticholinesterases",
    "slug": "pharmacology-ch07-anticholinesterases",
    "order": 1,
    "title": "第7章 抗胆碱酯酶药和胆碱酯酶复活药",
    "note": "题库章节：第7章 抗胆碱酯酶药和胆碱酯酶复活药。底稿 7 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch07-anticholinesterases-term001",
      "ext-pharmacology-ch07-anticholinesterases-fill001",
      "ext-pharmacology-ch07-anticholinesterases-fill002",
      "ext-pharmacology-ch07-anticholinesterases-a1001",
      "ext-pharmacology-ch07-anticholinesterases-a1002",
      "ext-pharmacology-ch07-anticholinesterases-short001",
      "ext-pharmacology-ch07-anticholinesterases-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch08-muscarinic-antagonists",
    "slug": "pharmacology-ch08-muscarinic-antagonists",
    "order": 1,
    "title": "第8章 胆碱受体阻断药",
    "note": "题库章节：第8章 胆碱受体阻断药。底稿 7 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch08-muscarinic-antagonists-term001",
      "ext-pharmacology-ch08-muscarinic-antagonists-term002",
      "ext-pharmacology-ch08-muscarinic-antagonists-fill001",
      "ext-pharmacology-ch08-muscarinic-antagonists-a1001",
      "ext-pharmacology-ch08-muscarinic-antagonists-a1002",
      "ext-pharmacology-ch08-muscarinic-antagonists-short001",
      "ext-pharmacology-ch08-muscarinic-antagonists-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch09-nicotinic-antagonists",
    "slug": "pharmacology-ch09-nicotinic-antagonists",
    "order": 1,
    "title": "第9章 胆碱受体阻断药",
    "note": "题库章节：第9章 胆碱受体阻断药。底稿 5 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch09-nicotinic-antagonists-term001",
      "ext-pharmacology-ch09-nicotinic-antagonists-term002",
      "ext-pharmacology-ch09-nicotinic-antagonists-fill001",
      "ext-pharmacology-ch09-nicotinic-antagonists-a1001",
      "ext-pharmacology-ch09-nicotinic-antagonists-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch10-adrenoceptor-agonists",
    "slug": "pharmacology-ch10-adrenoceptor-agonists",
    "order": 1,
    "title": "第10章 肾上腺素受体激动药",
    "note": "题库章节：第10章 肾上腺素受体激动药。底稿 19 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch10-adrenoceptor-agonists-term001",
      "ext-pharmacology-ch10-adrenoceptor-agonists-fill001",
      "ext-pharmacology-ch10-adrenoceptor-agonists-fill002",
      "ext-pharmacology-ch10-adrenoceptor-agonists-fill003",
      "ext-pharmacology-ch10-adrenoceptor-agonists-fill004",
      "ext-pharmacology-ch10-adrenoceptor-agonists-a1001",
      "ext-pharmacology-ch10-adrenoceptor-agonists-a1002",
      "ext-pharmacology-ch10-adrenoceptor-agonists-a1003",
      "ext-pharmacology-ch10-adrenoceptor-agonists-a1004",
      "ext-pharmacology-ch10-adrenoceptor-agonists-a1005",
      "ext-pharmacology-ch10-adrenoceptor-agonists-a1006",
      "ext-pharmacology-ch10-adrenoceptor-agonists-a1007",
      "ext-pharmacology-ch10-adrenoceptor-agonists-a1008",
      "ext-pharmacology-ch10-adrenoceptor-agonists-a1009",
      "ext-pharmacology-ch10-adrenoceptor-agonists-a1010",
      "ext-pharmacology-ch10-adrenoceptor-agonists-short001",
      "ext-pharmacology-ch10-adrenoceptor-agonists-short002",
      "ext-pharmacology-ch10-adrenoceptor-agonists-short003",
      "ext-pharmacology-ch10-adrenoceptor-agonists-short004"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch11-adrenoceptor-antagonists",
    "slug": "pharmacology-ch11-adrenoceptor-antagonists",
    "order": 1,
    "title": "第11章 肾上腺素受体阻断药",
    "note": "题库章节：第11章 肾上腺素受体阻断药。底稿 11 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch11-adrenoceptor-antagonists-term001",
      "ext-pharmacology-ch11-adrenoceptor-antagonists-term002",
      "ext-pharmacology-ch11-adrenoceptor-antagonists-fill001",
      "ext-pharmacology-ch11-adrenoceptor-antagonists-fill002",
      "ext-pharmacology-ch11-adrenoceptor-antagonists-a1001",
      "ext-pharmacology-ch11-adrenoceptor-antagonists-a1002",
      "ext-pharmacology-ch11-adrenoceptor-antagonists-a1003",
      "ext-pharmacology-ch11-adrenoceptor-antagonists-a1004",
      "ext-pharmacology-ch11-adrenoceptor-antagonists-short001",
      "ext-pharmacology-ch11-adrenoceptor-antagonists-short002",
      "ext-pharmacology-ch11-adrenoceptor-antagonists-short003"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch12-cns-pharmacology",
    "slug": "pharmacology-ch12-cns-pharmacology",
    "order": 1,
    "title": "第12章 中枢神经系统药理学概论",
    "note": "题库章节：第12章 中枢神经系统药理学概论。底稿 6 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch12-cns-pharmacology-term001",
      "ext-pharmacology-ch12-cns-pharmacology-fill001",
      "ext-pharmacology-ch12-cns-pharmacology-fill002",
      "ext-pharmacology-ch12-cns-pharmacology-a1001",
      "ext-pharmacology-ch12-cns-pharmacology-a1002",
      "ext-pharmacology-ch12-cns-pharmacology-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch13-general-anesthetics",
    "slug": "pharmacology-ch13-general-anesthetics",
    "order": 1,
    "title": "第13章 全身麻醉药",
    "note": "题库章节：第13章 全身麻醉药。底稿 3 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch13-general-anesthetics-term001",
      "ext-pharmacology-ch13-general-anesthetics-a1001",
      "ext-pharmacology-ch13-general-anesthetics-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch14-local-anesthetics",
    "slug": "pharmacology-ch14-local-anesthetics",
    "order": 1,
    "title": "第14章 局部麻醉药",
    "note": "题库章节：第14章 局部麻醉药。底稿 10 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch14-local-anesthetics-term001",
      "ext-pharmacology-ch14-local-anesthetics-fill001",
      "ext-pharmacology-ch14-local-anesthetics-fill002",
      "ext-pharmacology-ch14-local-anesthetics-fill003",
      "ext-pharmacology-ch14-local-anesthetics-fill004",
      "ext-pharmacology-ch14-local-anesthetics-a1001",
      "ext-pharmacology-ch14-local-anesthetics-a1002",
      "ext-pharmacology-ch14-local-anesthetics-short001",
      "ext-pharmacology-ch14-local-anesthetics-short002",
      "ext-pharmacology-ch14-local-anesthetics-short003"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch15-sedatives-hypnotics",
    "slug": "pharmacology-ch15-sedatives-hypnotics",
    "order": 1,
    "title": "第15章 镇静催眠药",
    "note": "题库章节：第15章 镇静催眠药。底稿 4 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch15-sedatives-hypnotics-term001",
      "ext-pharmacology-ch15-sedatives-hypnotics-a1001",
      "ext-pharmacology-ch15-sedatives-hypnotics-a1002",
      "ext-pharmacology-ch15-sedatives-hypnotics-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch16-antiepileptics",
    "slug": "pharmacology-ch16-antiepileptics",
    "order": 1,
    "title": "第16章 抗癫痫药和抗惊厥药",
    "note": "题库章节：第16章 抗癫痫药和抗惊厥药。底稿 7 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch16-antiepileptics-term001",
      "ext-pharmacology-ch16-antiepileptics-term002",
      "ext-pharmacology-ch16-antiepileptics-fill001",
      "ext-pharmacology-ch16-antiepileptics-fill002",
      "ext-pharmacology-ch16-antiepileptics-a1001",
      "ext-pharmacology-ch16-antiepileptics-a1002",
      "ext-pharmacology-ch16-antiepileptics-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch17-cns-degenerative-drugs",
    "slug": "pharmacology-ch17-cns-degenerative-drugs",
    "order": 1,
    "title": "第17章 治疗中枢神经系统退行性疾病药",
    "note": "题库章节：第17章 治疗中枢神经系统退行性疾病药。底稿 5 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch17-cns-degenerative-drugs-term001",
      "ext-pharmacology-ch17-cns-degenerative-drugs-fill001",
      "ext-pharmacology-ch17-cns-degenerative-drugs-fill002",
      "ext-pharmacology-ch17-cns-degenerative-drugs-a1001",
      "ext-pharmacology-ch17-cns-degenerative-drugs-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch18-antipsychotics",
    "slug": "pharmacology-ch18-antipsychotics",
    "order": 1,
    "title": "第18章 抗精神失常药",
    "note": "题库章节：第18章 抗精神失常药。底稿 13 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch18-antipsychotics-term001",
      "ext-pharmacology-ch18-antipsychotics-term002",
      "ext-pharmacology-ch18-antipsychotics-fill001",
      "ext-pharmacology-ch18-antipsychotics-fill002",
      "ext-pharmacology-ch18-antipsychotics-a1001",
      "ext-pharmacology-ch18-antipsychotics-a1002",
      "ext-pharmacology-ch18-antipsychotics-a1003",
      "ext-pharmacology-ch18-antipsychotics-a1004",
      "ext-pharmacology-ch18-antipsychotics-a1005",
      "ext-pharmacology-ch18-antipsychotics-a1006",
      "ext-pharmacology-ch18-antipsychotics-a1007",
      "ext-pharmacology-ch18-antipsychotics-short001",
      "ext-pharmacology-ch18-antipsychotics-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch19-analgesics",
    "slug": "pharmacology-ch19-analgesics",
    "order": 1,
    "title": "第19章 镇痛药",
    "note": "题库章节：第19章 镇痛药。底稿 8 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch19-analgesics-term001",
      "ext-pharmacology-ch19-analgesics-term002",
      "ext-pharmacology-ch19-analgesics-fill001",
      "ext-pharmacology-ch19-analgesics-fill002",
      "ext-pharmacology-ch19-analgesics-fill003",
      "ext-pharmacology-ch19-analgesics-a1001",
      "ext-pharmacology-ch19-analgesics-a1002",
      "ext-pharmacology-ch19-analgesics-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch20-antipyretic-analgesics",
    "slug": "pharmacology-ch20-antipyretic-analgesics",
    "order": 1,
    "title": "第20章 解热镇痛抗炎药",
    "note": "题库章节：第20章 解热镇痛抗炎药。底稿 9 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch20-antipyretic-analgesics-term001",
      "ext-pharmacology-ch20-antipyretic-analgesics-term002",
      "ext-pharmacology-ch20-antipyretic-analgesics-fill001",
      "ext-pharmacology-ch20-antipyretic-analgesics-fill002",
      "ext-pharmacology-ch20-antipyretic-analgesics-fill003",
      "ext-pharmacology-ch20-antipyretic-analgesics-a1001",
      "ext-pharmacology-ch20-antipyretic-analgesics-short001",
      "ext-pharmacology-ch20-antipyretic-analgesics-short002",
      "ext-pharmacology-ch20-antipyretic-analgesics-short003"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch21-ion-channel-calcium-blockers",
    "slug": "pharmacology-ch21-ion-channel-calcium-blockers",
    "order": 1,
    "title": "第21章 离子通道概论及钙通道阻滞药",
    "note": "题库章节：第21章 离子通道概论及钙通道阻滞药。底稿 7 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch21-ion-channel-calcium-blockers-term001",
      "ext-pharmacology-ch21-ion-channel-calcium-blockers-term002",
      "ext-pharmacology-ch21-ion-channel-calcium-blockers-fill001",
      "ext-pharmacology-ch21-ion-channel-calcium-blockers-a1001",
      "ext-pharmacology-ch21-ion-channel-calcium-blockers-short001",
      "ext-pharmacology-ch21-ion-channel-calcium-blockers-short002",
      "ext-pharmacology-ch21-ion-channel-calcium-blockers-short003"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch22-antiarrhythmics",
    "slug": "pharmacology-ch22-antiarrhythmics",
    "order": 1,
    "title": "第22章 抗心律失常药",
    "note": "题库章节：第22章 抗心律失常药。底稿 17 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch22-antiarrhythmics-term001",
      "ext-pharmacology-ch22-antiarrhythmics-term002",
      "ext-pharmacology-ch22-antiarrhythmics-term003",
      "ext-pharmacology-ch22-antiarrhythmics-fill001",
      "ext-pharmacology-ch22-antiarrhythmics-fill002",
      "ext-pharmacology-ch22-antiarrhythmics-fill003",
      "ext-pharmacology-ch22-antiarrhythmics-fill004",
      "ext-pharmacology-ch22-antiarrhythmics-fill005",
      "ext-pharmacology-ch22-antiarrhythmics-a1001",
      "ext-pharmacology-ch22-antiarrhythmics-a1002",
      "ext-pharmacology-ch22-antiarrhythmics-a1003",
      "ext-pharmacology-ch22-antiarrhythmics-a1004",
      "ext-pharmacology-ch22-antiarrhythmics-short001",
      "ext-pharmacology-ch22-antiarrhythmics-short002",
      "ext-pharmacology-ch22-antiarrhythmics-short003",
      "ext-pharmacology-ch22-antiarrhythmics-short004",
      "ext-pharmacology-ch22-antiarrhythmics-short005"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch23-renin-angiotensin-drugs",
    "slug": "pharmacology-ch23-renin-angiotensin-drugs",
    "order": 1,
    "title": "第23章 作用于肾素-血管紧张素系统的药物",
    "note": "题库章节：第23章 作用于肾素-血管紧张素系统的药物。底稿 5 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch23-renin-angiotensin-drugs-fill001",
      "ext-pharmacology-ch23-renin-angiotensin-drugs-fill002",
      "ext-pharmacology-ch23-renin-angiotensin-drugs-fill003",
      "ext-pharmacology-ch23-renin-angiotensin-drugs-a1001",
      "ext-pharmacology-ch23-renin-angiotensin-drugs-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch24-diuretics",
    "slug": "pharmacology-ch24-diuretics",
    "order": 1,
    "title": "第24章 利尿药",
    "note": "题库章节：第24章 利尿药。底稿 16 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch24-diuretics-term001",
      "ext-pharmacology-ch24-diuretics-term002",
      "ext-pharmacology-ch24-diuretics-term003",
      "ext-pharmacology-ch24-diuretics-term004",
      "ext-pharmacology-ch24-diuretics-term005",
      "ext-pharmacology-ch24-diuretics-fill001",
      "ext-pharmacology-ch24-diuretics-fill002",
      "ext-pharmacology-ch24-diuretics-fill003",
      "ext-pharmacology-ch24-diuretics-fill004",
      "ext-pharmacology-ch24-diuretics-fill005",
      "ext-pharmacology-ch24-diuretics-fill006",
      "ext-pharmacology-ch24-diuretics-fill007",
      "ext-pharmacology-ch24-diuretics-a1001",
      "ext-pharmacology-ch24-diuretics-short001",
      "ext-pharmacology-ch24-diuretics-short002",
      "ext-pharmacology-ch24-diuretics-short003"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch25-antihypertensives",
    "slug": "pharmacology-ch25-antihypertensives",
    "order": 1,
    "title": "第25章 抗高血压药",
    "note": "题库章节：第25章 抗高血压药。底稿 9 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch25-antihypertensives-term001",
      "ext-pharmacology-ch25-antihypertensives-term002",
      "ext-pharmacology-ch25-antihypertensives-fill001",
      "ext-pharmacology-ch25-antihypertensives-fill002",
      "ext-pharmacology-ch25-antihypertensives-fill003",
      "ext-pharmacology-ch25-antihypertensives-fill004",
      "ext-pharmacology-ch25-antihypertensives-a1001",
      "ext-pharmacology-ch25-antihypertensives-short001",
      "ext-pharmacology-ch25-antihypertensives-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch26-heart-failure-drugs",
    "slug": "pharmacology-ch26-heart-failure-drugs",
    "order": 1,
    "title": "第26章 治疗心力衰竭的药物",
    "note": "题库章节：第26章 治疗心力衰竭的药物。底稿 32 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch26-heart-failure-drugs-term001",
      "ext-pharmacology-ch26-heart-failure-drugs-term002",
      "ext-pharmacology-ch26-heart-failure-drugs-term003",
      "ext-pharmacology-ch26-heart-failure-drugs-term004",
      "ext-pharmacology-ch26-heart-failure-drugs-fill001",
      "ext-pharmacology-ch26-heart-failure-drugs-fill002",
      "ext-pharmacology-ch26-heart-failure-drugs-fill003",
      "ext-pharmacology-ch26-heart-failure-drugs-fill004",
      "ext-pharmacology-ch26-heart-failure-drugs-fill005",
      "ext-pharmacology-ch26-heart-failure-drugs-fill006",
      "ext-pharmacology-ch26-heart-failure-drugs-fill007",
      "ext-pharmacology-ch26-heart-failure-drugs-fill008",
      "ext-pharmacology-ch26-heart-failure-drugs-fill009",
      "ext-pharmacology-ch26-heart-failure-drugs-fill010",
      "ext-pharmacology-ch26-heart-failure-drugs-fill011",
      "ext-pharmacology-ch26-heart-failure-drugs-fill012",
      "ext-pharmacology-ch26-heart-failure-drugs-fill013",
      "ext-pharmacology-ch26-heart-failure-drugs-a1001",
      "ext-pharmacology-ch26-heart-failure-drugs-a1002",
      "ext-pharmacology-ch26-heart-failure-drugs-a1003",
      "ext-pharmacology-ch26-heart-failure-drugs-a1004",
      "ext-pharmacology-ch26-heart-failure-drugs-a1005",
      "ext-pharmacology-ch26-heart-failure-drugs-short001",
      "ext-pharmacology-ch26-heart-failure-drugs-short002",
      "ext-pharmacology-ch26-heart-failure-drugs-short003",
      "ext-pharmacology-ch26-heart-failure-drugs-short004",
      "ext-pharmacology-ch26-heart-failure-drugs-short005",
      "ext-pharmacology-ch26-heart-failure-drugs-short006",
      "ext-pharmacology-ch26-heart-failure-drugs-short007",
      "ext-pharmacology-ch26-heart-failure-drugs-short008",
      "ext-pharmacology-ch26-heart-failure-drugs-short009",
      "ext-pharmacology-ch26-heart-failure-drugs-short010"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch27-lipid-lowering-drugs",
    "slug": "pharmacology-ch27-lipid-lowering-drugs",
    "order": 1,
    "title": "第27章 调血脂药与抗动脉粥样硬化药",
    "note": "题库章节：第27章 调血脂药与抗动脉粥样硬化药。底稿 12 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch27-lipid-lowering-drugs-term001",
      "ext-pharmacology-ch27-lipid-lowering-drugs-term002",
      "ext-pharmacology-ch27-lipid-lowering-drugs-a1001",
      "ext-pharmacology-ch27-lipid-lowering-drugs-a1002",
      "ext-pharmacology-ch27-lipid-lowering-drugs-a1003",
      "ext-pharmacology-ch27-lipid-lowering-drugs-a1004",
      "ext-pharmacology-ch27-lipid-lowering-drugs-a1005",
      "ext-pharmacology-ch27-lipid-lowering-drugs-a1006",
      "ext-pharmacology-ch27-lipid-lowering-drugs-a1007",
      "ext-pharmacology-ch27-lipid-lowering-drugs-short001",
      "ext-pharmacology-ch27-lipid-lowering-drugs-short002",
      "ext-pharmacology-ch27-lipid-lowering-drugs-short003"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch28-antianginal-drugs",
    "slug": "pharmacology-ch28-antianginal-drugs",
    "order": 1,
    "title": "第28章 抗心绞痛药",
    "note": "题库章节：第28章 抗心绞痛药。底稿 12 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch28-antianginal-drugs-fill001",
      "ext-pharmacology-ch28-antianginal-drugs-fill002",
      "ext-pharmacology-ch28-antianginal-drugs-a1001",
      "ext-pharmacology-ch28-antianginal-drugs-a1002",
      "ext-pharmacology-ch28-antianginal-drugs-a1003",
      "ext-pharmacology-ch28-antianginal-drugs-a1004",
      "ext-pharmacology-ch28-antianginal-drugs-a1005",
      "ext-pharmacology-ch28-antianginal-drugs-a1006",
      "ext-pharmacology-ch28-antianginal-drugs-short001",
      "ext-pharmacology-ch28-antianginal-drugs-short002",
      "ext-pharmacology-ch28-antianginal-drugs-short003",
      "ext-pharmacology-ch28-antianginal-drugs-short004"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch29-blood-hematopoietic-drugs",
    "slug": "pharmacology-ch29-blood-hematopoietic-drugs",
    "order": 1,
    "title": "第29章 作用于血液及造血系统的药物",
    "note": "题库章节：第29章 作用于血液及造血系统的药物。底稿 16 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-term001",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-term002",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-a1001",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-a1002",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-a1003",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-a1004",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-a1005",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-a1006",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-a1007",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-a1008",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-a1009",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-short001",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-short002",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-short003",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-short004",
      "ext-pharmacology-ch29-blood-hematopoietic-drugs-short005"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch30-autacoids",
    "slug": "pharmacology-ch30-autacoids",
    "order": 1,
    "title": "第30章 影响自体活性物质的药物",
    "note": "题库章节：第30章 影响自体活性物质的药物。底稿 5 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch30-autacoids-term001",
      "ext-pharmacology-ch30-autacoids-fill001",
      "ext-pharmacology-ch30-autacoids-a1001",
      "ext-pharmacology-ch30-autacoids-short001",
      "ext-pharmacology-ch30-autacoids-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch31-respiratory-drugs",
    "slug": "pharmacology-ch31-respiratory-drugs",
    "order": 1,
    "title": "第31章 作用于呼吸系统的药物",
    "note": "题库章节：第31章 作用于呼吸系统的药物。底稿 10 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch31-respiratory-drugs-term001",
      "ext-pharmacology-ch31-respiratory-drugs-term002",
      "ext-pharmacology-ch31-respiratory-drugs-fill001",
      "ext-pharmacology-ch31-respiratory-drugs-fill002",
      "ext-pharmacology-ch31-respiratory-drugs-fill003",
      "ext-pharmacology-ch31-respiratory-drugs-a1001",
      "ext-pharmacology-ch31-respiratory-drugs-short001",
      "ext-pharmacology-ch31-respiratory-drugs-short002",
      "ext-pharmacology-ch31-respiratory-drugs-short003",
      "ext-pharmacology-ch31-respiratory-drugs-short004"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch32-gastrointestinal-drugs",
    "slug": "pharmacology-ch32-gastrointestinal-drugs",
    "order": 1,
    "title": "第32章 作用于消化系统的药物",
    "note": "题库章节：第32章 作用于消化系统的药物。底稿 8 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch32-gastrointestinal-drugs-fill001",
      "ext-pharmacology-ch32-gastrointestinal-drugs-fill002",
      "ext-pharmacology-ch32-gastrointestinal-drugs-a1001",
      "ext-pharmacology-ch32-gastrointestinal-drugs-a1002",
      "ext-pharmacology-ch32-gastrointestinal-drugs-a1003",
      "ext-pharmacology-ch32-gastrointestinal-drugs-a1004",
      "ext-pharmacology-ch32-gastrointestinal-drugs-short001",
      "ext-pharmacology-ch32-gastrointestinal-drugs-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch33-uterine-drugs",
    "slug": "pharmacology-ch33-uterine-drugs",
    "order": 1,
    "title": "第33章 子宫平滑肌兴奋药和抑制药",
    "note": "题库章节：第33章 子宫平滑肌兴奋药和抑制药。底稿 8 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch33-uterine-drugs-term001",
      "ext-pharmacology-ch33-uterine-drugs-term002",
      "ext-pharmacology-ch33-uterine-drugs-fill001",
      "ext-pharmacology-ch33-uterine-drugs-fill002",
      "ext-pharmacology-ch33-uterine-drugs-a1001",
      "ext-pharmacology-ch33-uterine-drugs-a1002",
      "ext-pharmacology-ch33-uterine-drugs-a1003",
      "ext-pharmacology-ch33-uterine-drugs-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch34-sex-hormone-contraceptives",
    "slug": "pharmacology-ch34-sex-hormone-contraceptives",
    "order": 1,
    "title": "第34章 性激素类药及避孕药",
    "note": "题库章节：第34章 性激素类药及避孕药。底稿 7 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch34-sex-hormone-contraceptives-term001",
      "ext-pharmacology-ch34-sex-hormone-contraceptives-fill001",
      "ext-pharmacology-ch34-sex-hormone-contraceptives-fill002",
      "ext-pharmacology-ch34-sex-hormone-contraceptives-a1001",
      "ext-pharmacology-ch34-sex-hormone-contraceptives-a1002",
      "ext-pharmacology-ch34-sex-hormone-contraceptives-a1003",
      "ext-pharmacology-ch34-sex-hormone-contraceptives-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch35-adrenocortical-hormones",
    "slug": "pharmacology-ch35-adrenocortical-hormones",
    "order": 1,
    "title": "第35章 肾上腺皮质激素类药物",
    "note": "题库章节：第35章 肾上腺皮质激素类药物。底稿 10 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch35-adrenocortical-hormones-term001",
      "ext-pharmacology-ch35-adrenocortical-hormones-term002",
      "ext-pharmacology-ch35-adrenocortical-hormones-term003",
      "ext-pharmacology-ch35-adrenocortical-hormones-term004",
      "ext-pharmacology-ch35-adrenocortical-hormones-fill001",
      "ext-pharmacology-ch35-adrenocortical-hormones-fill002",
      "ext-pharmacology-ch35-adrenocortical-hormones-a1001",
      "ext-pharmacology-ch35-adrenocortical-hormones-a1002",
      "ext-pharmacology-ch35-adrenocortical-hormones-a1003",
      "ext-pharmacology-ch35-adrenocortical-hormones-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch36-thyroid-hormones-antithyroid",
    "slug": "pharmacology-ch36-thyroid-hormones-antithyroid",
    "order": 1,
    "title": "第36章 甲状腺激素及抗甲状腺药",
    "note": "题库章节：第36章 甲状腺激素及抗甲状腺药。底稿 9 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch36-thyroid-hormones-antithyroid-term001",
      "ext-pharmacology-ch36-thyroid-hormones-antithyroid-term002",
      "ext-pharmacology-ch36-thyroid-hormones-antithyroid-fill001",
      "ext-pharmacology-ch36-thyroid-hormones-antithyroid-fill002",
      "ext-pharmacology-ch36-thyroid-hormones-antithyroid-fill003",
      "ext-pharmacology-ch36-thyroid-hormones-antithyroid-a1001",
      "ext-pharmacology-ch36-thyroid-hormones-antithyroid-a1002",
      "ext-pharmacology-ch36-thyroid-hormones-antithyroid-short001",
      "ext-pharmacology-ch36-thyroid-hormones-antithyroid-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch37-insulin-antidiabetics",
    "slug": "pharmacology-ch37-insulin-antidiabetics",
    "order": 1,
    "title": "第37章 胰岛素及其他降血糖药",
    "note": "题库章节：第37章 胰岛素及其他降血糖药。底稿 11 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch37-insulin-antidiabetics-term001",
      "ext-pharmacology-ch37-insulin-antidiabetics-term002",
      "ext-pharmacology-ch37-insulin-antidiabetics-term003",
      "ext-pharmacology-ch37-insulin-antidiabetics-fill001",
      "ext-pharmacology-ch37-insulin-antidiabetics-fill002",
      "ext-pharmacology-ch37-insulin-antidiabetics-fill003",
      "ext-pharmacology-ch37-insulin-antidiabetics-fill004",
      "ext-pharmacology-ch37-insulin-antidiabetics-fill005",
      "ext-pharmacology-ch37-insulin-antidiabetics-a1001",
      "ext-pharmacology-ch37-insulin-antidiabetics-a1002",
      "ext-pharmacology-ch37-insulin-antidiabetics-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch38-antiosteoporosis-drugs",
    "slug": "pharmacology-ch38-antiosteoporosis-drugs",
    "order": 1,
    "title": "第38章 抗骨质疏松药",
    "note": "题库章节：第38章 抗骨质疏松药。底稿 11 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch38-antiosteoporosis-drugs-fill001",
      "ext-pharmacology-ch38-antiosteoporosis-drugs-fill002",
      "ext-pharmacology-ch38-antiosteoporosis-drugs-fill003",
      "ext-pharmacology-ch38-antiosteoporosis-drugs-a1001",
      "ext-pharmacology-ch38-antiosteoporosis-drugs-a1002",
      "ext-pharmacology-ch38-antiosteoporosis-drugs-a1003",
      "ext-pharmacology-ch38-antiosteoporosis-drugs-a1004",
      "ext-pharmacology-ch38-antiosteoporosis-drugs-a1005",
      "ext-pharmacology-ch38-antiosteoporosis-drugs-short001",
      "ext-pharmacology-ch38-antiosteoporosis-drugs-short002",
      "ext-pharmacology-ch38-antiosteoporosis-drugs-short003"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch39-antimicrobial-overview",
    "slug": "pharmacology-ch39-antimicrobial-overview",
    "order": 1,
    "title": "第39章 抗菌药物概述",
    "note": "题库章节：第39章 抗菌药物概述。底稿 8 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch39-antimicrobial-overview-term001",
      "ext-pharmacology-ch39-antimicrobial-overview-term002",
      "ext-pharmacology-ch39-antimicrobial-overview-term003",
      "ext-pharmacology-ch39-antimicrobial-overview-term004",
      "ext-pharmacology-ch39-antimicrobial-overview-term005",
      "ext-pharmacology-ch39-antimicrobial-overview-term006",
      "ext-pharmacology-ch39-antimicrobial-overview-a1001",
      "ext-pharmacology-ch39-antimicrobial-overview-a1002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch40-beta-lactam-antibiotics",
    "slug": "pharmacology-ch40-beta-lactam-antibiotics",
    "order": 1,
    "title": "第40章 β-内酰胺类抗生素",
    "note": "题库章节：第40章 β-内酰胺类抗生素。底稿 14 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch40-beta-lactam-antibiotics-term001",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-term002",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-fill001",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-fill002",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-fill003",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-fill004",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-fill005",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-a1001",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-a1002",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-a1003",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-a1004",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-a1005",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-short001",
      "ext-pharmacology-ch40-beta-lactam-antibiotics-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch41-macrolides-lincosamides-polypeptides",
    "slug": "pharmacology-ch41-macrolides-lincosamides-polypeptides",
    "order": 1,
    "title": "第41章 大环内酯类、林可霉素类及多肽类抗生素",
    "note": "题库章节：第41章 大环内酯类、林可霉素类及多肽类抗生素。底稿 7 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch41-macrolides-lincosamides-polypeptides-term001",
      "ext-pharmacology-ch41-macrolides-lincosamides-polypeptides-fill001",
      "ext-pharmacology-ch41-macrolides-lincosamides-polypeptides-fill002",
      "ext-pharmacology-ch41-macrolides-lincosamides-polypeptides-a1001",
      "ext-pharmacology-ch41-macrolides-lincosamides-polypeptides-a1002",
      "ext-pharmacology-ch41-macrolides-lincosamides-polypeptides-a1003",
      "ext-pharmacology-ch41-macrolides-lincosamides-polypeptides-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch42-aminoglycosides",
    "slug": "pharmacology-ch42-aminoglycosides",
    "order": 1,
    "title": "第42章 氨基苷类抗生素",
    "note": "题库章节：第42章 氨基苷类抗生素。底稿 11 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch42-aminoglycosides-term001",
      "ext-pharmacology-ch42-aminoglycosides-fill001",
      "ext-pharmacology-ch42-aminoglycosides-fill002",
      "ext-pharmacology-ch42-aminoglycosides-fill003",
      "ext-pharmacology-ch42-aminoglycosides-fill004",
      "ext-pharmacology-ch42-aminoglycosides-a1001",
      "ext-pharmacology-ch42-aminoglycosides-a1002",
      "ext-pharmacology-ch42-aminoglycosides-a1003",
      "ext-pharmacology-ch42-aminoglycosides-a1004",
      "ext-pharmacology-ch42-aminoglycosides-a1005",
      "ext-pharmacology-ch42-aminoglycosides-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch43-tetracyclines-chloramphenicol",
    "slug": "pharmacology-ch43-tetracyclines-chloramphenicol",
    "order": 1,
    "title": "第43章 四环素类及氯霉素类",
    "note": "题库章节：第43章 四环素类及氯霉素类。底稿 9 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch43-tetracyclines-chloramphenicol-term001",
      "ext-pharmacology-ch43-tetracyclines-chloramphenicol-term002",
      "ext-pharmacology-ch43-tetracyclines-chloramphenicol-fill001",
      "ext-pharmacology-ch43-tetracyclines-chloramphenicol-fill002",
      "ext-pharmacology-ch43-tetracyclines-chloramphenicol-fill003",
      "ext-pharmacology-ch43-tetracyclines-chloramphenicol-a1001",
      "ext-pharmacology-ch43-tetracyclines-chloramphenicol-a1002",
      "ext-pharmacology-ch43-tetracyclines-chloramphenicol-short001",
      "ext-pharmacology-ch43-tetracyclines-chloramphenicol-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch44-synthetic-antimicrobials",
    "slug": "pharmacology-ch44-synthetic-antimicrobials",
    "order": 1,
    "title": "第44章 人工合成抗菌药",
    "note": "题库章节：第44章 人工合成抗菌药。底稿 9 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch44-synthetic-antimicrobials-fill001",
      "ext-pharmacology-ch44-synthetic-antimicrobials-fill002",
      "ext-pharmacology-ch44-synthetic-antimicrobials-fill003",
      "ext-pharmacology-ch44-synthetic-antimicrobials-fill004",
      "ext-pharmacology-ch44-synthetic-antimicrobials-fill005",
      "ext-pharmacology-ch44-synthetic-antimicrobials-a1001",
      "ext-pharmacology-ch44-synthetic-antimicrobials-a1002",
      "ext-pharmacology-ch44-synthetic-antimicrobials-short001",
      "ext-pharmacology-ch44-synthetic-antimicrobials-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch45-antiviral-antifungal",
    "slug": "pharmacology-ch45-antiviral-antifungal",
    "order": 1,
    "title": "第45章 抗病毒药和抗真菌药",
    "note": "题库章节：第45章 抗病毒药和抗真菌药。底稿 7 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch45-antiviral-antifungal-a1001",
      "ext-pharmacology-ch45-antiviral-antifungal-a1002",
      "ext-pharmacology-ch45-antiviral-antifungal-a1003",
      "ext-pharmacology-ch45-antiviral-antifungal-a1004",
      "ext-pharmacology-ch45-antiviral-antifungal-a1005",
      "ext-pharmacology-ch45-antiviral-antifungal-short001",
      "ext-pharmacology-ch45-antiviral-antifungal-short002"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch46-antituberculosis-antileprosy",
    "slug": "pharmacology-ch46-antituberculosis-antileprosy",
    "order": 1,
    "title": "第46章 抗结核药及抗麻风病药",
    "note": "题库章节：第46章 抗结核药及抗麻风病药。底稿 11 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch46-antituberculosis-antileprosy-fill001",
      "ext-pharmacology-ch46-antituberculosis-antileprosy-fill002",
      "ext-pharmacology-ch46-antituberculosis-antileprosy-fill003",
      "ext-pharmacology-ch46-antituberculosis-antileprosy-fill004",
      "ext-pharmacology-ch46-antituberculosis-antileprosy-fill005",
      "ext-pharmacology-ch46-antituberculosis-antileprosy-a1001",
      "ext-pharmacology-ch46-antituberculosis-antileprosy-a1002",
      "ext-pharmacology-ch46-antituberculosis-antileprosy-a1003",
      "ext-pharmacology-ch46-antituberculosis-antileprosy-a1004",
      "ext-pharmacology-ch46-antituberculosis-antileprosy-a1005",
      "ext-pharmacology-ch46-antituberculosis-antileprosy-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch47-antiparasitic",
    "slug": "pharmacology-ch47-antiparasitic",
    "order": 1,
    "title": "第47章 抗寄生虫药",
    "note": "题库章节：第47章 抗寄生虫药。底稿 6 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch47-antiparasitic-fill001",
      "ext-pharmacology-ch47-antiparasitic-fill002",
      "ext-pharmacology-ch47-antiparasitic-fill003",
      "ext-pharmacology-ch47-antiparasitic-a1001",
      "ext-pharmacology-ch47-antiparasitic-a1002",
      "ext-pharmacology-ch47-antiparasitic-short001"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch48-antitumor",
    "slug": "pharmacology-ch48-antitumor",
    "order": 1,
    "title": "第48章 抗恶性肿瘤药",
    "note": "题库章节：第48章 抗恶性肿瘤药。底稿 9 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch48-antitumor-term001",
      "ext-pharmacology-ch48-antitumor-term002",
      "ext-pharmacology-ch48-antitumor-term003",
      "ext-pharmacology-ch48-antitumor-fill001",
      "ext-pharmacology-ch48-antitumor-fill002",
      "ext-pharmacology-ch48-antitumor-a1001",
      "ext-pharmacology-ch48-antitumor-a1002",
      "ext-pharmacology-ch48-antitumor-a1003",
      "ext-pharmacology-ch48-antitumor-a1004"
    ],
    "caseIds": [],
    "lesson": null
  },
  {
    "id": "kp-pharmacology-ch49-immunomodulators",
    "slug": "pharmacology-ch49-immunomodulators",
    "order": 1,
    "title": "第49章 影响免疫功能的药物",
    "note": "题库章节：第49章 影响免疫功能的药物。底稿 11 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。",
    "emphasis": "重点",
    "contentStatus": "available",
    "evidenceFramework": [],
    "lenses": [],
    "relationships": [],
    "learningMemoryCriteria": [],
    "sourceIds": [],
    "learningTaskIds": [],
    "assessmentItemIds": [
      "ext-pharmacology-ch49-immunomodulators-term001",
      "ext-pharmacology-ch49-immunomodulators-term002",
      "ext-pharmacology-ch49-immunomodulators-fill001",
      "ext-pharmacology-ch49-immunomodulators-fill002",
      "ext-pharmacology-ch49-immunomodulators-fill003",
      "ext-pharmacology-ch49-immunomodulators-fill004",
      "ext-pharmacology-ch49-immunomodulators-fill005",
      "ext-pharmacology-ch49-immunomodulators-a1001",
      "ext-pharmacology-ch49-immunomodulators-a1002",
      "ext-pharmacology-ch49-immunomodulators-short001",
      "ext-pharmacology-ch49-immunomodulators-short002"
    ],
    "caseIds": [],
    "lesson": null
  }
] as const;

// 教材来源：全部 extracted 题目出自同一本题集，统一挂此来源（题目 locator 保留章/页细节）
const QB_SOURCE_ID = "source-pharmacology-qb-textbook" as const;
const qbSource = {
  id: QB_SOURCE_ID,
  order: 1,
  role: "course-material",
  type: "question-bank",
  authority: "publisher",
  scope: "general-reference",
  displayLabel: "《药理学学习指导与习题集》第4版",
  status: "available",
  missingLabel: null,
  citation: {
    label: "《药理学学习指导与习题集》第4版",
    edition: "第4版",
    page: null,
    slide: null,
    academicYear: null,
    url: null,
  },
  verifiedAt: null,
} as const;

// 边界转换：来源补充 + 知识点内 order 重排 + B1 题干并入成员 + 大组拆分（不修改底稿）
const { items: qbItems, groups: qbGroups } = buildQbCourseAssessmentData(
  pharmacologyExtractedItems,
  pharmacologyExtractedGroups,
  QB_SOURCE_ID,
);

export const pharmacologyQbCourse: CourseDefinition = {
  id: "course-pharmacology-qb",
  slug: "pharmacology-qb",
  title: "药理学 · 题库",
  catalogLabel: "药理学题库",
  classification: "西医基础医学",
  description: "《药理学学习指导与习题集》第4版题库底稿（扫描件 OCR 提取）：49 章恰好 600 道独立记分题（含 35 组 B1 配伍），答案未与权威教材交叉核对。",
  ghostWordmark: "PHARMACOLOGY",
  curriculumMode: "western-primary",
  contentStatus: "available",
  version: {
    id: "version-pharmacology-qb",
    status: "pending",
    textbookEdition: { status: "pending", value: null, missingLabel: "药理学教材版本信息待核验", verifiedAt: null },
    school: { status: "pending", value: null, missingLabel: "学校待确认", verifiedAt: null },
    program: { status: "pending", value: null, missingLabel: "专业待确认", verifiedAt: null },
    learnerYear: { status: "pending", value: null, missingLabel: "年级待确认", verifiedAt: null },
    teacher: { status: "pending", value: null, missingLabel: "任课教师待确认", verifiedAt: null },
    academicYear: { status: "pending", value: null, missingLabel: "学年待确认", verifiedAt: null },
    semester: { status: "pending", value: null, missingLabel: "学期待确认", verifiedAt: null },
  },
  sources: [qbSource],
  examBlueprint: {
    id: "exam-blueprint-pharmacology-qb",
    title: "药理学 · 题库",
    status: "pending",
    missingLabel: "药理学正式考纲/试卷结构待导入",
    provenance: "user-provided",
    scope: {
      school: "待确认",
      program: "待确认",
      learnerYear: "待确认",
      academicYear: "待确认",
      semester: "待确认",
      teacher: null,
    },
    sourceIds: [],
    totalPoints: 0,
    rows: [],
    summaryGroups: [],
    priorityNotice: null,
    integrity: null,
  },
  learningRoutes: [],
  chapters,
  knowledgePoints,
  learningTasks: [],
  assessmentItems: qbItems,
  assessmentGroups: qbGroups,
  cases: [],
};

export default pharmacologyQbCourse;
