import type { AssessmentItemDefinition } from "@/types/learning";
import {
  deepLoopSourceIds,
} from "@/content/courses/tcm-diagnostics-deep-loops";

/**
 * 中诊题库扩充（2026-08-06）。
 *
 * 目标：把模考组卷从“3 道 A1 的残缺卷”提升为有意义的半卷。
 * 原则：
 * - 所有新题都是 NUR 改编（nur-adapted + nur-editorial 题干），
 *   只引用已核验的教材/教师页码来源，不冒充学校原题；
 * - 答案全部为 nur-platform + source-cross-checked，明确不是学校答案或教师采分点；
 * - B1/B2 语义未被来源确认，继续不创建，模考如实报告 shortfall；
 * - 每个知识点在模考同题型中至多取一题（广度优先组卷），
 *   因此新增题与既有题按知识点互不挤占。
 */

const textbookSourceId = "source-tcm-diagnostics-textbook";

const a1Items: AssessmentItemDefinition[] = [
  {
    id: "assessment-qb-a1-diet-taste-thirst-polyuria",
    order: 8,
    knowledgePointId: "kp-inquiry-diet-taste",
    questionKind: "a1-single",
    status: "available",
    prompt: "患者消谷善饥，兼见多饮多尿、形体消瘦，最常见于下列哪种情况？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第60–61页问饮食口味",
      note: "NUR 改编自教材核心知识点与学校白皮书填充题同源内容，不冒充学校原题。",
      sourceIds: [textbookSourceId],
    },
    choices: ["胃火炽盛", "消渴病", "胃强脾弱", "肝胃不和"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["消谷善饥兼见多饮多尿、形体消瘦者，多见于消渴病；若仅见消谷善饥、口臭便秘则为胃火炽盛方向。"],
      notice: "答案参考教材第3版P60–61，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [textbookSourceId],
    },
    scoring: null,
    sourceIds: [textbookSourceId],
  },
  {
    id: "assessment-qb-a1-tongue-greasy",
    order: 3,
    knowledgePointId: "kp-tongue-coating",
    questionKind: "a1-single",
    status: "available",
    prompt: "舌苔质地致密细腻，如涂油腻之状，刮之难去者，称为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第37页腐苔、腻苔舌象特征",
      note: "NUR 改编自教材已核验页码内容。",
      sourceIds: [deepLoopSourceIds.tongueTextbook],
    },
    choices: ["薄苔", "厚苔", "腻苔", "腐苔"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["腻苔为苔质致密细腻、颗粒致密、如涂油腻状、刮之难去；腐苔则苔质疏松、颗粒粗大、刮之易去。"],
      notice: "答案参考教材第3版P37，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.tongueTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.tongueTextbook],
  },
  {
    id: "assessment-qb-a1-tongue-mouldy",
    order: 4,
    knowledgePointId: "kp-tongue-coating",
    questionKind: "a1-single",
    status: "available",
    prompt: "舌苔苔质疏松，颗粒粗大，形如豆腐渣，刮之易去者，称为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第37页腐苔、腻苔舌象特征",
      note: "NUR 改编自教材已核验页码内容。",
      sourceIds: [deepLoopSourceIds.tongueTextbook],
    },
    choices: ["腻苔", "腐苔", "剥苔", "燥苔"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["腐苔为苔质疏松、颗粒粗大、形如豆腐渣、刮之易去；腻苔则苔质致密、刮之难去，二者需鉴别。"],
      notice: "答案参考教材第3版P37，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.tongueTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.tongueTextbook],
  },
  {
    id: "assessment-qb-a1-cold-heat-superficies",
    order: 3,
    knowledgePointId: "kp-inquiry-cold-heat",
    questionKind: "a1-single",
    status: "available",
    prompt: "恶寒与发热同时并见，最常见于下列哪种情况？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第52–53页问寒热",
      note: "NUR 改编自教材已核验页码内容。",
      sourceIds: [deepLoopSourceIds.coldHeatTextbook],
    },
    choices: ["里实热证", "外感表证初期", "半表半里证", "阴虚内热证"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["恶寒与发热同时并见，多见于外感表证初期，是外邪犯表、卫阳被遏与邪正相争的反映；半表半里则见寒热往来。"],
      notice: "答案参考教材第3版P52–53，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.coldHeatTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.coldHeatTextbook],
  },
  {
    id: "assessment-qb-a1-cold-heat-tidal",
    order: 4,
    knowledgePointId: "kp-inquiry-cold-heat",
    questionKind: "a1-single",
    status: "available",
    prompt: "患者身热不扬，午后热甚，多见于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第52–53页但热不寒分类",
      note: "NUR 改编自教材已核验页码内容。",
      sourceIds: [deepLoopSourceIds.coldHeatTextbook],
    },
    choices: ["壮热", "湿温潮热", "微热", "寒热往来"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["但热不寒中的潮热按时发热或定时热甚，其中湿温潮热以身热不扬、午后热甚为特征；壮热为持续高热不退。"],
      notice: "答案参考教材第3版P52–53，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.coldHeatTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.coldHeatTextbook],
  },
  {
    id: "assessment-qb-a1-pulse-floating",
    order: 3,
    knowledgePointId: "kp-pulse-common",
    questionKind: "a1-single",
    status: "available",
    prompt: "轻取即得，重按稍减而不空，举之有余、按之不足的脉象是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第69、71、73、79页病脉与脉象鉴别",
      note: "NUR 改编自教材已核验页码内容。",
      sourceIds: [deepLoopSourceIds.pulseTextbook],
    },
    choices: ["沉脉", "浮脉", "迟脉", "数脉"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["浮脉轻取即得、重按稍减而不空，主表证；沉脉轻取不应、重按始得，与之相反。"],
      notice: "答案参考教材第3版P69、71、73、79，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.pulseTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.pulseTextbook],
  },
  {
    id: "assessment-qb-a1-pulse-rapid",
    order: 4,
    knowledgePointId: "kp-pulse-common",
    questionKind: "a1-single",
    status: "available",
    prompt: "一息脉来五至以上，其临床意义最常见的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第69、71、73、79页病脉与脉象鉴别",
      note: "NUR 改编自教材已核验页码内容。",
      sourceIds: [deepLoopSourceIds.pulseTextbook],
    },
    choices: ["寒证", "热证", "虚证", "痛证"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["数脉为一息脉来五至以上，主热证，亦可见于里虚证；迟脉一息不足四至主寒证。"],
      notice: "答案参考教材第3版P69、71、73、79，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.pulseTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.pulseTextbook],
  },
  {
    id: "assessment-qb-a1-exterior-superficies-signs",
    order: 3,
    knowledgePointId: "kp-eight-principles-exterior-interior",
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪项最符合表证的临床表现？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第89–91页表证、里证及鉴别",
      note: "NUR 改编自教材已核验页码内容。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    choices: ["恶寒发热并见，脉浮", "但热不寒，口渴便秘", "五心烦热，颧红盗汗", "手足不温，蜷卧嗜睡"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["表证以恶寒（或恶风）发热并见、头身疼痛、鼻塞流涕、脉浮、苔薄白为特征；但热不寒、口渴便秘多见于里证。"],
      notice: "答案参考教材第3版P89–91，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
  },
  {
    id: "assessment-qb-a1-exterior-enters-interior",
    order: 4,
    knowledgePointId: "kp-eight-principles-exterior-interior",
    questionKind: "a1-single",
    status: "available",
    prompt: "患者表证已解，恶寒消失，转而壮热、口渴、大便秘结、小便短赤，此属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第89–91页表里转化",
      note: "NUR 改编自教材已核验页码内容。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    choices: ["表证", "半表半里证", "里证", "表里同病"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["表邪入里后恶寒消失、壮热口渴便秘并见，说明病位已由肌表深入脏腑，属里证；表里同病则表证与里证表现并见。"],
      notice: "答案参考教材第3版P89–91，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
  },
  {
    id: "assessment-qb-a1-spleen-qi-not-cold",
    order: 2,
    knowledgePointId: "kp-organs-spleen-stomach",
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪项不属于脾气虚证的常见表现？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第121–123页脾气虚、脾阳虚及相关证候鉴别",
      note: "NUR 改编自教材已核验页码内容。",
      sourceIds: [deepLoopSourceIds.spleenTextbook],
    },
    choices: ["食少腹胀", "大便溏薄", "畏寒肢冷", "神疲乏力"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["脾气虚证以食少腹胀、便溏、神疲乏力、面色萎黄、少气懒言为常见表现；畏寒肢冷、腹痛喜温是脾阳虚证的增量表现。"],
      notice: "答案参考教材第3版P121–123，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.spleenTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.spleenTextbook],
  },
  {
    id: "assessment-qb-a1-spleen-yang-increment",
    order: 3,
    knowledgePointId: "kp-organs-spleen-stomach",
    questionKind: "a1-single",
    status: "available",
    prompt: "脾阳虚证在脾气虚证的基础上，最突出的增量表现是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第121–123页脾气虚、脾阳虚及相关证候鉴别",
      note: "NUR 改编自教材已核验页码内容。",
      sourceIds: [deepLoopSourceIds.spleenTextbook],
    },
    choices: ["食少腹胀", "四肢不温、腹痛喜温喜按", "神疲乏力", "大便稀溏"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["脾阳虚证在脾气虚共性（食少腹胀、便溏、神疲）之外，因温煦失职而见畏寒肢冷、腹痛喜温喜按、口泛清水等增量表现。"],
      notice: "答案参考教材第3版P121–123，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.spleenTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.spleenTextbook],
  },
  {
    id: "assessment-qb-a1-spirit-false",
    order: 8,
    knowledgePointId: "kp-inspection-spirit",
    questionKind: "a1-single",
    status: "available",
    prompt: "久病重病患者本已失神，突然精神转佳、目光转亮、两颧泛红如妆、言语不休，此属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材望诊·望神章节",
      note: "NUR 改编自教材望神知识点，不冒充学校原题。",
      sourceIds: [textbookSourceId],
    },
    choices: ["得神", "少神", "失神", "假神"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["久病重病之人本已失神，突然出现精神转佳、目光转亮、面色泛红如妆、言语不休等表现，属于假神，是脏腑精气极度衰竭的危候。"],
      notice: "NUR 参考教材望神内容组织答案；不是学校或任课教师标准答案。",
      sourceIds: [textbookSourceId],
    },
    scoring: null,
    sourceIds: [textbookSourceId],
  },
];

const fillItems: AssessmentItemDefinition[] = [
  {
    id: "assessment-qb-fill-cold-heat-superficies",
    order: 5,
    knowledgePointId: "kp-inquiry-cold-heat",
    questionKind: "fill",
    status: "available",
    prompt: "恶寒与发热同时并见，多见于＿＿＿＿证。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第52–53页问寒热",
      note: "NUR 改编自教材已核验页码内容，不冒充学校原题。",
      sourceIds: [deepLoopSourceIds.coldHeatTextbook],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["外感表证（表证）"],
      notice: "答案参考教材第3版P52–53，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.coldHeatTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.coldHeatTextbook],
  },
  {
    id: "assessment-qb-fill-tongue-greasy",
    order: 5,
    knowledgePointId: "kp-tongue-coating",
    questionKind: "fill",
    status: "available",
    prompt: "苔质致密细腻，颗粒均匀，如涂油腻状，刮之难去者，称为＿＿＿＿。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第37页腐苔、腻苔舌象特征",
      note: "NUR 改编自教材已核验页码内容，不冒充学校原题。",
      sourceIds: [deepLoopSourceIds.tongueTextbook],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["腻苔"],
      notice: "答案参考教材第3版P37，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.tongueTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.tongueTextbook],
  },
];

const termItems: AssessmentItemDefinition[] = [
  {
    id: "assessment-qb-term-cold-heat",
    order: 6,
    knowledgePointId: "kp-inquiry-cold-heat",
    questionKind: "term",
    status: "available",
    prompt: "名词解释：恶寒发热。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "由教材第52–53页问寒热转写为完整表达训练",
      note: "NUR 为训练完整表达所作的题型改写，不是学校原题。",
      sourceIds: [
        deepLoopSourceIds.coldHeatTextbook,
        deepLoopSourceIds.coldHeatReview,
        deepLoopSourceIds.editorial,
      ],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: [
        "定义：患者恶寒与发热同时并见，多见于外感表证初期。",
        "机理：外邪犯表，卫阳被遏则恶寒，邪正相争则发热，二者同时出现。",
        "鉴别：与但寒不热、但热不寒、寒热往来相区分，并结合脉证判断表证属性。",
      ],
      notice: "结构参考由 NUR 按教材第52–53页整理并经教师复习范围交叉核对，不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.coldHeatTextbook, deepLoopSourceIds.coldHeatReview, deepLoopSourceIds.editorial],
    },
    scoring: {
      id: "scoring-qb-term-cold-heat",
      standardVersion: "nur-writing-term-v1",
      status: "available",
      authority: "nur-platform",
      title: "NUR 名词解释完整度量表",
      totalPoints: 6,
      suggestedCharacters: 45,
      notice: "6分仅用于把答案拆开训练，不等同于当前课程每题3分，也不代表任课教师采分点。",
      answerFramework: ["是什么：先给出恶寒发热的规范定义。", "为什么：用卫阳被遏与邪正相争解释并见机理。", "如何辨：与但寒不热、但热不寒、寒热往来区分。"],
      criteria: [
        { id: "score-qb-term-cold-heat-definition", order: 1, perspective: "tcm", label: "定义准确", detail: "写明恶寒与发热同时并见及多见于表证初期。", points: 2 },
        { id: "score-qb-term-cold-heat-mechanism", order: 2, perspective: "tcm", label: "机理完整", detail: "写出卫阳被遏与邪正相争的解释。", points: 2 },
        { id: "score-qb-term-cold-heat-differentiation", order: 3, perspective: "tcm", label: "鉴别不跳步", detail: "至少与一种其他寒热类型区分，或说明需结合脉证。", points: 2 },
      ],
      assistanceRules: [
        {
          criterionId: "score-qb-term-cold-heat-definition",
          memoryCriterionId: "cold-heat-inquiry-memory-evidence",
          signalGroups: [["恶寒", "发热"], ["同时", "并见"], ["表证"]],
          nextStepPrompt: "先把恶寒与发热同时并见、多见于表证初期的定义要素写全。",
          rewriteSuggestion: "恶寒发热是指患者恶寒与发热同时并见，多见于外感表证初期。",
        },
        {
          criterionId: "score-qb-term-cold-heat-mechanism",
          memoryCriterionId: "cold-heat-inquiry-memory-reasoning",
          signalGroups: [["卫阳", "邪正相争"], ["被遏", "抗邪"]],
          nextStepPrompt: "补上卫阳被遏与邪正相争的机理说明。",
          rewriteSuggestion: "外邪犯表，卫阳被遏则恶寒，邪正相争则发热。",
        },
        {
          criterionId: "score-qb-term-cold-heat-differentiation",
          memoryCriterionId: "cold-heat-inquiry-memory-boundary",
          signalGroups: [["但寒不热", "但热不寒", "寒热往来"], ["鉴别", "结合"]],
          nextStepPrompt: "补一句与但寒不热、但热不寒或寒热往来的区分。",
          rewriteSuggestion: "需与但寒不热、但热不寒、寒热往来相鉴别，并结合脉证判断。",
        },
      ],
      sourceIds: [deepLoopSourceIds.coldHeatTextbook, deepLoopSourceIds.coldHeatReview, deepLoopSourceIds.editorial],
    },
    sourceIds: [deepLoopSourceIds.coldHeatTextbook, deepLoopSourceIds.coldHeatReview, deepLoopSourceIds.editorial],
  },
  {
    id: "assessment-qb-term-exterior-superficies",
    order: 5,
    knowledgePointId: "kp-eight-principles-exterior-interior",
    questionKind: "term",
    status: "available",
    prompt: "名词解释：表证。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "由教材第89–91页八纲辨证转写为完整表达训练",
      note: "NUR 为训练完整表达所作的题型改写，不是学校原题。",
      sourceIds: [
        deepLoopSourceIds.exteriorInteriorTextbook,
        deepLoopSourceIds.exteriorInteriorReview,
        deepLoopSourceIds.editorial,
      ],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: [
        "定义：六淫等外邪经皮毛、口鼻侵入，正气抗邪于肌表浅层所表现的证候。",
        "表现：恶寒（或恶风）发热并见，头身疼痛，鼻塞流涕，脉浮，苔薄白。",
        "边界：与里证、半表半里证相鉴别；表邪入里后表证表现消失。",
      ],
      notice: "结构参考由 NUR 按教材第89–91页整理并经教师复习范围交叉核对，不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook, deepLoopSourceIds.exteriorInteriorReview, deepLoopSourceIds.editorial],
    },
    scoring: {
      id: "scoring-qb-term-exterior-superficies",
      standardVersion: "nur-writing-term-v1",
      status: "available",
      authority: "nur-platform",
      title: "NUR 名词解释完整度量表",
      totalPoints: 6,
      suggestedCharacters: 50,
      notice: "6分仅用于把答案拆开训练，不等同于当前课程每题3分，也不代表任课教师采分点。",
      answerFramework: ["是什么：先给出表证的规范定义。", "长什么样：写全恶寒发热、头身疼痛、脉浮、苔薄白等表现。", "如何辨：与里证、半表半里证区分并说明转化。"],
      criteria: [
        { id: "score-qb-term-exterior-definition", order: 1, perspective: "tcm", label: "定义准确", detail: "写明外邪侵入、正气抗邪于肌表的浅层证候。", points: 2 },
        { id: "score-qb-term-exterior-signs", order: 2, perspective: "tcm", label: "表现完整", detail: "写全恶寒发热并见、头身疼痛、脉浮等特征。", points: 2 },
        { id: "score-qb-term-exterior-differentiation", order: 3, perspective: "boundary", label: "鉴别与边界", detail: "说明与里证或半表半里的区别，或表邪入里的转化。", points: 2 },
      ],
      assistanceRules: [
        {
          criterionId: "score-qb-term-exterior-definition",
          memoryCriterionId: "exterior-interior-memory-evidence",
          signalGroups: [["外邪", "皮毛", "口鼻", "肌表"]],
          nextStepPrompt: "先把外邪侵入、正气抗邪于肌表的定义要素写全。",
          rewriteSuggestion: "表证是六淫等外邪经皮毛、口鼻侵入，正气抗邪于肌表浅层所表现的证候。",
        },
        {
          criterionId: "score-qb-term-exterior-signs",
          memoryCriterionId: "exterior-interior-memory-reasoning",
          signalGroups: [["恶寒", "发热", "脉浮", "头身疼痛", "苔薄白"]],
          nextStepPrompt: "补全恶寒发热并见、头身疼痛、脉浮、苔薄白等特征表现。",
          rewriteSuggestion: "以恶寒（或恶风）发热并见、头身疼痛、鼻塞流涕、脉浮、苔薄白为特征。",
        },
        {
          criterionId: "score-qb-term-exterior-differentiation",
          memoryCriterionId: "exterior-interior-memory-boundary",
          signalGroups: [["里证", "半表半里", "鉴别", "入里", "转化"]],
          nextStepPrompt: "补一句与里证或半表半里证的鉴别，或表邪入里的转化。",
          rewriteSuggestion: "需与里证、半表半里证相鉴别；表邪入里后表证表现消失而里证表现出现。",
        },
      ],
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook, deepLoopSourceIds.exteriorInteriorReview, deepLoopSourceIds.editorial],
    },
    sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook, deepLoopSourceIds.exteriorInteriorReview, deepLoopSourceIds.editorial],
  },
];

const caseItem: AssessmentItemDefinition = {
  id: "assessment-qb-case-inquiry-diet",
  order: 9,
  knowledgePointId: "kp-inquiry-diet-taste",
  questionKind: "case",
  status: "available",
  prompt:
    "病例：患者诉近月进食减少，食后腹胀，神疲，大便偏溏；同时近期口渴较前明显、夜间排尿增多。舌脉与实验室信息尚未提供。"
    + "请按证据分组 → 病机与评估方向 → 暂定辨证结论 → 鉴别排除与边界四步完成辨证推理，并分别说明中医与现代医学评估的边界。",
  promptSource: {
    authority: "nur-editorial",
    wording: "nur-adapted",
    locator: "NUR LEARN · 问饮食口味案例迁移（教材P60–61）",
    note: "案例由 NUR 根据教材P60–61、教师复习范围及公开临床参考组织，不是学校原题、真实患者诊断或任课教师评分。",
    sourceIds: [
      textbookSourceId,
      deepLoopSourceIds.editorial,
    ],
  },
  answer: {
    status: "available",
    authority: "nur-platform",
    confidence: "source-cross-checked",
    content: [
      "证据分组：饮食消化（进食减少、食后腹胀、大便偏溏）与全身伴随（神疲）一组；饮水排尿（口渴加重、夜间排尿增多）单独一组；舌脉与实验室信息缺失。",
      "病机与评估方向：中医由脾失健运偏虚方向解释消化与全身表现，仍需四诊复核；现代医学将口渴夜尿组织为待评估的代谢方向，将消化表现继续消化系统问诊。",
      "暂定辨证结论：现有证据更支持脾胃运化失健、偏虚方向；因舌脉与其他四诊尚缺，不能写成最终证型。",
      "鉴别排除与边界：不能仅凭口渴直接转向胃热、胃阴虚或消渴；两套解释共享证据但证候与现代疾病不可直接等同，本案例不提供临床诊断。",
    ],
    notice: "结构参考由 NUR 按已接入资料交叉核对，用于发现推理断点；不是学校标准答案、教师批改答案或医疗诊断。",
    sourceIds: [textbookSourceId, deepLoopSourceIds.editorial],
  },
  scoring: null,
  sourceIds: [textbookSourceId, deepLoopSourceIds.editorial],
};

export const questionBankAssessmentItems = [
  ...a1Items,
  ...fillItems,
  ...termItems,
  caseItem,
] as const satisfies readonly AssessmentItemDefinition[];

/** 知识点 → 新增题目 id 映射，用于把新题挂到所属知识点。 */
export const questionBankKnowledgePointItems: Record<string, readonly string[]> = {
  "kp-inquiry-diet-taste": [
    "assessment-qb-a1-diet-taste-thirst-polyuria",
    "assessment-qb-case-inquiry-diet",
  ],
  "kp-tongue-coating": [
    "assessment-qb-a1-tongue-greasy",
    "assessment-qb-a1-tongue-mouldy",
    "assessment-qb-fill-tongue-greasy",
  ],
  "kp-inquiry-cold-heat": [
    "assessment-qb-a1-cold-heat-superficies",
    "assessment-qb-a1-cold-heat-tidal",
    "assessment-qb-fill-cold-heat-superficies",
    "assessment-qb-term-cold-heat",
  ],
  "kp-pulse-common": [
    "assessment-qb-a1-pulse-floating",
    "assessment-qb-a1-pulse-rapid",
  ],
  "kp-eight-principles-exterior-interior": [
    "assessment-qb-a1-exterior-superficies-signs",
    "assessment-qb-a1-exterior-enters-interior",
    "assessment-qb-term-exterior-superficies",
  ],
  "kp-organs-spleen-stomach": [
    "assessment-qb-a1-spleen-qi-not-cold",
    "assessment-qb-a1-spleen-yang-increment",
  ],
  "kp-inspection-spirit": [
    "assessment-qb-a1-spirit-false",
  ],
};
