import type {
  AssessmentItemDefinition,
  CaseDefinition,
  KnowledgePointDefinition,
  KnowledgeLessonDefinition,
  LearningMemoryCriterionDefinition,
  LensContent,
  LensRelationshipDefinition,
  CourseDefinition,
  ContentStatus,
  KnowledgeEmphasis,
} from "@/types/learning";
import {
  deepAssessmentItems,
  deepKnowledgePoints,
  deepLoopSources,
  spleenReasoningCase,
} from "@/content/courses/tcm-diagnostics-deep-loops";
import {
  questionBankAssessmentItems,
  questionBankKnowledgePointItems,
} from "@/content/courses/tcm-diagnostics-question-bank";
import {
  completeAssessmentItems,
} from "@/content/courses/tcm-diagnostics-question-bank-complete";
import {
  completeAssessmentGroups,
  completeKnowledgePointItems,
  completeSubjectiveItems,
} from "@/content/courses/tcm-diagnostics-question-bank-groups";

/** 把新增题库题目挂到知识点（无新增时原样返回）。 */
function withQuestionBankItems(point: KnowledgePointDefinition): KnowledgePointDefinition {
  const extra = [
    ...(questionBankKnowledgePointItems[point.id] ?? []),
    ...(completeKnowledgePointItems[point.id] ?? []),
  ];
  if (extra.length === 0) {
    return point;
  }
  return {
    ...point,
    assessmentItemIds: [...point.assessmentItemIds, ...extra],
  };
}

type DemoKnowledgePointOptions = {
  evidenceFramework?: readonly string[];
  lenses?: readonly LensContent[];
  relationships?: readonly LensRelationshipDefinition[];
  learningMemoryCriteria?: readonly LearningMemoryCriterionDefinition[];
  sourceIds?: readonly string[];
  assessmentItemIds?: readonly string[];
  caseIds?: readonly string[];
  lesson?: KnowledgeLessonDefinition;
  contentStatus?: ContentStatus;
};

function createDemoKnowledgePoint(
  id: string,
  slug: string,
  order: number,
  title: string,
  note: string,
  emphasis: KnowledgeEmphasis,
  options: DemoKnowledgePointOptions = {},
): KnowledgePointDefinition {
  return {
    id,
    slug,
    order,
    title,
    note,
    emphasis,
    contentStatus: options.contentStatus ?? "demo",
    evidenceFramework: options.evidenceFramework ?? [],
    lenses: options.lenses ?? [],
    relationships: options.relationships ?? [],
    learningMemoryCriteria: options.learningMemoryCriteria ?? [],
    sourceIds: options.sourceIds ?? [],
    learningTaskIds: [],
    assessmentItemIds: options.assessmentItemIds ?? [],
    caseIds: options.caseIds ?? [],
    lesson: options.lesson ?? null,
  };
}

const introductionKnowledgePoints = [
  createDemoKnowledgePoint("kp-introduction-content", "main-content", 1, "中医诊断学的主要内容", "建立课程总框架", "基础"),
  createDemoKnowledgePoint("kp-introduction-diagnosis-pattern", "diagnosis-and-pattern", 2, "诊法与辨证的关系", "理解证据如何进入推理", "重点"),
  createDemoKnowledgePoint("kp-introduction-principles", "diagnostic-principles", 3, "中医诊断的基本原理", "司外揣内、见微知著", "高频", {
    assessmentItemIds: ["assessment-a1-introduction-principles"],
  }),
  createDemoKnowledgePoint("kp-introduction-rules", "diagnostic-rules", 4, "中医诊断的基本原则", "整体审察、诊法合参", "高频"),
] as const;

const inspectionKnowledgePoints = [
  createDemoKnowledgePoint("kp-inspection-spirit", "spirit", 1, "望神", "得神、少神、失神与假神", "高频", {
    assessmentItemIds: [
      "assessment-a1-inspection-spirit",
      ...questionBankKnowledgePointItems["kp-inspection-spirit"],
    ],
  }),
  createDemoKnowledgePoint("kp-inspection-complexion", "complexion", 2, "望色", "常色、病色与五色主病", "高频"),
  createDemoKnowledgePoint("kp-inspection-body", "body-form", 3, "望形体", "强弱、胖瘦与体质线索", "重点"),
  createDemoKnowledgePoint("kp-inspection-posture", "posture", 4, "望姿态", "动静姿态中的病性判断", "基础"),
] as const;

const tongueKnowledgePoints = [
  createDemoKnowledgePoint("kp-tongue-method", "tongue-method", 1, "舌诊原理与方法", "光线、姿势与观察顺序", "基础"),
  withQuestionBankItems(createDemoKnowledgePoint("kp-tongue-body", "tongue-body", 2, "望舌质", "舌色、舌形、舌态", "高频")),
  withQuestionBankItems(deepKnowledgePoints.tongue),
  createDemoKnowledgePoint("kp-tongue-analysis", "combined-analysis", 4, "舌象综合分析", "主次兼顾，动态判断", "重点"),
] as const;

const listeningSmellingKnowledgePoints = [
  createDemoKnowledgePoint("kp-listening-sounds", "sounds", 1, "听声音", "语声、呼吸、咳嗽与呕吐", "高频"),
  createDemoKnowledgePoint("kp-listening-language", "language", 2, "语言异常", "谵语、郑声、独语与错语", "高频"),
  createDemoKnowledgePoint("kp-listening-breath-cough", "breath-and-cough", 3, "呼吸与咳嗽", "声音特征对应虚实寒热", "重点"),
  createDemoKnowledgePoint("kp-smelling-odour", "odour", 4, "嗅气味", "病体与病室气味", "基础"),
] as const;

const inquiryDietSourceIds = {
  textbook: "source-inquiry-diet-textbook",
  teacherReview: "source-inquiry-diet-teacher-review",
  editorial: "source-inquiry-diet-editorial",
  indigestion: "source-niddk-indigestion-symptoms",
  diabetes: "source-niddk-diabetes-symptoms",
  taste: "source-nidcd-taste-disorders",
} as const;

const inquiryDietCaseId = "case-inquiry-diet-reasoning";

const inquiryDietTcmLens: LensContent = {
  id: "lens-inquiry-diet-tcm",
  perspective: "tcm",
  title: "中医视角",
  status: "verified",
  explanation: "按第三版教材先分别询问口渴与饮水、食欲与食量、口中异常味觉，再结合病程、伴随表现和其他三诊证据判断脾胃、津液及寒热虚实。",
  clinicalObservations: [
    "口渴程度、饮量与冷热偏好",
    "食欲食量及特殊食欲变化",
    "口淡、苦、甜、酸、咸、涩、黏腻",
    "舌脉与其他四诊复核",
  ],
  missingLabel: null,
  sourceIds: [inquiryDietSourceIds.textbook, inquiryDietSourceIds.teacherReview],
};

const inquiryDietModernLens: LensContent = {
  id: "lens-inquiry-diet-modern",
  perspective: "modern-medicine",
  title: "现代医学视角",
  status: "available",
  explanation: "同一组问诊证据还需记录早饱或餐后饱胀、明显口渴与多尿、味觉或嗅觉变化，并据此提出需要进一步鉴别与评估的方向。",
  clinicalObservations: ["早饱与餐后饱胀", "明显口渴与多尿", "味觉与嗅觉变化", "药物、口腔与全身伴随线索"],
  missingLabel: null,
  sourceIds: [
    inquiryDietSourceIds.indigestion,
    inquiryDietSourceIds.diabetes,
    inquiryDietSourceIds.taste,
  ],
};

const inquiryDietLesson = {
  id: "lesson-inquiry-diet-taste",
  status: "available",
  eyebrow: "INQUIRY · EVIDENCE TO ANSWER",
  objective: "把饮食口味问诊拆成可核对证据，分别完成中医辨证与现代医学分析，并在作答中明确二者边界。",
  durationMinutes: 45,
  sections: [
    { id: "evidence", order: 1, indexLabel: "01", title: "取证", detail: "问全四组线索" },
    { id: "compare", order: 2, indexLabel: "02", title: "对照", detail: "并列两条推理链" },
    { id: "output", order: 3, indexLabel: "03", title: "输出", detail: "按采分点成句" },
    { id: "transfer", order: 4, indexLabel: "04", title: "迁移", detail: "回到案例复核" },
  ],
  evidenceGroups: [
    {
      id: "evidence-appetite-intake",
      order: 1,
      title: "食欲与食量",
      detail: "分清食欲、实际食量、特殊食欲表现及其病程变化。",
      prompts: [
        { id: "prompt-appetite", label: "食欲食量", question: "想不想吃、实际吃多少，有无纳少、纳呆或早饱？" },
        { id: "prompt-special-appetite", label: "特殊表现", question: "有无厌食、消谷善饥、饥不欲食或偏嗜食物与异物？" },
        { id: "prompt-appetite-course", label: "病程变化", question: "与平时相比如何，久病中是否突然食欲异常转强？" },
      ],
      sourceIds: [
        inquiryDietSourceIds.textbook,
        inquiryDietSourceIds.teacherReview,
        inquiryDietSourceIds.indigestion,
      ],
    },
    {
      id: "evidence-thirst-drinking",
      order: 2,
      title: "口渴与饮水",
      detail: "把是否口渴、饮量、偏好和相关排尿变化分开记录。",
      prompts: [
        { id: "prompt-thirst", label: "口渴", question: "口不渴、口干微渴还是大渴，何时最突出？" },
        { id: "prompt-drinking", label: "饮水", question: "饮水量、频次及冷热偏好如何？" },
        { id: "prompt-thirst-context", label: "反应与伴随", question: "有无水入即吐、但欲漱水不咽，或多尿、多食、消瘦？" },
      ],
      sourceIds: [
        inquiryDietSourceIds.textbook,
        inquiryDietSourceIds.teacherReview,
        inquiryDietSourceIds.diabetes,
      ],
    },
    {
      id: "evidence-taste-smell",
      order: 3,
      title: "口中味与嗅味觉",
      detail: "中医口中异常味与现代嗅味觉改变分别询问，不直接等同。",
      prompts: [
        { id: "prompt-mouth-taste", label: "口中异常味", question: "是否自觉口淡、苦、甜、酸、咸、涩或黏腻？" },
        { id: "prompt-taste-change", label: "味觉", question: "食物味道是否变弱、变形或出现异常味？" },
        { id: "prompt-smell-trigger", label: "相关因素", question: "近期嗅觉、口腔状态、感染或用药是否变化？" },
      ],
      sourceIds: [
        inquiryDietSourceIds.textbook,
        inquiryDietSourceIds.teacherReview,
        inquiryDietSourceIds.taste,
      ],
    },
    {
      id: "evidence-context-safety",
      order: 4,
      title: "伴随证据与安全边界",
      detail: "症状不能孤立解释；补足病程、体重和需要及时评估的线索。",
      prompts: [
        { id: "prompt-course", label: "病程", question: "何时开始，持续还是反复，与何种情境相关？" },
        { id: "prompt-weight", label: "全身变化", question: "体重、精神体力或其他全身表现是否改变？" },
        { id: "prompt-red-flags", label: "警示线索", question: "是否出现持续呕吐、吞咽困难、出血表现或明显非意愿体重下降？" },
      ],
      sourceIds: [inquiryDietSourceIds.indigestion, inquiryDietSourceIds.diabetes],
    },
  ],
  lensBlocks: [
    {
      id: "reasoning-inquiry-diet-tcm",
      perspective: "tcm",
      status: "verified",
      eyebrow: "TCM REASONING · TEXTBOOK VERIFIED",
      title: "从饮食口味证据进入辨证",
      summary: "教材把本节分为口渴与饮水、食欲与食量、口味三组。作答先规范描述表现，再写常见临床意义，并以其他四诊证据复核。",
      reasoningSteps: [
        "口渴须继续辨饮量、冷热偏好及饮后反应；口不渴、口渴欲饮与渴不多饮的意义不同。",
        "食欲食量须区分减退、厌食、消谷善饥、饥不欲食、偏嗜异物及病程中的突然变化。",
        "口淡、苦、甜、酸、咸、涩、黏腻分别提供不同辨证方向，但都不能脱离伴随表现定证。",
        "最终结论仍需结合舌象、脉象和其他四诊资料，避免从一个词直接跳到证名。",
      ],
      boundaryNote: "教材术语与教师复习范围已核对；任课教师主观题逐项采分标准尚未提供。",
      sourceIds: [inquiryDietSourceIds.textbook, inquiryDietSourceIds.teacherReview],
    },
    {
      id: "reasoning-inquiry-diet-modern",
      perspective: "modern-medicine",
      status: "available",
      eyebrow: "MODERN MEDICINE · ASSESSABLE",
      title: "从症状组合提出鉴别与评估",
      summary: "现代医学部分不是装饰性补充：需要准确复述症状组合、提出合理鉴别方向，并识别需要进一步评估的安全线索。",
      reasoningSteps: [
        "早饱或少量进食后持续饱胀属于需要进一步追问的消化不良相关表现。",
        "明显口渴若伴排尿增多、饥饿或疲乏，应记录为代谢评估的重要症状组合。",
        "味觉改变需同时追问嗅觉、近期感染、药物和口腔牙科因素，避免把主观口味直接解释为单一疾病。",
      ],
      boundaryNote: "作答训练评估的是观察、鉴别与安全意识，不以单个症状直接下现代医学诊断。",
      sourceIds: [
        inquiryDietSourceIds.indigestion,
        inquiryDietSourceIds.diabetes,
        inquiryDietSourceIds.taste,
      ],
    },
  ],
  scoring: {
    id: "scoring-inquiry-diet-integrated-answer",
    status: "available",
    authority: "nur-platform",
    title: "中西医并列作答训练",
    totalPoints: 10,
    notice: "这是 NUR 平台训练量表，不代表任课教师真实题目或评分标准；接入课程资料后再校准。",
    prompt: "患者近两周食欲下降，少量进食即觉脘腹胀满，口渴但饮水不多，近来觉得食物味道变淡。请写出你还需补问的证据，并分别说明中医与现代医学分析方向。",
    answerFramework: [
      "先补证据：病程与诱因 → 食欲食量及特殊表现 → 口渴饮水 → 口中异常味/嗅味觉 → 伴随与警示线索。",
      "中医部分：证据 → 可能的脾胃/津液/寒热虚实线索 → 需由哪些四诊证据复核。",
      "现代医学部分：症状组合 → 鉴别或评估方向 → 安全线索与下一步信息。",
      "边界句：两套解释并列记录、互助理解，但证候与疾病不可直接等同。",
    ],
    criteria: [
      { id: "score-tcm-evidence", order: 1, perspective: "tcm", label: "中医证据完整", detail: "写出口渴饮水、食欲食量、口中异常味的关键追问，并补充四诊复核。", points: 2 },
      { id: "score-tcm-reasoning", order: 2, perspective: "tcm", label: "中医推理成链", detail: "从证据写到脾胃、津液及寒热虚实方向，不只报结论。", points: 2 },
      { id: "score-modern-pattern", order: 3, perspective: "modern-medicine", label: "现代症状组合", detail: "准确组织早饱、口渴、多尿或嗅味觉变化等组合。", points: 2 },
      { id: "score-modern-assessment", order: 4, perspective: "modern-medicine", label: "现代鉴别与安全", detail: "提出进一步评估方向并识别警示线索，避免单症状下诊断。", points: 2 },
      { id: "score-boundary", order: 5, perspective: "boundary", label: "关系边界清楚", detail: "明确可关联与帮助理解之处，同时写明不可直接等同。", points: 2 },
    ],
    sourceIds: [
      inquiryDietSourceIds.textbook,
      inquiryDietSourceIds.teacherReview,
      inquiryDietSourceIds.editorial,
      inquiryDietSourceIds.indigestion,
      inquiryDietSourceIds.diabetes,
      inquiryDietSourceIds.taste,
    ],
  },
  transferCaseId: inquiryDietCaseId,
  transferExercise: null,
  sourceIds: [
    inquiryDietSourceIds.textbook,
    inquiryDietSourceIds.teacherReview,
    inquiryDietSourceIds.editorial,
    inquiryDietSourceIds.indigestion,
    inquiryDietSourceIds.diabetes,
    inquiryDietSourceIds.taste,
  ],
} satisfies KnowledgeLessonDefinition;

const inquiryDietReasoningCase = {
  id: inquiryDietCaseId,
  order: 1,
  knowledgePointIds: ["kp-inquiry-diet-taste"],
  status: "available",
  eyebrow: "CASE REASONING · FIND THE BROKEN LINK",
  title: "两组线索不能合成一个结论",
  stem: "患者诉近月进食减少，食后腹胀，神疲，大便偏溏；同时近期口渴较前明显、夜间排尿增多。舌脉与实验室信息尚未提供。",
  promptSource: {
    authority: "nur-editorial",
    wording: "nur-adapted",
    locator: "NUR LEARN · 问饮食口味案例迁移",
    note: "案例由 NUR 根据教材P60–61、教师复习范围及公开临床参考组织，不是学校原题或真实患者诊断。",
    sourceIds: [
      inquiryDietSourceIds.textbook,
      inquiryDietSourceIds.teacherReview,
      inquiryDietSourceIds.editorial,
      inquiryDietSourceIds.indigestion,
      inquiryDietSourceIds.diabetes,
    ],
  },
  evidence: [
    { id: "case-evidence-intake", order: 1, label: "进食减少", detail: "近一个月食量下降", role: "key", requiredForReasoning: true },
    { id: "case-evidence-distension", order: 2, label: "食后腹胀", detail: "进食后出现消化道不适", role: "key", requiredForReasoning: true },
    { id: "case-evidence-fatigue", order: 3, label: "神疲", detail: "伴随全身状态变化", role: "supporting", requiredForReasoning: true },
    { id: "case-evidence-loose-stool", order: 4, label: "大便偏溏", detail: "与脾胃运化方向共同复核", role: "supporting", requiredForReasoning: true },
    { id: "case-evidence-thirst", order: 5, label: "口渴加重", detail: "近期较前明显", role: "key", requiredForReasoning: true },
    { id: "case-evidence-nocturia", order: 6, label: "夜间排尿增多", detail: "需单独进入现代医学评估", role: "key", requiredForReasoning: true },
    { id: "case-evidence-tongue-pulse", order: 7, label: "舌脉缺失", detail: "中医定证仍缺关键复核信息", role: "missing", requiredForReasoning: true },
    { id: "case-evidence-lab", order: 8, label: "实验室信息缺失", detail: "现代医学只能提出评估方向", role: "missing", requiredForReasoning: true },
  ],
  reasoningSteps: [
    {
      id: "case-step-evidence",
      order: 1,
      stage: "evidence",
      label: "证据分组",
      prompt: "把现有表现按线索组重新组织，并写出目前最影响结论可靠性的缺失信息。",
      placeholder: "例如：饮食与消化表现……饮水排尿表现……仍缺……",
      minimumCharacters: 70,
      answerFramework: [
        "饮食与消化：进食减少、食后腹胀、大便偏溏；全身伴随：神疲。",
        "饮水排尿：口渴加重、夜间排尿增多，不能被并入同一个中医或现代结论。",
        "中医仍缺舌脉及更完整四诊；现代医学仍缺体重、尿量、用药和实验室等评估信息。",
      ],
      sourceIds: [inquiryDietSourceIds.textbook, inquiryDietSourceIds.editorial, inquiryDietSourceIds.diabetes],
    },
    {
      id: "case-step-mechanism",
      order: 2,
      stage: "mechanism",
      label: "病机与评估方向",
      prompt: "分别写出中医病机方向和现代医学评估方向，不要先报一个确定诊断。",
      placeholder: "中医证据如何指向病位、病性或运化变化；现代医学组合需要评估什么……",
      minimumCharacters: 90,
      answerFramework: [
        "中医：进食减少、食后腹胀、神疲、便溏可提示脾胃运化失健及偏虚方向，但仍需舌脉与其他四诊复核。",
        "现代医学：口渴与夜尿增多需要代谢方向评估；进食减少与食后腹胀需要继续消化系统问诊。",
        "两条推理链共享症状记录，但病机、评估方法和结论依据分别成立。",
      ],
      sourceIds: [
        inquiryDietSourceIds.textbook,
        inquiryDietSourceIds.teacherReview,
        inquiryDietSourceIds.editorial,
        inquiryDietSourceIds.indigestion,
        inquiryDietSourceIds.diabetes,
      ],
    },
    {
      id: "case-step-syndrome",
      order: 3,
      stage: "syndrome",
      label: "暂定辨证结论",
      prompt: "给出当前能支持到什么程度的中医辨证方向，并主动写明不能下确定结论的原因。",
      placeholder: "现有证据更支持……方向；但因为缺少……只能作为暂定判断……",
      minimumCharacters: 70,
      answerFramework: [
        "现有消化与全身证据更支持脾胃运化失健、偏虚的辨证方向。",
        "舌脉、寒热、口渴饮水偏好及其他四诊未补全，因此不能把方向直接写成最终证型。",
        "口渴和夜尿增多也不能单独证明某个中医证候或现代疾病。",
      ],
      sourceIds: [inquiryDietSourceIds.textbook, inquiryDietSourceIds.teacherReview, inquiryDietSourceIds.editorial],
    },
    {
      id: "case-step-differential",
      order: 4,
      stage: "differential",
      label: "鉴别排除与边界",
      prompt: "排除至少一个容易被单一症状带偏的方向，并分别写出中医复核、现代评估和关系边界。",
      placeholder: "不能仅凭口渴判断……；需要用……复核；现代医学应……；二者不可……",
      minimumCharacters: 110,
      answerFramework: [
        "不能仅凭口渴直接转向胃热、胃阴虚或消渴；便溏、神疲和食后腹胀仍要求复核脾胃偏虚方向。",
        "中医用舌脉、寒热、饮水偏好和其他四诊继续鉴别；现代医学对口渴、夜尿及消化表现分别补问并安排必要评估。",
        "中医证候与现代医学疾病不可直接等同；本案例只训练推理结构，不提供临床诊断。",
      ],
      sourceIds: [
        inquiryDietSourceIds.textbook,
        inquiryDietSourceIds.teacherReview,
        inquiryDietSourceIds.editorial,
        inquiryDietSourceIds.indigestion,
        inquiryDietSourceIds.diabetes,
      ],
    },
  ],
  answer: {
    authority: "nur-platform",
    confidence: "source-cross-checked",
    notice: "结构参考由 NUR 按已接入资料交叉核对，用于发现推理断点；不是学校标准答案、教师批改答案或医疗诊断。",
    sourceIds: [
      inquiryDietSourceIds.textbook,
      inquiryDietSourceIds.teacherReview,
      inquiryDietSourceIds.editorial,
      inquiryDietSourceIds.indigestion,
      inquiryDietSourceIds.diabetes,
    ],
  },
  scoring: {
    id: "scoring-case-inquiry-diet-reasoning",
    standardVersion: "nur-case-v1",
    status: "available",
    authority: "nur-platform",
    title: "NUR 推理链自核量表",
    totalPoints: 10,
    notice: "该10分仅表示平台推理训练结构，不代表本课程案例题真实采分点；教师评分标准仍待提供。",
    criteria: [
      { id: "case-score-evidence", order: 1, stage: "evidence", perspective: "shared-evidence", label: "证据分组完整", detail: "区分饮食消化、全身、饮水排尿及缺失信息，没有漏掉会改变结论的证据。", points: 2 },
      { id: "case-score-mechanism", order: 2, stage: "mechanism", perspective: "tcm", label: "病机推理成链", detail: "由现有证据写到脾胃运化与虚实方向，并说明仍需四诊复核。", points: 2 },
      { id: "case-score-syndrome", order: 3, stage: "syndrome", perspective: "tcm", label: "结论强度恰当", detail: "给出暂定辨证方向，同时主动限制结论，不因缺失舌脉而强行定证。", points: 2 },
      { id: "case-score-modern", order: 4, stage: "differential", perspective: "modern-medicine", label: "现代评估独立", detail: "把口渴夜尿与消化表现组织成待评估组合，不以单症状下现代诊断。", points: 2 },
      { id: "case-score-boundary", order: 5, stage: "differential", perspective: "boundary", label: "鉴别与边界明确", detail: "写出反证、下一步复核，并明确中医证候与现代疾病不可直接等同。", points: 2 },
    ],
    assistanceRules: [
      {
        criterionId: "case-score-evidence",
        memoryCriterionId: "memory-evidence-completeness",
        signalGroups: [
          ["进食", "饮食", "腹胀", "便溏"],
          ["口渴", "饮水", "夜尿", "排尿"],
          ["缺", "舌脉", "实验室", "未提供"],
        ],
        nextStepPrompt: "先把饮食消化、饮水排尿和缺失信息分成三组，再限制结论强度。",
        rewriteSuggestion: "现有证据应分为饮食消化、饮水排尿与缺失信息三组，其中舌脉和实验室信息缺失会限制结论强度。",
      },
      {
        criterionId: "case-score-mechanism",
        memoryCriterionId: "memory-reasoning-chain",
        signalGroups: [
          ["脾胃", "运化", "偏虚"],
          ["评估", "代谢", "消化"],
        ],
        nextStepPrompt: "分别补一条中医病机链和现代医学评估链，不要把两者合成一个诊断。",
        rewriteSuggestion: "中医方面可由进食减少、食后腹胀与便溏推至脾胃运化失健的偏虚方向；现代医学方面则需分别评估代谢与消化系统线索。",
      },
      {
        criterionId: "case-score-syndrome",
        memoryCriterionId: "memory-conclusion-boundary",
        signalGroups: [
          ["暂定", "方向", "支持"],
          ["不能", "缺少", "复核", "尚缺"],
        ],
        nextStepPrompt: "把“支持什么方向”和“为什么还不能定证”写在同一段。",
        rewriteSuggestion: "现有证据仅支持脾胃运化失健、偏虚的暂定方向；因舌脉与其他四诊尚缺，不能据此写成最终证型。",
      },
      {
        criterionId: "case-score-modern",
        memoryCriterionId: "memory-modern-assessment",
        signalGroups: [
          ["口渴", "夜尿", "多尿"],
          ["评估", "代谢", "检查", "实验室"],
        ],
        nextStepPrompt: "把口渴夜尿写成待评估组合，并说明需要补什么信息。",
        rewriteSuggestion: "口渴加重与夜尿增多应作为待评估的症状组合，继续补充尿量、体重、用药和必要的代谢检查，而不能据单一表现下诊断。",
      },
      {
        criterionId: "case-score-boundary",
        memoryCriterionId: "memory-conclusion-boundary",
        signalGroups: [
          ["不可直接等同", "不能直接等同", "分别论证"],
          ["鉴别", "复核", "不能仅凭", "下一步"],
        ],
        nextStepPrompt: "补一个容易被单症状带偏的方向，再写中医复核、现代评估和不可直接等同。",
        rewriteSuggestion: "不能仅凭口渴直接定证或下现代诊断；中医需结合舌脉等四诊复核，现代医学需独立评估，二者结论不可直接等同。",
      },
    ],
    sourceIds: [
      inquiryDietSourceIds.textbook,
      inquiryDietSourceIds.teacherReview,
      inquiryDietSourceIds.editorial,
      inquiryDietSourceIds.indigestion,
      inquiryDietSourceIds.diabetes,
    ],
  },
  boundaryNote: "本案例仅用于学习推理结构，不提供临床诊断、个人医疗建议或任课教师真实评分。",
  sourceIds: [
    inquiryDietSourceIds.textbook,
    inquiryDietSourceIds.teacherReview,
    inquiryDietSourceIds.editorial,
    inquiryDietSourceIds.indigestion,
    inquiryDietSourceIds.diabetes,
  ],
} satisfies CaseDefinition;

const inquiryDietAssessmentItemIds = {
  whitebookThirstFill: "assessment-whitebook-inquiry-diet-thirst-fill",
  whitebookBlandTasteFill: "assessment-whitebook-inquiry-diet-bland-taste-fill",
  termExcessiveHunger: "assessment-writing-inquiry-diet-excessive-hunger-term",
  shortAnswerInquiryStructure: "assessment-writing-inquiry-diet-structure-short-answer",
  a1DietTaste: "assessment-a1-inquiry-diet-taste",
  a1IntroPrinciples: "assessment-a1-introduction-principles",
  a1InspectionSpirit: "assessment-a1-inspection-spirit",
} as const;

const inquiryDietLearningMemoryCriteria = [
  {
    id: "memory-evidence-completeness",
    order: 1,
    label: "证据与定义要素不完整",
    detail: "作答常漏掉会改变结论的症状组、定义要素或缺失信息。",
  },
  {
    id: "memory-reasoning-chain",
    order: 2,
    label: "推理链缺少连接",
    detail: "从证据到病机或评估方向的中间论证没有写成完整句。",
  },
  {
    id: "memory-modern-assessment",
    order: 3,
    label: "现代医学评估链不完整",
    detail: "症状组合、待评估方向或安全边界没有独立说明。",
  },
  {
    id: "memory-conclusion-boundary",
    order: 4,
    label: "结论强度与关系边界缺失",
    detail: "没有主动限制结论，或没有说明中医证候与现代疾病不可直接等同。",
  },
] as const satisfies readonly LearningMemoryCriterionDefinition[];

const inquiryDietAssessmentItems = [
  {
    id: inquiryDietAssessmentItemIds.whitebookThirstFill,
    order: 1,
    knowledgePointId: "kp-inquiry-diet-taste",
    questionKind: "fill",
    status: "available",
    prompt: "消谷善饥，兼多饮多尿，形体消瘦者，多见于＿＿病，因＿＿，所致。",
    promptSource: {
      authority: "school",
      wording: "source-verbatim",
      locator: "学校白皮书《练习06卷》· 五、填充题第4题",
      note: "题干已按学校白皮书原文录入；原文件未附可核验答案。",
      sourceIds: ["source-tcm-diagnostics-whitebook"],
    },
    answer: {
      status: "missing",
      authority: null,
      confidence: "missing",
      content: null,
      notice: "白皮书原文件未附答案，暂不显示为标准答案。",
      sourceIds: [],
    },
    scoring: null,
    sourceIds: ["source-tcm-diagnostics-whitebook"],
  },
  {
    id: inquiryDietAssessmentItemIds.whitebookBlandTasteFill,
    order: 2,
    knowledgePointId: "kp-inquiry-diet-taste",
    questionKind: "fill",
    status: "available",
    prompt: "病人口淡乏味，多见于＿＿、＿＿及＿＿。",
    promptSource: {
      authority: "school",
      wording: "source-verbatim",
      locator: "学校白皮书《练习06卷》· 五、填充题第5题",
      note: "题干已按学校白皮书原文录入；原文件未附可核验答案。",
      sourceIds: ["source-tcm-diagnostics-whitebook"],
    },
    answer: {
      status: "missing",
      authority: null,
      confidence: "missing",
      content: null,
      notice: "白皮书原文件未附答案，暂不显示为标准答案。",
      sourceIds: [],
    },
    scoring: null,
    sourceIds: ["source-tcm-diagnostics-whitebook"],
  },
  {
    id: inquiryDietAssessmentItemIds.termExcessiveHunger,
    order: 3,
    knowledgePointId: "kp-inquiry-diet-taste",
    questionKind: "term",
    status: "available",
    prompt: "名词解释：消谷善饥。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "由学校白皮书填充题第4题转写为主观表达训练",
      note: "这是 NUR 为训练完整表达所作的题型改写，不是学校白皮书原题。",
      sourceIds: [
        "source-tcm-diagnostics-whitebook",
        inquiryDietSourceIds.textbook,
        inquiryDietSourceIds.teacherReview,
        inquiryDietSourceIds.editorial,
      ],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: [
        "先写定义：食欲过于旺盛、食量增多，食后不久即感饥饿，又称多食易饥。",
        "再写辨证分支：兼口渴心烦、口臭便秘可见胃火亢盛；兼多饮多尿、形体消瘦可见消渴；兼便溏可见胃强脾弱。",
        "最后写边界：须结合兼症与其他四诊证据判断，不能只凭“易饥”直接定证。",
      ],
      notice: "结构参考由 NUR 按教材第60–61页整理并经教师复习范围交叉核对，不是学校或任课教师标准答案。",
      sourceIds: [
        inquiryDietSourceIds.textbook,
        inquiryDietSourceIds.teacherReview,
        inquiryDietSourceIds.editorial,
      ],
    },
    scoring: {
      id: "scoring-writing-inquiry-diet-excessive-hunger-term",
      standardVersion: "nur-writing-term-v1",
      status: "available",
      authority: "nur-platform",
      title: "NUR 名词解释完整度量表",
      totalPoints: 6,
      suggestedCharacters: 45,
      notice: "6分仅用于把答案拆开训练，不等同于当前课程每题3分，也不代表任课教师采分点。",
      answerFramework: [
        "是什么：先用一句话给出规范定义。",
        "长什么样：补足食欲、食量和饥饿出现时间三个要素。",
        "如何辨：用兼症区分常见方向，并保留四诊复核边界。",
      ],
      criteria: [
        { id: "score-term-definition", order: 1, perspective: "tcm", label: "定义准确", detail: "写明食欲旺盛、食量增多、食后不久即饥饿。", points: 2 },
        { id: "score-term-synonym", order: 2, perspective: "tcm", label: "术语完整", detail: "写出又称多食易饥，并保持术语表达规范。", points: 2 },
        { id: "score-term-differentiation", order: 3, perspective: "tcm", label: "辨证不跳步", detail: "至少用一组兼症说明不同辨证方向，或明确需结合兼症复核。", points: 2 },
      ],
      assistanceRules: [
        {
          criterionId: "score-term-definition",
          memoryCriterionId: "memory-evidence-completeness",
          signalGroups: [
            ["食欲", "胃口"],
            ["食量", "多食"],
            ["食后不久", "易饥", "饥饿", "善饥"],
          ],
          nextStepPrompt: "先把食欲、食量和食后不久即饥三个定义要素写全。",
          rewriteSuggestion: "消谷善饥是指食欲过于旺盛、食量增多，食后不久即感饥饿。",
        },
        {
          criterionId: "score-term-synonym",
          memoryCriterionId: "memory-evidence-completeness",
          signalGroups: [["多食易饥", "又称"]],
          nextStepPrompt: "在定义后补上规范同义表述“多食易饥”。",
          rewriteSuggestion: "该表现又称多食易饥。",
        },
        {
          criterionId: "score-term-differentiation",
          memoryCriterionId: "memory-conclusion-boundary",
          signalGroups: [
            ["兼", "伴", "若", "如"],
            ["结合", "复核", "不能", "辨证"],
          ],
          nextStepPrompt: "补一组兼症分支，并写明不能只凭“易饥”直接定证。",
          rewriteSuggestion: "还需结合口渴、便溏等兼症及其他四诊资料辨别不同方向，不能只凭“易饥”直接定证。",
        },
      ],
      sourceIds: [
        inquiryDietSourceIds.textbook,
        inquiryDietSourceIds.teacherReview,
        inquiryDietSourceIds.editorial,
      ],
    },
    sourceIds: [
      "source-tcm-diagnostics-whitebook",
      inquiryDietSourceIds.textbook,
      inquiryDietSourceIds.teacherReview,
      inquiryDietSourceIds.editorial,
    ],
  },
  {
    id: inquiryDietAssessmentItemIds.shortAnswerInquiryStructure,
    order: 4,
    knowledgePointId: "kp-inquiry-diet-taste",
    questionKind: "short-answer",
    status: "available",
    prompt: "简述问饮食口味时应询问的主要内容，并说明这些信息如何分别进入中医辨证与现代医学评估。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "由学校白皮书填充题第4–5题与教材第60–61页转写",
      note: "学校材料证明相关内容进入练习范围；本简答题及现代医学部分由 NUR 组织，不冒充学校原题。",
      sourceIds: [
        "source-tcm-diagnostics-whitebook",
        inquiryDietSourceIds.textbook,
        inquiryDietSourceIds.teacherReview,
        inquiryDietSourceIds.editorial,
        inquiryDietSourceIds.indigestion,
        inquiryDietSourceIds.diabetes,
        inquiryDietSourceIds.taste,
      ],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: [
        "取证：分别询问口渴与饮水、食欲与食量、食物喜恶、口中异常味及病程和伴随表现。",
        "中医：依据津液盛衰与输布、脾胃功能及寒热虚实组织辨证方向，并结合舌脉等四诊资料复核。",
        "现代医学：把早饱、口渴多尿、嗅味觉改变等组织成症状组合，提出消化、代谢、口腔或用药等评估方向并识别警示线索。",
        "关系边界：两种视角共享观察证据，但证候与现代疾病不可直接等同，结论必须分别论证。",
      ],
      notice: "结构参考由 NUR 根据已核验教材、教师范围与公开临床资料整理，不是任课教师真实答案。",
      sourceIds: [
        inquiryDietSourceIds.textbook,
        inquiryDietSourceIds.teacherReview,
        inquiryDietSourceIds.editorial,
        inquiryDietSourceIds.indigestion,
        inquiryDietSourceIds.diabetes,
        inquiryDietSourceIds.taste,
      ],
    },
    scoring: {
      id: "scoring-writing-inquiry-diet-structure-short-answer",
      standardVersion: "nur-writing-short-v1",
      status: "available",
      authority: "nur-platform",
      title: "NUR 中西医并列简答量表",
      totalPoints: 10,
      suggestedCharacters: 140,
      notice: "这是平台训练量表；任课教师真实评分标准仍未提供。",
      answerFramework: [
        "列全取证对象：口渴饮水、食欲食量、喜恶口味、病程伴随。",
        "中医成链：证据 → 脾胃/津液/寒热虚实方向 → 四诊复核。",
        "现代成链：症状组合 → 鉴别与评估方向 → 安全线索。",
        "补边界句：共享证据，分别结论，不直接等同。",
      ],
      criteria: [
        { id: "score-short-tcm-evidence", order: 1, perspective: "tcm", label: "中医取证完整", detail: "覆盖饮水、饮食、口味与伴随证据，不只罗列一个表现。", points: 2 },
        { id: "score-short-tcm-reasoning", order: 2, perspective: "tcm", label: "中医推理成链", detail: "从证据写到脾胃、津液及寒热虚实，并说明四诊复核。", points: 2 },
        { id: "score-short-modern-pattern", order: 3, perspective: "modern-medicine", label: "现代症状组合", detail: "组织早饱、口渴多尿、嗅味觉改变等可评估组合。", points: 2 },
        { id: "score-short-modern-safety", order: 4, perspective: "modern-medicine", label: "现代评估与安全", detail: "提出进一步评估方向或警示线索，不从单症状直接下诊断。", points: 2 },
        { id: "score-short-boundary", order: 5, perspective: "boundary", label: "关系边界清楚", detail: "明确共享观察证据，但证候与现代疾病不可直接等同。", points: 2 },
      ],
      assistanceRules: [
        {
          criterionId: "score-short-tcm-evidence",
          memoryCriterionId: "memory-evidence-completeness",
          signalGroups: [
            ["口渴", "饮水"],
            ["食欲", "食量"],
            ["口味", "味觉", "嗅觉"],
            ["病程", "伴随", "舌脉"],
          ],
          nextStepPrompt: "按饮水、饮食、口味、病程伴随四组补齐取证对象。",
          rewriteSuggestion: "问诊应分别覆盖口渴与饮水、食欲与食量、食物喜恶和口中异常味，并补充病程及伴随表现。",
        },
        {
          criterionId: "score-short-tcm-reasoning",
          memoryCriterionId: "memory-reasoning-chain",
          signalGroups: [
            ["脾胃", "津液"],
            ["寒热", "虚实", "四诊", "舌脉"],
          ],
          nextStepPrompt: "把中医部分写成“证据 → 脾胃/津液/寒热虚实 → 四诊复核”。",
          rewriteSuggestion: "中医部分应由问诊证据推至脾胃、津液及寒热虚实方向，再结合舌脉等四诊资料复核。",
        },
        {
          criterionId: "score-short-modern-pattern",
          memoryCriterionId: "memory-modern-assessment",
          signalGroups: [
            ["早饱", "腹胀", "口渴", "多尿", "味觉", "嗅觉"],
            ["症状组合", "组合", "分别"],
          ],
          nextStepPrompt: "先把早饱、口渴多尿和嗅味觉改变组织成可评估的症状组合。",
          rewriteSuggestion: "现代医学部分应把早饱或餐后饱胀、口渴多尿及嗅味觉改变组织成不同的症状组合。",
        },
        {
          criterionId: "score-short-modern-safety",
          memoryCriterionId: "memory-modern-assessment",
          signalGroups: [
            ["评估", "鉴别", "检查"],
            ["警示", "安全", "不能", "避免"],
          ],
          nextStepPrompt: "补出评估方向或警示线索，并写明不能从单症状直接下诊断。",
          rewriteSuggestion: "应据症状组合提出消化、代谢、口腔或用药等评估方向并识别警示线索，不能从单一症状直接下诊断。",
        },
        {
          criterionId: "score-short-boundary",
          memoryCriterionId: "memory-conclusion-boundary",
          signalGroups: [["不可直接等同", "不能直接等同", "分别论证", "分别结论"]],
          nextStepPrompt: "用一句话说明两种视角共享证据，但结论分别论证、不可直接等同。",
          rewriteSuggestion: "两种视角可以共享观察证据，但中医证候与现代医学疾病必须分别论证，不可直接等同。",
        },
      ],
      sourceIds: [
        inquiryDietSourceIds.textbook,
        inquiryDietSourceIds.teacherReview,
        inquiryDietSourceIds.editorial,
        inquiryDietSourceIds.indigestion,
        inquiryDietSourceIds.diabetes,
        inquiryDietSourceIds.taste,
      ],
    },
    sourceIds: [
      "source-tcm-diagnostics-whitebook",
      inquiryDietSourceIds.textbook,
      inquiryDietSourceIds.teacherReview,
      inquiryDietSourceIds.editorial,
      inquiryDietSourceIds.indigestion,
      inquiryDietSourceIds.diabetes,
      inquiryDietSourceIds.taste,
    ],
  },
  {
    id: inquiryDietAssessmentItemIds.a1DietTaste,
    order: 5,
    knowledgePointId: "kp-inquiry-diet-taste",
    questionKind: "a1-single",
    status: "available",
    prompt: "消谷善饥最常见于下列哪种情况？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第60–61页问饮食口味内容",
      note: "NUR 改编自教材核心知识点，不冒充学校原题。",
      sourceIds: [inquiryDietSourceIds.textbook],
    },
    choices: [
      "脾胃湿热证",
      "胃强脾弱证",
      "肝胃不和证",
      "脾胃虚寒证",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["消谷善饥指患者食欲亢进，食后不久即感饥饿，多因胃火炽盛或胃强脾弱所致，以胃强脾弱证最为常见。"],
      notice: "答案参考教材第3版P60–61，由NUR组织表达。",
      sourceIds: [inquiryDietSourceIds.textbook],
    },
    scoring: null,
    sourceIds: [inquiryDietSourceIds.textbook, inquiryDietSourceIds.editorial],
  },
  {
    id: inquiryDietAssessmentItemIds.a1IntroPrinciples,
    order: 6,
    knowledgePointId: "kp-introduction-principles",
    questionKind: "a1-single",
    status: "available",
    prompt: "中医诊断的基本原理不包括下列哪项？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材绪论中医诊断基本原理",
      note: "NUR 改编自教材绪论知识点，不冒充学校原题。",
      sourceIds: ["source-tcm-diagnostics-textbook"],
    },
    choices: [
      "司外揣内",
      "见微知著",
      "以常衡变",
      "辨证论治",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["中医诊断的基本原理包括司外揣内、见微知著和以常衡变；辨证论治是中医学的基本特点之一，不属于诊断原理。"],
      notice: "NUR 参考教材组织答案。",
      sourceIds: ["source-tcm-diagnostics-textbook"],
    },
    scoring: null,
    sourceIds: ["source-tcm-diagnostics-textbook"],
  },
  {
    id: inquiryDietAssessmentItemIds.a1InspectionSpirit,
    order: 7,
    knowledgePointId: "kp-inspection-spirit",
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪项属于失神的临床表现？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材望神章节",
      note: "NUR 改编自教材望诊·望神知识点。",
      sourceIds: ["source-tcm-diagnostics-textbook"],
    },
    choices: [
      "目光明亮，神志清楚",
      "精神萎靡，目光晦暗",
      "烦躁不安，胡言乱语",
      "表情淡漠，喃喃自语",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["失神主要表现为精神萎靡、目光晦暗、反应迟钝等；烦躁不安属假神或实证，表情淡漠喃喃自语属癫证。"],
      notice: "NUR 参考教材望神内容组织答案。",
      sourceIds: ["source-tcm-diagnostics-textbook"],
    },
    scoring: null,
    sourceIds: ["source-tcm-diagnostics-textbook"],
  },
] as const satisfies readonly AssessmentItemDefinition[];

const inquiryKnowledgePoints = [
  withQuestionBankItems(deepKnowledgePoints.coldHeat),
  createDemoKnowledgePoint("kp-inquiry-sweat", "sweat", 2, "问汗", "有汗无汗、部位与时间", "重点"),
  createDemoKnowledgePoint("kp-inquiry-pain", "pain", 3, "问疼痛", "部位、性质、时间与喜恶", "高频"),
  createDemoKnowledgePoint(
    "kp-inquiry-diet-taste",
    "diet-and-taste",
    4,
    "问饮食口味",
    "食欲、食量、口渴与口味",
    "高频",
    {
      contentStatus: "available",
      evidenceFramework: ["食欲与食量", "口渴与饮水", "口味与嗅味觉", "伴随证据与安全边界"],
      lenses: [inquiryDietTcmLens, inquiryDietModernLens],
      relationships: [
        {
          id: "relationship-inquiry-diet-related",
          fromLensId: inquiryDietTcmLens.id,
          toLensId: inquiryDietModernLens.id,
          label: "related",
          status: "available",
          note: "两种视角共享食欲、食量、口渴、饮水和味觉变化等原始观察证据。",
          sourceIds: [inquiryDietSourceIds.textbook, inquiryDietSourceIds.editorial],
        },
        {
          id: "relationship-inquiry-diet-learning-aid",
          fromLensId: inquiryDietTcmLens.id,
          toLensId: inquiryDietModernLens.id,
          label: "learning-aid",
          status: "available",
          note: "现代医学的症状组合、鉴别与安全评估进入 NUR 平台作答及评分训练，帮助把证据描述得更完整。",
          sourceIds: [
            inquiryDietSourceIds.indigestion,
            inquiryDietSourceIds.diabetes,
            inquiryDietSourceIds.taste,
          ],
        },
        {
          id: "relationship-inquiry-diet-not-equivalent",
          fromLensId: inquiryDietTcmLens.id,
          toLensId: inquiryDietModernLens.id,
          label: "not-equivalent",
          status: "available",
          note: "中医证候、脏腑功能判断与现代医学疾病或机制不是一一对应，必须分别论证和评分。",
          sourceIds: [inquiryDietSourceIds.textbook, inquiryDietSourceIds.editorial],
        },
      ],
      learningMemoryCriteria: inquiryDietLearningMemoryCriteria,
      sourceIds: [
        inquiryDietSourceIds.textbook,
        inquiryDietSourceIds.teacherReview,
        inquiryDietSourceIds.editorial,
        inquiryDietSourceIds.indigestion,
        inquiryDietSourceIds.diabetes,
        inquiryDietSourceIds.taste,
      ],
      assessmentItemIds: [
        ...Object.values(inquiryDietAssessmentItemIds),
        ...questionBankKnowledgePointItems["kp-inquiry-diet-taste"],
        ...completeKnowledgePointItems["kp-inquiry-diet-taste"],
      ],
      caseIds: [inquiryDietCaseId],
      lesson: inquiryDietLesson,
    },
  ),
  createDemoKnowledgePoint("kp-inquiry-excretion", "urine-and-stool", 5, "问二便", "频次、性状与伴随感受", "高频"),
  createDemoKnowledgePoint("kp-inquiry-sleep", "sleep", 6, "问睡眠", "失眠、嗜睡与多梦", "重点"),
] as const;

const pulseKnowledgePoints = [
  createDemoKnowledgePoint("kp-pulse-method", "pulse-method", 1, "诊脉部位与方法", "寸口、布指与平息", "基础"),
  createDemoKnowledgePoint("kp-pulse-normal", "normal-pulse", 2, "正常脉象", "有胃、有神、有根", "重点"),
  withQuestionBankItems(deepKnowledgePoints.pulse),
  createDemoKnowledgePoint("kp-pulse-combined", "combined-pulses", 4, "相兼脉与主病", "组合分析，避免机械套用", "高频"),
] as const;

const eightPrinciplesKnowledgePoints = [
  withQuestionBankItems(deepKnowledgePoints.exteriorInterior),
  createDemoKnowledgePoint("kp-eight-principles-cold-heat", "cold-heat", 2, "寒热辨证", "区分性质与真假寒热", "高频"),
  createDemoKnowledgePoint("kp-eight-principles-deficiency-excess", "deficiency-excess", 3, "虚实辨证", "判断邪正盛衰", "高频"),
  createDemoKnowledgePoint("kp-eight-principles-yin-yang", "yin-yang", 4, "阴阳辨证", "八纲总纲与证候统摄", "重点"),
] as const;

const diseaseNatureKnowledgePoints = [
  createDemoKnowledgePoint("kp-disease-nature-six-excesses", "six-excesses", 1, "六淫辨证", "风寒暑湿燥火", "重点"),
  createDemoKnowledgePoint("kp-disease-nature-qi", "qi", 2, "气病辨证", "气虚、气陷、气滞与气逆", "高频"),
  createDemoKnowledgePoint("kp-disease-nature-blood", "blood", 3, "血病辨证", "血虚、血瘀、血热与血寒", "高频"),
  createDemoKnowledgePoint("kp-disease-nature-fluids", "body-fluids", 4, "津液辨证", "津液不足与水液停聚", "重点"),
] as const;

const organKnowledgePoints = [
  createDemoKnowledgePoint("kp-organs-heart-small-intestine", "heart-small-intestine", 1, "心与小肠病辨证", "神志、血脉与小便线索", "重点"),
  createDemoKnowledgePoint("kp-organs-lung-large-intestine", "lung-large-intestine", 2, "肺与大肠病辨证", "宣降、呼吸与传导", "重点"),
  withQuestionBankItems(deepKnowledgePoints.spleen),
  createDemoKnowledgePoint("kp-organs-liver-gallbladder", "liver-gallbladder", 4, "肝胆病辨证", "疏泄、藏血与胆汁", "高频"),
  createDemoKnowledgePoint("kp-organs-kidney-bladder", "kidney-bladder", 5, "肾与膀胱病辨证", "藏精、纳气与水液", "高频"),
] as const;

const knowledgePoints = [
  ...introductionKnowledgePoints,
  ...inspectionKnowledgePoints,
  ...tongueKnowledgePoints,
  ...listeningSmellingKnowledgePoints,
  ...inquiryKnowledgePoints,
  ...pulseKnowledgePoints,
  ...eightPrinciplesKnowledgePoints,
  ...diseaseNatureKnowledgePoints,
  ...organKnowledgePoints,
] as const;

export const tcmDiagnosticsCourse = {
  id: "course-tcm-diagnostics",
  slug: "tcm-diagnostics",
  title: "中医诊断学",
  catalogLabel: "COURSE 01",
  classification: "核心专业课",
  description: "以四诊证据组织知识，从理解、输出到案例应用，贯通一个学期的学习。",
  ghostWordmark: "DIAGNOSIS",
  curriculumMode: "tcm-primary",
  contentStatus: "demo",
  version: {
    id: "version-tcm-diagnostics-pilot",
    status: "pending",
    textbookEdition: {
      status: "verified",
      value: "《中医诊断学》第3版（吴承玉、王天芳主编，2018）",
      missingLabel: null,
      verifiedAt: "2026-07-16",
    },
    school: {
      status: "verified",
      value: "南京中医药大学",
      missingLabel: null,
      verifiedAt: "2026-07-16",
    },
    program: {
      status: "verified",
      value: "中西医结合临床",
      missingLabel: null,
      verifiedAt: "2026-07-16",
    },
    learnerYear: {
      status: "verified",
      value: "大一",
      missingLabel: null,
      verifiedAt: "2026-07-16",
    },
    teacher: {
      status: "pending",
      value: null,
      missingLabel: "待确认",
      verifiedAt: null,
    },
    academicYear: {
      status: "verified",
      value: "2026 学年",
      missingLabel: null,
      verifiedAt: "2026-07-16",
    },
    semester: {
      status: "verified",
      value: "下学期",
      missingLabel: null,
      verifiedAt: "2026-07-16",
    },
  },
  sources: [
    {
      id: "source-tcm-diagnostics-textbook",
      order: 1,
      role: "course-material",
      type: "textbook",
      authority: "publisher",
      scope: "current-offering",
      displayLabel: "教材版本",
      status: "verified",
      missingLabel: null,
      citation: {
        label: "第3版 · 2018",
        edition: "上海科学技术出版社，2018年5月第3版，ISBN 978-7-5478-3952-2",
        page: null,
        slide: null,
        academicYear: null,
        url: null,
      },
      verifiedAt: "2026-07-16",
      materialArtifactIds: ["artifact-tcm-diagnostics-textbook-third"],
    },
    {
      id: "source-tcm-diagnostics-teacher-slides",
      order: 2,
      role: "course-material",
      type: "teacher-slide",
      authority: "teacher",
      scope: "current-offering",
      displayLabel: "教师课件",
      status: "verified",
      missingLabel: null,
      citation: {
        label: "任课教师课件 · 5份",
        edition: null,
        page: null,
        slide: "肺大肠、肝胆、脾胃、肾膀胱、心与膀胱",
        academicYear: "2026 学年下学期",
        url: null,
      },
      verifiedAt: "2026-07-16",
      materialArtifactIds: [
        "artifact-tcm-diagnostics-heart-slide",
        "artifact-tcm-diagnostics-lung-slide",
        "artifact-tcm-diagnostics-spleen-slide",
        "artifact-tcm-diagnostics-liver-slide",
        "artifact-tcm-diagnostics-kidney-slide",
      ],
    },
    {
      id: "source-tcm-diagnostics-review-scope",
      order: 3,
      role: "course-material",
      type: "review-scope",
      authority: "teacher",
      scope: "current-offering",
      displayLabel: "复习范围",
      status: "verified",
      missingLabel: null,
      citation: {
        label: "中诊保命重点 · 2页",
        edition: null,
        page: "1–2",
        slide: null,
        academicYear: "2026 学年下学期",
        url: null,
      },
      verifiedAt: "2026-07-16",
      materialArtifactIds: ["artifact-tcm-diagnostics-teacher-review"],
    },
    {
      id: "source-tcm-diagnostics-past-exams",
      order: 4,
      role: "course-material",
      type: "past-exam",
      authority: "school",
      scope: "historical-offering",
      displayLabel: "历年真题",
      status: "verified",
      missingLabel: null,
      citation: {
        label: "中诊真题 · 2021–2022",
        edition: null,
        page: null,
        slide: null,
        academicYear: "2021–2022 学年第一学期",
        url: null,
      },
      verifiedAt: "2026-07-16",
      materialArtifactIds: ["artifact-tcm-diagnostics-exam-2021-2022"],
    },
    {
      id: "source-tcm-diagnostics-whitebook",
      order: 5,
      role: "course-evidence",
      type: "question-bank",
      authority: "school",
      scope: "general-reference",
      displayLabel: "学校白皮书",
      status: "verified",
      missingLabel: null,
      citation: {
        label: "南京中医药大学中医诊断学试题 · 练习06卷",
        edition: null,
        page: null,
        slide: null,
        academicYear: null,
        url: null,
      },
      verifiedAt: "2026-07-16",
      materialArtifactIds: ["artifact-tcm-diagnostics-whitebook"],
    },
    {
      id: "source-tcm-diagnostics-choice-bank",
      order: 6,
      role: "course-evidence",
      type: "question-bank",
      authority: "student",
      scope: "general-reference",
      displayLabel: "选择题资料",
      status: "available",
      missingLabel: null,
      citation: {
        label: "《中医诊断学》考试模拟题库 · 260题（答案待核）",
        edition: null,
        page: null,
        slide: null,
        academicYear: null,
        url: null,
      },
      verifiedAt: null,
    },
    {
      id: inquiryDietSourceIds.textbook,
      order: 7,
      role: "knowledge-reference",
      type: "textbook",
      authority: "publisher",
      scope: "current-offering",
      displayLabel: "教材 · 问饮食口味",
      status: "verified",
      missingLabel: null,
      citation: {
        label: "《中医诊断学》第3版 · 第60–61页",
        edition: "上海科学技术出版社，2018年5月第3版",
        page: "60–61",
        slide: null,
        academicYear: null,
        url: null,
      },
      verifiedAt: "2026-07-16",
      materialArtifactIds: ["artifact-tcm-diagnostics-textbook-third"],
      locators: [
        {
          id: "locator-inquiry-diet-textbook-p60-61",
          artifactId: "artifact-tcm-diagnostics-textbook-third",
          kind: "page",
          value: "教材印刷页60–61（PDF页73–74）",
          label: "口渴饮水、食欲食量与口味",
        },
      ],
    },
    {
      id: inquiryDietSourceIds.teacherReview,
      order: 8,
      role: "knowledge-reference",
      type: "review-scope",
      authority: "teacher",
      scope: "current-offering",
      displayLabel: "教师重点 · 问饮食口味",
      status: "verified",
      missingLabel: null,
      citation: {
        label: "中诊保命重点 · 第2页（对应教材P60–61）",
        edition: null,
        page: "2",
        slide: null,
        academicYear: "2026 学年下学期",
        url: null,
      },
      verifiedAt: "2026-07-16",
      materialArtifactIds: ["artifact-tcm-diagnostics-teacher-review"],
      locators: [
        {
          id: "locator-inquiry-diet-review-p2",
          artifactId: "artifact-tcm-diagnostics-teacher-review",
          kind: "page",
          value: "PDF第2页",
          label: "教师列明教材P60–61的口渴饮水、消谷善饥与问口味",
        },
      ],
    },
    {
      id: inquiryDietSourceIds.editorial,
      order: 9,
      role: "knowledge-reference",
      type: "editorial",
      authority: "nur-editorial",
      scope: "general-reference",
      displayLabel: "NUR 内容结构草案",
      status: "available",
      missingLabel: null,
      citation: {
        label: "NUR LEARN 问饮食口味结构演示（非教材）",
        edition: null,
        page: null,
        slide: null,
        academicYear: null,
        url: null,
      },
      verifiedAt: null,
    },
    {
      id: inquiryDietSourceIds.indigestion,
      order: 10,
      role: "knowledge-reference",
      type: "clinical-reference",
      authority: "clinical-authority",
      scope: "general-reference",
      displayLabel: "NIDDK · 消化不良症状",
      status: "available",
      missingLabel: null,
      citation: {
        label: "Symptoms & Causes of Indigestion",
        edition: null,
        page: null,
        slide: null,
        academicYear: null,
        url: "https://www.niddk.nih.gov/health-information/digestive-diseases/indigestion-dyspepsia/symptoms-causes",
      },
      verifiedAt: null,
    },
    {
      id: inquiryDietSourceIds.diabetes,
      order: 11,
      role: "knowledge-reference",
      type: "clinical-reference",
      authority: "clinical-authority",
      scope: "general-reference",
      displayLabel: "NIDDK · 糖尿病症状",
      status: "available",
      missingLabel: null,
      citation: {
        label: "Symptoms & Causes of Diabetes",
        edition: null,
        page: null,
        slide: null,
        academicYear: null,
        url: "https://www.niddk.nih.gov/health-information/diabetes/overview/symptoms-causes",
      },
      verifiedAt: null,
    },
    {
      id: inquiryDietSourceIds.taste,
      order: 12,
      role: "knowledge-reference",
      type: "clinical-reference",
      authority: "clinical-authority",
      scope: "general-reference",
      displayLabel: "NIDCD · 味觉障碍",
      status: "available",
      missingLabel: null,
      citation: {
        label: "Taste Disorders",
        edition: null,
        page: null,
        slide: null,
        academicYear: null,
        url: "https://www.nidcd.nih.gov/health/taste-disorders",
      },
      verifiedAt: null,
    },
    {
      id: "source-tcm-diagnostics-teacher-final-review",
      order: 13,
      role: "course-evidence",
      type: "review-scope",
      authority: "teacher",
      scope: "current-offering",
      displayLabel: "任课教师最终重点",
      status: "pending",
      missingLabel: "待导入（原9页）",
      citation: null,
      verifiedAt: null,
    },
    {
      id: "source-tcm-diagnostics-teacher-rubric",
      order: 14,
      role: "course-evidence",
      type: "grading-rubric",
      authority: "teacher",
      scope: "current-offering",
      displayLabel: "教师主观题评分标准",
      status: "pending",
      missingLabel: "未提供",
      citation: null,
      verifiedAt: null,
    },
    ...deepLoopSources,
  ],
  examBlueprint: {
    id: "exam-blueprint-tcm-diagnostics-final",
    title: "当前课程默认期末结构",
    status: "available",
    missingLabel: null,
    provenance: "user-provided",
    scope: {
      school: "南京中医药大学",
      program: "中西医结合临床",
      learnerYear: "大一",
      academicYear: "2026 学年",
      semester: "下学期",
      teacher: null,
    },
    sourceIds: [],
    totalPoints: 100,
    rows: [
      { id: "exam-a1-single", order: 1, kind: "a1-single", label: "A1 单选题", count: 30, pointsEach: 1, totalPoints: 30 },
      { id: "exam-b1", order: 2, kind: "b1", label: "B1 型题", count: 10, pointsEach: 1, totalPoints: 10 },
      { id: "exam-b2", order: 3, kind: "b2", label: "B2 型题", count: 5, pointsEach: 1, totalPoints: 5 },
      { id: "exam-fill", order: 4, kind: "fill", label: "填空题", count: 5, pointsEach: 1, totalPoints: 5 },
      { id: "exam-term", order: 5, kind: "term", label: "名词解释", count: 5, pointsEach: 3, totalPoints: 15 },
      { id: "exam-short-answer", order: 6, kind: "short-answer", label: "简答题", count: 3, pointsEach: 5, totalPoints: 15 },
      { id: "exam-case", order: 7, kind: "case", label: "案例题", count: 2, pointsEach: 10, totalPoints: 20 },
    ],
    summaryGroups: [
      { id: "objective", order: 1, label: "客观题", questionKinds: ["a1-single", "b1", "b2"] },
      { id: "fill", order: 2, label: "填空题", questionKinds: ["fill"] },
      { id: "term", order: 3, label: "名词解释", questionKinds: ["term"] },
      { id: "short-answer", order: 4, label: "简答题", questionKinds: ["short-answer"] },
      { id: "case", order: 5, label: "案例题", questionKinds: ["case"] },
    ],
    priorityNotice: {
      lead: "名词解释、简答与案例共",
      questionKinds: ["term", "short-answer", "case"],
      guidance: "必须训练完整表达与辨证链条。",
    },
    integrity: {
      expectedTotalPoints: 100,
      expectedKindTotals: [
        { kind: "a1-single", totalPoints: 30 },
        { kind: "b1", totalPoints: 10 },
        { kind: "b2", totalPoints: 5 },
        { kind: "fill", totalPoints: 5 },
        { kind: "term", totalPoints: 15 },
        { kind: "short-answer", totalPoints: 15 },
        { kind: "case", totalPoints: 20 },
      ],
    },
  },
  learningRoutes: [
    {
      id: "understand",
      order: 1,
      indexLabel: "01",
      title: "理解",
      detail: "中西双视角知识点",
      guidance: "先建立证据结构，再进入记忆",
    },
    {
      id: "express",
      order: 2,
      indexLabel: "02",
      title: "输出",
      detail: "名词解释与简答成句",
      guidance: "按采分点写完整，而不只写关键词",
    },
    {
      id: "apply",
      order: 3,
      indexLabel: "03",
      title: "应用",
      detail: "案例证据与辨证推理",
      guidance: "用完整推理链解释证型选择",
    },
  ],
  chapters: [
    {
      id: "chapter-introduction",
      slug: "introduction",
      order: 1,
      indexLabel: "01",
      title: "绪论",
      focus: "掌握中医诊断的基本原理与基本原则。",
      knowledgePointIds: introductionKnowledgePoints.map((point) => point.id),
    },
    {
      id: "chapter-inspection",
      slug: "inspection",
      order: 2,
      indexLabel: "02",
      title: "望诊",
      focus: "能从神、色、形、态提取可复述的诊断证据。",
      knowledgePointIds: inspectionKnowledgePoints.map((point) => point.id),
    },
    {
      id: "chapter-tongue",
      slug: "tongue",
      order: 3,
      indexLabel: "03",
      title: "舌诊",
      focus: "把舌质、舌苔变化组织为病位、病性与病势依据。",
      knowledgePointIds: tongueKnowledgePoints.map((point) => point.id),
    },
    {
      id: "chapter-listening-smelling",
      slug: "listening-smelling",
      order: 4,
      indexLabel: "04",
      title: "闻诊",
      focus: "辨别声音与气味线索，并和望、问、切诊互相验证。",
      knowledgePointIds: listeningSmellingKnowledgePoints.map((point) => point.id),
    },
    {
      id: "chapter-inquiry",
      slug: "inquiry",
      order: 5,
      indexLabel: "05",
      title: "问诊",
      focus: "从主诉与伴随症状建立结构化证据，避免只背结论。",
      knowledgePointIds: inquiryKnowledgePoints.map((point) => point.id),
    },
    {
      id: "chapter-pulse",
      slug: "pulse",
      order: 6,
      indexLabel: "06",
      title: "脉诊",
      focus: "以位、数、形、势理解脉象，而不是孤立记忆名称。",
      knowledgePointIds: pulseKnowledgePoints.map((point) => point.id),
    },
    {
      id: "chapter-eight-principles",
      slug: "eight-principles",
      order: 7,
      indexLabel: "07",
      title: "八纲辨证",
      focus: "把四诊证据归纳为表里、寒热、虚实、阴阳。",
      knowledgePointIds: eightPrinciplesKnowledgePoints.map((point) => point.id),
    },
    {
      id: "chapter-disease-nature",
      slug: "disease-nature",
      order: 8,
      indexLabel: "08",
      title: "病性辨证",
      focus: "从病因与病理产物判断气血津液阴阳的变化。",
      knowledgePointIds: diseaseNatureKnowledgePoints.map((point) => point.id),
    },
    {
      id: "chapter-organs",
      slug: "organs",
      order: 9,
      indexLabel: "09",
      title: "脏腑辨证",
      focus: "综合病位、病性和脏腑功能形成完整辨证结论。",
      knowledgePointIds: organKnowledgePoints.map((point) => point.id),
    },
  ],
  knowledgePoints,
  learningTasks: [],
  assessmentItems: [
    ...inquiryDietAssessmentItems,
    ...deepAssessmentItems,
    ...questionBankAssessmentItems,
    ...completeAssessmentItems,
    ...completeSubjectiveItems,
  ],
  assessmentGroups: completeAssessmentGroups,
  cases: [inquiryDietReasoningCase, spleenReasoningCase],
} satisfies CourseDefinition;
