import type { AssessmentItemDefinition, AssessmentItemGroupDefinition } from "@/types/learning";
import { deepLoopSourceIds } from "@/content/courses/tcm-diagnostics-deep-loops";

/**
 * 中诊 B1/B2 组题与剩余主观题（2026-08-06）。
 *
 * B1/B2 语义由用户于 2026-08-06 口头确认并记录为来源：
 * - B1 = 共用备选答案配伍题（一组选项供多个小题共用、可重复选择）；
 * - B2 = 共用题干题组（一个病例/题干下多个小题，小题为单选）。
 *
 * 全部为 NUR 改编题（nur-editorial 题干 + nur-platform 答案 + source-cross-checked），
 * 只引用已核验教材页码 P37/P39/P52–53/P60–61/P69–91/P121–123 与教师重点来源，
 * 不冒充学校原题。
 */

const textbookSourceId = "source-tcm-diagnostics-textbook";

// ── B1 共用备选答案配伍组（5 组 × 2 小题 = 10 题）──────────────────────
const b1PulseMembers: readonly AssessmentItemDefinition[] = [
  {
    id: "assessment-qb2-b1-pulse-floating",
    order: 1,
    knowledgePointId: "kp-pulse-common",
    questionKind: "b1",
    status: "available",
    prompt: "轻取即得，重按稍减而不空，举之有余、按之不足者",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第69、71、73、79页病脉与脉象鉴别",
      note: "NUR 改编自教材已核验页码内容，B1 组题共用备选答案。",
      sourceIds: [deepLoopSourceIds.pulseTextbook],
    },
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["浮脉轻取即得、重按稍减而不空，主表证。"],
      notice: "答案参考教材第3版P69、71、73、79，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.pulseTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.pulseTextbook],
  },
  {
    id: "assessment-qb2-b1-pulse-deep",
    order: 2,
    knowledgePointId: "kp-pulse-common",
    questionKind: "b1",
    status: "available",
    prompt: "轻取不应，重按始得，举之不足、按之有余者",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第69、71、73、79页病脉与脉象鉴别",
      note: "NUR 改编自教材已核验页码内容，B1 组题共用备选答案。",
      sourceIds: [deepLoopSourceIds.pulseTextbook],
    },
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["沉脉轻取不应、重按始得，主里证。"],
      notice: "答案参考教材第3版P69、71、73、79，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.pulseTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.pulseTextbook],
  },
];

const b1ColdHeatMembers: readonly AssessmentItemDefinition[] = [
  {
    id: "assessment-qb2-b1-cold-heat-superficies",
    order: 1,
    knowledgePointId: "kp-inquiry-cold-heat",
    questionKind: "b1",
    status: "available",
    prompt: "外感表证初期，恶寒与发热同时并见者",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第52–53页问寒热分类",
      note: "NUR 改编自教材已核验页码内容，B1 组题共用备选答案。",
      sourceIds: [deepLoopSourceIds.coldHeatTextbook],
    },
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["恶寒发热并见多见于外感表证初期，为卫阳被遏与邪正相争所致。"],
      notice: "答案参考教材第3版P52–53，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.coldHeatTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.coldHeatTextbook],
  },
  {
    id: "assessment-qb2-b1-cold-heat-alternating",
    order: 2,
    knowledgePointId: "kp-inquiry-cold-heat",
    questionKind: "b1",
    status: "available",
    prompt: "寒热往来，发有定时，一日一发或二三日一发者",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第52–53页寒热往来",
      note: "NUR 改编自教材已核验页码内容，B1 组题共用备选答案。",
      sourceIds: [deepLoopSourceIds.coldHeatTextbook],
    },
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["寒热往来发有定时，一日一发或二三日一发，多属疟疾；发无定时多见于半表半里证。"],
      notice: "答案参考教材第3版P52–53，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.coldHeatTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.coldHeatTextbook],
  },
];

const b1TongueCoatingMembers: readonly AssessmentItemDefinition[] = [
  {
    id: "assessment-qb2-b1-tongue-greasy",
    order: 1,
    knowledgePointId: "kp-tongue-coating",
    questionKind: "b1",
    status: "available",
    prompt: "苔质致密细腻，如涂油腻之状，刮之难去者",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第37页腐苔、腻苔舌象特征",
      note: "NUR 改编自教材已核验页码内容，B1 组题共用备选答案。",
      sourceIds: [deepLoopSourceIds.tongueTextbook],
    },
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["腻苔苔质致密细腻、如涂油腻、刮之难去；腐苔苔质疏松、颗粒粗大、刮之易去。"],
      notice: "答案参考教材第3版P37，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.tongueTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.tongueTextbook],
  },
  {
    id: "assessment-qb2-b1-tongue-mouldy",
    order: 2,
    knowledgePointId: "kp-tongue-coating",
    questionKind: "b1",
    status: "available",
    prompt: "苔质疏松，颗粒粗大，形如豆腐渣，刮之易去者",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第37页腐苔、腻苔舌象特征",
      note: "NUR 改编自教材已核验页码内容，B1 组题共用备选答案。",
      sourceIds: [deepLoopSourceIds.tongueTextbook],
    },
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["腐苔苔质疏松、颗粒粗大、形如豆腐渣、刮之易去；腻苔则刮之难去。"],
      notice: "答案参考教材第3版P37，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.tongueTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.tongueTextbook],
  },
];

const b1ExteriorMembers: readonly AssessmentItemDefinition[] = [
  {
    id: "assessment-qb2-b1-exterior-superficies",
    order: 1,
    knowledgePointId: "kp-eight-principles-exterior-interior",
    questionKind: "b1",
    status: "available",
    prompt: "恶寒发热并见，头身疼痛，鼻塞流涕，脉浮者",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第89–91页表证、里证及鉴别",
      note: "NUR 改编自教材已核验页码内容，B1 组题共用备选答案。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["恶寒发热并见、头身疼痛、脉浮为表证特征。"],
      notice: "答案参考教材第3版P89–91，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
  },
  {
    id: "assessment-qb2-b1-exterior-interior-same",
    order: 2,
    knowledgePointId: "kp-eight-principles-exterior-interior",
    questionKind: "b1",
    status: "available",
    prompt: "表证未解，又见里证，恶寒发热与腹痛便秘并见者",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第89–91页表里同病",
      note: "NUR 改编自教材已核验页码内容，B1 组题共用备选答案。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["表证未解又见里证表现者为表里同病；表邪入里则表证表现消失。"],
      notice: "答案参考教材第3版P89–91，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
  },
];

const b1SpleenMembers: readonly AssessmentItemDefinition[] = [
  {
    id: "assessment-qb2-b1-spleen-yang",
    order: 1,
    knowledgePointId: "kp-organs-spleen-stomach",
    questionKind: "b1",
    status: "available",
    prompt: "食少腹胀，便溏，神疲乏力，兼畏寒肢冷、腹痛喜温喜按者",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第121–123页脾气虚、脾阳虚及相关证候鉴别",
      note: "NUR 改编自教材已核验页码内容，B1 组题共用备选答案。",
      sourceIds: [deepLoopSourceIds.spleenTextbook],
    },
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["脾气虚共性之上兼畏寒肢冷、腹痛喜温喜按，为脾阳虚证的特征增量表现。"],
      notice: "答案参考教材第3版P121–123，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.spleenTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.spleenTextbook],
  },
  {
    id: "assessment-qb2-b1-stomach-yin",
    order: 2,
    knowledgePointId: "kp-organs-spleen-stomach",
    questionKind: "b1",
    status: "available",
    prompt: "胃脘隐隐灼痛，饥不欲食，口干，舌红少苔者",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第121–123页胃阴虚证",
      note: "NUR 改编自教材已核验页码内容，B1 组题共用备选答案。",
      sourceIds: [deepLoopSourceIds.spleenTextbook],
    },
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["胃脘灼痛、饥不欲食、口干、舌红少苔为胃阴虚证特征，胃失濡润所致。"],
      notice: "答案参考教材第3版P121–123，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.spleenTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.spleenTextbook],
  },
];

// ── B2 共用题干题组（3 组 = 5 小题）───────────────────────────────────
const b2ExteriorMembers: readonly AssessmentItemDefinition[] = [
  {
    id: "assessment-qb2-b2-exterior-diagnosis",
    order: 1,
    knowledgePointId: "kp-eight-principles-exterior-interior",
    questionKind: "b2",
    status: "available",
    prompt: "根据现有表现，该患者最可能的辨证是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第89–91页表证辨证",
      note: "NUR 改编自教材已核验页码内容，B2 组题共享病例题干。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    choices: ["表证", "里证", "半表半里证", "阴虚证", "阳虚证"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["恶寒发热并见、头身疼痛、鼻塞流涕、苔薄白、脉浮为表证表现。"],
      notice: "答案参考教材第3版P89–91，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
  },
  {
    id: "assessment-qb2-b2-exterior-turns-interior",
    order: 2,
    knowledgePointId: "kp-eight-principles-exterior-interior",
    questionKind: "b2",
    status: "available",
    prompt: "若两天后恶寒消失，转为壮热口渴、大便秘结、小便短赤、舌红苔黄，则提示",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第89–91页表里转化",
      note: "NUR 改编自教材已核验页码内容，B2 组题共享病例题干。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    choices: ["表证未解", "表邪入里化热", "半表半里证", "表里同病", "阴虚内热"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["恶寒消失、壮热口渴便秘并见，提示表邪入里化热，病位已由肌表深入脏腑。"],
      notice: "答案参考教材第3版P89–91，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
  },
];

const b2DietMembers: readonly AssessmentItemDefinition[] = [
  {
    id: "assessment-qb2-b2-diet-xiaoke",
    order: 1,
    knowledgePointId: "kp-inquiry-diet-taste",
    questionKind: "b2",
    status: "available",
    prompt: "该组表现（口渴多饮、多食易饥、小便频多、形体消瘦）最符合",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第60–61页消谷善饥与消渴",
      note: "NUR 改编自教材已核验页码内容，B2 组题共享病例题干。",
      sourceIds: [textbookSourceId, deepLoopSourceIds.editorial],
    },
    choices: ["胃火炽盛", "消渴病", "胃强脾弱", "脾胃虚寒", "肝胃不和"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["消谷善饥兼多饮多尿、形体消瘦，多见于消渴病；仅见消谷善饥、口臭便秘则多为胃火炽盛。"],
      notice: "答案参考教材第3版P60–61，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [textbookSourceId],
    },
    scoring: null,
    sourceIds: [textbookSourceId],
  },
  {
    id: "assessment-qb2-b2-diet-stomach-fire",
    order: 2,
    knowledgePointId: "kp-inquiry-diet-taste",
    questionKind: "b2",
    status: "available",
    prompt: "若仅见多食易饥，兼口臭便秘、舌红苔黄、脉滑数，则更支持",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第60–61页消谷善饥",
      note: "NUR 改编自教材已核验页码内容，B2 组题共享病例题干。",
      sourceIds: [textbookSourceId, deepLoopSourceIds.editorial],
    },
    choices: ["消渴病", "胃火炽盛", "胃阴虚", "脾虚湿困", "肝气犯胃"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["消谷善饥兼口臭便秘、舌红苔黄、脉滑数，为胃火炽盛的表现。"],
      notice: "答案参考教材第3版P60–61，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [textbookSourceId],
    },
    scoring: null,
    sourceIds: [textbookSourceId],
  },
];

const b2SpleenMembers: readonly AssessmentItemDefinition[] = [
  {
    id: "assessment-qb2-b2-spleen-qi",
    order: 1,
    knowledgePointId: "kp-organs-spleen-stomach",
    questionKind: "b2",
    status: "available",
    prompt: "该患者最可能的辨证是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第121–123页脾气虚证",
      note: "NUR 改编自教材已核验页码内容，B2 组题共享病例题干。",
      sourceIds: [deepLoopSourceIds.spleenTextbook],
    },
    choices: ["脾气虚证", "脾阳虚证", "胃阴虚证", "寒湿困脾证", "湿热蕴脾证"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "source-cross-checked",
      content: ["食少腹胀、便溏、神疲乏力、少气懒言、面色萎黄、舌淡脉缓弱，为脾气虚证表现。"],
      notice: "答案参考教材第3版P121–123，由NUR组织表达；不是学校或任课教师标准答案。",
      sourceIds: [deepLoopSourceIds.spleenTextbook],
    },
    scoring: null,
    sourceIds: [deepLoopSourceIds.spleenTextbook],
  },
];

// ── 名词解释 ×2（教材 P60–61、P37，带 NUR 完整度训练量表）───────────────
const termDietExcessiveHunger: AssessmentItemDefinition = {
  id: "assessment-qb2-term-diet-excessive-hunger",
  order: 15,
  knowledgePointId: "kp-inquiry-diet-taste",
  questionKind: "term",
  status: "available",
  prompt: "名词解释：消谷善饥。",
  promptSource: {
    authority: "nur-editorial",
    wording: "nur-adapted",
    locator: "由教材第60–61页问饮食口味转写为完整表达训练",
    note: "NUR 为训练完整表达所作的题型改写，不是学校原题。",
    sourceIds: [textbookSourceId, deepLoopSourceIds.editorial],
  },
  answer: {
    status: "available",
    authority: "nur-platform",
    confidence: "source-cross-checked",
    content: [
      "定义：指食欲过于旺盛，食后不久即感饥饿，进食量明显增多的一类表现。",
      "机理：多因胃火炽盛、腐熟水谷功能亢进所致；兼多饮多尿、形体消瘦者需考虑消渴。",
      "鉴别：与饥不欲食（胃阴虚）、食少纳呆（脾气虚）相区分，并结合口渴、二便、舌脉判断。",
    ],
    notice: "结构参考由 NUR 按教材第60–61页整理，不是学校或任课教师标准答案。",
    sourceIds: [textbookSourceId, deepLoopSourceIds.editorial],
  },
  scoring: {
    id: "scoring-qb2-term-diet-excessive-hunger",
    standardVersion: "nur-writing-term-v1",
    status: "available",
    authority: "nur-platform",
    title: "NUR 名词解释完整度量表",
    totalPoints: 6,
    suggestedCharacters: 50,
    notice: "6分仅用于把答案拆开训练，不等同于当前课程每题3分，也不代表任课教师采分点。",
    answerFramework: ["是什么：先给出消谷善饥的规范定义。", "为什么：用胃火亢进、腐熟太过解释机理，并提消渴方向。", "如何辨：与饥不欲食、食少纳呆区分。"],
    criteria: [
      { id: "score-qb2-term-diet-definition", order: 1, perspective: "tcm", label: "定义准确", detail: "写明食欲亢进、食后即饥、食量明显增多。", points: 2 },
      { id: "score-qb2-term-diet-mechanism", order: 2, perspective: "tcm", label: "机理完整", detail: "写出胃火炽盛、腐熟功能亢进，并提消渴兼见表现。", points: 2 },
      { id: "score-qb2-term-diet-differentiation", order: 3, perspective: "boundary", label: "鉴别不跳步", detail: "与饥不欲食或食少纳呆至少一处区分。", points: 2 },
    ],
    assistanceRules: [
      {
        criterionId: "score-qb2-term-diet-definition",
        memoryCriterionId: "memory-evidence-completeness",
        signalGroups: [["消谷善饥", "食欲", "食量"], ["食后", "即饥"]],
        nextStepPrompt: "先把食欲亢进、食后即饥、食量增多的定义要素写全。",
        rewriteSuggestion: "消谷善饥指食欲过于旺盛，食后不久即感饥饿、进食量明显增多。",
      },
      {
        criterionId: "score-qb2-term-diet-mechanism",
        memoryCriterionId: "memory-reasoning-chain",
        signalGroups: [["胃火", "腐熟"], ["亢进", "消渴"]],
        nextStepPrompt: "补上胃火炽盛、腐熟功能亢进的机理，并提消渴兼见表现。",
        rewriteSuggestion: "多因胃火炽盛、腐熟水谷功能亢进所致；兼多饮多尿、形体消瘦者需考虑消渴。",
      },
      {
        criterionId: "score-qb2-term-diet-differentiation",
        memoryCriterionId: "memory-conclusion-boundary",
        signalGroups: [["饥不欲食", "胃阴虚"], ["食少纳呆", "脾气虚"], ["鉴别"]],
        nextStepPrompt: "补一句与饥不欲食或食少纳呆的鉴别。",
        rewriteSuggestion: "与饥不欲食（胃阴虚）、食少纳呆（脾气虚）相区分，并结合口渴、二便、舌脉判断。",
      },
    ],
    sourceIds: [textbookSourceId, deepLoopSourceIds.editorial],
  },
  sourceIds: [textbookSourceId, deepLoopSourceIds.editorial],
};

const termTongueGreasy: AssessmentItemDefinition = {
  id: "assessment-qb2-term-tongue-greasy",
  order: 15,
  knowledgePointId: "kp-tongue-coating",
  questionKind: "term",
  status: "available",
  prompt: "名词解释：腻苔。",
  promptSource: {
    authority: "nur-editorial",
    wording: "nur-adapted",
    locator: "由教材第37页舌苔转写为完整表达训练",
    note: "NUR 为训练完整表达所作的题型改写，不是学校原题。",
    sourceIds: [deepLoopSourceIds.tongueTextbook, deepLoopSourceIds.editorial],
  },
  answer: {
    status: "available",
    authority: "nur-platform",
    confidence: "source-cross-checked",
    content: [
      "定义：苔质致密细腻，颗粒均匀，如涂油腻之状，紧贴舌面，刮之难去的一类舌苔。",
      "机理：多因湿浊、痰饮、食积内停，阳气被遏所致，主湿浊内盛、痰饮或食积。",
      "鉴别：与腐苔（苔质疏松、颗粒粗大、刮之易去）相区分，并结合苔色判断寒热属性。",
    ],
    notice: "结构参考由 NUR 按教材第37页整理，不是学校或任课教师标准答案。",
    sourceIds: [deepLoopSourceIds.tongueTextbook, deepLoopSourceIds.editorial],
  },
  scoring: {
    id: "scoring-qb2-term-tongue-greasy",
    standardVersion: "nur-writing-term-v1",
    status: "available",
    authority: "nur-platform",
    title: "NUR 名词解释完整度量表",
    totalPoints: 6,
    suggestedCharacters: 50,
    notice: "6分仅用于把答案拆开训练，不等同于当前课程每题3分，也不代表任课教师采分点。",
    answerFramework: ["是什么：先给出腻苔的规范定义（质地、形态、刮之难去）。", "为什么：用湿浊痰饮食积内停解释机理并写明主病。", "如何辨：与腐苔区分并说明结合苔色。"],
    criteria: [
      { id: "score-qb2-term-greasy-definition", order: 1, perspective: "tcm", label: "定义准确", detail: "写明苔质致密细腻、如涂油腻、刮之难去。", points: 2 },
      { id: "score-qb2-term-greasy-mechanism", order: 2, perspective: "tcm", label: "机理完整", detail: "写出湿浊、痰饮或食积内停及阳气被遏。", points: 2 },
      { id: "score-qb2-term-greasy-differentiation", order: 3, perspective: "boundary", label: "鉴别不跳步", detail: "与腐苔鉴别，或说明结合苔色判断寒热。", points: 2 },
    ],
    assistanceRules: [
      {
        criterionId: "score-qb2-term-greasy-definition",
        memoryCriterionId: "tongue-coating-memory-evidence",
        signalGroups: [["致密细腻", "如涂油腻"], ["刮之难去"]],
        nextStepPrompt: "先把苔质致密细腻、如涂油腻、刮之难去的定义要素写全。",
        rewriteSuggestion: "腻苔是苔质致密细腻、颗粒均匀、如涂油腻之状、紧贴舌面、刮之难去的一类舌苔。",
      },
      {
        criterionId: "score-qb2-term-greasy-mechanism",
        memoryCriterionId: "tongue-coating-memory-reasoning",
        signalGroups: [["湿浊", "痰饮", "食积"], ["阳气被遏"]],
        nextStepPrompt: "补上湿浊、痰饮或食积内停、阳气被遏的机理说明。",
        rewriteSuggestion: "多因湿浊、痰饮、食积内停，阳气被遏所致，主湿浊内盛、痰饮或食积。",
      },
      {
        criterionId: "score-qb2-term-greasy-differentiation",
        memoryCriterionId: "tongue-coating-memory-boundary",
        signalGroups: [["腐苔", "刮之易去"], ["苔色", "寒热"]],
        nextStepPrompt: "补一句与腐苔的鉴别，或说明结合苔色判断寒热。",
        rewriteSuggestion: "与腐苔（苔质疏松、颗粒粗大、刮之易去）相区分，并结合苔色判断寒热属性。",
      },
    ],
    sourceIds: [deepLoopSourceIds.tongueTextbook, deepLoopSourceIds.editorial],
  },
  sourceIds: [deepLoopSourceIds.tongueTextbook, deepLoopSourceIds.editorial],
};

// ── 案例 ×1（教材 P121–123，四步推理）─────────────────────────────────
const caseSpleenStomach: AssessmentItemDefinition = {
  id: "assessment-qb2-case-spleen-stomach",
  order: 16,
  knowledgePointId: "kp-organs-spleen-stomach",
  questionKind: "case",
  status: "available",
  prompt:
    "病例：患者诉近两周食少腹胀，食后尤甚，大便溏薄，神疲乏力，少气懒言，面色萎黄；舌淡苔白，脉缓弱。"
    + "请按证据分组 → 病机与评估方向 → 暂定辨证结论 → 鉴别排除与边界四步完成辨证推理，并分别说明中医与现代医学评估的边界。",
  promptSource: {
    authority: "nur-editorial",
    wording: "nur-adapted",
    locator: "NUR LEARN · 脾胃辨证案例迁移（教材P121–123）",
    note: "案例由 NUR 根据教材P121–123及教师重点来源组织，不是学校原题、真实患者诊断或任课教师评分。",
    sourceIds: [deepLoopSourceIds.spleenTextbook, deepLoopSourceIds.editorial],
  },
  answer: {
    status: "available",
    authority: "nur-platform",
    confidence: "source-cross-checked",
    content: [
      "证据分组：消化系统（食少腹胀、食后尤甚、大便溏薄）与全身伴随（神疲乏力、少气懒言、面色萎黄）一组；舌脉（舌淡苔白、脉缓弱）为支持性证据。",
      "病机与评估方向：中医由脾失健运、气血生化不足方向解释，为脾气虚证候；现代医学将便溏与消瘦乏力组织为消化功能评估方向，仍需追问体重变化、排便性状与有无慢性失血线索。",
      "暂定辨证结论：现有证据支持脾气虚证；因缺乏完整四诊与其他检查，不写成其他证型或最终诊断。",
      "鉴别排除与边界：与脾阳虚（须有畏寒肢冷、腹痛喜温喜按等阳虚增量表现）、胃阴虚（饥不欲食、舌红少苔）相区分；证候与现代疾病不可直接等同，本案例不提供临床诊断。",
    ],
    notice: "结构参考由 NUR 按已接入资料交叉核对，用于发现推理断点；不是学校标准答案、教师批改答案或医疗诊断。",
    sourceIds: [deepLoopSourceIds.spleenTextbook, deepLoopSourceIds.editorial],
  },
  scoring: null,
  sourceIds: [deepLoopSourceIds.spleenTextbook, deepLoopSourceIds.editorial],
};

export const completeAssessmentGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "group-qb2-b1-pulse",
    order: 10,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["浮脉", "沉脉", "迟脉", "数脉", "洪脉"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第69、71、73、79页病脉与脉象鉴别",
      note: "NUR 改编自教材已核验页码内容，B1 配伍组。",
      sourceIds: [deepLoopSourceIds.pulseTextbook],
    },
    members: b1PulseMembers,
    sourceIds: [deepLoopSourceIds.pulseTextbook],
  },
  {
    id: "group-qb2-b1-cold-heat",
    order: 11,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["恶寒发热", "但寒不热", "但热不寒", "寒热往来", "潮热"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第52–53页问寒热分类",
      note: "NUR 改编自教材已核验页码内容，B1 配伍组。",
      sourceIds: [deepLoopSourceIds.coldHeatTextbook],
    },
    members: b1ColdHeatMembers,
    sourceIds: [deepLoopSourceIds.coldHeatTextbook],
  },
  {
    id: "group-qb2-b1-tongue-coating",
    order: 12,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["薄苔", "厚苔", "腻苔", "腐苔", "剥苔"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第37页腐苔、腻苔舌象特征",
      note: "NUR 改编自教材已核验页码内容，B1 配伍组。",
      sourceIds: [deepLoopSourceIds.tongueTextbook],
    },
    members: b1TongueCoatingMembers,
    sourceIds: [deepLoopSourceIds.tongueTextbook],
  },
  {
    id: "group-qb2-b1-exterior-interior",
    order: 13,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["表证", "里证", "半表半里证", "表里同病", "表邪入里"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第89–91页表证、里证及鉴别",
      note: "NUR 改编自教材已核验页码内容，B1 配伍组。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    members: b1ExteriorMembers,
    sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
  },
  {
    id: "group-qb2-b1-spleen-stomach",
    order: 14,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["脾气虚证", "脾阳虚证", "胃气虚证", "胃阴虚证", "寒湿困脾证"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第121–123页脾胃病辨证及证候鉴别",
      note: "NUR 改编自教材已核验页码内容，B1 配伍组。",
      sourceIds: [deepLoopSourceIds.spleenTextbook],
    },
    members: b1SpleenMembers,
    sourceIds: [deepLoopSourceIds.spleenTextbook],
  },
  {
    id: "group-qb2-b2-exterior-case",
    order: 15,
    questionKind: "b2",
    status: "available",
    groupPrompt: "患者，男，28岁。恶寒发热两天，头身疼痛，鼻塞流涕，舌苔薄白，脉浮。",
    sharedChoices: null,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第89–91页表证辨证与表里转化",
      note: "NUR 根据教材已核验页码组织病例，B2 题组。",
      sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
    },
    members: b2ExteriorMembers,
    sourceIds: [deepLoopSourceIds.exteriorInteriorTextbook],
  },
  {
    id: "group-qb2-b2-diet-case",
    order: 16,
    questionKind: "b2",
    status: "available",
    groupPrompt: "患者，女，42岁。近三月口渴多饮，多食易饥，小便频多，形体日渐消瘦。",
    sharedChoices: null,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第60–61页消谷善饥与消渴",
      note: "NUR 根据教材已核验页码组织病例，B2 题组。",
      sourceIds: [textbookSourceId, deepLoopSourceIds.editorial],
    },
    members: b2DietMembers,
    sourceIds: [textbookSourceId, deepLoopSourceIds.editorial],
  },
  {
    id: "group-qb2-b2-spleen-case",
    order: 17,
    questionKind: "b2",
    status: "available",
    groupPrompt: "患者，男，58岁。食少腹胀，食后尤甚，大便溏薄，神疲乏力，少气懒言，面色萎黄，舌淡苔白，脉缓弱。",
    sharedChoices: null,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "参照教材第121–123页脾气虚证",
      note: "NUR 根据教材已核验页码组织病例，B2 题组。",
      sourceIds: [deepLoopSourceIds.spleenTextbook],
    },
    members: b2SpleenMembers,
    sourceIds: [deepLoopSourceIds.spleenTextbook],
  },
];

export const completeKnowledgePointItems: Record<string, readonly string[]> = {
  "kp-tongue-coating": [
    "assessment-qb2-a1-tongue-coating-thin-thick",
    "assessment-qb2-a1-tongue-coating-peeled",
    "assessment-qb2-term-tongue-greasy",
  ],
  "kp-tongue-body": [
    "assessment-qb2-a1-tongue-body-pale",
    "assessment-qb2-a1-tongue-body-red",
  ],
  "kp-inquiry-cold-heat": [
    "assessment-qb2-a1-cold-heat-aversion-cold",
    "assessment-qb2-a1-cold-heat-alternating",
    "assessment-qb2-a1-cold-heat-tidal-yangming",
  ],
  "kp-inquiry-diet-taste": [
    "assessment-qb2-a1-diet-taste-sweet",
    "assessment-qb2-a1-diet-taste-bitter",
    "assessment-qb2-term-diet-excessive-hunger",
  ],
  "kp-pulse-common": [
    "assessment-qb2-a1-pulse-slow",
    "assessment-qb2-a1-pulse-surging",
    "assessment-qb2-fill-pulse-rapid",
  ],
  "kp-eight-principles-exterior-interior": [
    "assessment-qb2-a1-exterior-half-interior",
    "assessment-qb2-a1-exterior-deficiency-excess",
  ],
  "kp-organs-spleen-stomach": [
    "assessment-qb2-a1-spleen-damp-cold",
    "assessment-qb2-a1-spleen-stomach-qi",
    "assessment-qb2-case-spleen-stomach",
  ],
};

/** 追加进课程定义的顶层主观题（term/case），与 completeAssessmentItems 分离导出便于合并。 */
export const completeSubjectiveItems: readonly AssessmentItemDefinition[] = [
  termDietExcessiveHunger,
  termTongueGreasy,
  caseSpleenStomach,
];
