import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 病理学学习指导与习题集 — 第3章 局部血液循环障碍 题库提取（等比取样）
 * 来源：《病理学学习指导与习题集》（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：10 题
 * - 选择题（a1-single）：9 题（含 A1 型、A2 型病例题）
 * - 判断题 + 问答题（short-answer）：19 题（判断题 10、问答题 9）
 * - B1 配伍题：0 组（本书无 B1 型）
 * - 独立记分题合计：38 题（须等于本文件预算 38）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书含名词解释、判断题、选择题（A1/A2）、问答题；本文件按 38 道预算在
 *   原书顺序内取材：名词解释取第 1–10 题、A1 型取第 1–7 题、A2 型取第 1–2 题（原书
 *   第 53–54 题）、判断题取第 1–10 题、问答题取第 1–9 题；未纳入的题因预算所限。
 *   正确项对齐章末参考答案键号（A1/A2 各小节独立编号），选项已随机重排并同步
 *   correctChoiceIndex。判断题答案按 √/× 键号归位（√=对、×=错）。OCR 错字已按
 *   病理学医学语义恢复（如 静脉血栓成静脉石→静脉血栓形成静脉石、泡沫状红色液体→
 *   泡沫状血性液体 等），数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "pathology-ch03-local-blood-circulation-disorders";
const locatorBase =
  "《病理学学习指导与习题集》 第3章 局部血液循环障碍 习题（核对PDF 第37–54页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），10 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：充血（hyperemia）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "器官或组织因动脉输入血量的增多，称动脉性充血（hyperemia），一般简称充血。",
        "充血是一种主动过程，包括生理性充血和病理性充血，炎症性充血和减压后充血是较为常见的病理性充血。原书名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：淤血（congestion）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "局部组织或器官静脉血液回流受阻，血液淤积于小静脉和毛细血管内，导致血量增加，称静脉性充血（congestion），一般简称淤血。",
        "淤血的原因分为全身性（如心力衰竭）和局部性（局部静脉血管受压与阻塞）；后果包括淤血性水肿、淤血性出血、实质细胞萎缩变性坏死及淤血性硬化。原书名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：发绀（cyanosis）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "由于淤血时微循环的动脉血灌注量减少，血液内氧合血红蛋白含量减少而还原血红蛋白含量增加，发生于体表的淤血可见局部皮肤呈紫蓝色，称发绀（cyanosis）。",
        "发绀是淤血发生于体表时的表现之一，此时局部皮肤温度下降。原书名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：心衰细胞（heart failure cell）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "慢性肺淤血时，肺泡腔内见大量吞噬含铁血黄素颗粒的巨噬细胞，因常在左心衰时发生，故称心衰细胞（heart failure cell）。",
        "心衰细胞是慢性肺淤血的镜下特征之一，与肺褐色硬化的形成有关。原书名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：槟榔肝（nutmeg liver）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "慢性肝淤血时，肝小叶中央区因严重淤血呈暗红色，两个或多个肝小叶中央淤血区可相连，而肝小叶周边部肝细胞则因脂肪变性呈黄色，致使在肝的切面上出现红（淤血区）、黄（肝脂肪变区）相间的状似槟榔切面的条纹，故而得名。",
        "长期的严重肝淤血可发展为淤血性肝硬化。原书名词解释第 5 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：出血（hemorrhage）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血液从血管或心腔溢出，称出血（hemorrhage）。",
        "出血按发生机制可分为破裂性出血和漏出性出血。原书名词解释第 6 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：紫癜（purpura）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "直径 3~5mm 的出血，称紫癜（purpura）。",
        "紫癜是皮肤黏膜出血的表现之一，可见于血小板减少性紫癜等出血性疾病。原书名词解释第 7 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：血栓形成（thrombosis）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "在活体的心脏和血管内血液发生凝固或血液中某些有形成分凝集形成固体质块的过程，称血栓形成（thrombosis）。",
        "血栓形成的条件和机制包括心血管内皮细胞损伤、血流状态的异常和血液凝固性增加。原书名词解释第 8 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：血栓（thrombus）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血栓形成过程中形成的固体质块，称血栓（thrombus）。",
        "血栓可分为白色血栓、混合血栓、红色血栓和透明血栓等类型。原书名词解释第 9 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：混合血栓（mixed thrombus）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "在静脉血栓形成过程中形成的灰白色和红褐色层状交替结构，称为层状血栓；大体粗糙、干燥、圆柱状，与血管壁粘连；光镜下由血小板小梁和充满小梁间纤维蛋白网的红细胞构成，血小板小梁边缘可见有中性粒细胞附着。",
        "混合血栓构成静脉血栓的体部，也可发生于心腔内、动脉粥样硬化溃疡部位或动脉瘤内。原书名词解释第 10 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），9 道（A1 型 7 道 + A2 型病例题 2 道） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-a1001",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "对血栓的叙述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "静脉血栓比动脉血栓多见",
      "混合血栓是层状血栓",
      "静脉血栓均为混合血栓",
      "下肢血栓比上肢血栓多见",
      "毛细血管内血栓为纤维素性血栓",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "静脉血栓均为混合血栓",
        "静脉血栓可为混合血栓（体部），但静脉血栓头部为白色血栓、尾部为红色血栓，并非均为混合血栓；其余叙述均正确。原书 A1 型题第 1 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-a1002",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "易出现气体栓塞的情况是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "深海潜水者迅速升至水面",
      "飞行员按正常速度从地表升入低空",
      "静脉输液误伤动脉",
      "腹部严重冲击伤",
      "短时间内自口腔吸入大量空气",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "深海潜水者迅速升至水面",
        "人体从高气压环境迅速进入常压或低气压环境时，原溶于血液、组织液和脂肪组织的气体（主要是氮气）迅速游离形成气泡，引起气体栓塞（减压病）。原书 A1 型题第 2 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-a1003",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "静脉血栓形成静脉石，是因为发生了",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "透明变性",
      "钙化",
      "机化",
      "脱落栓塞",
      "包裹",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "钙化",
        "血栓继发钙盐沉着称为钙化，血栓钙化后形成静脉石或动脉石。原书 A1 型题第 3 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-a1004",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "心房附壁血栓脱落后可导致肾和脾发生",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "败血性梗死",
      "坏疽",
      "干酪样坏死",
      "贫血性梗死",
      "出血性梗死",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "贫血性梗死",
        "心房附壁血栓脱落后随动脉血流运行阻塞肾、脾等器官的小动脉；肾、脾组织结构致密且侧支循环不丰富，发生贫血性梗死。原书 A1 型题第 4 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-a1005",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可致猝死的栓塞是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脑中动脉栓塞",
      "肺动脉主干栓塞",
      "脾动脉栓塞",
      "肾动脉栓塞",
      "股动脉栓塞",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺动脉主干栓塞",
        "巨大栓子栓塞于肺动脉主干或其大分支，患者可因急性呼吸和循环衰竭死亡（猝死）；肺动脉分支广泛栓塞也可引起右心衰竭而猝死。原书 A1 型题第 5 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-a1006",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与陈旧性心肌梗死灶的形态描述相符合的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "梗死灶周边见充血出血带",
      "梗死灶多血、呈暗红色",
      "位于心脏表面的梗死灶收缩下陷",
      "梗死灶湿润、肿胀",
      "梗死灶隆起于周边正常组织表面",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "位于心脏表面的梗死灶收缩下陷",
        "陈旧性梗死灶由于机化和瘢痕收缩，病灶表面下陷、质地变坚实，充血出血带消失；早期梗死灶边缘可见充血出血带。原书 A1 型题第 6 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-a1007",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下述情况不会导致静脉淤血的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "大隐静脉结扎",
      "肝硬化",
      "右心衰竭",
      "左心衰竭",
      "肠套叠",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "大隐静脉结扎",
        "大隐静脉结扎后因静脉分支相互吻合、侧支循环可有效建立，一般不致淤血；肝硬化（门静脉淤血）、左心衰竭（肺淤血）、右心衰竭（肝淤血等）及肠套叠（肠系膜静脉受压）均可引起静脉淤血。原书 A1 型题第 7 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-a1008",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某患者有明显气促、缺氧、发绀、咳粉红色泡沫痰等症状，X线显示整个肺野透亮度降低、密度增高、边缘云雾状改变，可能的病变是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "气胸",
      "肺淤血",
      "肺出血",
      "肺脂肪栓塞",
      "肺羊水吸入",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺淤血",
        "急性肺淤血时肺体积增大、暗红色，切面流出泡沫状血性液体，肺泡腔内充满水肿液；患者出现气促、缺氧、发绀、咳粉红色泡沫痰，X线示肺野透亮度降低、密度增高、边缘云雾状改变。原书 A2 型题第 53 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-a1009",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "急性菌痢患者出现剧烈腹泻伴呕吐，2天后病情加重，血压迅速下降，神志不清，全身皮下多处出血，针刺部位渗血不止，诊断为弥散性血管内凝血，其发生广泛出血是由于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "血管内皮细胞中毒损伤",
      "凝血酶原合成减少",
      "大量血小板及纤维蛋白原消耗",
      "血管壁广泛损伤",
      "痢疾杆菌毒素损伤肝脏",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "大量血小板及纤维蛋白原消耗",
        "DIC 时微循环内广泛形成透明血栓，大量消耗血小板和凝血因子（纤维蛋白原），导致全身广泛出血和休克。原书 A2 型题第 54 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 判断题 + 问答题（short-answer），19 道（判断题 10、问答题 9） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short001",
    order: 20,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：充血时，局部组织血管内血液含量增多，就其性质可分为动脉性、毛细血管性和静脉性。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。充血按其性质可分为动脉性充血和静脉性充血（淤血），并非分为动脉性、毛细血管性和静脉性三种。",
        "动脉性充血一般简称充血，静脉性充血一般简称淤血。原书判断题第 1 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short002",
    order: 21,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：病理性充血均是静脉性充血。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。病理性充血包括炎症性充血和减压后充血等，属于动脉性充血；静脉性充血（淤血）是另一类充血。",
        "充血分为生理性充血和病理性充血，炎症性充血和减压后充血是较为常见的病理性充血。原书判断题第 2 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short003",
    order: 22,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：生理性充血主要在适应器官和组织生理需要和代谢增强需要时发生。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。生理性充血是在器官和组织生理需要和代谢增强需要时发生的充血。",
        "充血包括生理性充血和病理性充血两大类，生理性充血发生于器官和组织生理需要和代谢增强时。原书判断题第 3 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short004",
    order: 23,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：动脉性充血时，微循环内氧合血红蛋白含量增加，局部组织颜色鲜红，代谢增强，局部组织温度升高。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。动脉性充血时微循环内氧合血红蛋白含量增加，局部组织颜色鲜红、代谢增强、温度升高。",
        "动脉性充血发生于体表时，局部组织颜色鲜红、温度增高，镜下见局部细动脉及毛细血管扩张充血。原书判断题第 4 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short005",
    order: 24,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：淤血就是静脉性充血，可导致胸腔积液（胸水）、腹腔积液（腹水）和心包腔积液等。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。淤血即静脉性充血，可导致淤血性水肿，出现胸腔积液、腹腔积液和心包腔积液等。",
        "淤血的后果包括淤血性水肿、淤血性出血、实质细胞萎缩变性坏死及淤血性硬化。原书判断题第 5 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short006",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：淤血都发生在病理状态。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。淤血（静脉性充血）均发生于病理状态。",
        "与动脉性充血可有生理性充血不同，淤血均属病理性。原书判断题第 6 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short007",
    order: 26,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：由于组织内静脉有较多分支相互吻合，故静脉淤血一般不易发生。只有在当较大的静脉干阻塞或多条静脉阻塞，侧支循环不能有效建立时才引起淤血。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。组织内静脉分支相互吻合、侧支循环较丰富，一般不易发生淤血；当较大的静脉干阻塞或多条静脉阻塞、侧支循环不能有效建立时才引起淤血。",
        "淤血的原因分为全身性和局部性，局部原因见于局部静脉血管的受压与阻塞。原书判断题第 7 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short008",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：慢性心功能衰竭时，首先表现为肝淤血，严重时也可以出现门静脉淤血及四肢淤血。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。慢性心功能衰竭时左心衰竭首先表现为肺淤血、右心衰竭首先表现为肝淤血，并非首先表现为肝淤血；严重时也可出现门静脉淤血及四肢淤血。",
        "左心衰竭主要引起肺淤血，右心衰竭主要引起肝淤血及体循环淤血。原书判断题第 8 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short009",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：淤血的后果取决于淤血的程度和时间的长短。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。淤血的后果不仅取决于淤血的程度和时间的长短，还与淤血发生的速度及侧支循环状况等因素有关。",
        "淤血的后果包括淤血性水肿、淤血性出血、实质细胞萎缩变性坏死及淤血性硬化。原书判断题第 9 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short010",
    order: 29,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：急性肺淤血时，肺体积增大，暗红色，切面可见泡沫状血性液体溢出。镜下可见肺泡壁增厚，纤维化，肺泡腔内充满水肿液和大量吞噬含铁血黄素的巨噬细胞。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。急性肺淤血时肺体积增大、暗红色，切面可见泡沫状血性液体溢出；但肺泡壁增厚、纤维化和肺泡腔内大量吞噬含铁血黄素的巨噬细胞（心衰细胞）是慢性肺淤血的病变特点。",
        "急性肺淤血镜下见肺泡壁毛细血管扩张充血，肺泡腔内充满水肿液；慢性肺淤血时肺泡间隔增厚、纤维化，肺泡腔内见大量心衰细胞。原书判断题第 10 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short011",
    order: 30,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述局部血液循环障碍的主要表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "局部血液循环障碍主要表现为：①血液成分的异常，如充血、淤血、缺血、血栓形成以及继之引起的栓塞（可造成梗死）；②血管壁通透性或完整性改变，如水肿、出血。",
        "原书问答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short012",
    order: 31,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：以肺、肝为例，简述重要器官慢性淤血的病变特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "慢性肺淤血：①大体：肺体积增大、暗红色，淤血性硬化时质地变硬、呈棕褐色，称肺褐色硬化；②光镜：肺泡壁毛细血管与间质小静脉明显扩张充血，肺泡腔内可出现红细胞、巨噬细胞，肺泡壁变厚和纤维化，高倍镜下见吞噬含铁血黄素颗粒的巨噬细胞（心衰细胞），呈散在或片团状分布。慢性肝淤血：①大体：肝小叶中央区因严重淤血呈暗红色，两个或多个肝小叶中央淤血区可相连，肝小叶周边部肝细胞因脂肪变性呈黄色，切面呈红（淤血区）、黄（肝脂肪变区）相间的槟榔样条纹，称槟榔肝；②光镜：肝小叶中央肝窦高度扩张淤血、出血，肝细胞萎缩甚至坏死消失，肝小叶周边部肝细胞脂肪变性，胞质可见多个脂肪空泡。",
        "原书问答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short013",
    order: 32,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述血栓的主要类型及其分类原则。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血栓根据形态特点可分为白色血栓、混合血栓、红色血栓和透明血栓，可多种联合出现也可单独发生；根据发生部位可分为动脉性血栓、静脉性血栓、微血管血栓、附壁血栓、心脏瓣膜血栓。在静脉腔内，白色血栓、混合血栓和红色血栓依次发生，构成完整的静脉延续性血栓；白色血栓可单独发生于心瓣膜上形成疣状赘生物；透明血栓常于弥散性血管内凝血时发生，出现于微循环内。",
        "原书问答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short014",
    order: 33,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述常见四型血栓的病变特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①白色血栓：肉眼呈灰白色小结节或赘生物状，表面粗糙、质实，与血管壁紧密黏着不易脱落；光镜下为无结构淡红色，主要由血小板和少量纤维素构成；主要发生于心瓣膜和静脉血栓起始部。②混合血栓：肉眼呈灰白色和红褐色层状交替结构，称层状血栓；由珊瑚状血小板小梁及小梁间网络大量红细胞的纤维蛋白网构成，血小板小梁边缘可见中性粒细胞附着；构成静脉血栓的体部，可发生于心腔内、动脉粥样硬化溃疡部位或动脉瘤内。③红色血栓：肉眼呈暗红色、湿润、有弹性，与血管壁无粘连；镜下见纤维蛋白网眼内充满血细胞，主要见于静脉内，构成静脉血栓尾部。④透明血栓：发生于微循环内，只能在显微镜下观察到，主要由均匀红染的纤维蛋白构成，多见于弥散性血管内凝血。",
        "原书问答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short015",
    order: 34,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述血栓的结局及其对机体的影响。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①血栓的结局：溶解和吸收、机化、再通、钙化，可脱落形成栓子致栓塞。②对机体的影响：血栓形成可对破裂的血管起止血作用、避免大出血，对机体有利；但在多数情况下给机体造成严重后果甚至危及生命，如阻塞血管、造成栓塞、使心瓣膜变形、导致广泛性出血（DIC）。",
        "原书问答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short016",
    order: 35,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：列举临床常见四类栓子并简述其运行途径。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "临床常见四类栓子为血栓栓子、脂肪栓子、空气栓子、羊水栓子。栓子的运行途径一般与血流方向一致，少数情况下可发生动、静脉系统交叉运行或罕见逆血流运行：①来自体静脉和右心的栓子栓塞于肺动脉及其分支，引起肺动脉系统栓塞，只有某些体积小而富有弹性的栓子才有可能通过肺毛细血管，经左心进入动脉系统阻塞某些动脉分支；②左心和动脉系统来源的栓子栓塞于体循环的动脉分支；③门静脉系统的栓子栓塞于肝脏。",
        "原书问答题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short017",
    order: 36,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：比较贫血性梗死和出血性梗死的异同。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "贫血性梗死（白色梗死）与出血性梗死（红色梗死）的异同：①原因：前者为动脉阻断、静脉回流正常；后者为动脉、静脉同时阻断。②发生条件与好发部位：前者发生于组织结构致密、侧支循环不丰富的器官（心、肾、脾等）；后者发生于严重淤血、组织结构疏松、侧支循环丰富或双重血供的器官（肺、肠等）。③肉眼观察：前者形状与血管分布一致，肾、脾呈锥体形，心呈地图形，颜色苍白、含血量少，质地坚实、干燥，边界清楚；后者形状与血管分布一致，肺呈锥形、肠呈节段形，颜色暗红、含血量多，质实、潮湿，边界不清。④镜下特点：前者细胞坏死、组织轮廓尚存；后者组织坏死伴弥散性出血。",
        "原书问答题第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short018",
    order: 37,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述栓塞的类型及其后果。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "栓塞的类型包括血栓栓塞、气体栓塞、脂肪栓塞、羊水栓塞，以及其他异物栓塞（如寄生虫、虫卵、组织块、子弹片等）和肿瘤细胞栓塞等。后果：肺动脉栓塞可致肺出血性梗死，甚至急性呼吸衰竭、心力衰竭而死亡；脑动脉栓塞可致脑梗死，呼吸中枢和心血管中枢的梗死可引起患者死亡；肾动脉栓塞可引起肾脏梗死；脾动脉栓塞可引起脾脏梗死；肠系膜动脉栓塞可致肠梗死、湿性坏疽形成；肝动脉栓塞可引起肝梗死等。脂肪栓塞可引起神经症状、呼吸困难、血小板减少导致皮肤黏膜出血等；气体栓塞可导致严重循环障碍、右心衰竭、呼吸衰竭而死亡；羊水栓塞后果严重，患者常在分娩过程中或分娩后突然出现呼吸困难、发绀、抽搐、休克、昏迷，甚至死亡。",
        "原书问答题第 8 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch03-local-blood-circulation-disorders-short019",
    order: 38,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述血栓形成、栓塞、梗死的概念以及三者间的相互关系。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①概念：血栓形成是活体的心脏或血管腔内血液成分凝固形成固体质块的过程；栓塞是在循环血液中出现不溶于血液的异常物质，随血流运行阻塞血管腔的现象；梗死是器官或局部组织由于血管阻塞、血流停滞导致缺氧而发生的坏死。②相互关系：血栓形成→血栓栓子→栓塞→梗死（无足够侧支循环时发生），原位形成的血栓也可导致梗死。",
        "原书问答题第 9 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1/B2 组题（bGroups）：本书无 B1/B2 型，为空数组 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
