import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 病理学学习指导与习题集 — 第6章 肿瘤 题库提取（等比取样）
 * 来源：《病理学学习指导与习题集》（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：10 题
 * - 选择题（a1-single）：10 题（含 A1 型 8、A2 型病例题 2）
 * - 判断题 + 问答题（short-answer）：28 题（判断题 10、问答题 18）
 * - B1 配伍题：0 组（本书无 B1 型）
 * - 独立记分题合计：48 题（须等于本文件预算 48）
 * - 缺失答案：0；无法可靠提取：0（A1 型第 3–6 题选项 OCR 缺失无法可靠重建，
 *   换同源清晰题第 7–12 题，如实记录）
 * - 说明：本章原书含名词解释、判断题、选择题（A1/A2）、问答题；本文件按 48 道预算在
 *   原书顺序内取材：名词解释取第 1–10 题、A1 型取第 1–2、7–12 题、A2 型取第 61–62 题、
 *   判断题取第 1–10 题、问答题取第 1–18 题（全取）；未纳入的题因预算所限。正确项对齐
 *   章末参考答案键号（A1/A2 各小节独立编号），选项已随机重排并同步 correctChoiceIndex。
 *   判断题答案按 √/× 键号归位（√=对、×=错）。OCR 错字已按病理学医学语义恢复（如
 *   昇型性→异型性、昇位→异位、Epstein-Bar→Epstein-Barr、阝粒子→β粒子、子官→子宫、
 *   卵菓→卵巢、只检→尸检、又线→X线、病理性核分裂等），数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "pathology-ch06-tumor";
const locatorBase =
  "《病理学学习指导与习题集》 第6章 肿瘤 习题（核对PDF 第83–104页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），10 道（原书第 1–10 题） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pathology-pathology-ch06-tumor-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肿瘤（neoplasm）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤（neoplasm）是机体在各种致瘤因素作用下，在基因水平上失去对其生长的正常调控，导致细胞异常增殖而形成的新生物。",
        "肿瘤常表现为机体局部的异常团块（肿块）；肿瘤性增殖与非肿瘤性增殖有着本质区别，前者为单克隆性、失去控制、对机体有害。原书第6章名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：分化（differentiation）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "分化（differentiation）是指肿瘤组织在形态和功能上与某种正常组织的相似之处，相似的程度称为肿瘤的分化程度。",
        "有些恶性肿瘤细胞分化很差、异型性显著，称为间变性肿瘤（anaplastic neoplasm），多为高度恶性的肿瘤。原书第6章名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：异质性（heterogeneity）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "异质性（heterogeneity）是指由一个克隆来源的肿瘤细胞群，在生长过程中出现侵袭能力、生长速度、对生长信号的反应、对抗肿瘤药物的敏感性等方面均有差异的亚克隆的过程。",
        "恶性肿瘤从一个发生恶性转化的细胞单克隆性增殖和生长过程中，经过许多代分裂繁殖产生的子代细胞可出现不同的基因改变或其他大分子改变，成为具有各自特性的亚克隆；侵袭性更强、更能逃避宿主反应的亚克隆得以存活与繁衍，使肿瘤演进为侵袭性更强的异质性肿瘤。原书第6章名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：异型性（atypia）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "异型性（atypia）是指肿瘤在细胞形态和组织结构上，与其相应的正常细胞和组织有不同程度的差异，包括细胞异型性和组织结构异型性两个方面。",
        "肿瘤的细胞异型性表现为：细胞大小和形态很不一致（多形性），出现瘤巨细胞；细胞核体积增大、核质比增高；核的大小、形状和染色差别较大（核的多形性）；核仁明显、体积大、数目增多；核分裂象增多，出现病理性核分裂象。原书第6章名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：浸润（infiltration, invasion）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "浸润（infiltration, invasion）是指瘤细胞借助自身的运动能力，在组织间隙中蔓延生长；或穿破原有组织屏障，侵犯邻近器官或组织的现象。",
        "恶性肿瘤多呈浸润性生长，肿瘤细胞长入并破坏周围组织（包括组织间隙、淋巴管或血管）；浸润性肿瘤没有被膜（或破坏原来的被膜），与邻近的正常组织无明显界限。原书第6章名词解释第 5 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：演进（progression）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "演进（progression）是指恶性肿瘤在生长过程中变得越来越富有侵袭性和获得更大异质性的现象。",
        "肿瘤的演进可表现为生长速度加快、浸润周围组织和发生远处转移，与肿瘤获得越来越大的异质性有关。原书第6章名词解释第 6 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：间变（anaplasia）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "间变（anaplasia）是指恶性肿瘤细胞分化很差时异型性明显，或出现多形性、或缺乏分化的状态，这时的肿瘤称之为间变性肿瘤。",
        "间变性肿瘤多为高度恶性的肿瘤，其特点是显著的异型性、较多的病理性核分裂象等。原书第6章名词解释第 7 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：转移（metastasis）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "转移（metastasis）是指恶性肿瘤细胞从原发部位侵入血管、淋巴管或体腔，迁徙到其他部位继续生长，形成与原发肿瘤同样类型的肿瘤的过程。",
        "转移是恶性肿瘤的特点，但并非所有恶性肿瘤都会发生转移；转移途径包括淋巴道转移、血道转移和种植性转移。原书第6章名词解释第 8 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：畸胎瘤（teratoma）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "畸胎瘤（teratoma）是一种来源于生殖细胞的肿瘤，由两个或两个以上胚层的多种组织构成。",
        "畸胎瘤多发生于性腺（卵巢和睾丸），一般含有两个以上胚层的多种成分，结构混乱，分为良性畸胎瘤和恶性畸胎瘤两类。原书第6章名词解释第 9 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：癌前疾病或癌前病变（precancerous disease or precancerous lesion）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "癌前疾病或癌前病变（precancerous disease or precancerous lesion）是指具有癌变的潜在可能性的病变或者疾病；癌前病变大多数不会演变成癌，仅仅是其中部分可能演变成癌症。",
        "常见癌前疾病或病变包括：大肠腺瘤、乳腺导管上皮非典型增生、慢性胃炎与肠上皮化生、慢性溃疡性结肠炎、皮肤慢性溃疡、黏膜白斑等。原书第6章名词解释第 10 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），10 道（A1 型第 1–2、7–12 题，A2 型第 61–62 题） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pathology-pathology-ch06-tumor-a1001",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肿瘤的说法，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "常表现机体局部的异常组织团块",
      "是以细胞异常增殖为特点的一大类疾病",
      "肿瘤细胞生长旺盛，失去控制",
      "肿瘤细胞的形态、代谢和功能均正常",
      "肿瘤性的增殖与机体不协调，对机体有害",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤细胞的形态、代谢和功能均正常",
        "肿瘤细胞具有异常的形态、代谢和功能，并不同程度地失去分化成熟的能力，故“肿瘤细胞的形态、代谢和功能均正常”的说法错误。原书第6章 A1 型题第 1 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-a1002",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肿瘤的异型性是指",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肿瘤的分化程度",
      "肿瘤组织结构和细胞形态与相应的正常组织有不同程度的差异",
      "肿瘤组织结构和细胞形态与相对应的正常组织的相似和不同之处",
      "肿瘤的异常增生",
      "肿瘤组织结构和细胞形态与相应的正常组织的相似之处",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤组织结构和细胞形态与相应的正常组织有不同程度的差异",
        "异型性是指肿瘤在细胞形态和组织结构上与其相应的正常细胞和组织有不同程度的差异，包括细胞异型性和组织结构异型性两方面。原书第6章 A1 型题第 2 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-a1003",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可含有三个胚层组织的肿瘤是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "绒毛膜癌",
      "畸胎瘤",
      "精原细胞瘤",
      "纤维腺瘤",
      "淋巴瘤",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "畸胎瘤",
        "畸胎瘤来源于生殖细胞，由两个或两个以上胚层（可含三个胚层）的多种组织构成，如可见毛发、牙齿、骨、神经等组织。原书第6章 A1 型题第 7 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-a1004",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "属于癌前病变的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "结肠多发性腺瘤",
      "慢性浅表性胃炎",
      "十二指肠溃疡",
      "病毒性肝炎",
      "乳腺增生",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结肠多发性腺瘤",
        "常见癌前疾病或病变包括大肠腺瘤（结肠多发性腺瘤）、乳腺导管上皮非典型增生、慢性胃炎与肠上皮化生、慢性溃疡性结肠炎、皮肤慢性溃疡、黏膜白斑等。原书第6章 A1 型题第 8 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-a1005",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于良恶性肿瘤的鉴别，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "良性肿瘤对机体影响较小",
      "良性肿瘤核分裂象多见，可见病理性核分裂",
      "恶性肿瘤不会发生转移",
      "恶性肿瘤生长方式为膨胀性或外生性",
      "良性肿瘤常形成溃疡、出血",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "良性肿瘤对机体影响较小",
        "良性肿瘤分化好、异型性小，核分裂象无或少、不见病理性核分裂，生长缓慢，呈膨胀性或外生性生长，不转移，对机体影响较小、主要为局部压迫或阻塞；恶性肿瘤核分裂象多、可见病理性核分裂，呈浸润性或外生性生长，可转移，继发改变常见。原书第6章 A1 型题第 9 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-a1006",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "恶性肿瘤血道转移的最常见部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肝、肺",
      "脑、肾",
      "脾、脑",
      "肺、脾",
      "肝、脑",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝、肺",
        "恶性肿瘤可以通过血道转移累及许多器官，但最常受累的脏器是肺和肝。原书第6章 A1 型题第 10 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-a1007",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "诊断恶性肿瘤的主要依据是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肿瘤的继发改变",
      "肿瘤的异型性",
      "肿瘤的大体形态",
      "肿瘤对机体的影响",
      "肿瘤的大小",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤的异型性",
        "区分异型性的大小是诊断肿瘤与否、确定分化程度和其良、恶性的主要组织学依据，故诊断恶性肿瘤的主要依据是肿瘤的异型性。原书第6章 A1 型题第 11 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-a1008",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肠腺瘤和肠腺癌的鉴别主要依据是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "细胞的异型性",
      "腺体的多少",
      "发生的部位",
      "间质的多少",
      "是否伴有出血坏死",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞的异型性",
        "腺瘤与腺癌的鉴别主要依据细胞异型性（及组织结构异型性）的大小，异型性显著、出现病理性核分裂者考虑恶性。原书第6章 A1 型题第 12 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-a1009",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，女，32岁，一侧颈部淋巴结肿大，穿刺病理活检查见乳头状结构病变，异型性不大。最可能的诊断是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "鼻咽癌转移",
      "甲状腺癌转移",
      "食管癌转移",
      "肺癌转移",
      "喉癌转移",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甲状腺癌转移",
        "甲状腺乳头状癌镜下见乳头状结构，异型性不大，常较早发生颈部淋巴结转移，故最可能为甲状腺癌转移。原书第6章 A2 型题第 61 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-a1010",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，女，28岁，卵巢发现包块。大体呈囊性，可见毛发、牙齿等，镜下可见纤毛柱状上皮、骨、神经等组织。最可能的诊断是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "卵巢黏液性囊腺瘤",
      "卵巢子宫内膜异位囊肿",
      "卵巢囊性畸胎瘤",
      "卵巢癌",
      "卵巢浆液性囊腺瘤",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "卵巢囊性畸胎瘤",
        "畸胎瘤由两个或两个以上胚层的多种组织构成，大体呈囊性，可见毛发、牙齿，镜下可见纤毛柱状上皮、骨、神经等组织，符合卵巢囊性畸胎瘤。原书第6章 A2 型题第 62 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 判断题 + 问答题（short-answer），28 道（判断题第 1–10 题、问答题第 1–18 题） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pathology-pathology-ch06-tumor-short001",
    order: 21,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：肿瘤大多数表现为局部肿块，出现局部肿块即是发生了肿瘤。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。肿瘤大多数表现为局部肿块，但出现局部肿块不一定是发生了肿瘤。",
        "局部肿块也可由炎症性增生、血肿、囊肿等非肿瘤性病变引起，需病理检查鉴别。原书第6章判断题第 1 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short002",
    order: 22,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：肿瘤的异型性主要反映了肿瘤的组织来源。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。肿瘤的异型性主要反映肿瘤的分化程度（成熟程度），而非组织来源。",
        "异型性是指肿瘤在细胞形态和组织结构上与其相应正常细胞和组织的差异程度，异型性越大，分化越差、恶性程度越高。原书第6章判断题第 2 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short003",
    order: 23,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：肿瘤的分期指肿瘤细胞的分化程度。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。肿瘤的分期指恶性肿瘤的生长范围和播散程度；分化程度是肿瘤分级（grade）的依据。",
        "分级根据恶性肿瘤的分化程度、异型性、核分裂象数目等描述其恶性程度；分期反映生长范围和播散程度，国际上广泛采用 TNM 分期系统。原书第6章判断题第 3 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short004",
    order: 24,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：诊断恶性肿瘤的主要形态学依据是组织结构紊乱。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。诊断恶性肿瘤的主要形态学依据是肿瘤的异型性（细胞异型性和组织结构异型性），而非单纯的组织结构紊乱。",
        "异型性的大小是诊断肿瘤与否、确定分化程度和良恶性的主要组织学依据。原书第6章判断题第 4 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short005",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：肿瘤的生物学行为与肿瘤的生长部位和生长方式密切相关。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。肿瘤的生物学行为与肿瘤的生长部位和生长方式密切相关。",
        "肿瘤的生长方式（膨胀性、外生性、浸润性）与生长部位可反映其良恶性及生物学行为，如浸润性生长提示恶性。原书第6章判断题第 5 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short006",
    order: 26,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：肿瘤转移的确切依据为在远隔器官形成与原发瘤同样组织学类型的肿瘤。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。肿瘤转移的确切依据是在远隔器官形成与原发瘤同样组织学类型的肿瘤。",
        "转移是指恶性肿瘤细胞从原发部位侵入淋巴管、血管或体腔，迁徙到其他部位继续生长，形成与原发部位同样类型肿瘤的过程。原书第6章判断题第 6 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short007",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：肿瘤性增殖与非肿瘤性增殖的根本区别为细胞增殖呈现不可逆的自主性生长。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。肿瘤性增殖与非肿瘤性增殖的根本区别在于肿瘤细胞增殖呈不可逆的自主性生长。",
        "肿瘤性增殖为单克隆性，病因去除后细胞仍持续增殖，失去控制、具有相对独立性，对机体有害；非肿瘤性增殖为多克隆性，有自限性、受机体调控。原书第6章判断题第 7 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short008",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：转移是恶性肿瘤最重要的生物学特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。转移是恶性肿瘤最重要的生物学特点。",
        "转移是恶性肿瘤的特点，但并非所有恶性肿瘤都会发生转移。原书第6章判断题第 8 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short009",
    order: 29,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：淋巴结转移性癌的可靠依据为淋巴结肿大。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。淋巴结转移性癌的可靠依据是病理检查在淋巴结内发现与原发癌同类型的癌细胞，而非单纯淋巴结肿大。",
        "淋巴结肿大也可由炎症、反应性增生等引起，需病理活检证实转移。原书第6章判断题第 9 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short010",
    order: 30,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：良性肿瘤异型性主要表现在细胞形态和组织结构两方面均有明显异型性。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。良性肿瘤的细胞异型性较小，但可有不同程度的组织结构异型性，并非细胞形态和组织结构两方面均有明显异型性。",
        "恶性肿瘤的细胞异型性和组织结构异型性都比较明显；良性肿瘤细胞异型性小。原书第6章判断题第 10 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short011",
    order: 31,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：什么是肿瘤？肿瘤性增殖与非肿瘤性增殖有什么区别？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤是在各种致瘤因素作用下，机体局部细胞在基因水平上失去对其生长的正常调控，导致克隆性异常增殖而形成的新生物。肿瘤性增殖与非肿瘤性增殖的区别：①克隆性：肿瘤性增殖为单克隆性，非肿瘤性增殖为多克隆性；②病因去除后：肿瘤性增殖细胞持续增殖，非肿瘤性增殖一般不再继续；③分化成熟程度：肿瘤性增殖不同程度失去分化成熟的能力，非肿瘤性增殖能够分化成熟并在一定程度上恢复原来正常组织的结构和功能；④与机体的协调性：肿瘤性增殖失去控制、具有相对独立性，对机体有害，非肿瘤性增殖具有自限性、受机体调控，是符合机体需要的生物学过程。",
        "原书第6章问答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short012",
    order: 32,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述肿瘤的异型性。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤的异型性是指肿瘤在细胞形态和组织结构上与其相应正常细胞和组织有不同程度的差异，包括细胞异型性和组织结构异型性两方面。细胞异型性表现：细胞体积异常、多形性（出现瘤巨细胞）、核体积增大核浆比增高、核的多形性、核仁明显且数目增多、核分裂象增多并出现病理性核分裂。结构异型性是肿瘤细胞形成的组织结构在空间排列方式上与相应正常组织的差异。异型性大小反映肿瘤组织的成熟程度（分化程度）：良性肿瘤细胞异型性小，但可有不同程度的组织结构异型性；恶性肿瘤细胞异型性和组织结构异型性都比较明显。区分异型性大小是诊断肿瘤、确定分化程度和良恶性的主要组织学依据。",
        "原书第6章问答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short013",
    order: 33,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：肿瘤的常见颜色有哪些？如何通过肿瘤的颜色作出初步诊断？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤的颜色由组成肿瘤的组织、细胞及其产物的颜色决定。通常情况下肿瘤多呈灰白或灰红色，可因含血量多寡、有无变性坏死出血及是否含有色素等呈现不同颜色。据此可大致推测肿瘤类型：纤维组织的肿瘤切面多呈灰白色；脂肪瘤呈黄色；血管瘤常呈红色或暗红色；绿色瘤呈绿色；黑色素瘤细胞产生黑色素，使肿瘤呈黑褐色。肿瘤发生变性、坏死、出血等继发改变时，颜色可发生变化。",
        "原书第6章问答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short014",
    order: 34,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：肿瘤的硬度是由哪些因素决定的？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤的硬度（质地）与肿瘤的种类、肿瘤实质与间质的比例以及有无变性坏死等有关。骨瘤很硬，脂肪瘤质地较软；实质多于间质的肿瘤一般较软（如大肠腺瘤），反之则较硬（如伴有纤维增生反应的浸润性癌）；瘤组织发生坏死时变软，有钙质沉着（钙化）或骨质形成（骨化）时则变硬。",
        "原书第6章问答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short015",
    order: 35,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：肿瘤的间质对肿瘤的生长有何意义？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤的间质一般由结缔组织、血管和淋巴细胞等组成，起着支持和营养肿瘤实质、参与肿瘤免疫反应等作用。通常生长迅速的肿瘤间质血管较丰富而结缔组织较少，生长缓慢的肿瘤间质血管相对较少。间质内常有数量不等的淋巴细胞等单个核细胞浸润，体现机体对肿瘤组织的免疫应答。肿瘤间质构成的微环境对肿瘤细胞生长、分化和迁移具有重要影响。",
        "原书第6章问答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short016",
    order: 36,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：肿瘤常见的生长方式有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤常见的生长方式有膨胀性、外生性和浸润性生长。①膨胀性生长：实质器官良性肿瘤多呈膨胀性生长，生长缓慢，推挤但不侵犯周围组织，多呈结节状，周围常有完整包膜或假包膜，与周围组织分界清楚，对局部器官、组织的影响主要是挤压和占位效应。②外生性生长：多发生在体表、体腔或管道器官腔面，向表面生长形成乳头状、息肉状、蕈状或菜花状肿物；良、恶性肿瘤都可呈外生性生长，但恶性肿瘤在外生性生长的同时基底部往往也呈浸润性生长，生长迅速时中央部易坏死脱落形成底部高低不平、边缘隆起的恶性溃疡。③浸润性生长：是大多数恶性肿瘤的生长方式，肿瘤细胞侵入周围组织间隙、淋巴管或血管内，浸润并破坏周围组织，往往没有包膜，与邻近正常组织紧密交织、无明显界限。",
        "原书第6章问答题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short017",
    order: 37,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：恶性肿瘤的转移方式有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "恶性肿瘤的转移方式有：①淋巴道转移：肿瘤细胞侵入淋巴管，随淋巴流首先到达局部淋巴结（区域淋巴结）边缘窦，可继续转移至淋巴循环下一站淋巴结，最后可经胸导管进入血流继发血道转移；上皮源性恶性肿瘤（癌）最常见的转移方式是淋巴道转移。②血道转移：瘤细胞侵入血管后随血流到达远处器官继续生长形成转移瘤；因静脉壁较薄、管内压力较低，瘤细胞多经静脉入血，少数经淋巴管间接入血；最常受累的脏器是肺和肝。③种植性转移：发生于胸腹腔等体腔内器官的恶性肿瘤，侵及器官表面时瘤细胞脱落，种植在体腔其他器官表面，形成多个转移性肿瘤，常见于腹腔器官恶性肿瘤。",
        "原书第6章问答题第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short018",
    order: 38,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：列表比较良、恶性肿瘤的区别。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "良、恶性肿瘤的区别（表6-2）：①分化程度：良性分化好、异型性小，恶性不同程度分化障碍或未分化、异型性大；②核分裂象：良性无或少、不见病理性核分裂象，恶性多、可见病理性核分裂象；③生长速度：良性缓慢，恶性较快；④生长方式：良性膨胀性或外生性生长，恶性浸润性或外生性生长；⑤继发改变：良性少见，恶性常见（出血、坏死、溃疡形成）；⑥转移：良性不转移，恶性可转移；⑦复发：良性不复发或很少复发，恶性易复发；⑧对机体的影响：良性较小、主要为局部压迫或阻塞，恶性较大、破坏原发部位和转移部位的组织，可致坏死、出血、合并感染及恶病质。",
        "原书第6章问答题第 8 题参考答案（详见表6-2）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short019",
    order: 39,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：肿瘤对机体的影响有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "良性肿瘤分化较成熟、生长缓慢、在局部生长、不浸润不转移，对机体影响相对较小，主要表现为局部压迫和阻塞症状，其影响主要与发生部位和继发变化有关。恶性肿瘤分化不成熟、生长较迅速，浸润破坏器官的结构和功能并可发生转移，对机体影响严重：除局部压迫和阻塞症状外，发生于消化道者更易并发溃疡、出血甚至穿孔导致腹膜炎；肿瘤产物或合并感染可引起发热；压迫、浸润局部神经可引起顽固性疼痛；晚期患者往往发生恶病质导致死亡；异位内分泌肿瘤还可引起异位内分泌综合征及副肿瘤综合征。",
        "原书第6章问答题第 9 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short020",
    order: 40,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：肿瘤命名的一般原则是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "良性肿瘤命名的一般原则是在组织或细胞类型的名称后面加一个“瘤”字（英文后缀-oma），如腺瘤、平滑肌瘤。恶性肿瘤命名的一般原则：①上皮组织的恶性肿瘤统称癌，在上皮名称后加“癌”字，如鳞状细胞癌、腺癌；同时具有腺癌和鳞状细胞癌成分者称腺鳞癌；缺乏特定上皮分化特征的癌称未分化癌。②间叶组织的恶性肿瘤统称肉瘤，在间叶组织名称后加“肉瘤”二字，如纤维肉瘤、脂肪肉瘤、骨肉瘤；缺乏特定间叶组织分化特征的肉瘤称未分化肉瘤；同时具有癌和肉瘤两种成分者称癌肉瘤。此外还可结合形态特点命名，如乳头状囊腺瘤、乳头状囊腺癌。少数约定俗成的命名不完全依照上述原则：①“母细胞瘤”，良性者如骨母细胞瘤，恶性者如神经母细胞瘤、髓母细胞瘤、肾母细胞瘤；②白血病、精原细胞瘤等虽称“病”或“瘤”实为恶性肿瘤；③有些恶性肿瘤直接称“恶性…瘤”，如恶性黑色素瘤、恶性畸胎瘤、恶性脑膜瘤、恶性神经鞘瘤；④以学者名字命名，如尤因（Ewing）肉瘤、霍奇金（Hodgkin）淋巴瘤；⑤以细胞形态命名，如透明细胞肉瘤；⑥“瘤病”指肿瘤多发状态，如神经纤维瘤病、脂肪瘤病、血管瘤病；⑦畸胎瘤是性腺或胚胎剩件中的全能细胞发生的肿瘤，多发生于性腺，含两个以上胚层的多种成分，结构混乱，分良性畸胎瘤和恶性畸胎瘤两类。",
        "原书第6章问答题第 10 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short021",
    order: 41,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：常见的上皮组织肿瘤有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常见的良性上皮组织肿瘤有：鳞状上皮乳头状瘤、腺瘤、尿路上皮乳头状瘤。常见的恶性上皮组织肿瘤有：鳞状细胞癌、基底细胞癌、尿路上皮癌、腺癌。",
        "原书第6章问答题第 11 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short022",
    order: 42,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：常见的肉瘤有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常见的间叶组织恶性肿瘤（肉瘤）有：纤维肉瘤、脂肪肉瘤、平滑肌肉瘤、横纹肌肉瘤、血管肉瘤、淋巴管肉瘤、骨肉瘤、软骨肉瘤。",
        "原书第6章问答题第 12 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short023",
    order: 43,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：癌的一般特点是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "癌是由上皮组织发生的恶性肿瘤，是人类最常见的恶性肿瘤，40岁以上人群发生率显著增加。癌常以浸润性生长为主，与周围组织分界不清；发生在皮肤、黏膜表面的癌可呈息肉状、蕈伞状或菜花状，表面常有坏死及溃疡形成；发生在器官内的癌常呈不规则结节状，呈树根状或蟹足状向周围组织浸润，质地较硬，切面常为灰白色。镜下癌细胞可呈巢状（癌巢）、腺泡状、腺管状或条索状排列，与间质分界一般较清楚；网状纤维染色见癌细胞之间多无网状纤维，网状纤维只见于癌巢周围。癌的转移早期一般多经淋巴道，晚期发生血道转移。",
        "原书第6章问答题第 13 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short024",
    order: 44,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：肉瘤的一般特点是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肉瘤是恶性间叶组织肿瘤的总称，较癌少见。有些类型较多发生于儿童或青少年，如胚胎性横纹肌肉瘤多见于儿童，60%的骨肉瘤发生在25岁以下；有些肉瘤主要发生于中老年人，如脂肪肉瘤。肉瘤体积常较大，质软，切面多呈灰红色、均质性、湿润，外观多呈鱼肉状，易发生出血、坏死、囊性变等继发改变。镜下肉瘤细胞大多弥漫排列，不形成细胞巢，与间质分界不清，网状纤维染色可见肉瘤细胞间存在网状纤维；间质结缔组织一般较少，但血管常较丰富，故肉瘤多先由血道转移。",
        "原书第6章问答题第 14 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short025",
    order: 45,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述食管癌、胃癌、大肠癌的共同点（或相似点）。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "食管癌、胃癌、大肠癌的共同点（或相似点）：①发病年龄、早期转移途径相似；②有相似的肉眼类型，如溃疡型、蕈伞型（息肉型、隆起型）、浸润型（髓质型、缩窄型）等；③均来源于相应消化道上皮组织，镜下组织学特点为多形成癌巢；④早、中、晚期的分期均以浸润的深度为主要依据。",
        "原书第6章问答题第 15 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short026",
    order: 46,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述肿瘤的分级、分期及与肿瘤发生发展的关系。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤的分级是描述恶性肿瘤恶性程度的指标，根据分化程度、异型性、核分裂象数目等进行分级：三级分级法中 I 级高分化、分化良好、恶性程度低，II 级为中分化、中度恶性，III 级为低分化、恶性程度高；某些肿瘤采用低级别（分化较好）和高级别（分化较差）的两级分级法。肿瘤的分期是指恶性肿瘤的生长范围和播散程度，需考虑原发肿瘤大小、浸润深度、浸润范围、邻近器官受累情况、局部和远处淋巴结转移情况及远处转移等，国际上广泛采用 TNM 分期系统。肿瘤体积越大、生长范围和播散程度越广，预后越差。分级和分期是制定治疗方案和估计预后的重要指标，一般来说分级和分期越高，生存率越低。",
        "原书第6章问答题第 16 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short027",
    order: 47,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：什么是癌前病变？常见的癌前病变有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "癌前病变（癌前疾病）是指某些疾病（或病变）虽然本身不是恶性肿瘤，但具有发展为恶性肿瘤的潜在可能，患者发生相应恶性肿瘤的风险增加；癌前病变并不一定会发展为癌。常见的癌前病变有：大肠腺瘤、乳腺导管上皮不典型增生、慢性胃炎与肠上皮化生、溃疡性结肠炎、皮肤慢性溃疡、黏膜白斑等。从癌前状态发展为癌可经过很长时间，在上皮组织可先出现非典型增生或异型增生，再发展为局限于上皮内的原位癌，进而发展为浸润性癌。",
        "原书第6章问答题第 17 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch06-tumor-short028",
    order: 48,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述非典型增生、异型增生与原位癌的区别。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "非典型增生用以描述细胞增生并出现细胞和结构异型性，多用于上皮病变，既可见于肿瘤性病变，也可见于修复、炎症等情况下出现的反应性非典型增生，多用于无法确定病变性质时的描述。异型增生用以描述与肿瘤形成相关的非典型增生，具有细胞和结构异型性，但并非总是进展为癌，致病因素去除时某些未累及上皮全层的异型增生可能逆转消退。原位癌指异型增生的细胞在形态和生物学特性上与癌细胞相同，常累及上皮全层，但尚未突破基底膜向下浸润，有时也称上皮内癌，是一种早期癌，如能及时发现和治疗可防止其发展为浸润性癌。",
        "原书第6章问答题第 18 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 配伍题（bGroups），0 组（本书无 B1 型） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
