import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 病理学学习指导与习题集 — 第9章 心血管系统疾病 题库提取（等比取样）
 * 来源：《病理学学习指导与习题集》（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：12 题
 * - 选择题（a1-single）：12 题（含 A1 型 10、A2 型病例题 2）
 * - 判断题 + 问答题（short-answer）：22 题（判断题 14、问答题 8）
 * - B1 配伍题：0 组（本书无 B1 型）
 * - 独立记分题合计：46 题（须等于本文件预算 46）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书含名词解释、判断题、选择题（A1/A2）、问答题；本文件按 46 道预算在
 *   原书顺序内取材：名词解释取第 1–12 题、A1 型取第 1–10 题、A2 型取第 41–42 题、
 *   判断题取第 1–14 题、问答题取第 1–8 题（全取）；未纳入的题因预算所限。正确项对齐
 *   章末参考答案键号（A1/A2 各小节独立编号），选项已随机重排并同步 correctChoiceIndex。
 *   判断题答案按 √/× 键号归位（√=对、×=错）。OCR 错字已按病理学医学语义恢复（如
 *   心肉膜炎→心内膜炎、赞生物→赘生物、只检→尸检、菱缩→萎缩、左止肢→左上肢、
 *   动脉脉痉挛→动脉痉挛、破人侧脑室→破入侧脑室、主要内左心室→主要为左心室、
 *   Aschoft→Aschoff、乙带→Z带、肉柱→肉柱等），数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "pathology-ch09-cardiovascular-diseases";
const locatorBase =
  "《病理学学习指导与习题集》 第9章 心血管系统疾病 习题（核对PDF 第122–140页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），12 道（原书第 1–12 题） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：动脉粥样硬化（atherosclerosis）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动脉粥样硬化（atherosclerosis）是心血管系统疾病中最常见的疾病，其特征以内膜灶性纤维性增厚及粥样斑块形成为主，主要累及大动脉和中等动脉，使动脉壁增厚、变硬和弹性减退。",
        "动脉粥样硬化（AS）病变以内膜脂质沉积、纤维组织增生和粥样斑块形成为特征，好发于腹主动脉、冠状动脉等大中动脉。原书第9章名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：脂纹（fatty streak）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脂纹（fatty streak）是动脉粥样硬化肉眼可见的最早病变。肉眼观点状或条纹状黄色不隆起或微隆起于内膜的病灶，常见于主动脉后壁及其分支开口处。光镜下，病灶处的内膜下有大量泡沫细胞聚集。",
        "脂纹是动脉粥样硬化最早期的肉眼可见病变，由大量泡沫细胞聚集形成，属可逆性病变。原书第9章名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：纤维斑块（fibrous plaque）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "纤维斑块（fibrous plaque）是动脉粥样硬化的中期病变，由脂纹发展而来。肉眼观为内膜表面见散在不规则隆起的斑块，颜色浅黄、灰黄色或瓷白色。光镜下，病灶表面为一层纤维帽，在纤维帽之下可见数量不等的泡沫细胞、平滑肌细胞（SMC）、细胞外基质和炎症细胞。",
        "纤维斑块由脂纹发展而来，表面为纤维帽，其下为泡沫细胞、SMC、细胞外基质和炎症细胞。原书第9章名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：粥样斑块（atheromatous plaque）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "粥样斑块（atheromatous plaque）亦称粥瘤，是纤维斑块深层组织因营养不良而发生的坏死、崩解，这些崩解物质与脂质混合而成为粥糜样物质，是动脉粥样硬化的典型病变。",
        "粥样斑块是动脉粥样硬化的典型病变，由纤维斑块深层细胞坏死发展而来，其内可见大量坏死崩解产物、胆固醇结晶（针状空隙）和钙盐沉积。原书第9章名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：动脉瘤（aneurysm）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动脉瘤（aneurysm）是指动脉管壁的局限性、持久性异常扩张。动脉瘤最常见于弹性动脉及其主要分支，肌型动脉次之。可累及任何部位的血管，但以主动脉和脑血管最常受累。",
        "动脉瘤不是真性肿瘤，而是动脉壁因局部病变（薄弱或结构破坏）而向外膨出形成的永久性局限性扩张，破裂出血可危及生命。原书第9章名词解释第 5 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：冠状动脉性心脏病（coronary artery heart disease）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "冠状动脉性心脏病（coronary artery heart disease）简称冠心病，是一种最常见的心脏病，是指因冠状动脉狭窄、供血不足而引起的心肌功能障碍和（或）器质性病变，故又称缺血性心肌病。",
        "冠心病（CHD）又称缺血性心脏病（IHD），好发于左冠状动脉前降支，可引起心绞痛、心肌梗死、心肌纤维化和冠状动脉性猝死等。原书第9章名词解释第 6 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：心绞痛（angina pectoris）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心绞痛（angina pectoris）是冠状动脉供血不足和（或）心肌耗氧量骤增致使心肌急性、暂时性缺血、缺氧所引起的临床综合征。表现为胸骨后部位压榨性或紧缩性疼痛感，常放射至左肩和左臂。",
        "心绞痛典型表现为阵发性胸骨后或心前区疼痛、憋闷或压迫感，持续数分钟，休息或服用硝酸酯类药物可缓解。原书第9章名词解释第 7 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：心肌梗死（myocardial infarction）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心肌梗死（myocardial infarction）是由于冠状动脉供血中断，致供血区持续缺血而导致的较大范围的心肌坏死，临床上多有剧烈而持久的胸骨后疼痛，休息及硝酸酯类药物不能完全缓解，伴白细胞增高、发热、血沉加快，血清心肌酶活性增高及进行性心电图变化，可并发心律失常、休克或心力衰竭。",
        "心肌梗死属于贫血性梗死，常发生心脏破裂、室壁瘤、附壁血栓形成、急性心包炎等合并症。原书第9章名词解释第 8 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：心内膜下心肌梗死（subendocardial myocardial infarction）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心内膜下心肌梗死（subendocardial myocardial infarction）病变主要累及心室壁内层1/3的心肌，并波及肉柱和乳头肌，常表现为多发性、小灶性坏死。病变分布常不限于某支冠状动脉的供血范围，而是不规则地分布于左心室四周，严重时病灶扩大融合累及整个心内膜下心肌，引起环状梗死。",
        "心内膜下心肌梗死病灶较小（直径约0.5~1.5cm），与透壁性心肌梗死相对，是心肌梗死的两个主要类型之一。原书第9章名词解释第 9 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：透壁性心肌梗死（transmural myocardial infarction）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "透壁性心肌梗死（transmural myocardial infarction）是典型心肌梗死（MI）的类型，也称为区域性MI。MI的部位与闭塞的冠状动脉分支供血区一致，病灶较大，最大直径在2.5cm以上，累及心室壁全层或未累及全层而深达室壁2/3，此型MI多发生在左冠状动脉前降支的供血区。",
        "透壁性心肌梗死常有相应的一支冠状动脉病变突出，并常附加动脉痉挛或血栓形成。原书第9章名词解释第 10 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-term011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：室壁瘤（ventricular aneurysm）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "室壁瘤（ventricular aneurysm）是由于冠状动脉硬化、闭塞等造成心室的心肌梗死后，心肌全层坏死，坏死的心肌逐渐被纤维瘢痕组织所替代，形成室壁瘤。病变区薄层的心室壁向外膨出，心脏收缩时丧失活动能力或呈现反常运动。室壁瘤常见于左心室。",
        "室壁瘤是心肌梗死的合并症之一，为梗死心肌被纤维瘢痕组织替代后心室壁向外膨出形成，常见于左心室。原书第9章名词解释第 11 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-term012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：原发性高血压（primary hypertension）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "原发性高血压（primary hypertension）又称特发性高血压或高血压病，是我国最常见的心血管疾病，是一种原因未明的、以体循环动脉压升高为主要表现的独立性全身性疾病。多见于中老年人。",
        "原发性高血压诊断标准为成人收缩压≥140mmHg和（或）舒张压≥90mmHg，可分为良性高血压和恶性高血压两类。原书第9章名词解释第 12 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），12 道（A1 型第 1–10 题、A2 型第 41–42 题） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-a1001",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪项不是动脉粥样硬化的危险因素",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "高血压",
      "高盐膳食",
      "高脂血症",
      "糖尿病",
      "吸烟",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "高盐膳食",
        "动脉粥样硬化的危险因素包括高脂血症、高血压、吸烟、糖尿病、遗传等；高盐膳食是高血压的危险因素，不属于动脉粥样硬化的危险因素。原书第9章 A1 型题第 1 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-a1002",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "动脉粥样硬化病变早期最具特征性的细胞成分是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "平滑肌细胞",
      "淋巴细胞",
      "泡沫细胞",
      "中性粒细胞",
      "单核细胞",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "泡沫细胞",
        "泡沫细胞是动脉粥样硬化病变早期最具特征性的细胞成分，由巨噬细胞和平滑肌细胞吞噬脂质后形成。原书第9章 A1 型题第 2 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-a1003",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "动脉粥样硬化形成中的泡沫细胞主要来源于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "红细胞",
      "内皮细胞",
      "巨噬细胞",
      "上皮样细胞",
      "中性粒细胞",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "巨噬细胞",
        "动脉粥样硬化形成中的泡沫细胞主要来源于巨噬细胞（吞噬脂质后形成），也可来源于平滑肌细胞。原书第9章 A1 型题第 3 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-a1004",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "动脉粥样硬化最早期的病理变化是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "粥样斑块",
      "钙化",
      "斑块破裂",
      "脂纹",
      "纤维斑块",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脂纹",
        "脂纹是动脉粥样硬化肉眼可见的最早病变，其后依次发展为纤维斑块、粥样斑块。原书第9章 A1 型题第 4 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-a1005",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "粥样斑块光镜下纤维帽中所不具备的成分是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "钙盐沉积",
      "胆固醇结晶",
      "中性粒细胞",
      "坏死崩解物",
      "肉芽组织",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中性粒细胞",
        "粥样斑块纤维帽之下含有大量不定形的坏死崩解产物、胆固醇结晶（针状空隙）、钙盐沉积，斑块底部和边缘出现肉芽组织，少量淋巴细胞和泡沫细胞；不含中性粒细胞。原书第9章 A1 型题第 5 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-a1006",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "动脉粥样硬化继发性病变中最凶险的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "血栓形成",
      "斑块内出血",
      "血管腔狭窄",
      "动脉瘤形成并破裂出血",
      "斑块破裂",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动脉瘤形成并破裂出血",
        "动脉粥样硬化继发性改变包括斑块内出血、斑块破裂、血栓形成、钙化、动脉瘤形成、血管腔狭窄等，其中动脉瘤形成并破裂出血最为凶险。原书第9章 A1 型题第 6 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-a1007",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一项不属于动脉粥样硬化的继发性改变",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "血栓形成",
      "肉芽组织形成",
      "斑块内出血",
      "斑块破裂",
      "动脉瘤形成",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肉芽组织形成",
        "动脉粥样硬化的继发性改变包括斑块内出血、斑块破裂、血栓形成、钙化、动脉瘤形成、血管腔狭窄；肉芽组织形成是粥样斑块基本病变的一部分（斑块底部和边缘出现肉芽组织），不属于继发性改变。原书第9章 A1 型题第 7 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-a1008",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "动脉粥样硬化最好发的动脉是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胸主动脉",
      "冠状动脉",
      "腹主动脉",
      "升主动脉",
      "颈动脉",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腹主动脉",
        "动脉粥样硬化好发于腹主动脉后壁及其分支开口处，其次为胸主动脉、主动脉弓和升主动脉。原书第9章 A1 型题第 8 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-a1009",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "冠状动脉粥样硬化最常受累的动脉分支是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "右冠状动脉主干",
      "左冠状动脉主干",
      "左冠状动脉左旋支",
      "左冠状动脉前降支",
      "左冠状动脉后降支",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "左冠状动脉前降支",
        "冠状动脉粥样硬化最常发生于左冠状动脉前降支，后依次为右主干、左主干或左旋支、后降支。原书第9章 A1 型题第 9 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-a1010",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列有关心肌梗死的描述中错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "斑块性病变多发生于血管的心壁侧",
      "是心源性猝死的主要原因",
      "多为出血性梗死",
      "多发生于左冠状动脉前降支供血的区域",
      "临床上有剧烈而较持久的胸骨后疼痛，用硝酸酯类制剂或休息后症状不能完全缓解",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多为出血性梗死",
        "心肌梗死属于贫血性梗死（白色梗死），而非出血性梗死，故“多为出血性梗死”的描述错误。原书第9章 A1 型题第 10 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-a1011",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "64岁的老年男性，近来在轻微运动时感到胸痛，数分钟休息后可获得缓解。这一情况持续了数月，疼痛发作的频率和持续时间都没有加重。此患者的诊断应为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "变异型心绞痛",
      "老年性支气管哮喘",
      "稳定型心绞痛",
      "不典型心绞痛",
      "不稳定型心绞痛",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "稳定型心绞痛",
        "患者胸痛在轻微运动时出现、休息数分钟可缓解，发作频率和持续时间数月无加重，符合稳定型（劳累性）心绞痛的特点。原书第9章 A2 型题第 41 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-a1012",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "患者近年来劳累时，心前区经常疼痛，并向左肩部放射，因病情不缓解，住院治疗。心电图显示系统性心肌缺血，入院后逐渐加重，出现肝大，下肢水肿，在治疗过程中，夜间突然死亡。该患者死亡原因最可能是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "风湿性心脏病合并心衰",
      "冠心病合并心肌梗死",
      "心肌病合并心衰",
      "心肌硬化合并心衰",
      "高血压心脏病合并心衰",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "冠心病合并心肌梗死",
        "患者有劳累性心绞痛病史，心电图示心肌缺血，病情逐渐加重并出现心力衰竭表现，夜间突然死亡，最可能为冠心病基础上发生急性心肌梗死导致心源性猝死。原书第9章 A2 型题第 42 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 判断题 + 问答题（short-answer），22 道（判断题第 1–14 题在前、问答题第 1–8 题在后） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short001",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt:
      "判断题：动脉粥样硬化主要累及中小动脉，基本病变包括动脉内膜的脂质沉积、内膜灶状纤维化、粥样斑块形成。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。动脉粥样硬化主要累及大动脉和中等动脉（如主动脉、冠状动脉等），而非中小动脉。",
        "动脉粥样硬化以内膜灶性纤维性增厚及粥样斑块形成为主，主要累及大动脉和中等动脉，使动脉壁增厚、变硬和弹性减退。原书第9章判断题第 1 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short002",
    order: 26,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：细动脉硬化表现细小动脉的玻璃样变，常见于高血压病和糖尿病。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。细动脉硬化表现为细小动脉的玻璃样变，常见于高血压病和糖尿病。",
        "细动脉玻璃样变（细动脉硬化）是良性高血压最主要的病变特征，也可见于糖尿病等疾病。原书第9章判断题第 2 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short003",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：动脉粥样硬化与动脉硬化属于同一概念。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。动脉粥样硬化与动脉硬化不是同一概念，动脉硬化是更广义的概念。",
        "动脉硬化泛指动脉壁增厚变硬、失去弹性的一类疾病，包括动脉粥样硬化、细动脉硬化、动脉中层钙化等类型；动脉粥样硬化只是其中最常见的一种。原书第9章判断题第 3 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short004",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：动脉粥样硬化症易发生在动脉分支开口处。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。动脉粥样硬化症易发生在动脉分支开口处。",
        "动脉分支开口处血流动力学改变明显，易发生内膜损伤和脂质沉积，是动脉粥样硬化的好发部位。原书第9章判断题第 4 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short005",
    order: 29,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：动脉粥样硬化危险因素包括高脂血症、高血压、吸烟、遗传等。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。动脉粥样硬化的危险因素包括高脂血症、高血压、吸烟、遗传等。",
        "除上述因素外，糖尿病、肥胖、缺乏运动、年龄等也是动脉粥样硬化的危险因素。原书第9章判断题第 5 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short006",
    order: 30,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt:
      "判断题：主动脉粥样硬化病变好发于主动脉的后壁及其分支开口处，以腹主动脉病变最为严重。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。主动脉粥样硬化好发于主动脉后壁及其分支开口处，以腹主动脉病变最为严重。",
        "主动脉粥样硬化病变严重者可形成动脉瘤，大出血是最严重的并发症。原书第9章判断题第 6 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short007",
    order: 31,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：脑动脉粥样硬化常于Willis环处形成动脉瘤，可破裂引起脑出血。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。脑动脉粥样硬化常于Willis环处形成动脉瘤，可破裂引起脑出血。",
        "脑动脉粥样硬化常见于基底动脉、大脑中动脉和Willis动脉环，动脉瘤多见于Willis环部，血压突然升高时可致小动脉瘤破裂引起脑出血。原书第9章判断题第 7 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short008",
    order: 32,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt:
      "判断题：冠状动脉粥样硬化最常发生于左冠状动脉前降支，后依次为右主干、左主干或左旋支、后降支。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。冠状动脉粥样硬化最常发生于左冠状动脉前降支，后依次为右主干、左主干或左旋支、后降支。",
        "左冠状动脉前降支是冠心病心肌梗死最常累及的供血动脉。原书第9章判断题第 8 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short009",
    order: 33,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：心肌梗死合并症包括心力衰竭、心脏破裂、室壁瘤、附壁血栓形成等。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。心肌梗死的合并症包括心力衰竭、心脏破裂、室壁瘤、附壁血栓形成等。",
        "心肌梗死常见合并症还有心源性休克、急性心包炎、心律失常等。原书第9章判断题第 9 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short010",
    order: 34,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：心肌梗死形态，一般在梗死后6小时后才能肉眼可辨。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。心肌梗死的形态改变一般在梗死后6小时后才能肉眼辨认。",
        "心肌梗死后早期（4~6小时内）肉眼无明显改变，6小时后梗死区逐渐出现肉眼可辨的苍白、水肿等改变。原书第9章判断题第 10 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short011",
    order: 35,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：动脉粥样硬化可以累及肾动脉，造成固缩肾。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。动脉粥样硬化可以累及肾动脉，造成肾脏凹陷性大瘢痕，称动脉粥样硬化性固缩肾。",
        "肾动脉粥样硬化主要位于肾动脉开口处和主干近侧端，常引起顽固性高血压和肾脏凹陷性大瘢痕。原书第9章判断题第 11 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short012",
    order: 36,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：脑动脉粥样硬化晚期，脑组织可因长期供血不足而发生萎缩。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。脑动脉粥样硬化晚期，脑组织可因长期供血不足而发生萎缩。",
        "由于脑动脉管腔狭窄，脑组织长期供血不足而发生脑萎缩，严重者智力减退甚至痴呆。原书第9章判断题第 12 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short013",
    order: 37,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：高血压主要造成细动脉硬化。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对。高血压主要造成细动脉硬化。",
        "细动脉硬化（细动脉玻璃样变）是良性高血压最主要的病变特征，管壁增厚、变硬、管腔狭窄甚至闭塞。原书第9章判断题第 13 题，参考答案键号 √。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short014",
    order: 38,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题：缓进性高血压病基本病变是全身细小动脉的痉挛及纤维素样坏死。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错。缓进性（良性）高血压病的基本病变是全身细小动脉的玻璃样变（细动脉硬化），而非纤维素样坏死。",
        "细小动脉纤维素样坏死是恶性高血压的特征性病变之一（坏死性细动脉炎）；良性高血压的基本病变为细动脉玻璃样变。原书第9章判断题第 14 题，参考答案键号 ×。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short015",
    order: 39,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述动脉粥样硬化的基本病变及继发性改变。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动脉粥样硬化的基本病变包括：①脂纹：AS肉眼可见的最早病变。肉眼观为点状或条纹状黄色不隆起或微隆起于内膜的病灶，常见于主动脉后壁及其分支开口处。光镜下，病灶处的内膜下有大量泡沫细胞聚集。泡沫细胞体积大，圆形或椭圆形，胞质内含有大量小空泡。②纤维斑块：由脂纹发展而来。肉眼观，内膜表面见散在不规则隆起的斑块，颜色浅黄、灰黄色或瓷白色。光镜下，病灶表面为一层纤维帽，在纤维帽之下可见数量不等的泡沫细胞、SMC、细胞外基质和炎症细胞。③粥样斑块：由纤维斑块深层细胞的坏死发展而来，是AS的典型病变。肉眼观，内膜面可见明显的灰黄色斑块。切面，斑块既向内膜表面隆起又向深部压迫中膜。斑块的管腔面为白色质硬组织，深部为黄色或黄白色质软的粥样物质。光镜下，在纤维帽之下含有大量不定形的坏死崩解产物、胆固醇结晶（针状空隙）、钙盐沉积，斑块底部和边缘出现肉芽组织，少量淋巴细胞和泡沫细胞，中膜因斑块压迫、SMC萎缩、弹力纤维破坏而变薄。继发性改变：①斑块内出血；②斑块破裂和溃疡形成；③血栓形成；④钙化；⑤动脉瘤形成。",
        "原书第9章问答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short016",
    order: 40,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：试述冠状动脉粥样硬化性心脏病的主要类型及病变特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "冠状动脉粥样硬化性心脏病的主要类型包括心绞痛、心肌梗死、心肌纤维化及冠状动脉性猝死。（1）心绞痛是由于心肌急剧的、暂时性缺血、缺氧所造成的一种常见的临床综合征。临床表现为阵发性心前区疼痛或压迫感，可放射至心前区、左上肢，持续数分钟，用硝酸酯制剂或稍休息后症状可缓解。分为：①稳定性心绞痛；②不稳定性心绞痛；③变异性心绞痛。（2）心肌梗死是由于冠状动脉供血中断，致供血区持续缺血而导致的较大范围的心肌坏死。临床上有剧烈而较持久的胸骨后疼痛，用硝酸酯类制剂或休息后症状不能完全缓解，可并发心律失常、休克或心力衰竭。（3）心肌纤维化是由于中至重度的冠状动脉狭窄引起的心肌纤维持续性和（或）反复加重的缺血、缺氧所产生的结果，是逐渐发展为心力衰竭的慢性缺血性心脏病。（4）冠状动脉性猝死是心源性猝死中最常见的一种，多发生在冠状动脉粥样硬化的基础上，由于冠状动脉中至重度粥样硬化、斑块内出血，致冠状动脉狭窄或微循环血栓致栓塞，导致心肌急性缺血，冠状动脉血流的突然中断，引起心室颤动等严重心律失常。",
        "原书第9章问答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short017",
    order: 41,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述心肌梗死的好发部位、类型及其常见合并症。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心肌梗死的好发部位：最常见的部位为左冠状动脉前降支的供血区，其中以左心室前壁、心尖部及室间隔前2/3及前内乳头肌多见，约占全部MI的50%。约25%的MI发生于右冠状动脉供血区的左心室后壁、室间隔后1/3及右心室。此外，还见于左心室后壁，相当于左冠状动脉左旋支的供血区域。右心室和心房发生MI者较为少见。根据MI的范围和深度可分为心内膜下MI和透壁性MI两个主要类型。（1）心内膜下MI：病变主要累及心室壁内层1/3的心肌，并波及肉柱和乳头肌，常表现为多发性、小灶性坏死，直径约0.5~1.5cm。病变分布常不限于某支冠状动脉的供血范围，而是不规则地分布于左心室四周，严重时病灶扩大融合累及整个心内膜下心肌，引起环状梗死。（2）透壁性MI：是典型MI的类型，也称为区域性MI。MI的部位与闭塞的冠状动脉分支供血区一致，病灶较大，最大直径在2.5cm以上，累及心室壁全层或未累及全层而深达室壁2/3，此型MI多发生在左冠状动脉前降支的供血区，透壁性MI常有相应的一支冠状动脉病变突出，并常附加动脉痉挛或血栓形成。心肌梗死的常见合并症：①心功能不全；②心源性休克；③心脏破裂；④室壁瘤；⑤附壁血栓；⑥急性心包炎；⑦心律失常。",
        "原书第9章问答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short018",
    order: 42,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：试比较高血压引起的脑病变与动脉粥样硬化引起的脑病变。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "高血压病引起的脑病变包括：①脑水肿或高血压脑病，由于脑小动脉硬化和痉挛，局部组织缺血，毛细血管通透性增加，发生脑水肿，严重时出现高血压危象。②脑软化，是细小动脉病变造成的供血区域脑组织缺血的结果。供血区脑组织缺血而发生多数小坏死灶，即微梗死灶。严重病例细小动脉壁可发生纤维素样坏死，并发血栓形成和微动脉瘤。③脑出血，是高血压最严重的、往往是致命的并发症。脑出血多为大出血，常发生于基底节、内囊，其次大脑白质、脑桥和小脑。当出血范围扩大时，可破入侧脑室。出血导致颅内压增高，并发脑疝，可出现对侧肢体瘫痪、失语、昏迷，甚至死亡。脑动脉粥样硬化最常见于颈内动脉起始部、基底动脉、大脑中动脉和Willis环。纤维斑块和粥样斑块常导致管腔狭窄，甚至闭塞。由于脑动脉管腔狭窄，脑组织长期供血不足而发生脑萎缩，严重脑萎缩者智力减退，甚至痴呆。斑块处常继发血栓形成致管腔阻塞，引起脑梗死（脑软化）。脑AS病变常可形成动脉瘤，动脉瘤多见于Willis环部，患者血压突然升高时，可致小动脉瘤破裂引起脑出血。",
        "原书第9章问答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short019",
    order: 43,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：试述良性高血压的心脏病变特征。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "良性高血压的心脏病变主要为左心室肥大，心脏重量增加，可达400g以上或更重。肉眼观，左心室壁增厚，可达1.5~2.0cm（正常≤1.0cm）。左心室乳头肌和肉柱明显增粗，心腔不扩张，相对缩小，称为向心性肥大。光镜下，心肌细胞增粗、变长，有较多分支。心肌细胞核肥大，呈圆形或椭圆形，核深染。晚期当左心室代偿失调，心肌收缩力降低时，逐渐出现心腔扩张，称离心性肥大，严重者可发生心力衰竭。",
        "原书第9章问答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short020",
    order: 44,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：试述风湿病的基本病理变化。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "风湿病主要病变发生于结缔组织的胶原纤维，全身各器官均可受累，但以心脏、血管和浆膜等处的病变最为明显。风湿病的特征性病理变化是风湿小体，即Aschoff小体，对诊断风湿病有意义。该病的发展过程较长，可分为三期：（1）变质渗出期：是风湿病的早期改变。在心脏、浆膜、关节、皮肤等病变部位表现为结缔组织基质的黏液样变性和胶原纤维素样坏死。同时在浆液纤维素渗出过程中，有少量淋巴细胞、浆细胞、单核细胞浸润。此期病变可持续1个月。（2）增生期或肉芽肿期：此期病变特点是在变质渗出的基础之上，在心肌间质、心内膜下和皮下结缔组织中，可见具有特征性的肉芽肿性病变，称风湿小体或Aschoff小体。风湿小体由聚集于纤维素样坏死灶内的成群风湿细胞及少量的淋巴细胞和浆细胞构成。风湿细胞由增生的巨噬细胞吞噬纤维素样坏死物质后转变而来。风湿细胞也称为阿绍夫细胞（Aschoff cell），在心肌间质内的Aschoff细胞多位于小血管旁，细胞体积大，圆形，胞质丰富，略嗜碱性。核大，圆形或椭圆形，核膜清晰，染色质集中于中央，核的横切面似枭眼状，纵切面呈毛虫状，有时可见多个核的Aschoff细胞。此期病变可持续2~3个月。（3）纤维化期或硬化期：Aschoff小体中的坏死组织逐渐被吸收，风湿细胞转变为成纤维细胞，使风湿小体逐渐纤维化，最后形成梭形小瘢痕。此期病变可持续2~3个月。上述整个病程在4~6个月。由于风湿病病变具有反复发作的性质，在受累的器官和组织中常可见到新旧病变同时并存的现象。病变持续反复进展，纤维化的瘢痕可不断形成，破坏组织结构，影响器官功能。",
        "原书第9章问答题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short021",
    order: 45,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：风湿病引起的心脏病变有哪些？各有何特征？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "风湿病引起的心脏病变可以表现为风湿性心内膜炎、风湿性心肌炎和风湿性心外膜炎。若病变累及心脏全层组织，则称风湿性全心炎或风湿性心脏炎。（1）风湿性心内膜炎：病变主要侵犯心瓣膜，其中二尖瓣最常受累，其次为二尖瓣和主动脉瓣同时受累。主动脉瓣、三尖瓣和肺动脉瓣极少受累。病变初期，受累瓣膜肿胀，瓣膜内出现黏液样变性和纤维素样坏死，浆液渗出和炎细胞浸润。病变瓣膜表面，尤以瓣膜闭锁缘上形成单行排列、直径为1~2mm的疣状赘生物。这些赘生物呈灰白色半透明状，附着牢固，不易脱落。赘生物多时，可呈片状累及腱索及邻近内膜。光镜下，赘生物由血小板和纤维蛋白构成，伴小灶状的纤维素样坏死。其周围可出现少量的Aschoff细胞。病变后期，由于病变反复发作，引起纤维组织增生，导致瓣膜增厚、变硬、卷曲、短缩、瓣膜间互相粘连、腱索增粗、短缩，最后形成慢性心瓣膜病。当炎症病变累及房、室内膜时，引起内膜灶状增厚及附壁血栓形成。由于病变所致瓣膜口狭窄或关闭不全，受血流反流冲击较重，引起内膜灶状增厚，称为McCallum斑。（2）风湿性心肌炎：病变主要累及心肌间质结缔组织，常表现为灶状间质性心肌炎，间质水肿，在间质血管附近可见Aschoff小体和少量的淋巴细胞浸润。病变反复发作，Aschoff小体机化形成小瘢痕。病变常见于左心室、室间隔、左心房及左心耳等处。（3）风湿性心外膜炎：病变主要累及心外膜脏层，呈浆液性或纤维素性炎症。当大量浆液渗出为主时，形成心外膜腔积液。当渗出以纤维素为主时，覆盖于心外膜表面的纤维素可因心脏的不停搏动和牵拉而形成绒毛状，称为绒毛心。渗出的大量纤维素如不能被溶解吸收，则发生机化，使心外膜脏层和壁层互相粘连形成缩窄性心外膜炎。",
        "原书第9章问答题第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pathology-pathology-ch09-cardiovascular-diseases-short022",
    order: 46,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：请比较急性与亚急性感染性心内膜炎的异同点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "急性与亚急性感染性心内膜炎的异同点（表9-2）：①临床过程：急性为数周，亚急性为数月。②病原体：急性为毒力较强的化脓菌，亚急性为毒力较弱的草绿色链球菌。③感染诱因：急性为脓毒血症、败血症，亚急性为菌血症。④受累瓣膜：急性多累及正常瓣膜，多为二尖瓣、主动脉瓣，常见穿孔；亚急性多累及原有病变的瓣膜，多为二尖瓣、主动脉瓣，极少穿孔。⑤赘生物：急性者较大、质地松软、灰黄或浅绿色，含大量细菌及脓性渗出物等；亚急性者较小、息肉状或菜花状、质松脆、易破碎脱落，含少量细菌及血小板、纤维蛋白等。⑥合并症：急性为感染性梗死和脓肿、急性心瓣膜功能不全；亚急性为无菌性梗死、瓣膜口狭窄或关闭不全、变态反应。",
        "原书第9章问答题第 8 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 配伍题（bGroups），0 组（本书无 B1 型） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
