import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 生理学 学习指导与习题集（第3版）— 第九章 感觉器官 题库提取（等比取样）
 * 来源：《生理学学习指导与习题集》第3版（人民卫生出版社，本章作者：邢国刚、邸阳、王爱梅）
 *
 * == 统计报告（本文件题量 = 41 道独立记分题）==
 * - 名词解释：6 题
 * - A1/A2/X 型选择题（统一映射为 a1-single 单选）：26 题（含 A2 病例题 7 题、X 型多选按规约映射 4 题）
 * - 简答题：5 题
 * - B1 共用备选答案配伍题：2 组、共 4 个成员
 * - case 独立题：0 题（本章 A2 病例型均为选择题，已按项目规约映射为 a1-single，无独立非选择型病例自由题）
 * - 独立记分题合计：41 题（含 B1 组成员）
 * - 缺失答案：0 题；无法可靠提取：0 题
 * - 说明：本章原书依次含名词解释 14、A1 型选择 55、A2 型病例选择 16、X 型多选 13、
 *   B 型 5 组（共 11 成员）、简答 12、思考题 3；本文件按 41 道预算等比取材并改写。
 *   各题型按原书结构匀衡取材（第一节感觉概述/躯体内脏感觉/视觉与第二节听觉/平衡/嗅觉/味觉兼顾）。
 *   X 型多选按项目规约映射为 a1-single（题干改写成单句式并在 promptSource.note 中标为 xMapNote，
 *   单选其中一个正确项或改问"错误的是/不会出现/不属于"后选其唯一正确项）。
 *   A2 病例型亦映射为 a1-single。OCR 错字已按医学语义恢复（如"凾/厚度"→度、"视網膜"→视网膜、
 *   "肋膜"→鼓膜、"内淋巴"等），数值与单位（10×10⁹/L、39℃、50mmHg、3000Hz、40~70dB、1°/s²~3°/s²、
 *   +80mV、6m、1.5mm、4.5μm、380~760nm、20~20000Hz 等）保留原值，未捏造。
 *   各选择题可选项行（题号相邻）经人工重建为 A–E 逻辑顺序后填入 choices。
 * 注意：本文件覆盖 PDF 第213–238页（第九章 感觉器官，第一节 + 第二节）。
 *
 * 解析内容位于 answer.content 数组的第二个元素。
 */

const topic = "physiology-ch9-sensory-organs";
const locatorBase =
  "《生理学学习指导与习题集》第3版 第九章 感觉器官 复习思考题 习题（PDF 第213–238页）";
const promptNote =
  "题干改写；原题来自用户提供的题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原书为X型多选题，按项目规约映射为a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据上传题集整理并改写，尚未与权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），6 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-physiology-ch9-sensory-organs-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：适宜刺激（adequate stimulus）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "适宜刺激",
        "指某种感受器对之最为敏感的某种特异能量形式的刺激，如可见光是视网膜感光细胞的适宜刺激。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：牵涉痛（referred pain）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "牵涉痛",
        "指由某些内脏疾病引起的某远隔体表部位疼痛或痛觉过敏的现象，如发生心绞痛时常感到心前区、左肩和左上臂疼痛。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：三色学说（trichromatic theory）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "三色学说",
        "一种用以解释人眼色觉功能的学说：视网膜中存在分别含红、绿、蓝光敏色素的三种视锥细胞，当某一波长的光线作用于视网膜时，可依一定比例使三种不同的视锥细胞发生兴奋，经中枢分析后产生某一种颜色的感觉。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：暗适应（dark adaptation）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "暗适应",
        "指人长时间处于明亮环境中突然进入暗处时，最初看不清任何东西，经一定时间后视觉敏感度才逐渐增高而看清暗处物体的现象，是人眼在暗处对光敏感度逐渐提高的过程。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：听阈（hearing threshold）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "听阈",
        "对于每一种频率的声波，人耳都有一个刚能引起听觉的最小强度，称为听阈；听阈以上继续增加强度直至引起鼓膜疼痛的强度限度，此最大可听阈与听阈之间构成人耳的听域。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：前庭自主神经反应（vestibular autonomic reaction）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前庭自主神经反应",
        "当前庭器官受到过强或过久的刺激时，可通过前庭神经核与网状结构的联系而引起自主神经功能失调，导致皮肤苍白、恶心、呕吐、出汗、心率加快、血压下降、呼吸加快以及唾液分泌增多等现象。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2/X 型选择题（统一映射为 a1-single），26 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-physiology-ch9-sensory-organs-a1001",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列「感受器或感觉器官—适宜刺激」的配对中，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "内耳耳蜗-声波",
      "皮肤环层小体-机械压迫",
      "中枢化学感受器-PCO2",
      "视网膜感光细胞-可见光",
      "肌梭-骨骼肌长度变化",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中枢化学感受器-PCO2",
        "中枢化学感受器的适宜刺激是脑脊液中的H+（CO2经血-脑屏障溶于水转化为H+而间接起作用），故以「PCO2」作为其最敏感特异刺激的配对错误；其余配对均为正常对应关系。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1002",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "特异神经能量定律的主要内容是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "感受器对刺激能量转换的规律",
      "感觉通路监测刺激持续时间的机制",
      "感觉通路识别不同感觉类型的原理",
      "神经系统中涉及能量代谢的问题",
      "感觉通路对刺激强度的编码特性",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "感觉通路识别不同感觉类型的原理",
        "特异神经能量定律阐明：不同类型感觉的引起，除取决于刺激类型及其相应感受器外，还取决于传入冲动经过的专用通路及其最终到达的大脑皮层特定部位，即感觉通路识别不同感觉类型的原理。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1003",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "感觉通路中存在侧向抑制的主要意义是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "起反馈控制作用",
      "使同类神经元群同步活动",
      "扩大作用的空间范围",
      "增强感觉分辨能力",
      "协调不同中枢的活动",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "增强感觉分辨能力",
        "侧向抑制指中心区的初级传入纤维兴奋次级神经元的同时，通过侧支抑制周边区次级神经元活动，从而加大刺激中心区与周边区之间的信号差距，增强感觉系统的分辨能力。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1004",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "内脏痛最主要的特点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "伴有不愉快情绪",
      "定位不准确",
      "一般表现为锐痛",
      "伴有自主神经反应",
      "潜伏期和持续时间长",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "定位不准确",
        "内脏痛最主要的特点是定位不准确，常不能明确指出疼痛所在部位；发生缓慢、持续时间较长、伴不愉快情绪和自主神经反应亦为内脏痛特点，但以定位不准确最为突出。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1005",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在正常人眼，入射光线的折射主要发生在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "晶状体前表面",
      "角膜前表面",
      "玻璃体前表面",
      "角膜后表面",
      "晶状体后表面",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "角膜前表面",
        "人眼的折光系统由角膜、房水、晶状体和玻璃体组成，入射光线折射主要发生在角膜前表面，因为空气与角膜之间折射率差别最大，折光力也最强。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1006",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "注视6m以内的近物时，人眼所进行的最重要的调节是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "眼轴会聚",
      "角膜曲率增加",
      "晶状体变凸",
      "瞳孔近反射",
      "瞳孔对光反射",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "晶状体变凸",
        "视6m以内近物时眼进行近反射，包括晶状体变凸（最重要）、瞳孔缩小和视轴会聚。其中晶状体变凸通过睫状体肌收缩、悬韧带松弛使晶状体前凸，眼折光力增大，使视网膜像前移而变清晰。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1007",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "视近物和远物均需眼进行调节的折光异常是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["复视", "远视", "近视", "斜视", "散光"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "远视",
        "远视眼眼球前后径过短或折光能力过弱，平行光线聚焦于视网膜后方，故视远物即需调节，视近物时调节程度更大、易疲劳（近点移远）；近视与散光则不具备此特点。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1008",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "视网膜上形成生理盲点的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "黄斑外环区",
      "视神经乳头",
      "中央凹外20°处",
      "视网膜锯齿缘",
      "黄斑中央凹",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "视神经乳头",
        "神经节细胞轴突在视网膜上汇集成视神经并经视神经乳头穿出眼球，该处无感光细胞，故成为生理盲点；但人类因双眼视觉的视野补偿作用而不会感觉盲点存在。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1009",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "人眼暗适应过程的实质是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "视野的增大",
      "光感受器的适应",
      "视色素合成增加",
      "视力的提高",
      "色素上皮突起缩回",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "视色素合成增加",
        "人从明处突然进入暗处时，视色素尤其是对光敏感度较高的视杆色素在暗处合成增加，使视觉敏感度逐渐提高而能在暗处看清物体，此为暗适应过程的实质。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1010",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪种情况不属于人眼屈光不正",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["散光", "远视", "老视", "斜视", "近视"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "老视",
        "屈光不正指眼的折光异常，包括近视、远视和散光；老视是老年人晶状体弹性减退、调节能力下降所致，是一种调节功能减退而非屈光不正。原书为X型多选，此处按规约映射为单选并取其正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1011",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列「内脏疾患—体表牵涉痛部位」的配对中，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "左上腹和肩胛间-胃溃疡",
      "腹股沟区-输尿管结石",
      "右肩区-胆囊炎、胆石症",
      "左肩和左上臂-心绞痛",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腹股沟区-输尿管结石",
        "腹股沟区牵涉痛见于阑尾炎，输尿管结石则多放射至睾丸等部位，故「腹股沟区-输尿管结石」配对错误；其余三个配对均为正确对应。原书为X型多选，此处改问错误配对并映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1012",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "进行眼科检查时用后马托品滴眼后，下列哪种结果不会出现",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["视近物模糊", "青光眼病情加重", "瞳孔扩大", "产生复视"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "产生复视",
        "后马托品为M受体拮抗剂，可阻断虹膜环行肌和睫状体肌的收缩，引起瞳孔扩大、晶状体不能变凸而视近物模糊，并因瞳孔扩大使前房角变窄而加重青光眼病情；它不会产生复视。原书为X型多选，此处取不会出现的表现映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1013",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪种不属于双眼视觉的优点",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["弥补单眼视觉中的盲区", "产生立体视觉", "扩大视野", "增强分辨能力"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "增强分辨能力",
        "双眼视觉的优点是可弥补单眼视野中的盲区缺损、扩大视野并产生立体视觉，「增强分辨能力」不在本题所列双眼视觉优点之列。原书为X型多选，此处取不属于的优点映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1014",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "一位65岁女性，因进食后右上腹胀痛并向后背部放射、伴恶心2周来诊。查体右上腹部有压痛，无腹肌紧张和反跳痛；腹部B超提示胰腺肿物。该患者后背部疼痛最可能的原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "后背脊柱痛",
      "胰腺肿瘤压迫痛",
      "胰腺炎症痛",
      "胰腺病变的牵涉痛",
      "后背炎症痛",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胰腺病变的牵涉痛",
        "内脏疾病往往引起远隔体表部位的牵涉痛，胰腺癌常发生肩背部牵涉痛，故该患者后背部疼痛最可能是胰腺病变引起的牵涉痛，而不是肿瘤直接压迫或局部炎症所致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1015",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "一位26岁男性，因发热、腹痛并加剧就诊，腹痛开始时位于上腹部和脐周，数小时后转移至右下腹部，查体右下腹有压痛、反跳痛、伴轻度腹壁肌紧张，体温39℃，白细胞计数超过10×10⁹/L。该患者所患疾病应诊断为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "急性胆囊炎",
      "十二指肠溃疡穿孔",
      "心绞痛发作",
      "急性阑尾炎",
      "输尿管结石发作",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "急性阑尾炎",
        "患者起病于上腹部和脐周后转移至右下腹，伴右下腹压痛、反跳痛及发热、白细胞升高，为典型急性阑尾炎表现；结合年龄及心电图等可排除心绞痛、十二指肠溃疡穿孔、急性胆囊炎和输尿管结石。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1016",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "一位55岁女性，因情绪激动而突感右眼胀痛和同侧头痛，剧烈难忍，并出现虹视（看灯如见彩色光晕）和视蒙（视物雾蒙蒙）、恶心、呕吐而来诊，眼科检查示眼部充血、角膜水肿、瞳孔散大、前房变浅、眼压超过50mmHg。该患者应诊断为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "急性结膜炎",
      "青光眼",
      "偏头痛",
      "远视眼",
      "急性虹膜睫状体炎",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "青光眼",
        "患者眼压明显升高（超过50mmHg），伴虹视、视蒙、眼胀痛、恶心呕吐等症状，结合性别年龄可确诊为青光眼；其余选项均无眼压升高，症状亦不同。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1017",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "一位40岁女性，患慢性腹泻，影响营养物质吸收，粪便中检出大量脂肪，患者在黎明和黄昏时视物不清并逐渐发展为夜盲。该患者暗视觉功能减退的主要原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "缺乏维生素A",
      "缺乏蛋白质",
      "缺乏脂肪",
      "缺乏维生素B",
      "缺乏维生素C",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "缺乏维生素A",
        "脂肪吸收不良可影响脂溶性维生素（包括维生素A）的吸收；维生素A长期摄入不足时视紫红质中的视黄醛得不到补充，故引起夜盲症，暗视觉功能减退。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1018",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "一位67岁女性，一觉醒来发现视力明显下降，眼科检查发现两眼右半视野大部分缺失，但右黄斑区视野和两眼左半视野保留。可推测其视觉通路受损的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "左侧视束",
      "右侧视神经",
      "左侧视皮层",
      "视交叉",
      "左外侧膝状体",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "左侧视皮层",
        "左侧视皮层（及视放射后部）受损引起双眼右侧同向偏盲而黄斑区保留，与该患者两眼右半视野缺失、黄斑保留的表现相符，故受损部位为左侧视皮层。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1019",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "正常情况下，声波传入内耳的主要途径是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "外耳道-鼓膜-听骨链-圆窗膜-耳蜗",
      "颅骨-耳蜗内淋巴",
      "外耳道-鼓膜-听骨链-卵圆窗膜-耳蜗",
      "外耳道-鼓膜-鼓室内空气-圆窗膜-耳蜗",
      "外耳道-鼓膜-听骨链-卵圆窗膜-圆窗膜-耳蜗",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "外耳道-鼓膜-听骨链-卵圆窗膜-耳蜗",
        "气传导是正常情况声波传导的主要途径，即声波经外耳道引起鼓膜振动，再经听骨链和卵圆窗膜传入耳蜗；经圆窗或鼓室空气的途径在正常情况下作用很小。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1020",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "根据行波理论，声波频率越高，基底膜出现最大振幅的部位越靠近",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "耳蜗顶部",
      "基底膜顶部",
      "基底膜中间部",
      "基底膜底部",
      "基底膜最宽部位",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "基底膜底部",
        "声波频率越高，行波传播越近，基底膜最大振幅出现部位越靠近蜗底；频率越低，行波传播越远，最大振幅部位越靠近蜗顶。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1021",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "耳蜗毛细胞去极化感受器电位的形成机制是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["Ca2+内流", "Cl-内流", "K+内流", "Na+内流", "Mg2+内流"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "K+内流",
        "声波使基底膜振动并在盖膜与基底膜间产生剪切运动，毛细胞纤毛弯曲使机械门控通道开放，因内淋巴中K+浓度较高（耳蜗内电位约+80mV），引起K+内流而产生去极化感受器电位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1022",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "人体向左旋转刚开始时，关于水平方向眼震颤的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "慢动相向左，快动相向左",
      "慢动相向右，快动相向右",
      "慢动相向左，快动相向右",
      "慢动相向右，快动相向左",
      "慢动相向颞侧，快动相向鼻侧",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "慢动相向右，快动相向左",
        "身体向左旋转开始时，水平性眼震颤的慢动相向右、快动相向左（眼震颤的快动相方向与旋转方向一致）。眼震颤是人类前庭反应中最特殊的一种，含慢动相和快动相两个时相。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1023",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "「如入芝兰之室，久而不闻其香；入鲍鱼之肆，久而不闻其臭。」从生理学角度，这一现象说明",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "人的嗅觉对香、臭的嗅敏度较低",
      "过度刺激导致嗅上皮损伤",
      "人的嗅觉中枢不发达",
      "某些嗅质对嗅觉中枢有抑制作用",
      "人的嗅觉适应较快",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "人的嗅觉适应较快",
        "长时间持续接触某一种气味后，人对其感受逐渐减弱乃至完全不觉，这是嗅觉适应较快（嗅觉的一般性质之一）的典型表现，而非嗅上皮损伤或嗅敏度低。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1024",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "人类分辨的味觉中，下列哪种不属于基本味觉",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["苦", "甜", "辣", "酸", "咸"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "辣",
        "人类味觉由五种基本味觉（咸、酸、甜、苦和鲜）组合而成，「辣」实际上多为痛觉及温度觉等复合感受，不属于基本味觉。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1025",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "贝多芬耳聋后，为「听」声音而用牙咬住一根木棒的一端，把另一端插入钢琴的共鸣箱内。他能借此听到声音的原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "牙可以增幅声音",
      "液体传导",
      "气传导",
      "骨传导",
      "牙促进声波传导",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骨传导",
        "贝多芬利用的是骨传导：声波经颌骨和颅骨传入耳蜗。传音性耳聋时气传导明显受损，而骨传导不受影响甚至相对增强，故可借此「听」到声音。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-a1026",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "一位27岁职业乐队鼓手，近来听力下降，排练时听不清他人说话和音乐节奏。林纳试验两耳气传导时间均长于骨传导，韦伯试验不偏向任一侧，听力测试示其丧失3000Hz以上频率、40~70dB的听力。其耳聋最可能的原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "听神经病变",
      "听骨链损伤",
      "鼓膜病变",
      "耳蜗毛细胞损伤",
      "听皮层损伤",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "耳蜗毛细胞损伤",
        "林纳试验气导时间大于骨导且韦伯试验无偏向，提示为双侧感音性（耳蜗性）耳聋；长期高分贝噪声使基底膜相应区域毛细胞纤毛过度偏转而受损，与职业鼓手的高频（3000Hz以上）听力丧失相符。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];
/** 简答题（short-answer），5 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-physiology-ch9-sensory-organs-short001",
    order: 33,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述目前所知的感受器和感觉通路对感觉信号的编码机制。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "感受器与感觉通路的编码机制",
        "编码主要涉及刺激的类型、部位、强度和持续时间等属性。①刺激类型：各感受器有各自的适宜刺激，是识别刺激类型的基础，同时还取决于传入冲动经过的专用通路及其最终到达的大脑皮层特定部位（特异神经能量定律）；②刺激部位：与感受器和感觉通路具有不同的感受野有关；③刺激强度：通过改变感受器电位的大小（进而影响相应传入神经动作电位频率）以及募集到感受野中的感受器数量来实现，募集增多时更多神经纤维共同向高位中枢传输同一性质的刺激信息，使感觉得到增强；④刺激持续时间：除刺激本身是否持续存在外，还受感受器适应的影响。此外，感觉通路普遍存在侧向抑制，其意义在于增强感觉系统的分辨能力。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-short002",
    order: 34,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述内脏疾病常见的牵涉痛体表部位、产生机制及临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "牵涉痛的部位、机制与临床意义",
        "常见体表部位：心肌缺血→心前区、左肩和左上臂；膈中央部受刺激→肩上部；胃溃疡和胰腺炎→左上腹和肩胛间；胆囊炎、胆石症发作→右肩区；阑尾炎→上腹部或脐周（发病开始时），继而牵涉腹股沟区；肾结石→睾丸。产生机制：发生牵涉痛的部位与疼痛原发内脏具有相同胚胎节段和皮节来源，二者受同一脊髓节段背部根支配，其传入纤维相互部分重叠；机制有会聚学说（内脏与体表感觉传入纤维在脊髓、丘脑或皮层会聚于共同神经元，经共同通路上传，将内脏痛误判为体表痛）和易化学说。临床意义：各种牵涉痛的体表放射部位较固定，对临床某些疾病的诊断具有重要提示作用和旁证意义。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-short003",
    order: 35,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述人眼视6m以内近物时所进行的调节及其生理意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "视近物时的调节及其意义",
        "自近物（6m以内）发出的入眼光线呈不同程度的辐射状，眼通过近反射进行调节，包括晶状体变凸（最重要）、瞳孔缩小和视轴会聚。①晶状体变凸：双眼睫状体肌收缩→悬韧带松弛→晶状体前凸，眼折光力增大，使视网膜像前移而变清晰；②瞳孔缩小：双眼瞳孔环行肌收缩使瞳孔变小，减小球面像差和色像差；③视轴会聚：双眼内直肌收缩使双眼视网膜像落在对称点上，避免发生复视。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-short004",
    order: 36,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述中耳的构成和功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中耳的构成与功能",
        "中耳由鼓膜、听骨链、鼓室和咽鼓管等结构组成。中耳的主要功能是将声波振动能量高效地传给内耳，其中鼓膜和听骨链在声音传递过程中还起增压作用；鼓室内的鼓膜张肌和镫骨肌可对内耳的感音装置起到保护作用；咽鼓管可平衡鼓室内气压与外界大气压，以维持鼓膜的正常位置与功能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-short005",
    order: 37,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试用行波理论解释内耳对音调的分析原理。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "行波理论对音调分析的解释",
        "当声波经卵圆窗膜传入耳蜗后，内淋巴液的振动引起基底膜振动。振动从基底膜底部开始，以行波方式从蜗底向蜗顶传播：声波频率越高，行波传播越近，最大振幅出现部位越靠近蜗底；频率越低，行波传播越远，最大振幅部位越靠近蜗顶。这样每一声波频率在基底膜上都有一个特定的行波传播范围和最大振幅区，位于该区的毛细胞受刺激最强，与之相联系的听神经纤维的传入冲动也最多；来自基底膜不同部位的听神经纤维冲动传到听觉中枢的不同部位，即可产生不同音调的感觉。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，2 组 × 2 成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-physiology-ch9-sensory-organs-b001",
    order: 38,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "增加折光能力",
      "减小球面像差和色像差",
      "避免复视",
      "减少人眼光量",
      "产生立体感觉",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-physiology-ch9-sensory-organs-b001m1",
        order: 38,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "视6m内近物时瞳孔缩小的意义是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "减小球面像差和色像差",
            "视近物时瞳孔缩小可减小光线透过晶状体边缘所产生的球面像差和色像差，使视网膜像更清晰。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch9-sensory-organs-b001m2",
        order: 39,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "在强光照射下瞳孔缩小的意义是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "减少人眼光量",
            "强光照射下瞳孔缩小以减少进入眼的光量，使视网膜不至于因光过强而受损，是瞳孔对光反射（适应功能）的体现。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch9-sensory-organs-b002",
    order: 40,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "视神经乳头",
      "黄斑中央凹",
      "中央凹外10°~20°处",
      "视网膜颞侧半",
      "视网膜鼻侧半",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-physiology-ch9-sensory-organs-b002m1",
        order: 40,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "视网膜上视杆细胞分布最多的部位是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "中央凹外10°~20°处",
            "视杆细胞主要分布于视网膜周边部，在中央凹外10°~20°处最多，对光敏感度高、无色觉、分辨力低。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch9-sensory-organs-b002m2",
        order: 41,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "视网膜上视锥细胞分布最多的部位是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "黄斑中央凹",
            "视锥细胞集中于黄斑中央凹处，数量较多但对光敏感度低、有色觉、分辨力高。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];