import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 生理学 学习指导与习题集（第3版）— 第十章 神经系统的功能 题库提取（等比取样）
 * 来源：《生理学学习指导与习题集》第3版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 101 道独立记分题，按本检查章节各题意量等比缩放）==
 * - 名词解释：11 题
 * - A1/A2/X 型选择题（统一映射为 a1-single 单选）：62 题
 * - 简答题（含部分思考题）：9 题
 * - B1 共用备选答案配伍题：6 组、共 19 个成员
 * - 独立记分题合计：101 题（含 B1 组成员）
 * - 缺失答案：0 题；无法可靠提取：0 题
 * - 说明：本章原书设 6 节复习思考题与参考答案，依次覆盖突触传递/神经元功能、感觉分析、
 *   躯体运动调控、自主神经与内脏调节、脑电/睡眠与觉醒、脑的高级功能（语言与记忆）。
 *   本题库按各节题量等比取材并改写题干。X 型多选按项目规约映射为 a1-single 单选
 *   （题干改写成单句式并在 promptSource.note 中标注），A1/A2 型亦映射为 a1-single。
 *   OCR 错字已按医学语义恢复（如“脊俄”→脊髓、“突触躲泡”→突触囊泡、“微粒分子”→郎飞结、
 *   “催进”→促进等），数值与单位保留原值，未捏造。
 *   各选择题可选项行（题号相邻、OCR 乱序）经人工重建为 A–E 逻辑顺序后填入 choices。
 * 注意：本文件覆盖 PDF 第239–293页（第十章 神经系统的功能）。
 *
 * 解析内容位于 answer.content 数组的第二个元素。
 */

const topic = "physiology-ch10-nervous-system";
const locatorBase =
  "《生理学学习指导与习题集》第3版 第十章 神经系统的功能 复习思考题 习题（PDF 第239–293页）";
const promptNote =
  "题干改写；原题来自用户提供的题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原书为X型多选题，按项目规约映射为a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据上传题集整理并改写，尚未与权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），11 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-physiology-ch10-nervous-system-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：神经冲动（nerve impulse）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "神经冲动",
        "是指在神经纤维上传导着的兴奋或动作电位，简称冲动，是兴奋沿神经纤维进行传导的形式。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：轴浆运输（axoplasmic transport）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "轴浆运输",
        "指神经轴突内的胞浆沿从胞体到末梢方向（顺向）或从末梢到胞体方向（逆向）流动的现象，具有运输物质的作用，对维持神经元解剖和功能的完整性具有重要意义。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：突触后抑制（postsynaptic inhibition）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "突触后抑制",
        "由抑制性中间神经元释放抑制性递质，使突触后神经元产生抑制性突触后电位（IPSP）而产生的抑制，包括传入侧支性抑制和回返性抑制等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：突触前抑制（presynaptic inhibition）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "突触前抑制",
        "当一个神经元的轴突末梢与第二个兴奋性神经元的轴突末梢形成轴突-轴突型突触，前者兴奋时所释放的递质可影响后者兴奋时在第三个神经元胞体产生的兴奋性突触后电位；若第一个神经元预先兴奋降低了第二个神经元兴奋时释放的兴奋性递质量，便称为突触前抑制（反之则称突触前易化）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：特异投射系统（specific projection system）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "特异投射系统",
        "指丘脑特异感觉接替核和联络核及其投射至大脑皮层的神经通路。来自躯体各部位和各种类型的感觉传入以点对点方式投向大脑皮层的特定区域，产生特定的感觉。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：脊休克（spinal shock）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脊休克",
        "当脊髓与高位中枢离断后，脊髓暂时丧失反射活动的能力而进入无反应状态的现象。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：运动单位（motor unit）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "运动单位",
        "由一个α运动神经元及其所支配的全部肌纤维所组成的功能单位称为运动单位，其大小取决于α运动神经元轴突末梢分支的多少。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：小脑性共济失调（cerebellar ataxia）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "小脑性共济失调",
        "脊髓小脑受损后，由于不能有效利用来自大脑皮层和外周感觉的反馈信息来协调运动，运动变得笨拙而不准确，表现为随意运动的力量、方向及限度发生紊乱，称为小脑性共济失调。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：自主神经系统（autonomic nervous system）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "自主神经系统",
        "通常指中枢及其支配内脏器官的传出神经，不包括传入神经，主要包括交感神经系统和副交感神经系统。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：非快眼动睡眠（non-rapid eye movement sleep）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "非快眼动睡眠",
        "脑电图呈现高幅慢波，各种感觉及骨骼肌反射、呼吸、循环和交感神经活动等较清醒时减弱，不伴眼球剧烈运动的睡眠状态，可分为四期，I、II期称浅睡眠，III、IV期称深睡眠，又称慢波睡眠（NREM睡眠）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-term011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：优势半球（dominant hemisphere）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "优势半球",
        "语言中枢所在的大脑半球称为优势半球。人类两侧大脑半球的功能是不对等的，习惯使用右手的成年人，其语言活动中枢主要在左侧大脑皮层。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2/X 型选择题（统一映射为 a1-single），62 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-physiology-ch10-nervous-system-a1001",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在中枢神经系统中，神经元的动作电位一般首先发生的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["轴突", "树突", "轴突始段", "轴丘", "胞体"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "轴突始段",
        "轴突始段电压门控钠通道密度高、阈值最低，EPSP 经总和后一般首先在此爆发动作电位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1002",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "周围感觉神经元的假单极神经元，其动作电位一般首先发生的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "周围突距离胞体最近的第一个郎飞结",
      "周围突距离远端末梢最近的第一个郎飞结",
      "中枢突末梢",
      "胞体",
      "树突",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "周围突距离胞体最近的第一个郎飞结",
        "假单极神经元外周感受器受刺激产生的局部电流在有髓周围突上传导，多于距离胞体最近的第一个郎飞结处首先爆发动作电位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1003",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于神经纤维兴奋传导特征的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "神经干中各纤维的动作电位传导互不干扰",
      "只能从轴突至末梢单向传导",
      "只要结构完整就能正常传导兴奋",
      "不受内环境因素变化的影响",
      "连续刺激时传导能力很快下降",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "神经干中各纤维的动作电位传导互不干扰",
        "神经纤维兴奋传导具有完整性、绝缘性（互不干扰性）、双向性和相对不疲劳性，故神经干中各纤维动作电位互不干扰。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1004",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "支配骨骼肌梭内肌的传出神经纤维属于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["Aα类纤维", "Aβ类纤维", "Aγ类纤维", "B类纤维", "C类纤维"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Aγ类纤维",
        "γ运动神经元支配梭内肌，其传出纤维属 Aγ 类；α 运动神经元支配梭外肌。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1005",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "脊髓灰质炎患者发生肢体肌肉萎缩的主要原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "骨骼肌失去神经的营养性作用",
      "病毒对患肢肌肉的直接侵害",
      "患肢肌肉血液供应减少",
      "患肢长期失用",
      "脊髓失去高位中枢的控制",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骨骼肌失去神经的营养性作用",
        "脊髓前角运动神经元受损后，其所支配的骨骼肌失去神经末梢释放营养因子的营养性作用，缓慢但持续地发生萎缩。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1006",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于神经胶质细胞的描述，最准确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "终生具有分裂增殖的能力",
      "既有树突又有轴突",
      "细胞之间能形成化学性突触",
      "有随细胞外Na+浓度改变而改变的膜电位",
      "有产生动作电位的能力",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "终生具有分裂增殖的能力",
        "胶质细胞无树突、轴突之分，不形成化学性突触，不能产生动作电位，但终身具有分裂增殖能力，其余选项均与其特性不符。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1007",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "当神经胶质细胞受损而过度增生时，可因下列哪项功能减弱而形成局部癫痫病灶",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["泵K+能力", "绝缘作用", "屏障作用", "营养性作用", "支持作用"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "泵K+能力",
        "星形胶质细胞能摄取细胞外液中过多的 K+ 以维持其浓度稳定，该功能减弱使局部神经元兴奋性异常增高，可成为致痫病灶。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1008",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "动作电位传导到突触末梢时，以下哪一项是触发神经递质释放的关键变化",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["Ca2+内流", "Na+内流", "Cl-外流", "K+外流", "Ca2+外流"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Ca2+内流",
        "突触前末梢去极化使电压门控钙通道开放、Ca2+ 内流，轴浆内 Ca2+ 浓度升高触发突触囊泡出胞释放递质。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1009",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "对动作电位在突触末梢所触发的神经递质释放来说，可直接使释放量减少的变化是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "Ca2+内流减少",
      "Ca2+通道通透性增加",
      "Na+内流增加，动作电位时程延长",
      "K+外流减慢",
      "Cl-内流增加",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Ca2+内流减少",
        "递质释放量与进入轴浆内的 Ca2+ 量呈正相关，钙通道通透性降低或 Ca2+ 内流减少时释放量随之减少。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1010",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下哪种神经递质受体属于促代谢型受体",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["GABAb受体", "GABAA受体", "GABAC受体", "甘氨酸受体", "5-HT3受体"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "GABAb受体",
        "GABAb 受体经 G 蛋白耦联启动第二信使反应，属促代谢型受体；其余 GABAA、GABAC、甘氨酸、5-HT3 受体均为促离子型（配体门控离子通道）受体。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1011",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "产生快速兴奋性突触后电位（快EPSP）的主要机制是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "突触后膜Na+内流增加",
      "突触前末梢递质释放增多",
      "突触后神经元反应性升高",
      "突触后膜K+外流减少",
      "突触后膜K+外流增加",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "突触后膜Na+内流增加",
        "兴奋性递质使突触后膜对 Na+ 通透性增大、Na+ 内流大于 K+ 外流，产生净内向电流致后膜局部去极化，即形成快EPSP。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1012",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "产生快速抑制性突触后电位（快IPSP）的主要机制是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "突触后膜Cl-内流增加",
      "突触前末梢兴奋性递质释放减少",
      "突触后膜Na+内流减少",
      "突触后膜Ca2+内流减少",
      "突触后膜Cl-外流增加",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "突触后膜Cl-内流增加",
        "抑制性递质作用于突触后膜使氯通道开放、Cl- 内流增加，引起外向电流使后膜超极化，即形成快IPSP。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1013",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "突触后神经元兴奋时，动作电位一般首先在轴突始段爆发，其主要原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "电压门控钠通道高密度表达在始段",
      "EPSP传导至此处时因总和而幅度最大",
      "此处的细胞膜静息电位最低",
      "此处缺乏钾通道",
      "此处无髓鞘包裹",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "电压门控钠通道高密度表达在始段",
        "轴突始段富含电压门控钠通道、阈值最低，故与神经元兴奋有关的动作电位一般首先在此爆发。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1014",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于突触可塑性的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "是神经系统成熟前的特征性表现",
      "包括突触功能与形态改变",
      "突触前或突触后均可参与发生",
      "普遍存在于中枢神经系统",
      "突触传递效率改变较持久",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "是神经系统成熟前的特征性表现",
        "突触可塑性贯穿整个生命过程而非仅见于成熟前，该说法为错误表述；其余选项均符合突触可塑性的特征。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1015",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪些类型的抑制必须有抑制性中间神经元参与（原书为多选题，此处取其中一项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "回返性抑制",
      "突触前抑制",
      "突触后易化",
      "单纯性抑制",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "回返性抑制",
        "原书为X型多选，答案为侧支性抑制、回返性抑制、突触后抑制（均需抑制性中间神经元参与）；此处按规约取回返性抑制映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1016",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪种受体属于G蛋白耦联受体",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["毒蕈碱受体", "烟碱受体", "甘氨酸受体", "NMDA受体", "GABAA受体"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "毒蕈碱受体",
        "毒蕈碱（M）受体经 G 蛋白耦联，属促代谢型受体；N、甘氨酸、NMDA、GABAA 受体均为促离子型通道受体。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1017",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "菜农喷施农药后胸闷、流涎、恶心、间歇腹痛、冷汗、视力模糊且瞳孔缩小、伴抽搐，接诊医生依次处置，其中哪一项不妥",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "用新斯的明滴眼液给其滴眼",
      "肌内注射硫酸阿托品0.5mg",
      "嘱其立即去卫生间淋浴并多打肥皂",
      "嘱其在留观室休息并给予吸氧",
      "嘱其适量饮水",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "用新斯的明滴眼液给其滴眼",
        "该病例为有机磷农药中毒，抑制胆碱酯酶、乙酰胆碱蓄积，应用阿托品（M 受体拮抗剂）解救；新斯的明是胆碱酯酶抑制剂，会加重中毒，故滴眼不妥。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1018",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "集体进食未经烧烤的自带即食食品后出现乏力、呼吸和吞咽困难、视物模糊，诊为肉毒梭菌中毒，其肌肉乏力的发生机制是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "乙酰胆碱囊泡释放障碍",
      "乙酰胆碱合成障碍",
      "乙酰胆碱重摄取障碍",
      "乙酰胆碱灭活障碍",
      "乙酰胆碱受体被阻断",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "乙酰胆碱囊泡释放障碍",
        "肉毒梭菌毒素可灭活与囊泡着位有关的蛋白，阻碍神经-肌接头处乙酰胆碱囊泡的释放，产生柔软性麻痹、肌肉乏力。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1019",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "感觉的特异投射系统能引起特定感觉的主要原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "与大脑皮层有点对点的投射关系",
      "发自丘脑髓板内核团",
      "中间多次换元，再投射到大脑皮层",
      "投射纤维主要终止于皮层各层",
      "很少受内环境理化因素的影响",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "与大脑皮层有点对点的投射关系",
        "特异投射系统来自丘脑特异感觉接替核和联络核，点对点投向大脑皮层特定区域（终止于皮层第四层），因此能够产生特定感觉。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1020",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "感觉的非特异投射系统的主要功能是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "维持和改变大脑皮层的兴奋状态",
      "产生各种特定感觉",
      "抑制大脑皮层的活动",
      "激发大脑皮层产生传出冲动",
      "在丘脑和大脑皮层间进行往返联络",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "维持和改变大脑皮层的兴奋状态",
        "非特异投射系统弥散投射到大脑皮层广泛区域，不产生特定的感觉，但可维持和改变大脑皮层的兴奋状态（上行唤醒作用）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1021",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于皮层第一感觉区的投射规律，以下哪项叙述是正确的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "膝以下代表区位于大脑半球内侧面",
      "所有的感觉纤维投射均来自对侧躯体",
      "代表区大小与身体各部大小成正比",
      "整个人体代表区完全倒置性安排",
      "代表区前后按肢体近、远端顺序排列",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "膝以下代表区位于大脑半球内侧面",
        "中央后回体表投射总体呈倒置安排但头面部为正立，代表区大小与分辨精细程度有关，膝以下代表区延伸至半球内侧面，故该项正确。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1022",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "中枢损伤最不易产生缺损的感觉类型是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["触-压觉", "本体感觉", "温度觉", "躯体痛", "内脏痛"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "触-压觉",
        "触-压觉传入通路分支多，抗损伤能力强，是中枢损伤后最不易出现缺损的感觉类型。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1023",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下感觉类型中，传入通路不经过丘脑的是哪一种",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["嗅觉", "振动觉", "触-压觉", "温度觉", "味觉"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "嗅觉",
        "嗅觉冲动不经过丘脑中继，直接投射到大脑皮层嗅区（梨状区等）进行加工。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1024",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "男性50岁，近一月来乳头以下胸部、腰部皮肤感觉麻木、迟钝，两天前被热水袋轻度烫伤；一年前肺癌手术，疑脊髓转移，对转移灶初发位置可能性最大的判断是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胸髓近中央部",
      "胸髓近边缘部",
      "腰髓近边缘部",
      "骶髓近中央部",
      "腰髓近中央部",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸髓近中央部",
        "患者浅感觉（痛温觉）障碍自胸部向下发展，符合前外侧索内颈、胸、腰、骶自内向外的走行排列特点，提示早期受压偏近脊髓中央部，胸髓近中央部可能性最大。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1025",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "脊髓突然横断后，断面以下脊髓反射减弱或消失，其原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脊髓突然失去了高级中枢的调节作用",
      "损伤性刺激对脊髓的抑制作用",
      "脊髓的反射中枢被破坏",
      "失去了网状结构抑制区对脊髓的抑制作用",
      "血压下降导致脊髓功能受损",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脊髓突然失去了高级中枢的调节作用",
        "脊休克的发生不是刺激本身或反射中枢破坏所致，而是离断后脊髓突然失去高位中枢的易化作用，反射活动暂时减弱或消失。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1026",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪种反射不属于姿势反射",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["屈肌反射", "翻正反射", "对侧伸肌反射", "节间反射", "状态反射"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "屈肌反射",
        "屈肌反射是肢体受伤害性刺激时的防御性反射，不属于姿势反射。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1027",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "脊髓高位离断的病人，在脊休克过去后的表现是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "离断面以下的感觉和随意运动功能永久性丧失",
      "排尿、排便功能恢复正常并能自主控制",
      "血压恢复至正常水平并保持稳定",
      "离断面以下屈肌反射减弱",
      "离断面以下伸肌反射增强",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "离断面以下的感觉和随意运动功能永久性丧失",
        "脊髓横断后断面以下与大脑的联系被永久切断，感觉与随意运动不能恢复；脊休克期过后可恢复部分反射，但血压、排便等不一定完全恢复正常。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1028",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于腱反射的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "高位中枢病变时可引起腱反射亢进",
      "腱反射是多突触反射",
      "腱反射中枢位于延髓",
      "是由于缓慢牵拉肌腱引起的反射",
      "腱反射的感受器是腱器官",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "高位中枢病变时可引起腱反射亢进",
        "腱反射由快速牵拉肌腱引起、为单突触反射、感受器是肌梭；高位中枢（上运动神经元）病变使脊髓失去抑制，可引起腱反射亢进。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1029",
    order: 40,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "当α运动神经元传出冲动增加时可引起",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "梭外肌收缩",
      "梭内肌收缩",
      "肌梭敏感性增加",
      "腱器官敏感性降低",
      "梭内肌和梭外肌同时收缩",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "梭外肌收缩",
        "α 运动神经元支配梭外肌，传出冲动增加引起梭外肌收缩，产生运动与张力。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1030",
    order: 41,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "当γ运动神经元传出冲动增加时可引起",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肌梭敏感性增加",
      "肌梭传入冲动减少",
      "α运动神经元传出冲动减少",
      "梭外肌收缩弛缓",
      "腱器官的传入冲动增加",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌梭敏感性增加",
        "γ 运动神经元支配梭内肌，冲动增加使梭内肌纤维收缩、肌梭感觉末梢被牵张，肌梭敏感性提高，肌梭传入冲动增多。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1031",
    order: 42,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "维持躯体姿势的最基本的反射是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["肌紧张", "屈肌反射", "对侧伸肌反射", "腱反射", "节间反射"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌紧张",
        "肌紧张是维持躯体姿势的最基本的反射，是姿势反射的基础。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1032",
    order: 43,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肌紧张的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "人类以屈肌肌紧张为主要表现",
      "感受器为肌梭",
      "为多突触反射",
      "反射持久进行时不易疲劳",
      "由缓慢持续牵拉肌腱引起",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "人类以屈肌肌紧张为主要表现",
        "人类维持姿势以伸肌肌紧张为主（抗重力肌），而不是屈肌肌紧张，故该项为错误描述；肌紧张感受器为肌梭、属多突触反射、不易疲劳、由缓慢持续牵拉引起。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1033",
    order: 44,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于牵张反射的叙述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "腱反射中枢位于延髓",
      "包括腱反射和肌紧张两种类型",
      "牵张反射是维持姿势的基本反射",
      "牵张反射在抗重力肌表现最为明显",
      "牵张反射的中枢在脊髓",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腱反射中枢位于延髓",
        "牵张反射的中枢在脊髓，腱反射中枢位于脊髓相应节段，而非延髓，故该项为错误表述。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1034",
    order: 45,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "去大脑僵直的产生是由于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "切断了网状结构和皮层运动区及纹状体之间的联系",
      "切除了脑干网状结构抑制区",
      "切除了脑干网状结构易化区",
      "切断了网状结构和小脑之间的联系",
      "切断了网状结构和前庭核之间的联系",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "切断了网状结构和皮层运动区及纹状体之间的联系",
        "中脑上、下丘之间切断脑干，中断大脑皮层、纹状体与脑干网状结构间的联系，使抑制区活动减弱、易化区活动占优势，产生去大脑僵直。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1035",
    order: 46,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于大脑皮层运动区的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "对躯体骨骼肌运动为交叉性支配",
      "人大脑皮层主要运动区位于中央后回",
      "对头面部肌肉运动均为双侧性支配",
      "躯体和头面部内部均为倒置性安排",
      "代表区的大小与肌肉运动产生力量的大小相关",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对躯体骨骼肌运动为交叉性支配",
        "主要运动区位于中央前回(4区)和运动前区(6区)，对躯体骨骼肌运动为交叉性支配；头面部多为双侧支配但并非全部；代表区大小与运动精细程度有关。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1036",
    order: 47,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "帕金森病是由哪一神经通路受损引起的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "黑质-纹状体多巴胺能通路",
      "纹状体-黑质γ-氨基丁酸能通路",
      "纹状体内胆碱能通路",
      "结节-漏斗多巴胺能通路",
      "脑干网状结构胆碱能系统",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "黑质-纹状体多巴胺能通路",
        "帕金森病主要由黑质-纹状体多巴胺能神经通路受损、多巴胺缺失引起。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1037",
    order: 48,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "帕金森病产生的原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "黑质多巴胺递质系统功能受损",
      "新纹状体-苍白球内侧部直接通路活动增强",
      "新纹状体-苍白球内侧部间接通路活动减弱",
      "纹状体乙酰胆碱递质系统活动减弱",
      "黑质多巴胺递质系统功能亢进",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "黑质多巴胺递质系统功能受损",
        "帕金森病是黑质多巴胺能神经元变性致黑质-纹状体多巴胺递质系统功能受损所致，多巴胺对纹状体内胆碱能神经元的抑制作用减弱，乙酰胆碱递质系统功能相对亢进。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1038",
    order: 49,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某患者因外伤造成胸部脊髓突然横断，此时患者可出现",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "粪、尿潴留",
      "断面以下骨骼肌肌紧张增强",
      "血压升高",
      "脊休克恢复后伸肌和屈肌反射都增强",
      "断面以下皮肤发汗",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "粪、尿潴留",
        "脊髓横断后处于脊休克期，断面以下肌紧张减弱、血压下降、发汗和排便排尿反射消失，出现粪、尿潴留。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1039",
    order: 50,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关副交感神经系统的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "在安静时活动较强",
      "节前纤维短，节后纤维长",
      "只支配少部分器官",
      "无紧张性活动",
      "刺激节前纤维引起的反应比较弥散",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "在安静时活动较强",
        "副交感神经节距效应器近，节前纤维长、节后纤维短；安静时副交感神经活动相对较强，参与机体的休整和消化吸收。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1040",
    order: 51,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于交感神经系统的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "在应急或应激时，活动较强",
      "节前纤维长，节后纤维短",
      "只支配少部分器官",
      "无紧张性活动",
      "刺激节前纤维引起的反应比较局限",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "在应急或应激时，活动较强",
        "交感神经节前纤维短、节后纤维长，支配范围广，在应急或应激时活动增强，动员机体潜力以适应环境剧变。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1041",
    order: 52,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "交感神经兴奋或紧张性增强时",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "可使心肌收缩力增强",
      "促进糖原合成，使血糖浓度降低",
      "使支气管平滑肌收缩",
      "促进胃肠运动",
      "抑制汗腺分泌",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "可使心肌收缩力增强",
        "交感神经兴奋使心率加快、心肌收缩力增强、支气管平滑肌舒张、胃肠运动减弱、糖原分解增强血糖升高。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1042",
    order: 53,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "交感神经系统功能活动的意义在于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "应付环境急剧变化",
      "促进消化",
      "保存能量",
      "增加器官血流量",
      "加速排泄",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "应付环境急剧变化",
        "交感神经系统活动较广泛，在环境急剧变化时动员机体潜力、提高适应能力，以应付环境的急剧变化。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1043",
    order: 54,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列生理活动的基本中枢不在延髓的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["体温调节", "心脏活动", "血管活动", "呼吸运动", "消化管运动"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "体温调节",
        "体温调节的基本中枢在视前区-下丘脑前部，而心脏、血管、呼吸、消化管运动等基本生命反射中枢均在延髓，故称延髓为生命中枢。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1044",
    order: 55,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下丘脑具有多种较高级的整合功能，但不包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "调节肌紧张",
      "调节饮水",
      "调节摄食行为和自主神经活动",
      "调节情绪反应",
      "调节体温",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "调节肌紧张",
        "下丘脑参与体温、饮水、摄食、情绪和自主神经活动的整合调节，但不属于调节肌紧张的中枢（肌紧张调节中枢在脑干与脊髓水平）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1045",
    order: 56,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下丘脑控制日周期节律中心的核团是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["视交叉上核", "视上核", "下丘脑前核", "室旁核", "下丘脑后核"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "视交叉上核",
        "下丘脑视交叉上核是哺乳动物控制日周期（昼夜）节律的关键部位，使内源性日节律适应外界昼夜节律并同步化。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1046",
    order: 57,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下丘脑的防御反应区主要位于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["腹内侧区", "前区", "视前区", "背内侧区", "外侧区"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腹内侧区",
        "下丘脑的防御反应区主要位于下丘脑腹内侧区；刺激该区可引发典型的防御反应。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1047",
    order: 58,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "交感神经系统活动的一般特征和意义包括（原书为多选题，此处取其中一项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "动员机体潜力以应对环境急剧变化",
      "其功能活动较为局限",
      "对心脏活动有抑制作用",
      "对消化系统活动有增强作用",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动员机体潜力以应对环境急剧变化",
        "原书为X型多选，答案为功能活动广泛、对心脏活动增强、对胃肠道平滑肌活动抑制、动员机体潜力应对环境急剧变化；此处取“动员机体潜力以应对环境急剧变化”映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1048",
    order: 59,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "脑电图对于以下哪种疾病的诊断有较好的诊断价值",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["癫痫", "精神分裂症", "焦虑症", "抑郁症", "智力低下"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "癫痫",
        "脑电图对癫痫的诊断价值较高，常可记录到棘波、尖波等异常放电；对其他选项无特异诊断意义。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1049",
    order: 60,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "大脑皮层处于紧张活动时脑电活动主要表现为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["β波", "α波", "θ波", "δ波", "κ复合波"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "β波",
        "成人清醒活动、思维紧张时脑电以快波（β波）为主，表现为低波幅高频去同步化。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1050",
    order: 61,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与觉醒状态维持有关的神经递质是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["组胺", "腺苷", "前列腺素D2", "生长激素", "褪黑素"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "组胺",
        "下丘脑结节乳头体核组胺能神经元参与维持觉醒；腺苷、前列腺素D2 等则促进睡眠，与觉醒维持无关。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1051",
    order: 62,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于脑干网状结构上行激动系统的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "可维持大脑皮层的兴奋状态",
      "通过丘脑特异投射系统发挥作用",
      "兴奋后脑电波呈现同步化慢波",
      "神经元的联系在此高度会聚，使各种特异感觉的传入具有专一性",
      "是一个多递质系统，不易受药物的影响",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "可维持大脑皮层的兴奋状态",
        "脑干网状结构上行激动系统经丘脑非特异投射系统弥散投射到大脑皮层广泛区域，维持大脑皮层兴奋状态（上行唤醒作用），兴奋时脑电呈去同步化快波。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1052",
    order: 63,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "非快眼动（NREM）睡眠的特征是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "促进生长和体力恢复",
      "脑电呈去同步化的快波",
      "生长激素分泌减少",
      "多梦",
      "脑内蛋白质合成加快",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "促进生长和体力恢复",
        "NREM 睡眠脑电呈同步化慢波、生长激素分泌增多，意义在于促进生长和体力恢复；多梦和脑内蛋白质合成加快主要用于描述 REM 睡眠。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1053",
    order: 64,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "快眼动（REM）睡眠的生物学意义是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "促进学习记忆和精力的恢复",
      "促进机体的生长发育",
      "促进生长激素的释放",
      "促进细胞增殖和分化",
      "增进食欲和促进消化吸收",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "促进学习记忆和精力的恢复",
        "REM 睡眠期脑内蛋白质合成加快、耗氧量和血流量增多，与幼儿神经系统成熟、新突触联系建立有关，能促进学习记忆和精力的恢复。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1054",
    order: 65,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "非联合型学习",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "单一刺激的重复进行即可产生",
      "需要两种刺激或刺激与反应间的联合",
      "习惯化不属于非联合型学习",
      "敏感化不属于非联合型学习",
      "人体不存在非联合型学习",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单一刺激的重复进行即可产生",
        "非联合型学习不需在两种刺激或刺激与反应间建立联系，只要单一刺激的重复即可产生，习惯化和敏感化属于此类。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1055",
    order: 66,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于联合型学习的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "突触的习惯化和敏感化是形成的基础",
      "两个事件在时间上很接近地重复发生",
      "需要大脑皮层的参与",
      "条件反射属于联合型学习",
      "过目不忘不属于联合型学习",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "突触的习惯化和敏感化是形成的基础",
        "习惯化和敏感化属于非联合型学习，故说它们是联合型学习的形成基础是错误的；其余选项均符合联合型学习的特征。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1056",
    order: 67,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪项是关于非陈述性记忆的正确描述",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "游泳、开车、演奏乐器等技巧性动作的记忆均属于非陈述性记忆",
      "受意识控制",
      "需要海马、杏仁核和其他边缘系统的参与",
      "不需要重复练习即可形成",
      "容易忘记",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "游泳、开车、演奏乐器等技巧性动作的记忆均属于非陈述性记忆",
        "非陈述性记忆是对一系列规律性操作程序的记忆，是一种下意识的感知及反射，一旦形成则不容易遗忘，需经反复练习才能形成，不依赖意识过程。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1057",
    order: 68,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于遗忘的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "是条件刺激长时间得不到强化而引起的",
      "遗忘是一种不正常的生理现象",
      "脑震荡可引起顺行性遗忘症",
      "信息进入长时程记忆就不会产生遗忘",
      "遗忘意味着记忆痕迹完全消失",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "是条件刺激长时间得不到强化而引起的",
        "条件反射性“遗忘”是条件刺激长时间得不到强化而发生消退的表现，属正常生理现象；脑震荡引起的是逆行性遗忘，遗忘并不意味记忆痕迹完全消失。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1058",
    order: 69,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "逆行性遗忘发生的可能机制是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "第二级记忆发生紊乱",
      "感觉性记忆发生紊乱",
      "第一级记忆发生紊乱",
      "第三级记忆发生紊乱",
      "海马环路的损害",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第二级记忆发生紊乱",
        "逆行性遗忘的发生机制可能是第二级记忆发生紊乱，而第三级记忆不受影响。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1059",
    order: 70,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "长时程记忆障碍主要与下列哪个部位受损有关",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["海马", "纹状体", "下丘脑", "小脑", "大脑皮层联络区"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "海马",
        "海马在长时程记忆的形成中起重要作用，海马受损则短时程记忆不能转变为长时程记忆。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1060",
    order: 71,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "习惯用右手的人，其左侧大脑半球的优势主要表现在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["语言活动", "空间辨认", "深度知觉", "音乐欣赏", "精巧的运动功能"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "语言活动",
        "习惯用右手的成年人，其语言活动中枢主要在左侧大脑皮层，即左侧半球为语言的优势半球。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1061",
    order: 72,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "运动失语症表现为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "自己不会讲话",
      "看不懂文字",
      "与发音有关的肌肉麻痹",
      "听不懂别人谈话",
      "说话正常，但词不达意",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "自己不会讲话",
        "运动失语症（Broca 区损伤）患者能看懂文字、听懂别人谈话，但自己不会讲话；说话器官本身并无肌肉麻痹。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-a1062",
    order: 73,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "感觉性失语表现为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "能听到别人的发音，但是听不懂说话的含义",
      "能听懂别人谈话",
      "看不懂文字",
      "不能用语言来表达",
      "不能组织语言",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "能听到别人的发音，但是听不懂说话的含义",
        "感觉性失语（Wernicke 区、颞上回后部损伤）患者的听力和发音均正常，但听不懂别人说话的含义。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），9 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-physiology-ch10-nervous-system-short001",
    order: 74,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述神经对效应组织的作用和神经纤维的主要功能活动。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "神经的功能性作用、营养性作用与神经纤维的主要功能",
        "神经对效应组织有功能性作用和营养性作用两方面作用：功能性作用指神经末梢释放递质使所支配组织迅速发生功能变化，如肌肉收缩、腺体分泌；营养性作用指神经通过末梢释放某些营养因子持续调整所支配组织的内在代谢活动、结构与功能状态。神经纤维的主要功能是传导兴奋（动作电位的传导）和轴浆运输；轴浆运输指借助轴突内轴浆流动进行的物质运输，有顺向和逆向之分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-short002",
    order: 75,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试比较各类突触传递的结构和功能特征。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "电突触与化学性（定向/非定向）突触的比较",
        "突触传递分电突触传递和化学性突触传递两类。电突触传递的结构基础是缝隙连接，具有双向性、低电阻性和快速性特点，主要分布在同类神经元群之间，对其活动的同步化有重要作用。化学性突触传递又分定向和非定向两类：定向突触具有特化的突触前膜、突触后膜和突触间隙结构，递质仅在狭小突触间隙内扩散、定向作用于突触后膜中的受体；非定向突触无上述特化结构，其突触前末梢分出许多含曲张体的分支穿行于突触后细胞间，递质从曲张体释出、扩散远近不等，能否产生效应取决于突触后成分上有无相应受体。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-short003",
    order: 76,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述经典突触的传递过程及其影响因素。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "经典突触的传递过程与影响因素",
        "当突触前神经元的兴奋传到末梢时，突触前膜去极化；去极化达一定程度时膜上的电压门控钙通道开放、Ca2+内流，轴浆内Ca2+浓度迅速升高，触发突触囊泡的出胞释放递质。递质的释放量与进入轴浆内的Ca2+量呈正相关。影响因素详见本教材知识要点部分表10-2。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-short004",
    order: 77,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "人体的直立姿势是如何维持的？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "直立姿势的维持机制",
        "取直立体位时支持体重的关节因重力影响而趋向弯曲，使伸肌的肌梭受到持续牵拉，引起被牵拉的肌肉收缩，使背部骶棘肌、颈部和下肢的伸肌群肌紧张加强，以对抗关节屈曲，保持抬头、挺胸、伸腰、直腿的直立姿势。另一原因是高位中枢不断下传冲动兴奋γ运动神经元，影响肌梭敏感性，进而影响α运动神经元兴奋性，使骨骼肌处于持续轻微收缩状态。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-short005",
    order: 78,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "在动物中脑上、下丘之间横断脑干，将会出现什么现象？为什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "去大脑僵直",
        "在麻醉动物于中脑上、下丘之间切断脑干，肌紧张明显亢进，表现为四肢伸直、坚硬如柱、头尾昂起、脊柱挺硬、呈角弓反张状态，这一现象称为去大脑僵直，是抗重力肌（伸肌）紧张增强的表现。其发生机制是中脑水平切断脑干后中断了大脑皮层、纹状体等部位与脑干网状结构之间的功能联系，造成抑制区与易化区活动失衡，使抑制区活动减弱、易化区活动明显占优势。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-short006",
    order: 79,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "基底神经节与小脑在躯体运动的调节中有何异同？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "基底神经节与小脑调节运动的异同",
        "两者都参与运动的策划和程序编制、运动协调、肌紧张调节以及本体感觉传入信息的处理，但作用并不完全相同。基底神经节主要在运动的准备和发动阶段起作用，而小脑主要在运动进行过程中发挥作用；基底神经节主要与大脑皮层之间构成回路，小脑除与大脑皮层形成回路外，还与脑干及脊髓有大量纤维联系。因此基底神经节可能主要参与运动的策划，小脑除参与策划外还参与运动的执行。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-short007",
    order: 80,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "为什么快眼动睡眠又称为异相睡眠？此期睡眠有何生理意义？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "异相睡眠的得名与生理意义",
        "快眼动睡眠阶段各种感觉明显减弱，但脑电活动与觉醒期类似、呈去同步化快波，行为表现与脑电变化不一致，因此又称异相睡眠。此期脑内蛋白质合成加快、脑的耗氧量和血流量增多，与幼儿神经系统的成熟及新突触联系的建立关系密切，能促进学习记忆与精力恢复；但此期出现的阵发性表现可能与哮喘、心绞痛、阻塞性肺气肿缺氧发作等某些疾病易于在夜间发作有关。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-short008",
    order: 81,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述人类的记忆过程。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "记忆的四个阶段",
        "人类的记忆过程分为感觉性记忆、第一级记忆、第二级记忆和第三级记忆四个阶段。前两个阶段相当于短时程记忆，后两个阶段相当于长时程记忆。感觉性记忆是感觉系统获取的外界信息在脑内感觉区短暂储存的过程（一般不超过1秒），未经加工的信息会很快消失；若大脑对传入信息进行加工整合，则进入第一级记忆（保留数秒至数分钟）；部分信息经反复运用、强化得以在第一级记忆中循环并转入第二级记忆；经长年累月运用不易遗忘的记忆（如自己的名字、日常手艺）储存在第三级记忆中，成为永久记忆。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-short009",
    order: 82,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "比较顺行性遗忘和逆行性遗忘有何不同？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "顺行性与逆行性遗忘的比较",
        "临床上把由脑疾患引起的记忆障碍称为遗忘症，分顺行性遗忘症和逆行性遗忘症两种。顺行性遗忘指患者不能再形成新的记忆，而已形成的记忆不受影响，多见于慢性酒精中毒患者；脑自然衰老、海马和颞叶皮层损伤引起的记忆功能障碍亦属此类，其发生机制与信息不能从第一级记忆转入第二级记忆有关。逆行性遗忘指患者不能回忆发生记忆障碍之前一段时间的经历，但仍可形成新的记忆，多见于脑震荡、电击等非特异性脑疾患和麻醉，其发生机制可能是由于第二级记忆发生紊乱而第三级记忆不受影响。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，6 组 × 共 19 个成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-physiology-ch10-nervous-system-b001",
    order: 83,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["乙酰胆碱", "肾上腺素", "去甲肾上腺素", "5-羟色胺", "多巴胺"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-physiology-ch10-nervous-system-b001m1",
        order: 83,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "支配肾上腺的交感神经所释放的递质是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "乙酰胆碱",
            "支配肾上腺的交感神经为胆碱能节前纤维，其末梢释放的递质为乙酰胆碱，作用于肾上腺髓质促其分泌。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b001m2",
        order: 84,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "支配小汗腺的交感神经节后纤维末梢释放的递质是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "乙酰胆碱",
            "支配小汗腺的交感神经节后纤维末梢是胆碱能的，释放乙酰胆碱。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b001m3",
        order: 85,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "交感舒血管纤维末梢释放的递质是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "乙酰胆碱",
            "交感舒血管纤维末梢释放的递质为乙酰胆碱（胆碱能交感舒血管纤维）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b001m4",
        order: 86,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "交感缩血管纤维末梢释放的递质是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "去甲肾上腺素",
            "绝大多数交感缩血管纤维末梢释放的递质为去甲肾上腺素（肾上腺素能纤维）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-b002",
    order: 87,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["脑桥蓝斑核", "延髓中缝核", "下丘脑结节乳头体核", "迷走神经运动核", "中脑黑质"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-physiology-ch10-nervous-system-b002m1",
        order: 87,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "下列哪个核团主要含组胺能神经元",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "下丘脑结节乳头体核",
            "下丘脑结节乳头体核主要含有组胺能神经元。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b002m2",
        order: 88,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "下列哪个核团主要含胆碱能神经元",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "迷走神经运动核",
            "迷走神经运动核的神经元主要是胆碱能的。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b002m3",
        order: 89,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "下列哪个核团主要含5-羟色胺能神经元",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "延髓中缝核",
            "延髓中缝核主要含有5-羟色胺能神经元。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b002m4",
        order: 90,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "下列哪个核团主要含去甲肾上腺素能神经元",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "脑桥蓝斑核",
            "脑桥蓝斑核主要含有去甲肾上腺素能神经元。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-b003",
    order: 91,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["中央前回", "颞叶皮层", "中央后回", "枕叶皮层", "额叶皮层"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-physiology-ch10-nervous-system-b003m1",
        order: 91,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "人大脑皮层第一体表感觉区位于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "中央后回",
            "人大脑皮层第一体表感觉区位于中央后回。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b003m2",
        order: 92,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "人大脑皮层本体感觉代表区主要位于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "中央前回",
            "人大脑皮层本体感觉（深感觉）代表区主要位于中央前回一带。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b003m3",
        order: 93,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "人大脑皮层内脏感觉代表区主要位于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "中央后回",
            "人大脑皮层内脏感觉代表区主要位于中央后回附近。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-b004",
    order: 94,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "肌梭传入冲动减少，腱器官传入冲动不变",
      "肌梭传入冲动不变，腱器官传入冲动增加",
      "肌梭传入冲动增加，腱器官传入冲动减少",
      "肌梭传入冲动增加，腱器官传入冲动增加",
      "肌梭传入冲动减少，腱器官传入冲动增加",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-physiology-ch10-nervous-system-b004m1",
        order: 94,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "当骨骼肌做等张收缩时",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肌梭传入冲动减少，腱器官传入冲动不变",
            "等张收缩时肌肉长度缩短而张力不变，肌梭（长度感受器）传入冲动减少，腱器官（张力感受器）传入冲动不变。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b004m2",
        order: 95,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "当骨骼肌做等长收缩时",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肌梭传入冲动不变，腱器官传入冲动增加",
            "等长收缩时肌肉长度不变而张力增加，故肌梭传入冲动不变，腱器官传入冲动增加。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-b005",
    order: 96,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["去甲肾上腺素", "肾上腺素", "乙酰胆碱", "5-羟色胺", "γ-氨基丁酸"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-physiology-ch10-nervous-system-b005m1",
        order: 96,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "交感神经节前纤维释放的递质是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "乙酰胆碱",
            "交感神经节前纤维末梢释放的递质为乙酰胆碱。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b005m2",
        order: 97,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "支配皮肤黏膜血管的交感神经节后纤维释放的递质是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "去甲肾上腺素",
            "支配皮肤黏膜血管的交感神经节后纤维为肾上腺素能纤维，其释放的递质是去甲肾上腺素。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch10-nervous-system-b006",
    order: 98,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["下丘脑外侧区", "中脑", "下丘脑腹内侧核", "下丘脑前部", "延髓"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-physiology-ch10-nervous-system-b006m1",
        order: 98,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "瞳孔对光反射的中枢位于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "中脑",
            "瞳孔对光反射的中枢位于中脑。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b006m2",
        order: 99,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "渗透压感受器位于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "下丘脑前部",
            "渗透压感受器位于下丘脑前部（视前区）一带。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b006m3",
        order: 100,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "摄食中枢位于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "下丘脑外侧区",
            "摄食中枢位于下丘脑外侧区。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch10-nervous-system-b006m4",
        order: 101,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "饱中枢位于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "下丘脑腹内侧核",
            "饱中枢位于下丘脑腹内侧核。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];