import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 生理学 学习指导与习题集（第3版）— 第二章 细胞的基本功能 题库提取（等比取样）
 * 来源：《生理学学习指导与习题集》第3版（人民卫生出版社，主编：罗自强、祁金顺）
 *
 * == 统计报告（本文件题量 = 66 道独立记分题，按本章各题型占比等比取样）==
 * - 名词解释：8 题
 * - A1/A2/X 型选择题（统一映射为 a1-single 单选）：41 题
 * - 简答题：7 题
 * - 思考题（病例/计算，归为 case）：2 题
 * - B1 共用备选答案配伍题：3 组、共 8 个成员
 * - 独立记分题合计：66 题（含 B1 组成员）
 * - 缺失答案：0 题；无法可靠提取：0 题
 * - 说明：本章原书依次含名词解释 20（三节10/4/6）、A1型选择 61、A2型 24、
 *   B型 6 组（三节 12/3/6 成员）、X型多选 19、简答 18、思考题 4；
 *   本文件按 66 道预算等比取材并改写。X 型多选（含"选出全部正确答案"题）按项目
 *   规约映射为 a1-single 单选：从原 X 题干中提炼一个可单选的考点，题干改写并在
 *   promptSource.note 中标注（xMapNote）。A2 病例型亦映射为 a1-single。
 *   OCR 错字已按医学语义恢复（如"鲤/fl/fi/ffl/咱"→量、"ft→等）、数值与单位保留
 *   原值，未捏造。各选择题可选项行（题号相邻）经人工重建为 A–E 逻辑顺序后
 *   填入 choices 并随机重排。
 * 注意：本文件覆盖 PDF 第24–57页（第二章 细胞的基本功能，含第一节 细胞膜的物质转运
 * 与电活动、第二节 信号转导、第三节 肌细胞的收缩）。
 *
 * 解析内容位于 answer.content 数组的第二个元素。
 */

const topic = "physiology-ch2-cell-basic-functions";
const locatorBase =
  "《生理学学习指导与习题集》第3版 第二章 细胞的基本功能 复习思考题 习题（PDF 第24–57页）";
const promptNote =
  "题干改写；原题来自用户提供的题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原书为X型多选题，按项目规约映射为a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据上传题集整理并改写，尚未与权威教材交叉核对";

const kp = `kp-physiology-ch2-cell-basic-functions`;

/** 名词解释（term），8 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-physiology-ch2-cell-basic-functions-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：易化扩散（facilitated diffusion）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "易化扩散",
        "指在膜蛋白的帮助（或介导）下，非脂溶性的小分子物质或带电离子顺浓度梯度和（或）电位梯度进行的跨膜转运。易化扩散为被动转运，本身不消耗能量，分为经通道和经载体易化扩散两种形式。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：继发性主动转运（secondary active transport）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "继发性主动转运",
        "有些物质主动转运所需的驱动力并不是直接来自ATP的分解，而是利用原发性主动转运所形成的某些离子浓度梯度，在这些离子顺浓度梯度扩散的同时使其他物质逆浓度梯度和（或）电位梯度跨膜转运，这种间接利用ATP能量的主动转运过程称为继发性主动转运。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：静息电位（resting potential）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "静息电位",
        "指安静情况下细胞膜两侧存在的外正内负且相对平稳的电位差。静息电位主要是由K+外流形成的，实测值接近K+平衡电位，而钠泵的生电作用对其有小量贡献。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：动作电位（action potential）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动作电位",
        "指细胞在静息电位基础上，接受有效刺激后产生的一个迅速的可向远处传播的膜电位波动。动作电位包括锋电位和后电位两部分，具有全或无、不衰减传播和脉冲式发放等特点。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：信号转导（signal transduction）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "信号转导",
        "指生物学信息（兴奋或抑制）在细胞间或细胞内转换和传递，并产生生物效应的过程。信号转导通常指跨膜信号转导，即生物活性物质（激素、神经递质和细胞因子等）通过受体或离子通道的作用而激活或抑制细胞功能的过程。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：G蛋白耦联受体（G protein-linked receptor）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "G蛋白耦联受体",
        "指激活后作用于与之耦联的G蛋白，然后引发一系列以信号蛋白为主的级联反应而完成跨膜信号转导的一类受体，也称促代谢型受体。由形成7个跨膜区段的单条多肽链构成，故又称7次跨膜受体。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：微终板电位（miniature end-plate potential, MEPP）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "微终板电位",
        "指运动神经末梢单个囊泡的自发释放，所引起终板膜的微小去极化反应。终板电位（EPP）即为接头前膜一次动作电位所引发的大量囊泡同时释放ACh所产生的多个MEPP总和而成。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：完全强直收缩（complete tetanus）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "完全强直收缩",
        "指后一次收缩过程叠加在前一次收缩过程的收缩期所产生的收缩总和。在等长收缩条件下，完全强直收缩所产生的张力可达单收缩的3~4倍。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2/X 型选择题（统一映射为 a1-single），41 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1001",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与第二信使二酰甘油（DG）和肌醇三磷酸（IP3）的产生有关、且几乎全部分布在膜内层靠近胞浆的膜脂质成分是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "磷脂酰丝氨酸",
      "磷脂酰肌醇",
      "糖脂",
      "磷脂酰胆碱",
      "磷脂酰乙醇胺",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "磷脂酰肌醇",
        "磷脂酰肌醇含量最少、主要分布于膜的内层，与第二信使DG和IP3的产生有关；磷脂酰胆碱最多、主要在外层，磷脂酰丝氨酸和磷脂酰乙醇胺次之、主要在膜内层。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1002",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "葡萄糖或氨基酸逆浓度梯度跨膜转运（如小肠上皮细胞吸收葡萄糖）的方式属于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "原发性主动转运",
      "单纯扩散",
      "继发性主动转运",
      "经通道易化扩散",
      "经载体易化扩散",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "继发性主动转运",
        "葡萄糖或氨基酸逆浓度梯度（如进入小肠上皮细胞和近端肾小管上皮细胞）的转运属继发性主动转运，利用钠泵建立的Na+浓度梯度，通过Na+-葡萄糖同向转运体将葡萄糖逆浓度差带入胞内。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1003",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "单纯扩散、易化扩散和主动转运三种跨膜转运方式共同的共同点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "要消耗能量",
      "转运的物质都是小分子",
      "有饱和性",
      "顺浓度梯度",
      "需要膜蛋白帮助",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "转运的物质都是小分子",
        "单纯扩散、易化扩散和主动转运所转运的都是小分子物质，这是三者的共同特点；是否耗能、顺梯度、需膜蛋白或有饱和性各不相同。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1004",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于Na+泵（钠-钾泵）功能的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "活动增强导致细胞膜去极化",
      "转运等量的Na+和K+",
      "将细胞外Na+转运入细胞",
      "维持细胞内外的Na+、K+浓度梯度",
      "将细胞内K+转运出去",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "维持细胞内外的Na+、K+浓度梯度",
        "钠泵逆浓度差将细胞内3个Na+泵出胞外、将2个K+泵入胞内，其最重要的功能是维持细胞内高K+、细胞外高Na+的浓度梯度，这是细胞发生电活动等生理功能的基础。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1005",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "静息电位的实测值小于K+平衡电位的理论值，产生这一差异的主要原因是静息时细胞膜对",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["Ca2+", "Mg2+", "Na+", "H+", "Cl-"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Na+",
        "安静时细胞膜对Na+亦有一定通透性（为K+的1/100~1/50），少量Na+逸入膜内可部分抵消K+外流形成的膜内负电位，使静息电位实测值小于（负值小于）K+平衡电位的理论值。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1006",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "逐渐增加细胞外液中的K+浓度，静息电位将",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "先增大后减小",
      "逐渐减小",
      "不变",
      "逐渐增大",
      "先减小后增大",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "逐渐减小",
        "细胞外K+浓度升高时，K+平衡电位（Ek）减小，静息电位相应减小，即发生去极化，静息电位的负值减小。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1007",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "降低离体神经纤维浸浴液中的Na+浓度，则单根神经纤维动作电位的超射值将",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "不变",
      "先增后减",
      "增大",
      "减小",
      "先减后增",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "减小",
        "超射值与Na+平衡电位密切相关。降低细胞外Na+浓度使膜两侧Na+浓度差减小、Na+平衡电位下降，故动作电位的超射值减小。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1008",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可兴奋组织接受刺激后产生兴奋的共同表现形式是出现",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "收缩",
      "动作电位",
      "分泌",
      "局部电位",
      "收缩和分泌",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动作电位",
        "可兴奋细胞（神经细胞、肌细胞和腺细胞）受刺激后产生兴奋的共同表现形式是出现动作电位，动作电位是兴奋的客观标志。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1009",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "神经纤维动作电位去极化过程中，膜电位值超过0mV的部分称为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["极化", "超极化", "超射", "去极化", "复极化"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "超射",
        "膜内电位经去极化至零电位后进一步变为正值、使膜两侧电位极性与原来相反称为反极化，此时膜内电位高于零电位的部分即超射。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1010",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于神经纤维动作电位复极相（降支）形成机制的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "Cl-通道激活",
      "Na+通道失活",
      "Na+通道失活和K+通道激活",
      "K+通道和Cl-通道激活",
      "K+通道激活",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Na+通道失活和K+通道激活",
        "复极相的形成是Na+通道失活、钠电导下降，同时K+通道激活、K+外流增大的结果，使膜电位向静息电位的方向恢复。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1011",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "动作电位去极化期间，促进Na+内流的直接动力是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "钠泵作用",
      "ATP分解",
      "浓度梯度",
      "电-化学驱动力",
      "电位梯度",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "电-化学驱动力",
        "带电离子跨膜扩散需要电化学驱动力的推动，电位差和浓度差两个驱动力的代数和即为电化学驱动力，兴奋时Na+在增大的内向电化学驱动力作用下发生内流。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1012",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "神经细胞动作电位去极化的幅度（由静息电位至超射）接近于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "钾平衡电位与钠平衡电位之和",
      "钠平衡电位",
      "钠平衡电位与静息电位之差",
      "钾平衡电位",
      "钾平衡电位与静息电位之差",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "钠平衡电位与静息电位之差",
        "动作电位去极化幅度（静息电位到超射最大值的差）接近Na+平衡电位减去静息电位的差值，因超射值接近Na+平衡电位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1013",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "衡量组织兴奋性高低的指标是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "组织反应强度",
      "刺激持续时间",
      "动作电位幅度",
      "阈值",
      "动作电位频率",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阈值",
        "阈值愈小，兴奋性愈高；阈值愈大，兴奋性愈低。故常用阈值（阈强度）作为衡量组织兴奋性高低的指标。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1014",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "神经纤维的阈电位是指",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "K+通道开始关闭的膜电位临界值",
      "Na+通道大量开放的膜电位临界值",
      "K+通道大量开放的膜电位临界值",
      "Na+通道开始关闭的膜电位临界值",
      "K+通道少量开放的膜电位值",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Na+通道大量开放的膜电位临界值",
        "阈电位是能触发动作电位发生的膜电位临界值，即刚好能引起膜去极化与Na+电导之间形成正反馈、Na+通道大量开放的膜电位水平。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1015",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "即使给予非常强的刺激，神经元也不能产生动作电位的时期是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "超常期",
      "低常期",
      "相对不应期",
      "绝对不应期和相对不应期",
      "绝对不应期",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "绝对不应期",
        "绝对不应期时钠通道处于激活及随后的失活状态，无论施加多强的刺激也不能使细胞再次兴奋，此期基本与锋电位持续时间相当。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1016",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "维甲酸为维生素A的代谢产物，脂溶性较高，经单纯扩散通过细胞膜后与核受体结合发挥疗效。此类脂溶性物质在通过细胞膜时，对其跨膜扩散能力影响最大的因素是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["空间结构", "脂溶性", "分子量", "所带电荷", "分子大小"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脂溶性",
        "单纯扩散是脂溶性物质顺浓度梯度透过脂质分子间隙的扩散，物质能否以单纯扩散方式跨膜以及扩散能力，主要与物质本身的脂溶性强弱密切相关。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1017",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "腹泻患者通常口服糖盐水（含葡萄糖和NaCl）而不口服纯生理盐水来防止脱水，其主要原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "服用含NaCl和葡萄糖的糖盐水能有效减少粪便形成",
      "葡萄糖通过Na+-葡萄糖继发性主动转运促进小肠上皮细胞顶端膜Na+和水的吸收",
      "服用糖盐水可同时补充NaCl和能量物质",
      "NaCl和葡萄糖混合液胃排空的速率大于单纯盐溶液",
      "葡萄糖能够促进小肠上皮细胞顶端膜Na+和Cl-的协同转运",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "葡萄糖通过Na+-葡萄糖继发性主动转运促进小肠上皮细胞顶端膜Na+和水的吸收",
        "葡萄糖经Na+-葡萄糖同向转运体与Na+一起进入小肠上皮细胞，可促进Na+和水的吸收，故口服糖盐水比纯生理盐水更有效地补充水分和电解质，防止脱水。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1018",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "葡萄糖在小肠黏膜上皮处的吸收是通过继发性主动转运实现的，抑制下列哪种功能活动可以影响葡萄糖的吸收",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["钙泵", "钠氢交换体", "质子泵", "钠泵", "钠钙交换体"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "钠泵",
        "葡萄糖在肠道的继发性主动转运依赖钠泵建立的Na+浓度梯度。抑制钠泵可使膜两侧Na+浓度梯度减小，直接妨碍Na+-葡萄糖同向转运，从而影响葡萄糖的吸收。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1019",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "用哇巴因抑制钠泵活动后，细胞的静息电位将",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "基本不变",
      "先减小后增大",
      "逐渐增大",
      "逐渐减小",
      "先增大后减小",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "逐渐减小",
        "哇巴因抑制钠泵后，Na+泵生电作用消失使膜内负电位减小，同时胞内Na+蓄积、K+浓度差逐渐缩小，K+平衡电位下降，静息电位逐渐减小。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1020",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者进食河豚后相继出现口唇、舌尖、指端麻木、全身麻木、四肢无力、腱反射消失，诊断为河豚毒素（TTX）中毒。该患者出现神经麻痹症状的机制是TTX",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "阻断K+通道开放，不能产生动作电位",
      "阻断Na+通道开放，不能产生动作电位",
      "阻断Na+-K+泵的活动，影响了动作电位的产生",
      "阻断Cl-通道开放，不能产生静息电位",
      "阻断Na+通道开放，动作电位不能复极化",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阻断Na+通道开放，不能产生动作电位",
        "TTX特异性地阻断电压门控Na+通道，使去极化时Na+不能内流、不能产生动作电位，从而使神经传导和肌肉收缩障碍，出现全身麻木、肌肉软瘫和腱反射消失等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1021",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列生理过程中，属于经通道易化扩散完成的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "递质囊泡的出胞",
      "受体介导的入胞",
      "氨基酸的Na+同向转运",
      "静息电位的产生（K+外流）",
      "磷酸化时钠泵的转运",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "静息电位的产生（K+外流）",
        "静息电位的产生主要依赖K+经非门控K+漏通道的易化扩散，属经通道易化扩散。原书X型题答案还包括动作电位去极相（Na+内流）等，本节按规约取静息电位映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1022",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于经载体易化扩散特点的表述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "逆电-化学梯度进行",
      "有竞争性抑制",
      "有结构特异性",
      "有饱和现象",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "逆电-化学梯度进行",
        "经载体易化扩散是顺浓度梯度的被动转运，故“逆电-化学梯度进行”为错误表述；结构特异性、饱和现象和竞争性抑制才是其特点。原书为X型多选，本题按规约取易化扩散特点映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1023",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于钠泵（Na+-K+泵）生理作用的叙述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "维持细胞内正常的渗透压",
      "钠泵活动与静息电位的维持无关",
      "建立离子势能储备",
      "逆浓度差将胞内Na+移到胞外、同时将胞外K+移到胞内",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "钠泵活动与静息电位的维持无关",
        "钠泵通过建立膜两侧Na+、K+浓度梯度正是静息电位形成的基础，其生电效应还与静息电位维持有关，故“与静息电位的维持无关”为错误叙述。原书X型题取此错误项映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1024",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于局部兴奋特征的叙述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "可产生时间总和",
      "具有'全或无'特征",
      "具有电紧张电位的特征",
      "可产生空间总和",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "具有'全或无'特征",
        "局部兴奋是等级性电位，不具有全或无特征；其具有电紧张电位特征、可发生时间总和和空间总和。原书X型题取此错误项映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1025",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "记录静息电位和动作电位时，必需的操作是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "增大刺激强度可增加去极化的速度",
      "用金属电极置于细胞外即可记录",
      "增大刺激强度可增加去极化幅度",
      "须将微电极插入细胞内",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "须将微电极插入细胞内",
        "静息电位和动作电位是细胞膜内外的电位差，必须将微电极插入细胞内才能记录到。增大刺激强度只能决定是否触发动作电位，不能增加其幅度或速度。原书X型题按规约取这一要点映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1026",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可以通过幅度变化和总和效应在细胞上实现信号整合的局部电活动是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["静息电位", "锋电位", "突触后电位", "动作电位"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "突触后电位",
        "突触后电位为局部电位，具有等级性和可总和的特点，可通过幅度变化和总和效应实现信号整合；动作电位具有全或无特征，不符合。原书X型题答案还包括终板电位，本节按规约取突触后电位映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1027",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "cAMP作为第二信使，其主要作用是激活",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["PKC", "PLC", "PKA", "AC", "PKG"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "PKA",
        "cAMP主要通过激活cAMP依赖的蛋白激酶A（PKA），将ATP的磷酸根转移到底物蛋白的丝氨酸和苏氨酸残基上（磷酸化反应），进而调节细胞功能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1028",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞内能使蛋白质发生磷酸化的酶是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "磷脂酶C",
      "乙酰胆碱酯酶",
      "磷酸二酯酶",
      "蛋白激酶",
      "蛋白磷酸酶",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "蛋白激酶",
        "蛋白激酶是一类将ATP分子上的磷酸基团转移到底物蛋白而产生蛋白质磷酸化的酶类，被磷酸化的蛋白质触发级联反应或直接改变功能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1029",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "生长因子一般作用于生长因子受体而激活的信号转导通路是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "离子通道型受体介导的信号转导通路",
      "核受体介导的信号转导通路",
      "酶联型受体介导的信号转导通路",
      "G蛋白耦联受体介导的信号转导通路",
      "招募型受体介导的信号转导通路",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "酶联型受体介导的信号转导通路",
        "生长因子作用于其受体（如酪氨酸激酶受体）通过蛋白磷酸化产生效应，属酶联型受体介导的信号转导通路。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1030",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与细胞因子跨膜信号转导有关的受体主要是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "促代谢型受体",
      "核受体",
      "促离子型受体",
      "招募型受体",
      "酶联型受体",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "招募型受体",
        "细胞因子主要经JAK-STAT等通路介导信号转导，其受体属招募型受体（单个跨膜、胞内域无酶活性，胞外域与配体结合后招募激酶或转接蛋白），是本题最佳答案；本题原为难题，备选答案以招募型受体最恰当。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1031",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "研究发现，糖皮质激素可以作用于神经元的细胞膜而影响其功能，可见类固醇激素调控靶细胞功能的机制是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "是热休克蛋白机制",
      "仅有核受体机制",
      "主要是膜受体机制",
      "主要是核受体机制，也有膜受体机制",
      "主要是膜受体机制，也有核受体机制",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "主要是核受体机制，也有膜受体机制",
        "类固醇激素主要通过核受体调节靶基因转录发挥缓慢的“基因组效应”，有些类固醇激素还能激活膜受体产生快速的“非基因组效应”，故“主要是核受体机制，也有膜受体机制”（原书B项）为最佳答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1032",
    order: 40,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列属于细胞信号转导途径的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "三羧酸循环",
      "脂肪酸β-氧化",
      "糖酵解途径",
      "核受体介导的信号转导通路",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "核受体介导的信号转导通路",
        "细胞的信号转导通路包括核受体、离子通道型、酶联型、招募型和G蛋白耦联受体介导的信号转导通路；代谢途径不属于信号转导。原书X型题按规约取核受体通路映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1033",
    order: 41,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "横纹肌神经-肌接头处传递兴奋的神经递质是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["去甲肾上腺素", "多巴胺", "乙酰胆碱", "肾上腺素", "5-羟色胺"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "乙酰胆碱（ACh）",
        "骨骼肌神经-肌接头处的接头前膜释放的递质是乙酰胆碱，ACh激活终板膜上的N2型ACh受体阳离子通道而引发终板电位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1034",
    order: 42,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "骨骼肌收缩和舒张的基本单位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肌原纤维",
      "横桥",
      "肌丝",
      "肌纤维",
      "肌节",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌节",
        "相邻两条Z线之间的区段称为肌节，是肌肉收缩和舒张的基本单位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1035",
    order: 43,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在横纹肌，引起肌丝滑行的始动步骤是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "横桥ATP酶活性增高，使ATP分解",
      "肌浆中Ca2+与肌钙蛋白结合",
      "钙泵活动增强",
      "横桥与肌动蛋白结合",
      "肌凝蛋白与肌动蛋白结合",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌浆中Ca2+与肌钙蛋白结合",
        "肌浆中升高的Ca2+与肌钙蛋白结合，使原肌球蛋白移位、暴露肌动蛋白上的横桥结合位点，从而启动肌丝滑行，故肌浆Ca2+与肌钙蛋白结合是始动步骤。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1036",
    order: 44,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肌肉收缩时张力保持不变而只发生肌肉缩短，称作",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "单收缩",
      "等长收缩",
      "完全强直收缩",
      "等张收缩",
      "不完全强直收缩",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "等张收缩",
        "等张收缩指肌肉收缩时张力保持不变而只发生肌肉缩短的收缩形式；等长收缩则指长度不变而只有张力增加。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1037",
    order: 45,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "能回收骨骼肌细胞胞质中Ca2+的钙泵主要分布在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肌细胞核膜",
      "终池膜",
      "肌膜",
      "纵行肌质网膜",
      "横管膜",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "纵行肌质网膜",
        "纵行肌质网膜上有钙泵，可逆浓度梯度将胞质中的Ca2+转运至肌质网（SR）内，从而降低胞质Ca2+浓度、引起肌肉舒张。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1038",
    order: 46,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在骨骼肌收缩的张力-速度关系曲线检测实验中，为保证有效、客观地检测后负荷对收缩的影响，前负荷应",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "为最大值",
      "小于后负荷值",
      "为某一数值不变",
      "等于后负荷值",
      "为0",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "为某一数值不变",
        "张力-速度关系曲线通过测定不同后负荷（张力）时肌肉缩短的速度作图得到，前负荷是另一影响因素，实验中需固定不变，且不应为零，这样才能客观检测后负荷的影响。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1039",
    order: 47,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有机磷农药中毒时可导致",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胆碱酯酶活性升高",
      "ACh释放量减少",
      "ACh释放量减少且胆碱酯酶活性降低",
      "ACh释放量增加",
      "胆碱酯酶活性降低",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胆碱酯酶活性降低",
        "有机磷农药使胆碱酯酶被磷酸化而丧失活性（即胆碱酯酶活性降低），ACh不能及时被分解而在接头间隙蓄积，从而引起中毒症状。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1040",
    order: 48,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "N2型ACh受体阳离子通道激活后可允许Na+、K+和Ca2+跨膜移动，但终板电位（EPP）仍是去极化电位，其原因在于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "Ca2+内流为主",
      "K+内流为主",
      "在静息状态下，Ca2+内向驱动力大于K+外向驱动力",
      "在静息状态下，Na+内向驱动力等于K+外向驱动力",
      "Na+内流为主",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Na+内流为主",
        "终板膜去极化是由Na+内流和K+外流等跨膜离子电流共同产生，但以Na+内流为主，因此EPP表现为去极化电位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-a1041",
    order: 49,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "机体增强骨骼肌收缩程度的主要途径是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "每个肌细胞动作电位幅度增大",
      "增大单个肌原纤维的横桥数",
      "参与收缩的运动单位数目增加",
      "每次肌细胞收缩幅度增加",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "参与收缩的运动单位数目增加",
        "骨骼肌为随意肌，运动神经元发放动作电位的数目增加可使参与收缩的运动单位数目增加，产生多运动单位总和以增强收缩强度。原书X型题答案还包括收缩频率加快（频率总和），本题按规约取运动单位总和映射为单选。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），7 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-physiology-ch2-cell-basic-functions-short001",
    order: 50,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "单纯扩散和易化扩散有何异同？请举例说明。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单纯扩散与易化扩散的异同",
        "相同点：单纯扩散和易化扩散都属于被动转运，本身都不需要消耗能量，都是物质分子顺浓度梯度和（或）电位梯度跨膜转运的过程。不同点：单纯扩散是一种简单的物理过程，没有生物学转运机制参与，转运的物质是脂溶性物质或少数不带电荷的极性小分子物质，如CO2、O2、乙醇、尿素、甘油和水等；易化扩散转运的是非脂溶性的小分子物质或带电离子，需要膜结构中特殊蛋白质的帮助。根据所借助的蛋白质不同，易化扩散分为经通道型（转运离子，如电压门控Na+通道、终板膜上N型ACh门控通道）和经载体型（底物需与载体结合、借助载体构象改变跨膜，如一般组织细胞膜上的葡萄糖载体和氨基酸载体）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-short002",
    order: 51,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "经载体和经通道易化扩散有何异同？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "经载体与经通道易化扩散的异同",
        "相同点：①都是顺浓度差和（或）电位差进行的被动转运，不消耗ATP；②均需膜蛋白协助。不同点：①膜蛋白种类不同，经通道为通道蛋白，经载体为载体蛋白；②转运速率不同，经通道快（约106~108/s），经载体慢（约103~105/s）且一般有饱和现象；③选择性差异，经通道选择性相对较差，经载体选择性高；④门控特性，经通道大多数有门控特性（电压、化学、机械门控），经载体无。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-short003",
    order: 52,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "原发性主动转运和继发性主动转运有何异同？请举例说明。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "原发性与继发性主动转运的异同",
        "相同点：两者都是借助膜上的载体蛋白、逆着电-化学梯度将底物进行跨膜转运，都要消耗能量。不同点：原发性主动转运的载体蛋白（泵蛋白）本质是ATP酶，可将ATP结合并水解，产生的能量直接用于底物的主动转运，如Na+-K+泵、Ca2+泵和质子泵等；继发性主动转运的载体（共转运体）本身不是ATP酶，其主动转运所需能量不是直接来自ATP水解，而是来自原发性主动转运所形成的离子浓度梯度（如钠泵形成的膜两侧Na+浓度差），当共转运体在离子浓度差推动下将结合的离子顺浓度梯度转运时，同时将结合的其他底物逆浓度差转运，如Na+-葡萄糖同向转运、Na+-Ca2+交换、Na+-H+交换等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-short004",
    order: 53,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "葡萄糖跨膜转运的方式有哪些？请举例说明。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "葡萄糖的跨膜转运方式",
        "主要有以下两种方式：①载体介导的易化扩散：胞外葡萄糖顺浓度梯度进入细胞内，如一般组织细胞膜上的葡萄糖载体介导葡萄糖进入细胞；②继发性主动转运：葡萄糖在小肠黏膜上皮细胞的吸收和在近端肾小管上皮细胞的重吸收，都是通过Na+-葡萄糖同向转运体实现的，其中Na+顺浓度梯度进入细胞，同时将葡萄糖逆浓度梯度转运至胞内，属继发性主动转运。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-short005",
    order: 54,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述跨膜信号转导的主要方式。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "跨膜信号转导的主要方式",
        "根据介导的配体和受体不同，跨膜信号转导的主要方式有两类：一类是水溶性配体或物理信号作用于膜受体而产生效应，涉及由离子通道型受体、G蛋白耦联受体、酶联型受体和招募型受体介导的信号转导；另一类是脂溶性配体直接与胞质受体或核受体结合，通过影响基因表达而产生效应。各通路特点：①离子通道型受体：由配体结合部位和离子通道组成，受化学信号分子、电信号、机械信号激活后产生跨膜离子电流而改变细胞功能；②G蛋白耦联受体：激活后作用于与之耦联的G蛋白，引发以信号蛋白为主的级联反应，涉及G蛋白耦联受体、G蛋白、G蛋白效应器、蛋白激酶及第二信使等，可调控酶、通道、转录因子的活性；③酶联型受体：自身具有酶活性或能与酶结合，胞外域结合配体、胞内域具酶活性或含酶结合位点（单个跨膜），通过蛋白磷酸化产生效应；④招募型受体：单个跨膜受体的胞内域无酶活性，激活后胞内域在胞质侧招募激酶或转接蛋白，激活不涉及经典第二信使的下游通路；⑤核受体：实质上是激素调控特定蛋白质转录的一大类转录调节因子（类固醇激素受体、VitD3受体、甲状腺激素受体和维甲酸受体等），被激素结合活化后与靶基因DNA中的激素反应元件（HRE）结合调控转录。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-short006",
    order: 55,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "影响横纹肌收缩效能的因素有哪些？各有何影响？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "影响横纹肌收缩效能的因素",
        "影响横纹肌收缩效能的因素有负荷、肌肉收缩能力及收缩的总和等。①前负荷：指肌肉在收缩前所承受的负荷，影响肌肉的初长度。在一定范围内，初长度增大则收缩张力增大；在最适初长度时，有效发挥作用的横桥数最多，产生最大的收缩张力。②后负荷：指肌肉在收缩后所承受的负荷。在一定范围内，后负荷越大，收缩张力增加，但肌肉缩短的程度和速度减小；后负荷为零时肌肉缩短速度达最大（Vmax），后负荷增加到使肌肉不能缩短时，肌肉产生的张力达最大收缩张力（P0）。③肌肉收缩能力：指与前负荷和后负荷均无关的能影响肌肉收缩效能的肌肉内在特性（如胞质Ca2+浓度变化、横桥ATP酶活性、代谢水平、功能蛋白表达等），收缩能力增强则收缩效能提高。④收缩的总和：参与同步收缩的运动单位数目增加则收缩增强（多运动单位总和）；提高收缩频率产生频率总和，等长条件下完全强直收缩张力可达单收缩的3~4倍。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-short007",
    order: 56,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述横纹肌兴奋-收缩耦联的概念和基本步骤。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "兴奋-收缩耦联的概念与基本步骤",
        "兴奋-收缩耦联是将横纹肌细胞产生动作电位的电兴奋过程与肌丝滑行的机械收缩联系起来的中介机制或过程。耦联因子是Ca2+，结构基础在骨骼肌为三联管结构、在心肌为二联管结构。基本步骤：①动作电位沿T管膜传导，激活T管膜和肌膜中的L型钙通道；②膜的去极化在骨骼肌通过构象变化触发钙释放机制、在心肌通过钙诱导钙释放机制，引起终池内Ca2+的释放；③胞质内Ca2+浓度升高，促使Ca2+与肌钙蛋白结合而触发肌肉收缩；④胞质内Ca2+浓度升高激活纵行肌质网膜中的钙泵，将胞质中的Ca2+回收入肌质网而降低胞质Ca2+浓度，引起肌肉舒张。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 思考题（case），2 道 */
const caseItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-physiology-ch2-cell-basic-functions-case001",
    order: 57,
    knowledgePointId: kp,
    questionKind: "case",
    status: "available",
    prompt: "细胞外液中的K+浓度对细胞的静息电位有显著影响。已知哺乳动物骨骼肌细胞在37℃下胞外Na+145mM、胞内Na+12mM，胞外K+4mM、胞内K+155mM；按Nernst方程Ex=61.5lg([X+]o/[X+]i)(mV)计算：(1)分别算出Na+平衡电位和K+平衡电位（保留整数），实际测得的静息电位（-90mV）更接近哪种离子的平衡电位？(2)当细胞外液K+浓度由4mM增加到5mM时，K+平衡电位将改变为多少？此时细胞静息电位将如何变化，是发生去极化还是超极化？细胞的兴奋性将如何改变？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Nernst方程计算与静息电位",
        "答：(1)由Nernst方程计算所得：Na+平衡电位约为+67mV，K+平衡电位约为-98mV。显然，实际测得的静息电位（-90mV）更接近K+平衡电位，说明静息电位主要由K+外流形成。(2)当细胞外液K+浓度由4mM增加到5mM时，K+平衡电位将减小（由-98mV变为约-92mV）。此时细胞的静息电位将随K+平衡电位下降而减小，即膜发生去极化。当膜发生轻度去极化时，膜电位距离阈电位水平更接近，故细胞的兴奋性将会增大。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-case002",
    order: 58,
    knowledgePointId: kp,
    questionKind: "case",
    status: "available",
    prompt: "患者，男性，40岁，颈椎粉碎性骨折致完全性截瘫后47天，在静脉复合麻醉下行椎板减压术。术前血压120/70mmHg、脉搏84次/分、血钾4.03mmol/L。静注琥珀酰胆碱（作用与ACh类似，但不易被胆碱酯酶分解）进行麻醉诱导后，患者四肢曾有一过性“强直”样痉挛，随后血压降至50/0mmHg、脉搏降至14次/分，血钾升至10.15mmol/L。问题：(1)琥珀酰胆碱为什么能产生肌松作用？(2)琥珀酰胆碱为什么可引起高血钾？(3)琥珀酰胆碱过量时能否用胆碱酯酶抑制剂来处理？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "琥珀酰胆碱的肌松与高钾机制",
        "答：(1)琥珀酰胆碱属于去极化型肌松剂，可持续激活N2型ACh受体阳离子通道，引起终板膜持续明显去极化，进而使Na+通道失活、肌细胞兴奋性降低而不能产生动作电位，最终阻断神经-肌接头的兴奋传递，导致肌肉松弛。(2)本例为完全性截瘫后47天的患者，其骨骼肌失去运动神经控制，肌细胞N2型ACh受体阳离子通道代偿性增加（尤其接头外肌膜），对去极化型肌松剂呈高敏感性。使用琥珀酰胆碱后受体被大量激活，在持续去极化状态下使细胞内K+大量扩散出细胞，导致高血钾。(3)不能。胆碱酯酶抑制剂通过抑制接头处乙酰胆碱酯酶、减少ACh消除而使ACh蓄积，只会进一步激活N2型ACh受体阳离子通道、加重琥珀酰胆碱引起的持续性去极化作用，故琥珀酰胆碱过量时不能用胆碱酯酶抑制剂处理。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，3 组 × 8 成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-physiology-ch2-cell-basic-functions-b001",
    order: 59,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["去极化", "复极化", "超极化", "极化", "反极化"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-physiology-ch2-cell-basic-functions-b001m1",
        order: 59,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "安静状态下细胞膜两侧外正内负的状态，称为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "极化",
            "安静情况下细胞膜电位所处的外正内负的稳定状态称为极化。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch2-cell-basic-functions-b001m2",
        order: 60,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "在静息电位基础上膜内电位负值增大，称为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "超极化",
            "静息电位增大（如细胞内电位由-70mV变为-90mV）的过程或状态称为超极化，表示膜极化状态增强。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch2-cell-basic-functions-b001m3",
        order: 61,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "在静息电位基础上膜内电位负值减小，称为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "去极化",
            "静息电位减小（如细胞内电位由-70mV变为-50mV）的过程或状态称为去极化，表示膜极化状态减弱。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-b002",
    order: 62,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["Na+", "K+", "Ca2+", "Cl-", "H+"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-physiology-ch2-cell-basic-functions-b002m1",
        order: 62,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "神经细胞静息电位的形成主要与以上哪种离子有关",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "K+",
            "静息电位主要是由K+外流形成的，实测值接近K+平衡电位。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch2-cell-basic-functions-b002m2",
        order: 63,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "神经细胞动作电位超射值与以上哪种离子的平衡电位最为接近",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "Na+",
            "动作电位超射值接近Na+平衡电位，因去极化时相主要由Na+内流形成。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-physiology-ch2-cell-basic-functions-b003",
    order: 64,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "肌凝蛋白",
      "肌动蛋白",
      "肌凝蛋白和肌动蛋白",
      "肌钙蛋白",
      "肌钙蛋白和原肌凝蛋白",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-physiology-ch2-cell-basic-functions-b003m1",
        order: 64,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "骨骼肌细胞中可作为Ca2+受体的蛋白是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肌钙蛋白",
            "肌钙蛋白（肌原蛋白）与Ca2+结合而改变构象，触发原肌球蛋白移位、暴露横桥结合位点。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch2-cell-basic-functions-b003m2",
        order: 65,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "调节蛋白是指",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肌钙蛋白和原肌凝蛋白",
            "原肌球蛋白（原肌凝蛋白）和肌转蛋白（肌钙蛋白）不直接参与肌肉收缩，而是调控收缩蛋白间的相互作用，故称为调节蛋白。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-physiology-ch2-cell-basic-functions-b003m3",
        order: 66,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "肌丝滑行时，横桥必须与之结合的蛋白是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肌动蛋白",
            "肌球蛋白横桥在Ca2+触发下与肌动蛋白（细肌丝主干蛋白）结合，产生“棘齿作用”拖动细分丝向M线方向滑行。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
  ...caseItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];