import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 神经病学学习指导与习题集（第3版）— 第4章 神经系统疾病的病史采集和体格检查 题库提取（等比取样）
 * 来源：《神经病学学习指导与习题集》第3版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 选择题（a1-single）：15 题（含 A2 病例题 0 题、A3/A4 病例串题 0 题）
 * - 问答题（short-answer）：10 题（含简答 10 题、论述 0 题）
 * - 病例分析题（case）：0 题
 * - B1 配伍题：2 组、共 9 个成员
 * - 独立记分题合计：34 题（须等于本文件预算 34）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含 A1 型 65、B1 型 7 组 30 成员、简答题 49、论述题 9，无 A2/A3/A4
 *   与病例分析题。本文件按 34 道预算在原书顺序内取材：A1 取第 1~15 题、简答取第 1~10 题，
 *   B1 取前两组（1~4、5~9）完整组。正确项逐一对齐章末参考答案键号。OCR 错字已按神经病学
 *   医学语义恢复（如 眼险→眼睑、祝束→视束、Kerig→Kernig、两点辦别觉→两点辨别觉、
 *   非体类→非甾体类、Horer→Horner、冀状肩胛→翼状肩胛、力主→为主 等），数值与分子标记
 *   （L2~4、S1~2、Rinne、Weber、Babinski、Glasgow 等）保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "neurology-ch04-history-taking-and-physical-examination";
const locatorBase =
  "《神经病学学习指导与习题集》第3版 第4章 神经系统疾病的病史采集和体格检查 习题（核对PDF 第61–84页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** A1 型选择题（统一映射为 a1-single），15 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于神经系统临床检查表述不正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "随着科学技术的发展，辅助检查手段已经可以替代详细的病史和体格检查",
      "神经系统的临床检查包括病史的采集、神经系统体格检查以及各种辅助检查",
      "病史采集和体格检查是神经系统疾病正确诊断的关键",
      "病史采集可对疾病的定位和定性/病因诊断提供有价值的线索",
      "某些神经系统疾病，病史可能是诊断的唯一线索和依据",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "随着科学技术的发展，辅助检查手段已经可以替代详细的病史和体格检查",
        "任何辅助检查手段都有局限性，辅助检查的阳性结果只有和患者的临床表现相符时，才能认为与疾病有关；辅助检查不能替代详细的病史和体格检查。原书 A1 答案第 1 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "脑干反射不包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "睫脊反射",
      "角膜反射",
      "跖反射",
      "头眼反射",
      "眼前庭反射",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "跖反射",
        "脑干反射包括睫脊反射、角膜反射和反射性眼球运动（头眼反射、眼前庭反射）；跖反射属于浅反射，不属于脑干反射。原书 A1 答案第 2 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "锥体束损害的体征是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "Kernig 征",
      "Lasegue 征",
      "Romberg 征",
      "Brudzinski 征",
      "Babinski 征",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Babinski 征",
        "Babinski 征是经典的病理反射，提示锥体束受损；Kernig 征和 Brudzinski 征属于脑膜刺激征，Lasegue 征提示神经根受牵拉，Romberg 征用于检查深感觉性共济失调。原书 A1 答案第 3 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "膝腱反射中枢在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "T12~L2",
      "L1~3",
      "L2~4",
      "L5~S1",
      "L5~S2",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "L2~4",
        "膝腱反射（膝反射）由 L2~4 节段支配，经股神经传导。原书 A1 答案第 4 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列眼部检查不正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "有无眼球运动受限及复视",
      "有无眼震及眼震的幅度",
      "眼部外观，如上睑下垂、眼裂大小",
      "瞳孔大小及对光反射",
      "眼压测定",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "眼压测定",
        "神经系统眼部检查主要观察眼球运动、眼震、眼睑外观、瞳孔大小及对光反射等；眼压测定属于眼科检查，不属于神经系统常规眼部检查。原书 A1 答案第 5 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于脑神经检查表述不恰当的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "手动法检查视野时患者与检查者相距 100cm",
      "手动法检查视野时患者不应注视检查者的手",
      "检查眼底时须先散瞳，可观察清楚",
      "检查角膜反射用棉签轻触角膜周边部",
      "检查胸锁乳突肌时令患者向对侧转头",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "检查眼底时须先散瞳，可观察清楚",
        "神经系统常规眼底检查一般不须先散瞳（散瞳会影响瞳孔对光反射的观察，并存在诱发急性闭角型青光眼的风险）；手动法检查视野时患者与检查者相距约 1m，患者注视检查者的眼睛而非其手。原书 A1 答案第 6 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "嗅觉检查时不宜使用",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "香烟",
      "香皂",
      "醋酸",
      "牙膏",
      "香油",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "醋酸",
        "醋酸、乙醇和甲醛溶液等刺激性物质不宜被用于嗅觉检查；常用香烟、香皂、牙膏、香油等无刺激性气味的物品。原书 A1 答案第 7 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列面神经检查表述正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "周围性面神经麻痹时同侧所有表情肌瘫痪",
      "中枢性面神经麻痹时对侧所有表情肌瘫痪",
      "检查面神经包括舌后1/3味觉",
      "面神经麻痹时面部感觉缺失",
      "周围性面瘫时对侧角膜反射消失",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "周围性面神经麻痹时同侧所有表情肌瘫痪",
        "周围性面瘫导致眼裂上、下的面部表情肌均瘫痪；中枢性面瘫只造成眼裂以下的面肌瘫痪。面神经支配舌前2/3味觉，不支配面部感觉。原书 A1 答案第 8 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列舌咽、迷走神经检查不正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "双侧软腭抬举是否一致，悬雍垂是否偏斜",
      "两侧软腭或咽后壁感觉",
      "舌前1/3味觉",
      "咽反射",
      "眼心反射及颈动脉窦反射",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "舌前1/3味觉",
        "舌咽神经支配舌后1/3味觉，舌前2/3味觉由面神经支配；舌前1/3味觉不属于舌咽、迷走神经检查内容。原书 A1 答案第 9 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "属于面神经检查的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "面部感觉",
      "咀嚼运动",
      "舌后1/3味觉",
      "舌前2/3味觉",
      "下颌反射",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "舌前2/3味觉",
        "面神经为混合神经，主要支配面部表情肌运动及舌前2/3味觉纤维；面部感觉、咀嚼运动、下颌反射属于三叉神经检查。原书 A1 答案第 10 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不属于三叉神经检查的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "角膜反射",
      "下颌反射",
      "咀嚼肌运动",
      "面部感觉",
      "表情肌运动",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "表情肌运动",
        "三叉神经检查包括面部感觉、咀嚼肌运动、角膜反射和下颌反射；表情肌运动由面神经支配，不属于三叉神经检查。原书 A1 答案第 11 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列表述不正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "一侧舌咽、迷走神经下运动神经元损害可引起真性延髓麻痹",
      "一侧或双侧舌咽、迷走神经上运动神经元损害可引起真性延髓麻痹",
      "双侧皮质脑干束受损产生假性延髓麻痹",
      "假性延髓麻痹时咽反射存在甚至亢进",
      "迷走神经受刺激时可出现咽肌、舌肌和胃痉挛",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "一侧或双侧舌咽、迷走神经上运动神经元损害可引起真性延髓麻痹",
        "真性延髓麻痹是一侧或双侧舌咽、迷走神经下运动神经元损害引起唇、腭、舌和声带麻痹或肌肉本身无力所致；上运动神经元（双侧皮质脑干束）损害产生假性延髓麻痹。原书 A1 答案第 12 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列不属于轻瘫试验的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "双上肢平举，手心向下，轻瘫侧上肢逐渐下垂和旋前",
      "双上肢平举，手心向下，轻瘫侧小指常轻度外展",
      "仰卧，下肢伸直，两膝并拢，检查者分开之，轻瘫侧较易移动",
      "仰卧位双腿伸直，轻瘫侧下肢常呈外旋位",
      "俯卧位，双膝、髋关节均屈曲成直角，轻瘫侧小腿逐渐下落",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "仰卧，下肢伸直，两膝并拢，检查者分开之，轻瘫侧较易移动",
        "轻瘫试验包括上肢平伸试验、Barre 分指试验、小指征、Jackson 征和下肢轻瘫试验等；选项 C 所述检查方法不属于轻瘫试验。原书 A1 答案第 13 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "闭目难立征（Romberg 征）阳性提示",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "前庭性共济失调",
      "小脑性共济失调",
      "感觉性共济失调",
      "额叶性共济失调",
      "基底节病变",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "感觉性共济失调",
        "闭目难立征（Romberg 征）阳性提示关节位置觉丧失的深感觉障碍，见于感觉性共济失调（后索病变）。原书 A1 答案第 14 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-a1015",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不属于运动系统检查的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肌力",
      "肌张力",
      "肌容积",
      "姿势及步态",
      "发汗试验",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "发汗试验",
        "运动系统检查包括肌容积、肌张力、肌力、不自主运动、共济运动、姿势和步态等；发汗试验属于自主神经检查。原书 A1 答案第 15 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（统一映射为 short-answer），10 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-short001",
    order: 16,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "视神经的检查包括哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "视神经的检查包括视力、视野和眼底检查。视力代表视网膜黄斑中心凹处的视敏度，分为远视力和近视力；视野是双眼向前方固视不动时所能看到的空间范围，分为周边视野和中心视野；眼底检查包括视乳头的形状、大小、色泽、边缘以及视网膜和血管情况。",
        "视神经属于中枢神经，其检查主要包括视力、视野和眼底三部分。原书简答题第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-short002",
    order: 17,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述三叉神经运动支支配的肌肉。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "三叉神经运动支支配咀嚼肌，即咬肌、颞肌、翼内肌和翼外肌。",
        "三叉神经为混合神经，运动支支配咀嚼肌。原书简答题第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-short003",
    order: 18,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述三叉神经运动支损害表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "三叉神经运动支损害表现为咀嚼肌无力和肌萎缩，张口时下颌向病侧偏斜。",
        "中枢性三叉神经损害时下颌偏向病灶对侧，周围性（核性及神经本身）损害时下颌偏向病灶同侧。原书简答题第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-short004",
    order: 19,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述传导性耳聋与感音性耳聋的鉴别试验及如何鉴别。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "传导性耳聋与感音性耳聋应用 Rinne 试验和 Weber 试验鉴别。正常情况下气导能听到的时间长于骨导，即气导>骨导，称为 Rinne 试验阳性；传导性耳聋时骨导>气导，称为 Rinne 试验阴性；感音性耳聋时虽气导>骨导，但两者时间均缩短。Weber 试验是将振动的音叉置于患者额顶正中，比较双侧骨导，正常时两耳感受到的声音相同，传导性耳聋时患侧较响（Weber 试验阳性），感音性耳聋时健侧较响（Weber 试验阴性）。",
        "Rinne 试验比较同侧气导与骨导，Weber 试验比较双侧骨导，二者结合可鉴别传导性与感音性耳聋。原书简答题第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-short005",
    order: 20,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "什么是肌张力？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌张力是肌肉松弛状态的肌肉紧张度和被动运动时遇到的阻力。",
        "肌张力检查时嘱患者肌肉放松，触摸感受肌肉硬度，并被动屈伸肢体感知阻力。原书简答题第 5 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-short006",
    order: 21,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "肌张力减低见于哪些病变？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌张力减低见于下运动神经元病变（如多发性神经病、脊髓前角灰质炎）、小脑病变、某些肌源性病变以及脑和脊髓急性病变的休克期等。",
        "肌张力减低表现为肌肉弛缓柔软、被动运动时阻力减低、关节活动范围扩大。原书简答题第 6 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-short007",
    order: 22,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "哪些类型的瘫痪可见浅反射减弱或消失？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "浅反射减弱或消失的瘫痪见于下运动神经元损害、小脑病变、肌源性病变。",
        "浅反射减弱或消失常见于下运动神经元损害、小脑病变及肌源性病变。原书简答题第 7 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-short008",
    order: 23,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "何谓浅反射，包括哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "浅反射是刺激皮肤、黏膜、角膜等引起肌肉快速收缩反应。包括角膜反射、咽反射、软腭反射、腹壁反射、提睾反射、跖反射和肛门反射。",
        "浅反射的反射弧经脊髓或脑干，由刺激皮肤、黏膜、角膜等引起。原书简答题第 8 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-short009",
    order: 24,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "何谓 Babinski 征？临床意义是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Babinski 征是经典的病理反射，提示锥体束受损。检查时取下肢伸直位，轻划足底外侧向前至小趾根部足掌时转向内侧，阳性为𧿹趾背屈伴其他足趾扇形分开。",
        "Babinski 征阳性提示锥体束受损，是最有意义的病理反射。原书简答题第 9 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-short010",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "常见的病理反射有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常见的病理反射中 Babinski 征最重要，其余还有 Chaddock 征、Oppenheim 征、Gordon 征、Gonda 征、Scheffer 征和 Pussep 征等。",
        "巴宾斯基等位征（Chaddock、Oppenheim、Scheffer、Gordon、Gonda、Pussep 征）的病理意义临床上一般认为同 Babinski 征。原书简答题第 10 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 病例分析题（case），本章无此题型 */
const caseItems: readonly AssessmentItemDefinition[] = [];

/** B1 配伍题组（b1），2 组、共 9 个成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-b001",
    order: 26,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "肱二头肌反射",
      "跖反射",
      "Babinski 征",
      "Kernig 征",
      "眼心反射",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-neurology-ch04-history-taking-and-physical-examination-b001m1",
        order: 26,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "属于浅反射的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "跖反射",
            "浅反射包括角膜反射、咽反射、软腭反射、腹壁反射、提睾反射、跖反射和肛门反射。原书 B1 答案第 1 题为 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-neurology-ch04-history-taking-and-physical-examination-b001m2",
        order: 27,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "属于病理反射的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "Babinski 征",
            "Babinski 征是经典的病理反射，提示锥体束受损。原书 B1 答案第 2 题为 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-neurology-ch04-history-taking-and-physical-examination-b001m3",
        order: 28,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "属于脑膜刺激征的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "Kernig 征",
            "脑膜刺激征包括颈强直、Kernig 征和 Brudzinski 征等。原书 B1 答案第 3 题为 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-neurology-ch04-history-taking-and-physical-examination-b001m4",
        order: 29,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "属于深反射的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肱二头肌反射",
            "深反射包括肱二头肌反射、肱三头肌反射、桡骨膜反射、膝反射、踝反射等。原书 B1 答案第 4 题为 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch04-history-taking-and-physical-examination-b002",
    order: 30,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "划圈样步态",
      "剪刀样步态",
      "慌张步态",
      "醉酒步态",
      "跨阈步态",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-neurology-ch04-history-taking-and-physical-examination-b002m1",
        order: 30,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "痉挛性偏瘫导致",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "划圈样步态",
            "痉挛性偏瘫患者行走时患侧下肢伸直、外旋，迈步时腿外旋画半圈，呈划圈样步态。原书 B1 答案第 5 题为 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-neurology-ch04-history-taking-and-physical-examination-b002m2",
        order: 31,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "小脑病变导致",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "醉酒步态",
            "小脑病变导致共济失调，行走时步基宽大、摇晃不稳，呈醉酒步态。原书 B1 答案第 6 题为 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-neurology-ch04-history-taking-and-physical-examination-b002m3",
        order: 32,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "帕金森综合征导致",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "慌张步态",
            "帕金森综合征表现为起步困难、呈小步、不易止步，呈慌张步态。原书 B1 答案第 7 题为 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-neurology-ch04-history-taking-and-physical-examination-b002m4",
        order: 33,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "腓总神经麻痹导致",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "跨阈步态",
            "腓总神经麻痹致足下垂，行走时抬腿过高、落脚时足尖先触及地面，呈跨阈步态。原书 B1 答案第 8 题为 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-neurology-ch04-history-taking-and-physical-examination-b002m5",
        order: 34,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "痉挛性截瘫导致",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "剪刀样步态",
            "痉挛性截瘫双下肢肌张力增高、内收，行走时两腿交叉呈剪刀样步态。原书 B1 答案第 9 题为 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...a1Items, ...shortItems, ...caseItems,
];
export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
