import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 神经病学学习指导与习题集（第3版）— 第12章 中枢神经系统感染性疾病 题库提取（等比取样）
 * 来源：《神经病学学习指导与习题集》第3版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 选择题（a1-single）：28 题（含 A2 病例题 5 题、A3/A4 病例串题 7 题）
 * - 问答题（short-answer）：12 题（含简答、论述）
 * - 病例分析题（case）：2 题
 * - B1 配伍题：1 组、共 4 个成员
 * - 独立记分题合计：46 题（须等于本文件预算 46）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含 A1 型 48、A2 型 10、A3/A4 型 14（4 组病例串）、B1 型 3 组 14 成员、
 *   简答题 17、论述题 13、病例分析题 4。本文件按 46 道预算在原书顺序内取材：A1 取第
 *   1~16 题、A2 取第 1~5 题、A3/A4 取前两组病例串（1~7 题）、简答取第 1~8 题、论述取
 *   第 1~4 题、病例分析取第 1~2 题，B1 取第 1 组（1~4）完整组。正确项逐一对齐章末
 *   参考答案键号。OCR 错字与双栏错序已按神经病学医学语义恢复（如 祝神经→视神经、
 *   力→为、洽疗→治疗、行改变→行为改变、密啶→嘧啶、昇烟肼→异烟肼、青莓素→青霉素、
 *   草兰→革兰、颅肉压→颅内压 等），数值与分子标记（mmH₂O、mmol/L、HSV、PCR、CJD、
 *   PrP、HIV、PPD、TBM、NMDAR、FLAIR、DWI）保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "neurology-ch12-cns-infectious-disease";
const locatorBase =
  "《神经病学学习指导与习题集》第3版 第12章 中枢神经系统感染性疾病 习题（核对PDF 第221–247页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** A1/A2/A3-A4 型选择题（统一映射为 a1-single），28 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "中枢神经系统最常见的病毒感染性疾病是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "带状疱疹病毒性脑炎",
      "单纯疱疹病毒性脑炎",
      "肠道病毒性脑炎",
      "腺病毒性脑炎",
      "巨细胞病毒性脑炎",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单纯疱疹病毒性脑炎",
        "单纯疱疹病毒性脑炎（HSE）是中枢神经系统最常见的病毒感染性疾病。原书 A1 答案第 1 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "感染后病理为以脑实质出血性坏死为主要特征的脑炎，该病毒是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脊髓灰质炎病毒",
      "柯萨奇病毒",
      "水痘-带状疱疹病毒",
      "巨细胞病毒",
      "单纯疱疹病毒",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单纯疱疹病毒",
        "单纯疱疹病毒性脑炎的病理特征为脑实质出血性坏死及神经细胞和胶质细胞核内嗜酸性包涵体。原书 A1 答案第 2 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "85%～95% 病毒性脑膜炎由此种病毒引起，该病毒是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肠道病毒",
      "带状疱疹病毒",
      "单纯疱疹病毒",
      "巨细胞病毒",
      "腺病毒",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肠道病毒",
        "85%～95% 的病毒性脑膜炎由肠道病毒引起，主要经粪-口途径传播。原书 A1 答案第 3 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不属于单纯疱疹病毒性脑炎确诊依据的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "口唇或生殖道疱疹史，或本次发病有皮肤、黏膜疱疹",
      "双份血清和脑脊液检查发现 HSV 特异性抗体有显著变化趋势",
      "脑组织活检或病理发现组织细胞核内包涵体，或原位杂交发现 HSV 病毒核酸",
      "脑脊液的 PCR 检测发现 HSV-DNA",
      "脑组织或脑脊液标本培养出 HSV",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "口唇或生殖道疱疹史，或本次发病有皮肤、黏膜疱疹",
        "口唇或生殖道疱疹史属于临床诊断依据而非确诊依据；确诊依据为双份血清和脑脊液 HSV 特异性抗体显著变化、脑组织活检或病理发现核内包涵体或原位杂交发现 HSV 核酸、脑脊液 PCR 检测发现 HSV-DNA、脑组织或脑脊液标本 HSV 分离培养鉴定。原书 A1 答案第 4 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不属于进行性风疹全脑炎临床特点的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "约在 20 岁发病",
      "行为改变、认知障碍和痴呆常为首发症状",
      "癫痫和肌阵挛明显，小脑性共济失调不明显",
      "无头痛、发热和颈强直等症状",
      "病程与亚急性硬化性全脑炎相似",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "癫痫和肌阵挛明显，小脑性共济失调不明显",
        "进行性风疹全脑炎约在 20 岁发病，行为改变、认知障碍和痴呆常为首发症状，小脑性共济失调明显，而癫痫和肌阵挛不明显，无头痛、发热和颈强直等症状。原书 A1 答案第 5 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不符合单纯疱疹病毒性脑炎脑脊液常规特点的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "有核细胞数增多，以淋巴细胞为主",
      "可有红细胞数增多",
      "糖与氯化物正常",
      "外观多微黄混浊",
      "蛋白质呈轻、中度增高",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "外观多微黄混浊",
        "单纯疱疹病毒性脑炎脑脊液常规特点为有核细胞数增多、以淋巴细胞为主，可有红细胞数增多，糖与氯化物正常，蛋白质轻、中度增高；外观多微黄混浊不符合其特点。原书 A1 答案第 6 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "单纯疱疹病毒性脑炎或脑膜炎的一线抗病毒药物为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "更昔洛韦",
      "阿昔洛韦",
      "伐昔洛韦",
      "喷昔洛韦",
      "泛昔洛韦",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阿昔洛韦",
        "单纯疱疹病毒性脑炎或脑膜炎的一线抗病毒药物为阿昔洛韦，也可用更昔洛韦。原书 A1 答案第 7 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "化脓性脑膜炎脑脊液常规检查的特征性改变是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "蛋白升高",
      "外观混浊或呈脓性",
      "糖含量下降",
      "氯化物降低",
      "中性粒细胞明显升高，多为（1000~10000）×10⁶/L",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中性粒细胞明显升高，多为（1000~10000）×10⁶/L",
        "化脓性脑膜炎脑脊液常规的特征性改变是中性粒细胞明显升高，多为（1000~10000）×10⁶/L。原书 A1 答案第 8 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "单纯疱疹病毒最易累及中枢神经系统的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "枕叶、顶叶",
      "基底节区",
      "颞叶、额叶及边缘系统",
      "脑干",
      "小脑",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颞叶、额叶及边缘系统",
        "单纯疱疹病毒最易累及颞叶、额叶及边缘系统，脑电图和影像学常以颞、额区损害为主。原书 A1 答案第 9 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "流行性脑脊髓膜炎的病原体是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "流感嗜血杆菌 B 型",
      "金黄色葡萄球菌",
      "乙型脑炎病毒",
      "铜绿假单胞菌",
      "脑膜炎双球菌",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑膜炎双球菌",
        "流行性脑脊髓膜炎的病原体是脑膜炎双球菌，属于化脓性脑膜炎的一种。原书 A1 答案第 10 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "单纯疱疹病毒性脑炎诊断的“金标准”是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脑脊液中发现 HSV 特异性抗体",
      "脑脊液中检查出 HSV 核酸",
      "脑组织活检或病理发现组织细胞核内包涵体",
      "血清标本培养出 HSV",
      "脑组织或脑脊液标本培养出 HSV",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑组织活检或病理发现组织细胞核内包涵体",
        "单纯疱疹病毒性脑炎诊断的“金标准”是脑组织活检或病理发现组织细胞核内包涵体。原书 A1 答案第 11 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不是变异型 CJD 特点的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "发病较早（平均约 30 岁），病程较长（>1 年）",
      "早期突出的精神异常和行为改变，痴呆发生较晚",
      "痴呆发生较早，约 2/3 患者出现肌阵挛",
      "小脑必定受累出现共济失调",
      "通常无肌阵挛和特征性脑电图改变",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "痴呆发生较早，约 2/3 患者出现肌阵挛",
        "变异型 CJD 发病较早（平均约 30 岁）、病程较长（>1 年），小脑必定受累出现共济失调，早期突出的精神异常和行为改变，痴呆发生较晚，通常无肌阵挛和特征性脑电图改变。原书 A1 答案第 12 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "化脓性脑膜炎最常见的致病菌",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "金黄色葡萄球菌",
      "大肠杆菌",
      "肺炎球菌、脑膜炎双球菌及流感嗜血杆菌 B 型",
      "厌氧杆菌",
      "铜绿假单胞菌",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺炎球菌、脑膜炎双球菌及流感嗜血杆菌 B 型",
        "化脓性脑膜炎最常见的致病菌为肺炎球菌、脑膜炎双球菌及流感嗜血杆菌 B 型。原书 A1 答案第 13 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不属于单纯疱疹病毒性脑炎临床诊断依据的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脑脊液红、白细胞数增多，糖和氯化物正常",
      "脑电图以颞、额区损害为主的脑弥漫性异常",
      "头颅 CT 或 MRI 发现颞叶局灶性出血性脑软化灶",
      "口唇或生殖道疱疹史，或本次发病有皮肤、黏膜疱疹",
      "亚急性或慢性起病，常以人格改变和智能减退起病",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "亚急性或慢性起病，常以人格改变和智能减退起病",
        "单纯疱疹病毒性脑炎多急性起病、病情重，亚急性或慢性起病、常以人格改变和智能减退起病不属于其临床诊断依据。原书 A1 答案第 14 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1015",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "病毒性脑膜炎的高发季节为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "夏秋季",
      "冬季",
      "春季",
      "冬春季",
      "春夏季",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "夏秋季",
        "病毒性脑膜炎夏秋季高发，儿童多见。原书 A1 答案第 15 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1016",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "病毒性脑膜炎的特征性表现是手-足-口综合征的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "埃可病毒 9 型脑膜炎",
      "柯萨奇病毒 A 型脑膜炎",
      "埃可病毒性脑膜炎",
      "肠道病毒 71 型脑膜炎",
      "单纯疱疹病毒性脑膜炎",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肠道病毒 71 型脑膜炎",
        "手-足-口综合征常发生于肠道病毒 71 型脑膜炎，非特异性皮疹常见于埃可病毒 9 型脑膜炎。原书 A1 答案第 16 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1017",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "女性，21 岁，因“高热、寒战伴头痛、呕吐 5 天”入院。查体：体温 40°C，脑膜刺激征阳性。头颅 CT：未见异常。血常规：白细胞 21.7×10⁹/L，中性粒细胞 90%。腰穿：脑压 360mmH₂O，脑脊液灰白色混浊，糖 1.78mmol/L、氯化物 114mmol/L，蛋白 2.8g/L，白细胞 7200×10⁶/L，中性粒细胞 89%，淋巴细胞 8%，单核细胞 3%。该患者最可能的诊断是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "单纯疱疹病毒性脑炎",
      "结核性脑膜炎",
      "化脓性脑膜炎",
      "新型隐球菌脑膜炎",
      "病毒性脑膜炎",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "化脓性脑膜炎",
        "高热、寒战伴头痛呕吐，脑膜刺激征阳性，脑脊液灰白色混浊、白细胞显著升高且以中性粒细胞为主、糖降低，符合化脓性脑膜炎。原书 A2 答案第 1 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1018",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "男性，16 岁，主因“发热、头痛伴呕吐 2 天”入院。查体：体温 38.2°C，颈胸四横指。腰穿：脑压 150mmH₂O，脑脊液无色透明，糖、氯化物正常，蛋白 0.42g/L，白细胞 57×10⁶/L，淋巴细胞 94%，单核细胞 6%。该患者最可能的诊断是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "带状疱疹病毒性脑炎",
      "病毒性脑膜炎",
      "单纯疱疹病毒性脑炎",
      "化脓性脑膜炎",
      "结核性脑膜炎",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "病毒性脑膜炎",
        "发热、头痛伴呕吐，脑脊液无色透明、糖和氯化物正常、白细胞轻中度增高且以淋巴细胞为主，符合病毒性脑膜炎。原书 A2 答案第 2 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1019",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "男性，18 岁，主因“反复抽搐 1 月余”入院，家中蓄养猪、羊等牲畜。患者近一月无明显诱因反复出现抽搐，发作间期正常，头 CT 检查可见散在直径约 0.5~1.0cm 大小不等的圆形或类圆形低密度和高低混杂密度影及数个钙化灶。该患者最可能的诊断是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脑脓肿",
      "脑肿瘤",
      "脑膜炎",
      "脑囊虫病",
      "脑炎",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑囊虫病",
        "家中蓄养猪、羊等牲畜，反复抽搐，头 CT 见散在圆形或类圆形低密度影及钙化灶，符合脑囊虫病。原书 A2 答案第 3 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1020",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "男性，20 岁，主因“头痛、呕吐 2 天”入院，发病前 1 周有腹泻史。查体：体温 37.8°C，神志清，颈略抵抗，Kernig 征及 Brudzinski 征均阴性。腰穿：脑压 185mmH₂O，脑脊液无色透明，糖 2.6mmol/L、氯化物 127mmol/L，蛋白 0.6g/L，白细胞 40×10⁶/L，淋巴细胞 95%，单核细胞 5%。该病最可能的病原体是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "新型隐球菌",
      "肠道病毒",
      "结核分枝杆菌",
      "带状疱疹病毒",
      "单纯疱疹病毒",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肠道病毒",
        "发病前 1 周有腹泻史，脑脊液无色透明、糖和氯化物正常、淋巴细胞为主，符合病毒性脑膜炎，最常见的病原体为肠道病毒。原书 A2 答案第 4 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1021",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "女性，45 岁，病史：头痛、呕吐，体温最高 39.8°C，伴躁动，2 天后频繁癫痫发作，且出现昏迷，3 天后死亡。病理检查脑实质内出血性坏死、细胞核内包涵体。该病最主要药物治疗为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肾上腺皮质激素",
      "青霉素",
      "抗病毒药物",
      "头孢类抗生素",
      "抗结核治疗",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗病毒药物",
        "病理检查示脑实质内出血性坏死、细胞核内包涵体，符合单纯疱疹病毒性脑炎，最主要药物治疗为抗病毒药物（阿昔洛韦或更昔洛韦）。原书 A2 答案第 5 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1022",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（共用题干）女性，24 岁，主因“发热、头痛 25 天，加重伴呕吐 3 天”入院。病程中感乏力、食欲缺乏、盗汗，一月内体重下降约 10 斤。其弟患肺结核，正行抗结核治疗。查体：体温 38.4°C，神志清，双眼外展、内收均不到位，颈强直，Kernig 征阳性，Brudzinski 征阳性。胸片未见异常。该患者首选检查",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "头 CT",
      "头 MRI",
      "脑电图",
      "腰穿",
      "血细菌培养",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腰穿",
        "发热、头痛、呕吐伴结核接触史及脑膜刺激征，考虑结核性脑膜炎可能，首选腰穿检查脑脊液。原书 A3/A4 答案第 1 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1023",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（共用题干）女性，24 岁，主因“发热、头痛 25 天，加重伴呕吐 3 天”入院。病程中感乏力、食欲缺乏、盗汗，一月内体重下降约 10 斤。其弟患肺结核，正行抗结核治疗。查体：体温 38.4°C，神志清，双眼外展、内收均不到位，颈强直，Kernig 征阳性，Brudzinski 征阳性。胸片未见异常。若腰穿检查：脑压 330mmH₂O，脑脊液微黄，糖 1.9mmol/L、氯化物 110mmol/L，蛋白 1.4g/L，白细胞 385×10⁶/L，中性粒细胞 39%，淋巴细胞 48%，单核细胞 13%，考虑可能性大的疾病是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "化脓性脑膜炎",
      "结核性脑膜炎",
      "新型隐球菌脑膜炎",
      "病毒性脑膜炎",
      "单纯疱疹病毒性脑炎",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结核性脑膜炎",
        "亚急性病程伴结核中毒症状及结核接触史，脑脊液微黄、糖和氯化物降低、蛋白增高、淋巴细胞为主，符合结核性脑膜炎。原书 A3/A4 答案第 2 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1024",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（共用题干）女性，24 岁，主因“发热、头痛 25 天，加重伴呕吐 3 天”入院。病程中感乏力、食欲缺乏、盗汗，一月内体重下降约 10 斤。其弟患肺结核，正行抗结核治疗。查体：体温 38.4°C，神志清，双眼外展、内收均不到位，颈强直，Kernig 征阳性，Brudzinski 征阳性。胸片未见异常。应选用的治疗是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "抗病毒",
      "使用广谱抗生素",
      "抗结核治疗",
      "营养神经",
      "抗真菌治疗",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗结核治疗",
        "考虑结核性脑膜炎，应选用抗结核治疗，原则为早期给药、合理选药、联合用药及系统治疗。原书 A3/A4 答案第 3 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1025",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（共用题干）女性，56 岁，因“间歇性头痛伴发热 2 月，加重 10 天”入院。在某私人诊所先后静脉滴注青霉素、头孢哌酮钠治疗一月，发热、头痛未减轻，且逐渐加重，体温多在 37.8~38.5°C。2 年前确诊“肾病综合征、膜性肾病”，一直口服泼尼松治疗。查体：颈抵抗（+），Kernig 征及 Brudzinski 征阴性。颅脑 CT：未见异常。为有助诊断，需进一步进行的检查是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "头 MRI",
      "脑电图",
      "血细菌培养",
      "血沉、PPD 试验",
      "腰穿",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腰穿",
        "长期口服泼尼松的免疫抑制患者，慢性发热头痛，广谱抗生素治疗无效，考虑新型隐球菌脑膜炎可能，需行腰穿检查脑脊液（墨汁染色）。原书 A3/A4 答案第 4 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1026",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（共用题干）女性，56 岁，因“间歇性头痛伴发热 2 月，加重 10 天”入院。在某私人诊所先后静脉滴注青霉素、头孢哌酮钠治疗一月，发热、头痛未减轻，且逐渐加重，体温多在 37.8~38.5°C。2 年前确诊“肾病综合征、膜性肾病”，一直口服泼尼松治疗。查体：颈抵抗（+），Kernig 征及 Brudzinski 征阴性。颅脑 CT：未见异常。若腰穿检查：脑压 190mmH₂O，脑脊液无色透明，糖 1.5mmol/L、氯化物 117mmol/L，蛋白 1.2g/L，白细胞 180×10⁶/L，中性粒细胞 24%，淋巴细胞 70%，单核细胞 6%，墨汁染色（+），该患者应诊断为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "结核性脑膜炎",
      "化脓性脑膜炎",
      "新型隐球菌脑膜炎",
      "病毒性脑膜炎",
      "病毒性脑膜脑炎",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "新型隐球菌脑膜炎",
        "免疫抑制患者慢性病程，脑脊液糖降低、淋巴细胞为主，墨汁染色（+）检出隐球菌，可确诊新型隐球菌脑膜炎。原书 A3/A4 答案第 5 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1027",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（共用题干）女性，56 岁，因“间歇性头痛伴发热 2 月，加重 10 天”入院。在某私人诊所先后静脉滴注青霉素、头孢哌酮钠治疗一月，发热、头痛未减轻，且逐渐加重，体温多在 37.8~38.5°C。2 年前确诊“肾病综合征、膜性肾病”，一直口服泼尼松治疗。查体：颈抵抗（+），Kernig 征及 Brudzinski 征阴性。颅脑 CT：未见异常。与该病最相似的疾病是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "新型隐球菌脑膜炎",
      "病毒性脑膜炎",
      "结核性脑膜炎",
      "单纯疱疹病毒性脑炎",
      "化脓性脑膜炎",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结核性脑膜炎",
        "新型隐球菌脑膜炎的临床表现与结核性脑膜炎相似，需与之鉴别。原书 A3/A4 答案第 6 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-a1028",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（共用题干）女性，56 岁，因“间歇性头痛伴发热 2 月，加重 10 天”入院。在某私人诊所先后静脉滴注青霉素、头孢哌酮钠治疗一月，发热、头痛未减轻，且逐渐加重，体温多在 37.8~38.5°C。2 年前确诊“肾病综合征、膜性肾病”，一直口服泼尼松治疗。查体：颈抵抗（+），Kernig 征及 Brudzinski 征阴性。颅脑 CT：未见异常。治疗方案是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "抗结核治疗",
      "抗病毒治疗",
      "广谱抗生素治疗",
      "抗真菌治疗",
      "皮质类固醇治疗",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗真菌治疗",
        "新型隐球菌脑膜炎的治疗以抗真菌治疗为主，可用两性霉素 B、氟康唑、5-氟胞嘧啶。原书 A3/A4 答案第 7 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 问答题（short-answer，含简答、论述），12 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-neurology-ch12-cns-infectious-disease-short001",
    order: 29,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "中枢神经系统感染的定义是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中枢神经系统感染的定义",
        "中枢神经系统感染是指各种病原微生物（病毒、细菌、真菌、螺旋体、寄生虫、立克次体和朊蛋白等）侵犯中枢神经系统（CNS）的实质、被膜及血管等引起的急性或慢性炎症性（或非炎症性）疾病。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-short002",
    order: 30,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "中枢神经系统感染依据感染部位和感染途径的分类是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中枢神经系统感染的分类",
        "中枢神经系统感染依据感染部位分为脑炎、脊髓炎或脑脊髓炎；脑膜炎、脊膜炎或脑脊膜炎；脑膜脑炎。根据感染途径分为血行感染、直接感染、神经干逆行感染。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-short003",
    order: 31,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "单纯疱疹病毒性脑炎主要累及的部位及其重要病理特征是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单纯疱疹病毒性脑炎累及部位与病理特征",
        "单纯疱疹病毒性脑炎主要累及颞叶内侧、边缘系统和额叶眶面。脑实质中出血性坏死及神经细胞和胶质细胞核内可见含有疱疹病毒颗粒和抗原的嗜酸性包涵体是其重要病理特征。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-short004",
    order: 32,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "单纯疱疹病毒性脑炎的确诊依据有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单纯疱疹病毒性脑炎的确诊依据",
        "①双份血清和脑脊液检查发现 HSV 特异性抗体有显著变化趋势；②脑组织活检或病理发现组织细胞核内包涵体，或原位杂交发现 HSV 病毒核酸；③脑脊液的 PCR 检测发现 HSV-DNA；④脑组织或脑脊液标本 HSV 分离、培养和鉴定。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-short005",
    order: 33,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "化脓性脑膜炎最常见的致病菌有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "化脓性脑膜炎最常见的致病菌",
        "化脓性脑膜炎最常见的致病菌为肺炎球菌、脑膜炎双球菌及流感嗜血杆菌 B 型。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-short006",
    order: 34,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "结核性脑膜炎的脑脊液特点有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结核性脑膜炎的脑脊液特点",
        "①脑脊液压力增高，可达 400mmH₂O 或以上；②静置后可有薄膜形成；③淋巴细胞数显著增多，常为（50~500）×10⁶/L；④蛋白质明显增高，通常为 1~2g/L；⑤糖及氯化物下降；⑥少数抗酸染色阳性，可培养出结核菌。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-short007",
    order: 35,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "老年人结核性脑膜炎有哪些特点？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "老年人结核性脑膜炎的特点",
        "老年人结核性脑膜炎的临床表现主要有头痛、呕吐较轻，颅高压症状不明显，脑脊液改变可不典型，发生结核性动脉内膜炎而引起脑梗死的较多。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-short008",
    order: 36,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "目前已知的人类朊蛋白病主要有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "人类朊蛋白病的主要类型",
        "目前已知的人类朊蛋白病主要有 Creutzfeldt-Jakob 病（CJD）、Kuru 病、Gerstmann-Straussler 综合征（GSS）、致死性家族性失眠症（FFI）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-short009",
    order: 37,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "单纯疱疹病毒性脑炎（HSE）的主要临床表现是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单纯疱疹病毒性脑炎的主要临床表现",
        "(1)任何年龄、季节均可患病。原发感染的潜伏期平均 6 天。前驱期可有发热、全身不适、头痛、肌痛、嗜睡、腹痛和腹泻等症状。多急性起病，可有口唇疱疹史。病程为数日至 1~2 个月。(2)常见症状有发热、头痛、呕吐、轻微意识和人格改变、记忆丧失、偏瘫、偏盲、失语、共济失调、多动、脑膜刺激征等。部分以癫痫发作或精神行为异常为首发或唯一症状。(3)病情常快速进展，多数有意识障碍。重者可因颅内压增高致脑疝形成而死亡。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-short010",
    order: 38,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "单纯疱疹病毒性脑炎（HSE）的主要诊断依据是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单纯疱疹病毒性脑炎的主要诊断依据",
        "(1)口唇或生殖道疱疹史，或本次发病有皮肤、黏膜疱疹；(2)起病急，病情重，有发热、咳嗽等上呼吸道感染的前驱症状；(3)明显精神行为异常、抽搐、意识障碍及早期出现的局灶性神经系统损害体征；(4)脑脊液红、白细胞数增多，糖和氯化物正常；(5)脑电图以颞、额区损害为主的脑弥漫性异常；(6)头颅 CT 或 MRI 发现颞叶局灶性出血性脑软化灶；(7)特异性抗病毒药物治疗有效支持诊断。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-short011",
    order: 39,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述化脓性脑膜炎的临床表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "化脓性脑膜炎的临床表现",
        "(1)感染症状：发热、寒战或上呼吸道感染等。(2)脑膜刺激征：颈项强直、Kernig 征和 Brudzinski 征阳性。(3)颅内压增高：剧烈头痛、呕吐、意识障碍等，严重时形成脑疝。(4)局灶性神经功能损害症状：偏瘫、失语等。(5)其他症状：脑膜炎双球菌脑膜炎（又称流行性脑脊髓膜炎）菌血症时可出现皮疹，初为弥散性红色斑丘疹，迅速转变成皮肤瘀点，主要见于躯干、下肢、黏膜以及结膜，偶见于手掌及足底。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-short012",
    order: 40,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述化脓性脑膜炎抗菌治疗方案。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "化脓性脑膜炎抗菌治疗方案",
        "化脓性脑膜炎抗菌治疗原则是及早使用抗生素，通常在确定病原菌之前使用广谱抗生素，若明确病原菌则应选用敏感的抗生素。(1)未确定病原菌：三代头孢的头孢曲松或头孢噻肟常作为化脓性脑膜炎首选用药，对脑膜炎双球菌、肺炎球菌、流感嗜血杆菌及 B 型链球菌引起的化脓性脑膜炎疗效比较肯定。(2)确定病原菌：应根据病原菌选择敏感的抗生素。①肺炎球菌：对青霉素敏感者可用大剂量青霉素，成人每天 2000 万~2400 万 U，儿童每天 40 万 U/kg，分次静脉滴注。对青霉素耐药者，可考虑用头孢曲松，必要时联合万古霉素治疗。2 周为一疗程，通常开始抗生素治疗后 24~36 小时内复查脑脊液，以评价治疗效果。②脑膜炎球菌：首选青霉素，耐药者选用头孢噻肟或头孢曲松，可与氨苄西林或氯霉素联用。对青霉素或 β-内酰胺类抗生素过敏者可用氯霉素。③革兰阴性杆菌：对铜绿假单胞菌引起的脑膜炎可使用头孢他啶，其他革兰阴性杆菌脑膜炎可用头孢曲松、头孢噻肟或头孢他啶，疗程常为 3 周。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 病例分析题（case），2 道 */
const caseItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-neurology-ch12-cns-infectious-disease-case001",
    order: 41,
    knowledgePointId: kp,
    questionKind: "case",
    status: "available",
    prompt: "男性，13 岁，学生，因“发热、头痛伴呕吐 3 天”入院。患者 3 天前突然出现高热，体温达 39°C 以上，伴寒战，同时出现剧烈全头痛，多次喷射性呕吐，呕吐物为胃内容物和胆汁。无腹痛、腹泻、抽搐，进食少，二便正常。近一月体重无明显变化。2 周前有外耳道流脓现象。既往无胃病和结核病史。入院查体：体温 39.8°C，急性热病容，心肺腹（-），神志清，四肢肌力、肌张力正常，双 Babinski 征（-），颈部抵抗（+），Kernig 征（+），Brudzinski 征（+）。辅助检查：血常规：白细胞 15.6×10⁹/L，中性粒细胞 91%，血红蛋白 125g/L，血小板 162×10⁹/L。尿常规、便常规、生化全套、心电图等均正常。问题：（1）请写出诊断及诊断依据。（2）需与哪些疾病鉴别？（3）还应做哪些辅助检查？（4）治疗原则是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "化脓性脑膜炎的诊断、鉴别、检查与治疗",
        "(1)诊断：化脓性脑膜炎。诊断依据：少年男性，急性起病，主要症状为高热、寒战、剧烈头痛伴喷射性呕吐；2 周前有外耳道流脓现象。查体：体温 39.8°C，急性热病容，脑膜刺激征阳性；血白细胞总数及中性粒细胞比例均增高。(2)需与病毒性脑膜炎、结核性脑膜炎和隐球菌性脑膜炎相鉴别。(3)进一步检查有：①腰穿检查包括测脑压、脑脊液常规、生化、细胞学、脑脊液细菌培养及细菌涂片、脑脊液墨汁染色、脑脊液抗酸染色涂片、脑脊液结核杆菌培养等；②头颅 CT 或 MRI；③胸片或胸部 CT；④血细菌培养；⑤血沉及 PPD 试验。(4)①抗菌治疗：原则是及早使用抗生素，在确定病原菌之前使用广谱抗生素如三代头孢（头孢曲松或头孢噻肟），若明确病原菌则选用敏感抗生素；②糖皮质激素治疗：对病情较重且没有明显激素禁忌证患者可应用；③对症支持治疗：降颅压、退热、控制癫痫发作等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-neurology-ch12-cns-infectious-disease-case002",
    order: 42,
    knowledgePointId: kp,
    questionKind: "case",
    status: "available",
    prompt: "女性，26 岁，农民，因“发热、头痛 1 月，加重伴呕吐 4 天”入院。患者于 1 月前受凉后出现发热，下午明显，体温在 37.4~38.4°C 波动。同时出现全头持续性胀痛，伴乏力、食欲缺乏、出汗多，咳少量白色黏痰，无咯血和胸痛。就诊于当地医院，给予“头孢曲松钠”输液治疗半月，症状无改善，仍发热，且头痛逐渐加重，4 天前频繁呕吐，呈喷射性，呕吐物为胃内容物。病后进食及睡眠差，一月来体重下降约 4kg。既往体健。邻居有一人 2 月前患肺结核，正行抗结核治疗。入院查体：体温 38°C，心肺腹（-），神志清，四肢肌力正常，双 Babinski 征（-），颈部抵抗（+），Kernig 征（+），Brudzinski 征（+）。辅助检查：血常规：白细胞 6.1×10⁹/L，中性粒细胞 72%，血红蛋白 127g/L，血小板 245×10⁹/L。尿常规、便常规正常，血钠 125mmol/L，血沉 50mm/h，PPD 试验强阳性。问题：（1）请写出诊断及诊断依据。（2）需与哪些疾病鉴别？（3）还应做哪些辅助检查？（4）治疗原则是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结核性脑膜炎的诊断、鉴别、检查与治疗",
        "(1)诊断：结核性脑膜炎。诊断依据：青年女性，亚急性起病，主要表现为低中热、头痛，伴乏力、食欲缺乏、盗汗、消瘦等结核中毒症状；在当地医院给予广谱抗生素治疗无效；其邻居患肺结核，有可疑肺结核接触史；查体：体温 38°C，脑膜刺激征阳性；血沉增快及 PPD 试验强阳性。(2)需与隐球菌脑膜炎、化脓性脑膜炎、病毒性脑膜炎、脑膜癌病等相鉴别。(3)进一步检查有：①腰椎穿刺检查包括测脑压、脑脊液常规、生化、细胞学、脑脊液抗酸染色涂片、脑脊液结核杆菌培养、细菌培养及细菌涂片、脑脊液墨汁染色；②头颅 CT 或 MRI；③胸片或胸部 CT；④血细菌培养。(4)原则是早期给药、合理选药、联合用药及系统治疗。①抗结核治疗：异烟肼、利福平、吡嗪酰胺或乙胺丁醇、链霉素是治疗 TBM 最有效的联合用药方案；②皮质类固醇激素；③药物鞘内注射；④降颅内压；⑤对症及全身支持治疗。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，1 组、共 4 个成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-neurology-ch12-cns-infectious-disease-b001",
    order: 43,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "脑脊液白细胞 2400×10⁶/L，中性粒细胞 90%，淋巴细胞 6%，单核细胞 4%，蛋白 2.2g/L，糖 1.9mmol/L，氯化物 112mmol/L",
      "脑脊液淡黄，白细胞 420×10⁶/L，中性粒细胞 44%，淋巴细胞 50%，单核细胞 6%，蛋白 1.8g/L，糖 1.4mmol/L，氯化物 94mmol/L",
      "脑脊液白细胞 120×10⁶/L，中性粒细胞 8%，淋巴细胞 70%，单核细胞 22%，蛋白 1g/L，糖 1.6mmol/L，氯化物 124mmol/L，墨汁染色阳性",
      "脑脊液无色清亮，白细胞 90×10⁶/L，淋巴细胞 92%，单核细胞 8%，蛋白 0.8g/L，糖 3.2mmol/L，氯化物 126mmol/L",
      "脑脊液无色清亮，白细胞 2×10⁶/L，蛋白 0.15g/L，糖 3mmol/L，氯化物 124mmol/L",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-neurology-ch12-cns-infectious-disease-b001m1",
        order: 43,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "隐球菌脑膜炎脑脊液符合",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "脑脊液白细胞 120×10⁶/L，中性粒细胞 8%，淋巴细胞 70%，单核细胞 22%，蛋白 1g/L，糖 1.6mmol/L，氯化物 124mmol/L，墨汁染色阳性",
            "隐球菌脑膜炎脑脊液以淋巴细胞为主、糖降低，墨汁染色阳性。原书 B1 答案第 1 题为 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-neurology-ch12-cns-infectious-disease-b001m2",
        order: 44,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "结核性脑膜炎脑脊液符合",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "脑脊液淡黄，白细胞 420×10⁶/L，中性粒细胞 44%，淋巴细胞 50%，单核细胞 6%，蛋白 1.8g/L，糖 1.4mmol/L，氯化物 94mmol/L",
            "结核性脑膜炎脑脊液淡黄、淋巴细胞为主、蛋白增高、糖及氯化物下降。原书 B1 答案第 2 题为 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-neurology-ch12-cns-infectious-disease-b001m3",
        order: 45,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "化脓性脑膜炎脑脊液符合",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "脑脊液白细胞 2400×10⁶/L，中性粒细胞 90%，淋巴细胞 6%，单核细胞 4%，蛋白 2.2g/L，糖 1.9mmol/L，氯化物 112mmol/L",
            "化脓性脑膜炎脑脊液白细胞显著升高、以中性粒细胞为主、糖降低。原书 B1 答案第 3 题为 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-neurology-ch12-cns-infectious-disease-b001m4",
        order: 46,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "病毒性脑膜炎脑脊液符合",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "脑脊液无色清亮，白细胞 90×10⁶/L，淋巴细胞 92%，单核细胞 8%，蛋白 0.8g/L，糖 3.2mmol/L，氯化物 126mmol/L",
            "病毒性脑膜炎脑脊液无色清亮、糖和氯化物正常、以淋巴细胞为主。原书 B1 答案第 4 题为 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...a1Items,
  ...shortItems,
  ...caseItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
