import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 系统解剖学习题集（第2版）— 第3章 肌学 题库提取（等比取样）
 * 来源：《系统解剖学习题集》第2版（人民卫生出版社，以柏树令主编《系统解剖学》第8版为蓝本）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算 43）==
 * - 名词解释：4 题
 * - A1/A2/A3 型选择题（a1-single）：21 题
 * - 填空题（fill）：4 题
 * - 判断改错题 + 问答题（short-answer）：5 题
 * - B1 配伍题：3 组、共 9 个成员
 * - 独立记分题合计：43 题（等于本文件预算 43）
 * - 缺失答案：0；无法可靠提取：0（未换题，均直接取材源参考答案）
 * - 说明：本章原书依次含（一）A1 型题 68、（二）A2 型题 16、（三）A3 型共用题干题 16、
 *   （四）B 型共用备选答案配伍题 21 个成员、填空题 50、名词解释 30、判断改错题 30、
 *   问答题 20。本文件按 43 道预算在素材内按原书顺序等比取材并改写。
 *   A2/A3 亦映射为 a1-single；B 型按原书选项顺序保留 sharedChoices 并取 3 个完整组。
 *   扫描版 OCR 错字已按医学语义恢复，如 沩/力→为、孟上结节（盂上结节）、
 *   蝴/胫/翼（翼）等，数值/结构保留原值，未捏造。涉及头颈、躯干、四肢各肌的
 *   起止点、作用与神经支配（咬肌/颞肌/翼内肌/翼外肌、颊肌、胸锁乳突肌、斜方肌、
 *   胸大肌、肱三头肌、前锯肌、腹外斜肌/腹内斜肌/腹横筋膜、指浅屈肌、桡侧腕长/短伸肌、
 *   臀大肌、股四头肌、小腿三头肌、腓骨长肌/胫骨后肌、膈、咀嚼肌等）。
 * 注意：本文件覆盖 PDF 第45–65页（第三章 肌学）。
 *
 * 解析内容位于 answer.content 数组的第二个元素。
 */

const topic = "human-anatomy-ch3-myology";
const locatorBase =
  "《系统解剖学习题集》第2版 第3章 肌学 复习思考题 习题（扫描版原书核对PDF 第45–65页）";
const promptNote =
  "题干改写；原题来自用户提供的扫描题集（OCR 已按医学语义恢复），未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多选，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据扫描题集整理并改写，未经权威教材交叉核对，OCR 错字已按医学语义恢复";

const kp = `kp-${topic}`;

/** 名词解释（term），4 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-human-anatomy-ch3-myology-term001",
    order: 35,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肌腹",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌腹",
        "为骨骼肌的肌性部分，主要由肌纤维即肌细胞组成，色红而柔软，有收缩能力。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-term002",
    order: 36,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：腱膜",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腱膜",
        "扁肌的腱性部分呈薄膜状，故称腱膜，如腹外斜肌腱膜。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-term003",
    order: 37,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肌的起点",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌的起点",
        "骨骼肌通常以两端附于两块或两块以上的骨上，肌收缩时两骨彼此靠近或分离而产生运动，其中一骨的位置相对固定，肌在固定骨上的附着点称为起点。一般来说，靠近身体正中面或四肢近侧端的附着点为起点。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-term004",
    order: 38,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：拮抗肌",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "拮抗肌",
        "每一关节运动轴的相对侧配布有两组作用相反的肌，这些在作用上相互对抗的肌称拮抗肌（如屈肌与伸肌）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2/A3 型选择题（统一映射为 a1-single），21 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-human-anatomy-ch3-myology-a1001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列属于肌的腱性部分的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["腱划", "肌内膜", "筋膜", "肌外膜", "滑膜囊"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腱划",
        "腱划为腹直肌前面的腱性组织，属肌的腱性部分。筋膜、滑膜囊属肌的辅助装置；肌内膜、肌外膜为包裹肌纤维的结缔组织膜，均不属于肌的腱性部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肌的起止和作用，正确的叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肌运动时定点和动点是固定不变的",
      "四肢肌多起自肢体的远端",
      "躯干肌多起自远离身体正中线的部位",
      "肌运动时多以起点作定点",
      "肌两端皆以肌腱附着于骨上",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌运动时多以起点作定点",
        "肌收缩时多以起点为定点、止点为动点，动点向定点靠近而产生运动；肌的起止点（定点与动点）在一定条件下可互换，故“定点和动点固定不变”有误。四肢肌多起自近端，躯干肌多起自靠近身体正中面的部位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列属于肌的辅助装置的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["腱划", "腱膜", "腱鞘", "中间腱", "肌腱"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腱鞘",
        "肌的辅助装置包括筋膜、滑膜囊、腱鞘和籽骨等；腱鞘是包围在肌腱外面的鞘管，属辅助装置。肌腱、腱膜、腱划、中间腱均为肌本身的组成部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于腱鞘的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "腱纤维鞘脏层包在肌腱表面",
      "腱系膜将肌腱固定于骨表面上",
      "包围在肌腱外面的鞘管",
      "腱纤维鞘可分为脏、壁两层",
      "存在于活动性较小的部位",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "包围在肌腱外面的鞘管",
        "腱鞘是包围在肌腱外面的鞘管，存在于活动性较大的部位（如腕、踝、手指、足趾等处），分纤维层与滑膜层两部分；滑膜层分脏、壁两层，脏层包在肌腱表面，由腱系膜将肌腱固定于骨面。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列属于面肌（表情肌）的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["咬肌", "翼内肌", "颞肌", "颊肌", "翼外肌"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颊肌",
        "面肌包括眼、口、鼻周围肌以及颊肌、枕额肌等皮肌，属表情肌，受面神经支配。咬肌、颞肌、翼内肌、翼外肌为咀嚼肌。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "瘫痪时引起被咀嚼食物滞留于齿颊间隙内的肌是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["口轮匝肌", "翼内肌", "颊肌", "咬肌", "翼外肌"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颊肌",
        "颊肌收缩可使颊部贴紧牙齿，帮助咀嚼和吸吮；其一侧瘫痪时该侧颊部松弛无力，被咀嚼的食物易滞留于齿颊间隙内。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "收缩时上提下颌骨（闭口）的肌是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["翼外肌", "二腹肌", "颊肌", "翼内肌", "下颌舌骨肌"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "翼内肌",
        "翼内肌两侧同时收缩时上提下颌骨（闭口），一侧收缩使下颌移向对侧。二腹肌、下颌舌骨肌收缩时下降下颌骨（张口），颊肌属面肌。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "收缩时作张口运动的肌是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["翼内肌", "口轮匝肌", "咬肌", "翼外肌", "颞肌"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "翼外肌",
        "翼外肌两侧同时收缩使下颌头连同关节盘向前移至关节结节，作张口运动；一侧收缩使下颌移向对侧。咬肌、颞肌、翼内肌收缩时上提下颌骨作闭口运动。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "使下颌骨上提和后退的肌是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["翼外肌", "翼内肌", "咬肌", "二腹肌", "颞肌"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颞肌",
        "颞肌前、中部肌束上提下颌骨，后部肌束使下颌后退，共同协助闭口运动。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列属于舌骨下肌群的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["茎突舌骨肌", "二腹肌", "下颌舌骨肌", "颏舌骨肌", "甲状舌骨肌"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甲状舌骨肌",
        "舌骨下肌群每侧有4块肌：胸骨舌骨肌、肩胛舌骨肌、胸骨甲状肌和甲状舌骨肌。二腹肌、茎突舌骨肌、下颌舌骨肌、颏舌骨肌属舌骨上肌群。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于胸锁乳突肌作用的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "一侧肌收缩使头向对侧倾斜，脸转向同侧",
      "两侧收缩可使头前倾",
      "一侧肌收缩使头向同侧倾斜，脸转向对侧",
      "一侧肌收缩使头向对侧倾斜，脸转向对侧",
      "一侧肌收缩使头向同侧倾斜，脸转向同侧",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "一侧肌收缩使头向同侧倾斜，脸转向对侧",
        "一侧胸锁乳突肌收缩使头向同侧倾斜，脸转向对侧；两侧同时收缩可使头后仰，而非头前倾，故“两侧收缩可使头前倾”错误。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "斜方肌麻痹时，活动受到限制的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "充分外展肩关节",
      "作耸肩活动",
      "充分屈肩关节",
      "作推墙动作",
      "作引体向上活动",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "作耸肩活动",
        "斜方肌上部纤维上提肩胛骨、耸肩，该肌麻痹时耸肩活动受限。肩关节充分外展主要靠三角肌、冈上肌。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肱三头肌的叙述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "止于尺骨鹰嘴",
      "长头参与三边孔和四边孔的围成",
      "长头起自肩胛骨盂上结节",
      "能伸肘关节",
      "长头可使肩关节后伸和内收",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "长头起自肩胛骨盂上结节",
        "肱三头肌长头起自肩胛骨盂下结节，故“起自肩胛骨盂上结节”错误；内侧头、外侧头起自肱骨背面，三头会合后止于尺骨鹰嘴。长头经过肩关节后方并参与围成三边孔、四边孔，除伸肘外还可使肩关节后伸和内收。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肘窝的叙述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "内有肱二头肌腱、肱动脉和正中神经",
      "外侧界为桡侧腕屈肌",
      "位于肘关节前面",
      "上界为肱骨内、外上髁之间的连线",
      "内侧界为旋前圆肌",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "外侧界为桡侧腕屈肌",
        "肘窝在肘关节前面呈三角形凹窝：上界为肱骨内、外上髁的连线，下外侧界为肱桡肌，下内侧界为旋前圆肌，故“外侧界为桡侧腕屈肌”错误；窝内有肱二头肌腱、肱动脉和正中神经等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1015",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于臀大肌的叙述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "深面有坐骨神经等结构通过",
      "下肢固定时可伸躯干",
      "止于股骨大转子",
      "起自髂骨翼和骶骨背面",
      "收缩时伸髋关节并旋外",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "止于股骨大转子",
        "臀大肌起自髂骨翼外面和骶骨背面，止于髂胫束和股骨的臀肌粗隆，故“止于股骨大转子”错误；其深面有坐骨神经等结构通过，收缩时伸髋关节并旋外，下肢固定时可伸直躯干。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1016",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于股四头肌的叙述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "起自股骨的前面、后面和髂前下棘",
      "收缩时伸膝关节、伸髋关节",
      "止于胫骨粗隆",
      "为全身最大的肌",
      "肌腱包绕髌骨",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "收缩时伸膝关节、伸髋关节",
        "股四头肌为全身最大的肌，由股直肌、股内侧肌、股外侧肌和股中间肌构成，四个头向下形成肌腱包绕髌骨，延续为髌韧带止于胫骨粗隆，主要作用为屈髋关节和伸膝关节；说其“伸髋关节”错误。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1017",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于小腿三头肌的叙述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "收缩时屈踝关节和膝关节",
      "止于跟骨",
      "由腓浅神经支配",
      "站立时稳定踝关节和膝关节",
      "分为深、浅层排列",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "由腓浅神经支配",
        "小腿三头肌由浅层腓肠肌和深层比目鱼肌构成，两腱合成跟腱止于跟骨，收缩时屈踝关节和膝关节，站立时稳定踝、膝关节；该肌由胫神经支配，而非腓浅神经。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1018",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "参与组成头皮的肌是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["眼轮匝肌", "颊肌", "颞肌", "翼外肌", "枕额肌"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "枕额肌",
        "枕额肌的额腹与枕腹借帽状腱膜相连，枕额肌连同帽状腱膜参与组成头皮层次。颞肌、翼外肌为咀嚼肌，颊肌、眼轮匝肌为面肌。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1019",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "位于颞下窝的肌是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["咬肌", "翼外肌", "二腹肌", "颊肌", "颞肌"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "翼外肌",
        "翼外肌位于颞下窝深部，属咀嚼肌。颞肌位于颞窝及颞下窝，咬肌位于下颌支外面，颊肌、二腹肌不位于颞下窝。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1020",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列属于胸固有肌的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["前锯肌", "胸大肌", "背阔肌", "肋间内、外肌", "胸小肌"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肋间内、外肌",
        "胸固有肌包括肋间内肌、肋间外肌及胸横肌等，参与构成胸壁。胸大肌、胸小肌、前锯肌属胸上肢肌，背阔肌为背部浅层肌。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-a1021",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "由胸长神经支配的肌是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["肋间内肌", "胸大肌", "前锯肌", "胸横肌", "肋间外肌"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前锯肌",
        "前锯肌由胸长神经支配，胸长神经受损则前锯肌瘫痪，产生“翼状肩”。胸大肌、胸小肌由胸内、外侧神经支配，肋间内外肌由肋间神经支配。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），4 道 */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-human-anatomy-ch3-myology-fill001",
    order: 31,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：骨骼肌由____和____构成，其辅助装置包括____、____、____和____等。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌腹、肌腱；筋膜、滑膜囊、腱鞘、籽骨",
        "骨骼肌由肌腹（肌性部分，有收缩能力）和肌腱（腱性部分，无收缩能力）构成；其辅助装置包括筋膜、滑膜囊、腱鞘和籽骨等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-fill002",
    order: 32,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：骨骼肌按其外形大致可分为____、____、____和____四种。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "长肌、短肌、扁肌、轮匝肌",
        "按外形骨骼肌可分为长肌（多见于四肢）、短肌（多见于躯干深层）、扁肌（如腹壁肌）和轮匝肌（位于孔裂周围）四种。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-fill003",
    order: 33,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：咀嚼肌包括____、____、____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "咬肌、颞肌、翼内肌、翼外肌",
        "咀嚼肌有咬肌、颞肌、翼内肌、翼外肌四块，配布于颞下颌关节周围，参与咀嚼运动。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-fill004",
    order: 34,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：枕额肌由____和____构成；其中，____止于眉部皮肤，收缩时可提眉并使额部皮肤出现皱纹。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "额肌、枕肌；额肌",
        "枕额肌由额肌（额腹）和枕肌（枕腹）借帽状腱膜相连构成；额肌止于眉部皮肤，收缩时提眉并使额部皮肤出现皱纹。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 判断改错题 + 问答题（short-answer），5 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-human-anatomy-ch3-myology-short001",
    order: 39,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断改错：每块骨骼肌包括肌腹和肌腱两部分，肌腹有收缩能力。（判断正误；如错误请改正）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "正确",
        "骨骼肌由肌腹和肌腱两部分构成；肌腹是主要由肌纤维（肌细胞）组成的肌性部分，色红柔软，有收缩能力。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-short002",
    order: 40,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt:
      "判断改错：肩关节和髋关节都是二轴关节，配备有屈、伸、内收和外展肌四组肌。（判断正误；如错误请改正）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错误，肩关节和髋关节都是三轴关节，配备有屈、伸、内收外展、旋内和旋外等六组肌",
        "肩关节和髋关节均为典型的球窝（三轴）关节，沿三个运动轴可作屈伸、内收外展、旋内旋外及环转等运动，故应配备有屈、伸、内收、外展、旋内和旋外六组肌。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-short003",
    order: 41,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt:
      "问答题：试述咀嚼肌有哪些？各有何作用？为什么下颌神经受到刺激时常导致牙关紧闭？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "咀嚼肌包括咬肌、颞肌、翼内肌和翼外肌。咬肌、颞肌、翼内肌收缩时上提下颌骨（闭口）；翼外肌两侧同时收缩作张口运动，一侧收缩则使下颌移向对侧。",
        "由于作张口、闭口运动的肌大都由下颌神经支配，且闭口肌的力量大于张口肌的力量，所以当下颌神经受到刺激时常导致牙关紧闭（咀嚼肌痉挛性收缩、下颌不能张开）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-short004",
    order: 42,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：试述膈的三个裂孔的名称及其通过的结构。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "主动脉裂孔（约平第12胸椎前方，由左、右膈脚与脊柱围成），有主动脉和胸导管通过；食管裂孔（约平第10胸椎，位于膈的肌性部），有食管和迷走神经通过；腔静脉孔（约平第8胸椎，位于中心腱内），有下腔静脉通过。",
        "膈为主要的呼吸肌，三个裂孔中主动脉裂孔最靠后、位于T12水平，食管裂孔居中约T10，腔静脉孔最靠前上、约T8并在中心腱内，其平面和通过结构须与教材表述核对后记忆。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-short005",
    order: 43,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：试述参与运动肩关节的主要肌名称及其作用。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "屈：肱二头肌、喙肱肌、胸大肌、三角肌前部肌束；伸：肱三头肌长头、背阔肌、三角肌后部肌束；内收：大圆肌、肩胛下肌、胸大肌、背阔肌、喙肱肌、肱三头肌长头；外展：三角肌、冈上肌；旋内：大圆肌、肩胛下肌、胸大肌、背阔肌、三角肌前部肌束；旋外：冈下肌、小圆肌、三角肌后部肌束。",
        "以外展最为重要：最初外展（约15°~20°）主要由冈上肌启动，继续外展由三角肌完成；内收、旋内以胸大肌、背阔肌、大圆肌、肩胛下肌为主，旋外以冈下肌、小圆肌为主。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，3 组、共 9 个成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-human-anatomy-ch3-myology-b001",
    order: 22,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["肋间外肌", "膈", "腹外斜肌", "腹内斜肌", "腹横筋膜"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-human-anatomy-ch3-myology-b001m1",
        order: 22,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "位于胸、腹腔之间的肌是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "膈",
            "膈位于胸、腹腔之间，为向上膨隆的扁阔肌，是主要的呼吸肌。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch3-myology-b001m2",
        order: 23,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "起自下8位肋骨外面的肌是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "腹外斜肌",
            "腹外斜肌起自下8位肋骨的外面，肌纤维斜向前下，其余不满足此起点。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch3-myology-b001m3",
        order: 24,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "参与构成提睾肌的肌是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "腹内斜肌",
            "腹内斜肌与腹横肌的最下部细散肌纤维构成提睾肌，包绕精索和睾丸，可反射性提起睾丸。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch3-myology-b001m4",
        order: 25,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "形成腹股沟管深环（深口）的结构是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "腹横筋膜",
            "腹股沟管深环（腹环）为腹横筋膜在腹股沟韧带中点上方约1.5cm处向外突形成的一个开口。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch3-myology-b001m5",
        order: 26,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "形成精索内筋膜的结构是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "腹横筋膜",
            "腹横筋膜沿精索向下延续包裹精索形成精索内筋膜；同一备选答案可复用，故与“形成腹股沟管深环”同为腹横筋膜。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-b002",
    order: 27,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "指浅屈肌",
      "拇长屈肌",
      "尺侧腕屈肌",
      "桡侧腕长、短伸肌",
      "尺侧腕伸肌",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-human-anatomy-ch3-myology-b002m1",
        order: 27,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "屈桡腕关节并屈第2~5指的肌是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "指浅屈肌",
            "指浅屈肌为前臂前群浅层肌，可屈桡腕关节、屈掌指关节并屈近侧指骨间关节（屈第2~5指），由正中神经支配。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch3-myology-b002m2",
        order: 28,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "伸并外展桡腕关节的肌是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "桡侧腕长、短伸肌",
            "桡侧腕长伸肌和短伸肌均可伸桡腕关节并使其外展，由桡神经支配。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch3-myology-b003",
    order: 29,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["腓肠肌", "胫骨前肌", "胫骨后肌", "腓骨长肌", "比目鱼肌"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-human-anatomy-ch3-myology-b003m1",
        order: 29,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "使足跖屈和外翻的肌是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "腓骨长肌",
            "腓骨长肌可屈踝关节（跖屈）并使足外翻，由腓浅神经支配。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch3-myology-b003m2",
        order: 30,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "使足跖屈和内翻的肌是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "胫骨后肌",
            "胫骨后肌可屈踝关节（跖屈）并使足内翻，由胫神经支配。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...fillItems,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
