import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 系统解剖学习题集（第2版）— 第十章 心血管系统 题库提取（等比取样）
 * 来源：《系统解剖学习题集》第2版（人民卫生出版社，以柏树令主编《系统解剖学》第8版为蓝本）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：6 题
 * - A1/A2/A3 型选择题（a1-single）：24 题
 * - 填空题（fill）：10 题
 * - 判断改错题 + 问答题（short-answer）：12 题
 * - B1 配伍题：3 组、共 11 个成员
 * - 独立记分题合计：63 题（含 B1 组成员；须等于本文件预算 63）
 * - 缺失答案：0；无法可靠提取：0（或如实记录换题）
 * - 说明：本章原书依序含 第一节 总论 心（A1、A2、A3 型题、B1 配伍、填空题 20、
 *   名词解释 10、判断改错 20、问答题 10）、第二节 动脉（A1 32、A2 18、B1 配伍、
 *   填空 6、名词解释 10、判断改错 20、问答题 10）、第三节 静脉（A1 30、B1 配伍、
 *   填空 7、名词解释 5、判断改错 20、问答题 5）。本文件按 63 道预算在全书顺序中
 *   取材并改写，覆盖心（结构与传导系、冠状动脉）、动脉（颈总/肱/掌浅弓/腹腔分支等）
 *   与静脉（上腔静脉、头静脉、肝门静脉相关）三大节。
 *   A1/A2/A3 型均映射为 a1-single；B1 型按项目规约组织为 Group b1。
 *   OCR 错字已按医学语义恢复（如「A，型题/Az型题」→A1/A2 型题、「Ag型题」→A3型题、
 *   「力/沩」→为、「左束支（左東支、I1）」→左束支、「胭/膕/胭窝」→腘窝、
 *   「歡弓/冀丛/内眦」→颧弓/翼丛/内眦、「下领/下領」→下颌），
 *   结构名、数值与单位（cm/肋间隙/腰椎高度等）均按原文保留，未捏造。
 * 解析内容位于 answer.content 数组的第二个元素。
 */

const topic = "human-anatomy-ch10-cardiovascular";
const locatorBase =
  "《系统解剖学习题集》第2版 第十章 心血管系统 复习思考题 习题（扫描版原书核对PDF 第131–159页）";
const promptNote =
  "题干改写；原题来自用户提供的扫描题集（OCR 已按医学语义恢复），未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多选/共用题干，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据扫描题集整理并改写，未经权威教材交叉核对，OCR 错字已按医学语义恢复";

const kp = `kp-${topic}`;

/** 名词解释（term），6 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-human-anatomy-ch10-cardiovascular-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：体循环",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "体循环",
        "血液由左心室射出，经主动脉及其分支到达全身毛细血管，与周围的组织、细胞进行物质交换和气体交换后，再通过各级静脉，最后经上、下腔静脉和冠状窦回流至右心房的途径。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：冠状窦",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "冠状窦",
        "冠状窦位于左心房与左心室之间的冠状沟后部，引流心的大部分静脉血，开口于右心房的冠状窦口。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：三尖瓣复合体",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "三尖瓣复合体",
        "三尖瓣复合体由三尖瓣环、三尖瓣、腱索和乳头肌构成，在结构及功能上呈一整体，共同保证血液的单向流动。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：心包腔",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心包腔",
        "心包腔由浆膜性心包的脏、壁层相互移行形成，内含少量液体，可减少心搏动时的摩擦。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：Koch 三角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Koch 三角",
        "Koch 三角是冠状窦口前内缘、三尖瓣隔侧尖附着缘与 Todaro 腱之间的三角形区域，该三角尖端的心内膜深面有房室结，为心内直视手术的重要标志。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：心纤维骨骼",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心纤维骨骼",
        "心纤维骨骼又称心纤维性支架，位于房室口、肺动脉口和主动脉口周围，由致密结缔组织构成，为心肌纤维和心瓣膜的附着处。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2/A3 型选择题（统一映射为 a1-single），24 道（心 12、动脉 7、静脉 5） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1001",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "维持血液连续性流动的动力来自",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["心", "中动脉", "大动脉", "静脉", "小动脉"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "大动脉",
        "血液的连续流动主要靠大动脉管壁的弹性回缩维持，其将心收缩期的动能贮存为弹性势能并平稳释放。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1002",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "右心室流入道与流出道的分界标志",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["隔缘肉柱", "三尖瓣隔侧尖", "室上嵴", "前乳头肌", "三尖瓣前尖"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "室上嵴",
        "室上嵴是右心室流入道（窦部）与流出道（动脉圆锥）的分界标志。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1003",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "心的正常起搏点",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["房室束", "左、右束支", "房室结", "窦房结", "浦肯野纤维"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "窦房结",
        "窦房结是心的正常起搏点，能产生和传导兴奋，控制心的节律性活动。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1004",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "冠状动脉起自",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["冠状窦", "主动脉弓", "升主动脉", "胸主动脉", "主动脉前庭"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "升主动脉",
        "左、右冠状动脉分别起自升主动脉起始处的主动脉左窦和主动脉右窦。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1005",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪项符合冠状窦的特征",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "引流心的全部静脉血",
      "由心大静脉延续形成",
      "心前静脉注入冠状窦右端",
      "位于冠状沟全长",
      "借冠状窦口开口于左心房",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "由心大静脉延续形成",
        "冠状窦由心大静脉延续形成，位于左心房与左心室之间的冠状沟后部，借冠状窦口开口于右心房；心前静脉可直接注入右心房，心最小静脉直接开口于各心腔。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1006",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于心尖的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "朝向右前下方",
      "由右心室构成",
      "前室间支与后室间支吻合处",
      "平对左侧第5肋间隙",
      "活体不易触摸到其搏动",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "平对左侧第5肋间隙",
        "心尖朝向左前下方，由左心室构成，平对左侧第5肋间隙，在左锁骨中线内侧1~2cm处可触到心尖搏动。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1007",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "穿行于右纤维三角内的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["左束支", "结间束", "浦肯野纤维", "房室束", "右束支"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "房室束",
        "房室束（His束）起自房室结前端，穿右纤维三角，沿室间隔膜部下缘前行并分叉为左、右束支。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1008",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "窦房结位于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "房间隔的心内膜深面",
      "上腔静脉口的心内膜深面",
      "上腔静脉与右心房交界处",
      "右肺静脉入口处",
      "下腔静脉入口处",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "上腔静脉与右心房交界处",
        "窦房结位于上腔静脉与右心房交界处心外膜的深面，是心的正常起搏点。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1009",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于后室间支的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "沿后室间沟下行至心尖",
      "发出房室结动脉",
      "分布于左心室侧、后壁",
      "分布于右心房",
      "分布于室间隔后1/3",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "分布于室间隔后1/3",
        "右冠状动脉（后室间支）分布于右心房、部分右心室、室间隔后1/3、部分左心室后壁、窦房结和房室结等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1010",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于纤维性心包的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "分为脏层和壁层",
      "与膈胸膜相贴",
      "在大血管根部移行心外膜",
      "与血管外膜相延续",
      "形成心包腔",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "与血管外膜相延续",
        "纤维性心包为致密结缔组织囊，与大血管的外膜相延续；浆膜性心包分脏、壁层，脏壁层移行形成心包腔。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1011",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "心舒张时，防止血液逆行流动的装置是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "主动脉瓣、三尖瓣",
      "二尖瓣、三尖瓣",
      "主动脉瓣、肺动脉瓣",
      "肺动脉瓣、三尖瓣",
      "主动脉瓣、二尖瓣",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "主动脉瓣、肺动脉瓣",
        "心室舒张时二、三尖瓣开放，而主动脉瓣和肺动脉瓣关闭，防止血液从主动脉和肺动脉反流回心室。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1012",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "室间隔膜部分隔",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "左心室与右心室",
      "右心室与左心房",
      "左心房与左心室、右心房",
      "右心室与左心室、左心房",
      "左心室与右心室、右心房",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "左心室与右心室、右心房",
        "室间隔膜部分为房室部和室间部：房室部介于右心房与左心室之间，室间部介于左、右心室之间，故膜部分隔左心室与右心室、右心房。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1013",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于颈总动脉的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "右侧的起自升主动脉",
      "约平对甲状软骨上缘高度分出颈内动脉和颈外动脉",
      "左侧的起自头臂干",
      "走行于气管和喉的后方",
      "颈动脉窦位于颈总动脉的起始处",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "约平对甲状软骨上缘高度分出颈内动脉和颈外动脉",
        "颈总动脉在甲状软骨上缘高度分为颈内动脉和颈外动脉；左侧直接起自主动脉弓，右侧起自头臂干。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1014",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "颈动脉窦",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "可感受血液中氧分压的变化",
      "位于颈外动脉的起始处",
      "化学感受器",
      "为压力感受器",
      "可感受血液中二氧化碳分压的变化",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "为压力感受器",
        "颈动脉窦是颈总动脉末端和颈内动脉起始部的膨大部分，壁内含有特殊的感觉神经末梢，属于压力感受器。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1015",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于肱动脉的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "与肌皮神经伴行",
      "发出旋肱前动脉",
      "沿肱二头肌外侧沟下行",
      "沿肱二头肌内侧沟下行",
      "发出旋肱后动脉",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "沿肱二头肌内侧沟下行",
        "肱动脉在大圆肌下缘续于腋动脉，沿肱二头肌内侧沟下行至肘窝，分支有肱深动脉及尺、桡动脉等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1016",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "掌浅弓的组成是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "由骨间总动脉与桡动脉末端吻合形成",
      "由尺动脉的末端与桡动脉的末端吻合形成",
      "由尺动脉的掌深支与桡动脉的掌浅支吻合形成",
      "由尺动脉末端与桡动脉掌浅支吻合形成",
      "以上都不正确",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "由尺动脉末端与桡动脉掌浅支吻合形成",
        "掌浅弓由尺动脉的末端和桡动脉的掌浅支吻合形成，位于掌腱膜和指浅、深屈肌腱之间。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1017",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于肾动脉的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "平对第2~3腰椎椎间盘的高度发自腹主动脉",
      "仅分布于肾",
      "发出肾上腺上动脉",
      "平对第1~2腰椎椎间盘的高度发自腹主动脉",
      "以上都不正确",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "平对第1~2腰椎椎间盘的高度发自腹主动脉",
        "肾动脉约平第1~2腰椎椎间盘高度发自腹主动脉，除分布于肾外，还发出肾上腺下动脉分布于肾上腺。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1018",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于肠系膜上动脉的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "供应范围包括空肠、升结肠、横结肠和降结肠",
      "分支有左结肠动脉",
      "平对第1腰椎高度起自腹主动脉前壁",
      "分支包括胰十二指肠上动脉",
      "以上都不正确",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "平对第1腰椎高度起自腹主动脉前壁",
        "肠系膜上动脉约平第1腰椎高度起自腹主动脉前壁，分布于空肠、回肠、盲肠、升结肠和横结肠等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1019",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于肠系膜下动脉的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "左结肠动脉发自肠系膜下动脉",
      "发出后行向右下方",
      "分支分布于横结肠、降结肠、乙状结肠和全部直肠",
      "约平对第2腰椎的高度起自腹主动脉前壁",
      "以上都不正确",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "左结肠动脉发自肠系膜下动脉",
        "肠系膜下动脉分支有左结肠动脉、乙状结肠动脉和直肠上动脉，主要分布于降结肠、乙状结肠和直肠上部。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1020",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "面静脉与翼丛相交通的静脉是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["内眦静脉", "面深静脉", "眼上静脉", "颞浅静脉", "眼下静脉"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "面深静脉",
        "面静脉通过面深静脉与翼丛相交通，又可借眼上、眼下静脉与颅内海绵窦交通，是面部感染向颅内扩散的途径之一。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1021",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "颈前静脉注入",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "颈内静脉",
      "头臂静脉",
      "颈静脉弓",
      "颈外静脉",
      "面静脉",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈外静脉",
        "颈前静脉多与对侧同名静脉吻合形成颈静脉弓后汇入颈外静脉。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1022",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于锁骨下静脉的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "在第1肋外侧缘续于腋静脉",
      "行于腋动脉的后上方",
      "在前斜角肌后方与颈外静脉汇合",
      "属支是颈内静脉",
      "右淋巴导管注入",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "在第1肋外侧缘续于腋静脉",
        "锁骨下静脉在第1肋外侧缘续于腋静脉，与颈内静脉在同侧胸锁关节后方汇合成头臂静脉。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1023",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于头静脉的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "经贵要静脉与肘正中静脉交通",
      "起自手背静脉网的尺侧",
      "经肱二头肌内侧沟上行",
      "收集前臂尺侧半的静脉血",
      "注入腋静脉或锁骨下静脉",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "注入腋静脉或锁骨下静脉",
        "头静脉起自手背静脉网的桡侧，沿前臂桡侧、肱二头肌外侧沟上行，经三角肌胸大肌间沟穿深筋膜注入腋静脉或锁骨下静脉。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-a1024",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于上腔静脉的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "穿纤维心包前有奇静脉注入",
      "沿升主动脉左侧下行",
      "接受肋间后静脉",
      "由头臂静脉和锁骨下静脉汇合形成",
      "收集上腹部器官的静脉血",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "穿纤维心包前有奇静脉注入",
        "上腔静脉由左、右头臂静脉汇合而成，沿升主动脉右侧下行，穿纤维心包前有奇静脉注入，收集头颈部、上肢及胸部（心和肺除外）的静脉血。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），10 道 */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-human-anatomy-ch10-cardiovascular-fill001",
    order: 31,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "体循环起自____，静脉回流至____；肺循环起自____，左、右肺静脉回流至____；肺静脉内流动的血液是____血。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①左心室 ②右心房 ③右心室 ④左心房 ⑤动脉",
        "体循环起自左心室、终于右心房；肺循环起自右心室、终于左心房，肺静脉内流动的是动脉血。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-fill002",
    order: 32,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "心尖朝向____一方，由____构成，在左侧第____肋间隙或锁骨中线____侧1~2cm处可触摸到心尖搏动。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①左前下 ②左心室 ③5 ④内",
        "心尖朝向左前下方，由左心室构成，平对左侧第5肋间隙，在左锁骨中线内侧1~2cm处可触到心尖搏动。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-fill003",
    order: 33,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "在心的表面，区分心房与心室的标志是____，区分左、右心室的标志是____和____，区分左、右心房的标志是____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①冠状沟 ②前室间沟 ③后室间沟 ④后房间沟",
        "冠状沟为心房与心室的表面分界标志，前、后室间沟为左、右心室的表面分界标志，后房间沟为左、右心房的表面分界标志。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-fill004",
    order: 34,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "房间隔最薄弱处为____，是____的好发部位；室间隔最薄弱处是____，是____的好发部位。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①卵圆窝 ②房间隔缺损 ③室间隔膜部 ④室间隔缺损",
        "卵圆窝为房间隔最薄弱处，是房间隔缺损的好发部位；室间隔膜部最薄弱，是室间隔缺损的好发部位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-fill005",
    order: 35,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "心的正常起搏点是____，位于____与____交界处心外膜的深面；房室结能将____传来的冲动传向____，具有____和____的特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①窦房结 ②上腔静脉 ③右心房 ④窦房结 ⑤心室 ⑥传导 ⑦延搁",
        "窦房结位于上腔静脉与右心房交界处心外膜的深面，是心的正常起搏点；房室结能将窦房结传来的冲动传向心室，并具有传导和延搁的特点。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-fill006",
    order: 36,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "心的静脉主要经____回流至右心房，由____、____和____静脉汇合成，在右心房的开口处称为____；一部分心的静脉，如心前静脉可直接注入____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①冠状窦 ②心大静脉 ③心中静脉 ④心小静脉 ⑤冠状窦口 ⑥右心房",
        "心的静脉血大部分经冠状窦回流至右心房，冠状窦由心大静脉、心中静脉和心小静脉汇合而成；心前静脉直接注入右心房，心最小静脉直接开口于各心腔。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-fill007",
    order: 37,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "房室束起自____前端，穿过____，沿____后下缘前行，至室间隔肌部上缘分分为左、右束支。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①房室结 ②右纤维三角 ③室间隔膜部",
        "房室束起自房室结前端，穿右纤维三角，沿室间隔膜部后下缘前行，至室间隔肌部上缘分叉为左、右束支。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-fill008",
    order: 38,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "左颈总动脉起自____，右颈总动脉起自____，至甲状软骨上缘高度分为____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①主动脉弓 ②头臂干 ③颈内动脉 ④颈外动脉",
        "左侧颈总动脉直接起自主动脉弓，右侧颈总动脉起自头臂干，均于甲状软骨上缘高度分为颈内动脉和颈外动脉。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-fill009",
    order: 39,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "头面部大出血时，将____动脉压向第____颈椎的____进行急救止血；上肢出血时可将____动脉向后下压向____进行止血。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①颈总动脉 ②6 ③颈动脉结节 ④锁骨下动脉 ⑤第1肋",
        "一侧头面部出血时将颈总动脉压向第6颈椎横突（颈动脉结节）；上肢出血时将锁骨下动脉向后下方压向第1肋骨。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-fill010",
    order: 40,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "头臂静脉由____和____在____后方汇合形成。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①颈内静脉 ②锁骨下静脉 ③胸锁关节",
        "左、右头臂静脉分别由同侧颈内静脉和锁骨下静脉在胸锁关节后方汇合形成。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 判断改错题 + 问答题（short-answer），12 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-human-anatomy-ch10-cardiovascular-short001",
    order: 41,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt:
      "判断题（叙述正确者打“对”，错误者改正）：脉管系统既是运输管道，又具有内分泌功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "正确",
        "脉管系统不仅输送血液、营养物质和激素等，血管内皮等结构本身也具内分泌功能，故叙述正确。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-short002",
    order: 42,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题（叙述正确者打“对”，错误者改正）：心传导系由神经组织构成。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错误；应将“神经组织”改为“特殊的心肌细胞”",
        "心传导系由特殊分化的心肌细胞构成（包括窦房结、结间束、房室结、房室束、左右束支及 Purkinje 纤维），而非神经组织。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-short003",
    order: 43,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题（叙述正确者打“对”，错误者改正）：房室结是心自动节律性兴奋的发源地。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错误；应将“房室结”改为“窦房结”",
        "心的自动节律性兴奋发源于窦房结；房室结具有次级起搏作用，位于房室交界区中央部，尚有延搁传导作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-short004",
    order: 44,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题（叙述正确者打“对”，错误者改正）：冠状窦位于左、右心房之间的冠状沟后部。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错误；应将“左、右心房之间”改为“左心房与左心室之间”",
        "冠状窦位于左心房与左心室之间的冠状沟后部，引流心的大部分静脉血，开口于右心房的冠状窦口。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-short005",
    order: 45,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题（叙述正确者打“对”，错误者改正）：心在发育过程中出现了沿纵轴向右的轻度旋转。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错误；应将“向右”改为“向左”",
        "心在发育过程中沿纵轴向左发生轻度旋转，从而使右心偏于右前上方、左心偏于左后下方。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-short006",
    order: 46,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题（叙述正确者打“对”，错误者改正）：左、右颈总动脉均直接发自主动脉弓。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错误；应将“右颈总动脉均直接发自主动脉弓”改为“右侧颈总动脉发自头臂干”",
        "左侧颈总动脉直接发自主动脉弓，右侧颈总动脉则发自头臂干。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-short007",
    order: 47,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题（叙述正确者打“对”，错误者改正）：子宫动脉在子宫颈的外侧2cm处，从输尿管的后方跨越。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错误；应将“后方”改为“前方”",
        "子宫动脉在子宫颈外侧约2cm处从输尿管前方跨越，行子宫手术结扎子宫动脉时须避免误伤输尿管。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-short008",
    order: 48,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断题（叙述正确者打“对”，错误者改正）：左侧睾丸静脉注入下腔静脉，右侧睾丸静脉注入右肾静脉。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错误；应将“左侧睾丸静脉注入下腔静脉，右侧睾丸静脉注入右肾静脉”改为“左侧睾丸静脉注入左肾静脉，右侧睾丸静脉注入下腔静脉”",
        "左侧睾丸静脉注入左肾静脉，右侧睾丸静脉以直角注入下腔静脉，故左侧精索静脉曲张较右侧多见。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-short009",
    order: 49,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述心房与心室和左、右心室的表面分界标志及其内的结构。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心房与心室的表面分界标志是冠状沟，左、右心室的表面分界标志是前、后室间沟。冠状沟右侧部内主要有右冠状动脉和心小静脉，左侧部内主要有左冠状动脉，冠状沟后部有冠状窦；前室间沟内有前室间支和心大静脉，后室间沟内有后室间支和心中静脉。",
        "左、右心房的表面分界标志为后房间沟；冠状动脉及静脉主干沿这些沟走行，是解剖学定位和临床上手术常用标志。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-short010",
    order: 50,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述左、右冠状动脉的起始、行程及主要分支。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "右冠状动脉起自主动脉右窦，在右心耳与肺动脉干根部之间进入冠状沟，绕行至房室交点附近分为后室间支和右旋支，主要分支有右缘支、后室间支、右旋支、右心房支和房室结支，分布于右心房、部分右心室、室间隔后1/3、部分左心室后壁、窦房结和房室结等。左冠状动脉起自主动脉左窦，分为前室间支和旋支，前室间支沿前室间沟走行并绕心尖切迹至后室间沟，与后室间支吻合，分出左心室前支、右心室前支和室间隔前支，分布于左心室前壁、部分右心室前壁、室间隔前2/3、前乳头肌、心尖及左右束支；旋支沿冠状沟向左行，分出左缘支、左心室后支、窦房结支等，分布于左心房、部分左心室前壁及左心室侧壁和后壁。",
        "前室间支栓塞可引起左心室前壁等心肌梗死，旋支栓塞常引起左心室侧壁梗死，后室间支供应室间隔后1/3。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-short011",
    order: 51,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述心室的分部及心腔内的主要结构。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "右心室以室上嵴为界分为窦部（流入道）和漏斗部（流出道，亦称动脉圆锥），窦部室壁有纵横交错的肉柱、前中隔三群乳头肌及节制索（隔缘肉柱）等，入口为右房室口及其三尖瓣，出口为肺动脉口及肺动脉瓣，纤维环为肺动脉瓣环。左心室以二尖瓣前尖为界分为窦部（流入道）和主动脉前庭（流出道），窦部的入口为左房室口，周缘附有二尖瓣及其腱索和乳头肌，出口为主动脉口，周缘附着有主动脉瓣。",
        "节制索（隔缘肉柱）内通过右束支；左心室出口经主动脉前庭通向主动脉口。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-short012",
    order: 52,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述心室舒张及收缩时瓣膜的活动情况，心腔内血液的流动方向。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心室舒张时，二、三尖瓣开放，主、肺动脉瓣关闭；心室收缩时，二、三尖瓣关闭，主、肺动脉瓣开放。心腔内血液流动方向：上、下腔静脉和冠状窦→右心房→右房室口→右心室流入道→右心室流出道→肺动脉口→肺动脉干→肺动脉→肺毛细血管网→左、右肺静脉→左心房→左房室口→左心室流入道→左心室流出道→主动脉口→主动脉。",
        "房室瓣借腱索和乳头肌牵拉而不致翻向心房，防止血液逆流回心房；主、肺动脉瓣防止血液由大动脉反流回心室。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，3 组（4+4+3 成员） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-human-anatomy-ch10-cardiovascular-b001",
    order: 53,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["冠状沟", "前室间沟", "后室间沟", "界沟", "房间沟"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-human-anatomy-ch10-cardiovascular-b001m1",
        order: 53,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "右冠状动脉主干走行于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "冠状沟",
            "右冠状动脉主干在右心耳与肺动脉干之间进入冠状沟走行，绕至房室交点附近分支。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch10-cardiovascular-b001m2",
        order: 54,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "心中静脉走行于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "后室间沟",
            "心中静脉沿后室间沟上行，与右冠状动脉的后室间支伴行，注入冠状窦。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch10-cardiovascular-b001m3",
        order: 55,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "心大静脉走行于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "前室间沟",
            "心大静脉沿前室间沟上行，与左冠状动脉前室间支伴行，延续为冠状窦。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch10-cardiovascular-b001m4",
        order: 56,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "心房与心室的表面分界标志是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "冠状沟",
            "冠状沟是环绕心的表面的环形沟，为心房与心室的表面分界标志。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-b002",
    order: 57,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "左冠状动脉旋支",
      "左冠状动脉前室间支",
      "右冠状动脉主干",
      "右冠状动脉后室间支",
      "右冠状动脉左心室后支",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-human-anatomy-ch10-cardiovascular-b002m1",
        order: 57,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "引起左心室侧壁心肌梗死的动脉是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "左冠状动脉旋支",
            "旋支沿冠状沟向左行并主要分布于左心室侧壁及后壁，其阻塞可致左心室侧壁心肌梗死。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch10-cardiovascular-b002m2",
        order: 58,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "左心室前壁和室间隔前部心肌梗死由哪个动脉分支闭塞所致的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "左冠状动脉前室间支",
            "前室间支分布于左心室前壁、部分右心室前壁及室间隔前2/3等，其闭塞可引起该区域心肌梗死。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch10-cardiovascular-b002m3",
        order: 59,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "房室结（动脉）支一般起自",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "右冠状动脉主干",
            "房室结支一般由右冠状动脉主干在房室交点附近发出，分布于房室结。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch10-cardiovascular-b002m4",
        order: 60,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "供应室间隔后1/3部的动脉是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "右冠状动脉后室间支",
            "后室间支沿后室间沟下行，分布于右心室及室间隔后1/3部。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch10-cardiovascular-b003",
    order: 61,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "压迫颈总动脉进行止血",
      "压迫颞浅动脉进行止血",
      "压迫面动脉进行止血",
      "压迫锁骨下动脉进行止血",
      "压迫股动脉进行止血",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-human-anatomy-ch10-cardiovascular-b003m1",
        order: 61,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "一侧头面部出血",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "压迫颈总动脉进行止血",
            "一侧头面部出血时，在环状软骨弓两侧向内后方将颈总动脉压向第6颈椎横突（颈动脉结节）以止血。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch10-cardiovascular-b003m2",
        order: 62,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "面颊部出血",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "压迫面动脉进行止血",
            "面颊部出血时，在下颌骨下缘与咬肌前缘相交处将面动脉压向下颌骨止血。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch10-cardiovascular-b003m3",
        order: 63,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "上肢出血",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "压迫锁骨下动脉进行止血",
            "整个上肢出血时，在锁骨中点上方1~2指处，向后下方将锁骨下动脉压向第1肋骨止血。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...fillItems,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];