import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 系统解剖学习题集（第2版）— 第1章 骨学 题库提取（等比取样）
 * 来源：《系统解剖学习题集》第2版（人民卫生出版社，以柏树令主编《系统解剖学》第8版为蓝本）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：6 题
 * - A1/A2/A3 型选择题（a1-single）：9 题
 * - 填空题（fill）：5 题
 * - 判断改错题 + 问答题（short-answer）：8 题（判断改错 6 题 + 问答题 2 题）
 * - B1 配伍题：1 组、共 5 个成员
 * - 独立记分题合计：33 题（须等于本文件预算 33）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含选择题（A1 型 70、A2 型 15、A3 型 15、B1 型 4 组 20 小题）、
 *   填空题 20、名词解释 30、判断改错题 30、问答题 10；本文件按 33 道预算等比取材并在
 *   原书顺序内取满。A2/A3 型按项目规约与 A1 型一起映射为 a1-single。判断题「含气骨属于
 *   不规则骨」（正确）、「骶角是骶管麻醉的体表标志」（正确）与问答题均取自源参考答案。
 *   OCR 错字已按医学语义恢复（如「沩/力/分力」→为、「变形体」→整骨等），骨名、孔道、
 *   数字（肋对数、椎骨数、第2/4肋、第7颈椎等）与单位均保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "human-anatomy-ch1-osseous";
const locatorBase =
  "《系统解剖学习题集》第2版 第1章 骨学 复习思考题 习题（扫描版原书核对PDF 第11–27页）";
const promptNote =
  "题干改写；原题来自用户提供的扫描题集（OCR 已按医学语义恢复），未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多选，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据扫描题集整理并改写，未经权威教材交叉核对，OCR 错字已按医学语义恢复";

const kp = `kp-${topic}`;

/** 名词解释（term），6 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-human-anatomy-ch1-osseous-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：骺软骨",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骺软骨",
        "骨干与骺相邻的部分称为干骺端，幼年时保留软骨成分，称为骺软骨。骺软骨细胞能不断分裂繁殖和骨化，使骨不断加长。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：骺线",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骺线",
        "成年后，骺软骨骨化，骨干与骺融为一体，其间遗留下来一条线状痕迹，称为骺线。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：骨松质",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骨松质",
        "呈海绵状，由相互交织的骨小梁排列形成，分布于骨的内部。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：板障",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "板障",
        "颅盖骨表层为密质，分别称为内板和外板，两板之间的松质称为板障，内有板障静脉通过。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：骨髓",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骨髓",
        "充填于骨髓腔和松质间隙内，分为红骨髓和黄骨髓。红骨髓有造血功能，黄骨髓含有大量脂肪组织。在失血过多或重度贫血时，黄骨髓可在一定程度上转化为红骨髓，恢复造血功能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：胸骨角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸骨角",
        "胸骨柄和胸骨体连结处微向前突，称为胸骨角。可在体表扪及，两侧平对第2肋，是计数肋的重要标志。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2/A3 型选择题（统一映射为 a1-single），9 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-human-anatomy-ch1-osseous-a1001",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胸椎",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "棘突向后平伸",
      "椎体大",
      "横突末端前面有横突肋凹",
      "棘突末端分叉",
      "有横突孔",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "横突末端前面有横突肋凹",
        "胸椎横突末端的前面有横突肋凹，与肋结节相关节；胸椎有椎体肋凹、棘突长伸向后下方、关节突关节面呈冠状位。原书 A1 答案第 1 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-a1002",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "属于长骨的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["胸骨", "桡骨", "肩胛骨", "下颌骨", "肋骨"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "桡骨",
        "桡骨为前臂长骨，中间有骨髓腔、两端膨大，属长骨；胸骨、肩胛骨属扁骨，下颌骨属不规则骨，肋骨与桡骨不同属扁骨类。原书 A1 答案第 2 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-a1003",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "骺线位于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "短骨",
      "长骨的骨干与骺之间",
      "长骨骨干",
      "扁骨",
      "长骨骺端",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "长骨的骨干与骺之间",
        "骺线是成年后骺软骨骨化遗留的痕迹，位于长骨的骨干与骺之间。原书 A1 答案第 3 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-a1004",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "颈椎",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "棘突末端都分叉",
      "第2颈椎又称为寰椎",
      "第7颈椎又称为隆椎",
      "第1、2颈椎无横突孔",
      "均有椎体",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第7颈椎又称为隆椎",
        "第7颈椎棘突长、末端不分叉，在皮下易于触及，称为隆椎；第1颈椎称寰椎、第2颈椎称枢椎，均有横突孔。原书 A1 答案第 4 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-a1005",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "腰椎",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["棘突宽短呈板状", "椎体横断面呈心形", "棘突分叉"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "棘突宽短呈板状",
        "腰椎椎体粗壮、椎体横断面呈肾形，棘突宽短呈板状、近似水平伸向后方，关节突关节面几乎呈矢状位。原书 A1 答案第 5 题为 C。扫描版缺 D、E 两项，按现有选项如实保留。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-a1006",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肋",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肋结节与椎体肋凹相关节",
      "呈长条形，属于长骨",
      "第2肋平对胸骨角",
      "上6对肋直接与胸骨相连故称为真肋",
      "第8~12肋组成肋弓",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第2肋平对胸骨角",
        "胸骨角两侧平对第2肋，是计数肋的重要标志。肋属扁骨；真肋为上7对（直接连胸骨），假肋为第8~10对借肋软骨连上位肋软骨构成肋弓，浮肋为第11~12对。原书 A1 答案第 6 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-a1007",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "上颌窦",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "开口于下鼻道",
      "窦口低于窦底部",
      "位于上颌骨体内",
      "开口于上鼻道",
      "窦顶为颧弓",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "位于上颌骨体内",
        "上颌窦位于上颌骨体内，窦口高于窦底、开口于中鼻道（引流不畅），窦顶为眶下壁而非颧弓。原书 A1 答案第 7 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-a1008",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胸骨",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胸骨体外侧缘连结第2~8肋软骨",
      "胸骨角向后平对第4胸椎体",
      "由胸骨柄和胸骨体组成",
      "上7对肋软骨与胸骨之间均为滑膜关节",
      "胸骨角平对第4肋",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸骨角向后平对第4胸椎体",
        "胸骨由胸骨柄、胸骨体和剑突组成；胸骨角向前平对第2肋、向后平对第4胸椎体。胸骨体外侧缘连结第2~7肋软骨，与胸骨相连的肋软骨连结多为软骨连结而非滑膜关节。原书 A1 答案第 8 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-a1009",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "蝶窦开口于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["中鼻道后部", "下鼻道", "蝶筛隐窝", "上鼻道", "中鼻道中部"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "蝶筛隐窝",
        "蝶窦开口于上鼻甲后上方与蝶骨之间的蝶筛隐窝。原书 A1 答案第 9 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），5 道 */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-human-anatomy-ch1-osseous-fill001",
    order: 16,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "按形态可将骨分为___四类。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "长骨、短骨、扁骨、不规则骨",
        "按形态骨可分为长骨（一体两端）、短骨（近似立方形）、扁骨（板状，如颅盖骨）和不规则骨（形态不规则，如椎骨）。原书填空题第 1 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-fill002",
    order: 17,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "骨的基本结构包括___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骨质、骨膜、骨髓",
        "骨的基本结构包括骨质（骨密质与骨松质）、骨膜（内、外骨膜）和骨髓。原书填空题第 2 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-fill003",
    order: 18,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "骨髓充填于___和___内，分为___和___两种。___骨髓具有造血功能，___骨髓是脂肪组织。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骨髓腔、松质间隙；红骨髓、黄骨髓；红；黄",
        "红骨髓充填于骨髓腔和松质间隙内，有造血功能；黄骨髓含大量脂肪组织，为脂肪组织。原书填空题第 3 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-fill004",
    order: 19,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "椎骨由位于前方的___和后方的___组成。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "椎体（前方）；椎弓（后方，两者围成椎孔）",
        "椎骨由前部的椎体和后部的椎弓组成，二者共同围成椎孔，椎孔上下贯通形成椎管。原书填空题第 6 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-fill005",
    order: 20,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "由椎弓上发出7个突起，包括成对的___和不成对的___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "横突、上关节突、下关节突（成对，各 1 对）；棘突（不成对，1 个）",
        "椎弓上发出 7 个突起：成对的横突、上关节突、下关节突（共 6 个）和不成对的棘突（1 个）。原书填空题第 7 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 判断改错题 + 问答题（short-answer），8 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-human-anatomy-ch1-osseous-short001",
    order: 21,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断改错：成人有 206 块骨，不包括听小骨。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错误；应改为「成人有 206 块骨，包括听小骨」（共 206 块骨含 6 块听小骨）",
        "成人共有 206 块骨，其中包括 6 块听小骨（锤骨、砧骨、镫骨各 2 块）。原书判断改错第 1 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-short002",
    order: 22,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断改错：按照形态，骨可分为长骨、短骨、扁骨、籽骨。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错误；应将「籽骨」改为「不规则骨」",
        "按形态骨分为长骨、短骨、扁骨和不规则骨四类；籽骨如髌骨是包于肌腱内的小骨，不属于形态分类的一类。原书判断改错第 2 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-short003",
    order: 23,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断改错：含气骨属于不规则骨。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "正确",
        "含气骨（如额骨、蝶骨、筛骨、上颌骨等）内含空气的空腔，其外形不规则，属于不规则骨。原书判断改错第 3 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-short004",
    order: 24,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断改错：颈椎的棘突都分叉。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错误；应改为「第2~6颈椎棘突较短、末端分叉，第7颈椎棘突不分叉」（隆椎棘突不分叉、特长，皮下易于触及）",
        "第2~6颈椎棘突末端分叉，第7颈椎（隆椎）棘突特长且末端不分叉。原书判断改错第 9 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-short005",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断改错：骶角是骶管麻醉的体表标志。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "正确",
        "骶管裂孔两侧向下的突起称为骶角，是骶管麻醉的重要体表标志，可据此定位骶管裂孔进行骶管麻醉。原书判断改错第 14 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-short006",
    order: 26,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "判断改错：胸骨角两侧平对第4肋。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "错误；应改为「胸骨角两侧平对第2肋」",
        "胸骨角两侧平对第2肋，向后平对第4胸椎体下缘，是计数肋的重要标志。原书判断改错第 17 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-short007",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：颈椎、胸椎和腰椎各有何主要形态特点？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈椎、胸椎和腰椎的主要形态特点",
        "①颈椎：椎体小、椎孔大呈三角形；横突有孔（横突孔）；上、下关节突关节面几乎呈水平位；第2~6颈椎棘突较短、末端分叉，第7颈椎（隆椎）棘突特长、皮下易于触及。第3~7颈椎体上面侧缘向上突起为椎体钩，若与上位椎体下面两侧唇缘相接则形成钩椎关节。第1颈椎（寰椎）无椎体、棘突和关节突，由前弓、后弓和侧块构成；第2颈椎（枢椎）椎体上有向上突起的齿突。②胸椎：椎体侧面有肋凹；横突末端前面有横突肋凹；关节突的关节面几乎呈冠状位；棘突长、伸向后下方并呈叠瓦状排列。③腰椎：椎体粗壮；关节突粗大、关节面几乎呈矢状位；棘突宽扁呈板状、近似水平伸向后方。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-human-anatomy-ch1-osseous-short008",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：在活体上，能摸到躯干骨的哪些重要的骨性标志？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "躯干骨的骨性标志",
        "躯干骨的骨性标志主要有：第7颈椎棘突、胸椎和腰椎的棘突（可在背部正中线上触及）、颈静脉切迹、胸骨角、剑突、第2~12对肋、肋弓、骶岬和骶角。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，1 组 × 5 成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-human-anatomy-ch1-osseous-b001",
    order: 29,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["趾骨", "髌骨", "顶骨", "腕骨", "蝶骨"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-human-anatomy-ch1-osseous-b001m1",
        order: 29,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "属于籽骨的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "髌骨",
            "髌骨是人体最大的籽骨，包于股四头肌腱内。原书 B1 第 1 题答案 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch1-osseous-b001m2",
        order: 30,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "属于长骨的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "趾骨",
            "趾骨为足部远节长骨，属长骨。原书 B1 第 2 题答案 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch1-osseous-b001m3",
        order: 31,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "属于短骨的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "腕骨",
            "腕骨为近似立方形、无髓腔的短骨。原书 B1 第 3 题答案 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch1-osseous-b001m4",
        order: 32,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "属于扁骨的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "顶骨",
            "顶骨为构成颅盖的板状扁骨。原书 B1 第 4 题答案 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-human-anatomy-ch1-osseous-b001m5",
        order: 33,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "属于不规则骨的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "蝶骨",
            "蝶骨形态不规则，属于不规则骨。原书 B1 第 5 题答案 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...fillItems,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];