import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 生物化学与分子生物学学习指导与习题集 — 第1章 蛋白质 结构与功能 题库提取（等比取样）
 * 来源：《生物化学与分子生物学学习指导与习题集》（人民卫生出版社，主编：周春燕）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：8 题
 * - A1/A2 型选择题（a1-single）：14 题（均为 A1 型单选）
 * - 简答题（short-answer）：6 题
 * - B1 配伍题：1 组、共 3 个成员
 * - 独立记分题合计：31 题（含 B1 组成员；须等于本文件预算 31）
 * - 缺失答案：0；无法可靠提取：0（换题如实说明见下）
 * - 换题说明：原书本章依序含名词解释 16、A1 型选择题 59、A2 型选择题 10、
 *   B1 型配伍 8 组（70–89）、简答题 11。本文件按 31 道预算在 A1 型内按原书顺序取材，
 *   跳过因双栏 OCR 错位或多处文字残缺、或源参考答案与生物化学事实冲突而无法可靠锚定
 *   的题（如 A1 第 3 题选项残缺、第 8 题“属于二级结构”答案为三级结构的结构域、
 *   第 12 题“分子伴侣”答案误指血红蛋白、第 23 题“α亚基疏水黏性位点”、第 25 题
 *   肌红蛋白/血红蛋白一/三级结构描述与事实相反、第 32 题青霉素列为抗生素肽、第 33/38/
 *   39/40 题题干选项严重残缺、第 57 题免疫球蛋白转运等），实取 14 道可清洗还原的 A1 题，
 *   以保证正确项严谨对齐源参考答案（1.C 2.D 4.B 5.A 6.D 9.B 10.A 11.E 15.B 16.D 17.C
 *   18.B 19.A 20.E）。选项顺序已随机重排并同步 correctChoiceIndex（0 起）。
 * - 恢复说明：本书为原生文本层 PDF 但双栏排版错序，题干/选项被拆散（如
 *   a■螺旋/a•螺旋→α-螺旋、P-折叠→β-折叠、肽键、蛋白质构象病、分子伴侣、蛋白
 *   质等电点 pi 等），已按蛋白质结构与功能的生化医学语义恢复；数值（螺距 0.54nm、
 *   每 3.6 个残基、280nm、等电点 pi 4.7 等）、缩写（GSH/GSSG、Hb、Mb、SDS、pi）
 *   均保留原文，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "biochem-ch1-protein";
const locatorBase =
  "《生物化学与分子生物学学习指导与习题集》第1章 蛋白质 结构与功能 复习思考题 习题（核对原书PDF 第13–30页）";
const promptNote =
  "题干改写；原题来自用户提供的配套习题集（原生文本但双栏错序，已按医学语义恢复），未经第三方授权审核";
const answerNotice =
  "答案依据配套习题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），8 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-biochem-ch1-protein-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：蛋白质的一级结构（protein primary structure）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "蛋白质的一级结构",
        "在蛋白质/多肽中，以肽键相连的氨基酸的组成及排列顺序构成蛋白质的一级结构，还包括二硫键的位置。一级结构是决定蛋白质空间构象和功能的基础。一级结构中的主要化学键是肽键。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肽键（peptide bond）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肽键",
        "肽键是蛋白质一级结构中的主要化学键，是由一个氨基酸的α-羧基与另一个氨基酸的α-氨基脱去一分子水反应生成的酰胺键，具有部分双键的性质。氨基酸通过肽键相连构成肽/蛋白质。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：α-螺旋（α-helix）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "α-螺旋",
        "α-螺旋是蛋白质二级结构的主要形式之一，为右手螺旋，每 3.6 个氨基酸残基螺旋上升一圈，螺距为 0.54nm。氨基酸侧链（R 基团）伸向螺旋外侧；每个肽键的 N–H 与氨基端第 4 个肽键的羰基氧形成氢键，氢键方向与螺旋长轴基本平行，全部肽键都可形成氢键以稳固 α-螺旋。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：结构模体（structural motif）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结构模体",
        "结构模体由 2 个或 2 个以上二级结构肽段组成，是蛋白质分子中具有特定空间构象和特定功能的结构成分，又称折叠或超二级结构。例如锌指结构即由 1 个 α-螺旋和 2 个反平行 β-折叠组成，可结合锌离子，能与 DNA 或 RNA 结合。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：结构域（domain）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结构域",
        "结构域是多肽链在二级结构或超二级结构基础上形成的三级结构层次上的局部折叠区域，是球状蛋白质分子中独立折叠的三维空间结构单位，呈珠（或球）状，结构紧密，并各行其功能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：分子病（molecular disease）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "分子病",
        "分子病是因蛋白质一级结构发生变异所导致的疾病，其病因为基因突变所致。如镰状细胞贫血：血红蛋自β亚基第 6 位谷氨酸变异成缬氨酸，使脱氧 HbS 聚集形成纤维样沉淀，刺破红细胞引起溶血。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：分子伴侣（molecular chaperone）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "分子伴侣",
        "除一级结构为决定因素外，蛋白质空间构象的正确形成还需要分子伴侣的参与，包括热激蛋白和伴侣蛋白（如 GroEL/GroES）等。分子伴侣通过封闭待折叠肽链暴露的疏水区段并提供保护环环境，从而加速蛋白质折叠成天然构象或形成四级结构。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：蛋白质构象病（protein conformational diseases）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "蛋白质构象病",
        "若蛋白质的折叠发生错误，尽管其一级结构不变，但蛋白质的构象发生改变，仍可影响其功能，严重时可导致疾病发生，此类疾病称为蛋白质构象病。例如疯牛病（牛海绵状脑病）中致病性朊蛋白与正常型一级结构相同、构象却由 α-螺旋变为全 β-折叠。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2 型选择题（统一映射为 a1-single），14 道（均 A1 型，按原书顺序） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-biochem-ch1-protein-a1001",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "蛋白质肽键的化学本质是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["酰胺键", "氢键", "盐键", "疏水键", "离子键"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "酰胺键",
        "原书 A1 型选择题答案第一题为 C，即酰胺键。肽键由一个氨基酸的 α-羧基与另一个氨基酸的 α-氨基去一分子水缩合生成的酰胺键，具有部分双键的性质。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1002",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列氨基酸属于酸性氨基酸的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["Asp", "Val", "Ser", "Lys", "Met"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Asp",
        "原书 A1 型选择题答案第二题为 D，即天冬氨酸（Asp）为酸性氨基酸。在常见 20 种氨基酸中，天冬氨酸和谷氨酸属酸性（带负电荷）氨基酸。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1003",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列由于蛋白质一级结构改变而引起的分子病是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "镰刀型贫血",
      "老年性痴呆",
      "糖尿病",
      "疯牛病（牛海绵状脑病）",
      "白血病",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "镰刀型贫血",
        "原书 A1 型选择题答案第四题为 B，即镰刀型贫血。镰刀型贫血由血红蛋白 β 亚基第 6 位谷氨酸变异成缬氨酸、一级结构改变所致，是典型的分子病；疯牛病属蛋白质构象病，一级结构不变。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1004",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在蛋白质二级结构中，由于下列哪一种氨基酸残基的存在，而不能形成 α-螺旋",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["Tyr", "Pro", "Asp", "Ile", "Phe"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Pro",
        "原书 A1 型选择题答案第五题为 A，即脯氨酸（Pro）。脯氨酸为亚氨基酸，其侧链与主链形成刚性环状结构，不能形成 α-螺旋。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1005",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "蛋白质 α-螺旋的特点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "氨基酸侧链伸向外侧",
      "呈左手螺旋",
      "螺旋方向与长轴垂直",
      "螺旋力靠盐键维持",
      "呈双螺旋结构",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "氨基酸侧链伸向外侧",
        "原书 A1 型选择题答案第六题为 D，即 α-螺旋中氨基酸侧链伸向外侧。α-螺旋为右手螺旋，每 3.6 个残基上升一圈、螺距 0.54nm，靠肽键间氢键维持稳定。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1006",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "构成蛋白质的氨基酸均属 L 型，例外的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["甘氨酸", "丙氨酸", "亮氨酸", "脯氨酸", "组氨酸"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甘氨酸",
        "原书 A1 型选择题答案第九题为 B，即甘氨酸。构成蛋白质的氨基酸均属 L 型（甘氨酸除外），因为甘氨酸的 R 基团仅为氢原子，其 α-碳原子不是不对称碳原子，故无旋光异构。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1007",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一种物质不属于神经肽",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["谷胱甘肽", "脑啡肽", "β-内啡肽", "强啡肽", "孤啡肽"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "谷胱甘肽",
        "原书 A1 型选择题答案第十题为 A，即谷胱甘肽不属于神经肽。神经肽（如脑啡肽、β-内啡肽、强啡肽、孤啡肽）在神经传导中发挥重要作用；谷胱甘肽（三肽）是体内重要的还原剂。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1008",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于结构模体的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "结构模体是蛋白质肽段的一种折叠方式，它既可以是整条肽链的一部分，也可以是整个蛋白质",
      "指几个二级结构及其连接部分形成的比较稳定的区域，又称为折叠或者超二级结构",
      "某些简单的结构模体可以进一步组合成更为复杂的结构模体",
      "结构模体只是蛋白质结构的一部分，不是一个完整的蛋白质结构",
      "结构模体、折叠、超二级结构这三种说法在使用时并没有统一的规定，经常混用",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结构模体是蛋白质肽段的一种折叠方式，它既可以是整条肽链的一部分，也可以是整个蛋白质",
        "原书 A1 型选择题答案第十一题为 E，即上述说法是错误的。结构模体是蛋白质分子中的局部结构成分，只是蛋白质结构的一部分，代表超二级结构的折叠方式，不可能等于整个蛋白质。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1009",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于蛋白质分子组成的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "单纯蛋白质只由氨基酸组成",
      "根据蛋白质所含氨基酸组成分为单纯蛋白质和结合（缀合）蛋白质",
      "结合（缀合）蛋白质除氨基酸外还连接有其他化学基团，这些非氨基酸部分称为辅基，均通过范德华力与蛋白质部分相连",
      "蛋白质辅基都是金属离子",
      "细胞色素 c 是结合（缀合）蛋白质，铁离子与蛋白质部分的半胱氨酸残基以化学键相连",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单纯蛋白质只由氨基酸组成",
        "原书 A1 型选择题答案第十五题为 B，即此说法正确。单纯蛋白质只由氨基酸组成；结合（缀合）蛋白质除氨基酸外还连有辅基，辅基可通过共价键（如细胞色素 c 中血红素铁与蛋白质的化学键）相连，并非均为金属离子、亦非全由范德华力连接。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1010",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肽链方向性的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "C-端为肽链的起始，N-端是肽链的末尾",
      "有游离氨基的一端称氨基末端或 N-端",
      "有游离羧基的一端称为羧基末端或 C-端",
      "N-端为肽链的起始，C-端是肽链的末尾",
      "多肽是由氨基酸分子通过肽键连接而成的线性大分子",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "C-端为肽链的起始，N-端是肽链的末尾",
        "原书 A1 型选择题答案第十六题为 D，即该叙述错误。肽链起始端为 N-端（氨基末端），末尾为 C-端（羧基末端），题中说法把方向弄反了。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1011",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于蛋白质四级结构的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "具有 2 条多肽链的蛋白质不一定具有四级结构",
      "亚基与亚基之间呈特定的三维空间排布，并以共价键作连接",
      "在四级结构中，各亚基间的结合力主要是氢键和离子键，包括共价键",
      "由多个亚基构成的蛋白质称为多聚体，其亚基数量可以从 3 个到成百个",
      "只有 1 个亚基的蛋白质又可称为寡聚体",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "具有 2 条多肽链的蛋白质不一定具有四级结构",
        "原书 A1 型选择题答案第十七题为 C，即此说法正确。四级结构系各亚基的空间排布及相互作用；若两条多肽链分别各有独立完整三级结构才构成四/多聚体，否则不一定具备四级结构。各亚基间主要以非共价键（氢键、离子键、疏水作用等）连接。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1012",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下不参与维持蛋白质三级结构的作用力是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["肽键", "氢键", "范德华力", "疏水作用", "盐键"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肽键",
        "原书 A1 型选择题答案第十八题为 B，即肽键不参与维持蛋白质三级结构。三级结构的形成与稳定主要靠次级键（氢键、盐键、疏水作用、范德华力等）；肽键属一级结构的共价键。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1013",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下关于结构域的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "结构域是在多肽链二级结构或超二级结构的基础上形成的三级结构层次上的局部折叠区域",
      "结构域是球状蛋白质分子中独立折叠的三维空间结构单位，呈纤维状，结构疏松",
      "经过蛋白酶水解，结构域一旦从蛋白质整体结构中被分离，其构象也随之改变",
      "大多数结构域含有序列上连续的超过 200 个氨基酸残基，平均直径为 2.5nm",
      "分子质量较大的蛋白质常含有 2 个以上的球状或纤维状的结构域，但没有功能",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结构域是在多肽链二级结构或超二级结构的基础上形成的三级结构层次上的局部折叠区域",
        "原书 A1 型选择题答案第十九题为 A，即此说法正确。结构域呈珠（球）状、结构紧密，经蛋白酶水解分离后构象并不改变，一般含序列连续的 100~200 个氨基酸残基，各行其功能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-a1014",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于蛋白质一级结构的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "序列相似但非进化相关的 2 个蛋白质的序列，常被称为同源序列",
      "一级结构是指肽链中所有氨基酸残基的排列顺序",
      "一级结构是空间构象和功能的基础",
      "一级结构提供重要的生物进化信息",
      "一级结构比对常被用来预测蛋白质之间结构与功能的相似性",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "序列相似但非进化相关的 2 个蛋白质的序列，常被称为同源序列",
        "原书 A1 型选择题答案第二十题为 E，即该说法错误。同源序列强调共同进化祖先，若序列相似但非进化相关，则不能称同源序列，而常被称为相似序列或非同源相似。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），6 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-biochem-ch1-protein-short001",
    order: 23,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "氨基酸有哪些理化特征？这些特征对研究氨基酸有什么意义？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "① 两性解离（等电点）；② 呈色反应（茚三酮反应）；③ 含芳香环氨基酸的紫外吸收",
        "氨基酸的理化特征：① 两性离子特征：所有常见氨基酸都含可解离的 α-氨基和 α-羧基，溶解于水时呈两性离子（兼性离子/偶极离子），某一特定 pH 时解离成正负离子趋势相等、呈电中性，此时 pH 即为该氨基酸的等电点；② 呈色反应——茚三酮反应：茚三酮在弱酸性溶液中与 α-氨基酸共加热，引起氨基酸氧化脱氨、脱羧反应，生成蓝紫色化合物，最大吸收峰在 570nm，吸收峰大小与氨基酸释放的氨量成正比，可作为氨基酸定性定量分析的方法；③ 紫外吸收性质：含共轭双键的色氨酸、酪氨酸具有紫外吸收，最大吸收峰在 280nm 附近。这些理化共性及特性是氨基酸分离、纯化及定性、定量分析的依据。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-short002",
    order: 24,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "请问结构模体和结构域有什么差别？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结构模体＝二级结构及连接区形成的稳定折叠模式（超二级结构）；结构域＝三级结构层次上独立折叠的局部区域",
        "结构模体指几个二级结构及其连接部分形成的特别稳定的折叠模式，又称折叠或超二级结构，由 2~3 个二级结构折叠成相对简单的构象，往往是蛋白质肽链的一部分，具有特征性氨基酸序列（如锌指结构）。结构域是球状蛋白质分子中独立折叠的三维空间结构单位，呈珠（球）状、结构紧密，经蛋白酶水解分离后构象不变，一般含序列连续的 100~200 个残基；分子质量较大的蛋白质常含 2 个以上结构域，各行其功能。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-short003",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "为什么说多肽链具有方向性？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多肽链两端化学性质不同：N-端（游离氨基）与 C-端（游离羧基）",
        "蛋白质/多肽是由氨基酸分子通过肽键依次连接而成的线性大分子。肽键由一个氨基酸的 α-羧基与另一个氨基酸的 α-氨基脱去一分子水反应生成，因此多肽链一端总保留游离的 α-氨基，为氨基末端（N-端）；另一端总保留游离的 α-羧基，为羧基末端（C-端），故多肽链具有方向性，N-端为起始、C-端为末尾。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-short004",
    order: 26,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt:
      "什么是蛋白质的二级结构？常见的二级结构有哪些？二级结构对蛋白质空间结构有什么影响？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "二级结构＝肽链主链的局部空间构象；常见有 α-螺旋、β-折叠、β-转角、Ω环，靠氢键稳定",
        "蛋白质的二级结构指组成蛋白质肽链的主链的局部空间构象，即肽链主链骨架原子的相对空间位置，不涉及氨基酸残基侧链的构象。常见形式包括 α-螺旋、β-折叠、β-转角和 Ω 环，其稳定主要靠肽链内部和（或）肽链间的氢键。它们共同决定了肽链主链的空间走向：① α-螺旋为右手螺旋、每 3.6 个残基一圈、螺距 0.54nm，侧链伸向外侧；② β-折叠为伸展锯齿状结构，走向可相同或相反；③ β-转角常发生于肽链 180°反转时，通常由 4 个残基组成、第二个残基常为脯氨酸；④ Ω 环存在于球状蛋白质表面，以亲水残基为主，参与分子识别。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-short005",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "何谓蛋白质变性？影响蛋白质变性的因素有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "变性＝理化因素破坏蛋白质特定空间构象、改变理化性质并丧失生物活性；因素含物理与化学两大类",
        "在某些理化因素作用下，蛋白质分子内部的非共价键断裂、天然构象被破坏，引起理化性质改变、生物活性丧失，称为蛋白质变性。变性实质是维系空间结构的次级键断开、空间结构松解，但肽键未断裂、一级结构不变。引起变性的因素：① 物理因素——高温、紫外线、X 射线、超声波、剧烈震荡等；② 化学因素——强酸、强碱、尿素、去污剂（如 SDS）、重金属离子、有机溶剂等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-biochem-ch1-protein-short006",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "何谓蛋白质的两性解离？利用此性质分离纯化蛋白质常用的方法有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "两性解离＝蛋白质在溶液中既可带正电荷又可带负电荷；常用方法为电泳法和离子交换层析法",
        "蛋白质分子中带有可解离的氨基和羧基等基团，这些基团在不同 pH 溶液中可解离成正离子或负离子，因此蛋白质分子既可带正电荷又可带负电荷，这种性质称为蛋白质的两性解离。当溶液 pH＝等电点时净电荷为零。利用蛋白质的两性解离性质，常采用电泳法（如等电聚焦电泳）和离子交换层析法等分离纯化蛋白质。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，1 组 × 3 成员（原书某组题共用备选答案，依序对齐参考答案 80.D 81.A 82.E） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-biochem-ch1-protein-b001",
    order: 29,
    questionKind: "b1",
    status: "available",
    groupPrompt:
      "（以下各题共用备选答案）根据蛋白质的理化性质选择对应的概念或特性。",
    sharedChoices: [
      "蛋白质变性",
      "蛋白质沉淀",
      "蛋白质的凝固",
      "蛋白质的等电点",
      "蛋白质的胶体稳定性",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-biochem-ch1-protein-b001m1",
        order: 29,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "使蛋白质分子所带正、负电荷相等时溶液的 pH 是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "蛋白质的等电点",
            "原书 B1 型参考答案对应第 80 题为 D，即蛋白质的等电点。当溶液 pH 使蛋白质解离成正、负离子的趋势相等、净电荷为零时，该 pH 即为蛋白质的等电点（pI）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-biochem-ch1-protein-b001m2",
        order: 30,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "蛋白质空间结构被破坏，理化性质改变，并失去其生物学活性称为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "蛋白质变性",
            "原书 B1 型参考答案对应第 81 题为 A。在某些理化因素作用下蛋白质特定的空间构象被破坏，导致理化性质改变和生物学活性丧失，称为蛋白质变性。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-biochem-ch1-protein-b001m3",
        order: 31,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "水化膜和表面电荷主要影响蛋白质的什么特性",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "蛋白质的胶体稳定性",
            "原书 B1 型参考答案对应第 82 题为 E。蛋白质具有胶体性质，其水化膜和表面电荷使蛋白质颗粒在溶液中保持稳定而不易沉淀，是维持蛋白质胶体稳定性的重要因素。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];