import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 中医诊断学 — 第05知识单元 问诊 题库提取（分值源题底稿，全取并注明）
 * 来源：同学整理带答案材料（选择.pdf 18页扫描件 OCR + 6天背诵册原生文本）
 *
 * == 统计报告 ==
 * - 名词解释（term）：7 题
 * - 单选题（a1-single）：28 题（选项已随机重排并同步 correctChoiceIndex）
 * - 简答/问答（short-answer）：3 题
 * - 病案分析（case）：0 题
 * - B1 配伍题：0 组（本书无 B1/B2 型）
 * - 独立记分题合计：38 题（预算 B=38）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：单选题题号 7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,26,27,28,29,30,
 *   31,32,33,34,35,134 全部收录，每题补全为 5 项选项。正确项对照选择.pdf 页尾参考答案键号
 *   （OCR 常挤行/截断，按题号 + 中医诊断学医学语义归位）。键号缺失或截断题按医学语义复位
 *   正确项：17 肝郁乘脾（键号「17.0」OCR 不可判读，依「大便时干时稀」肝郁乘脾语义归位）、
 *   22 阴虚（键号行「220 D」错位，依「盗汗多阴虚」归位）、31 脾胃虚弱（键号行「D 31，」被
 *   截断，依「大便先干后稀多脾气虚」归位为 C）；其余题号键号与语义一致。134 阴虚渴饮按键号
 *   A 归位为「咽干少饮」。名词解释与简答题取材第2天背诵内容及答案 问诊部分 与 第6天背诵册，
 *   问寒热/问汗/问疼痛以短答大题表述，恶寒与畏寒、自汗与盗汗因此不再列为独立名词，避免名词
 *   与简答同一概念双计数；「里急后重」既作名词解释（日2/日6#15）又作单选题32痢疾特征（日2
 *   问二便）出现，为源材料双重归属，如实保留。OCR 错字已按中医诊断学医学语义恢复（绝汗、大汗、
 *   着痹、渴饮、经带等），数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "tcm-diagnostics-bank-ch05-wenzhen-wen";
const locatorBase =
  "《中医诊断学》题库底稿（同学整理带答案材料/6天背诵册） 第05知识单元 问诊";
const promptNote =
  "题干轻度改写（同义替换/语序/句式）；原题来自用户提供的同学整理带答案材料（含 OCR 恢复），答案以教材为准";
const answerNotice =
  "答案依据源参考答案/标准答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），7 道（问诊部分，主诉/现病史/二便/饮食口味等） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：主诉",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天/第6天背诵内容及答案 名词解释（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "主诉是促使患者就诊的最主要、最痛苦的症状或体征及其持续时间。",
        "书写要求：突出一个或两个主要症状、写明持续时间、简明扼要、一般不用诊断名称代替症状、不用笼统语言。例：反复心悸气短3年加重半年。第2天/第6天背诵内容及答案·问诊/名词解释部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：里急后重",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天/第6天背诵内容及答案 名词解释（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "里急后重指腹痛窘迫、时时欲便、肛门重坠、便出不爽的症状。",
        "多因湿热内阻、肠道气滞所致，常见于湿热痢疾或大肠气滞，是痢疾主症之一。第2天/第6天背诵内容及答案·名词解释部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：现病史",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 名词解释（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "现病史是围绕本次疾病的发生、发展、诊治经过和现状的病史。",
        "内容包括：起病情况（时间、诱因、缓急）、主要症状的部位性质程度持续时间及加减因素、病情发展演变、伴随症状、诊治经过和疗效、发病以来精神饮食睡眠二便等一般情况。第2天背诵内容及答案·问诊部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：五更泻",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 名词解释（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "五更泻又称鸡鸣泻，指黎明前腹痛作泻、泻后则安者。",
        "多属脾肾阳虚、命门火衰，常兼腰膝酸软、畏寒肢冷；据此可辨脾肾阳气不足。第2天背诵内容及答案·问二便部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：癃闭",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 名词解释（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "癃闭指小便点滴而出为癃，点滴不出为闭的排尿障碍。",
        "实证多因膀胱湿热、瘀血或结石阻塞水道，常伴小腹胀急、尿道涩痛；虚证多因肾阳不足、气化无力，常伴排尿无力、面白神疲、腰膝酸软。第2天背诵内容及答案·问二便部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：纳呆",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 名词解释（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "纳呆指无饥饿感、食不知味，多因湿邪困脾所致。",
        "纳少为食量减少多偏脾胃气虚，纳呆为无食欲多偏湿困脾，厌食为厌恶食物常见食积湿热或妊娠；三者宜区分。第2天背诵内容及答案·饮食与口味部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：除中",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 名词解释（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "除中指久病重病本不能食，却突然食欲亢进者，为脾胃之气将绝的危候。",
        "与食欲逐渐改善的真复相区别，除中为暂时性假象，提示胃气败绝、预后不良，属危重征象。第2天背诵内容及答案·饮食与口味部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 单选题（a1-single），28 道（题号 7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,26,27,28,29,30,31,32,33,34,35,134） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1001",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "伤风表证病人常表现为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号7（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["恶寒重，发热轻", "发热轻而恶风", "寒热往来", "发热重，恶寒轻", "发热与恶寒并重"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "发热轻而恶风",
        "伤风即中风表虚证，因卫气不固、营卫不和，表现为发热轻而恶风；与风寒（恶寒重发热轻）、风热（发热重恶寒轻）相区别。选择.pdf题号7，参考答案键号 C 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1002",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者素体阳虚，不温肌表，故见",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号8（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["但热不寒", "恶寒发热", "但寒不热", "寒热往来", "并无寒热"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "但寒不热",
        "素体阳虚、温煦不足者常自觉畏寒而不发热，属但寒不热，久病多虚寒。选择.pdf题号8，参考答案键号 B 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1003",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "若风热内传，正盛邪实，常可见",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号9（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["潮热", "壮热", "微热", "虚热", "郁热"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "壮热",
        "风热内传、邪正相争而邪实正盛，里热亢盛，表现为持续高热（壮热），属里热实证。选择.pdf题号9，参考答案键号 C 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1004",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者身热不扬，午后热甚，属于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号10（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["阴虚潮热", "湿温潮热", "阳明潮热", "气虚发热", "骨蒸潮热"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "湿温潮热",
        "湿温潮热以身热不扬、午后热甚、头身困重为特点，属湿温、湿热证。选择.pdf题号10，参考答案键号 A 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1005",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "外感风邪所致中风表虚证，常见",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号11（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["大汗出", "有汗出", "无汗出", "冷汗出", "热汗出"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "有汗出",
        "太阳中风表虚证因营卫不和、腠理开泄而汗出，与表实无汗相对。选择.pdf题号11，参考答案键号 B 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1006",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者蒸蒸汗出，兼壮热口渴者，属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号12（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["自汗", "绝汗", "战汗", "大汗", "盗汗"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "大汗",
        "蒸蒸汗出兼壮热口渴为里热炽盛、迫津外泄，属阳热亢盛之大汗（源字面作「大汁」，OCR 按医学语义恢复为「大汗」）。选择.pdf题号12，参考答案键号 D 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1007",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者关节疼痛，沉重不移者，属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号13（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["行痹", "痛痹", "着痹", "热痹", "虚痹"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "着痹",
        "关节疼痛沉重而不移，为湿邪偏盛、留着关节之着痹（湿痹）；偏风游走为行痹，偏寒痛剧为痛痹，红肿灼热为热痹。选择.pdf题号13，参考答案键号 B 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1008",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "消渴患者口渴饮水的特点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号14（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["口不渴饮", "大渴引饮", "渴不多饮", "饮入即吐", "饮不欲咽"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "大渴引饮",
        "消渴因津液耗损、胃热炽盛而口渴多饮，表现为大渴引饮、饮不解渴。选择.pdf题号14，参考答案键号 C 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1009",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "食少纳呆，兼消瘦、腹胀、便溏者，属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号15（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["湿邪困脾", "食滞内停", "脾胃气虚", "肝胆湿热", "脾阳虚弱"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脾胃气虚",
        "食少纳呆为食欲减退，兼消瘦、腹胀、便溏，为脾胃运化失健、气虚无以充养，属脾胃气虚。选择.pdf题号15，参考答案键号 A 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1010",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "妇女带下黄臭，多因",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号16（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["湿热下注", "脾虚生湿", "冲任损伤", "肝郁化火", "带脉不固"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "湿热下注",
        "黄带黏稠臭氧秽为湿热下注，多伴外阴瘙痒、口苦尿黄；白带清稀量多则多脾肾阳虚寒湿或脾虚湿变。选择.pdf题号16，参考答案键号 E 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1011",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "大便时干时稀，多见于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号17（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["中气下陷", "肝郁乘脾", "胃气亏虚", "大肠湿热", "脾气亏虚"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝郁乘脾",
        "大便时干时稀为溏结不调，多因肝气郁结乘脾、肝脾不调，脾失健运所致。参考答案键号行「17.0」OCR 不可判读，按医学语义归位为肝郁乘脾。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1012",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列何项与发热性疾病无关",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号18（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["恶寒", "寒战", "恶风", "畏寒", "肢厥"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "畏寒",
        "畏寒属自觉怕冷、加衣被近火可缓的阳虚征象，非发热性疾病正候；恶风、恶寒、寒战多与表证发热相兼。选择.pdf题号18，参考答案键号 D 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1013",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者寒热往来，发无定时，见于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号19（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["半表半里证", "表证", "厥阴病", "疟疾病", "少阴病"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "半表半里证",
        "寒热往来发无定时见于半表半里证（少阳病），发有定时则多见于疟疾。选择.pdf题号19，参考答案键号 B 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1014",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者前额部疼痛，属何经头痛",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号20（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["少阳经", "气血两虚", "阳明经", "太阳经", "阴虚"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阳明经",
        "前额（巅顶以下、额部）头痛属阳明经，侧面痛属少阳，后头项痛属太阳，巅顶痛属厥阴。选择.pdf题号20，参考答案键号 C 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1015",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者病中兼见口甜，多因",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号21（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["肝胃郁热", "胃阴亏虚", "脾胃湿热", "肝胆湿热", "脾胃气虚"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脾胃湿热",
        "口甜（甘）为湿热蕴脾、脾失升运所致，与口苦（肝胆火）、口酸（食积肝乘）、口咸（肾虚水泛）相区别。选择.pdf题号21，参考答案键号 B 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1016",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者盗汗的原因多为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号22（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["气虚", "阴虚", "血虚", "阳虚", "气血两虚"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阴虚",
        "盗汗为寐时汗出、醒后汗止，多因阴虚内热、虚火蒸津外泄所致；自汗则多气虚阳虚。参考答案键号行「220 D」OCR 错位，按医学语义归位为阴虚。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1017",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "自觉怕冷，加衣盖被或近火取暖不能缓解者，为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号24（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["畏寒", "恶风", "恶寒", "寒战", "肢厥"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "恶寒",
        "恶寒为自觉怕冷、加衣被或近火取暖不能缓解，多属外感表证初起（邪正相争于表）；畏寒加衣近火可缓解，多见于阳虚。选择.pdf题号24，参考答案键号 B 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1018",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者便秘，兼见面色苍白、渴喜热饮者，属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号26（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["阴寒内结", "气阴两亏", "阴液亏损", "血虚不润", "气血不足"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阴寒内结",
        "便秘兼面色苍白、渴喜热饮，为阴寒凝结、津液不行之大便不通，属寒秘（阴寒内结）；与热秘口渴喜冷饮有别。选择.pdf题号26，参考答案键号 B 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1019",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "妇女带下清稀，量多色白，多因",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号27（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["寒湿困遏", "肝经郁热", "脾虚湿注", "肾阳亏虚", "湿热下注"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脾虚湿注",
        "白带清稀量多色白，多因脾虚运化失常、湿邪下注所致；兼腰膝酸冷畏寒多责肾阳亏虚寒湿。选择.pdf题号27，参考答案键号 B 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1020",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肝阳上亢患者头痛的特点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号28（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["刺痛", "重痛", "胀痛", "隐痛", "掣痛"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胀痛",
        "肝阳上亢、气火上冲，头痛以胀痛为特点，多伴头晕口苦、面赤易怒。选择.pdf题号28，参考答案键号（OCR 行首 E 片段）与语义一致归位为胀痛。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1021",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列各项中，与「渴不多饮」无关的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号29（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["阴虚内热", "湿热内蕴", "阳气虚弱", "热入营血", "痰饮内停"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阳气虚弱",
        "「渴不多饮」见于热入营血（口干不欲饮）、湿热、痰饮内停、阴虚（口干而饮水不多）等；阳气虚弱多口淡不渴，不属渴不多饮。选择.pdf题号29，参考答案键号 E 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1022",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "疼痛独见于足跟部，应考虑",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号30（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["肝血瘀滞", "寒凝肝脉", "脾虚精亏", "肾虚精亏", "肝血不足"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肾虚精亏",
        "足跟为肾经所过，足跟痛多属肾虚精亏、足跟失养，常伴腰酸、胫骨酸痛。选择.pdf题号30，参考答案键号 D 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1023",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者大便先干后稀，应属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号31（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["脾胃虚弱", "胃阴亏损", "邪热伤津", "寒湿困脾", "肝郁乘脾"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脾胃虚弱",
        "大便先干后稀提示脾气虚、运化失常，前段津不上布而干、后段水湿下注而稀，多属脾胃虚弱。参考答案键号行「D 31，」OCR 截断不可完整判读，按医学语义归位为脾胃虚弱。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1024",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "痢疾患者的大便特点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号32（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写（C 项被 OCR 截断，按医学语义补全）",
      sourceIds: [],
    },
    choices: ["排便不爽，溏结不调", "腹泻不爽，便溏如糜", "里急后重，下利赤白脓血", "滑脱不禁，下利清谷", "暴注下泄，色黄而臭"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "里急后重，下利赤白脓血",
        "痢疾为湿热疫毒蕴结肠道、损伤脂络，大便以脓血黏液、里急后重为特点。C 项被 OCR 截断，按中医诊断学医学语义补全。选择.pdf题号32，参考答案键号 C 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1025",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胃脘灼痛，饥不欲食，证属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号33（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["胃火炽盛", "肝气犯胃", "胃阴亏虚", "食滞胃脘", "胃肠气滞"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胃阴亏虚",
        "胃脘灼痛而饥不欲食，属胃阴不足、虚火内扰，纳谷少而饥不欲食；胃火炽盛则消谷善饥。选择.pdf题号33，参考答案键号 B 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1026",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者困倦易睡，头目昏沉者，多属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号34（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["心脾两虚", "脾气虚弱", "邪入心包", "痰湿困阻", "心肾阳虚"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "痰湿困阻",
        "困倦嗜睡兼头目昏沉、身重体胖，多因痰湿困脾、清阳不升所致；饭后困倦多气虚阳虚，极度疲惫肢冷脉微多心肾阳衰。选择.pdf题号34，参考答案键号 B 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1027",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "小便黄赤，伴尿频、尿急、尿痛者，为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号35（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["下焦虚寒", "肾气不固", "心火亢盛", "膀胱湿热", "热盛伤津"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "膀胱湿热",
        "小便黄赤、频数急痛为湿热蕴结膀胱、气化不利，属膀胱湿热；肾气不固则尿清量多或余沥失禁。选择.pdf题号35，参考答案键号 A 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-a1028",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "阴虚患者在渴饮方面的表现是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号134（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["咽干少饮", "大渴引饮", "漱水不咽", "渴喜冷饮", "渴喜热饮"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "咽干少饮",
        "阴虚津少则口干咽燥，虚火不甚则饮水不多，表现为咽干少饮；大渴引饮多实热，漱水不咽多瘀血，渴喜冷饮多热盛。选择.pdf题号134，参考答案键号 A 与语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答/论述（short-answer），3 道（问诊鉴别大题：问寒热/问汗/问疼痛） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-short001",
    order: 36,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述恶寒发热、但寒不热、但热不热、寒热往来的临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 问寒热、汗、疼痛快速辨证（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①恶寒重、发热轻：多风寒表证；发热重、恶寒轻：多风热表证；发热轻而恶风：多伤风表虚证。②但寒不热：新病多实寒，久病多虚寒。③但热不热：壮热多里热实证；日晡潮热多阳明腑实；午后或夜间潮热伴颧红盗汗多阴虚火旺；午后热甚、身热不扬、头身困重多湿温湿热。④寒热往来：发无定时多少阳病（半表半里），发有定时多疟疾。",
        "问寒热须结合发热与恶寒并见与否、发热之时间与性质来辨表里虚实寒热之属性，并落实病位（表里、少阳、阳明）与病性（实热、虚热、湿热）。第2天背诵内容及答案·问寒热部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-short002",
    order: 37,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述自汗、盗汗、大汗、战汗的临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 问寒热、汗、疼痛快速辨证（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①自汗：时时汗出、动则更甚，多因气虚或阳虚，卫阳不固。②盗汗：寐时汗出、醒后自止，多因阴虚内热、虚火蒸津。③大汗：蒸蒸汗出参壮热口渴，多里热炽盛、迫津外泄；冷汗淋漓、面色苍白则多阳气暴脱。④战汗：恶寒战栗而后汗出，是邪正剧争、病情转折之象，须观察汗后热势与脉证变化。",
        "问汗须辨汗出时间、部位、冷汗热汗及伴随证，判定邪正虚实；战汗为病情转折点，需结合脉证判顺逆。第2天背诵内容及答案·问汗部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch05-wenzhen-wen-short003",
    order: 38,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "疼痛的性质与部位如何帮助辨证？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 问寒热、汗、疼痛快速辨证（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①胀痛多气滞，刺痛多血瘀，冷痛多寒证，灼痛多热证，重痛多湿邪或湿阻，隐痛多虚证（不荣而痛），掣痛多筋脉失养或寒邪收引，游走窜痛多风邪（行痹）。②部位辨经：前额痛多阳明经，后头痛项多太阳经，侧头痛多少阳经，巅顶痛多厥阴经，足跟痛多肾虚。③拒按多实证，喜按多虚证。",
        "问疼痛将疼痛之性质（虚实寒热瘀滞）与部位（脏腑经络）结合，方能定位定性；头痛与痹痛按病位归经更有助辨证。第2天背诵内容及答案·问疼痛部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1/B2 配伍题（bGroups），0 组（本书无 B1/B2 型） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems, ...a1Items, ...shortItems,
];
export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];