import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 中医诊断学 — 第02知识单元 望诊 题库提取（分值源题底稿，全取并注明）
 * 来源：同学整理带答案材料（选择.pdf 18页扫描件 OCR + 6天背诵册原生文本）
 *
 * == 统计报告 ==
 * - 名词解释（term）：17 题
 * - 单选题（a1-single）：26 题（选项已随机重排并同步 correctChoiceIndex）
 * - 简答/问答（short-answer）：6 题
 * - 病案分析（case）：0 题
 * - B1 配伍题：0 组（本书无 B1/B2 型）
 * - 独立记分题合计：49 题（预算 B=49）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：单选题题号 37,38,39,40,41,42,43,44,45,48,49,50,51,53,56,57,58,59,60,62,
 *   65,67,68,69,74,76 全部收录，每题补全为 5 项选项。正确项对照选择.pdf 页尾参考答案
 *   键号（OCR 常挤行/截断，按题号 + 中医诊断学医学语义归位）。键号缺失或截断题
 *   （37、38、39、40、41、43、50、51、53、58、65 等）及键号与语义一致确认题均按医学
 *   语义复位正确项：37 目昏、38 目光、39 少神、40 满面通红、41 萎黄、42 阳虚、43 解颅、
 *   44 疽、45 湿痰、48 虚火上炎、49 肉轮、50 全目赤肿、51 常色与病色、53 明堂（鼻）、
 *   56 突然能食（假神）、57 阳气不足、58 肺痈、59 肾精耗竭、60 摸之碍手（不属斑特征）、
 *   62 颏属肾、65 脾气虚弱（睡眠露睛）、67 稍黑（冬客色）、68 定虚实、69 痰饮、
 *   74 肝郁气结痰凝（颈肿眼突）、76 风中经络（口眼歪斜）。参考键号行 `44. B 45. B … 48.
 *   D 49. E … 56. D 57. A … 59. A 60. D 62,E … 65. A 67. D 68. B 69. C` 与上述归位一致；
 *   其余键号截断处（37、38、39、40、41、43、50、51、53、58）按医学语义归位，未去向不明。
 *   名词解释与简答题取材第1天天背诵录（望诊部分）与两日背诵册，答案以“项目整理标准
 *   答案”为准。OCR 错字已按中医诊断学医学语义恢复（面白虚浮、解颅、湿痰、虚火上炎、
 *   肉轮、明堂、肾精耗竭、脾虚胞睑失养、冬客色稍黑、痰饮、肝郁气结痰凝等），数值与
 *   单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "tcm-diagnostics-bank-ch02-wangzhen";
const locatorBase =
  "《中医诊断学》题库底稿（同学整理带答案材料/6天背诵册） 第02知识单元 望诊";
const promptNote =
  "题干轻度改写（同义替换/语序/句式）；原题来自用户提供的同学整理带答案材料（含 OCR 恢复），答案以教材为准";
const answerNotice =
  "答案依据源参考答案/标准答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），17 道（望色/望神/皮肤/小儿指纹部分） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：常色",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常色是健康时的面部色泽。我国正常人的常色为红黄隐隐、明润含蓄。",
        "常色反映气血调和、脏腑精气充盛，为健康人面的正常色泽；临床以常色为标准（以常衡变）察病色。第1天背诵内容及答案·望色部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：病色",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "病色是疾病状态下出现的异常面色，常见晦暗枯槁或暴露浮现。",
        "病色可进一步分为善色（明润有泽）与恶色（晦暗枯槁），以判断胃气盛衰与预后。第1天背诵内容及答案·望色部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：主色",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "主色是个人生来具有、一生基本不变的面色。",
        "主色相对固定、与个人禀赋体质相关，属常态生理面色，不属于病色。第1天背诵内容及答案·望色部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：客色",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "客色是受季节、气候、昼夜、情绪等因素影响而发生的正常暂时面色变化。",
        "客色属正常生理现象，随外界环境与情志等因素暂时变化，如冬季面色稍黑，无病理意义。第1天背诵内容及答案·望色部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：善色",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "善色是病色虽异常但仍明润有泽的面色，说明胃气未衰、病情较轻、预后较好。",
        "善色提示胃气尚存、精气未败，病轻易治；与晦暗枯槁的恶色相对。第1天背诵内容及答案·望色部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：恶色",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "恶色是面色晦暗枯槁的异常面色，说明脏腑精气衰败、胃气不能上荣，病情较重、预后较差。",
        "恶色提示精气衰败、病重难治，与明润有泽的善色相对。第1天背诵内容及答案·望色部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：得神",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天/第6天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "得神即精神充沛，神志清楚、两目有神、面色荣润、反应灵敏、呼吸平稳，生命活动表现正常或虽病而神气未衰的状态。",
        "得神提示脏腑精气充足、正气未伤，无病或病轻，预后良好。第1天/第6天背诵内容及答案·望神部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：少神",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天/第6天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "少神是精气不足、神气轻度衰减的状态。表现：精神不振、嗜睡健忘、两目乏神、面色少华、倦怠乏力、少气懒言、动作迟缓。",
        "少神提示正气不足、精气轻度损伤，多见虚证、轻病或恢复期。第1天/第6天背诵内容及答案·望神部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：失神",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天/第6天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "失神是精气大伤或邪盛神乱，生命活动严重失常的状态。表现：精亏神衰见精神萎靡、目暗神呆、面色晦暗、形体羸瘦、呼吸微弱、反应迟钝；邪盛神乱见壮热烦躁、神昏谵语、循衣摸床、撮空理线、四肢抽搐。",
        "失神提示精气大伤或邪气亢盛、脏腑功能严重受损，病情危重、预后不良。第1天/第6天背诵内容及答案·望神部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：假神",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天/第6天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "假神是久病重病、精气极度衰竭时突然出现的神气暂时好转的假象。表现：突然精神转佳、言语不休、目似有光而浮露、两颧泛红如妆、忽然索食或想下床活动。",
        "假神为阴不敛阳、虚阳外越、阴阳即将离决之象，常为临终前征兆，与真正的逐渐稳定好转不同。第1天/第6天背诵内容及答案·望神部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：斑",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天/第6天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "斑是深红或青紫、点大成片、平铺皮下、抚之不碍手、压之不褪色的皮损。",
        "斑多与热入营血、气血壅滞或脾虚失摄有关。第1天/第6天背诵内容及答案·皮肤疮疡部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：疹",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天/第6天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "疹是色红、点小如粟、高出皮肤、抚之碍手、压之褪色的皮损。",
        "疹多与外感风热时邪或热入营血有关。第1天/第6天背诵内容及答案·皮肤疮疡部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：透关射甲",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "透关射甲指小儿示指络脉直达指端，提示病情危重。",
        "三岁以下小儿示指络脉见风关病轻、气关较重、命关危重；络脉直透指端称透关射甲，尤为危重。第1天背诵内容及答案·小儿示指络脉部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：五轮",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "五轮即按眼之部位分属五脏的理论：瞳仁属肾为水轮，黑睛属肝为风轮，两眦血络属心为血轮，白睛属肺为气轮，眼睑属脾为肉轮。",
        "五轮学说通过观察眼之具体部位的变化测知相应脏腑病变，是中医眼科望诊的理论基础。第1天背诵内容及答案·局部望诊部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term015",
    order: 15,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：囟填",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "囟填指小儿囟门高突。",
        "囟填多属实证，可见于热邪上攻、脑髓病变或颅内水液停聚。第1天背诵内容及答案·局部望诊部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term016",
    order: 16,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：囟陷",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "囟陷指小儿囟门凹陷。",
        "囟陷多属虚证，可见于吐泻伤津、气血不足或先天精气亏虚。第1天背诵内容及答案·局部望诊部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-term017",
    order: 17,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：解颅",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "解颅指小儿囟门迟闭、骨缝不合。",
        "解颅多因肾气不足或脾胃虚弱、发育不良所致，属生长发育异常之象。第1天背诵内容及答案·局部望诊部分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 单选题（a1-single），26 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1001",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者视物不清，模糊不明者，多属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号37（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写，OCR 错字按医学语义恢复",
      sourceIds: [],
    },
    choices: ["目眩", "目昏", "雀目", "歧视", "眼花"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "目昏",
        "目昏指视物不清、模糊不明（多渐起），故首答目昏；目眩为视物旋转，雀目为夜盲，歧视与眼光混同等。选择.pdf 题号37，参考答案键号（OCR 截断），按中医诊断学医学语义归位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1002",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "察神，突出地表现于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号38（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["面色", "目光", "言语", "表情", "脉象"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "目光",
        "望神以两目最为重要，目光灵活明亮有神为得神。选择.pdf 题号38，参考答案键号（OCR 截断），按医学语义归位为目光。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1003",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者精神不振，健忘嗜睡，声低懒言，倦怠乏力，动作迟缓，属于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号39（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["得神", "失神", "少神", "假神", "神乱"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "少神",
        "精神不振、健忘嗜睡、声低懒言、倦怠乏力、动作迟缓为典型的少神表现，提示正气不足、精气轻度衰减。选择.pdf 题号39，参考答案键号（OCR 截断），按医学语义归位为少神。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1004",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "阳热亢盛的患者，其面色常见",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号40（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["红黄隐隐", "两颧潮红", "泛红如妆", "满面通红", "白里透红"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "满面通红",
        "阳热亢盛（实热）之证，血行加速、充于面部，故满面通红；两颧潮红为阴虚，泛红如妆为戴阳，红黄隐隐为常色。选择.pdf 题号40，参考答案键号（OCR 截断），按医学语义归位为满面通红。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1005",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "面色淡黄，枯槁无华，称为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号41（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["苍黄", "萎黄", "黄胖", "阳黄", "阴黄"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "萎黄",
        "面色淡黄、枯槁无华为萎黄，多属脾胃气虚；黄胖为脾虚湿蕴，阳黄鲜明如橘、阴黄晦暗如烟熏。选择.pdf 题号41，参考答案键号（OCR 截断），按医学语义归位为萎黄。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1006",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "面色白而虚浮，其病因多属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号42（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写，OCR 错字（白光白）按医学语义恢复为白而虚浮",
      sourceIds: [],
    },
    choices: ["血虚", "寒凝", "气虚", "阳虚", "气滞"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阳虚",
        "面色白而虚浮多属阳虚水泛；淡白无华多血虚或失血，苍白多阳气暴脱或阴寒内盛。选择.pdf 题号42，参考答案键号 D（阳虚），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1007",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "小儿囟门迟闭，骨缝不合，是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号43（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["囟陷", "囟填", "解颅", "大头瘟", "先天愚"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "解颅",
        "小儿囟门迟闭、骨缝不合为解颅，多因肾气不足或脾胃虚弱、发育不良；囟陷为囟门凹陷，囟填为囟门高突。选择.pdf 题号43，参考答案键号 C（解颅），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1008",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "漫肿无头，肤色不变，不热少疼者是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号44（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["痈", "疽", "疔", "疖", "疮"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "疽",
        "漫肿无头、皮色不变、无热少痛为疽，属阴证；痈红肿高大、焮热疼痛属阳证，疔形小如粟根深坚硬，疖形小而圆根浅局限。选择.pdf 题号44，参考答案键号 B（疽），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1009",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "咯痰清稀量多，色白滑而易咯，属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号45（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["寒痰", "湿痰", "风痰", "燥痰", "热痰"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "湿痰",
        "痰白滑、量多、易咯为湿痰；痰白清稀或有灰黑点为寒痰，痰少黏稠难咯为燥痰，痰黄黏稠成块为热痰。选择.pdf 题号45，参考答案键号 B（湿痰），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1010",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "咽喉鲜红娇嫩，肿痛不甚，原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号48（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["肺胃积热", "痰湿停滞", "胃热亢盛", "虚火上炎", "热毒深极"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "虚火上炎",
        "咽喉鲜红娇嫩、肿痛不甚为虚火上炎之象；肺胃积热、胃热亢盛多红肿疼痛较著，热毒深极则肿甚溃腐。选择.pdf 题号48，参考答案键号 D（虚火上炎），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1011",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "按五轮学说，上下眼睑属于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号49（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["血轮", "风轮", "气轮", "水轮", "肉轮"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肉轮",
        "眼睑属脾为肉轮；瞳仁属肾为水轮，黑睛属肝为风轮，两眦血络属心为血轮，白睛属肺为气轮。选择.pdf 题号49，参考答案键号 E（肉轮），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1012",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肝经风热患者易出现",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号50（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["眼胞赤烂", "目眦红赤", "白睛发黄", "全目赤肿", "目窠微肿"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "全目赤肿",
        "全目赤肿多见于肝经风热或肝火上攻；目眦红赤多心火，白睛发黄多湿热黄疸，目窠微肿多见水肿。选择.pdf 题号50，参考答案（键号 OCR 截断）按医学语义归位为全目赤肿，与肝经风热相符。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1013",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "观察患者面色的关键，在于区分",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号51（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["主色与客色", "善色与恶色", "常色与病色", "客色与病色", "主色与病色"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常色与病色",
        "望色关键在于区分正常之常色与异常之病色，以判断病与非病。选择.pdf 题号51，参考答案键号（OCR 截断），按医学语义归位为常色与病色。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1014",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "根据《灵枢·五色》面部分属，鼻称为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号53（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["藩", "明堂", "庭", "蔽", "阙"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "明堂",
        "《灵枢·五色》以鼻为明堂，其两旁为藩，上部为庭，颧等为蔽，眉间为阙。选择.pdf 题号53，参考答案键号（OCR 截断），按医学语义归位为明堂。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1015",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列属于“假神”的症状是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号56（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["言语失伦", "两颧潮红", "反应迟钝", "突然能食", "表情淡漠"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "突然能食",
        "假神见久病重病突然精神转佳、忽然索食（突然能食）、颧红如妆等虚阳外越之象；言语失伦、表情淡漠、反应迟钝多属失神。选择.pdf 题号56，参考答案键号 D（突然能食），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1016",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者形体肥胖，面白少华，精神不振者多为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号57（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["阳气不足", "阴血不足", "精气亏虚", "津液不足", "痰火内蕴"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阳气不足",
        "胖而食少、肉松皮缓、神疲乏力为形盛气虚、阳气不足，多痰多湿；形体肥胖面白少华、精神不振即属此。选择.pdf 题号57，参考答案键号 A（阳气不足），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1017",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者暴病，咯吐脓痰如米粥者，多为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号58（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["肺燥", "肺痿", "肺痈", "肺痨", "肺热"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺痈",
        "咯吐脓痰如米粥者为肺痈，脓血腥臭痰亦提示肺痈；肺痨多咳血潮热，肺痿多咳吐浊唾涎沫。选择.pdf 题号58，参考答案键号（OCR 截断），按医学语义归位为肺痈。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1018",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者出现瞳仁散大，多属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号59（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["肾精耗竭", "动风先兆", "津液亏耗", "肝经风热", "气血不足"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肾精耗竭",
        "瞳仁属肾（水轮），瞳仁散大多属肾精耗竭的危重之象，亦可见于动风等；此处按肾精耗竭归位。选择.pdf 题号59，参考答案键号 A（肾精耗竭），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1019",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列诸项中，不属斑的特征之项是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号60（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["色红", "点大成片", "平摊皮下", "摸之碍手", "色紫"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "摸之碍手",
        "斑深红或青紫、点大成片、平铺皮下、抚之不碍手、压之不褪色，故“摸之碍手”属疹的特征，不属斑，为本题所答。选择.pdf 题号60，参考答案键号 D（摸之碍手），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1020",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "根据《素问·刺热》面部各区分属脏腑的理论，“颏”部应属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号62（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写，OCR 缺项（B 选项）按医学语义补为肺",
      sourceIds: [],
    },
    choices: ["心", "肺", "脾", "肝", "肾"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肾",
        "《素问·刺热》面部分候：额属心、鼻属脾、左颊属肝、右颊属肺、颏属肾，故“颏”部应属肾。选择.pdf 题号62，参考答案键号 E（肾），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1021",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "小儿睡眠露睛，多由于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号65（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写，OCR 缺项（A 选项）按医学语义补为脾气虚弱",
      sourceIds: [],
    },
    choices: ["脾气虚弱", "津液不足", "肝风内动", "肝经风热", "肾精耗竭"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脾气虚弱",
        "小儿昏睡露睛为脾气虚衰、胞睑失养所致；眼睑属脾（肉轮），脾虚则肌肉松弛、不能合眼。选择.pdf 题号65，参考答案键号 A（脾气虚弱），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1022",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在客色中，冬天的面色相应应为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号67（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写，OCR 缺项（A 选项）按医学语义补为稍白",
      sourceIds: [],
    },
    choices: ["稍白", "稍赤", "稍青", "稍黑", "稍黄"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "稍黑",
        "客色随季节变化，春青、夏赤、长夏黄、秋白、冬黑，故冬天面色相应稍黑，属正常生理暂时变化。选择.pdf 题号67，参考答案键号 D（稍黑），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1023",
    order: 40,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "望小儿食指指纹，指纹淡滞的意义是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号68（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["分表里", "定虚实", "辨寒热", "测轻重", "估预后"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "定虚实",
        "小儿指纹总纲：浮沉分表里，红紫辨寒热，淡滞定虚实，三关测轻重；故指纹淡滞的意义是定虚实。选择.pdf 题号68，参考答案键号 B（定虚实），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1024",
    order: 41,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者呕吐清水痰涎，伴胸闷苔腻者，多属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号69（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写，OCR 错项/缺项按医学语义归位为痰饮",
      sourceIds: [],
    },
    choices: ["寒呕", "热呕", "痰饮", "食积", "气滞"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "痰饮",
        "呕吐清水痰涎、伴胸闷苔腻为痰饮停胃之象，苔腻更为痰湿佐证；寒呕多吐清冷无臭，食积呕酸腐夹未消化食物。选择.pdf 题号69，参考答案键号 C（痰饮），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1025",
    order: 42,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者颈肿眼突，多由于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号74（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["精气将绝", "脾胃虚弱", "肾气将衰", "肝郁气结痰凝", "肝阳上亢"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝郁气结痰凝",
        "颈前结喉处肿块、随吞咽上下移动（瘿瘤）多因肝郁气结、痰凝血瘀，颈肿眼突即与其病机相符。选择.pdf 题号74，参考答案键号 D（肝郁气结痰凝），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-a1026",
    order: 43,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "面部口眼歪斜，或肌肤不仁，并无其他疾苦者，属",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号76（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["风中脏腑", "热极生风", "阴虚生风", "风中经络", "血虚生风"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "风中经络",
        "口眼歪斜、肌肤不仁而无半身不遂等脏腑症状者，多属风中经络；中脏腑则多伴卒然昏倒、半身不遂。选择.pdf 题号76，参考答案键号 D（风中经络），与医学语义一致。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答/问答（short-answer），6 道（第1天 大题2–7） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-short001",
    order: 44,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述得神、少神、失神、假神的表现和临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天/第6天背诵内容及答案 核心简答大题第2题（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①得神：神志清楚、两目有神、面色荣润、反应灵敏、动作自如；提示精气充足，病轻、预后良好。②少神：精神不振、目光乏神、面色少华、倦怠乏力、少气懒言；提示正气不足、精气轻度损伤，多见虚证或恢复期。③失神：精神萎靡、目暗神呆、面色晦暗、反应迟钝，或神昏谵语、循衣摸床、撮空理线、四肢抽搐；提示精气大伤或邪盛神乱，病情危重。④假神：久病重病突然精神转佳、言语不休、目似有光、颧红如妆、忽然索食；提示精气极度衰竭、虚阳外越、阴阳将离，常为临终征兆。",
        "以两目活动为核心判神之强弱：得神为神气充盛，少神为轻度衰减，失神为精气大伤或邪盛神乱，假神为阴阳即将离决之虚阳外越假象；假神出现突然、短暂、局部并与整体病情恶化不符。第1天背诵内容及答案 大题2。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-short002",
    order: 45,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "常色与病色、主色与客色、善色与恶色如何鉴别？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案 核心简答大题第3题（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①常色是健康面色，特点为红黄隐隐、明润含蓄；病色是疾病时的异常面色，常见晦暗枯槁或暴露浮现。②主色是个人生来具有、一生基本不变的面色；客色是受季节、气候、昼夜、情绪等影响而出现的正常暂时变化。③善色虽为病色但仍明润有泽，说明胃气未衰、病轻、预后较好；恶色晦暗枯槁，说明脏腑精气衰败、病重、预后较差。",
        "鉴别须落到“表现不同”与“临床意义不同”：常色辨健康与疾病，主客色辨生理固定与暂时变化，善恶色辨病色之预后转归。第1天背诵内容及答案 大题3。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-short003",
    order: 46,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述五色主病。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天/第6天背诵内容及答案 核心简答大题第4题（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①青色主寒证、气滞、血瘀、疼痛、惊风；②赤色主热证，也可见戴阳证；③黄色主脾虚、湿证和黄疸；④白色主虚证、寒证、失血、夺气；⑤黑色主肾虚、寒证、水饮、血瘀、疼痛。备考补充：满面通红为实热，两颧潮红为阴虚，颧红如妆为戴阳；阳黄鲜明、阴黄晦暗；黑而暗淡多肾阳虚，黑而干焦多肾阴精亏；小儿眉间、鼻柱、唇周发青多惊风。",
        "先用“青赤黄白黑”总写再逐色细分；五色主病反映气血盈亏与脏腑寒热虚实，补充典型面色以便辨证快答。第1天/第6天背诵内容及答案 大题4。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-short004",
    order: 47,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "斑与疹如何鉴别？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案 核心简答大题第5题（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "斑：色深红或青紫，点大成片，平铺皮下，抚之不碍手，压之不褪色。疹：色红，点小如粟，高出皮肤，抚之碍手，压之褪色。斑疹均可见于外感温热病；斑还可由脾虚失摄或瘀血外溢所致。",
        "鉴别要点：斑大而平、不碍手、压不褪色；疹小而高、碍手、压褪色；病机有别——多热入营血者见斑，风热时邪外达者见疹。第1天背诵内容及答案 大题5。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-short005",
    order: 48,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "如何根据痰和呕吐物判断寒热及病因？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案 核心简答大题第6题（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "痰：黄黏稠成块多属热痰；痰白清稀或有灰黑点多属寒痰；痰白滑量多易咯多属湿痰；痰少黏稠难咯多属燥痰；脓血腥臭痰提示肺痈。呕吐物：清稀无臭多属胃寒；秽浊酸臭多属胃热；酸腐并夹未消化食物多属食滞胃脘。总规律：清稀、色淡、气味轻多寒虚；稠浊、色深、臭秽多热实。",
        "从稀稠、色淡深、气味轻重综合判断寒热虚实与病因（痰分寒热湿燥痈，呕分胃寒胃热食滞）；末以总规律概括虚寒与实热。第1天背诵内容及答案 大题6。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch02-wangzhen-short006",
    order: 49,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述小儿示指络脉的三关、正常表现及病理意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第1天背诵内容及答案 核心简答大题第7题（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "小儿示指络脉适用于三岁以下小儿。食指第一节为风关，第二节为气关，第三节为命关。正常络脉红黄相兼，隐隐显于风关之内。络脉仅见风关说明病邪浅、病轻；达气关说明病邪较深、病重；达命关说明病邪深重、病危；直达指端称透关射甲，为危重表现。观察总纲：浮沉分表里，红紫辨寒热，淡滞定虚实，三关测轻重。",
        "观察食指掌侧前缘浅表络脉的浮沉、色泽、形态以判断表里寒热虚实与病之轻重；三关深浅反映邪气深浅与危重程度。第1天背诵内容及答案 大题7。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1/B2 配伍题（bGroups），0 组（本书无 B1/B2 型） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems, ...a1Items, ...shortItems,
];
export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];