import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 中医诊断学 — 第03知识单元 舌诊 题库提取（分值源题底稿，全取并注明）
 * 来源：同学整理带答案材料（选择.pdf 18页扫描件 OCR + 6天背诵册原生文本）
 *
 * == 统计报告 ==
 * - 名词解释（term）：9 题
 * - 单选题（a1-single）：17 题（选项已随机重排并同步 correctChoiceIndex）
 * - 简答/问答（short-answer）：6 题
 * - 病案分析（case）：0 题
 * - B1 配伍题：0 组（本书无 B1/B2 型）
 * - 独立记分题合计：32 题（预算 B=32）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：单选题题号 46,47,52,54,55,61,63,64,66,70,71,72,73,75,77,79,80 全部收录，
 *   每题补全为 5 项选项。正确项对照选择.pdf 页尾参考答案键号（OCR 常挤行/截断，按题号 +
 *   中医诊断学医学语义归位）：46 消瘦人、47 痿软舌、52 酒毒攻心、54 阳虚、55 舌质老嫩、
 *   61 胃气暴绝、63 舌苔焦黄、64 实热证、66 胃肠热盛、70 脾虚湿盛、71 绛舌、72 淡白舌、
 *   73 舌苔厚薄、75 寒凝血瘀、77 绛舌薄白苔、79 里实热证、80 舌苔颜色，均与键号
 *   `46.D 47.B 52.A 54.D 55.B 61.D 63.C 64.B 66.D 70.B 71.B 72.E 73.B 75.C 77.B 79.A 80.D`
 *   一致，未去向不明。键号行无冲突、无复位项。
 *   约束与补全：题 70 选项中被 OCR 串入他题残留字串“估预后”，本文件按中医诊断学医学语义
 *   补全为“脾气虚”作干扰项；题 71 原选项 OCR 重排重复（紫舌、芒刺舌同标 D），按 5 项补全为
 *   红舌/绛舌/紫舌/芒刺舌/镜面舌。两处均未影响正确项（70＝脾虚湿盛、71＝绛舌），已在
 *   content[1] 如实注明。
 *   名词解释与简答题取材第2天/第6天背诵册（舌诊核心背诵、名词解释速背清单、核心简答大题
 *   大题3 舌色舌形舌态、大题4 苔质苔色、舌质与舌苔合参），答案以“项目整理标准答案”为准。
 *   OCR 错字已按中医诊断学医学语义恢复（痿软舌、酒毒攻心、胃肠热盛、绛舌、寒凝血瘀等），
 *   数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "tcm-diagnostics-bank-ch03-shezhen";
const locatorBase =
  "《中医诊断学》题库底稿（同学整理带答案材料/6天背诵册） 第03知识单元 舌诊";
const promptNote =
  "题干轻度改写（同义替换/语序/句式）；原题来自用户提供的同学整理带答案材料（含 OCR 恢复），答案以教材为准";
const answerNotice =
  "答案依据源参考答案/标准答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），9 道（舌质/舌苔/苔质/舌形舌态部分，与 a1/short 不重复概念） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：舌质",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 舌诊核心背诵·基本概念（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "舌质是舌的肌肉脉络组织，又称舌体，主要观察其神、色、形、态。",
        "舌质反映脏腑气血阴阳的盛衰，为舌象合参中偏重于“本”的一方；正常舌质淡红荣润、大小适中、柔软灵活。第2天背诵内容及答案·舌诊核心背诵。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：舌苔",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 舌诊核心背诵·基本概念（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "舌苔是覆盖于舌面的一层苔状物，由胃气上蒸、胃津熏化而形成。",
        "舌苔主要反映病邪性质、邪气深浅及胃气盛衰，为舌象合参中偏重于“标”的一方；正常为薄白均匀、干湿适中的有根薄白苔。第2天背诵内容及答案·舌诊核心背诵。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：腻苔",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 舌诊核心背诵·苔质（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腻苔是颗粒细腻致密、融合成片、如涂油腻而紧贴舌面、刮之难去的舌苔。",
        "腻苔主湿浊、痰饮、食积、湿热；苔虽黏腻紧贴，与腐苔之松而可去相对。第2天背诵内容及答案·苔质。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：腐苔",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 舌诊核心背诵·苔质（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腐苔是颗粒疏松粗大而厚、形如豆腐渣堆积、较易刮去的舌苔。",
        "腐苔多主食积、痰浊，脓腐苔可见内痈；与腻苔之颗粒细密、刮之难去相鉴别。第2天背诵内容及答案·苔质。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：剥落苔",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 舌诊核心背诵·苔质（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "剥落苔是舌苔全部或部分脱落、脱处光滑无苔的舌苔。",
        "剥落苔主胃气不足、胃阴损伤或气血两虚；全部剥落、舌面光滑如镜则为镜面舌，多胃气胃阴大伤，病情较重。第2天背诵内容及答案·苔质。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：舌象",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 舌诊核心背诵·基本概念（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "舌象是舌质与舌苔变化的总称。",
        "舌诊即通过观察舌象来了解脏腑气血津液盛衰及病邪性质、病位与病势；正常舌象简称“淡红舌，薄白苔”。第2天背诵内容及答案·舌诊核心背诵。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：裂纹舌",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 舌诊核心背诵·舌形（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "裂纹舌是舌面出现深浅不一的裂沟的舌象。",
        "红绛而裂多热盛伤津，淡白而裂多阴血不足，胖嫩有裂可见脾虚湿盛；先天裂纹舌无病象。第2天背诵内容及答案·舌形。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：镜面舌",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 名词解释速背清单（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "镜面舌是舌苔全部剥落、舌面光滑如镜的舌象。",
        "镜面舌提示胃气胃阴大伤，多属危重征象；由舌苔全剥而成，须结合症状判断预后。第2天背诵内容及答案·名词解释速背清单。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：短缩舌",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 舌诊核心背诵·舌态（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "短缩舌是舌体卷短紧缩、不能伸长的舌象。",
        "短缩舌多因寒凝筋脉、痰湿内阻、气血虚衰或热盛伤津所致，病情较重；须与痿软舌、强硬舌相鉴别。第2天背诵内容及答案·舌态。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 单选题（a1-single），17 道（题号 46,47,52,54,55,61,63,64,66,70,71,72,73,75,77,79,80） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1001",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "正常人舌体瘦而偏红，常见于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号46（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写，OCR 错字按医学语义恢复",
      sourceIds: [],
    },
    choices: ["消瘦人", "老年人", "肥胖人", "年轻人", "婴幼儿"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "消瘦人",
        "正常人舌体瘦而偏红多见于消瘦人：体质瘦弱者舌多瘦薄而偏红（舌形偏瘦、气血上充）；肥胖者舌多胖大色淡，老年人舌色可偏暗，儿童舌多淡嫩。选择.pdf 题号46，参考答案键号 46. D＝消瘦人。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1002",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "舌体软弱，屈伸无力者，称",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号47（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["短缩舌", "痿软舌", "吐弄舌", "强硬舌", "颤动舌"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "痿软舌",
        "痿软舌为舌体软弱无力伸缩，多主气血俱虚、阴液亏极或热灼津伤；短缩舌卷短不伸属危重，强硬舌板硬不灵，吐弄舌反复伸缩，颤动舌震颤不止。选择.pdf 题号47，参考答案键号 47. B＝痿软舌。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1003",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "舌青紫而肿胀，多为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号52（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["气血上壅", "酒毒攻心", "心脾热盛", "气滞血瘀", "热毒上攻"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "酒毒攻心",
        "舌青紫而肿胀，多为酒毒攻心上犯所致；气血上壅、心脾热盛等均非此舌象专主病机，故取酒毒攻心。选择.pdf 题号52，参考答案键号 52. A＝酒毒攻心。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1004",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "舌质淡胖而嫩，苔白而润，见于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号54（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["气虚", "阳虚", "血虚", "气血两虚", "气阴两虚"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阳虚",
        "舌质淡胖而嫩、苔白而润为阳虚、水湿不化之象；气血两虚虽舌淡但多不胖嫩，气阴两虚多舌红少苔，气虚、血虚寒象不著，故取阳虚。选择.pdf 题号54，参考答案键号 54. D＝阳虚。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1005",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "望舌辨虚实，主要观察",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号55（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["舌苔厚薄", "舌色浅深", "舌质老嫩", "舌苔润燥", "舌体胖瘦"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "舌质老嫩",
        "老舌纹理粗糙、坚敛苍老多主实证，嫩舌纹理细腻、娇嫩浅淡多主虚证，故辨虚实主要观察舌质老嫩；舌色浅深辨寒热盛衰，苔厚薄辨邪之深浅，苔润燥辨津液盈亏。选择.pdf 题号55，参考答案键号 55. B＝舌质老嫩。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1006",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "若满舌厚苔骤然退出，提示",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号61（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["邪去正安", "表邪入里", "寒证化热", "胃气暴绝", "邪热伤津"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胃气暴绝",
        "满舌厚苔骤然退出为舌苔骤剥之危象，提示胃气暴绝；邪去正安应脉症向愈而不致骤然退苔，表邪入里苔当转厚，故取胃气暴绝。选择.pdf 题号61，参考答案键号 61. D＝胃气暴绝。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1007",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "黄苔主热证，若热结于里，则见",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号63（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["舌苔淡黄", "舌苔深黄", "舌苔焦黄", "舌苔灰黄", "舌苔黄腻"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "舌苔焦黄",
        "黄苔色越深则热越重，热结于里可见焦黄苔；淡黄热轻，深黄热重，焦黄为热结之极，黄腻多湿热痰热食积，灰黄不专主热结。选择.pdf 题号63，参考答案键号 63. C＝舌苔焦黄。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1008",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "舌苔黄燥，主病为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号64（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["表热证", "实热证", "湿热证", "虚热证", "假热证"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "实热证",
        "舌苔黄燥为里实热、热盛伤津之象，故属实热证；表热可见薄白苔而非黄燥，湿热多黄腻，虚热多舌红少苔。选择.pdf 题号64，参考答案键号 64. B＝实热证。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1009",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "舌质中部生芒刺，常提示",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号66（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写，OCR 错字按医学语义恢复",
      sourceIds: [],
    },
    choices: ["心火上炎", "肝胆热盛", "胃阴不足", "胃肠热盛", "疫疠初起"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胃肠热盛",
        "舌中候脾胃（胃肠），中部生芒刺为胃肠热盛之象；舌尖多心火，舌边多肝胆，故取胃肠热盛。选择.pdf 题号66，参考答案键号 66. D＝胃肠热盛。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1010",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "舌体胖大有齿痕，主病为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号70（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写，选项按医学语义补全",
      sourceIds: [],
    },
    choices: ["脾气虚", "脾阳虚", "脾虚湿盛", "肾虚水泛", "肾阳虚"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脾虚湿盛",
        "舌体胖大、边有齿痕多主脾虚湿盛，气虚水湿不化则舌胖、脾失健运则舌边齿痕；本题题70 选项中原本被 OCR 串入他题残留“估预后”，本文件按中医诊断学医学语义补全为“脾气虚”作干扰项，正确项不受影响。选择.pdf 题号70，参考答案键号 70. B＝脾虚湿盛。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1011",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "主热入营血或阴虚火旺的舌象是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号71（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写，选项按 5 项补全",
      sourceIds: [],
    },
    choices: ["红舌", "绛舌", "紫舌", "芒刺舌", "镜面舌"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "绛舌",
        "绛舌色深红，主里热亢盛、热入营血或阴虚火旺；红舌主热证但未至营血，紫舌主血行不畅，芒刺舌主热盛，镜面舌主胃气胃阴大伤。原题71 选项 OCR 重排重复（紫舌、芒刺舌同标 D），本文件按 5 项补全为红/绛/紫/芒刺/镜面舌，正确项仍为绛舌。选择.pdf 题号71，参考答案键号 71. B＝绛舌。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1012",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列舌象中，除（ ）之外，健康人均可出现",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号72（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["裂纹舌", "齿痕舌", "剥落苔", "淡红舌", "淡白舌"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "淡白舌",
        "淡白舌为病理舌色（主气血两虚、阳虚），健康人不出现；淡红舌为正常舌色，裂纹舌、齿痕舌、地图样轻度剥落可见于健康人生理变异，故选淡白舌。选择.pdf 题号72，参考答案键号 72. E＝淡白舌。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1013",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "观察舌苔辨邪之浅深，主要依据",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号73（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["舌苔有无", "舌苔厚薄", "舌苔润燥", "舌苔颜色", "舌苔腐腻"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "舌苔厚薄",
        "苔薄主邪浅病轻，苔厚主邪深病重、痰湿食积，故辨邪之浅深主要依据舌苔厚薄；苔色辨病邪性质，润燥辨津液盈亏，有无辨胃气存亡。选择.pdf 题号73，参考答案键号 73. B＝舌苔厚薄。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1014",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者舌色淡紫而润，主病为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号75（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写，OCR 错字（菸→瘀）按医学语义恢复",
      sourceIds: [],
    },
    choices: ["气滞血瘀", "气虚血瘀", "寒凝血瘀", "外伤血瘀", "血虚夹瘀"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "寒凝血瘀",
        "淡紫而湿润多津为寒凝血瘀之象，寒凝则舌淡紫、津液未伤故润；绛紫干燥多热盛血瘀，局部紫斑紫点多气滞血瘀，血虚夹瘀多舌淡晦不润（原选项“气滞血菸”为 OCR 误字，已恢复为“气滞血瘀”）。选择.pdf 题号75，参考答案键号 75. C＝寒凝血瘀。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1015",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者素体阴虚火旺，复感风寒之邪，可见",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号77（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["红瘦舌，灰苔", "绛舌，薄白苔", "绛舌，黄白相兼苔", "淡白舌，黄裂苔", "红舌，苍老滑苔"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "绛舌，薄白苔",
        "素体阴虚火旺故舌绛（或红），复感风寒之邪、表寒尚未入里故苔仍薄白，综合为绛舌薄白苔；灰苔、黄裂苔、黄白相兼苔均非风寒表浅之象，故取绛舌薄白苔。选择.pdf 题号77，参考答案键号 77. B＝绛舌，薄白苔。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1016",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "舌质红，苔黄厚，多见于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号79（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["里实热证", "虚热证", "胃气阴大伤证", "热入营血证", "痰热证"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "里实热证",
        "舌质红、苔黄厚为里实热之火热蒸腾所致；虚热多舌红少苔，热入营血多绛舌少苔或无苔，痰热多苔黄腻，胃气阴大伤多舌红少苔光剥，故取里实热证。选择.pdf 题号79，参考答案键号 79. A＝里实热证。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-a1017",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "观察舌苔辨别病邪的性质主要依据是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；中医诊断学选择.pdf题号80（同学整理参考版）`,
      note: "同学整理参考版，以教材为准；选择题题干轻度改写",
      sourceIds: [],
    },
    choices: ["舌苔有无", "舌苔润燥", "舌苔厚薄", "舌苔颜色", "舌苔真假"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "舌苔颜色",
        "苔白主表、寒、湿，苔黄主里热，苔灰黑主里之寒极或热极，故以舌苔颜色辨别病邪性质；有无辨胃气存亡，厚薄辨邪之浅深，润燥辨津液盈亏。选择.pdf 题号80，参考答案键号 80. D＝舌苔颜色。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答/问答（short-answer），6 道（舌色/舌形/舌态/苔质/苔色/舌象分析合参） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-short001",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述淡白、红、绛、青紫舌的表现和临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第6天背诵内容及答案 大题3 舌色（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①淡红舌：舌色淡红润泽，为正常舌色，说明气血调和，也可见外感初起、病情轻浅。②淡白舌：舌色较正常浅淡甚至枯白，主气血两虚、阳虚寒证，枯白舌可见亡血夺气。③红舌：舌色较正常鲜红，主热证——舌红苔黄多实热，舌红少苔多阴虚内热。④绛舌：舌色深红，主里热亢盛、热入营血或阴虚火旺。⑤青紫舌：舌色青紫或有瘀点瘀斑，主气血运行不畅——淡紫湿润多寒凝血瘀，绛紫干燥多热盛血瘀，局部紫斑紫点多气滞血瘀。",
        "舌色主要反映气血盛衰与寒热虚实：淡红为常，淡白为气血两虚或阳虚，红为热证，绛为热入营血或阴虚火旺，青紫为血行不畅（寒凝、热盛、气滞、血瘀）。缘引 第6天背诵内容及答案 大题3 一、舌色。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-short002",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述老嫩、胖瘦、点刺、裂纹、齿痕舌的表现和临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第6天背诵内容及答案 大题3 舌形（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①老舌：舌质苍老坚敛、纹理粗糙，多主实证；嫩舌：质地娇嫩松软、浅淡，多主虚证。②胖大舌：舌体较大、边有齿痕，淡白胖嫩多阳虚水湿，红肿胖大多湿热或热毒；瘦薄舌：舌体瘦小薄弱，淡白瘦薄多气血两虚，红绛瘦薄、少苔多阴虚火旺。③点刺舌：舌乳头增大高起呈点刺状，主脏腑热盛或血分热盛，舌尖多心火、舌中多胃肠热。④裂纹舌：舌面有深浅不一裂沟，红绛而裂多热盛伤津，淡白而裂多阴血不足，胖嫩有裂可见脾虚湿盛。⑤齿痕舌：舌边有牙齿压迫痕迹，多主脾虚湿盛，常与胖大舌并见。",
        "舌形反映邪正虚实与津液化源：老嫩辨虚实，胖瘦多水湿与气血，点刺为热盛，裂纹辨津伤与阴血不足，齿痕主脾虚湿盛。缘引 第6天背诵内容及答案 大题3 二、舌形。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-short003",
    order: 29,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述痿软、强硬、歪斜、颤动、吐弄、短缩舌的表现和临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第6天背诵内容及答案 大题3 舌态（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①痿软舌：舌体软弱无力伸缩，多主气血俱虚、阴液亏极或热灼津伤。②强硬舌：舌体强直、屈伸不利，可伴语言謇涩，多主热入心包、热盛伤津或风痰阻络。③歪斜舌：伸舌偏向一侧，多主中风或中风先兆，常因肝风夹痰、痰瘀阻络。④颤动舌：舌体震颤不能自主，久病多气血亏虚，新病多热极生风或肝风内动。⑤吐弄舌：舌伸出口外不回为吐舌、反复微伸舐唇为弄舌，多主心脾有热或动风先兆。⑥短缩舌：舌体卷短紧缩不能伸长，主寒凝筋脉、痰湿内阻、气血虚衰或热盛伤津，病情较重。",
        "舌态多反映动风、热扰或气血筋脉受损：痿软为气血阴液亏虚，强硬为热入心包或风痰阻络，歪斜为中风征兆，颤动为肝风或气血亏虚，吐弄为心脾热或动风，短缩多属危重。缘引 第6天背诵内容及答案 大题3 舌态。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-short004",
    order: 30,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "薄苔、厚苔、润苔、燥苔、腻苔、腐苔、剥落苔、真假苔如何鉴别？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第6天背诵内容及答案 大题4 苔质（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①薄苔：透过舌苔能隐约见舌质，属正常或表证、病轻；厚苔：不能见底，主里证、痰湿、食积，邪盛病重。②润苔：舌苔润泽有津，津液未伤或水湿内停；燥苔：干燥少津，津液已伤或阳虚气不化津。③腻苔：颗粒细腻致密、如涂油腻、紧贴难刮，主湿浊、痰饮、食积；腐苔：颗粒粗大疏松、如豆腐渣、较易刮去，多主食积、痰浊，脓腐苔可见内痈。④剥落苔：舌苔部分或全部脱落，主胃气不足、胃阴损伤或气血两虚，全剥可见镜面舌。⑤真苔：紧贴舌面、有根、刮之难去，提示胃气尚存；假苔：浮涂无根、刮之即去，多胃气衰败、病情较重。",
        "苔质主要反映津液盈亏、病邪深浅与胃气盛衰：薄厚辨深浅轻重，润燥辨津液盈亏，腻腐辨湿浊痰积，剥脱辨胃气胃阴，真假辨胃气存亡。缘引 第6天背诵内容及答案 大题4 一、苔质。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-short005",
    order: 31,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述白苔、黄苔、灰黑苔的临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第6天背诵内容及答案 大题4 苔色（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①白苔：主表证、寒证，也可见于湿证——薄白而润可为正常或表寒，白厚腻多痰湿、食积。②黄苔：主热证、里证——颜色越深热势越重，薄黄热轻，深黄热重，焦黄热结，黄腻多湿热、痰热或食积化热。③灰黑苔：主里证，可见寒极或热极——灰黑而干多热极津枯，灰黑而润滑多寒湿内盛或阳虚。",
        "苔色辨病邪性质：白主表寒湿，黄主里热（色深热重），灰黑主里（润为寒湿阳虚、干为热极津枯）。口诀：白表寒，黄里热；灰黑主里，润为寒湿，干为热极。缘引 第6天背诵内容及答案 大题4 二、苔色。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-tcm-diagnostics-bank-tcm-diagnostics-bank-ch03-shezhen-short006",
    order: 32,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "舌质与舌苔如何合参？舌象分析有哪些原则？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: `${locatorBase}；第2天背诵内容及答案 舌质与舌苔合参（项目整理标准答案）`,
      note: "项目整理标准答案；题干轻度改写",
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①舌质主要反映脏腑气血阴阳盛衰，舌苔主要反映病邪性质、深浅及胃气盛衰。②合参原则：舌质与舌苔一致时判断较直接；不一致时结合病程、症状和脉象，分清标本、先后和真假。③常见组合快答：淡白胖大、白滑苔多阳虚水湿；红绛瘦薄、少苔多阴虚火旺；红舌黄厚干苔多里热炽盛、津伤；淡红舌白腻苔多痰湿或寒湿。④同时察舌之神气与胃气：荣润红活、活动自如为有神；苔薄白有根为有胃气，苔骤剥、镜面无苔或苔无根多为胃气胃阴受损。",
        "舌象分析须舌质舌苔合参而不能只凭一种表现下结论：舌质定脏腑气血阴阳之本，舌苔标病邪深浅与胃气盛衰，二者不一致时重舌质并结合病程、症状、脉象综合辨别。缘引 第2天背诵内容及答案 舌质与舌苔合参。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1/B2 配伍题（bGroups），0 组（本书无 B1/B2 型） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems, ...a1Items, ...shortItems,
];
export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];