import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 组织学与胚胎学学习指导与习题集（第4版）— 第14章 消化管 题库提取（等比取样）
 * 来源：《组织学与胚胎学学习指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：9 题
 * - 选择题（a1-single）：11 题（含 3 道 X 型映射为单选）
 * - 填空题（fill）：0 题
 * - 简答/问/论述题（short-answer）：8 题
 * - B1 配伍题：3 组、共 9 个成员
 * - 独立记分题合计：37 题（须等于本文件预算 37）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含选择题（A1 型 22、B1 型 3 组 9 小题、多选题 12）、名词解释 9、
 *   简答题 6、论述题 2，无填空题；本文件按 37 道预算等比取材并在原书顺序内取满。题干/
 *   选项/题号在双栏排版中交错散落（如某题 A 项出现后隔行才见其 E 项），已按组织学医学
 *   语义重建完整选项集合，正确项全数对照章末「参考答案」键号锚定。数值（微绒毛、皱襞倍数、
 *   细胞位置/深度）、结构、细胞类型均保留原值，未捏造。第 29/30/31 题组内胃与结肠均取
 *   "外膜为浆膜"，与源参考答案 30/31 均为 D 一致。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "histology-embryology-ch14-alimentary-canal";
const locatorBase =
  "《组织学与胚胎学学习指导与习题集》第4版 第14章 消化管 复习思考题 习题（核对PDF 第117–127页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多选，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），9 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：黏膜肌层",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "黏膜肌层",
        "是消化管（除口腔和咽以外）黏膜固有层深面的一薄层平滑肌。其收缩运动可使黏膜活动，促使黏膜固有层内腺体分泌物排出和血液与淋巴运行，利于物质的消化吸收。原书名词解释第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：味蕾",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "味蕾",
        "是味觉感受器，呈卵圆形小体，主要分布于舌的菌状乳头和轮廓乳头，少数散在于软腭、会厌及咽等部上皮内。味蕾顶部有一小孔称味孔。味蕾内有大量长梭形的味细胞，为感觉细胞，细胞顶部有微绒毛伸入味孔内，细胞基底面与神经末梢形成突触。原书名词解释第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：中央乳糜管",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中央乳糜管",
        "绒毛中轴的固有层结缔组织内，有 1～2 条中央乳糜管，它的起始部为盲端，向下穿过黏膜肌层进入黏膜下层形成淋巴管丛。中央乳糜管管腔较大，内皮细胞间隙宽，无基膜，故通透性大。吸收细胞释放出的乳糜微粒进入中央乳糜管输出。原书名词解释第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肠相关淋巴组织",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肠相关淋巴组织",
        "即消化管淋巴组织，包括黏膜淋巴小结，固有层中弥散分布的淋巴细胞、浆细胞、巨噬细胞、间质树突状细胞、上皮内的淋巴细胞等成分。消化管淋巴组织能接受消化管内的抗原刺激，并主要通过产生和向消化管腔分泌免疫球蛋白作为免疫应答。原书名词解释第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：微皱褶细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "微皱褶细胞",
        "又称 M 细胞。在肠集合淋巴小结处，局部黏膜向肠腔隆起，无微绒毛和小肠腺，此部位上皮内有散在分布的 M 细胞。M 细胞基底面质膜内陷形成一较大的穹窿状凹腔，凹腔内含有多个淋巴细胞和巨噬细胞。M 细胞下方的基膜多不完整，淋巴细胞易通过。M 细胞可摄取肠腔内抗原，通过巨噬细胞将抗原传递给下方的淋巴细胞（B 细胞），发挥免疫作用。原书名词解释第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：小肠皱襞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "小肠皱襞",
        "由小肠的黏膜和黏膜下层共同向肠腔内突出形成，和小肠绒毛一起扩大了小肠的表面积。原书名词解释第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：帕内特细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "帕内特细胞",
        "是小肠腺的特征性细胞，常三五成群，位于腺底部。细胞呈锥体形，胞质顶部充满粗大嗜酸性颗粒，内含溶菌酶等，具有一定的灭菌作用。原书名词解释第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：杯状细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "杯状细胞",
        "分布于肠黏膜上皮和肠腺内。细胞呈高脚酒杯状，顶部膨大充满黏原颗粒，胞质色浅，在 HE 切片中颗粒溶解，故呈空泡状，细胞基部细窄。核呈扁圆或三角形，位于基底部，染色深。杯状细胞具有分泌黏液功能。原书名词解释第 8 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：浆膜",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "浆膜",
        "为消化管外膜的一种类型，由薄层结缔组织和间皮共同构成，间皮为单层扁平细胞，表面光滑，可减小腹腔器官移动时相互间产生的摩擦。原书名词解释第 9 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/X 型选择题（统一映射为 a1-single），11 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-a1001",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于食管的组织结构特点，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "腔面有纵行皱襞",
      "黏膜上皮是未角化的复层扁平上皮",
      "黏膜下层内含有黏液腺",
      "肌层含平滑肌和骨骼肌",
      "外膜为浆膜",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "外膜为浆膜（错误项）",
        "食管黏膜为未角化的复层扁平上皮，黏膜下层含黏液性食管腺，肌层上 1/3 为骨骼肌、下 1/3 为平滑肌、中 1/3 混合；食管外膜为纤维膜而非浆膜，故“外膜为浆膜”说法错误。原书 A1 参考答案第 1 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-a1002",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胃黏膜上皮的主要细胞是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "主细胞",
      "壁细胞",
      "内分泌细胞",
      "表面黏液细胞",
      "表面浆液细胞",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "表面黏液细胞",
        "胃黏膜上皮为单层柱状上皮，主要由表面黏液细胞组成，分泌的黏液覆盖上皮，有重要保护作用。原书 A1 参考答案第 2 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-a1003",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不是胃底腺细胞的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "主细胞",
      "壁细胞",
      "帕内特细胞",
      "未分化细胞",
      "内分泌细胞",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "帕内特细胞",
        "胃底腺由主细胞（胃酶细胞）、壁细胞（泌酸细胞）、颈黏液细胞和内分泌细胞组成；帕内特细胞是小肠腺的特征性细胞，不属于胃底腺细胞。原书 A1 参考答案第 3 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-a1004",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胃底腺壁细胞合成盐酸的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "粗面内质网",
      "滑面内质网",
      "高尔基复合体",
      "微管泡系统",
      "细胞内分泌小管",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞内分泌小管",
        "壁细胞内游离面的细胞膜内陷形成细胞内分泌小管，H+ 和 Cl- 转运到小管内并结合形成盐酸。微管泡系统是分泌期小管与胞膜间的贮备结构。原书 A1 参考答案第 4 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-a1005",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于胃底腺主细胞的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "主要位于腺的颈部",
      "细胞呈柱状，细胞核位基底部",
      "大量的粗面内质网聚集在核周围细胞基部",
      "胞质嗜碱性",
      "分泌胃蛋白酶原被盐酸激活",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "主要位于腺的颈部（错误项）",
        "主细胞又称胃酶细胞，分布于胃底腺的体、底部（壁细胞多在颈、体部）；细胞呈柱状、核居基底部，胞质基部强嗜碱性、含大量粗面内质网，顶部充满酶原颗粒，分泌胃蛋白酶原经盐酸激活成胃蛋白酶。故“主要位于腺的颈部”说法错误。原书 A1 参考答案第 5 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-a1006",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胃底腺主细胞顶部充满",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "黏原颗粒",
      "嗜银颗粒",
      "大量粗面内质网",
      "酶原颗粒",
      "大量滑面内质网",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "酶原颗粒",
        "主细胞顶部充满圆形酶原颗粒，其分泌胃蛋白酶原；粗面内质网位于核周、胞质基部。原书 A1 参考答案第 6 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-a1007",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "小肠消化吸收的主要部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "绒毛表面的黏液层",
      "微绒毛表面的细胞衣",
      "吸收细胞的粗面内质网",
      "吸收细胞的滑面内质网",
      "小肠绒毛内的杯状细胞",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "微绒毛表面的细胞衣",
        "微绒毛表面的细胞衣是小肠消化吸收的重要部位，其中含有参与消化碳水化合物和蛋白质的双糖酶和肽酶。原书 A1 参考答案第 9 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-a1008",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于帕内特细胞的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "为小肠腺的特征性细胞",
      "位于腺底部，常三五成群",
      "细胞呈柱形",
      "胞质顶部充满粗大嗜酸性颗粒",
      "颗粒内含溶菌酶，具有灭菌作用",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞呈柱形（错误项）",
        "帕内特细胞是小肠腺的特征性细胞，位于腺底部、常三五成群，细胞呈锥体形而非柱形，胞质顶部充满粗大嗜酸性颗粒，内含防御素和溶菌酶等，具灭菌作用。故“细胞呈柱形”说法错误。原书 A1 参考答案第 10 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-a1009",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "壁细胞分泌（原题为多选，此处单选其中一正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "盐酸",
      "胃泌素",
      "内因子",
      "组胺",
      "胃蛋白酶原",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "盐酸",
        "壁细胞分泌盐酸和内因子，盐酸激活胃蛋白酶原为胃蛋白酶，内因子与维生素 B12 结合促进回肠吸收。胃泌素由 G 细胞分泌，组胺由 ECL 细胞分泌，胃蛋白酶原由主细胞分泌。原书多选题第 33 题参考答案为 AC，此处单选取其中一正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-a1010",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "产生黏液的细胞是（原题为多选，此处单选其中一正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "颈黏液细胞",
      "表面黏液细胞",
      "杯状细胞",
      "帕内特细胞",
      "微皱褶细胞",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "杯状细胞",
        "杯状细胞分泌黏液，此外颈黏液细胞、表面黏液细胞也能分泌黏液；帕内特细胞分泌溶菌酶和防御素，微皱褶细胞主要摄取并传递抗原。原书多选题第 34 题参考答案为 ABC，此处单选取其中一正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-a1011",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于胃肠内分泌细胞的描述，正确的是（原题为多选，此处单选其中一正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "属于含氮激素分泌细胞",
      "分泌颗粒位于细胞基底部",
      "为高柱状，游离面均达管腔",
      "宜用免疫组织化学方法显示",
      "于胃幽门部和十二指肠最多",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "属于含氮激素分泌细胞",
        "胃肠内分泌细胞大多单个夹于上皮细胞间，分泌颗粒位于基底部，属含氮激素分泌细胞；开放型游离面有微绒毛伸向管腔、封闭型顶部被覆盖而未露腔面，故“游离面均达管腔”错误。胃幽门部和十二指肠检出此类细胞较多。原书多选题第 36 题参考答案为 ABDE，此处单选取其中一正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），本章无，置空 */
const fillItems: readonly AssessmentItemDefinition[] = [];

/** 简答/论述题（short-answer），8 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-short001",
    order: 21,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：试述小肠黏膜的结构与小肠吸收功能的关系。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "小肠黏膜结构与吸收功能的关系",
        "答：①形成环状皱襞、绒毛及上皮游离面的微绒毛，三级扩大吸收表面积；②上皮的吸收细胞为高柱状，游离面有密集排列的微绒毛，表面有较厚的细胞衣，吸附有多种消化酶，与消化吸收有关；③吸收细胞吸收单糖、氨基酸，经细胞侧面的间隙进入固有层的毛细血管网；④细胞吸收的脂肪酸和甘油一酯，在胞质内合成为乳糜微粒，后经细胞侧面释出，进入固有层的中央乳糜管；⑤固有层内散在平滑肌的收缩使绒毛不断活动，以促进物质吸收和血液、淋巴的运行。原书简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-short002",
    order: 22,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：试述壁细胞的分布、结构与功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "壁细胞的分布、结构与功能",
        "答：壁细胞多分布于胃底腺的颈、体部。壁细胞体积大，呈圆锥形、三角形、圆形，细胞核圆形居中，胞质嗜酸性。电镜下细胞游离面的细胞膜向胞质内凹陷形成细胞内分泌小管。小管腔面有大量的微绒毛，可扩大小管的表面积。细胞内分泌小管将 H+、Cl- 转运到小管内，H+、Cl- 结合形成盐酸。小管周围的胞质有微管泡系统。分泌期合成盐酸时，小管的微绒毛增多增长、充满小管腔，而微管泡系统数量减少；静止期不合成盐酸时，小管微绒毛短而稀疏，而微管泡系统极发达。功能：壁细胞分泌盐酸，激活胃蛋白酶原形成胃蛋白酶；人的壁细胞还分泌内因子，与维生素 B12 结合形成复合物，使维生素 B12 不易被酶分解。原书简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-short003",
    order: 23,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：试述食管腺的分布、结构和功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "食管腺的分布、结构和功能",
        "答：食管腺位于食管的黏膜下层，由分泌部和导管部组成，分泌部为黏液性腺泡，腺细胞呈锥体形，胞质染色淡，细胞核扁圆形、位于细胞底部，电镜下可见胞质内含粗大的黏原颗粒。腺细胞分泌黏液，分泌的黏液涂布于食管表面，利于食物通过。原书简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-short004",
    order: 24,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：试述小肠绒毛的形成、结构和功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "小肠绒毛的形成、结构和功能",
        "答：小肠的黏膜上皮和固有层向肠腔伸出许多指状突起，称小肠绒毛。小肠绒毛表面覆以单层柱状上皮，由吸收细胞、杯状细胞和内分泌细胞组成。吸收细胞数量最多，游离面有大量微绒毛密集排列形成纹状缘，扩大游离面的表面积；微绒毛表面有较厚的细胞衣，内含多种酶，故细胞衣是小肠消化、吸收的重要部位。杯状细胞分泌黏液。内分泌细胞散在分布于吸收细胞之间，分泌胃肠激素，调节小肠的功能。绒毛中轴为固有层，由疏松结缔组织构成，内含中央乳糜管、有孔毛细血管和散在的平滑肌纤维。吸收细胞吸收的葡萄糖、氨基酸经有孔毛细血管进入血液循环，乳糜微粒经中央乳糜管运输。功能：①绒毛有吸收糖、蛋白质、脂类作用；②绒毛有分泌黏液功能；③绒毛还有扩大小肠表面积的作用。原书简答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-short005",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：试述胃上皮细胞的结构及功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胃上皮细胞的结构及功能",
        "答：胃上皮细胞为单层柱状，主要由表面黏液细胞组成。该细胞椭圆形的核位于基部，顶部胞质充满黏原颗粒，在 HE 染色切片上着色浅淡以至透明；上皮细胞分泌物中富含中性糖蛋白，分泌至细胞表面形成一层保护性的黏液膜，可防止高浓度盐酸与胃蛋白酶对黏膜的消化以及食物对上皮的磨损。相邻柱状细胞在近游离面处形成紧密连接，起屏障作用，防止胃腔内的化学物质进入胃壁；黏液膜和紧密连接共同组成屏障，起保护作用。原书简答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-short006",
    order: 26,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：试述小肠腺的结构和功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "小肠腺的结构和功能",
        "答：小肠相邻绒毛根部之间的上皮内陷，深入固有层中，形成小肠腺，又称肠隐窝。肠腺上皮内有吸收细胞、杯状细胞、帕内特细胞、未分化细胞和内分泌细胞。吸收细胞数量最多，其游离面有微绒毛，扩大细胞游离面面积，表面的细胞衣有利于小肠的消化与吸收。杯状细胞分泌黏液，涂于上皮表面，起屏障作用。帕内特细胞位于肠腺基部，常三五成群，细胞较大，呈圆锥形，核卵圆位于基部，顶部胞质含粗大的嗜酸性颗粒，基部胞质嗜碱性；电镜下胞质中含丰富的粗面内质网、发达的高尔基复合体及粗大的酶原颗粒；能分泌溶菌酶和防御素等物质。内分泌细胞可产生缩胆囊素-促胰酶素以及促胰液素，促进胰液和胆汁的分泌与排出，为胰酶提供碱性环境。原书简答题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-short007",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "论述题：试述消化管壁一般结构。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "消化管壁一般结构",
        "答：除口腔外，消化管管壁自内向外分为四层结构：黏膜、黏膜下层、肌层和外膜。(1)黏膜：由内向外依次分为上皮、固有层和黏膜肌层。①上皮：消化管的两端（口腔、咽、食管及肛门）为未角化的复层扁平上皮，具有保护作用；胃肠道是单层柱状上皮，以消化、吸收功能为主。②固有层由富有淋巴组织和免疫细胞的疏松结缔组织构成，并含有丰富的血管、淋巴管、神经、小腺体和散在的平滑肌纤维。③黏膜肌层为薄层平滑肌。(2)黏膜下层：由疏松结缔组织组成，内含较大的血管、淋巴管、神经纤维和黏膜下神经丛；在食管及十二指肠的黏膜下层内，分别有食管腺与十二指肠腺。(3)肌层：口腔、咽、食管上段和肛门处的肌层为骨骼肌，食管中段为平滑肌和骨骼肌兼具，其余为平滑肌；肌层一般分为内环行、外纵行两层（胃有三层），其间有肌间神经丛。(4)外膜：咽、食管和大肠末段的外膜为纤维膜；其余消化管的外膜是浆膜。原书论述题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-short008",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "论述题：试比较胃和小肠黏膜结构和功能的异同。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胃和小肠黏膜结构和功能的异同",
        "答：胃和小肠的黏膜都由三层结构构成，上皮均为单层柱状，固有层的疏松结缔组织内都含有丰富的有孔毛细血管，黏膜肌层为薄层的平滑肌。胃的上皮向固有层凹陷形成胃小凹，其深部的干细胞可增殖分化，补充衰老脱落的上皮细胞；小肠的上皮与固有层组织共同凸起，形成肠绒毛，增大了小肠的内表面积，有利于营养物质吸收。胃上皮主要由表面黏液细胞构成，该细胞分泌的碱性黏液形成黏液-碳酸氢盐屏障，保护胃黏膜不受胃液中的胃蛋白酶和盐酸的损伤；小肠上皮主要由吸收细胞和杯状细胞构成，前者从事营养的吸收，后者分泌的黏液具有润滑作用。胃固有层中含贲门腺、幽门腺和胃底腺，前两者主要分泌黏液；胃底腺中的主细胞分泌胃蛋白酶原，壁细胞分泌盐酸和内因子，是胃液中参与消化的重要成分。小肠固有层含小肠腺，其深部的干细胞可增殖分化为吸收细胞和杯状细胞，迁移、补充在绒毛顶部脱落的上皮细胞；此外，小肠腺还具有特征性的帕内特细胞，分泌溶菌酶和防御素，发挥免疫作用。在胃上皮和腺体中主要的内分泌细胞是 ECL 细胞、G 细胞和 D 细胞，分泌的组胺、胃泌素和生长抑素主要调节盐酸的分泌。小肠上皮和腺体中主要的内分泌细胞有 S 细胞和 I 细胞，分泌促胰液素和缩胆囊素-促胰酶素，主要刺激胰和胆囊中消化液的分泌和排放，以进入小肠参与消化。原书论述题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，3 组 × 共 9 成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-b001",
    order: 29,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "消化蛋白质",
      "吸收营养物质",
      "吸收水分",
      "分泌黏液",
      "分泌盐酸",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch14-alimentary-canal-b001m1",
        order: 29,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "胃柱状细胞的主要功能有",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "分泌黏液",
            "胃表面黏液细胞分泌黏液形成保护性黏液膜。原书 B1 第 23 题答案 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch14-alimentary-canal-b001m2",
        order: 30,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "小肠柱状细胞的主要功能有",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "吸收营养物质",
            "小肠柱状（吸收）细胞是消化吸收的主要执行者。原书 B1 第 24 题答案 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch14-alimentary-canal-b001m3",
        order: 31,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "大肠柱状细胞的主要功能有",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "吸收水分",
            "大肠的主要功能是吸收水分和电解质，使食物残渣形成粪便。原书 B1 第 25 题答案 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-b002",
    order: 32,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "分泌内因子",
      "分泌防御素",
      "分泌黏液",
      "分泌蛋白水解酶",
      "分泌胃泌素",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch14-alimentary-canal-b002m1",
        order: 32,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "胃腺壁细胞",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "分泌内因子",
            "壁细胞分泌盐酸和内因子，内因子与维生素 B12 结合促进回肠吸收。原书 B1 第 26 题答案 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch14-alimentary-canal-b002m2",
        order: 33,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "帕内特细胞",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "分泌防御素",
            "帕内特细胞分泌溶菌酶和防御素等，具有一定灭菌作用。原书 B1 第 27 题答案 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch14-alimentary-canal-b002m3",
        order: 34,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "杯状细胞",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "分泌黏液",
            "杯状细胞具有分泌黏液功能，起润滑和保护作用。原书 B1 第 28 题答案 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch14-alimentary-canal-b003",
    order: 35,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "表面为假复层纤毛柱状上皮",
      "表面为未角化的复层扁平上皮",
      "黏膜下层含黏液性腺体",
      "外膜为浆膜",
      "表面有绒毛",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch14-alimentary-canal-b003m1",
        order: 35,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "食管",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "黏膜下层含黏液性腺体",
            "食管黏膜下层含黏液性食管腺，分泌黏液起润滑作用；其外膜为纤维膜。原书 B1 第 29 题答案 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch14-alimentary-canal-b003m2",
        order: 36,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "胃",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "外膜为浆膜",
            "胃的肌层为内斜、中环、外纵三层平滑肌，外膜为浆膜。原书 B1 第 30 题答案 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch14-alimentary-canal-b003m3",
        order: 37,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "结肠",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "外膜为浆膜",
            "结肠（人多部分）外膜为浆膜，表面无绒毛，肠腺含大量杯状细胞。原书 B1 第 31 题答案 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...fillItems,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];