import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 组织学与胚胎学学习指导与习题集（第4版）— 第21章 胚胎发生总论 题库提取（等比取样）
 * 来源：《组织学与胚胎学学习指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：6 题
 * - 选择题（a1-single）：15 题（A1 型 9 道 + 多选映射 6 道）
 * - 填空题（fill）：0 题
 * - 简答/问/论述题（short-answer）：7 题
 * - B1 配伍题：2 组、共 8 个成员
 * - 独立记分题合计：36 题（须等于本文件预算 36）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含选择题（A1 型 1–21、B1 型 2 组 8 小题、多选题 30–41）、
 *   名词解释 9、简答题 6、论述题 3，无填空题；本文件按 36 道预算等比取材并在原书顺序内
 *   取满。双栏排版中题干/选项/题号/字母交错散落，已按胚胎学医学生理语义重建完整选项集合；
 *   正确项均对照本章末尾「参考答案」键号（如 1.B 2.B …）锚定。发育时间（受精后第3天/4天/5~6天
 *   起始 11~12天完成、第8周末、266天、1000~1500ml 羊水、40~60cm 脐带）、结构（桑葚胚、胚泡、
 *   滋养层、原条、脊索、体蒂）与数值均保留原值，未捏造。多选题 30/31/32/36/40/41 按项目规约
 *   映射为 a1-single，仅取其中一个正确项。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "histology-embryology-ch21-general-embryology";
const locatorBase =
  "《组织学与胚胎学学习指导与习题集》第4版 第21章 胚胎发生总论 复习思考题 习题（核对PDF 第171–182页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多选，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），6 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch21-general-embryology-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：获能",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "获能",
        "精子头的外表面原本被一层来自精液中的糖蛋白所覆盖，能阻止顶体酶释放。当精子通过子宫和输卵管时，该糖蛋白被去除，从而使精子获得了释放顶体酶、使卵子受精的能力，此现象称获能。原书名词解释第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：透明带反应",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "透明带反应",
        "受精过程中，精卵结合后，卵子浅层胞质内的皮质颗粒立即释放溶酶体酶，使透明带结构发生变化，特别是使ZP3分子变性，不能再与精子结合，从而阻止了其他精子穿越透明带，这一过程称透明带反应。这一反应保证了正常的单精受精。原书名词解释第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：胚泡",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胚泡",
        "桑葚胚进入子宫腔，细胞之间出现腔隙，形成一泡状结构，称胚泡。其内部腔隙叫胚泡腔；壁由单层细胞构成叫滋养层，与吸收营养有关；腔内一侧有一团细胞叫内细胞群，是胚胎发生的原基。原书名词解释第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：脊索",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脊索",
        "当原条出现之后，其原凹的细胞增殖，在内、外胚层之间向头端增生迁移，直抵口咽膜，形成一条单独的中胚层细胞索，称脊索，它在早期胚胎起一定支架作用，并诱导外胚层形成神经板。原书名词解释第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：胚盘",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胚盘",
        "第2周末，胚泡的内细胞群增殖分化形成圆盘状的结构称胚盘，细胞分两层：上胚层和下胚层。第3周末时，胚盘发育为三个胚层：外胚层、中胚层、内胚层，此即三胚层胚盘。胚盘是人体发育的原基。原书名词解释第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：单卵孪生",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单卵孪生",
        "即一个受精卵发育为两个胚胎，这种孪生儿的遗传基因完全一样，因此性别一致，相貌、体态和生理特征等也极相似。单卵孪生的成因可以是：①从受精卵发育出两个胚泡而分别植入；②一个胚泡内出现两个内细胞群，各发育为一个胚胎；③一个胚盘上出现两个原条与脊索，形成两个神经管，发育为两个胚胎。原书名词解释第 9 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/X 型选择题（统一映射为 a1-single），15 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1001",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "精子获能发生在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["附睾", "输精管", "女性生殖管道", "男性生殖管道", "睾丸网"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "女性生殖管道",
        "精子在附睾内获得定向运动能力和受精潜力，但头部外表面被精液中的糖蛋白覆盖，阻止顶体酶释放；当精子通过子宫和输卵管时糖蛋白被去除，称获能。故获能发生在女性生殖管道。原书 A1 参考答案第 1 题为 B，按选项重排后正确项即「女性生殖管道」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1002",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "受精多发生于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "子宫体部或底部",
      "输卵管峡部",
      "输卵管壶腹部",
      "输卵管漏斗部",
      "输卵管子宫部",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "输卵管壶腹部",
        "精子与卵子结合形成受精卵的过程称受精，一般发生在输卵管壶腹部。原书 A1 参考答案第 2 题为 B，按选项重排后正确项即「输卵管壶腹部」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1003",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于植入的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "植入时的子宫内膜处于分泌期",
      "植入部位通常在子宫体和子宫底",
      "桑葚胚埋入子宫内膜的过程",
      "透明带已消失",
      "开始于受精后第5～6天，完成于第11～12天",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "植入部位通常在子宫体和子宫底",
        "植入是胚泡逐渐埋入子宫内膜的过程，植入部位通常在子宫体和子宫底；植入约于受精后第5～6天起始，第11～12天完成，此时子宫内膜处于分泌期，透明带已消失。原书 A1 参考答案第 3 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1004",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不属于胎膜的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["卵黄囊", "脐带", "胎盘", "绒毛膜、羊膜", "尿囊"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胎盘",
        "胎膜包括绒毛膜、羊膜、卵黄囊、尿囊和脐带；胎盘是由胎儿的丛密绒毛膜与母体的基蜕膜共同组成的圆盘形结构，不属于胎膜。原书 A1 参考答案第 9 题为 D，按选项重排后正确项即「胎盘」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1005",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "从卵巢排出的卵子处于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "第一次减数分裂中期",
      "第一次减数分裂前期",
      "第二次减数分裂前期",
      "第二次减数分裂中期",
      "第二次减数分裂后期",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第二次减数分裂中期",
        "排卵后，卵子处于第二次减数分裂的中期，进入并停留在输卵管壶腹部；当受到精子激发时才完成第二次减数分裂。原书 A1 参考答案第 11 题为 D，按选项重排后正确项即「第二次减数分裂中期」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1006",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "精卵结合后，使透明带结构发生变化是由于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["卵子", "精子", "卵泡细胞", "透明带自身"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "卵子",
        "精卵结合后，卵子浅层胞质内的皮质颗粒立即释放溶酶体酶，使透明带结构发生变化，特别是使ZP3分子变性，这一过程称透明带反应。故引起透明带结构变化的是卵子（皮质颗粒）。原书 A1 参考答案第 12 题为 A，即「卵子」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1007",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "宫外孕最常发生于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["输卵管", "卵巢表面", "腹膜腔", "子宫直肠陷窝", "输卵管壶腹部"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "输卵管",
        "受精多发生于输卵管壶腹部，若受精卵常在输卵管内植入则形成输卵管妊娠（宫外孕最常见于此）。原书 A1 参考答案第 14 题为 B，按选项重排后正确项即「输卵管」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1008",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "前置胎盘是由于胚泡植入在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["子宫底部", "子宫后壁", "近子宫颈处", "子宫前壁", "子宫颈管"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "近子宫颈处",
        "若胚泡植入在近子宫颈处，绒毛膜在子宫颈内口处发育形成胎盘，即前置胎盘。原书 A1 参考答案第 15 题为 C，按选项重排后正确项即「近子宫颈处」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1009",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "人胚初具雏形（初具人形）的时间是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["第4周", "第10周", "第8周", "第3个月", "第4个月"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第8周",
        "伴随三胚层分化，胚盘边缘向腹侧卷折形成头褶、尾褶和左右侧褶，至第8周末胚体外表初具人形。原书 A1 参考答案第 19 题为 B，按选项重排后正确项即「第8周」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1010",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "排卵时，从成熟卵泡中排出的是（原题为多选，此处单选其中一正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["颗粒细胞", "次级卵母细胞", "卵泡膜细胞", "透明带", "放射冠"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "次级卵母细胞",
        "排卵时从成熟卵泡中排出的是次级卵母细胞（连同透明带、放射冠等）。原书多选题第 30 题参考答案为 ABC，此处单选取其中一正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1011",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "受精的意义在于（原题为多选，此处单选其中一正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "决定性别",
      "恢复二倍体",
      "启动细胞分裂",
      "子代获得双亲的遗传物质",
      "子代具有与亲代不完全相同的性状",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "恢复二倍体",
        "受精的意义：①恢复了46条染色体（二倍体），具有双亲的遗传物质；②决定新个体的遗传性别；③启动胚胎发育与细胞分裂。原书多选题第 31 题参考答案为 ABCDE，此处单选取其中一正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1012",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于桑葚胚的描述（原题为多选，此处单选其中一正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "由受精卵不断分裂后形成",
      "在受精后第3天形成",
      "是一个中空的细胞团",
      "体积比受精卵大得多",
      "在输卵管内形成",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "在受精后第3天形成",
        "受精后第3天形成由12～16个卵裂球组成的实心球，形似桑葚，称桑葚胚，由受精卵分裂而来。原书多选题第 32 题参考答案为 ACE，此处单选取其中一正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1013",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于绒毛膜的描述（原题为多选，此处单选其中一正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "与包蜕膜相连接的是丛密绒毛膜",
      "与基蜕膜相连接的是平滑绒毛膜",
      "平滑绒毛膜的绒毛逐渐退化消失",
      "丛密绒毛膜内的血管与脐带的血管相通连",
      "绒毛膜内的血均为胎儿血液",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "丛密绒毛膜内的血管与脐带的血管相通连",
        "胚胎早期整个绒毛膜表面绒毛均匀分布，后来形成表面无绒毛的平滑绒毛膜和基蜕膜侧绒毛茂密的丛密绒毛膜；丛密绒毛膜内的血管与脐带血管相通连。原书多选题第 36 题参考答案为 CDE，此处单选取其中一正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1014",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "脐带内含有（原题为多选，此处单选其中一正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "体蒂分化而成的黏液性结缔组织",
      "贮存营养物质的卵黄囊",
      "两条脐动脉",
      "贮存代谢废物的尿囊",
      "一条脐静脉",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "两条脐动脉",
        "脐带内含黏液性结缔组织，除闭锁的卵黄囊和脐尿管外，有两条脐动脉和一条脐静脉。原书多选题第 40 题参考答案为 ABC，此处单选取其中一正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-a1015",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胎盘膜最薄处仅隔有（原题为多选，此处单选其中一正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["毛细血管内皮", "薄层合体滋养层", "基膜", "细胞滋养层", "薄层结缔组织"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "毛细血管内皮",
        "胎儿血与母体血在胎盘内进行物质交换所通过的结构称胎盘膜或胎盘屏障，其最薄处仅隔有毛细血管内皮、薄层合体滋养层和基膜。原书多选题第 41 题参考答案为 ABC，此处单选取其中一正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），本章无，置空 */
const fillItems: readonly AssessmentItemDefinition[] = [];

/** 简答/论述题（short-answer），7 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch21-general-embryology-short001",
    order: 22,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：二胚层胚盘是如何变成三胚层胚盘的？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "二胚层胚盘形成三胚层胚盘的过程",
        "答：第3周初，二胚层胚盘的部分上胚层细胞增殖较快，在上胚层正中线的一侧形成一条增厚区，称原条。原条的头端略膨大，为原结。继而在原条的中线出现浅沟，原结的中心出现浅凹，分别称原沟和原凹。原沟深部的细胞不断增殖，并在上、下胚层之间向周边扩展迁移。一部分细胞在上、下两胚层之间形成一个夹层，称胚内中胚层，即中胚层；另一部分细胞进入下胚层，并逐渐全部置换了下胚层的细胞，形成一层新的细胞，称内胚层。在内胚层和中胚层出现之后，原上胚层改称外胚层。于是，在第3周末，三胚层胚盘形成。原书简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-short002",
    order: 23,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：细胞滋养层在绒毛膜形成过程中起了什么作用？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞滋养层在绒毛膜形成中的作用",
        "答：绒毛膜是由绒毛膜板、各级绒毛干及绒毛组成的。植入完成后，滋养层已分化为细胞滋养层和合体滋养层两层。细胞滋养层先是局部增殖，伸入合体滋养层内，形成许多绒毛状的突起。这样，外表的合体滋养层和内部的细胞滋养层构成了初级绒毛干。后来进一步发育为次级绒毛干，乃至三级绒毛干。各级绒毛干的表面都发出分支，形成许多细小的绒毛。各级绒毛干和绒毛的表面是合体滋养层，细胞滋养层位于合体滋养层的深面。同时，绒毛干末端的细胞滋养层细胞增殖，穿出合体滋养层，伸抵子宫蜕膜组织，将绒毛干固着于蜕膜上。这些穿出的细胞滋养层细胞还沿蜕膜扩展、彼此连接，在蜕膜表面形成一层细胞滋养层壳，使绒毛膜与子宫蜕膜牢固连接。原书简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-short003",
    order: 24,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：胚外中胚层起源于哪里，后来发生了什么变化？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胚外中胚层的起源与变化",
        "答：胚泡植入、二胚层胚盘形成之后，胚泡腔内出现松散分布的星状细胞和细胞外基质，充填于细胞滋养层和卵黄囊、羊膜囊之间，形成胚外中胚层。继而胚外中胚层细胞间出现腔隙，腔隙逐渐汇合增大，在胚外中胚层内形成一个大腔，称胚外体腔。此时的胚外中胚层则分别附着于滋养层内面及卵黄囊和羊膜囊的外面。随着胚外体腔的扩大，二胚层胚盘和其背腹两侧的羊膜囊、卵黄囊仅由少部分胚外中胚层与滋养层直接相连，这部分胚外中胚层称体蒂。体蒂将发育为脐带的主要成分。原书简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-short004",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：脐带是如何形成的？有什么结构特点？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脐带的形成与结构特点",
        "答：脐带是连于胚胎脐部与胎盘间的索状结构。脐带由体蒂发育而来，由于羊膜腔的扩大而外包羊膜。脐带内含黏液性结缔组织，其内除有闭锁的卵黄囊和脐尿管外，还有连接胚胎血管和胎盘绒毛血管的脐动脉和脐静脉。脐动脉有两条，呈螺旋状走行，将胚胎血液运送至胎盘绒毛血管，与绒毛间隙内的母体血进行物质交换。脐静脉仅有一条，将吸纳了丰富营养物质和氧的血液送回胚胎。胎儿出生时，脐带长40～60cm。脐带过短，胎儿娩出时易引起胎盘过早剥离，造成出血过多；脐带过长，易缠绕胎儿四肢或颈部，可致局部发育不良。原书简答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-short005",
    order: 26,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：胎盘的两套血液是如何循环和物质交换的？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胎盘两套血液循环与物质交换",
        "答：胎盘内有母体和胎儿两套血液循环，胎儿和母体的血液在各自的封闭管道内循环，互不相通。母体的动脉血从子宫螺旋动脉的开口流入绒毛间隙，在此与绒毛内毛细血管的胎儿血进行物质交换后，经子宫静脉回流人母体。胎儿的静脉血经过脐动脉的分支流入绒毛内毛细血管，与绒毛间隙内的母体血进行物质交换后，成为动脉血经脐静脉回流到胎儿体内。在绒毛间隙内，两套血液经过胎盘屏障进行物质交换，胎儿从母血中获得营养和氧气，排出代谢产物和二氧化碳。原书简答题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-short006",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "论述题：试述受精的过程和意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "受精的过程和意义",
        "答：获能的精子接触到卵子周围的放射冠时，即释放顶体酶，解离放射冠的卵泡细胞；进而接触到透明带，精子与精子受体ZP3结合，继续释放顶体酶，在透明带中溶蚀出一条孔道，精子头部便接触到卵子。精子的细胞核及细胞质进入卵子内，精子与卵子的细胞膜融合为一体。精卵结合后，透明带结构发生变化，特别是使ZP3分子变性，不能再与精子结合，从而阻止了其他精子穿越透明带。与此同时，卵子迅速完成第二次减数分裂，精子和卵子的细胞核膨大，进而融合，形成二倍体的受精卵，受精过程到此完成。受精的意义在于：①精子与卵子的结合，恢复了细胞的二倍体核型，受精卵含有来自双亲的遗传物质，新个体维持了双亲的遗传特点；②受精决定新个体的遗传性别；③受精卵开始进行细胞分裂，启动了胚胎发育的进程。原书论述题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-short007",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "论述题：试述胎盘的组织结构。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胎盘的组织结构",
        "答：胎盘是由胎儿的丛密绒毛膜与母体的基蜕膜共同组成的圆盘形结构。胎盘的胎儿面光滑，覆有羊膜，脐带附于中央，透过羊膜可见呈放射状走行的来自脐带的血管分支。胎盘的母体面粗糙，为剥脱后的基蜕膜，可见15～30个由浅沟分隔的胎盘小叶。在胎盘的垂直切面上，可见胎儿面的羊膜下方为绒毛膜的结缔组织，脐血管的分支走行其中。绒毛膜板发出几十根绒毛干，绒毛干又发出许多细小绒毛，绒毛干的末端以细胞滋养层壳固着于母体的基蜕膜。脐血管的分支沿绒毛干进入绒毛内，形成毛细血管，内含胎儿血。绒毛干之间为绒毛间隙，有基蜕膜构成的短隔伸入其内，称胎盘隔。胎盘隔将胎盘分隔为15～30个胎盘小叶，每个小叶含1～4根绒毛干及其分支。子宫螺旋动脉与子宫静脉的分支开口于绒毛间隙，故绒毛间隙内充满母体血液，绒毛浸泡其中，绒毛毛细血管里的胎儿血与绒毛间隙里的母体血相分隔。原书论述题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，2 组 × 共 8 成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-histology-embryology-ch21-general-embryology-b001",
    order: 29,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["下胚层", "原条", "胚外中胚层", "体蒂", "脊索"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch21-general-embryology-b001m1",
        order: 29,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "诱导神经板的发生",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "脊索",
            "脊索向头端增生迁移，诱导其背侧的外胚层细胞增厚形成神经板。原书 B1 第 22 题答案 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch21-general-embryology-b001m2",
        order: 30,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "细胞增殖迁移，形成胚内中胚层",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "原条",
            "原沟深部的细胞增殖并在上、下胚层之间向周边扩展迁移，一部分形成胚内中胚层（中胚层）。原书 B1 第 23 题答案 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch21-general-embryology-b001m3",
        order: 31,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "周缘细胞增殖并向胚泡腔迁移，形成卵黄囊",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "下胚层",
            "下胚层周缘的细胞向腹侧生长、延伸，形成由单层扁平上皮细胞围成的卵黄囊，下胚层构成卵黄囊的顶。原书 B1 第 24 题答案 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch21-general-embryology-b001m4",
        order: 32,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "细胞增殖迁移并取代下胚层",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "原条",
            "原沟深部的一部分细胞进入下胚层，并逐渐全部置换下胚层的细胞，形成一层新的细胞，称内胚层。原书 B1 第 25 题答案 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch21-general-embryology-b002",
    order: 33,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["内胚层", "外胚层", "基蜕膜", "胚外中胚层", "体蒂"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch21-general-embryology-b002m1",
        order: 33,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "参与绒毛膜的发育",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "胚外中胚层",
            "滋养层和衬于其内面的胚外中胚层组成绒毛膜板，胚外中胚层参与绒毛膜的发育。原书 B1 第 26 题答案 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch21-general-embryology-b002m2",
        order: 34,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "内含尿囊",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "体蒂",
            "尿囊是从原始消化管尾段腹侧向体蒂内伸出的一个盲管，故体蒂内含尿囊。原书 B1 第 27 题答案 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch21-general-embryology-b002m3",
        order: 35,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "参与组成胎盘",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "基蜕膜",
            "胎盘由胎儿的丛密绒毛膜与母体的基蜕膜共同组成，基蜕膜参与组成胎盘。原书 B1 第 28 题答案 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch21-general-embryology-b002m4",
        order: 36,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "可分化为甲状腺滤泡上皮",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "内胚层",
            "内胚层被包入胚体形成原始消化管，将分化为甲状腺等器官的上皮组织（甲状腺滤泡上皮）。原书 B1 第 29 题答案 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...fillItems,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];