import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 组织学与胚胎学学习指导与习题集（第4版）— 第5章 血液 题库提取（等比取样）
 * 来源：《组织学与胚胎学学习指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：4 题
 * - 选择题（a1-single）：16 题（A1 型 9 题 + X 型多选映射 7 题）
 * - 填空题（fill）：0 题
 * - 简答/问/论述题（short-answer）：3 题
 * - B1 配伍题：2 组、共 6 个成员
 * - 独立记分题合计：29 题（须等于本文件预算 29）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含 A1 型选择 16、B1 型 2 组共 6 小题、X 型多选 9、名词解释 6、
 *   简答题 4、论述题 2；本文件按 29 道预算等比取材并在原书顺序内取满。X 型多选按项目
 *   规约映射为 a1-single（取其一正确项）。双栏错序已按医学语义恢复，数值（红细胞正常值、
 *   血小板寿命、白细胞百分比等）与结构均保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "histology-embryology-ch05-blood";
const locatorBase =
  "《组织学与胚胎学学习指导与习题集》第4版 第5章 血液 复习思考题 习题（核对PDF 第39–47页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多选，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），4 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch05-blood-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：网织红细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "网织红细胞",
        "是未完全成熟的红细胞，直径略大于成熟红细胞。新鲜血液用煌焦油蓝染色，网织红细胞内残存的少量核蛋白体被染成蓝色细网状，故称网织红细胞。正常成年人外周血中，网织红细胞约占红细胞总数的0.5%～1.5%，新生儿较多，可达3%～6%。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：血小板",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血小板",
        "是从骨髓巨核细胞脱落下来的胞质小块，呈双凸圆盘状。有完整的胞膜，无细胞核。在血涂片上，血小板形态不规则、常聚集成群，细胞中央部有紫色颗粒，称颗粒区；周边部呈均质状浅蓝色，称透明区。血小板在止血、凝血过程中起重要作用。正常值：正常成人血液中血小板的含量为（100～300）×10⁹/L。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：嗜酸性粒细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "嗜酸性粒细胞",
        "占白细胞总数的0.5%～3%。光镜结构特点：细胞呈圆形，直径10～15μm；胞核多为2叶；胞质内充满粗大的鲜红色的嗜酸性颗粒。功能：释放组胺酶、芳基硫酸酯酶，从而抑制过敏反应；释放阳离子蛋白，对寄生虫有很强的杀灭作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：单核细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单核细胞",
        "白细胞中体积最大的细胞，直径14～20μm，呈球形。胞核呈肾形、马蹄形或不规则形，核染色质呈细网状、着色较浅。胞质丰富、呈灰蓝色，胞质内有许多细小的淡紫色嗜天青颗粒。电镜下，细胞表面有皱褶和微绒毛，胞质内含许多膜被颗粒和吞噬泡，颗粒具溶酶体样结构特点。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1 型选择题（a1-single），9 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch05-blood-a1001",
    order: 5,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下对于成熟红细胞特点的描述中，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "无细胞核",
      "呈双凹圆盘状",
      "细胞内尚残留部分核糖体",
      "胞质内充满血红蛋白",
      "无任何细胞器",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞内尚残留部分核糖体",
        "成熟红细胞无核、无细胞器，胞质内充满血红蛋白，不再残留核糖体；残留核糖体是网织红细胞的特点（煌焦油蓝染色呈细网状）。原书 A1 答案第 1 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1002",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "正常成人男性血液中红细胞的正常值是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "（3.5～4.5）×10¹²/L",
      "（4.0～5.5）×10¹²/L",
      "（4.5～5.5）×10⁹/L",
      "（3.5～5.5）×10⁹/L",
      "（4.0～5.0）×10⁹/L",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "（4.0～5.5）×10¹²/L",
        "正常成人男性红细胞正常值为（4.0～5.5）×10¹²/L，女性为（3.5～5.0）×10¹²/L；单位应为 10¹²/L 而非 10⁹/L。原书 A1 答案第 2 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1003",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下对于中性粒细胞的描述中，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "在白细胞中数量最多，占白细胞总数的50%～70%",
      "细胞呈球形，胞核呈杆状或分叶状",
      "胞质中只含有嗜天青颗粒",
      "具有很强的趋化作用和吞噬功能",
      "在杀死细菌后，自身也死亡，成为脓细胞",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胞质中只含有嗜天青颗粒",
        "中性粒细胞胞质中含嗜天青颗粒（溶酶体）和特殊颗粒两种颗粒，并非只含嗜天青颗粒。其数量最多（约占50%～70%），核呈杆状或分叶状，有强趋化和吞噬功能。原书 A1 答案第 3 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1004",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在患过敏性疾病或寄生虫病时，血液中白细胞数量明显增多的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["中性粒细胞", "单核细胞", "嗜酸性粒细胞", "淋巴细胞", "嗜碱性粒细胞"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "嗜酸性粒细胞",
        "嗜酸性粒细胞参与抗过敏和抗寄生虫，在过敏性疾病或寄生虫病时血液中其数量明显增多；其颗粒含阳离子蛋白对寄生虫有很强杀灭作用。原书 A1 答案第 4 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1005",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下对血小板的描述中，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "呈双凹圆盘状",
      "血小板中央部为透明区，周边部为颗粒区",
      "胞质内无颗粒",
      "受机械或化学刺激时，可伸出突起，呈不规则形",
      "直径与小淋巴细胞相近",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "受机械或化学刺激时，可伸出突起，呈不规则形",
        "血小板呈双凸圆盘状而非双凹圆盘状，无核但有细胞器和颗粒；受刺激时伸出突起呈不规则形。原书 A1 答案第 7 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1006",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "人胚胎时期最早形成造血干细胞的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["脾", "胸腺", "肝", "卵黄囊", "骨髓"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "卵黄囊",
        "最早造血的部位是胚胎时期卵黄囊壁，血岛在此形成并分化为造血干细胞（卵黄囊造血期）；其后依次为肝、脾、淋巴结，胚胎后期转骨髓造血。原书 A1 答案第 8 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1007",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列有关造血干细胞的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "有自我复制的能力",
      "有分化的能力",
      "有增殖的能力",
      "只分布于红骨髓中",
      "又称多能干细胞",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "只分布于红骨髓中",
        "造血干细胞起源于人胚卵黄囊血岛，出生后主要存在于红骨髓，并非只分布于红骨髓；其特性是强增殖潜力、多向分化和自我复制能力，又称多能干细胞。原书 A1 答案第 10 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1008",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "血小板的寿命是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["2～3天", "10～15天", "7～14天", "120天", "8～10天"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "7～14天",
        "血小板的寿命为7～14天；红细胞寿命约120天。原书 A1 答案第 12 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1009",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞的胞质脱落形成血小板的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["单核细胞", "巨噬细胞", "淋巴细胞", "树突状细胞", "巨核细胞"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "巨核细胞",
        "血小板是从骨髓巨核细胞脱落下来的胞质小块。原书 A1 答案第 14 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** X 型多选映射（a1-single），7 道，对应偶题排序在 a1001 之后 */
const a1XItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch05-blood-a1010",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关红细胞的描述，正确的是（按单选作答，取其正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "不能合成新的蛋白质",
      "呈双凹圆盘状",
      "能合成新的蛋白质",
      "无核，无细胞器",
      "具有形态的可变性",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "呈双凹圆盘状",
        "成熟红细胞呈双凹圆盘状、无核无细胞器、不能合成新的蛋白质且具有形态的可变性；原题为多选，正确答案为 ABCD（另三项亦正确），此为映射代表项。原书 X 型第 23 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1011",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关中性粒细胞的描述，正确的是（按单选作答，取其正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "抑制过敏反应",
      "可转化为巨噬细胞",
      "核呈杆状或分叶状",
      "有很强的趋化作用",
      "胞质中有嗜天青颗粒和特殊颗粒",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "核呈杆状或分叶状",
        "中性粒细胞核呈杆状或分叶状，胞质含嗜天青颗粒和特殊颗粒，有强趋化作用；原题为多选，正确答案为 ABE（嗜天青/特殊颗粒与趋化作用亦正确），此为映射代表项。原书 X 型第 24 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1012",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有嗜天青颗粒的细胞是（按单选作答，取其正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["单核细胞", "中性粒细胞", "嗜碱性粒细胞", "淋巴细胞", "嗜酸性粒细胞"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中性粒细胞",
        "中性粒细胞胞质含嗜天青颗粒（溶酶体）；原题为多选，正确答案为 ABC（中性粒细胞、淋巴细胞、单核细胞），此为映射代表项。原书 X 型第 26 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1013",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关血小板的描述，正确的是（按单选作答，取其正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "无核，有细胞器",
      "无核，无细胞器",
      "有血小板颗粒",
      "呈双凹圆盘状",
      "呈双凸圆盘状",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "呈双凸圆盘状",
        "血小板呈双凸圆盘状、无核但有细胞器并有血小板颗粒；原题为多选，正确答案为 BDE（另两项亦正确），此为映射代表项。原书 X 型第 27 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1014",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "造血干细胞的特征是（按单选作答，取其正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "有自我复制能力",
      "有多向分化能力",
      "有很强的增殖能力",
      "是生成各种血细胞的原始细胞",
      "终身数量恒定",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "有很强的增殖能力",
        "造血干细胞的特性包括强增殖潜力、多向分化、自我复制，终身保持恒定数量并生成各类血细胞；原题为多选，正确答案为 ABCDE（全部正确），此为映射代表项。原书 X 型第 28 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1015",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "造血诱导微环境的基质细胞包括（按单选作答，取其正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["巨核细胞", "内皮细胞", "网状细胞", "成纤维细胞", "巨噬细胞"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "网状细胞",
        "造血微环境中的基质细胞包括网状细胞、巨噬细胞、成纤维细胞、骨髓基质干细胞、血窦内皮细胞等，它们起支持作用并分泌造血生长因子；原题为多选，正确答案为 ACDE，此为映射代表项。原书 X 型第 29 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-a1016",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "单核细胞（按单选作答，取其正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "胞体由圆形演变为圆盘状",
      "胞核由大到小，最后消失",
      "与中性粒细胞有共同的造血祖细胞",
      "在骨髓中的储存量不及粒细胞多",
      "经过原单核细胞和幼单核细胞阶段",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "与中性粒细胞有共同的造血祖细胞",
        "单核细胞与中性粒细胞同由粒细胞单核细胞系造血祖细胞分化而来，经原单核细胞、幼单核细胞阶段，且胞体并非演变为圆盘状；原题为多选，正确答案为 ACD，此为映射代表项。原书 X 型第 31 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），0 道（本章无填空题） */
const fillItems: readonly AssessmentItemDefinition[] = [
  /* 本章原书无「填空题」题型，故为空数组 */
];

/** 简答/论述题（short-answer），3 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch05-blood-short001",
    order: 21,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述红细胞的形态结构特点、功能及正常值。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "形态结构特点（双凹圆盘状、无核无细胞器、内含血红蛋白）+功能（结合运输 O₂ 和 CO₂）+正常值（男女性红细胞及血红蛋白值）",
        "①形态结构特点：扫描电镜下成熟红细胞呈双凹圆盘状小体，直径7～8.5μm，中央较薄、周缘较厚，此种外形有较大表面积利于气体迅速交换。成熟红细胞无细胞核及细胞器，胞质内充满大量血红蛋白。电镜下红细胞膜为典型单位膜，含 ABO 血型抗原，具有半透膜特性。②功能：血红蛋白具有结合与运输 O₂ 和 CO₂ 的功能，能供给全身组织和细胞所需 O₂，并带走组织产生的部分 CO₂。③正常值：红细胞含量女性（3.5～5.0）×10¹²/L、男性（4.0～5.5）×10¹²/L；每升血液中血红蛋白含量女性110～140g、男性120～150g。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-short002",
    order: 22,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述造血干细胞的特性。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "强增殖潜能 + 多向分化能力 + 自我复制能力",
        "造血干细胞的特性是：①有很强的增殖潜能，在一定条件下能反复分裂、大量增殖，但在一般生理状态下多数细胞处于 G₀ 期静止状态；②有多向分化能力，在一些因素作用下能分化形成不同的祖细胞；③有自我复制能力，即细胞分裂后的部分子代细胞仍具原特性，故造血干细胞可终身保持恒定的数量。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-short003",
    order: 23,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述血细胞的分类及计数的正常值。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "红细胞/白细胞（有粒+无粒）/血小板三大类的分类及各正常值",
        "血细胞的分类及正常值：红细胞：男性（4.0～5.5）×10¹²/L，女性（3.5～5.0）×10¹²/L；白细胞（4.0～10）×10⁹/L，其中 有粒白细胞：中性粒细胞 50%～70%、嗜酸性粒细胞 0.5%～3%、嗜碱性粒细胞 0～1%；无粒白细胞：淋巴细胞 20%～30%、单核细胞 3%～8%；血小板（100～300）×10⁹/L。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，2 组 × 3 成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-histology-embryology-ch05-blood-b001",
    order: 24,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["单核细胞", "嗜酸性粒细胞", "嗜碱性粒细胞", "中性粒细胞", "淋巴细胞"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch05-blood-b001m1",
        order: 24,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "参与到细胞免疫的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "淋巴细胞",
            "T 细胞（胸腺依赖淋巴细胞）直接参与细胞免疫。原书 B1 第 17 题答案 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch05-blood-b001m2",
        order: 25,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "与肥大细胞分泌的物质相同的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "嗜碱性粒细胞",
            "嗜碱性粒细胞与肥大细胞都能释放组胺、白三烯等，均参与过敏反应。原书 B1 第 18 题答案 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch05-blood-b001m3",
        order: 26,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "可以分化成巨噬细胞的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "单核细胞",
            "单核细胞进入结缔组织或其他组织后分化成巨噬细胞等吞噬细胞。原书 B1 第 19 题答案 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch05-blood-b002",
    order: 27,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["血小板", "网织红细胞", "红细胞", "嗜酸性粒细胞", "嗜碱性粒细胞"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch05-blood-b002m1",
        order: 27,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "可以杀灭寄生虫的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "嗜酸性粒细胞",
            "嗜酸性粒细胞释放阳离子蛋白，对寄生虫有很强的杀灭作用。原书 B1 第 20 题答案 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch05-blood-b002m2",
        order: 28,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "没有细胞器的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "红细胞",
            "成熟红细胞无细胞核和任何细胞器。原书 B1 第 21 题答案 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch05-blood-b002m3",
        order: 29,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "骨髓巨核细胞胞质脱落形成的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "血小板",
            "血小板是骨髓巨核细胞脱落下来的胞质小块。原书 B1 第 22 题答案 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

/* caseItems 为空数组（本章无病例题） */
const caseItems: readonly AssessmentItemDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...a1XItems,
  ...fillItems,
  ...shortItems,
  ...caseItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];