import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 组织学与胚胎学学习指导与习题集（第4版）— 第10章 免疫系统 题库提取（等比取样）
 * 来源：《组织学与胚胎学学习指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 每教材章节等比缩放预算）==
 * - 名词解释：5 题
 * - 选择题（a1-single)：12 题（含 A2/X 型映射）
 * - 填空题（fill）：0 题
 * - 简答/问/论述题（short-answer）：5 题
 * - B1 配伍题：3 组、共 10 个成员
 * - 独立记分题合计：32 题（须等于本文件预算 32）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含 A1 选择题、B1 共用备选答案配伍、多选题、名词解释、
 *   简答题与论述题。本文件按 32 道预算在原书顺序内取满。多选未取（预算已满且
 *   单选/B1 已覆盖本章要点）。B1 组第 21 题原文语义（双栏错序致肯定/否定缺失）按
 *   医学语义与源键号确认为「不属于单核吞噬细胞系统的是」= 网状细胞，第 23 题确认为
 *   「不含淋巴小结的是」= 胸腺，均与源参考答案键号对齐。双栏错序已恢复题干/选项/
 *   键号对应，数值与结构保留，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "histology-embryology-ch10-immune-system";
const locatorBase =
  "《组织学与胚胎学学习指导与习题集》第4版 第10章 免疫系统 复习思考题 习题（核对PDF 第83–92页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多选，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），5 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch10-immune-system-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：NK细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "NK细胞",
        "NK细胞是指来源于骨髓，不表达T细胞和B细胞的膜受体，无需抗原呈递细胞的中介即可活化的一类大颗粒淋巴细胞，约占血液淋巴细胞的15%，属于固有免疫细胞，其杀伤靶细胞没有MHC限制性，是机体抗肿瘤和抗感染免疫的第一道天然防线。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：单核吞噬细胞系统",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单核吞噬细胞系统",
        "指由血液单核细胞和由其分化而来的具有吞噬功能的细胞，包括结缔组织和淋巴组织的巨噬细胞、骨组织的破骨细胞、神经组织的小胶质细胞、肝巨噬细胞（库普弗细胞）和肺巨噬细胞（尘细胞）等，它们均具有强大的吞噬能力，还是主要的抗原呈递细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：抗原呈递细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗原呈递细胞（APC）",
        "能捕获和处理抗原，形成抗原肽-MHC分子复合物，并将抗原呈递给T细胞，激发后者活化、增殖的一类免疫细胞。最主要的APC是树突状细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：淋巴小结",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "淋巴小结",
        "又称淋巴滤泡，是圆形或椭圆形的淋巴组织，主要由B细胞聚集而成。受抗原刺激后，小结增大，中央出现浅染的生发中心，内有许多呈分裂象的B细胞，还有巨噬细胞、滤泡树突状细胞和Th细胞等。有生发中心的称次级淋巴小结，没有生发中心的称初级淋巴小结。次级淋巴小结中产生出针对该抗原的浆细胞和记忆性B细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：血-胸腺屏障",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血-胸腺屏障",
        "胸腺皮质的毛细血管及其周围结构具有屏障作用，称血-胸腺屏障，由下列数层构成：①连续型毛细血管，其内皮细胞间有完整的紧密连接；②内皮周围连续的基膜；③血管周隙，内含巨噬细胞；④上皮基膜；⑤一层连续的胸腺上皮细胞。血液内一般抗原物质和某些药物不易透过此屏障，对维持胸腺内环境的稳定、保证胸腺细胞的正常发育起着极其重要的作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1 型选择题（含 X 型多选映射为单选），12 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch10-immune-system-a1001",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列专司抗原呈递功能的细胞是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["中性粒细胞", "浆细胞", "朗格汉斯细胞", "网状细胞", "嗜酸性粒细胞"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "朗格汉斯细胞",
        "朗格汉斯细胞是表皮内的树突状细胞，为专职性抗原呈递细胞。原书第10章选择题第1题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-a1002",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "合成和分泌免疫球蛋白的细胞是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["肥大细胞", "嗜酸性粒细胞", "浆细胞", "巨噬细胞", "嗜碱性粒细胞"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "浆细胞",
        "浆细胞是效应B细胞，可合成分泌免疫球蛋白（抗体）。原书第10章选择题第3题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-a1003",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "被膜内含平滑肌纤维的淋巴器官是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["胸腺", "脾", "阑尾", "扁桃体", "淋巴结"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脾",
        "脾的被膜较厚，由富含弹性纤维、Ⅲ型胶原纤维及平滑肌纤维的不规则致密结缔组织构成。原书第10章选择题第6题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-a1004",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关脾的结构，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "被膜表面覆盖间皮",
      "实质由白髓和红髓构成",
      "含有大量血窦，无淋巴窦",
      "脾血窦由高内皮细胞组成",
      "脾血窦内皮细胞外有不完整的基膜",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "含有大量血窦，无淋巴窦",
        "脾含大量脾血窦，无淋巴窦；脾实质分白髓和红髓，血窦壁由长杆状内皮细胞围成，脾被膜表面覆盖间皮而非被膜为间皮。原书第10章选择题第7题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-a1005",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "组成脾白髓的结构有",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脾索和淋巴小结",
      "脾索和脾血窦",
      "血窦和边缘窦",
      "脾血窦和动脉周围淋巴鞘",
      "动脉周围淋巴鞘和淋巴小结",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动脉周围淋巴鞘和淋巴小结",
        "脾白髓由动脉周围淋巴鞘和淋巴小结构成。原书第10章选择题第8题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-a1006",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在淋巴结和脾，以T细胞为主的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "副皮质区和淋巴小结",
      "副皮质区和脾索",
      "副皮质区和动脉周围淋巴鞘",
      "淋巴小结和动脉周围淋巴鞘",
      "淋巴小结和边缘窦",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "副皮质区和动脉周围淋巴鞘",
        "淋巴结副皮质区（胸腺依赖区）和脾的动脉周围淋巴鞘均以T细胞为主。原书第10章选择题第11题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-a1007",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在体液免疫应答时，淋巴结内增多变大的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["初级淋巴小结", "次级淋巴小结", "副皮质区", "深层皮质", "髓质"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "次级淋巴小结",
        "体液免疫应答时，淋巴小结增大并出现生发中心，成为次级淋巴小结。原书第10章选择题第13题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-a1008",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "中枢淋巴器官特点之一是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "较周围淋巴器官发生晚",
      "以网状细胞和网状纤维为支架",
      "培育效应性T淋巴细胞或B淋巴细胞",
      "淋巴细胞增殖不受抗原直接影响",
      "是胎儿期免疫应答的主要场所",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "淋巴细胞增殖不受抗原直接影响",
        "中枢淋巴器官（胸腺、骨髓）一般不受外界抗原刺激的影响，淋巴细胞增殖不受抗原直接影响。原书第10章选择题第14题答案 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-a1009",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "淋巴结副皮质区",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "在被膜下，主要含T细胞",
      "在皮质浅部，主要含B细胞",
      "在皮质深部，主要含T细胞",
      "在髓质浅部，主要含B细胞",
      "在髓质深部，主要含T细胞",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "在皮质深部，主要含T细胞",
        "副皮质区位于皮质深层，为较大片的弥散淋巴组织，主要含Th细胞，又称胸腺依赖区。原书第10章选择题第16题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-a1010",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于胸腺，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "上皮细胞有分泌功能",
      "淋巴性造血干细胞在胸腺内增殖分化为T细胞",
      "皮质和髓质内均有巨噬细胞",
      "皮质内胸腺细胞多未成熟",
      "抗原刺激促使胸腺细胞成熟",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗原刺激促使胸腺细胞成熟",
        "胸腺作为中枢淋巴器官，胸腺细胞分化发育不依赖也不需要抗原刺激；其在胸腺内经阳性与阴性选择而成熟。原书第10章选择题第17题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-a1011",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胸腺的特点不包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "能产生胸腺激素",
      "退化的胸腺细胞聚集成团，形成胸腺小体",
      "皮质内有连续毛细血管",
      "生成的T细胞进入血流",
      "约有95%胸腺细胞被灭活或淘汰",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "退化的胸腺细胞聚集成团，形成胸腺小体",
        "胸腺小体由胸腺上皮细胞呈同心圆状排列而成（而非胸腺细胞聚集成团），故该项不是胸腺的特点。原书第10章选择题第19题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-a1012",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不属于胸腺上皮细胞功能的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["形成网状纤维", "参与形成胸腺小体", "分泌激素", "辅助培育T细胞", "构成支架"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "形成网状纤维",
        "网状纤维由网状细胞（成纤维细胞亚型）产生；胸腺上皮细胞则参与形成胸腺小体、分泌胸腺激素、构成支架并辅助培育T细胞。原书第10章选择题第20题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），本章无填空题 */
const fillItems: readonly AssessmentItemDefinition[] = [];

/** 简答/论述题（short-answer），5 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch10-immune-system-short001",
    order: 18,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述淋巴细胞再循环的途径和意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "淋巴细胞再循环的途径和意义",
        "淋巴细胞再循环是指外周淋巴器官和淋巴组织内的淋巴细胞可经淋巴管进入血流，循环于全身，又可通过弥散淋巴组织内的毛细血管后微静脉，再返回淋巴器官或淋巴组织，如此周而复始，使淋巴细胞从一个淋巴器官或一处淋巴组织进入另一个淋巴器官或另一处淋巴组织。其意义：使体内淋巴细胞的区域分布更趋合理，局部的淋巴细胞能得到不断补充，使分散于全身的免疫细胞成为一个相互关联的统一体，也增加了其与抗原接触和活化的机会，有利于识别抗原，产生更有效的免疫应答。原书第10章简答题第1题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-short002",
    order: 19,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述中枢淋巴器官和周围淋巴器官的区别。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中枢淋巴器官和周围淋巴器官的区别",
        "(1)组成不同：中枢淋巴器官包括胸腺和骨髓，外周淋巴器官包括淋巴结、脾、扁桃体等。(2)发育时间不同：中枢淋巴器官发育早，外周淋巴器官发育晚，出生数月后才逐渐发育完善。(3)功能不同：中枢淋巴器官是产生初始T细胞和初始B细胞的场所，外周淋巴器官是机体进行免疫应答、T细胞和B细胞进行免疫反应的场所。(4)受抗原刺激影响不同：中枢淋巴器官一般不受外界抗原刺激的影响，外周淋巴器官则受外界抗原刺激的影响，无抗原刺激时较小，受抗原刺激后迅速增大，形态和结构成分发生剧烈变化，免疫应答过后又逐渐复原。原书第10章简答题第2题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-short003",
    order: 20,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述免疫系统的组成和功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "免疫系统的组成和功能",
        "免疫系统由淋巴器官、淋巴组织、免疫细胞和免疫活性分子构成。淋巴器官包括中枢淋巴器官（胸腺和骨髓）和外周淋巴器官（淋巴结、脾和扁桃体等）。淋巴组织是外周淋巴器官的主要成分，广泛分布于消化管和呼吸道等处。免疫细胞包括淋巴细胞、抗原呈递细胞、粒细胞和肥大细胞等，它们或聚集于淋巴组织中，或散在于血液、淋巴及其他组织内。免疫活性分子包括免疫球蛋白、补体、细胞因子等。它们通过血液循环和淋巴循环相互联系和流通，使免疫系统形成一个统一的整体。免疫系统有三大功能：①免疫防御——识别和清除外源的病原微生物（细菌、病毒、真菌和寄生虫等）；②免疫监视——识别和清除体内突变的肿瘤细胞和病毒感染细胞；③免疫自稳——识别和清除体内衰老、坏死、凋亡的细胞和免疫复合物，维持内环境的稳定。原书第10章简答题第3题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-short004",
    order: 21,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述T细胞在胸腺内分化发育过程。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "T细胞在胸腺内的分化发育过程",
        "胸腺是形成初始T细胞的场所。由骨髓来的淋巴性造血干细胞进入胸腺，从皮质到髓质，T细胞逐渐成熟。在由皮质向髓质的迁移发育过程中，在周围胸腺基质细胞参与下，经历了两次选择，即阳性选择和阴性选择：阳性选择发生在皮质外层，赋予T细胞具有MHC分子限制性识别能力；阴性选择发生在皮质深层和髓质，淘汰了能与机体自身抗原发生反应的T细胞。最终只有不足5%左右的胸腺细胞发育成熟，成为初始T细胞，具有正常的免疫应答潜能；绝大部分胸腺细胞发生凋亡，被巨噬细胞吞噬清除。人类终生保留产生T细胞的能力。原书第10章简答题第4题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-short005",
    order: 22,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "比较淋巴结和脾的结构和功能的异同。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "淋巴结和脾的结构和功能的异同",
        "(1)结构上相似：均为外周淋巴器官，均有被膜、结缔组织小梁，均以网状组织为支架，有大量淋巴组织，淋巴小结和胸腺依赖区（脾为动脉周围淋巴鞘）丰富，均有条索状弥散淋巴组织（淋巴结髓索、脾索）。(2)结构上不同：淋巴结被膜由薄层致密结缔组织构成；脾被膜较厚，由富含弹性纤维、Ⅲ型胶原纤维及平滑肌纤维的不规则致密结缔组织构成，表面覆有间皮。淋巴结实质分为皮质和髓质，皮质由浅层皮质、副皮质区及皮质淋巴窦构成，髓质由髓索和髓窦组成；脾实质包括白髓和红髓，白髓由动脉周围淋巴鞘和淋巴小结构成，相当于淋巴结的皮质，红髓由脾索和脾血窦组成。(3)功能上相同：均为机体免疫应答的场所。(4)功能上不同：淋巴结主要针对通过淋巴管道转运的抗原发挥作用，除免疫应答外还有滤过淋巴功能；脾脏除免疫应答外还有滤血和造血功能。原书第10章论述题第1题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，3 组、共 10 个成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-histology-embryology-ch10-immune-system-b001",
    order: 23,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["尘细胞", "小胶质细胞", "破骨细胞", "网状细胞", "库普弗细胞"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch10-immune-system-b001m1",
        order: 23,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "不属于单核吞噬细胞系统的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "网状细胞",
            "单核吞噬细胞系统包括尘细胞、小胶质细胞、破骨细胞、库普弗细胞及巨噬细胞等；网状细胞不属于该系统。原书第10章选择题第21题答案 D（原文为「f属于单核吞噬细胞系统的是」，双栏错序致肯定/否定缺失，按医学语义与键号确认为否定句）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch10-immune-system-b001m2",
        order: 24,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "属于消化系统的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "库普弗细胞",
            "库普弗细胞（肝巨噬细胞）位于肝脏，属于消化系统。原书第10章选择题第22题答案 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-b002",
    order: 25,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["胸腺", "淋巴结", "脾", "扁桃体", "回肠"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch10-immune-system-b002m1",
        order: 25,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "器官结构中不含淋巴小结的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "胸腺",
            "胸腺实质分皮质、髓质，无淋巴小结；淋巴结、脾、扁桃体和回肠（集合淋巴小结）均含淋巴小结。原书第10章选择题第23题答案 A（原文为「含淋巴小结的是」，双栏错序致肯定/否定缺失，按医学语义与键号确认为否定句）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch10-immune-system-b002m2",
        order: 26,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "黏膜表面覆盖复层扁平上皮的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "扁桃体",
            "腭扁桃体黏膜表面覆盖复层扁平上皮。原书第10章选择题第24题答案 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch10-immune-system-b002m3",
        order: 27,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "被膜中含丰富的弹性纤维和平滑肌纤维的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "脾",
            "脾的被膜由富含弹性纤维、Ⅲ型胶原纤维及平滑肌纤维的不规则致密结缔组织构成。原书第10章选择题第25题答案 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch10-immune-system-b002m4",
        order: 28,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "结构中含典型的高内皮微静脉的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "淋巴结",
            "淋巴结副皮质区内有高内皮微静脉（HEV），是淋巴细胞再循环的重要部位。原书第10章选择题第26题答案 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch10-immune-system-b003",
    order: 29,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["扁平内皮细胞", "网状细胞", "长杆状内皮细胞", "胸腺上皮细胞", "柱状内皮细胞"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch10-immune-system-b003m1",
        order: 29,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "脾血窦内皮",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "长杆状内皮细胞",
            "脾血窦壁由一层纵向平行排列的长杆状内皮细胞围成，有不完整的基膜及环行网状纤维。原书第10章选择题第27题答案 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch10-immune-system-b003m2",
        order: 30,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "毛细血管后微静脉内皮",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "柱状内皮细胞",
            "高内皮微静脉（毛细血管后微静脉）的内皮细胞为柱状内皮细胞，是淋巴细胞进入淋巴组织的重要通道。原书第10章选择题第28题答案 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch10-immune-system-b003m3",
        order: 31,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "淋巴窦内皮",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "扁平内皮细胞",
            "淋巴窦窦壁由扁平的内皮细胞衬里，窦内有星状的内皮细胞支撑窦腔。原书第10章选择题第29题答案 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch10-immune-system-b003m4",
        order: 32,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "有些为哺育细胞",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "胸腺上皮细胞",
            "胸腺上皮细胞中有些为哺育细胞，参与胸腺细胞的分化发育。原书第10章选择题第30题答案 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...fillItems,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];