import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 组织学与胚胎学学习指导与习题集（第4版）— 第4章 软骨和骨 题库提取（等比取样）
 * 来源：《组织学与胚胎学学习指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：5 题
 * - 选择题（a1-single）：12 题（含 X 型映射）
 * - 填空题（fill）：0 题
 * - 简答/问/论述题（short-answer）：5 题
 * - B1 配伍题：3 组、共 8 个成员
 * - 独立记分题合计：30 题（等于本文件预算 30）
 * - 缺失答案：0；无法可靠提取：2（原书 A1 第 8、13 题正确项与源答案印刷编号
 *   （8.E、13.D）存在 OCR 编号错乱、题支对应关系无法唯一锚定，予以跳过并换用
 *   同源多选映射题补足预算）
 * - 说明：本章原书依序含 A1 型选择题（第 1~18 题）、B1 型配伍题（19~21、22~24、
 *   25~26 三组）、多选题（27~35）、名词解释 8 个、简答题 5 个、论述题 2 个，无线其余
 *   类型。按 30 道预算等比取材：名词解释取 5 个清晰项，A1 取 11 个答案锚定清晰的
 *   单选项 + 1 个 X 型映射（第 28 题透明软骨胶原原纤维难分辨），简答题 5 个全取
 *   （含论述不取，保证「答:」内联完整），B1 三组共 8 个成员全部取满。双栏错序已
 *   按组织学/胚胎学语义恢复（「鞄/靱/莠」→板/骺/编织等），数值（骨盐占干骨重量
 *   65%、羟基磷灰石结晶长 10~20 nm、透明质酸 2.5 nm 等）与结构描述保留原义，
 *   未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "histology-embryology-ch04-cartilage-bone";
const locatorBase =
  "《组织学与胚胎学学习指导与习题集》第4版 第4章 软骨和骨 复习思考题 习题（核对PDF 第29–38页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多选，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），5 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：软骨囊",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "软骨囊",
        "位于软骨陷窝周围的软骨基质，因含较多的硫酸软骨素而呈明显的嗜碱性。从软骨周边到中部，随着软骨细胞成熟和分泌能力增强，软骨囊也越来越明显。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：同源细胞群",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "同源细胞群",
        "位于软骨中部的软骨细胞成群分布，每一群由 2~8 个软骨细胞聚集在一起，这群细胞皆由同一个幼稚的软骨细胞发育并分裂增生形成，故称同源细胞群。越靠近软骨中部，同源细胞群的细胞数量越多，是软骨间质性生长的表现。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：骨板",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骨板",
        "板层状的骨质结构，其纤维成分为大量平行排列的胶原纤维。骨板以成层叠加的方式聚集，同一层骨板内的纤维相互平行，而相邻骨板的纤维相互垂直，这种排列方式如同多层木质胶合板，可有效地增加骨的强度。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：骨领",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骨领",
        "骨领是长骨发生中出现的结构。在软骨雏形的中段，软骨膜内层的骨祖细胞增殖分化为成骨细胞，成骨细胞在软骨中段表面产生类骨质，继而钙化为骨基质，于是在软骨中段形成一圈「领圈样」的薄层骨组织，称骨领。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：骺板",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骺板",
        "在长骨发生过程中，随着骨干和骨骺的形成，干、骺之间留存的一定厚度的板状软骨，称骺板（生长板）。骺板软骨的不断生长及被骨的替换是长骨加长的结构基础，骺板停止生长并完全被骨替换后，长骨便不再加长。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1 型及 X 型映射选择题（统一映射为 a1-single），12 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-a1001",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "软骨囊是指",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "软骨细胞所在的小腔",
      "软骨细胞的细胞膜",
      "软骨细胞周围的软骨基质",
      "软骨周围的结缔组织",
      "软骨内纤维交织形成的结构",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "软骨细胞周围的软骨基质",
        "软骨囊是位于软骨陷窝周围的软骨基质，因含较多硫酸软骨素而呈明显嗜碱性。原书 A1 答案第 1 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-a1002",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "软骨细胞和成骨细胞超微结构的共同点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "溶酶体和线粒体多",
      "高尔基复合体和滑面内质网多",
      "线粒体和粗面内质网多",
      "粗面内质网和高尔基复合体多",
      "滑面内质网和溶酶体多",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "粗面内质网和高尔基复合体多",
        "软骨细胞和成骨细胞均以合成大量细胞外基质（蛋白等）为主，超微结构上粗面内质网和高尔基复合体发达。原书 A1 答案第 2 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-a1003",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于同源细胞群，描述正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "单核细胞聚集形成",
      "是成骨细胞的前体",
      "属于一种多核细胞",
      "来源于同一个软骨细胞",
      "是破骨细胞的前体",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "来源于同一个软骨细胞",
        "同源细胞群由同一个幼稚的软骨细胞发育并分裂增生而来，每群含 2~8 个软骨细胞。原书 A1 答案第 3 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-a1004",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在透明软骨的软骨组织中不存在的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胶原蛋白",
      "硫酸角质素",
      "透明质酸",
      "毛细血管",
      "硫酸软骨素",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "毛细血管",
        "软骨组织内无血管，软骨细胞依靠基质渗透获得营养。原书 A1 答案第 5 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-a1005",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "软骨细胞的营养依靠",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "毛细血管直接开口于软骨陷窝",
      "基质中有少量的淋巴管",
      "有软骨内小管",
      "基质中丰富的血管",
      "通过基质渗透",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "通过基质渗透",
        "软骨基质内无血管和淋巴管，软骨细胞的营养主要由软骨膜血管渗入基质后，通过基质渗透获得。原书 A1 答案第 6 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-a1006",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于软骨的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "羟基磷灰石结晶比骨组织少",
      "富含钙、磷两种无机盐",
      "透明软骨对长骨的生长作用甚微",
      "三种软骨均含纤维",
      "电镜下可见软骨细胞有许多细长突起",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "三种软骨均含纤维",
        "透明软骨、弹性软骨和纤维软骨的软骨基质中都含有纤维，仅纤维类型和含量不同。软骨不含羟基磷灰石结晶和钙盐沉积（属骨的特征）。原书 A1 答案第 7 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-a1007",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "相邻骨细胞突起之间有",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "紧密连接",
      "桥粒",
      "黏合带",
      "连接复合体",
      "缝隙连接",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "缝隙连接",
        "相邻骨细胞的突起以缝隙连接相连，骨小管彼此相通，骨陷窝和骨小管内含少量组织液。原书 A1 答案第 10 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-a1008",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "骨基质是指",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "未钙化的细胞外基质",
      "无定形基质",
      "骨盐",
      "骨细胞分泌的细胞外基质",
      "钙化的细胞外基质",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "钙化的细胞外基质",
        "细胞外基质在骨盐沉积后转变为坚硬的骨质，故骨基质指已钙化的细胞外基质；骨盐沉积前称类骨质。原书 A1 答案第 12 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-a1009",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "类骨质是指",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "黏合线处的骨质",
      "尚未形成骨板的骨质",
      "软骨雏形的基质",
      "新形成尚无骨盐沉积的骨质",
      "中央管周围的骨质",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "新形成尚无骨盐沉积的骨质",
        "新形成、尚无骨盐沉积的细胞外基质称类骨质，骨盐沉积后才转变为坚硬的骨质。原书 A1 答案第 15 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-a1010",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可出现皱褶缘和胞质围墙的细胞是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "软骨细胞",
      "成骨细胞",
      "骨祖细胞",
      "骨细胞",
      "破骨细胞",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "破骨细胞",
        "破骨细胞溶骨活跃时，贴骨组织一侧出现许多突起构成皱褶缘，环绕皱褶缘的胞质略微隆起似一圈胞质围墙（亮区/封闭区）。原书 A1 答案第 16 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-a1011",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于骨组织的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "松质骨内没有骨板",
      "黏合线是骨组织内的微血管通道",
      "穿通管与中央管各自独立",
      "密质骨内没有骨小梁",
      "编织骨内无骨盐沉积",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "密质骨内没有骨小梁",
        "松质骨由大量针片状骨小梁构成；密质骨由紧密排列的骨板形成，不含骨小梁。穿通管分支连接骨单位的中央管，两者相通；编织骨同样有骨盐沉积。原书 A1 答案第 17 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-a1012",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "光镜下透明软骨中胶原原纤维难以分辨的主要原因是（原题为多选题，取其一个正确原因）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "纤维极细",
      "数量少",
      "染色与基质近似",
      "交织分布",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "纤维极细",
        "透明软骨中的胶原原纤维极细，且折光率与基质近似，故光镜下难以分辨。原书多选题第 28 题答案 BC（纤维极细、折光率与基质近似），本项目取纤维极细为映射正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill）— 本章原书无此类题，空数组 */
const fillItems: readonly AssessmentItemDefinition[] = [];

/** 简答题（short-answer），5 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-short001",
    order: 18,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述透明软骨、弹性软骨和纤维软骨的结构同异。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "三种软骨的结构同异",
        "相同之处：都是由软骨组织和软骨膜构成，软骨细胞都能增殖分裂形成同源细胞群，软骨基质都包括纤维和基质，组织内皆无血管。不同之处：透明软骨含胶原原纤维，基质嗜碱性明显，尤其是软骨囊呈强嗜碱性；弹性软骨含大量弹性纤维，基质仅软骨囊呈明显嗜碱性；纤维软骨含大量粗大的胶原纤维，基质嗜酸性强，仅软骨囊处弱嗜碱性，同源细胞群的软骨细胞多排列成线性。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-short002",
    order: 19,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述软骨的生长方式。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "软骨的生长方式",
        "即附加性生长（软骨膜下生长）和间质性生长（软骨内生长）。附加性生长是通过在表面添加新的软骨细胞实现，来源于软骨膜内骨祖细胞的增殖分化，形成新的软骨细胞、产生新的软骨基质，使软骨从表面向外扩大。间质性生长则是已存在的软骨细胞由小变大、逐渐生长并进行分裂形成同源细胞群，同时分泌更多基质，使软骨从内部不断膨胀式生长。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-short003",
    order: 20,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述成骨细胞的来源、结构和功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "成骨细胞的来源、结构和功能",
        "来源：由骨祖细胞增殖分化而来。结构：分布在骨组织表面，呈矮柱状或不规则形，通常单层排列；细胞核圆，细胞质嗜碱性，含丰富的粗面内质网和发达的高尔基复合体。功能：具有分泌类骨质的强大能力，在分泌过程中自身被包埋、并发出许多细小突起，逐渐演变为骨细胞；成骨过程中还向类骨质中释放含细小钙盐结晶的基质小泡，具有促进类骨质钙化成骨质的重要作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-short004",
    order: 21,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述破骨细胞的结构和功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "破骨细胞的结构和功能",
        "破骨细胞是具有强大溶骨和溶软骨能力的细胞，数量少、散在分布于骨组织表面。细胞很大、形态不规则、多核、胞质嗜酸性强，含丰富的溶酶体和线粒体。功能活跃时呈现明显极性，紧贴骨组织一侧出现许多细小突起（皱褶缘），周围的胞质隆起、表面光滑、紧贴骨质构成一圈胞质围墙封闭溶骨区域（吸收陷窝）；细胞向此处释放多种水解酶和有机酸，溶解骨盐、分解有机质，故而起破骨作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-short005",
    order: 22,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述骨单位的结构。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骨单位的结构",
        "骨单位又称哈弗斯系统，位于内、外环骨板之间，是长骨中起支持作用的主要结构。数量多、长筒状，排列方向与骨干长轴基本一致。骨单位由多层同心圆排列的哈弗斯骨板围绕中央管构成。骨板中的胶原纤维绕中央管呈螺旋状走行，相邻骨板的纤维方向互成直角。哈弗斯骨板层数不等，故骨单位粗细不一。中央管为细长的管道，内有血管、神经纤维和少量疏松结缔组织。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，3 组 × 8 成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-b001",
    order: 23,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["内环骨板", "外环骨板", "骨小梁", "间骨板", "哈弗斯系统"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch04-cartilage-bone-b001m1",
        order: 23,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "构成松质骨的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "骨小梁",
            "松质骨由大量针片状骨小梁构成，肉眼可见许多孔隙。原书 B1 第 19 题答案 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch04-cartilage-bone-b001m2",
        order: 24,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "骨板排列成同心圆状的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "哈弗斯系统",
            "骨单位（哈弗斯系统）由多层同心圆排列的哈弗斯骨板围绕中央管构成。原书 B1 第 20 题答案 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch04-cartilage-bone-b001m3",
        order: 25,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "数量多，形状不规则的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "间骨板",
            "间骨板位于骨单位之间或骨单位与环骨板之间，大小和形状皆不甚规则。原书 B1 第 21 题答案 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-b002",
    order: 26,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["软骨成熟区", "成骨区", "软骨增生区", "软骨钙化区", "软骨静止区"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch04-cartilage-bone-b002m1",
        order: 26,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "细胞退化，基质嗜碱性强的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "软骨钙化区",
            "骺板五区中，软骨钙化区软骨细胞退化死亡、软骨基质钙化并呈较强嗜碱性。原书 B1 第 22 题答案 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch04-cartilage-bone-b002m2",
        order: 27,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "细胞小，分散排列的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "软骨静止区",
            "软骨储备（静止）区软骨细胞较小、散在分布，相当于软骨基质中相对「静息」的细胞。原书 B1 第 23 题答案 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch04-cartilage-bone-b002m3",
        order: 28,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "开始出现同源细胞群的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "软骨增生区",
            "软骨增生区软骨细胞分裂增殖，形成纵行排列的细胞柱（同源细胞群开始出现）。原书 B1 第 24 题答案 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-histology-embryology-ch04-cartilage-bone-b003",
    order: 29,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["成骨细胞", "骨细胞", "破骨细胞", "成软骨细胞", "骨祖细胞"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-histology-embryology-ch04-cartilage-bone-b003m1",
        order: 29,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "来源于单核细胞的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "破骨细胞",
            "破骨细胞为多核巨细胞，一般认为来源于单核-吞噬细胞系统的单核细胞。原书 B1 第 25 题答案 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-histology-embryology-ch04-cartilage-bone-b003m2",
        order: 30,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "来源于间充质细胞的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "骨祖细胞",
            "骨祖细胞位于骨膜内层，来自间充质，有增殖分化为成骨细胞的潜力。原书 B1 第 26 题答案 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...fillItems,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];