import type { MaterialCatalog } from "@/types/learning";

export const materialCatalog = {
  id: "material-catalog-2026-07-18-intake-fixtures",
  assets: [
    {
      id: "asset-tcm-diagnostics-textbook-third",
      sha256: "31b59341779d2507a5d6b8bb82cc2b902ea28d31139311cf1fe7e9fe59bf6e9b",
      byteSize: 112545318,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "ocr-pending",
      integrityStatus: "intact",
      privacyRisk: "document-metadata",
      publicationPolicy: "structured-excerpts-only",
      originalPathAliases: [
        { intakeId: "MAT-TCM-001", relativePath: "中医诊断学  第3版96186922.pdf" },
      ],
    },
    {
      id: "asset-tcm-diagnostics-teacher-review",
      sha256: "b0ec7744c9c91d3f1dfb41999302bb744ea5c419f0860f034f9899481cadae89",
      byteSize: 109338,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "native-text",
      integrityStatus: "intact",
      privacyRisk: "document-metadata",
      publicationPolicy: "structured-excerpts-only",
      originalPathAliases: [
        { intakeId: "MAT-017", relativePath: "中医诊断学/中诊保命重点.pdf" },
      ],
    },
    {
      id: "asset-tcm-diagnostics-liver-slide",
      sha256: "08b5c065380c3af6eacedc7c7983231a4607c9a8217ab042f8bdcbd21bcdf013",
      byteSize: 18375238,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "ocr-pending",
      integrityStatus: "pending-review",
      privacyRisk: "document-metadata",
      publicationPolicy: "local-only",
      originalPathAliases: [
        { intakeId: "MAT-001", relativePath: "中医诊断学/PPT重点/20240614_肝胆 增强文本.pdf" },
      ],
    },
    {
      id: "asset-tcm-diagnostics-lung-slide",
      sha256: "74577733a5a7438e62aaff1d879205384e1831bc191e4258d3c31830f732697f",
      byteSize: 21338345,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "ocr-pending",
      integrityStatus: "pending-review",
      privacyRisk: "document-metadata",
      publicationPolicy: "local-only",
      originalPathAliases: [
        { intakeId: "MAT-002", relativePath: "中医诊断学/PPT重点/20240614_肺大肠 增强文本.pdf" },
      ],
    },
    {
      id: "asset-tcm-diagnostics-kidney-slide",
      sha256: "bb65d0f66b47aa7f283ae2d7491cfd2310582746f67065bdfedb2bdc6b035825",
      byteSize: 5571371,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "ocr-pending",
      integrityStatus: "pending-review",
      privacyRisk: "document-metadata",
      publicationPolicy: "local-only",
      originalPathAliases: [
        { intakeId: "MAT-003", relativePath: "中医诊断学/PPT重点/20240614_肾膀胱 锐化打印.pdf" },
      ],
    },
    {
      id: "asset-tcm-diagnostics-spleen-slide",
      sha256: "371267dad76d1a2d1d6f9429197a046b0a72fe56c60b4913369a92775f7850fe",
      byteSize: 11404657,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "ocr-pending",
      integrityStatus: "pending-review",
      privacyRisk: "document-metadata",
      publicationPolicy: "local-only",
      originalPathAliases: [
        { intakeId: "MAT-004", relativePath: "中医诊断学/PPT重点/20240614_脾胃 锐化打印.pdf" },
      ],
    },
    {
      id: "asset-tcm-diagnostics-heart-slide",
      sha256: "46bdb386cdd9f3956e6e18d614aec39b6774db97024bb40dc928d345305e96b8",
      byteSize: 2354542,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "ocr-pending",
      integrityStatus: "pending-review",
      privacyRisk: "document-metadata",
      publicationPolicy: "local-only",
      originalPathAliases: [
        { intakeId: "MAT-005", relativePath: "中医诊断学/PPT重点/心与膀胱.pdf" },
      ],
    },
    {
      id: "asset-tcm-diagnostics-exam-2021-2022",
      sha256: "0d593607986478196480126b82bbcf32c265fe4aa5fedebb0c509874ee944c8f",
      byteSize: 122743,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "native-text",
      integrityStatus: "intact",
      privacyRisk: "blank-personal-fields",
      publicationPolicy: "structured-excerpts-only",
      originalPathAliases: [
        { intakeId: "MAT-019", relativePath: "中医诊断学/南京中医药大学《中医诊断学》2021-2022学年第一学期期末试卷.pdf" },
      ],
    },
    {
      id: "asset-tcm-diagnostics-whitebook",
      sha256: "593e7672e0e57c9904c77fceefd96314b505e7818fdee8a7e727cac56da55f30",
      byteSize: 22016,
      mediaType: "word",
      academicContentStatus: "available",
      transcriptionStatus: "native-text",
      integrityStatus: "intact",
      privacyRisk: "blank-personal-fields",
      publicationPolicy: "structured-excerpts-only",
      originalPathAliases: [
        { intakeId: "MAT-022", relativePath: "中医诊断学/南京中医药大学中医诊断学试题.doc.doc.doc" },
      ],
    },
    {
      id: "asset-western-diagnostics-2022-2023",
      sha256: "b89a6fc9ccd9e78546ceb736a640a6f9efcb200f4686d2ee54859c9c689274a6",
      byteSize: 136455,
      mediaType: "pdf",
      academicContentStatus: "pending",
      transcriptionStatus: "native-text",
      integrityStatus: "misfiled",
      privacyRisk: "blank-personal-fields",
      publicationPolicy: "local-only",
      originalPathAliases: [
        {
          intakeId: "MAT-020",
          relativePath: "中医诊断学/南京中医药大学《诊断学》2022-2023学年第一学期期末试卷.pdf",
        },
        {
          intakeId: "MAT-080",
          relativePath: "组织胚胎学/南京中医药大学《诊断学》2022-2023学年第一学期期末试卷.pdf",
        },
      ],
    },
    {
      id: "asset-western-diagnostics-2023-2024",
      sha256: "2cb07c693ce4d52215c796c5e14d5a0ca7a8e94e947c3e6a3ac2ece6725e9b8c",
      byteSize: 162888,
      mediaType: "pdf",
      academicContentStatus: "pending",
      transcriptionStatus: "native-text",
      integrityStatus: "misfiled",
      privacyRisk: "blank-personal-fields",
      publicationPolicy: "local-only",
      originalPathAliases: [
        {
          intakeId: "MAT-021",
          relativePath: "中医诊断学/南京中医药大学《诊断学》2023-2024学年第一学期期末试卷.pdf",
        },
      ],
    },
    {
      id: "asset-physiology-textbook-fourth",
      sha256: "23afdb7838f814538dde65182436d6a604ff54976cfa9a3573fb6e5ab9a3320c",
      byteSize: 97413706,
      mediaType: "pdf",
      academicContentStatus: "verified",
      transcriptionStatus: "native-text",
      integrityStatus: "intact",
      privacyRisk: "document-metadata",
      publicationPolicy: "structured-excerpts-only",
      originalPathAliases: [
        { intakeId: "MAT-042", relativePath: "生理学 第4版.pdf" },
      ],
    },
    {
      id: "asset-physiology-question-collection",
      sha256: "300cc8ff8b2ea0c4d1f76ffc8dfe725475f076c049812f152eafff387fc5a9b0",
      byteSize: 5594420,
      mediaType: "word",
      academicContentStatus: "available",
      transcriptionStatus: "native-text",
      integrityStatus: "intact",
      privacyRisk: "document-metadata",
      publicationPolicy: "structured-excerpts-only",
      originalPathAliases: [
        { intakeId: "MAT-043", relativePath: "生理学/20240601_生理问答题.doc" },
      ],
    },
    {
      id: "asset-physiology-nur-day-one",
      sha256: "32cd7b1cfa846a6f644c4e7f321bc9e717912cf1c5b279309f1262db3f8c4145",
      byteSize: 333119,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "native-text",
      integrityStatus: "derived",
      privacyRisk: "document-metadata",
      publicationPolicy: "structured-excerpts-only",
      originalPathAliases: [
        { intakeId: "MAT-045", relativePath: "生理学/output/pdf/第一天生理学背诵内容及答案.pdf" },
      ],
    },
    {
      id: "asset-physiology-exam-2021-2022",
      sha256: "8aa9af04a8450c84417a9b1305876b197734c4ff831f6451e83164bd18bad7c5",
      byteSize: 148801,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "native-text",
      integrityStatus: "intact",
      privacyRisk: "blank-personal-fields",
      publicationPolicy: "structured-excerpts-only",
      originalPathAliases: [
        { intakeId: "MAT-054", relativePath: "生理学/南京中医药大学《生理学》2021-2022第一学期期末试卷(2).pdf" },
      ],
    },
    {
      id: "asset-physiology-exam-2022-2023",
      sha256: "38a488404a6d32a5b499465c6f9edc5050433ab2ed38e860c31bdbe0a7858748",
      byteSize: 155115,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "native-text",
      integrityStatus: "intact",
      privacyRisk: "blank-personal-fields",
      publicationPolicy: "structured-excerpts-only",
      originalPathAliases: [
        { intakeId: "MAT-055", relativePath: "生理学/南京中医药大学《生理学》2022-2023第一学期期末试卷(2).pdf" },
      ],
    },
    {
      id: "asset-physiology-whitebook-pdf",
      sha256: "87d90a7be634006c874f992eef7b89b6d5b43f2f2f0a1c61e3297e8f52b4249c",
      byteSize: 981932,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "native-text",
      integrityStatus: "intact",
      privacyRisk: "document-metadata",
      publicationPolicy: "structured-excerpts-only",
      originalPathAliases: [
        { intakeId: "MAT-057", relativePath: "生理学/生理白皮.pdf" },
      ],
    },
    {
      id: "asset-physiology-whitebook-docx",
      sha256: "46018178d1e17ec48f80a82c4fd2d85c456a41ccdd6daad7fdddeaad82ce5fa3",
      byteSize: 191762,
      mediaType: "word",
      academicContentStatus: "available",
      transcriptionStatus: "native-text",
      integrityStatus: "tracked-changes",
      privacyRisk: "document-metadata",
      publicationPolicy: "local-only",
      originalPathAliases: [
        { intakeId: "MAT-058", relativePath: "生理学/生理白皮（题库）.docx" },
      ],
    },
    {
      id: "asset-physiology-classroom-task-image",
      sha256: "eccf1788e50d126a88837cdbe7f199b6ba0687b82323c306d20eb09bf7aae8c2",
      byteSize: 226785,
      mediaType: "image",
      academicContentStatus: "available",
      transcriptionStatus: "ocr-transcribed",
      integrityStatus: "pending-review",
      privacyRisk: "identifiable-person",
      publicationPolicy: "local-only",
      originalPathAliases: [
        { intakeId: "MAT-070", relativePath: "生理学/课件/绪论学习任务.jpg" },
      ],
    },
    {
      id: "asset-biochemistry-question-bank-tracked",
      sha256: "95c12df7958d34d4290801dddf5fadeaac8746fa832c17609cbcfa613a801f41",
      byteSize: 30425,
      mediaType: "word",
      academicContentStatus: "available",
      transcriptionStatus: "native-text",
      integrityStatus: "tracked-changes",
      privacyRisk: "document-metadata",
      publicationPolicy: "local-only",
      originalPathAliases: [
        { intakeId: "MAT-040", relativePath: "生物化学/生物化学（期末考试大题题库）.docx" },
      ],
    },
    {
      id: "asset-histology-bank-111",
      sha256: "4f00f837fcf7e15462c855e2aea328478d4d7f191ef675f0c894b25b290e1203",
      byteSize: 65434,
      mediaType: "word",
      academicContentStatus: "available",
      transcriptionStatus: "native-text",
      integrityStatus: "intact",
      privacyRisk: "document-metadata",
      publicationPolicy: "structured-excerpts-only",
      originalPathAliases: [
        { intakeId: "MAT-111", relativePath: "组织胚胎学/组织胚胎学考试复习题库含答案（最全版+） (1).docx" },
      ],
    },
    {
      id: "asset-histology-bank-113",
      sha256: "90fbf718d211ba6066b434c24b54bedfbe94ad6314dbc5983cb919016ce46ce7",
      byteSize: 171008,
      mediaType: "word",
      academicContentStatus: "available",
      transcriptionStatus: "native-text",
      integrityStatus: "intact",
      privacyRisk: "document-metadata",
      publicationPolicy: "structured-excerpts-only",
      originalPathAliases: [
        { intakeId: "MAT-113", relativePath: "组织胚胎学/组织胚胎学题库.doc" },
      ],
    },
    {
      id: "asset-histology-scanned-yellow-book",
      sha256: "ed9a683ae830b72e67918480f9a39987a2d6eacb980a09f827d3751d41287fad",
      byteSize: 22557365,
      mediaType: "pdf",
      academicContentStatus: "available",
      transcriptionStatus: "ocr-transcribed",
      integrityStatus: "pending-review",
      privacyRisk: "document-metadata",
      publicationPolicy: "local-only",
      originalPathAliases: [
        { intakeId: "MAT-115", relativePath: "组织胚胎学/组胚黄皮（扫描版）.pdf" },
      ],
    },
  ],
  families: [
    { id: "family-tcm-diagnostics-textbook-third", label: "《中医诊断学》第3版教材", artifactIds: ["artifact-tcm-diagnostics-textbook-third"] },
    { id: "family-tcm-diagnostics-teacher-review", label: "任课教师中诊复习重点", artifactIds: ["artifact-tcm-diagnostics-teacher-review"] },
    { id: "family-tcm-diagnostics-liver-slide", label: "任课教师肝胆重点课件", artifactIds: ["artifact-tcm-diagnostics-liver-slide"] },
    { id: "family-tcm-diagnostics-lung-slide", label: "任课教师肺与大肠重点课件", artifactIds: ["artifact-tcm-diagnostics-lung-slide"] },
    { id: "family-tcm-diagnostics-kidney-slide", label: "任课教师肾与膀胱重点课件", artifactIds: ["artifact-tcm-diagnostics-kidney-slide"] },
    { id: "family-tcm-diagnostics-spleen-slide", label: "任课教师脾胃重点课件", artifactIds: ["artifact-tcm-diagnostics-spleen-slide"] },
    { id: "family-tcm-diagnostics-heart-slide", label: "任课教师心与小肠重点课件", artifactIds: ["artifact-tcm-diagnostics-heart-slide"] },
    { id: "family-tcm-diagnostics-exam-2021-2022", label: "中医诊断学2021–2022历史试卷", artifactIds: ["artifact-tcm-diagnostics-exam-2021-2022"] },
    { id: "family-tcm-diagnostics-whitebook", label: "南京中医药大学中医诊断学白皮题库", artifactIds: ["artifact-tcm-diagnostics-whitebook"] },
    { id: "family-western-diagnostics-exam-2022-2023", label: "错放的西医《诊断学》2022–2023试卷", artifactIds: ["artifact-western-diagnostics-2022-2023"] },
    { id: "family-western-diagnostics-exam-2023-2024", label: "错放的西医《诊断学》2023–2024试卷", artifactIds: ["artifact-western-diagnostics-2023-2024"] },
    { id: "family-physiology-textbook-fourth", label: "《生理学》第4版", artifactIds: ["artifact-physiology-textbook-fourth"] },
    { id: "family-physiology-question-collection", label: "生理问答题汇编", artifactIds: ["artifact-physiology-question-collection"] },
    { id: "family-physiology-nur-day-one", label: "NUR/Codex 生理学第一天派生稿", artifactIds: ["artifact-physiology-nur-day-one"] },
    { id: "family-physiology-exam-2021-2022", label: "生理学2021–2022历史试卷", artifactIds: ["artifact-physiology-exam-2021-2022"] },
    { id: "family-physiology-exam-2022-2023", label: "生理学2022–2023历史试卷", artifactIds: ["artifact-physiology-exam-2022-2023"] },
    { id: "family-physiology-whitebook", label: "南京中医药大学生理学教研室白皮", artifactIds: ["artifact-physiology-whitebook-pdf", "artifact-physiology-whitebook-docx"] },
    { id: "family-physiology-classroom-task", label: "生理学绪论课堂任务照片", artifactIds: ["artifact-physiology-classroom-task-image"] },
    { id: "family-biochemistry-question-bank", label: "生物化学大题库", artifactIds: ["artifact-biochemistry-question-bank-tracked"] },
    { id: "family-histology-bank-111", label: "组织胚胎学学生题库 MAT-111", artifactIds: ["artifact-histology-bank-111"] },
    { id: "family-histology-bank-113", label: "组织胚胎学学生题库 MAT-113", artifactIds: ["artifact-histology-bank-113"] },
    { id: "family-histology-scanned-yellow-book", label: "组织胚胎学黄皮扫描件", artifactIds: ["artifact-histology-scanned-yellow-book"] },
  ],
  artifacts: [
    { id: "artifact-tcm-diagnostics-textbook-third", familyId: "family-tcm-diagnostics-textbook-third", assetId: "asset-tcm-diagnostics-textbook-third", label: "出版社教材扫描PDF", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-tcm-diagnostics-teacher-review", familyId: "family-tcm-diagnostics-teacher-review", assetId: "asset-tcm-diagnostics-teacher-review", label: "任课教师复习重点PDF", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-tcm-diagnostics-liver-slide", familyId: "family-tcm-diagnostics-liver-slide", assetId: "asset-tcm-diagnostics-liver-slide", label: "肝胆重点增强文本PDF", versionKind: "format-variant", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-tcm-diagnostics-lung-slide", familyId: "family-tcm-diagnostics-lung-slide", assetId: "asset-tcm-diagnostics-lung-slide", label: "肺与大肠重点增强文本PDF", versionKind: "format-variant", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-tcm-diagnostics-kidney-slide", familyId: "family-tcm-diagnostics-kidney-slide", assetId: "asset-tcm-diagnostics-kidney-slide", label: "肾与膀胱重点锐化打印PDF", versionKind: "format-variant", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-tcm-diagnostics-spleen-slide", familyId: "family-tcm-diagnostics-spleen-slide", assetId: "asset-tcm-diagnostics-spleen-slide", label: "脾胃重点锐化打印PDF", versionKind: "format-variant", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-tcm-diagnostics-heart-slide", familyId: "family-tcm-diagnostics-heart-slide", assetId: "asset-tcm-diagnostics-heart-slide", label: "心与小肠重点课件PDF", versionKind: "format-variant", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-tcm-diagnostics-exam-2021-2022", familyId: "family-tcm-diagnostics-exam-2021-2022", assetId: "asset-tcm-diagnostics-exam-2021-2022", label: "学校历史试卷PDF", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-tcm-diagnostics-whitebook", familyId: "family-tcm-diagnostics-whitebook", assetId: "asset-tcm-diagnostics-whitebook", label: "学校题库Word原件", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-western-diagnostics-2022-2023", familyId: "family-western-diagnostics-exam-2022-2023", assetId: "asset-western-diagnostics-2022-2023", label: "同一PDF的两个原路径别名", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-western-diagnostics-2023-2024", familyId: "family-western-diagnostics-exam-2023-2024", assetId: "asset-western-diagnostics-2023-2024", label: "错放的西医诊断学历史试卷PDF", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-physiology-textbook-fourth", familyId: "family-physiology-textbook-fourth", assetId: "asset-physiology-textbook-fourth", label: "出版社教材PDF", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-physiology-question-collection", familyId: "family-physiology-question-collection", assetId: "asset-physiology-question-collection", label: "问答题汇编Word", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-physiology-nur-day-one", familyId: "family-physiology-nur-day-one", assetId: "asset-physiology-nur-day-one", label: "NUR/Codex派生复习稿", versionKind: "derived", derivationStatus: "inferred", derivedFromArtifactIds: ["artifact-physiology-textbook-fourth", "artifact-physiology-whitebook-pdf"] },
    { id: "artifact-physiology-exam-2021-2022", familyId: "family-physiology-exam-2021-2022", assetId: "asset-physiology-exam-2021-2022", label: "历史试卷PDF", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-physiology-exam-2022-2023", familyId: "family-physiology-exam-2022-2023", assetId: "asset-physiology-exam-2022-2023", label: "历史试卷PDF", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-physiology-whitebook-pdf", familyId: "family-physiology-whitebook", assetId: "asset-physiology-whitebook-pdf", label: "白皮PDF版", versionKind: "format-variant", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-physiology-whitebook-docx", familyId: "family-physiology-whitebook", assetId: "asset-physiology-whitebook-docx", label: "白皮DOCX修订版", versionKind: "tracked-revision", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-physiology-classroom-task-image", familyId: "family-physiology-classroom-task", assetId: "asset-physiology-classroom-task-image", label: "含人物的课堂投影照片", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-biochemistry-question-bank-tracked", familyId: "family-biochemistry-question-bank", assetId: "asset-biochemistry-question-bank-tracked", label: "含修订痕迹的DOCX", versionKind: "tracked-revision", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-histology-bank-111", familyId: "family-histology-bank-111", assetId: "asset-histology-bank-111", label: "学生题库MAT-111", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-histology-bank-113", familyId: "family-histology-bank-113", assetId: "asset-histology-bank-113", label: "学生题库MAT-113", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
    { id: "artifact-histology-scanned-yellow-book", familyId: "family-histology-scanned-yellow-book", assetId: "asset-histology-scanned-yellow-book", label: "黄皮扫描件", versionKind: "original", derivationStatus: "not-applicable", derivedFromArtifactIds: [] },
  ],
  transcriptions: [
    {
      id: "transcription-physiology-classroom-task",
      artifactId: "artifact-physiology-classroom-task-image",
      status: "ocr-transcribed",
      academicContentStatus: "available",
      locators: [
        { id: "locator-physiology-classroom-task-ocr", artifactId: "artifact-physiology-classroom-task-image", kind: "ocr-region", value: "整张图像中的课堂投影区域", label: "Vision OCR转录层；人物区域不发布" },
      ],
      notice: "OCR仅用于检索课堂投影中的体液、内环境与稳态关键词；图中人物和原图不得进入前端。",
    },
    {
      id: "transcription-histology-yellow-book",
      artifactId: "artifact-histology-scanned-yellow-book",
      status: "ocr-transcribed",
      academicContentStatus: "available",
      locators: [
        { id: "locator-histology-yellow-book-ocr", artifactId: "artifact-histology-scanned-yellow-book", kind: "ocr-region", value: "PDF页1–61", label: "扫描页Vision OCR转录层" },
      ],
      notice: "OCR文本保留PDF页码定位，未经逐页人工核对，不能作为verified答案或教材真相。",
    },
  ],
  answerConflicts: [
    {
      id: "conflict-histology-peroxisome",
      prompt: "主要参与细胞内过氧化物分解的细胞器是",
      questionKind: "a1-single",
      status: "unresolved",
      locators: [
        { id: "locator-conflict-peroxisome-111", artifactId: "artifact-histology-bank-111", kind: "question", value: "题干全文", label: "MAT-111同题" },
        { id: "locator-conflict-peroxisome-113", artifactId: "artifact-histology-bank-113", kind: "question", value: "题干全文", label: "MAT-113同题" },
      ],
      variants: [
        { id: "variant-peroxisome-111-b", label: "MAT-111标注B", authority: "student-compiled", confidence: "unverified", content: ["B（线粒体）"], sourceArtifactIds: ["artifact-histology-bank-111"] },
        { id: "variant-peroxisome-113-d", label: "MAT-113标注D", authority: "student-compiled", confidence: "unverified", content: ["D（微体／过氧化物酶体）"], sourceArtifactIds: ["artifact-histology-bank-113"] },
      ],
      notice: "两份学生题库选项顺序一致但答案不同；未由教材或教师答案裁决前不得显示标准答案。",
    },
    {
      id: "conflict-histology-cns-myelin",
      prompt: "在中枢神经系统内参与髓鞘形成的细胞是",
      questionKind: "a1-single",
      status: "unresolved",
      locators: [
        { id: "locator-conflict-cns-myelin-111", artifactId: "artifact-histology-bank-111", kind: "question", value: "题干全文", label: "MAT-111同题" },
        { id: "locator-conflict-cns-myelin-113", artifactId: "artifact-histology-bank-113", kind: "question", value: "题干全文", label: "MAT-113同题" },
      ],
      variants: [
        { id: "variant-cns-myelin-111-b", label: "MAT-111标注B", authority: "student-compiled", confidence: "unverified", content: ["B（少突胶质细胞）"], sourceArtifactIds: ["artifact-histology-bank-111"] },
        { id: "variant-cns-myelin-113-c", label: "MAT-113标注C", authority: "student-compiled", confidence: "unverified", content: ["C（小胶质细胞）"], sourceArtifactIds: ["artifact-histology-bank-113"] },
      ],
      notice: "两份学生题库选项顺序一致但答案不同；未由教材或教师答案裁决前不得显示标准答案。",
    },
  ],
} satisfies MaterialCatalog;
