import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学免疫学学习指导与习题集（第3版）— 第9章 B淋巴细胞 题库提取（等比取样）
 * 来源：《医学免疫学学习指导与习题集》第3版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 章节等比缩放预算）==
 * - 名词解释：5 题
 * - 填空题（fill）：5 题
 * - 选择题（a1-single）：17 题（含 A2 病例题）
 * - 问答题（short-answer）：4 题
 * - 独立记分题合计：31 题（须等于本文件预算 31）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书题型分布为名词解释 5、填空 5、A1 型 45、A2 型 27、B1 型 12、问答题 4；
 *   本文件按 31 道预算等比取材并在原书范围取样。全部正确项对照章末「参考答案」键号锚定，
 *   A1 型 41~44 题答案在 OCR 中与该章节 A1 段分离（出现在 A2 键号前部），已按题号正确归位；
 *   选项均已随机重排并同步 correctChoiceIndex（0 起）。OCR 错字已按免疫学医学语义恢复
 *   （如 Iga/Igβ→CD79a/CD79b 复合物、mIgM/mIgD 标记符号、ITIM 基序、CD4⁺/CD4⁻ 等），未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "immunology-ch09-b-lymphocyte";
const locatorBase =
  "《医学免疫学学习指导与习题集》第3版 第9章 B淋巴细胞 习题（核对PDF 第99–111页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），5 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-immunology-ch09-b-lymphocyte-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：初始B细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "初始B细胞",
        "初始B细胞是指从未接受过抗原刺激的B细胞。初始B细胞能够接受抗原刺激并活化，分化成记忆B细胞或浆细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：等位排斥",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "等位排斥",
        "等位排斥指B细胞中一条染色体上的重链（或轻链）基因重排成功后，抑制另一条同源染色体上重链（或轻链）基因的重排。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：受体编辑",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "受体编辑",
        "受体编辑指一些完成基因重排并成功表达BCR（mIgM）的B细胞识别自身抗原后未被克隆清除，而是发生RAG基因重新活化，导致轻链VJ再次重排，合成新的轻链以替代自身反应性轻链，从而使BCR获得新的特异性。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：克隆清除",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "克隆清除",
        "前B细胞在骨髓中发育至未成熟B细胞后，其表面仅表达完整的mIgM，此时的mIgM若与骨髓中的自身抗原结合，则导致细胞凋亡，此为克隆清除。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：B细胞抗原受体（BCR）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "B细胞抗原受体（BCR）",
        "BCR即膜表面免疫球蛋白（mIg），存在于B细胞表面，是B细胞的标志，其V区部分能与抗原特异性结合。在BCR复合物中还有由两对异二聚体组成的信号传导分子Iga和Igβ（CD79a/CD79b），其功能是辅助mIg向B细胞传导活化信号，参与mIg的表达与转运。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2 型选择题（统一映射为 a1-single），17 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1001",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "mIgD 只表达在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "抗原递呈细胞",
      "成熟的初始B细胞上",
      "调节性B细胞",
      "记忆B细胞",
      "浆细胞",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "成熟的初始B细胞上",
        "初始（成熟）B细胞表面同时表达mIgM和mIgD，mIgD仅表达在成熟初始B细胞上，是初始B细胞的标志之一。抗原递呈细胞、记忆B细胞、浆细胞及调节性B细胞一般不单独以mIgD为主要标志。原书 A1 第 1 题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1002",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下关于BCR的胚系基因结构错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "人Ig重链基因群位于第14号染色体长臂",
      "人的V和J基因片段数分别为40和5个",
      "人Ig轻链λ基因定位于第22号染色体短臂",
      "人Ig轻链K基因定位于第2号染色体长臂",
      "人的VH、DH和JH基因片段数分别为45、23和6个",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "人Ig轻链λ基因定位于第22号染色体短臂",
        "人Ig轻链λ基因定位于第22号染色体长臂（非短臂），故该项表述错误。其余均正确：重链基因群位于第14号染色体长臂，κ基因位于第2号染色体长臂。原书 A1 第 4 题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1003",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "体细胞高频突变主要发生在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["D区", "V区", "J区", "C区", "M区"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "V区",
        "体细胞高频突变主要发生在Ig可变区（V区）的CDR区段基因序列，通过碱基点突变提高抗体的亲和力。原书 A1 第 6 题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1004",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于B细胞错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "早期pro-B细胞开始重排重链可变区基因D-J",
      "pro-B cell 开始表达 mlgM",
      "晚期pro-B细胞的V-D-J基因发生重排",
      "pro-B细胞开始表达Iga/Igβ异源二聚体",
      "Iga/Igβ是BCR复合物的组成部分，是B细胞的重要标记",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "pro-B cell 开始表达 mlgM",
        "表达mIgM（完整BCR）的是未成熟B细胞而非pro-B细胞；pro-B细胞仅开始表达Iga/Igβ异源二聚体。其余各项均是pro-B细胞发育特征的正确描述。原书 A1 第 9 题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1005",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "B细胞表面最重要的标志为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["FcyR", "CD5", "mlg", "CD40", "CD80"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "mlg",
        "膜表面免疫球蛋白（mIg）是B细胞最特征性的表面标志，是B细胞识别特异性抗原的受体。FcyR、CD5、CD40、CD80等亦见于其他细胞或非最特异标志。原书 A1 第 12 题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1006",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "属于B细胞的表面标志为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD3", "CD4", "CD19", "CD8", "CD56"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD19",
        "CD19是B细胞表面的特异性标志，也是BCR识别抗原过程中关键的信号传递分子。CD3、CD4、CD8为T细胞标志，CD56为NK细胞标志。原书 A1 第 13 题答案 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1007",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下不属于B细胞共刺激分子的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD40", "CD80", "CD54", "LFA-1", "CD19"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD19",
        "CD19 是B细胞共受体及信号传递分子，不属于共刺激分子。CD40、CD80以及黏附分子类（CD54/ICAM-1、LFA-1）均参与B细胞与T细胞间的共刺激/黏附作用。原书 A1 第 16 题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1008",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "能与C3d结合形成复合体，发挥B细胞共受体作用的分子为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD21", "CD80", "CD20", "CD32", "CD40"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD21",
        "CD21（CR2）是补体C3d的受体，与CD19、CD81非共价相连形成B细胞的多分子共受体，可增强BCR与抗原结合的稳定性。原书 A1 第 18 题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1009",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "利妥昔单抗结合的靶分子",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD32", "CD20", "CD19", "CD40", "CD80"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD20",
        "利妥昔单抗是抗CD20的人鼠嵌合单克隆抗体，CD20表达于除浆细胞外的各发育阶段B细胞，是治疗B淋巴细胞瘤的常用靶点。原书 A1 第 20 题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1010",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下不属于调节性B细胞（Breg）功能的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "产生炎性的细胞因子IL-6、TNF-α",
      "调节NK细胞和T细胞的功能",
      "调节巨噬细胞、树突状细胞",
      "分泌IL-10、TGF-β等抑制性细胞因子",
      "分泌IFN-γ等因子",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "分泌IFN-γ等因子",
        "调节性B细胞（Breg）主要通过分泌IL-10、TGF-β、IL-35等抑制性细胞因子发挥免疫调节作用，并调节巨噬细胞、DC、NK和T细胞功能；分泌IFN-γ并非其典型功能。原书 A1 第 21 题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1011",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下关于B1细胞的说法错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "B1细胞能自发分泌针对微生物脂多糖和某些自身抗原的IgM",
      "属于固有免疫细胞，在腹膜腔等部位能对微生物感染迅速产生抗体",
      "B1细胞也能产生多种针对自身抗原的抗体",
      "也是分泌抗体参与体液免疫应答的主要细胞",
      "B1在个体发育胚胎期即产生，具有自我更新能力",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "也是分泌抗体参与体液免疫应答的主要细胞",
        "分泌抗体参与体液免疫应答的主要细胞是B2细胞（滤泡B细胞），而非B1细胞。B1细胞属固有免疫细胞，主要参与对微生物脂多糖等的早期IgM应答。原书 A1 第 33 题答案 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1012",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下面哪个分子具有ITIM基序",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD19", "CD20", "CD22", "CD80", "CD86"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD22",
        "CD22特异性表达于B细胞，其胞质区含免疫受体酪氨酸抑制基序（ITIM），能负调节CD19/CD21/CD81共受体，从而负反馈调节B细胞活化。原书 A1 第 41 题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1013",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，男性，2岁，出生后5个月易患感冒、呼吸系统感染，因发烧39°C、咳嗽、呼吸困难入院，检查丙种球蛋白低，诊断为Bruton综合征。其体内缺乏",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["B细胞", "T细胞", "单核/巨噬细胞", "NK细胞", "树突状细胞"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "B细胞",
        "Bruton综合征即X-连锁无丙种球蛋白血症，是X染色体上酪氨酸激酶（Btk）基因缺陷所致，B细胞发育受阻，体内缺乏B细胞及抗体，故易反复发生细菌感染。原书 A2 第 46 题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1014",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，女性，40岁，患有哮喘，常反复发生呼吸道感染，检测血清免疫球蛋白：IgG 10.3g/L，IgA 0.04g/L，IgM 0.52g/L。该患者最有可能患有",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "Bruton综合征",
      "选择性IgA缺陷症",
      "X-连锁无丙种球蛋白血症",
      "霍奇金淋巴瘤",
      "系统性红斑狼疮",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "选择性IgA缺陷症",
        "该患者IgA仅0.04g/L（明显降低），而IgG、IgM基本正常，符合选择性IgA缺陷症的特点；此类患者常伴呼吸道和黏膜反复感染。原书 A2 第 47 题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1015",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，女性，50岁，贫血，晨起关节活动不灵活，近一月发现关节畸形，诊断为类风湿关节炎，考虑使用Rituximab（利妥昔单抗）治疗，其原理为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "抗CD19单抗",
      "TNF-α嵌合性单克隆抗体",
      "抗CD20单抗",
      "IL-6受体拮抗剂",
      "抗CD79a单抗",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗CD20单抗",
        "利妥昔单抗是抗CD20的人鼠嵌合单抗，通过清除CD20⁺B细胞来减少致病性自身抗体产生，用于类风湿关节炎等B细胞介导自身免疫病的治疗。原书 A2 第 51 题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1016",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某患者每到春天就出现皮肤红肿、奇痒难熬的症状，其他季节则不会发病。诊断为因花粉导致的过敏反应（荨麻疹），过敏反应的主要效应细胞为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "mIgM⁺ B细胞",
      "mIgD⁺ B细胞",
      "mIgG⁺ B细胞",
      "mIgA⁺ B细胞",
      "mIgE⁺ B细胞",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "mIgE⁺ B细胞",
        "花粉引起的I型超敏反应（荨麻疹）效应分子是IgE，IgE由mIgE⁺B细胞分化而来的浆细胞产生，与肥大细胞、嗜碱性粒细胞表面FcεRI结合导致介质释放。原书 A2 第 53 题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-a1017",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患儿，男性，6岁，因颈部淋巴结无痛性、渐进性增大就诊，穿刺免疫组化结果：肿瘤细胞CD20⁺、Bcl6⁺、MUM1⁺、Bcl2⁺，CD3⁻、CD4⁻、CD8⁻，AE1/AE3⁻，Ki67⁺（约60%），其可能的诊断是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["胃癌", "肝癌", "肺癌", "直肠癌", "淋巴瘤"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "淋巴瘤",
        "肿瘤细胞表达B细胞标记CD20、Bcl6、MUM1等，而T细胞标记（CD3、CD4、CD8）及上皮标记AE1/AE3均阴性，结合Ki67约60%，符合淋巴瘤（生发中心来源B细胞淋巴瘤）的诊断。原书 A2 第 58 题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），5 道 */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-immunology-ch09-b-lymphocyte-fill001",
    order: 23,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "根据B细胞所处的活化阶段分类，将B细胞分为___、___和___三类。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "初始B细胞、记忆B细胞、浆细胞",
        "按活化阶段，B细胞分为初始（naive）B细胞、记忆B细胞和浆细胞（效应B细胞）。原书填空题第 1 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-fill002",
    order: 24,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "根据CD5分子将B细胞分为___和___两群。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "B1细胞；B2细胞",
        "CD5⁺B1细胞和CD5⁻B2细胞（滤泡B细胞）。小鼠B1细胞表面标志为CD5分子。原书填空题第 2 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-fill003",
    order: 25,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "人Ig重链基因群包括___、___、___和___基因片段；人Ig轻链基因群分为___和___两种。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "V基因片段、D基因片段、J基因片段、C基因片段；K基因、λ基因",
        "Ig重链基因由V、D、J、C四类基因片段组成；轻链基因群分为κ基因和λ基因，仅含V、J基因片段。原书填空题第 3 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-fill004",
    order: 26,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "抗原识别受体多样性产生的四种机制包括___、___、___和___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "组合多样性；连接多样性；受体编辑；体细胞高频突变",
        "BCR多样性的四种机制：组合多样性、连接多样性、受体编辑和体细胞高频突变。原书填空题第 4 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-fill005",
    order: 27,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "B细胞表面的___、___和___非共价相连，形成B细胞的多分子共受体。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD19、CD21、CD81",
        "CD19、CD21及CD81非共价相连形成B细胞的多分子共受体，能增强BCR与抗原结合的稳定性并与Iga/Igβ共同传递B细胞活化的第一信号。原书填空题第 5 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 问答题（short-answer），4 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-immunology-ch09-b-lymphocyte-short001",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述B细胞的功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "B细胞的功能",
        "B细胞的主要功能是产生抗体介导体液免疫应答，还可提呈可溶性抗原、产生细胞因子参与免疫调节。①产生抗体介导体液免疫：抗体具有中和作用、激活补体、调理作用、ADCC、参与I型超敏反应等效应；②提呈抗原：B细胞也可作为抗原提呈细胞摄取、加工并提呈抗原，在再次免疫应答中对可溶性抗原的提呈尤为重要；③免疫调节：B细胞产生的细胞因子（IL-6、IL-10、TNF-α等）调节巨噬细胞、DC、NK及T细胞功能，Breg通过分泌IL-10、TGF-β、IL-35等抑制性细胞因子及表达FasL、CD1d等膜分子发挥免疫调节作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-short002",
    order: 29,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述B1细胞和B2细胞。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "B1细胞与B2细胞的区别",
        "B1是一个发育较早的固有免疫细胞亚群，约占B细胞总数的5%~10%，主要定居于腹膜腔、胸膜腔及肠道黏膜固有层；由胎肝分化，具有自我更新能力，小鼠表面标志为CD5；在免疫应答早期对微生物感染迅速产生IgM天然抗体，无需Th辅助、不进行类别转换，具多反应性，可产生自身抗体与自身免疫病有关。B2细胞是分泌抗体参与体液免疫应答的主要细胞，出现相对较晚，定位于外周淋巴器官滤泡区（滤泡B细胞），在抗原刺激和Th辅助下分化成浆细胞产生抗体，部分高亲和力细胞分化为记忆B细胞，介导快速的再次免疫应答。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-short003",
    order: 30,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述B细胞中枢免疫耐受的形成机制。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "B细胞中枢免疫耐受的形成机制",
        "前B细胞在骨髓中发育至未成熟B细胞后，其表面仅表达完整的mIgM。mIgM若与骨髓中的自身抗原结合，即导致细胞凋亡（克隆清除）；一些识别自身抗原的未成熟B细胞可通过受体编辑改变其BCR特异性；在某些情况下，未成熟B细胞与自身抗原结合可致mIgM表达下调，此类细胞虽可进入外周免疫器官但对抗原刺激不产生应答（失能）。通过克隆清除、受体编辑和失能等机制形成对自身抗原的中枢免疫耐受，成熟B细胞到达外周后仅被外来抗原激活。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch09-b-lymphocyte-short004",
    order: 31,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述B细胞在中枢免疫器官中的分化、发育过程。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "B细胞在中枢免疫器官的分化发育",
        "B细胞在骨髓中的发育不依赖抗原，依次经历祖B细胞（pro-B）、前B细胞（pre-B）、未成熟B细胞和成熟B细胞等阶段：祖B细胞开始表达Iga/Igβ异源二聚体；前B细胞表达前B细胞受体（pre-BCR）；未成熟B细胞表达完整BCR（mIgM）；成熟（初始）B细胞表面同时表达mIgM和mIgD。成熟B细胞迁移到外周，在抗原刺激下进一步分化为浆细胞和记忆B细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B 型配伍题：本书第9章虽有 B1 型题，但按项目规约不单独提取 B 组，bGroups 置空 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...fillItems,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];