import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学免疫学学习指导与习题集（第3版）— 第7章 白细胞分化抗原和黏附分子 题库提取（等比取样）
 * 来源：《医学免疫学学习指导与习题集》第3版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：3 题
 * - 填空题（fill）：3 题
 * - 选择题（a1-single）：18 题（含 A2 病例题 2 道；A1 型 16 道）
 * - 问答题（short-answer）：4 题
 * - 独立记分题合计：28 题（须等于本文件预算 28）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含名词解释 5、填空题 6、选择题（A1 型 47 + A2 型 17）、B1 配伍题
 *   及问答题 5；按预算等比取材（B1 按契约不提取为独立记分题，bGroups 置空）。A1 答案键
 *   为 1~47，A2 答案键为 48~64，与题目编号对齐，正确项均按源参考答案键号并对照免疫学
 *   医学语义核对。A2 病例题保留全部临床细节。OCR 错字与双栏错序已按医学语义恢复
 *   （CD3/CD4/CD8/CD19/CD20/CD45、LFA-1/ICAM-1、CD28/CTLA-4、CD152、HLA-B27 等）。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "immunology-ch07-adhesion-molecules";
const locatorBase =
  "《医学免疫学学习指导与习题集》第3版 第7章 白细胞分化抗原和黏附分子 习题（核对PDF 第76–87页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），3 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-immunology-ch07-adhesion-molecules-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：白细胞分化抗原",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白细胞分化抗原",
        "白细胞分化抗原（human leukocyte differentiation antigen, HLDA）是指造血干细胞在分化为不同谱系、各个细胞谱系分化不同阶段以及成熟细胞活化过程中，细胞表面表达的标记分子。它除表达于白细胞外，还广泛分布于红细胞、血小板、血管内皮细胞、成纤维细胞、上皮细胞、神经内分泌细胞等表面，参与固有免疫和适应性免疫应答。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞黏附分子",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞黏附分子",
        "细胞黏附分子（cell adhesion molecule, CAM）是介导细胞间或细胞与细胞外基质（ECM）间相互接触与结合的分子。黏附分子以受体-配体结合的形式发挥作用，使细胞与细胞间或细胞与基质间发生黏附。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：整合素",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "整合素",
        "整合素家族（integrin family）是因该类黏附分子主要介导细胞与细胞外基质的黏附，使细胞得以附着而形成整体（integration）而得名。整合素由一条 α 链和一条 β 链组成，按 β 亚单位不同分为 β1~β8 等组，分布广泛、作用广泛。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2 型选择题（映射为 a1-single），18 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1001",
    order: 4,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "结合抗原肽并将其提呈给 T 细胞的表面功能分子是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "T 细胞受体",
      "B 细胞受体",
      "共刺激分子",
      "MHC 分子",
      "细胞因子受体",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "MHC 分子",
        "MHC 分子结合抗原肽并将其提呈给 T 细胞，形成 TCR–抗原肽–MHC 复合物，是抗原特异性识别的关键。原书 A1 第 2 题答案 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1002",
    order: 5,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "LFA-1 的配体是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["LFA-2", "VLA-1", "FN", "LFA-3", "ICAM-1"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "ICAM-1",
        "LFA-1 属于整合素家族，其配体为 ICAM-1（CD54）以及 ICAM-2 等免疫球蛋白超家族分子。原书 A1 第 3 题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1003",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "HIV 的主要受体是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD3", "CD4", "CD8", "CD28", "CD40"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD4",
        "CD4 分子胞膜外区第一结构域是 HIV 外壳蛋白 gp120 识别的部位，因此人类 CD4 分子是 HIV 的主要受体。原书 A1 第 4 题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1004",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "白细胞分化抗原是指",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "白细胞分化过程中出现的各种膜分子",
      "T 细胞分化过程中出现的各种膜分子",
      "B 细胞分化过程中出现的各种膜分子",
      "淋巴细胞分化过程中出现的各种膜分子",
      "血细胞在分化成熟为不同谱系、分化的不同阶段及活化过程中出现或消失的细胞表面标记分子",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血细胞在分化成熟为不同谱系、分化的不同阶段及活化过程中出现或消失的细胞表面标记分子",
        "白细胞分化抗原是造血干细胞分化成熟为不同谱系、不同阶段及活化过程中出现或消失的细胞表面标记分子，故仅限「白细胞/某类细胞分化」的选项均不全面。原书 A1 第 6 题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1005",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在 TCR 识别抗原的信号转导过程中起关键作用的 CD 分子是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD2", "CD3", "CD4", "CD8", "CD28"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD3",
        "CD3 与 TCR 组成复合物，其胞质区含 ITAM 基序，在 TCR 识别抗原后的信号转导中起关键作用。原书 A1 第 7 题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1006",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "CD2 分子又称",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["LFA-1", "LFA-2", "LFA-3", "ICAM-1", "ICAM-2"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "LFA-2",
        "CD2 又称 LFA-2（或绵羊红细胞受体），其配体为 LFA-3（CD58），属于免疫球蛋白超家族，参与 T 细胞黏附与活化。原书 A1 第 9 题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1007",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与配体结合后，对 T 细胞活化有负调节作用的 CD 分子是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD2", "CD4", "CD8", "CD152", "CD28"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD152",
        "CD152 即 CTLA-4，与 CD28 拥有共同配体 B7-1/B7-2（CD80/CD86），但结合后向 T 细胞传递抑制信号，对 T 细胞活化发挥负调节作用。原书 A1 第 12 题答案 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1008",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "Th 细胞识别抗原的辅助受体是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD2", "CD3", "CD4", "CD5", "CD8"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD4",
        "CD4 表达于 Th 细胞表面，是辅助性 T 细胞识别抗原的辅助受体，与 MHC II 类分子结合，并参与 TCR 信号转导。原书 A1 第 18 题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1009",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "介导 NK 细胞发挥 ADCC 的分子是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD16", "CD3", "CD64", "CD23", "CD89"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD16",
        "CD16（FcγRIII）表达于 NK 细胞等表面，与抗体 Fc 段结合介导 ADCC，是 NK 细胞发挥 ADCC 的关键分子。原书 A1 第 22 题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1010",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下哪种黏附分子属于整合素家族",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["LFA-1", "LFA-2", "LFA-3", "ICAM-1", "ICAM-2"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "LFA-1",
        "LFA-1（CD11a/CD18）由 α、β 两条链组成，属于整合素家族（β2 组）；LFA-2、LFA-3、ICAM-1、ICAM-2 均属于免疫球蛋白超家族。原书 A1 第 26 题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1011",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "选择素家族的 CD 编号是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD29", "CD49", "CD18", "CD61", "CD62"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD62",
        "选择素家族成员均为 CD62，即 L-选择素（CD62L）、P-选择素（CD62P）、E-选择素（CD62E）。原书 A1 第 28 题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1012",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "L 选择素主要分布于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["白细胞", "血小板", "活化内皮细胞", "红细胞", "巨噬细胞"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白细胞",
        "L-选择素组成性表达于白细胞（淋巴细胞、中性粒细胞等）表面，主要参与淋巴细胞归巢和白细胞与内皮细胞的初始黏附；P/E-选择素才分别表达于血小板/巨噬细胞和活化内皮细胞。原书 A1 第 30 题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1013",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "介导血流中中性粒细胞与血管内皮细胞初始黏附的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "整合素家族",
      "免疫球蛋白超家族",
      "选择素家族",
      "钙黏蛋白（Cadherin）家族",
      "I 型细胞因子受体家族",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "选择素家族",
        "中性粒细胞沿血管内壁「滚动」再牢固黏附，其初始（最早）黏附主要由选择素家族（如 L/P/E-选择素与其寡糖配体 sLex）介导。原书 A1 第 36 题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1014",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在 T 细胞活化中，最重要的协同刺激分子是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "CD4/MHC II 类分子",
      "CD8/MHC I 类分子",
      "CD28/CD80 或 CD86",
      "CD2/CD58",
      "LFA-1/ICAM-1",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD28/CD80 或 CD86",
        "CD28 表达于 T 细胞，其配体 B7-1（CD80）/B7-2（CD86）表达于 APC，两者结合是 T 细胞活化最重要的协同（共）刺激信号。原书 A1 第 40 题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1015",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪项不是黏附分子的作用",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "参与淋巴细胞归巢",
      "参与免疫应答",
      "参与炎症的形成",
      "参与补体系统的激活",
      "参与血栓的形成",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "参与补体系统的激活",
        "黏附分子参与淋巴细胞归巢、免疫应答、炎症形成及血栓形成等，但不参与补体系统的激活（补体激活由补体固有成分与调节蛋白完成）。原书 A1 第 42 题答案 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1016",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "淋巴细胞归巢受体的配体是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["血管活性肽", "细胞因子受体", "血管地址素", "L-选择素", "P-选择素"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血管地址素",
        "淋巴细胞表面的归巢受体与血管内皮细胞（高内皮微静脉）表面的血管地址素相结合，介导淋巴细胞的定向归巢与再循环。原书 A1 第 44 题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1017",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某患者确诊为来源于 B 细胞的非霍奇金淋巴瘤（NHL），拟行靶向治疗，则最有价值的治疗药物是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "抗 CD20 单克隆抗体",
      "抗 CD3 单克隆抗体",
      "抗 CD4 单克隆抗体",
      "抗 CD25 单克隆抗体",
      "抗 CD18 单克隆抗体",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗 CD20 单克隆抗体",
        "CD20 表达于 B 细胞，B 细胞来源的 NHL 表达 CD20，利妥昔单抗（抗 CD20 单抗）是首选靶向治疗药物。原书 A2 型 48 题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-a1018",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，男性，25 岁。入院后确诊为强直性脊柱炎，则以下哪项阳性可协助诊断",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD18", "CD20", "HLA-DRB1", "HLA-B27", "HLA-A"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "HLA-B27",
        "强直性脊柱炎与 HLA-B27 高度关联，HLA-B27 阳性可协助诊断该病。原书 A2 型 52 题答案 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），3 道 */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-immunology-ch07-adhesion-molecules-fill001",
    order: 22,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "白细胞分化抗原大都是跨膜的糖蛋白，含三个区域：___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胞膜外区、跨膜区、胞质区",
        "白细胞分化抗原多为跨膜糖蛋白，由胞膜外区、跨膜区和胞质区三部分组成，亦存在糖基磷脂酰肌醇锚定和碳水化合物等形式。原书填空题第 1 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-fill002",
    order: 23,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "目前人 CD 的编号已命名至___，大致划分为___个组。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD363；14",
        "经国际人类白细胞分化抗原专题讨论会命名，目前人 CD 编号已命名至 CD363，可大致划分为 14 个组。原书填空题第 2 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-fill003",
    order: 24,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "在淋巴细胞归巢过程中，归巢受体是表达在___细胞上的黏附分子，血管地址素是表达在___细胞上的黏附分子。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "淋巴；内皮",
        "归巢受体表达于淋巴细胞表面，血管地址素表达于血管内皮细胞（高内皮微静脉）表面，两者结合介导淋巴细胞归巢。原书填空题第 6 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 问答题（short-answer），4 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-immunology-ch07-adhesion-molecules-short001",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述白细胞分化抗原、CD 分子和黏附分子的基本概念。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白细胞分化抗原：指造血干细胞在分化为不同谱系、各个细胞谱系分化不同阶段以及成熟细胞活化过程中，细胞表面表达的标记分子。CD 分子：应用以单克隆抗体鉴定为主的方法，将来自不同实验室的单克隆抗体所识别的同一分化抗原称为分化群（CD）。黏附分子：是以结构特点分为免疫球蛋白超家族、整合素家族、选择素家族等的、介导细胞间或细胞与细胞外基质间相互接触与结合的分子。CD 分子根据其主要表达细胞分为 T 细胞、B 细胞、NK 细胞、髓样细胞、黏附分子等 14 个组。",
        "解析：三者层次关系——白细胞分化抗原是一类膜标记分子的总称，其中以单克隆抗体归群鉴定的称 CD 分子，黏附分子则是按结构特点划分的一类介导细胞黏附的分子。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-short002",
    order: 26,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述黏附分子的分类和主要功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "黏附分子是介导细胞间或细胞与细胞外基质间相互接触与结合的分子，根据结构特点分为免疫球蛋白超家族、整合素家族、选择素家族、钙黏蛋白家族等四大类。主要功能：（1）参与免疫细胞之间的相互作用和活化，如 CD4、CD8 为 T 细胞活化辅助受体，CD28/CD80 或 CD86、CD2/CD58、LFA-1/ICAM-1 提供协同刺激信号；（2）参与炎症过程中白细胞与血管内皮细胞黏附；（3）参与淋巴细胞归巢；（4）参与细胞的发育、分化、附着和移动，钙黏蛋白及 NCAM、PECAM 参与细胞附着移动，整合素家族介导细胞与细胞外基质附着。",
        "解析：黏附分子通过受体-配体结合介导细胞黏附，是免疫细胞迁移、活化及免疫应答的物质基础。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-short003",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述选择素家族的组成与主要功能。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "选择素家族由 L-选择素（CD62L）、P-选择素（CD62P）和 E-选择素（CD62E）三个成员组成。它们识别的是一些寡糖基因，主要是唾液酸化的路易斯寡糖（sLex，即 CD15s）。选择素主要分布于白细胞、血小板/巨噬细胞、活化内皮细胞等。其功能是介导白细胞与内皮细胞的黏附，参与炎症过程，以及淋巴细胞归巢到外周淋巴结和派尔集合淋巴结等。",
        "解析：L-选择素组成性表达于白细胞，P-选择素贮存于血小板/巨噬细胞，E-选择素表达于活化内皮细胞，三者共同介导炎症渗出早期白细胞的滚动性初始黏附。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch07-adhesion-molecules-short004",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述白细胞分化抗原及其单克隆抗体的临床应用。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白细胞分化抗原及其单克隆抗体已在临床免疫学广泛应用：（1）阐明发病机制：CD4 分子胞膜外区第一结构域是 HIV 外壳蛋白 gp120 的识别部位，HIV 感染 CD4 阳性细胞后使 CD4 细胞数量明显下降、免疫功能降低甚至缺陷。（2）疾病诊断：检测 HIV 患者外周血 CD4/CD8 比值和 CD4 阳性细胞绝对数，对辅助诊断和判断病情有重要参考价值。（3）疾病预防和治疗：抗 CD3、抗 CD25 等单克隆抗体作为免疫抑制剂用于防治移植排斥反应；抗 CD20 单抗用于治疗 B 细胞淋巴瘤等。",
        "解析：单克隆抗体借助 CD 分子的独特性可定向阻断或靶向特定免疫细胞，用于疾病的发病机制研究、诊断及免疫干预治疗。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 配伍题：按契约不提取为独立记分题，bGroups 置空。 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...fillItems,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];