import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学免疫学学习指导与习题集（第3版）— 第13章 B淋巴细胞介导的特异性免疫应答 题库提取（等比取样）
 * 来源：《医学免疫学学习指导与习题集》第3版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：5 题
 * - 填空题（fill）：3 题
 * - 选择题（a1-single）：15 题（含 A2 病例题）
 * - 问答题（short-answer）：5 题
 * - 独立记分题合计：28 题（须等于本文件预算 28）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含名词解释 7、填空题 4、选择题 A1 型 55 + A2 型 10、B1 配伍题
 *   6 组 30 小题、问答题 6；按预算等比取材（B1 型按项目规约不纳入 a1-single，故未取）。
 *   A2 病例题保留全部临床细节。本章一般无多选/B 型独立记分题与提取相冲突；B1 配伍题
 *   按契约不提取为独立记分题。OCR 错字与双栏错序已按免疫学医学语义恢复（如 BCR-Igα/β、
 *   CD40L、IgM/IgD、生发中心暗区/明区等），未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "immunology-ch13-b-cell-response";
const locatorBase =
  "《医学免疫学学习指导与习题集》第3版 第13章 B淋巴细胞介导的特异性免疫应答 习题（核对PDF 第143–155页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），5 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-immunology-ch13-b-cell-response-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：体液免疫应答",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "体液免疫应答",
        "抗原进入机体后诱导相应的抗原特异性B细胞活化、增殖并最终分化为浆细胞，产生特异性抗体进入体液，发挥免疫效应；由于抗体存在于体液中，故此过程称为体液免疫应答。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：Ig类别转换",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Ig类别转换",
        "B细胞在IgV区基因重排完成后，其子代细胞均表达同一个IgV区基因，但IgC基因（恒定区基因）的表达在子代细胞受抗原刺激而成熟并增殖的过程中是可变的。每个B细胞开始时一般均表达IgM，免疫应答中先分泌IgM，随后可表达IgG、IgA或IgE，而其IgV区不发生改变，这种可变区相同而Ig类别发生变化的过程称为Ig的类别转换或同种型转换。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：体细胞高频突变",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "体细胞高频突变",
        "生发中心母细胞的轻链和重链V基因可发生高频率的点突变，称为体细胞高频突变。体细胞高频突变在抗原诱导下发生，在构成BCR多样性及体液免疫应答中抗体的多样性中有重要作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：初次应答",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "初次应答",
        "机体初次接受抗原刺激后，需经一定潜伏期才能在血清中出现抗体，该种抗体含量低、持续时间短，此现象称为初次应答。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：再次应答",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "再次应答",
        "初次应答中所形成的记忆性淋巴细胞再次接触相同抗原刺激后所产生的迅速、高效、持久的免疫应答，称为再次应答。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2 型选择题（统一映射为 a1-single），15 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-immunology-ch13-b-cell-response-a1001",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "高浓度时能多克隆激活B细胞的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["TD 抗原", "TI-1 抗原", "TI-2 抗原", "细菌胞壁抗原", "荚膜多糖抗原"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "TI-1 抗原",
        "TI-1 抗原又称 B 细胞丝裂原，高浓度时可通过非特异的丝裂原受体多克隆激活B细胞。原书 A1 答案第 5 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1002",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "成熟B细胞的膜表面免疫球蛋白（mIg）表达模式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["IgG", "IgE", "IgM", "IgA", "IgM、IgD"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "IgM、IgD",
        "成熟B细胞表面同时表达IgM和IgD，二者共享同一个V区（VH、VL相同），仅恒定区（CH、CL）不同；作为BCR的共受体成员。原书 A1 答案第 7 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1003",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "B细胞不具有的功能是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "抗原递呈功能",
      "分化为浆细胞产生抗体",
      "细胞因子分泌功能",
      "免疫记忆功能",
      "直接杀伤靶细胞功能",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "直接杀伤靶细胞功能",
        "B细胞具有抗原递呈、分化为浆细胞产生抗体、分泌细胞因子（如参与辅助）及免疫记忆等功能；直接杀伤靶细胞是细胞毒性T细胞（CTL）或NK细胞的功能，B细胞不具备。原书 A1 答案第 9 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1004",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于TD抗原引起的体液免疫，下列哪项是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "不需要APC参与",
      "浆细胞合成并分泌 Ig",
      "需要抗原刺激",
      "B细胞活化、增殖、分化浆细胞",
      "Ig 仅在细胞外发挥主要作用",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "不需要APC参与",
        "TD抗原引起的体液免疫需要APC摄取加工提呈抗原以辅助TD抗原特异性B细胞活化；故「不需要APC参与」错误。原书 A1 答案第 13 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1005",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞间相互作用不受MHC限制的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "树突状细胞与 Th 细胞",
      "Th 细胞与B细胞",
      "NK 细胞与靶细胞",
      "CTL 细胞与靶细胞",
      "巨噬细胞与Th 细胞",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "NK 细胞与靶细胞",
        "NK细胞识别杀伤靶细胞不受MHC限制（通过杀伤活化/抑制受体），而Th细胞与B细胞、APC的相互作用均受MHC II 类分子限制，CTL与靶细胞受MHC I 类分子限制。原书 A1 答案第 16 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1006",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "抗体产生过程中，下列说法错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "TI 抗原刺激B 细胞产生抗体需T细胞的辅助",
      "应答早期主要产生低亲和力的IgM",
      "Th细胞与B细胞的相互作用受 MHC 限制",
      "Ig 的类别转换需要 Th细胞的辅助",
      "浆细胞是产生抗体的细胞",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "TI 抗原刺激B 细胞产生抗体需T细胞的辅助",
        "TI 抗原（TI-1、TI-2）刺激B细胞产生抗体不需要Th细胞的辅助，故该说法错误；其余关于IgM、MHC限制、类别转换依赖Th及浆细胞产抗体均正确。原书 A1 答案第 20 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1007",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "初次应答中产生的抗体主要是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["IgA", "IgE", "IgG", "IgM", "IgD"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "IgM",
        "初次应答潜伏期较长，产生抗体量少、主要为低亲和力的IgM；再次应答主要产生高亲和力的IgG。原书 A1 答案第 23 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1008",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "B细胞区别于T细胞的特征是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "属于淋巴细胞",
      "可被 PWM 激活",
      "表达膜型Ig 识别抗原",
      "表达 CD3分子",
      "可分化记忆性细胞",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "表达膜型Ig 识别抗原",
        "B细胞通过表达膜型免疫球蛋白（mIg/BCR）识别抗原，这是其区别于T细胞（表达TCR、CD3）的特征。原书 A1 答案第 24 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1009",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "B细胞表面的抗原识别受体是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD21", "CD40", "BCR", "CD19", "Iga/IgB"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "BCR",
        "B细胞表面的抗原识别受体是BCR（由mIg和Igα/Igβ组成），可特异性识别并结合抗原；CD19、CD21、CD81是其信号转导共受体。原书 A1 答案第 25 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1010",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "发生类别转换前，B细胞表达",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["IgA", "IgG", "IgE", "IgM和IgD", "IgG 和IgD"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "IgM和IgD",
        "B细胞在发生Ig类别转换前表面表达IgM和IgD；类别转换发生后才转为分泌IgG、IgA或IgE等。原书 A1 答案第 43 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1011",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "发生子宫内感染时，新生儿血液中发现高滴度的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["IgD", "IgE", "IgM", "IgG", "IgA"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "IgM",
        "IgM分子量大不能通过胎盘，母体IgG可通过胎盘进入胎儿体内，因此新生儿血液中若出现高滴度IgM则提示发生了子宫内感染（胎儿自身产生的IgM）。原书 A2 答案第 56 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1012",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "寄生虫感染时水平显著升高的Ig是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["IgM", "IgG", "IgA", "IgD", "IgE"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "IgE",
        "寄生虫感染时机体产生以IgE为主的免疫应答，IgE升高参与抗寄生虫及I型超敏反应。原书 A2 答案第 57 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1013",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "能对肺炎链球菌脂多糖进行应答的细胞是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["生发中心细胞", "生发中心母细胞", "B1细胞", "浆细胞", "记忆性B 细胞"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "B1细胞",
        "肺炎球菌脂多糖为TI-2（类TI）抗原，主要应答细胞为B1细胞；B1细胞可直接识别细菌多糖类抗原并产生抗体。原书 A2 答案第 58 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1014",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "多发性骨髓瘤中出现异常的细胞主要是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["浆细胞", "CD4+T细胞", "CD8+T细胞", "B1细胞", "巨噬细胞"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "浆细胞",
        "多发性骨髓瘤是浆细胞恶性克隆增殖性肿瘤，以单克隆浆细胞异常增生及血中或尿中出现克隆性Ig或其轻链为特征。原书 A2 答案第 62 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-a1015",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "BCR识别抗原产生的活化信号传导是通过",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD40", "CD19", "CD21", "Iga 和IgB", "CD81"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Iga 和IgB",
        "BCR（mIg-Igα/Igβ复合物）识别抗原后，由Igα（CD79a）和Igβ（CD79b）胞浆区的ITAM传导活化信号入胞。原书 A1 答案第 33 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），3 道 */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-immunology-ch13-b-cell-response-fill001",
    order: 21,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "依据抗原种类和成分的不同，B细胞介导的免疫应答可分为___和___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对胸腺依赖抗原（TD抗原）的免疫应答；对胸腺非依赖抗原（TI抗原）的免疫应答",
        "按抗原种类和成分，B细胞介导的免疫应答分为对TD抗原的免疫应答和对TI抗原的免疫应答；TI抗原又分TI-1和TI-2。原书填空题第 1 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-fill002",
    order: 22,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "B细胞活化的第二信号又称___，由Th细胞与B细胞表面多对共刺激分子相互作用产生，其中最重要的是___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "共刺激信号；CD40/CD40L",
        "B细胞活化的第二信号又称共刺激信号，其中最重要的是Th细胞表面CD40L与B细胞表面CD40的结合。原书填空题第 2 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-fill003",
    order: 23,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "在B细胞对TI抗原的免疫应答中，成熟和不成熟的B细胞均可被___激活，诱导产生低亲和力的IgM；TI-2 抗原仅能激活___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "TI-1抗原；成熟的B细胞",
        "TI-1抗原（B细胞丝裂原）可激活成熟和不成熟的B细胞并诱导产生低亲和力IgM；TI-2抗原仅能激活成熟的B细胞（以B1细胞为主）。原书填空题第 4 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 问答题（short-answer），5 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-immunology-ch13-b-cell-response-short001",
    order: 24,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：Th细胞如何辅助B细胞的免疫应答？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Th细胞通过第二信号和细胞因子两方面辅助B细胞",
        "①Th细胞提供B细胞活化的第二信号：Th细胞表面的共刺激分子与B细胞表面相应分子结合，提供B细胞活化必需的第二信号，其中最重要的是T细胞表面CD40L与B细胞表面CD40的结合；②Th细胞产生细胞因子的作用：活化的Th细胞产生多种细胞因子（如IL-4、IL-5、IL-6等），可辅助B细胞的活化、增殖与分化。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-short002",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述B细胞在生发中心分化成熟的过程。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "生发中心B细胞经体细胞高频突变、亲和力成熟及类别转换，最终分化为浆细胞和记忆性B细胞",
        "在周围淋巴器官T细胞区激活的部分B细胞进入初级淋巴滤泡分裂增殖，形成生发中心（约在抗原刺激一周后）。生发中心分暗区（分裂增殖的生发中心母细胞紧密集聚，FDC很少）和明区（生发中心细胞聚集不甚紧密，但与众多FDC接触）。抗原抗体复合物结合于FDC树突上形成串珠状小体，B细胞内化后加工提呈给Th细胞；活化的Th通过CD40L-CD40向B细胞提供协同刺激信号并分泌细胞因子辅助B细胞。绝大多数B细胞凋亡，部分B细胞在抗原刺激和T细胞辅助下经历体细胞高频突变、Ig亲和力成熟及类别转换，最终形成浆细胞及记忆性B细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-short003",
    order: 26,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：体液免疫应答中的再次应答和初次应答有何不同？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "再次应答潜伏期短、抗体浓度高且维持时间长，主要产生高亲和力IgG",
        "①再次应答潜伏期短，大约为初次应答潜伏期的一半；②再次应答抗体浓度增加快、迅速到达平台期，平台高（有时可比初次应答高10倍以上）；③再次应答抗体维持时间长；④诱发再次应答所需抗原剂量小；⑤再次应答主要产生高亲和力的IgG抗体，而初次应答中主要产生低亲和力的IgM。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-short004",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述抗体多样性形成的机制。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗体多样性源自组合多样性、连接多样性和体细胞高频突变",
        "①组合多样性：胚系未重排IgV区基因中有众多V、D、J片段，重排时分别取用其中一个，可产生众多V区基因片段组合，加上轻重链组合（理论上IgV区基因片段组合约3.4×10^9）；②连接多样性：Ig各基因片段间连接往往不准确，有插入、替换或缺失核苷酸，产生新序列；③体细胞高频突变：发生在已完成V基因重排的成熟B细胞（抗原刺激后外周淋巴器官生发中心），不仅增加抗体多样性，还可导致抗体亲和力成熟。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-immunology-ch13-b-cell-response-short005",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：细胞免疫和体液免疫有何关系？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞免疫与体液免疫作用对象、效应方式不同，两者相互配合共同发挥作用",
        "细胞免疫作用对象为靶细胞（被病原体感染的体细胞、肿瘤细胞团和癌细胞等），由效应细胞毒T细胞接触靶细胞使其破裂；体液免疫作用对象为位于细胞外的抗原（如病原体和毒素），由效应B细胞（浆细胞）产生抗体与抗原结合发挥作用。二者相互配合，共同发挥免疫效应。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题（本书第13章存在，但按契约不提取为独立记分题），置空 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...fillItems,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];