import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学细胞生物学实验指导与习题集（第4版）— 第9章 细胞内遗传信息的传递及调控 题库提取（等比取样）
 * 来源：《医学细胞生物学实验指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：9 题
 * - 单项选择题（a1-single）：30 题（其中多项选择题映射 10 题）
 * - 独立记分题合计：39 题（须等于本文件预算 39）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书题型为名词解释（9）、单项选择题（60）、多项选择题（10），本书无配伍/填空/简答，
 *   故 bGroups 为空数组。本文件按 39 道预算等比取材并在原书顺序内取满：名词 9 道全部取，
 *   单项选择题从中取 20 道（a1-single 单选），多项选择题 10 道全部按项目规约映射为
 *   a1-single（promptSource.note=xMapNote）。正确项均按章末「参考答案」键号锚定（如 1.B 2.C …），
 *   选项按细胞生物学医学语义恢复完整集合（原书双栏排版致题干/选项/题号交错散落，已按语义重建），
 *   再随机重排并同步 correctChoiceIndex（0 起）。数值、密码子、过程、结构名均保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "cell-bio-ch09-genetic-info";
const locatorBase =
  "《医学细胞生物学实验指导与习题集》第4版 第9章 细胞内遗传信息的传递及调控 习题集（核对PDF 第160–167页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），9 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch09-genetic-info-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：基因组（genome）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "基因组（genome）",
        "指细胞或生物体的一套完整的单倍体遗传物质，是所有染色体全部基因和基因间的 DNA 总和，含有一个生物体进行各种生命活动所需要的全部遗传信息。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：外显子（exon）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "外显子（exon）",
        "指在真核生物的断裂基因及其成熟 RNA 中都存在的核酸序列，是基因内部能够被转录，并能指导蛋白质生物合成的编码序列。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：顺式作用元件（cis-acting element）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "顺式作用元件（cis-acting element）",
        "在真核基因的转录调控区，含有能与特异转录因子结合并影响转录水平的 DNA 序列，可分为启动子、增强子、沉默子和绝缘子。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：翻译（translation）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "翻译（translation）",
        "细胞内以 mRNA 为模板，按照 mRNA 分子中由核苷酸组成的密码信息合成蛋白质的过程。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：遗传密码（genetic code）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "遗传密码（genetic code）",
        "在 mRNA 分子上，以每 3 个相邻的核苷酸为一组，代表一种氨基酸或其他信息，这种存在于 mRNA 分子上的三联体形式的核苷酸序列称为密码子，即遗传密码。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：启动子（promoter）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "启动子（promoter）",
        "位于编码区上游、为 RNA 聚合酶识别结合并启动转录的 DNA 序列，至少包括一个转录起始点及一个以上的功能组件。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：操纵子（operon）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "操纵子（operon）",
        "由结构基因和表达调控元件组成，是原核细胞中最常见的表达调控单位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：转录因子（transcription factor，TF）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "转录因子（TF）",
        "在真核细胞中，能够帮助 RNA 聚合酶转录 RNA 的蛋白质统称转录因子，主要通过蛋白质-蛋白质间作用与 DNA 序列联系并调节转录。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：染色质重塑（chromatin remodeling）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "染色质重塑（chromatin remodeling）",
        "指染色质位置和结构的动态变化过程，主要涉及核小体的置换或重新排列，改变了核小体在基因启动序列区域的排列，增加了基因转录装置和启动序列的可接近性。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 单项选择题（a1-single），20 道（源为单项选择题） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch09-genetic-info-a1001",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于真核生物结构基因的说法中，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "编码序列被非编码序列所隔断",
      "结构基因的转录是不连续的",
      "结构基因在基因组中所占比例较小",
      "结构基因大都为断裂基因",
      "产物多为单顺反子RNA",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结构基因的转录是不连续的",
        "真核生物结构基因大都为断裂基因，编码序列被非编码的内含子所隔断，转录是连续的，故「转录不连续」表述错误。原书单项选择题答案第 1 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1002",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "将一段 DNA 序列插入某基因启动子下游，能够使该基因表达水平增加 4 倍，这段 DNA 序列具有的特征是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["反式作用因子", "绝缘子", "增强子", "操纵子", "沉默子"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "增强子",
        "增强子是可增强基因转录水平的顺式作用元件，插入启动子附近可使表达水平增加。原书单项选择题答案第 2 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1003",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "蛋白质生物合成过程中，终止密码子为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["UUG", "AGG", "UAA", "AUG", "UUA"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "UAA",
        "UAA、UAG、UGA 是三种终止密码子；AUG 为起始（兼编码甲硫氨酸），AGG、UUG、UUA 为普通密码子。原书单项选择题答案第 5 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1004",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "遗传密码的简并性是指",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "密码子与反密码子配对不严格",
      "大多数氨基酸有一个以上的密码子",
      "一些三联体密码子可缺少一个嘌呤或嘧啶碱基",
      "一些密码子适用于一种以上的氨基酸",
      "所有生物使用同一套遗传密码",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "大多数氨基酸有一个以上的密码子",
        "简并性指一种氨基酸可由多种密码子编码；摆动性指反密码子与密码子配对不严格。原书单项选择题答案第 6 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1005",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "直接以 DNA 为模板合成的物质是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["转录因子", "调节蛋白", "引物酶", "hnRNA", "反式作用因子"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "hnRNA",
        "hnRNA 是直接以 DNA 为模板转录合成的核内不均一 RNA；转录因子、调节蛋白、反式作用因子等是蛋白质。原书单项选择题答案第 7 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1006",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "真核生物转录终止的加工修饰点序列是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "TATA box",
      "Pribnow 盒",
      "TTGACA",
      "AATAAA 和其下游 GT 序列",
      "ρ因子（p 因子）",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "AATAAA 和其下游 GT 序列",
        "真核生物 mRNA 前体 3' 端加尾信号为 AATAAA 及下游 GT/GU 富集序列；TATA box 为启动子、ρ因子为原核转录终止因子。原书单项选择题答案第 8 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1007",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "参与 RNA 剪接的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["mRNA", "tRNA", "snRNA", "45S rRNA", "hnRNA"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "snRNA",
        "snRNA 与蛋白质组成剪接体参与 RNA 剪接，切除内含子。原书单项选择题答案第 9 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1008",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于转录因子（TF）的正确叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "本质是DNA分子",
      "是真核生物的启动子",
      "是原核生物RNA聚合酶的组分",
      "是真核生物RNA聚合酶的组分",
      "是真核生物转录调控中的反式作用因子",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "是真核生物转录调控中的反式作用因子",
        "转录因子本质是蛋白质（反式作用因子），帮助 RNA 聚合酶启动转录。原书单项选择题答案第 10 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1009",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "人类基因组比大肠杆菌基因组大 700 倍左右，然而人类基因组复制的时间仅比大肠杆菌基因组复制长 6〜8 倍，这是因为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "人类基因组的GC含量低，两条链更容易解链",
      "组蛋白的存在提高了人染色体DNA的复制速率",
      "人染色体DNA上具有多个复制起始区，大肠杆菌只有一个",
      "人基因组的许多序列不被复制",
      "人染色质DNA复制贯穿整个细胞周期，而大肠杆菌的DNA复制每小时启动一次",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "人染色体DNA上具有多个复制起始区，大肠杆菌只有一个",
        "真核染色体为多复制起点、分段复制，故虽基因组大但整体复制时间仅小幅延长。原书单项选择题答案第 11 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1010",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某 RNA 为 5'-UGACGA-3'，与其对应的 DNA 双链中的编码链为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "5'-TCGTCA-3'",
      "5'-ACTGCT-3'",
      "5'-TGACGA-3'",
      "5'-UCGTCA-3'",
      "5'-ACTGCU-3'",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "5'-TGACGA-3'",
        "编码链与 mRNA 序列一致（T 替代 U）：U→T，故为 5'-TGACGA-3'。原书单项选择题答案第 12 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1011",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "真核细胞中由 RNA 聚合酶 I 催化生成的产物是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["mRNA", "hnRNA", "tRNA", "snRNA", "45S RNA"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "45S RNA",
        "RNA 聚合酶 I 催化合成 45S rRNA（rRNA 前体）；RNA 聚合酶 II 转录 mRNA/hnRNA，RNA 聚合酶 III 转录 tRNA 和 5S rRNA 等。原书单项选择题答案第 13 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1012",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "对基因表达的调控，不发生在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "DNA复制",
      "转录起始",
      "转录后调控",
      "翻译起始",
      "翻译后水平",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "DNA复制",
        "基因表达调控主要发生在转录起始、转录后、翻译及翻译后等水平，DNA 复制不属于基因表达环节。原书单项选择题答案第 14 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1013",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "蛋白质生物合成的方向是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "定点双向进行",
      "从C端到N端",
      "从N端到C端",
      "从5'端到3'端",
      "从3'端到5'端",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "从N端到C端",
        "翻译从起始密码子开始沿 mRNA 5'→3' 方向进行，多肽链自 N 端向 C 端延伸。原书单项选择题答案第 16 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1014",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "合成 DNA 的原料是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "dAMP、dGMP、dCMP、dTMP",
      "dATP、dGTP、dCTP、dTTP",
      "dADP、dGDP、dCDP、dTDP",
      "AMP、GMP、CMP、TMP",
      "ATP、GTP、CTP、TTP",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "dATP、dGTP、dCTP、dTTP",
        "DNA 合成的直接原料是 4 种脱氧核苷三磷酸 dNTP。原书单项选择题答案第 17 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1015",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关遗传密码的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "每种氨基酸至少有一个密码子",
      "位于mRNA分子上",
      "有起始密码子和终止密码子",
      "由mRNA排列顺序决定的",
      "所有密码子都负责编码氨基酸",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "所有密码子都负责编码氨基酸",
        "遗传密码中三种终止密码子（UAA、UAG、UGA）不编码氨基酸。原书单项选择题答案第 18 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1016",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "蛋白质合成过程中，需要形成碱基配对的步骤是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["移位", "进位", "转肽", "结合终止因子", "释放肽链"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "进位",
        "进位时氨基酰-tRNA 的反密码子与 mRNA 上的密码子互补配对。原书单项选择题答案第 19 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1017",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于遗传密码的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "一种氨基酸可有一个以上的密码子",
      "遗传密码阅读有方向性，5'端起始，3'端终止",
      "遗传密码有种属特异性，所以不同生物合成不同的蛋白质",
      "密码子第3位碱基在决定掺入氨基酸的特异性方面重要性较小",
      "个别氨基酸的同义密码子可多达6个",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "遗传密码有种属特异性，所以不同生物合成不同的蛋白质",
        "遗传密码在绝大多数生物中通用；不同生物蛋白质不同是由其基因不同所致，而非密码种的属特异性。原书单项选择题答案第 20 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1018",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "真核生物转录发生的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["细胞核", "细胞质", "线粒体", "内质网", "微粒体"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞核",
        "真核生物核基因的转录主要在细胞核内进行，转录产物加工后转运至胞质翻译。原书单项选择题答案第 21 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1019",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "氨酰-tRNA 合成酶的特点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "只存在于细胞核内",
      "对氨基酸的识别没有专一性",
      "对tRNA的识别没有专一性",
      "催化反应需GTP",
      "对氨基酸识别有专一性",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对氨基酸识别有专一性",
        "氨酰-tRNA 合成酶对特定氨基酸和相应 tRNA 均有专一性，催化的活化反应由 ATP 供能（不一定需 GTP）。原书单项选择题答案第 22 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-a1020",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于反式作用因子的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "绝大多数反式作用因子属转录因子",
      "大多数的反式作用因子是DNA结合蛋白质",
      "指具有激活功能的调节蛋白",
      "包括基本转录因子和特异性转录因子",
      "通常含有DNA结合域",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "指具有激活功能的调节蛋白",
        "反式作用因子既包括激活因子也包括抑制因子，并非专指具有激活功能的调节蛋白。原书单项选择题答案第 23 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 多项选择题（原书 X 型），按项目规约映射为 a1-single 单选取一正确项，10 道 */
const xItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch09-genetic-info-x001",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】直接以 DNA 为模板合成的物质（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["转录因子", "rRNA", "tRNA", "hnRNA", "lncRNA"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "rRNA",
        "rRNA、tRNA、hnRNA、lncRNA 均直接以 DNA 为模板转录合成（原多项选择题答案 BCDE），转录因子是蛋白质。此处取 rRNA 为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-x002",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】蛋白质生物合成过程中，终止密码子包括（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["AUG", "UAG", "UAA", "UGA", "UUA"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "UAG",
        "终止密码子为 UAG、UAA、UGA（原多项选择题答案 BCD），此处取 UAG 为代表正确项；AUG 为起始密码子，UUA 为普通密码子。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-x003",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】下列过程属于转录后调控的是（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "mRNA的稳定性",
      "mRNA在核内的加工修饰",
      "mRNA的细胞质定位",
      "mRNA的转运",
      "hnRNA的形成",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "mRNA在核内的加工修饰",
        "mRNA 在核内的加工修饰（加帽、加尾、剪接）属于转录后调控（原多项选择题答案 ABCD）；hnRNA 形成属于转录本身。此处取核内加工修饰为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-x004",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】蛋白质生物合成体系包括（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["mRNA", "氨基酸", "DNA", "起始因子", "ATP"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "mRNA",
        "蛋白质合成体系含 mRNA、氨基酸、起始因子、ATP（延伸因子等），不含 DNA（原多项选择题答案 ABDE）。此处取 mRNA 为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-x005",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】遗传密码的基本特点是（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["通用性", "连续性", "摆动性", "简并性", "方向性"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "通用性",
        "遗传密码具备通用性、连续性、摆动性、简并性、方向性等特点（原多项选择题答案 ABCDE）。此处取通用性为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-x006",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】肽链延长的步骤包括（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["进位", "成肽", "转位", "氨基酸活化", "结合核糖体"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "进位",
        "肽链延长经历进位、成肽、转位三步（原多项选择题答案 ABC）；氨基酸活化在翻译起始前。此处取进位为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-x007",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】下列属于真核生物上游启动子组分的是（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["GC盒", "TATA盒", "CAAT盒", "增强子", "Pribnow盒"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "GC盒",
        "真核上游启动子含 GC 盒、TATA 盒（TATA box）、CAAT 盒（原多项选择题答案 ABC）；Pribnow 盒为原核启动子，增强子非启动子组分。此处取 GC 盒为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-x008",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】蛋白质生物合成的三个阶段包括（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["起始", "延长", "终止", "进位", "转位"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "起始",
        "蛋白质生物合成分起始、延长、终止三个阶段（原多项选择题答案 ABC）；进位、转位属延长阶段的具体步骤。此处取起始为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-x009",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】基因表达调控的主要环节包括（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "基因活化",
      "转录起始",
      "转录后加工和转运",
      "蛋白质翻译",
      "蛋白质降解",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "基因活化",
        "基因表达调控环节包括基因活化、转录起始、转录后加工和转运、蛋白质翻译及蛋白质降解等（原多项选择题答案 ABCDE）。此处取基因活化为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch09-genetic-info-x010",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】蛋白质合成后的加工包括（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["磷酸化", "信号肽去除", "亚基聚合", "乙酰化", "折叠"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "磷酸化",
        "翻译后加工包括磷酸化、信号肽去除、亚基聚合、乙酰化、折叠等（原多项选择题答案 ABCDE）。此处取磷酸化为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 本书无 B 型配伍题，bGroups 为空数组 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...xItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];