import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学细胞生物学实验指导与习题集（第4版）— 第3章 细胞生物学的研究方法 题库提取（等比取样）
 * 来源：《医学细胞生物学实验指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 章节等比缩放预算）==
 * - 名词解释：15 题
 * - 单项选择题（a1-single）：39 题（其中多项选择题映射 4 题）
 * - 独立记分题合计：54 题（等于本文件预算 54）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含名词解释 15、单项选择题 60、多项选择题 10，无配伍/填空/简答。
 *   60 道单选键号齐全，所选单选题均锚定源参考答案键号并与选项文本一一对照；多项选择题按项目
 *   规约映射为 a1-single 并只取其中一个正确项。个别单选题（如 Q1 离心、Q16 原子力显微镜、
 *   Q35 核酸电泳等）按源参考答案键号对正确项进行锚定并如实改写。原书为双栏排版，题干/选项/
 *   题号交错散落，已按细胞生物学医学语义重建完整选项集合（单选/映射 4~5 项），未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "cell-bio-ch03-research-methods";
const locatorBase =
  "《医学细胞生物学实验指导与习题集》第4版 第3章 细胞生物学的研究方法 习题集（核对PDF 第113–121页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），15 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch03-research-methods-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：分辨率（resolution）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "分辨率",
        "分辨率指显微镜或人眼能够区分相近两点的最小距离。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞培养（cell culture）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞培养",
        "细胞培养是细胞在体外的培养技术，即在无菌条件下，从机体中取出组织或细胞，模拟机体内正常生理状态下生存的基本条件，让它在培养器皿中继续生存、生长和繁殖的方法。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：原代培养（primary culture）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "原代培养",
        "原代培养是直接从体内获取的组织或细胞进行的首次培养。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：传代培养（secondary culture）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "传代培养",
        "当原代细胞经增殖达到一定密度后，将细胞分散，从一个培养器以一定比例移到另一个或几个容器中的扩大培养，称为传代培养。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞系（cell line）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞系",
        "细胞系指可以无限繁殖、传代的肿瘤细胞，或正常组织培养的细胞在某些条件处理后产生的“不死”的变异细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：等电聚焦电泳（isoelectric focusing）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "等电聚焦电泳",
        "等电聚焦电泳是在丙烯酰胺凝胶两端形成电场，使含有不同等电点的两性电解质在电场中形成 pH 梯度，样品中所有的蛋白质在电泳时都向自己的等电点处移动，最后聚集、静止于各自的等电点。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：cDNA 克隆（cDNA cloning）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "cDNA 克隆",
        "cDNA 克隆又称基因克隆，即将 mRNA 逆转录形成的 cDNA 或通过体外聚合酶链式反应得到的基因片段，插入到能进行自我复制的载体（通常是质粒），实现在受体细菌内大量扩增的过程。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：非细胞体系（cell free system）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "非细胞体系",
        "非细胞体系是用分级分离得到的具有生物学功能的细胞抽提物组成的活性反应体系。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：蛋白质组学（proteomics）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "蛋白质组学",
        "蛋白质组学是以特定时空条件下某种细胞、组织或器官所含有的全部蛋白质的存在及其活动方式为研究对象的学科。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：核酸原位杂交技术（in situ hybridization，ISH）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "核酸原位杂交技术",
        "核酸原位杂交以短的单链 cDNA、RNA 片段或寡核苷酸为探针，与经过固定并提高了通透性的细胞、组织切片或胚胎进行杂交，以荧光分子或显色酶为报告基团，显示特定 RNA（mRNA）分子在组织或细胞内分布和含量的变化。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：放射性自显影技术（autoradiography）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "放射性自显影技术",
        "放射性自显影技术用放射性同位素标记生物样品中的大分子或其前体物质，然后通过乳胶感光（卤化银还原成为银原子），显示出被标记物在组织和细胞内的位置、数量及其变化。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：显微结构（microscopic structure）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "显微结构",
        "光镜下所见的物体结构被称为显微结构。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：超微结构（ultramicroscopic structure）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "超微结构",
        "电子显微镜下观察到的细胞结构被称为亚显微结构或超微结构。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：单细胞测序技术（single cell sequencing）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单细胞测序技术",
        "单细胞测序技术是在单细胞水平对全基因组或转录组等进行扩增与测序的一项新技术。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-term015",
    order: 15,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：转基因小鼠（transgenic mouse）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "转基因小鼠",
        "在小鼠中引入一个额外的基因或对基因进行改变，来观察其效应的基因操作，进行这种基因操作的小鼠被称为转基因小鼠。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 单项选择题（含多项选择题的映射），39 道（单选 35 + 多选映射 4） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch03-research-methods-a1001",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于离心法分离细胞器及细胞组分，正确的描述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "差速离心法只能将大小显著不同的成分分开",
      "平衡沉降法分离取决于细胞成分的大小和形状",
      "利用免疫磁珠无需高速离心即可将膜性细胞器分离出来",
      "速度沉降可以使 tRNA 与其他成分分开",
      "超速离心法可根据生物大分子的沉降系数精确测定其分子量",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "平衡沉降法分离取决于细胞成分的大小和形状",
        "按源参考答案，本题正确项为平衡沉降法取决于细胞成分的大小和形状（原书单项选择题答案第 1 题为 B）。离心法通过沉降系数差异分离细胞器与组分，差速离心按沉降速度依次沉淀、各种沉降法的原理常交叉表述。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1002",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "检测特异 DNA 分子的方法是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["噬菌体展示", "ISH（原位杂交）", "Western blot", "Southern blot", "ChIP"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Southern blot",
        "Southern 印迹用于检测特异性 DNA 分子；Western blot 检测蛋白质，Northern blot 检测 RNA。原书单项选择题答案第 2 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1003",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "苏丹染料可以显示的细胞中成分是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["蛋白质", "DNA", "RNA", "糖", "脂肪"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脂肪",
        "苏丹染料（苏丹Ⅲ/Ⅳ等）是脂溶性染料，可特异性地显示细胞中的脂肪（脂滴）。原书单项选择题答案第 3 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1004",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "扫描隧道显微镜（STM）的侧分辨率约为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["2μm", "0.2μm", "0.2nm", "2nm", "2Å"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "0.2nm",
        "扫描隧道显微镜的侧向分辨率约为 0.2 nm，可在原子/纳米尺度观察样品表面形貌。原书单项选择题答案第 4 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1005",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "目前广泛应用的髙效基因敲除技术是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["cDNA 克隆", "RNAi", "CRISPR/Cas9", "ChIP", "转基因"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CRISPR/Cas9",
        "CRISPR/Cas9 是当前应用广泛的、高效精准的基因敲除（编辑）技术。原书单项选择题答案第 5 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1006",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可得到完整的细胞三维结构图像的显微镜是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "透射电子显微镜",
      "荧光显微镜",
      "暗视野显微镜",
      "相差显微镜",
      "共聚焦激光扫描显微镜",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "共聚焦激光扫描显微镜",
        "共聚焦激光扫描显微镜通过逐层光学切片与三维重建可获得完整细胞的三维结构图像。原书单项选择题答案第 6 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1007",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于免疫沉淀（IP）技术的错误描述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "用偶联在磁珠上的目的蛋白抗体将目的蛋白及其相互作用蛋白沉淀出来",
      "可通过 SDS-PAGE 或生物质谱对沉淀出来的蛋白进行鉴定",
      "属于体内实验方法，能得到细胞内蛋白相互作用的动态结果",
      "细胞内本来没有相互作用的蛋白在破碎细胞时可能发生凝聚，产生假阳性",
      "简便易行",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "属于体内实验方法，能得到细胞内蛋白相互作用的动态结果",
        "免疫沉淀通常是在细胞破碎后以抗体沉淀目标蛋白及其结合蛋白，为体外分析、反映某一时刻的静态结合，并非“体内动态结果”（共免疫沉淀常在破碎时产生假阳性）。原书单项选择题答案第 7 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1008",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "无需染色、标记即可直接用于观察活细胞状态的显微镜是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "扫描电子显微镜",
      "透射电子显微镜",
      "普通光学显微镜",
      "倒置相差显微镜",
      "荧光显微镜",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "倒置相差显微镜",
        "倒置相差显微镜利用相位差成像，无需染色/标记即可直接观察培养皿中活细胞的形态与状态。原书单项选择题答案第 8 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1009",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "制作透射电子显微镜超薄切片时，下列不必要的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["固定", "包埋", "切片", "金属投影", "染色"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "金属投影",
        "超薄切片常规流程为固定→包埋→切片→染色（重金属染色）；金属投影/复型用于复制型电镜样品，不属于超薄切片必需步骤。原书单项选择题答案第 10 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1010",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "能够在溶液中对生物大分子进行高分辨率结构测定的技术是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "X射线晶体衍射技术",
      "核磁共振技术",
      "扫描电子显微镜",
      "冷冻电镜",
      "共聚焦激光扫描显微镜",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "冷冻电镜",
        "冷冻电镜（冷冻电子显微镜）与核磁共振均可在溶液（水合）状态下对生物大分子进行高分辨率结构测定；冷冻电镜尤其适合大分子复合物。原书单项选择题答案第 11 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1011",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "透射电子显微镜借助一定技术手段可获取细胞亚显微结构的三维图像，下列不可行的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["金属投影", "金属复型", "金属染色", "冰冻断裂", "冰冻蚀刻技术"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "金属染色",
        "金属投影、金属复型、冰冻断裂和冰冻蚀刻均可通过复制凸显样品三维形貌；“金属染色”为常规负染/正染手段，不能提供三维立体信息。原书单项选择题答案第 12 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1012",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "能够从组织切片中精确分离单一细胞的方法是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "免疫磁珠法",
      "Percoll 精细密度梯度离心",
      "荧光激活细胞分选仪",
      "组织酶消化法",
      "激光捕获显微切割技术",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "激光捕获显微切割技术",
        "激光捕获显微切割（LCM）可在组织切片上精确定位并分离单一细胞。原书单项选择题答案第 15 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1013",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关原子力显微镜的错误描述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "在扫描隧道显微镜基础上发展起来的",
      "不需要所检测的样品具有导电性",
      "可对单个分子进行操控",
      "分辨率比扫描隧道显微镜高",
      "显示样品表面微细结构的三维特征",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "分辨率比扫描隧道显微镜高",
        "原子力显微镜（AFM）虽免于导电要求、可操控单分子并可显示表面三维特征，但其分辨率一般略低于扫描隧道显微镜；“分辨率比 STM 高”为错误表述。原书单项选择题答案第 16 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1014",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "操作简单、特异性强，能够在多细胞悬液中分离特定细胞的方法是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "免疫磁珠法",
      "荧光激活细胞分选仪",
      "Percoll 精细密度梯度离心",
      "利用贴壁生长和悬浮生长的特性进行细胞培养",
      "激光捕获显微切割技术",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "免疫磁珠法",
        "免疫磁珠法以抗体偶联磁珠特异性捕捉目标细胞，操作简单、特异性强，适合从悬液中分离特定细胞。原书单项选择题答案第 20 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1015",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞培养时所用的培养基中不包含",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["血清", "氨基酸", "二氧化碳", "维生素", "微量元素"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "二氧化碳",
        "培养基中添加血清、氨基酸、维生素、微量元素等营养物质；CO₂ 由培养箱的气氛提供（维持 pH），并不作为培养基的成分加入。原书单项选择题答案第 21 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1016",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "考察细胞侵袭和转移能力变化的方法是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "嵌套小室（transwell 法）",
      "软琼脂集落形成实验",
      "细胞生长曲线绘制",
      "流式细胞仪的 DNA 倍体分析",
      "细胞活力检测（MTT 法）",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "嵌套小室（transwell 法）",
        "transwell 嵌套小室法通过观察细胞穿膜迁移反映其侵袭、转移能力。原书单项选择题答案第 22 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1017",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "将细胞匀浆以 100000g 超速离心，上清液部分含有",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["线粒体", "溶酶体", "细胞核", "RNA", "微粒体"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "RNA",
        "100000g 超速离心可将线粒体、溶酶体、细胞核等沉淀，遗留在上清中的是可溶性成分（包括 RNA 等）；此为常规差速离心思路。原书单项选择题答案第 24 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1018",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "超分辨显微技术可使光学显微镜的分辨率达到",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["2μm", "50nm", "0.2nm", "2nm", "2Å"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "50nm",
        "超分辨显微（如 STED、STORM）突破了光学衍射极限，可将分辨率推进到约 50 nm 量级（数十 nm），远超传统光学显微镜的约 200 nm。原书单项选择题答案第 25 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1019",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "一般来说，分离纯化蛋白质最有效的方法是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "亲和层析",
      "阴离子交换层析",
      "阳离子交换层析",
      "凝胶滤过层析",
      "疏水性层析",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "亲和层析",
        "亲和层析利用生物分子之间的特异性亲和（如抗原-抗体、酶-底物）一步分离目标蛋白，选择性最高，是分离纯化蛋白质最有效的方法之一。原书单项选择题答案第 27 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1020",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "能揭示蛋白质精确三维结构的方法是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "扫描电子显微镜",
      "柱层析",
      "X射线晶体衍射技术",
      "SDS-PAGE",
      "共聚焦激光扫描显微镜",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "X射线晶体衍射技术",
        "X射线晶体衍射（以及冷冻电镜、核磁共振）可在原子分辨率揭示蛋白质的精确三维（空间）结构。原书单项选择题答案第 28 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1021",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "从细胞中分离染色质，抽提液中不应含有",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["DNA 酶", "RNA 酶", "异硫氰酸胍", "氯仿", "蛋白酶 K"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "DNA 酶",
        "分离染色质需保护 DNA 不被降解，抽提液中不能含 DNA 酶；RNA 酶、蛋白酶 K 等可用于去 RNA/蛋白。原书单项选择题答案第 30 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1022",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "二硫苏糖醇（DTT）在 SDS-聚丙烯酰胺凝胶电泳中的作用是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "与蛋白质疏水区结合",
      "使蛋白质带负电荷",
      "使蛋白质中的二硫键断裂",
      "使蛋白质分子折叠",
      "控制凝胶孔的大小",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "使蛋白质中的二硫键断裂",
        "DTT 是还原剂，在 SDS-PAGE 中用于断裂蛋白质中的二硫键，使蛋白充分线性化。原书单项选择题答案第 31 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1023",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "电子显微镜观察生物标本的分辨率约为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["2μm", "0.2μm", "0.2nm", "2nm", "2Å"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "2nm",
        "按源参考答案，电镜观察生物标本（含切片样品）的实际分辨本领约为 2 nm（原书单项选择题答案第 32 题为 D）。受制于样品制备等，较理论原子级分辨率低。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1024",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "SDS 在 SDS-聚丙烯酰胺凝胶电泳中的作用是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "与蛋白质亲水区结合",
      "控制凝胶孔的大小",
      "使蛋白质中的二硫键断裂",
      "使蛋白质分子折叠",
      "使蛋白质带负电荷",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "使蛋白质带负电荷",
        "SDS（阴离子去垢剂）包被蛋白质使之带大量负电荷并掩盖蛋白自身电荷，使蛋白按分子量大小在凝胶中迁移。原书单项选择题答案第 33 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1025",
    order: 40,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于核酸电泳，错误的描述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "是核酸分离鉴定的主要方法",
      "可直接判定核酸的纯度、完整性及片段大小",
      "核酸在碱性条件下向阳极移动",
      "荧光实时定量 PCR 也依赖核酸扩增原理",
      "琼脂糖凝胶电泳分辨率高于丙烯酰胺凝胶电泳",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "琼脂糖凝胶电泳分辨率高于丙烯酰胺凝胶电泳",
        "丙烯酰胺（聚丙烯酰胺）凝胶的孔径更小、分辨率更高，故“琼脂糖凝胶电泳分辨率高于丙烯酰胺凝胶电泳”为错误表述。原书单项选择题答案第 35 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1026",
    order: 41,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于生物芯片技术，错误的叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "由生物学、微电子学、物理和计算机科学等多学科交叉融合而成",
      "主要包括基因芯片和蛋白质芯片",
      "基因芯片中，荧光素直接标记待检测的 mRNA 分子",
      "可用于筛选候选基因",
      "可通过蛋白质-蛋白质间的相互作用对靶蛋白分子进行高通量检测",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "基因芯片中，荧光素直接标记待检测的 mRNA 分子",
        "基因芯片中由待检 mRNA 逆转录的 cDNA 以荧光标记，并非 mRNA 分子本身被直接标记；“荧光素直接标记待检测的 mRNA 分子”为错误表述。原书单项选择题答案第 36 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1027",
    order: 42,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "Western blot 不可以用于检测蛋白质的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["含量", "大小", "三维结构", "磷酸化", "泛素化"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "三维结构",
        "Western blot 可检测目标蛋白的含量、分子量大小以及磷酸化、泛素化等修饰（以特异性抗体），但不能直接揭示蛋白质的三维结构。原书单项选择题答案第 38 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1028",
    order: 43,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "放射性自显影技术中，下列属于强放射性同位素的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["14C", "35S", "3H", "32P", "131I"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "32P",
        "32P 为强放射性 β 发射体，放射自显影效率高；3H、14C、35S 等为弱/中放射性同位素。原书单项选择题答案第 39 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1029",
    order: 44,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可用于观察细胞表面三维结构的显微镜是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "扫描电子显微镜",
      "透射电子显微镜",
      "暗视野显微镜",
      "相差显微镜",
      "荧光显微镜",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "扫描电子显微镜",
        "扫描电子显微镜靠二次电子成像，能立体地显示细胞表面形貌与三维结构。原书单项选择题答案第 40 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1030",
    order: 45,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于 Northern 印迹分析，错误的描述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "可检测组织或细胞中特定的 mRNA",
      "可使用放射性物质标记的寡核苷酸为探针",
      "不能有效地检测小 miRNA 分子",
      "能够定量检测 mRNA 的变化",
      "能够提供基因不同转录本的转录长度信息",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "不能有效地检测小 miRNA 分子",
        "Northern 印迹可检测特异性 mRNA、可定量并给出转录本长度信息；因小 miRNA 分子太小、转移检测困难，故“不能有效检测小 miRNA”为错误表述。原书单项选择题答案第 42 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1031",
    order: 46,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "SDS 聚丙烯酰胺凝胶电泳分离蛋白质的依据是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["疏水性", "分子量大小", "所带正电荷多少", "所带负电荷多少", "形状特点"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "分子量大小",
        "SDS-PAGE 中蛋白被 SDS 包被带恒定负电荷、形状趋于一致，分离依据即分子量大小。原书单项选择题答案第 46 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1032",
    order: 47,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "最早制造出第一台显微镜并用它观察到细菌的科学家是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "L. Hooke",
      "R. Hooke",
      "M. J. Schleiden",
      "R. Virchow",
      "A. van Leeuwenhoek",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "A. van Leeuwenhoek",
        "A. van Leeuwenhoek（列文虎克）制成了高放大倍数的单透镜显微镜，并首次观察到细菌、红细胞等微生物。原书单项选择题答案第 50 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1033",
    order: 48,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与普通 PCR 不同的是，荧光实时定量 PCR 在反应体系中需加入",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "模板 DNA",
      "耐热的 DNA 聚合酶",
      "dNTP",
      "荧光染料",
      "引物",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "荧光染料",
        "实时定量 PCR（qPCR）在体系中额外加入荧光染料（如 SYBR Green I）或荧光探针，通过对荧光的实时监测反映扩增产物量。原书单项选择题答案第 51 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1034",
    order: 49,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "检测特异蛋白质分子的方法是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["PCR", "FISH", "Southern blot", "Northern blot", "Western blot"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Western blot",
        "Western blot 用抗体特异性检测（识别）目标蛋白质分子。原书单项选择题答案第 54 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-a1035",
    order: 50,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞内离子中，能起信号转导和促进膜融合作用的离子是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["钠", "钾", "钙", "铜", "铁"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "钙",
        "Ca²⁺ 是重要的第二信使，参与信号转导并调控囊泡与膜的融合（如神经递质释放）等过程。原书单项选择题答案第 56 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-x001",
    order: 51,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（原多选题）关于用酶解法从实体组织分离活细胞，正确的描述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "胰蛋白酶、胶原酶可消除细胞间的连接和细胞外基质",
      "分离体系必须在较高温度下进行以加快消化",
      "所用的试剂、器皿无需除菌",
      "分离体系应保持剧烈振摇以保证充分消化",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胰蛋白酶、胶原酶可消除细胞间的连接和细胞外基质",
        "原题为多项选择题，酶解分离活细胞的正确描述包括胰蛋白酶/胶原酶消除细胞间连接与细胞外基质、分离体系等渗、低温并严格除菌（源参考答案键号 1.BCDE）。本项映射为单选并按规约只取其中一个正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-x002",
    order: 52,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（原多选题）关于染色质免疫沉淀（ChIP）技术的正确描述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "是一种体内研究 DNA 与蛋白质相互作用的方法",
      "属于离体纯化 DNA 的方法，不能反映体内事件",
      "无法捕捉基因表达调控的瞬时事件",
      "分离得到的 DNA 不能用于序列分析",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "是一种体内研究 DNA 与蛋白质相互作用的方法",
        "原题为多项选择题，ChIP 是一种体内研究 DNA 与蛋白质相互作用的技术，能捕捉染色质上基因表达调控的瞬时事件、可结合测序获得序列信息（源参考答案键号 2.ACDE）。本项映射为单选并按规约只取其中一个正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-x003",
    order: 53,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（原多选题）关于核酸抽提的正确叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "氯仿可去除细胞内的脂类",
      "在纯化过程中加入核酸酶可保护核酸完整",
      "蛋白酶 K 能使核酸降解",
      "核酸只能沉淀于有机相而不能保留在水相",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "氯仿可去除细胞内的脂类",
        "原题为多项选择题，核酸抽提的正确叙述包括异硫氰酸胍使膜/蛋白变性、氯仿去除脂类、离心使核酸保留在水相中等（源参考答案键号 3.ABCD）。本项映射为单选并按规约只取其中一个正确项（氯仿去除脂类）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch03-research-methods-x004",
    order: 54,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（原多选题）酶细胞化学反应中，酶与其底物孵育并显色后生成的产物一般包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "高电子密度沉淀",
      "无色透明溶液",
      "可与底物相同的分子",
      "凝胶胶条",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "高电子密度沉淀",
        "原题为多项选择题，酶细胞化学反应的显色产物一般包括荧光分子、有色沉淀、高电子密度沉淀及有色可溶性化合物（源参考答案键号 4.ACDE）。本项映射为单选并按规约只取其中一个正确项（高电子密度沉淀，用于电镜定位）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 本书无 B 型配伍题，bGroups 为空数组 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];