import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学细胞生物学实验指导与习题集（第4版）— 第16章 细胞衰老与细胞死亡 题库提取（等比取样）
 * 来源：《医学细胞生物学实验指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：8 题
 * - 单项选择题（a1-single）：16 题（其中多项选择题映射 5 题）
 * - 独立记分题合计：29 题（须等于本文件预算 29）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依次含名词解释 11、单项选择题 40、多项选择题 10；本书无配伍/填空/简答，故
 *   按预算等比取材并在原书顺序内取满 29 道（名词 8 + 单选 16 + 多选映射 5）。多选映射按项目规约
 *   改为单选句、取其中一个正确项，promptSource.note 用 xMapNote。正确项均对照章末参考答案键号
 *   （单选 1.D…40.D；多选 1.ABDE…10.BCE）锚定；选项在原选项集合内随机重排并同步
 *   correctChoiceIndex（0 起）。双栏错序已按细胞衰老与死亡医学语义恢复，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "cell-bio-ch16-senescence-death";
const locatorBase =
  "《医学细胞生物学实验指导与习题集》第4版 第16章 细胞衰老与细胞死亡 习题集（核对PDF 第209–214页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），8 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch16-senescence-death-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞衰老",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞衰老",
        "细胞衰老（cell senescence）指随着时间的推移，细胞的增殖能力和生理功能逐渐发生衰退以及细胞形态发生改变，并趋向死亡的现象。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：复制性衰老",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "复制性衰老",
        "复制性衰老（replicative senescence）指端粒缩短诱发的细胞衰老，即随着细胞不断分裂、端粒逐渐缩短而导致的增殖能力丧失。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：Hayflick界限",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Hayflick界限",
        "Hayflick界限（Hayflick life span）由Hayflick等发现并提出，主要指体外培养的细胞具有增殖分裂的极限，且细胞的分裂能力与物种的寿命、个体的年龄等有关。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞凋亡",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞凋亡",
        "细胞凋亡（apoptosis）是细胞在一定的生理或病理条件下，细胞内死亡级联反应被触发所致的生理或病理性、主动性的死亡过程。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：凋亡小体",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "凋亡小体",
        "凋亡小体（apoptotic body）是细胞凋亡时，由完整的细胞膜包被形成的、内含细胞器、核碎片等内容物的囊状小体。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞坏死",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞坏死",
        "细胞坏死（necrosis）指在外来致病因子作用下，细胞生命活动被强行终止所致的病理性、被动性的死亡过程。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：失巢凋亡",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "失巢凋亡",
        "失巢凋亡（anoikis）是因细胞与细胞外基质和其他细胞脱离接触而诱发的细胞程序死亡。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞自噬",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞自噬",
        "细胞自噬（autophagy）是通过溶酶体与双层膜包裹的细胞自身物质融合，从而降解细胞自身物质的过程。自噬参与蛋白质、脂质、受损细胞器和蛋白聚集体的降解。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 单项选择题（a1-single），16 道（含多选映射 5 道，置于数组末尾） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch16-senescence-death-a1001",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列细胞中，能持续分裂增殖的细胞是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["神经元", "唾液腺细胞", "肝细胞", "肌细胞", "基底细胞"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "基底细胞",
        "表皮基底细胞（基底层细胞）可不断分裂增殖以补充脱落的上皮细胞；神经元、肌细胞为终末分化不再分裂，唾液腺细胞、肝细胞为保留分裂潜能但通常不持续分裂的休眠细胞。原书单选答案第 4 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1002",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列是衰老的生物学标志的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "色素颗粒沉积减少",
      "线粒体数目增多",
      "端粒长度缩短",
      "血清中自由基数量减少",
      "免疫功能增强",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "端粒长度缩短",
        "端粒随分裂次数增加而缩短，是细胞（复制性）衰老的重要生物学标志；衰老细胞色素颗粒（脂褐素）沉积增多而非减少，线粒体数目趋于减少，自由基增多而非减少。原书单选答案第 5 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1003",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列不属于细胞凋亡特征的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "核DNA在核小体连接处断裂",
      "核膜断裂",
      "形成凋亡小体",
      "细胞破裂，释放内容物",
      "不引起炎症",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞破裂，释放内容物",
        "细胞破裂、内容物释放是细胞坏死的特征；细胞凋亡为程序性死亡，核DNA在核小体连接处断裂、核膜断裂、形成凋亡小体且一般不引起炎症。原书单选答案第 6 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1004",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "非选择性自噬中，蛋白质或细胞器被随机运送并被降解的区域是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["溶酶体", "线粒体", "细胞外", "过氧化物酶体", "胞质溶胶"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "溶酶体",
        "非选择性自噬中被双层膜包裹的蛋白质或细胞器随机运送至溶酶体并被降解。原书单选答案第 7 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1005",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "衰老细胞中会出现固缩的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["核仁", "染色质", "细胞膜", "脂褐质", "线粒体"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "染色质",
        "衰老细胞中染色质（核）常出现凝聚、固缩、碎裂等形态变化。原书单选答案第 8 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1006",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "被称为细胞凋亡抑制基因的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["bcl-2", "Bad", "P53", "Ice", "Fas"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "bcl-2",
        "bcl-2是经典的细胞凋亡（抑制）基因，其过度表达抑制凋亡；Bad、P53、Ice、Fas多为促进凋亡相关分子。原书单选答案第 10 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1007",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "caspase-3的激活将直接导致",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["细胞坏死", "细胞焦亡", "细胞衰老性死亡", "细胞凋亡", "细胞自噬"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞凋亡",
        "caspase-3（凋亡执行型半胱氨酸天冬氨酸蛋白酶）的激活是细胞凋亡执行阶段的关键事件，直接导致细胞凋亡。原书单选答案第 12 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1008",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞的衰老死亡与机体的衰老死亡是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["一个概念", "两个概念", "因果关系", "主次关系", "二者无关"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "两个概念",
        "细胞衰老死亡是细胞层面的现象，机体衰老死亡是个体层面的整体现象，二者是两个概念，既有联系又有区别。原书单选答案第 13 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1009",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在衰老细胞中增多的细胞器是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["细胞核", "线粒体", "内质网", "中心体", "溶酶体"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "溶酶体",
        "衰老细胞内溶酶体增多且异常，堆积大量未消化物形成的脂褐素；线粒体数目一般减少。原书单选答案第 15 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1010",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "Hayflick界限指",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "细胞最小分裂次数",
      "细胞最大分裂次数",
      "细胞最适分裂次数",
      "细胞停止分裂的最终时限",
      "细胞停止分裂的最佳时间",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞最大分裂次数",
        "Hayflick界限指体外培养细胞所能达到的最大增殖分裂次数，超过该界限细胞停止分裂而衰老。原书单选答案第 17 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1011",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "具有凋亡抑制作用的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["Bax", "Bak", "Bcl-2", "Bad", "Fas"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Bcl-2",
        "Bcl-2具有抑制细胞凋亡的作用；Bax、Bak、Bad为促凋亡蛋白，Fas为死亡受体。原书单选答案第 18 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1012",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "通常不分裂，但终生保留分裂能力的细胞是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["肝细胞", "骨髓细胞", "基底细胞", "神经细胞", "心肌细胞"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝细胞",
        "肝细胞通常不分裂（静止期），但受损等刺激可进入G1期恢复分裂，终生保留分裂增殖能力；神经元、心肌细胞为不再分裂的终末细胞。原书单选答案第 19 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1013",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞凋亡的特征是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "细胞以出芽方式形成凋亡小体",
      "DNA随机降解",
      "细胞器溶解",
      "引起炎症",
      "核增大",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞以出芽方式形成凋亡小体",
        "细胞凋亡典型特征包括膜出芽形成凋亡小体、核固缩碎裂、DNA在核小体连接处规律降解（不引起炎症）。原书单选答案第 20 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1014",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞凋亡时DNA片段长度的规律是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "100bp的整数倍",
      "200bp的整数倍",
      "300bp的整数倍",
      "400bp的整数倍",
      "500bp的整数倍",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "200bp的整数倍",
        "细胞凋亡时核酸内切酶在核小体连接处切割DNA，产生长度约为200bp整数的DNA片段，电泳呈梯状图谱。原书单选答案第 24 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1015",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列基因具有促进细胞存活作用的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["Bax", "ced-3", "c-myc", "ice", "bcl-2"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "bcl-2",
        "bcl-2编码抗凋亡蛋白，具有促进细胞存活的作用；Bax、ced-3、ice均为促凋亡相关因子。原书单选答案第 30 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-a1016",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "机体中寿命最长的细胞是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["神经元", "红细胞", "表皮细胞", "白细胞", "肝细胞"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "神经元",
        "神经元是机体中寿命最长的细胞之一，可存活终生、不再分裂。原书单选答案第 36 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-x001",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "程序性死亡细胞的染色质DNA降解特点是（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "发生在细胞凋亡的早期",
      "染色质片段大小是200bp的倍数",
      "电泳时呈现弥散样",
      "断裂部位多位于核小体间的连接部位",
      "DNA片段可以被细胞膜包围",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "染色质片段大小是200bp的倍数",
        "原书多选答案第 1 题为 ABDE（凋亡早期发生、片段为200bp倍数、断裂多位于核小体连接处、片段可被膜包围）。此处取其中一个正确项「片段为200bp的倍数」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-x002",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞衰老时，内膜系统发生的变化之一是（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "糙面内质网排列不规则",
      "光面内质网减少",
      "高尔基复合体碎裂",
      "溶酶体增加",
      "线粒体增加",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "糙面内质网排列不规则",
        "原书多选答案第 4 题为 ABCD（糙面内质网排列不规则、光面内质网减少、高尔基复合体碎裂、溶酶体增加）。此处取其中一个正确项「糙面内质网排列不规则」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-x003",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "促进细胞凋亡的蛋白之一是（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["P53", "Bcl-2", "Fas", "Bax", "Ced-3"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "P53",
        "原书多选答案第 6 题为 ACDE（P53、Fas、Bax、Ced-3均为促凋亡蛋白）。此处取其中一个正确项「P53」，P53在DNA损伤时诱导细胞凋亡。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-x004",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞自噬的发生过程包括（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "自噬前体的形成",
      "自噬体形成",
      "自噬体与溶酶体融合",
      "自噬内容物被降解",
      "自噬体溶解、消失",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "自噬前体的形成",
        "原书多选答案第 9 题为 ABCD（自噬前体形成、自噬体形成、自噬体与溶酶体融合、内容物被降解）。此处取其中一个正确项「自噬前体的形成」，为自噬起始步骤。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch16-senescence-death-x005",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "凋亡细胞的特点之一是（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "细胞膜破裂",
      "细胞膜保持完整",
      "被邻近的细胞吞噬",
      "常引起炎症",
      "不引起炎症",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞膜保持完整",
        "原书多选答案第 10 题为 BCE（细胞膜保持完整、被邻近细胞吞噬、不引起炎症）。此处取其中一个正确项「细胞膜保持完整」，凋亡过程膜完整、无内容物外泄。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B 型配伍题：本书无 B1/B2 型，置空数组 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];