import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学细胞生物学实验指导与习题集（第4版）— 第13章 细胞分裂与细胞周期 题库提取（等比取样）
 * 来源：《医学细胞生物学实验指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：8 题
 * - 单项选择题（a1-single）：30 题（其中多项选择题映射 5 题）
 * - 独立记分题合计：43 题（须等于本文件预算 43）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依次含名词解释 14、单项选择题 60、多项选择题 10；本书无配伍/填空/简答，故
 *   按预算等比取材并在原书顺序内取满 43 道（名词 8 + 单选 30 + 多选映射 5）。多选映射按项目规约
 *   改为单选句、取其中一个正确项，promptSource.note 用 xMapNote。正确项均对照章末参考答案键号
 *   （单选 1.E…60.B；多选 1.BCD…10.ABCDE）锚定；选项在原选项集合内随机重排并同步
 *   correctChoiceIndex（0 起）。部分题干因双栏错序在提取时为与参考答案对齐而补全为「错误的是/
 *   不属于」句式，内容按细胞生物学语义恢复，未捏造数值与机制。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "cell-bio-ch13-cell-cycle";
const locatorBase =
  "《医学细胞生物学实验指导与习题集》第4版 第13章 细胞分裂与细胞周期 习题集（核对PDF 第189–196页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），8 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch13-cell-cycle-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞分裂",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞分裂",
        "细胞分裂是细胞生命活动的重要特征之一，指一个亲代细胞形成两个子代细胞的过程。通过细胞分裂，亲代细胞的遗传物质和某些细胞组分可以相对均等地分配到两个子代细胞中，从而有效保证生物遗传的稳定性。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞周期",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞周期",
        "细胞从上次分裂结束到下次分裂结束所经历的规律性变化过程，称为一个细胞周期。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：有丝分裂",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "有丝分裂",
        "有丝分裂也称间接分裂，是高等真核生物体细胞分裂的主要方式。通过核分裂及胞质分裂两个过程，借助细胞骨架的重排，有丝分裂的细胞实现了染色体及胞质在子代细胞中的均等分配。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：减数分裂",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "减数分裂",
        "减数分裂是生殖细胞形成过程中的特殊有丝分裂过程，受DNA只复制一次而细胞连续分裂两次的机制制约，产生四个子代细胞，每个子代细胞中染色体数目比亲代细胞减少一半，成为仅具单倍体遗传物质的配子细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：联会",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "联会",
        "在第一次减数分裂前期I的偶线期，染色质进一步凝集，分别来自父母本、形态及大小相同的同源染色体相互靠近、配对的过程，称为联会。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞周期蛋白",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞周期蛋白",
        "细胞周期蛋白（cyclin）是真核细胞中的一类蛋白质，能随细胞周期进程周期性地出现（合成）及消失（降解）。Cyclin通过选择性地与Cdk结合形成复合物，通过介导Cdk的激活过程而参与细胞周期的调控。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞周期蛋白依赖性激酶（Cdk）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞周期蛋白依赖性激酶（Cdk）",
        "Cdk是一类必须与特定的细胞周期蛋白（cyclin）结合后才具有激酶活性的蛋白激酶，通过磷酸化多种细胞周期相关蛋白，在细胞周期调控中发挥关键核心作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：成熟促进因子（MPF）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "成熟促进因子（MPF）",
        "成熟促进因子又称有丝分裂促进因子，是由cyclin B和Cdk 1结合形成的蛋白激酶复合物，在促进细胞从G2期向M期转换的过程中起着关键作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 单项选择题（a1-single），30 道（含多选映射 5 道，置于数组末尾） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1001",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "同源染色体分离发生在减数分裂的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "第一次减数分裂前期",
      "第一次减数分裂中期",
      "第一次减数分裂后期",
      "第二次减数分裂中期",
      "第二次减数分裂后期",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第一次减数分裂后期",
        "同源染色体分离发生于第一次减数分裂（减数分裂Ⅰ）的后期（后期Ⅰ），此时同源染色体在纺锤丝牵引下彼此分开移向两极；第二次减数分裂后期分离的是姐妹染色单体。原书单选答案第 2 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1002",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞周期的长短主要取决于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["G0期", "G1期", "S期", "G2期", "M期"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "G1期",
        "细胞周期的长短主要取决于G1期（间期最长的阶段）的长短，不同细胞的G1期差异最大，S期、G2期和M期相对固定。原书单选答案第 4 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1003",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有丝分裂后期，姐妹染色单体分离的主要原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "星体的牵引",
      "细胞两极的距离增大",
      "着丝粒的分裂",
      "动粒微管的去组装",
      "染色体凝集程度的增加",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "着丝粒的分裂",
        "有丝分裂后期姐妹染色单体分离的直接原因是着丝粒分裂（断裂），使姐妹染色单体彻底分开，随后在动粒微管牵引下分别移向两极。原书单选答案第 5 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1004",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "Cdk1与Cyclin B结合，可促进细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "从G1期向S期的转变",
      "从S期向G2期的转变",
      "从G2期向M期的转变",
      "从M期向G1期的转变",
      "S期的启动",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "从G2期向M期的转变",
        "Cyclin B与Cdk1结合形成成熟促进因子（MPF），主要促进细胞从G2期向M期转变即进入有丝分裂。原书单选答案第 6 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1005",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与细胞分裂时染色体移动有关的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["中心体", "线粒体", "核糖体", "溶酶体", "过氧化物酶体"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中心体",
        "中心体通过生出星体和纺锤丝（微管）构成纺锤体，与分裂期染色体的移动密切相关；线粒体、核糖体、溶酶体、过氧化物酶体与染色体移动无直接关系。原书单选答案第 7 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1006",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "同源染色体重组发生在第一次减数分裂前期中的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["细线期", "偶线期", "粗线期", "双线期"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "双线期",
        "同源染色体的重组（交叉互换）发生在第一次减数分裂前期Ⅰ的粗线期，而重组后形成的交叉（重组）可在双线期清楚观察到，本题按参考答案取「双线期」。原书单选答案第 9 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1007",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "重组结最早被观察到的时期是在第一次减数分裂过程前期的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["细线期", "偶线期", "粗线期", "双线期", "终变期"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "粗线期",
        "重组结（recombination nodule）是介导DNA重组交换的蛋白结构，最早在第一次减数分裂前期的粗线期被观察到。原书单选答案第 12 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1008",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有丝分裂前中期细胞变化的特征是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "染色质凝集",
      "核仁缩小解体",
      "核膜崩解",
      "染色体排列在细胞中央的赤道面",
      "姐妹染色单体分离",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "核膜崩解",
        "前中期（prometaphase）的典型特征是核膜崩解，纺锤体微管得以与染色体动粒结合；染色质凝集、核仁缩小解体发生于前期，染色体排列赤道面和姐妹染色单体分离分别对应中期和后期，故均非前中期特征。原书单选答案第 13 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1009",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "MPF形成于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["G0期", "G1期", "S期", "G2期", "M期"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "G2期",
        "成熟促进因子（MPF=Cyclin B+Cdk1）主要在G2期形成，并在G2期末启动M期。原书单选答案第 14 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1010",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "特别适合进行染色体数目、结构等细胞遗传学研究的细胞有丝分裂阶段是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["前期", "前中期", "中期", "后期", "末期"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中期",
        "有丝分裂中期染色体凝集程度最高、排列在赤道面上形态最典型，最适合进行染色体数目、形态结构等细胞遗传学研究（核型分析）。原书单选答案第 15 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1011",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有丝分裂器是指",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "由微管、微丝、中间纤维构成的复合细胞器",
      "由着丝粒、纺锤体、中心体构成的复合细胞器",
      "由纺锤体、中心体和染色体组成的复合细胞器",
      "由着丝粒、中心体、染色体组成的复合细胞器",
      "由纺锤体和中心体组成的复合细胞器",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "由纺锤体、中心体和染色体组成的复合细胞器",
        "有丝分裂器是指在有丝分裂前中期由纺锤体（包括星体和三种星体周围微管）及与之结合的染色体共同构成的结构。原书单选答案第 17 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1012",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "纺锤体形成于细胞有丝分裂的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["前期", "前中期", "中期", "后期", "末期"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前中期",
        "纺锤体（纺锤体微管）在有丝分裂前中期完成装配形成，此时核膜崩解、微管得以与染色体动粒相连。原书单选答案第 19 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1013",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不属于有丝分裂末期特征的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "动粒微管消失",
      "核膜重新形成",
      "核仁重新出现",
      "子代染色体到达纺锤体两极",
      "染色体形态继续保持凝集",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "染色体形态继续保持凝集",
        "有丝分裂末期动粒微管消失、核膜重新形成、核仁重新出现，子代染色体到达纺锤体两极后解螺旋形成染色质；「染色体形态继续保持凝集」不是末期特征。原书单选答案第 20 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1014",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "姐妹染色单体分离发生在减数分裂的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "第一次减数分裂前期",
      "第一次减数分裂中期",
      "第二次减数分裂后期",
      "第二次减数分裂中期",
      "第一次减数分裂后期",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第二次减数分裂后期",
        "减数分裂第一次分裂（前期具联会、后期同源染色体分离）不改姐妹染色单体关系，姐妹染色单体在减数分裂Ⅱ的后期彼此分离、移向两极。原书单选答案第 21 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1015",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "只发生于真核生物生殖细胞成熟阶段的分裂方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "无丝分裂",
      "有丝分裂",
      "减数分裂",
      "有丝分裂和减数分裂",
      "无丝分裂和减数分裂",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "减数分裂",
        "减数分裂只发生于真核生物生殖细胞成熟阶段，是生殖细胞形成过程中产生单倍体配子的特殊分裂方式；无丝分裂可见于体细胞，有丝分裂为一般体细胞分裂方式。原书单选答案第 22 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1016",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "联会复合体的形成发生在第一次减数分裂过程前期的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["细线期", "偶线期", "粗线期", "双线期", "终变期"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "偶线期",
        "联会复合体（synaptonemal complex）在第一次减数分裂前期Ⅰ的偶线期形成，与同源染色体联会配对同步。原书单选答案第 24 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1017",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞有丝分裂后期开始的标志是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "核膜消失",
      "染色体排列在赤道面上",
      "核仁消失",
      "染色体形成",
      "姐妹染色单体开始分离",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "姐妹染色单体开始分离",
        "有丝分裂后期以姐妹染色单体分开、各自成为独立染色体并移向两极开始为标志。原书单选答案第 25 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1018",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "一个卵母细胞经过减数分裂形成的卵细胞个数是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["1个", "2个", "3个", "4个", "8个"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "1个",
        "一个卵母细胞经过减数分裂只形成1个功能性的卵细胞，其余三次分裂产物为极体。原书单选答案第 26 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1019",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "姐妹染色单体分离并移向细胞两极发生的有丝分裂阶段是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["前期", "前中期", "中期", "后期", "末期"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "后期",
        "有丝分裂后期姐妹染色单体分离，各自移向细胞两极。原书单选答案第 27 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1020",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "二价体形成发生在第一次减数分裂前期中的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["细线期", "偶线期", "粗线期", "双线期", "终变期"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "偶线期",
        "二价体（联会复合体）形成发生在第一次减数分裂前期Ⅰ的偶线期，此时同源染色体完成联会配对形成二价体。原书单选答案第 28 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1021",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在生殖细胞减数分裂过程中，同源染色体分离并移向细胞两极发生在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["前期Ⅰ", "中期Ⅰ", "后期Ⅰ", "末期Ⅰ"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "后期Ⅰ",
        "减数分裂中，同源染色体分离并分别移向细胞两极发生在第一次减数分裂的后期（后期Ⅰ）。原书单选答案第 31 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1022",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "减数分裂的最主要特点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "纺锤体形成",
      "DNA复制一次，细胞分裂两次",
      "联会复合体的形成",
      "交叉互换现象",
      "重组结的出现",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "DNA复制一次，细胞分裂两次",
        "减数分裂最主要的特点是DNA只复制一次而细胞连续分裂两次，从而使子代细胞染色体数目减半、成为单倍体配子。原书单选答案第 33 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1023",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列具有增殖潜能的细胞是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["淋巴细胞", "红细胞", "角化细胞", "神经元细胞", "骨骼肌细胞"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "淋巴细胞",
        "淋巴细胞在受到抗原等刺激时可进入细胞周期增殖分化，具有增殖潜能；成熟红细胞、角化细胞、神经元细胞和骨骼肌细胞一般均为不再增殖的终末分化细胞。原书单选答案第 34 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1024",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞周期是指",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "从一次分裂结束到下一次分裂开始的过程",
      "从一次分裂开始到这次分裂结束的过程",
      "从这次分裂结束到下一次分裂开始的过程",
      "从一次分裂开始到下一次分裂结束的过程",
      "从一次分裂结束到下一次分裂结束的过程",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "从一次分裂结束到下一次分裂结束的过程",
        "细胞周期是从上次分裂结束到下次分裂结束所经历的规律性变化过程（亦可视为从上一次分裂开始到下一次分裂开始，二者等价）。原书单选答案第 36 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1025",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞周期中DNA的合成发生在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["G1期", "S期", "G0期", "M期", "G2期"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "S期",
        "细胞周期中DNA复制、DNA合成发生在S期（Synthesis期），遗传物质在此期倍增。原书单选答案第 38 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1026",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞处于暂不增殖状态的时期是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["G0期", "G1期", "S期", "G2期", "M期"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "G0期",
        "G0期细胞处于暂不增殖（静息）状态，但保持分裂潜能，在适当信号刺激下可重新进入细胞周期。原书单选答案第 39 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1027",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞有丝分裂中期发生的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "核膜消失",
      "染色体排列在赤道面上",
      "核仁消失",
      "染色体形成",
      "染色体复制",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "染色体排列在赤道面上",
        "有丝分裂中期染色体的着丝粒排列于细胞中央的赤道面（赤道板上），形态最典型。原书单选答案第 47 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1028",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "体细胞经过一次有丝分裂的结果是产生",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "多个相同的子细胞",
      "多个不同的子细胞",
      "两个相同的子细胞",
      "两个不同的子细胞",
      "一个与母细胞相同的子细胞",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "两个相同的子细胞",
        "体细胞经一次有丝分裂产生两个与母细胞遗传组成相同（相等倍性）的子细胞。原书单选答案第 50 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1029",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "中心粒的复制完成于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["G0期", "G1期", "S期", "G2期", "M期"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "S期",
        "中心粒的复制在细胞周期S期完成，与DNA复制同步，为有丝分裂时纺锤体的两极准备材料。原书单选答案第 51 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-a1030",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可作为MPF成分之一的周期蛋白是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["Cyclin A", "Cyclin B", "Cyclin C", "Cyclin D", "Cdk1"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Cyclin B",
        "成熟促进因子（MPF）由Cyclin B与Cdk1结合形成，故可作为MPF成分之一的周期蛋白是Cyclin B。原书单选答案第 54 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-x001",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有丝分裂末期的主要形态变化表现在（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "染色体螺旋化",
      "子细胞核形成",
      "核膜、核仁重现",
      "纺锤体消失",
      "着丝粒分裂",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "核膜、核仁重现",
        "原书多选答案第 1 题为 BCD（子细胞核形成、核膜核仁重现、纺锤体消失）。此处按规约取其中一个正确项「核膜、核仁重现」，有丝分裂末期核膜、核仁重新形成并重现。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-x002",
    order: 40,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有丝分裂活动中的三个重要特征之一是（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "染色质凝集",
      "染色体列队",
      "纺锤体的形成",
      "分裂极确定",
      "收缩环的形成",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "纺锤体的形成",
        "原书多选答案第 3 题为 ACE（染色质凝集、纺锤体形成、收缩环形成）。此处取其中一个正确项「纺锤体的形成」，有丝分裂活动的重要特征之一即纺锤体（有丝分裂器）的装配形成。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-x003",
    order: 41,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "表达仅限于G1期的细胞周期蛋白是（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "cyclin A",
      "cyclin B",
      "cyclin C",
      "cyclin D",
      "cyclin E",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "cyclin D",
        "原书多选答案第 8 题为 CDE（cyclin C、cyclin D、cyclin E 表达仅限于G1期）。此处取其中一个正确项「cyclin D」，cyclin D在G1期表达，与Cdk4/6结合驱动G1→S转变。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-x004",
    order: 42,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在细胞周期调控中起作用的因素包括（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["基因", "生长因子", "胆固醇", "cAMP", "抑素"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "生长因子",
        "原书多选答案第 9 题为 ABDE（基因、生长因子、cAMP、抑素）。此处取其中一个正确项「生长因子」，细胞周期受基因、生长因子、cAMP、抑素等多因素调控。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch13-cell-cycle-x005",
    order: 43,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "发生于MPF活化过程的分子事件是（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "cyclin B与Cdk1相结合",
      "Thr161与Tyr15均被磷酸化",
      "Tyr15被weel激酶磷酸化",
      "Tyr15被Cdc25磷酸酶去磷酸化",
      "Thr161被CAK磷酸化",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "cyclin B与Cdk1相结合",
        "原书多选答案第 10 题为 ABCDE（所列漂移均发生于MPF活化过程）。此处取其中一个正确项「cyclin B与Cdk1相结合」，即MPF复合物的形成。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B 型配伍题：本书无 B1/B2 型，置空数组 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];