import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学细胞生物学实验指导与习题集（第4版）— 第11章 细胞微环境及其与细胞的相互作用 题库提取（等比取样）
 * 来源：《医学细胞生物学实验指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：8 题
 * - 单项选择题（a1-single）：21 题（其中多项选择题映射 10 题）
 * - 独立记分题合计：29 题（须等于本文件预算 29）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书题型为名词解释（8）、单项选择题（40）、多项选择题（10），本书无配伍/填空/简答，
 *   故 bGroups 为空数组。本文件按 29 道预算等比取材并在原书顺序内取满：名词 8 道全部取，
 *   单项选择题取其中 11 道（a1-single 单选），多项选择题 10 道全部按项目规约映射为
 *   a1-single（promptSource.note=xMapNote）。正确项均按章末「参考答案」键号锚定（如 1.A 2.B …），
 *   选项按细胞生物学医学语义恢复完整集合（原书双栏排版致题干/选项/题号交错散落，已按语义重建），
 *   再随机重排并同步 correctChoiceIndex（0 起）。胶原类型、氨基酸（Gly/Hydroxyproline/Pro）、
 *   蛋白类型、糖胺聚糖等数值与构成均保留原值，未捏造。原书单词答案行第 7–11 题键号因扫描缺失，
 *   本文件未取用这些题号。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "cell-bio-ch11-microenvironment";
const locatorBase =
  "《医学细胞生物学实验指导与习题集》第4版 第11章 细胞微环境及其与细胞的相互作用 习题集（核对PDF 第175–180页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），8 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch11-microenvironment-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞外基质（extracellular matrix，ECM）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞外基质（ECM）",
        "细胞微环境的核心组分，指分布在细胞外空间、由细胞分泌的蛋白质和多糖所构成的精密有序的三维网状结构，参与组织结构的维持，影响细胞的存活、形态、代谢、增殖、分化、迁移等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：糖胺聚糖（glycosaminoglycan，GAG）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "糖胺聚糖（GAG）",
        "高分子量的含糖化合物，由重复的二糖单位（氨基己糖和糖醛酸）构成的长链多糖，参与形成细胞外亲水性的凝胶，赋予组织良好的弹性和抗压性。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：透明质酸（hyaluronic acid，HA）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "透明质酸（HA）",
        "结构最简单的糖胺聚糖，由葡萄糖醛酸和 N-乙酰氨基葡萄糖二糖单位重复排列构成，在胚胎发育早期和组织创伤修复时起到促进细胞迁移和增殖的作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：蛋白聚糖（proteoglycan，PG）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "蛋白聚糖（PG）",
        "由糖胺聚糖与核心蛋白的丝氨酸残基共价结合形成的高分子复合物，参与形成细胞外亲水性的凝胶，赋予组织良好的弹性和抗压性。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：层粘连蛋白（laminin，LN）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "层粘连蛋白（LN）",
        "由一条重链和两条轻链构成的高分子糖蛋白，分子呈不对称的十字形；层粘连蛋白是基膜的主要成分，在胚胎发育及组织分化中发挥重要作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：胶原（collagen）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胶原（collagen）",
        "遍布于体内各种器官和组织、含量最丰富的纤维蛋白家族，构成细胞外基质的框架结构，使组织具有韧性和抗拉性。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：纤连蛋白（fibronectin，FN）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "纤连蛋白（FN）",
        "广泛存在于人和动物组织中的一类高分子量非胶原糖蛋白，分子呈 V 字形，介导细胞与细胞外基质的黏着，参与细胞的迁移。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：基膜（basal lamina 或 basement membrane）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "基膜（basal lamina / basement membrane）",
        "也称基底膜，是细胞外基质特化而成的一种柔软、坚韧的网膜结构，主要由 IV 型胶原、层粘连蛋白、巢蛋白及渗滤素构成，具有支持、屏障、选择渗透、调节细胞增殖、迁移等作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 单项选择题（a1-single），11 道（源为单项选择题） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch11-microenvironment-a1001",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "发育早期基膜中主要的细胞外基质成分是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "I型胶原蛋白",
      "蛋白聚糖",
      "纤连蛋白",
      "层粘连蛋白",
      "糖胺聚糖",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "层粘连蛋白",
        "发育早期基膜中主要的 ECM 成分为层粘连蛋白，它是最早出现的基膜结构蛋白之一。原书单项选择题答案第 1 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-a1002",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胶原蛋白 α 肽链中的氨基酸以 Gly-X-Y 三肽序列重复排列，其中「X」多为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["羟脯氨酸", "脯氨酸", "赖氨酸", "丝氨酸", "色氨酸"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脯氨酸",
        "胶原的 Gly-X-Y 重复序列中，X 位多为脯氨酸（Pro），Y 位多为羟脯氨酸（Hyp）。原书单项选择题答案第 2 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-a1003",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "纤连蛋白与细胞结合的最小结构单位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "Gly-X-Y序列",
      "Arg-Gly-Asp序列",
      "信号肽",
      "二硫键",
      "KDEL序列",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Arg-Gly-Asp序列",
        "纤连蛋白上的 Arg-Gly-Asp（RGD）三肽序列是与整联蛋白等细胞表面受体结合的最小结构单位。原书单项选择题答案第 3 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-a1004",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "构成基膜的主要胶原类型是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "I型胶原蛋白",
      "II型胶原蛋白",
      "III型胶原蛋白",
      "IV型胶原蛋白",
      "V型胶原蛋白",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "IV型胶原蛋白",
        "基膜中的主要胶原为 IV 型胶原，其 Gly-X-Y 序列被中断形成柔性网架，与层粘连蛋白等共同构成基膜。原书单项选择题答案第 4 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-a1005",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "分别赋予细胞外基质弹性和抗张性的成分是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "弹性纤维和胶原纤维",
      "蛋白聚糖和糖胺聚糖",
      "纤连蛋白和层粘连蛋白",
      "弹性纤维和蛋白聚糖",
      "巢蛋白和凝集素",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "弹性纤维和胶原纤维",
        "弹性纤维使 ECM 具有弹性，胶原纤维赋予其抗张性（韧性、抗拉性）。原书单项选择题答案第 5 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-a1006",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胶原纤维最终完成装配是在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["内质网", "高尔基复合体", "细胞质基质", "溶酶体", "细胞外基质"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞外基质",
        "胶原前体分泌到细胞外后，在细胞外基质内经交联等步骤最终装配形成胶原原纤维和纤维。原书单项选择题答案第 6 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-a1007",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞外基质中非糖基化的蛋白是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["弹性蛋白", "层粘连蛋白", "胶原", "细胞纤连蛋白", "血浆纤连蛋白"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "弹性蛋白",
        "弹性蛋白为高度不溶的非糖基化蛋白；层粘连蛋白、胶原、纤连蛋白均属糖蛋白。原书单项选择题答案第 13 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-a1008",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于弹性蛋白的正确叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "糖基化、高度不溶、很少羟化",
      "非糖基化、高度不溶、羟化",
      "非糖基化、可溶、很少羟化",
      "非糖基化、高度不溶、很少羟化",
      "糖基化、可溶、很少羟化",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "非糖基化、高度不溶、很少羟化",
        "弹性蛋白是非糖基化、高度不溶、很少羟化的纤维蛋白，经交联成网赋予组织弹性。原书单项选择题答案第 16 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-a1009",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于蛋白聚糖的叙述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "蛋白聚糖由糖胺聚糖与核心蛋白共价连接形成",
      "蛋白聚糖单体与透明质酸非共价结合形成多聚体",
      "蛋白聚糖分子中含有O-连接的糖基",
      "糖链为无分支直链型",
      "先合成二糖单位，再将其连接到糖链上",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "先合成二糖单位，再将其连接到糖链上",
        "糖胺聚糖链是在糖基转移酶作用下把糖基逐一加到核心蛋白丝氨酸残基上逐步合成的，并非先合成二糖单位再接上。原书单项选择题答案第 18 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-a1010",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "动物体内含 S 最多的蛋白是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["弹性蛋白", "层粘连蛋白", "胶原", "纤连蛋白", "巢蛋白"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胶原",
        "胶原是动物体内含量最丰富的蛋白质，约占全身蛋白总量的 1/3 左右。原书单项选择题答案第 24 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-a1011",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于糖胺聚糖的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "是由重复的二糖单位构成的直链多糖",
      "构成细胞外亲水性凝胶，赋予组织良好的弹性和抗压性",
      "由氨基己糖和糖醛酸构成",
      "糖残基上通常带有硫酸基团或羧基",
      "带有大量正电荷",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "带有大量正电荷",
        "糖胺聚糖的硫酸基团或羧基使其带大量负电荷（故呈酸性），能结合大量水形成凝胶。原书单项选择题答案第 30 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 多项选择题（原书 X 型），按项目规约映射为 a1-single 单选取一正确项，10 道 */
const xItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch11-microenvironment-x001",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】IV 型胶原不具备的结构特征是（单选其中一个正确项，IV 型胶原无此特征者）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "α-螺旋结构",
      "保留前肽不被切除",
      "非糖基化蛋白",
      "重复的Gly-X-Y序列",
      "开始合成在内质网",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "α-螺旋结构",
        "IV 型胶原不具备 α-螺旋结构、非糖基化和完整重复的 Gly-X-Y 序列等特征（原多项选择题答案 ACD），其为三股超螺旋并含中断的 Gly-X-Y。此处取 α-螺旋结构为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-x002",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】细胞外基质中，凝胶样基质的主体成分是（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["蛋白聚糖", "纤连蛋白", "糖胺聚糖", "胶原", "弹性蛋白"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "蛋白聚糖",
        "蛋白聚糖与糖胺聚糖共同构成 ECM 的凝胶样基质（原多项选择题答案 AC），赋予组织弹性和抗压性。此处取蛋白聚糖为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-x003",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】胶原具有的特性包括（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "胶原是糖蛋白",
      "胶原富含甘氨酸",
      "组织分布具有特异性",
      "在细胞外基质起骨架作用",
      "由游离核糖体合成",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胶原是糖蛋白",
        "胶原是糖蛋白、富含甘氨酸、组织分布有特异性、在 ECM 中起骨架作用（原多项选择题答案 ABCD）；其合成经膜相核糖体-内质网途径而非游离核糖体。此处取「胶原是糖蛋白」为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-x004",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】细胞外基质中，参与形成纤维网架的主要成分是（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["蛋白聚糖", "纤连蛋白", "层粘连蛋白", "胶原", "弹性蛋白"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胶原",
        "参与形成 ECM 纤维网架的成分包括纤连蛋白、层粘连蛋白、胶原和弹性蛋白（原多项选择题答案 BCDE）。此处取胶原为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-x005",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】下列疾病中与胶原（或胶原代谢）有关的是（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "维生素C缺乏症",
      "成骨发育不全综合征",
      "爱-唐综合征",
      "扩张性心肌病与心肌炎",
      "黏多糖累积病",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "爱-唐综合征",
        "维生素C缺乏症（胶原羟化、胶原合成障碍）、成骨发育不全综合征、爱-唐（Ehlers-Danlos）综合征（原多项选择题答案 ABC）均与胶原异常有关。此处取爱-唐综合征为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-x006",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】下列关于肿瘤微环境的描述，正确的是（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "微环境中的细胞和基质成分的异常是肿瘤发生的重要因素",
      "成纤维细胞是肿瘤微环境中主要的基质细胞",
      "实体肿瘤附近往往可见成纤维细胞活化",
      "肿瘤微环境中存在大量的巨噬细胞",
      "肿瘤微环境可导致T细胞免疫功能下降",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "微环境中的细胞和基质成分的异常是肿瘤发生的重要因素",
        "上述有关肿瘤微环境的描述均正确（原多项选择题答案 ABCDE），包括基质异常、成纤维细胞活化、大量巨噬细胞、T 细胞免疫下降等。此处取首项为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-x007",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】胚胎结缔组织的细胞外基质主要成分是（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["I型胶原", "III型胶原", "弹性蛋白", "透明质酸", "纤连蛋白"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "透明质酸",
        "胚胎结缔组织 ECM 主要含 III 型胶原、弹性蛋白和透明质酸等（原多项选择题答案 BCD），透明质酸利于细胞迁移增殖。此处取透明质酸为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-x008",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】基膜的主要成分包括（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["IV型胶原", "层粘连蛋白", "渗滤素", "巢蛋白", "纤连蛋白"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "IV型胶原",
        "基膜主要由 IV 型胶原、层粘连蛋白、巢蛋白及渗滤素构成（原多项选择题答案 ABCD）。此处取 IV 型胶原为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-x009",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】与细胞外基质成分降解有关的是（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "基质金属蛋白酶",
      "丝氨酸蛋白酶",
      "胶原酶",
      "去垢剂",
      "透明质酸",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "基质金属蛋白酶",
        "基质金属蛋白酶（MMP）、丝氨酸蛋白酶、胶原酶等参与 ECM 的降解（原多项选择题答案 ABC）。此处取基质金属蛋白酶为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch11-microenvironment-x010",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "【原为多项选择题】成年结缔组织中细胞外基质主要成分是（单选其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["I型胶原", "III型胶原", "弹性蛋白", "透明质酸", "纤连蛋白"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "I型胶原",
        "成年结缔组织 ECM 主要成分为 I 型胶原和纤连蛋白等（原多项选择题答案 AE），I 型胶原提供强度。此处取 I 型胶原为代表正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 本书无 B 型配伍题，bGroups 为空数组 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...xItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];