import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学细胞生物学实验指导与习题集（第4版）— 第7章 细胞骨架与细胞的运动 题库提取（等比取样）
 * 来源：《医学细胞生物学实验指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：4 题
 * - 单项选择题（a1-single）：30 题（其中多项选择题映射 5 题）
 * - 独立记分题合计：34 题（须等于本文件预算 34）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书题型为名词解释（10）、单项选择题（60）、多项选择题（10），本书无配伍/填空/简答，
 *   故 bGroups 为空数组。本文件按 34 道预算等比取材并在原书顺序内取满：名词 4 道、单项选择题 25 道
 *   （a1-single 单选）、多项选择题 5 道按项目规约映射为 a1-single（promptSource.note=xMapNote）。
 *   正确项均按章末「参考答案」键号锚定（如 1.B 2.D …）。原书为双栏排版，题干/选项/题号交错散落，
 *   本文件已按细胞生物学医学语义恢复完整选项集合后再重排并同步 correctChoiceIndex（0 起）。
 *   数值（原纤维根数 13、“9+2/9×3”、7 个肌动蛋白、10~13 个 γ-TuRC 分子）、结构、过程、
 *   马达蛋白名称均保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "cell-bio-ch07-cytoskeleton-movement";
const locatorBase =
  "《医学细胞生物学实验指导与习题集》第4版 第7章 细胞骨架与细胞的运动 习题集（核对PDF 第144–151页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），4 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：微管组织中心（microtubule organizing center, MTOC）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "微管组织中心（microtubule organizing center, MTOC）",
        "细胞质中微管组装的起始点和核心，常见的有中心体、鞭毛和纤毛基体。对微管的形成、微管极性的确定及细胞分裂中纺锤体的形成起重要作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：马达蛋白（motor protein）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "马达蛋白（motor protein）",
        "指介导细胞内物质沿细胞骨架运输的蛋白，包括动力蛋白、驱动蛋白和肌球蛋白三大家族。其中驱动蛋白和动力蛋白以微管作为运行轨道，而肌球蛋白则是以肌动蛋白纤维作为运行轨道。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：细胞皮层（cell cortex）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞皮层（cell cortex）",
        "也叫肌动蛋白皮层，是指细胞质膜下方的一层由微丝和各种微丝结合蛋白组成的网状结构，具有很高的动态性，为细胞膜提供强度和韧性，维持细胞形态。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：γ-微管蛋白环形复合体（γ-tubulin ring complex, γ-TuRC）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "γ-微管蛋白环形复合体（γ-tubulin ring complex, γ-TuRC）",
        "含有 10~13 个 γ-微管蛋白分子的环形结构，与微管直径相同，可刺激微管核心形成，影响微管从中心粒上的释放。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 单项选择题 + 多项选择题映射（统一映射为 a1-single），30 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1004",
    order: 5,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列不属于微管的功能的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["颗粒的运输", "参与构成鞭毛、纤毛", "构成伪足", "参与细胞内信号转导", "维持高尔基复合体的位置"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "构成伪足",
        "构成伪足是微丝（肌动蛋白）的功能，不属于微管功能。原书单选第4题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1005",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "中间纤维装配最常见的调节方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["磷酸化", "糖基化", "泛素化", "甲基化", "羟基化"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "磷酸化",
        "中间纤维装配最常见的调节方式是磷酸化。原书单选第5题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1006",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "核纤层蛋白属于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["微管蛋白", "肌动蛋白", "中间纤维蛋白", "驱动蛋白", "动力蛋白"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中间纤维蛋白",
        "核纤层蛋白属于中间纤维蛋白家族。原书单选第6题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1007",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "微管体外装配可分为三个时期，其中为微管的限速过程的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["成核期", "聚合期", "延长期", "稳定期", "平衡期"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "成核期",
        "微管体外装配分为成核期、聚合（延长）期和稳定期，其中成核期为限速过程。原书单选第7题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1008",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "微丝在聚合过程中所需要的能量形式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["ATP", "ADP", "GTP", "GDP", "CTP"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "ATP",
        "微丝聚合所需要的能量由 ATP 提供。原书单选第8题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1009",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列以微丝为运行轨道的马达蛋白是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["微管蛋白", "动力蛋白", "驱动蛋白", "肌动蛋白", "肌球蛋白"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌球蛋白",
        "肌球蛋白是以肌动蛋白纤维（微丝）为运行轨道的马达蛋白。原书单选第9题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1010",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "使用秋水仙素可抑制细胞的有丝分裂并使其停滞于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["间期", "前期", "中期", "后期", "末期"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中期",
        "秋水仙素抑制微管聚合，使有丝分裂停滞于中期。原书单选第10题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可作为细胞中微管组织中心的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["星体微管", "中心体", "中心粒", "纤毛", "鞭毛"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中心体",
        "中心体是动物细胞中可作为微管组织中心（MTOC）的结构。原书单选第12题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1014",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "微管在聚合过程中所需要的能量形式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["ATP", "ADP", "GTP", "GDP", "CTP"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "GTP",
        "微管蛋白聚合形成微管需要 GTP 提供能量。原书单选第14题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1015",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "具有组织特异性分布的细胞骨架成分是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["α管蛋白", "β管蛋白", "γ微管蛋白", "G-肌动蛋白", "角蛋白"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "角蛋白",
        "角蛋白等中间纤维蛋白在不同组织中的表达具有组织特异性分布。原书单选第15题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1016",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "影响微管组装的主要条件中，不包括的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["GTP 浓度", "微管蛋白的浓度", "秋水仙素", "温度", "压力"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "压力",
        "GTP 浓度、微管蛋白浓度、温度等影响微管组装，压力不是其主要影响因素。原书单选第16题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1017",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "纤毛和鞭毛体部的微管均以“9+2”形式构成，其中",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "“2”表示2个单管",
      "“9”表示9个单管",
      "“2”表示2个二联管",
      "“9”表示9个三联管",
      "“2”表示2个三联管",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "“2”表示2个单管",
        "纤毛、鞭毛体部“9+2”结构中，外围“9”为 9 组二联管，中央“2”为 2 个单管。原书单选第17题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1018",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "构成细胞皮层的主要成分是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["微管蛋白", "核纤层蛋白", "肌球蛋白", "马达蛋白", "肌动蛋白"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌动蛋白",
        "细胞皮层主要由微丝（肌动蛋白丝）和各种微丝结合蛋白组成。原书单选第18题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1019",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "主要由微管构成的细胞结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["鞭毛", "伪足", "核纤层", "微绒毛", "细胞皮层"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "鞭毛",
        "鞭毛主要由微管（“9+2”结构）构成；伪足、微绒毛、细胞皮层以微丝为主，核纤层由核纤层蛋白构成。原书单选第19题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1020",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "影响微丝组装的最关键的因素是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "ATP 和肌动蛋白的浓度",
      "ATP 和温度",
      "GTP 和温度",
      "GTP 和肌动蛋白的浓度",
      "肌动蛋白的浓度和温度",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "ATP 和肌动蛋白的浓度",
        "影响微丝组装最关键的因素是 ATP 和肌动蛋白的浓度。原书单选第20题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1021",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "能够促进微管聚合的药物是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["紫杉醇", "长春花碱", "秋水仙素", "细胞松弛素 B", "鬼笔环肽"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "紫杉醇",
        "紫杉醇（TAXOL）是促进微管聚合、稳定微管的药物。原书单选第21题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1023",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "导致人纤毛不动综合征的结构异常是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["动力蛋白臂缺失", "中央微管缺失", "中央微管异常", "轴丝缺乏", "tau 蛋白过度磷酸化"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动力蛋白臂缺失",
        "人纤毛不动综合征（如 Kartagener 综合征）因动力蛋白臂缺失，纤毛不能摆动。原书单选第23题答案 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1024",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可介导物质沿微管负端向正端运动的马达蛋白是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["MAP-1", "MAP-2", "tau", "驱动蛋白", "动力蛋白"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "驱动蛋白",
        "驱动蛋白（kinesin）是介导物质沿微管负端向正端运动的马达蛋白。原书单选第24题答案 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1025",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "构成微丝的主要成分是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["肌球蛋白", "交联蛋白", "肌动蛋白", "毛缘蛋白", "结蛋白"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌动蛋白",
        "微丝（肌动蛋白丝）的主要成分是肌动蛋白。原书单选第25题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1026",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "鞭毛和纤毛基体的微管排列方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["9+2", "9+0", "9×2", "9×3", "9×2+2"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "9+0",
        "鞭毛和纤毛基体（中心粒）的微管排列方式为“9+0”（9 组三连管围成环，中央无微管）。原书单选第26题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1027",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞分裂进入末期时，核纤层蛋白发生",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["磷酸化", "去磷酸化", "甲基化", "去甲基化", "泛素化"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "去磷酸化",
        "细胞分裂进入末期时，核纤层蛋白去磷酸化，使核纤层重新组装，核膜（子核）重建。原书单选第27题答案 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1028",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "影响微管组装的最关键的因素是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "ATP 和微管蛋白的浓度",
      "ATP 和温度",
      "GTP 和温度",
      "GTP 和微管蛋白的浓度",
      "微管蛋白的浓度和温度",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "GTP 和微管蛋白的浓度",
        "影响微管组装最关键的因素是 GTP 和微管蛋白的浓度。原书单选第28题答案 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1030",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列参与构成有丝分裂器的细胞骨架结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["核纤层", "核基质", "中心体", "动粒", "收缩环"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中心体",
        "参与构成有丝分裂器的细胞骨架结构是中心体及其发出的星体微管（纺锤体）。原书单选第30题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1032",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可介导物质沿微管正端向负端运动的马达蛋白是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["MAP-1", "MAP-2", "tau", "驱动蛋白", "动力蛋白"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动力蛋白",
        "动力蛋白（dynein）是介导物质沿微管正端向负端运动的马达蛋白。原书单选第32题答案 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-a1034",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "γ-微管蛋白位于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["细胞膜", "细胞核", "中心体", "线粒体", "鞭毛体部"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中心体",
        "γ-微管蛋白位于中心体（及微管组织中心），参与微管成核。原书单选第34题答案 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-x001",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "中间纤维组装过程中，具有极性的是（原题为多项选择题）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["单体", "二聚体", "四聚体", "八聚体", "原纤维"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单体",
        "中间纤维组装中，单体（以及二聚体）具有极性，而更高层次的聚合体趋于非极性。原书多选第1题答案 AB，本题取其一。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-x002",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列属于细胞中微管组织中心的结构是（原题为多项选择题）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["纺锤体", "中心体", "纤毛基体", "鞭毛基体", "鞭毛"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中心体",
        "细胞中的微管组织中心包括中心体、纤毛基体和鞭毛基体。原书多选第2题答案 BCD，本题取其一。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-x003",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列属于马达蛋白的是（原题为多项选择题）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["微管蛋白", "肌动蛋白", "驱动蛋白", "动力蛋白", "肌球蛋白"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "驱动蛋白",
        "马达蛋白包括驱动蛋白、动力蛋白和肌球蛋白三大类。原书多选第4题答案 CDE，本题取其一。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-x004",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "参与构成细胞连接的细胞骨架成分是（原题为多项选择题）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["微管", "微丝", "中间纤维", "钙黏着蛋白", "整联蛋白"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中间纤维",
        "参与构成细胞连接的细胞骨架成分主要为微丝和中间纤维。原书多选第6题答案 BC，本题取其一。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch07-cytoskeleton-movement-x005",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "鬼笔环肽可影响的细胞活动是（原题为多项选择题）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["胞质分裂", "肌肉收缩", "纺锤体的形成", "变形运动", "肠上皮细胞的吸收作用"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胞质分裂",
        "鬼笔环肽能与微丝结合、抑制微丝解聚，从而影响胞质分裂、变形运动等依赖于微丝的活动。原书多选第8题答案 AD，本题取其一。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 本书无 B 型配伍题，bGroups 置空数组 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];