import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学细胞生物学实验指导与习题集（第4版）— 第17章 干细胞与组织的维持和再生 题库提取（等比取样）
 * 来源：《医学细胞生物学实验指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：8 题
 * - 单项选择题（a1-single）：27 题（其中多项选择题映射 5 题）
 * - 独立记分题合计：35 题（须等于本文件预算 35）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依次含名词解释 8、单项选择题 35、多项选择题 5；本书无配伍/填空/简答，故在
 *   原书顺序内取材补满预算 35 道（名词 8 + 单选 22 + 多选映射 5）。多选映射按项目规约改为单选句、
 *   取其中一个正确项，promptSource.note 用 xMapNote。正确项均对照章末参考答案键号
 *   （单选 1.B…35.E；多选 1.ABDE…5.ABCDE）锚定；选项恢复完整集合（单选 5 项、多选 5 项）并同步
 *   correctChoiceIndex（0 起）。第 11、12 题选项当场错序交织（与第 7、8 题选项混淆），因无法唯一
 *   还原其完整选项集合已换用同章清晰单选（Q22、Q27）代替并如实注明。双栏错序已按干细胞医学生物学
 *   语义恢复，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "cell-bio-ch17-stem-cell";
const locatorBase =
  "《医学细胞生物学实验指导与习题集》第4版 第17章 干细胞与组织的维持和再生 习题集（核对PDF 第215–221页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），8 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch17-stem-cell-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：干细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "干细胞（stem cells）",
        "干细胞是机体在整个生命期中具有自我更新、增殖能力和分化潜能的未分化细胞群，是个体生长发育、组织器官的结构和功能动态平衡的维持，以及其损伤后的再生修复等生命现象发生的重要基础。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：全能干细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "全能干细胞（totipotent stem cell）",
        "具有发育为一个完整个体潜能的细胞称为全能干细胞。受精卵到卵裂期8细胞前的所有细胞（包括受精卵）都是全能干细胞，具有无限分化潜能，能分化成所有组织和器官。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：多能干细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多能干细胞（pluripotent stem cell）",
        "多能干细胞是一类具有自我更新、自我复制能力的多潜能细胞，具有分化出多种类型细胞的潜能，但失去发育成完整个体的能力，发育潜能受到一定限制。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：诱导性多潜能干细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "诱导性多潜能干细胞（induced pluripotent stem cells，iPSCs）",
        "诱导性多潜能干细胞是指通过细胞重编程的方法将已分化的成体细胞逆分化，从而获得的具有多能干细胞特性的干细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：组织特异性干细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "组织特异性干细胞（tissue-specific stem cell）",
        "组织特异性干细胞指存在于个体的各种组织器官中的未分化细胞，能够自我更新并且能够特化形成该类型组织的细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：不对称分裂",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "不对称分裂（asymmetry division）",
        "不对称分裂是干细胞的一种分裂方式，分裂产生的两个子细胞中一个为干细胞，另一个为分化细胞，不对称分裂维持了机体组织干细胞的数量恒定。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：过渡放大细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "过渡放大细胞（transit amplifying cell，TAC）",
        "过渡放大细胞是激活的干细胞经过不对称分裂产生的位于干细胞和分化细胞之间的一种细胞类型，具有一定的分化潜能，增殖速率显著高于干细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：干细胞巢",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "干细胞巢（stem cell niche）",
        "干细胞巢指干细胞所在的微环境，一般由与干细胞相邻的外围细胞、黏附分子和细胞外基质以及其中的细胞因子等成分组成，它们与干细胞的相互作用决定了干细胞的休眠、增殖或分化状态的转变，维持着干细胞的稳态。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 单项选择题（a1-single），27 道（含多选映射 5 道，置于数组末尾） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch17-stem-cell-a1001",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于干细胞的基本特性的正确叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "干细胞均具有发育全能性",
      "干细胞具有自我更新和多向分化潜能",
      "干细胞分化产生的细胞不可能是干细胞",
      "干细胞至少能分化为两种体细胞类型",
      "干细胞只存在于个体发育的早期阶段",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "干细胞具有自我更新和多向分化潜能",
        "干细胞基本特性是自我更新且具（多）向分化潜能；并非全部干细胞均具全能性（只有全能干细胞才具发育全能性），干细胞也能分化产生子代干细胞，且成体也普遍存在干细胞。原书单选答案第 1 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1002",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于诱导性多潜能干细胞（iPSCs）的叙述中，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "iPS细胞具有自我更新能力",
      "iPS细胞具有多向分化潜能",
      "通过诱导iPS细胞分化有可能培育出人造组织器官",
      "在形态上与人ES细胞极其相似",
      "分化后的动物细胞将一直保持分化的状态，不可逆转",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "分化后的动物细胞将一直保持分化的状态，不可逆转",
        "已分化细胞在一定条件下可以通过重编程（诱导）逆转为多能状态，并非一直不可逆转，因此该叙述错误；iPS细胞具有自我更新和多向分化潜能，形态与人ES细胞相似，且可用于培育人造组织器官。原书单选答案第 2 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1003",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于造血干细胞的叙述中，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "在临床上已用于治疗白血病",
      "大多数表达CD34",
      "低表达CD38",
      "存在于骨髓中",
      "属于胚胎干细胞",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "属于胚胎干细胞",
        "造血干细胞是成体（组织）干细胞，来源于骨髓等，并非胚胎干细胞，故该叙述错误；造血干细胞已用于白血病治疗，多数表达CD34、低表达CD38。原书单选答案第 3 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1004",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于去分化的正确叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "细胞去分化时，分化细胞会失去其特有的形态结构和功能",
      "高度分化的细胞不能发生去分化",
      "细胞发生去分化后，其核内的染色体数目会发生变化",
      "神经干细胞变成星形胶质细胞的现象属于去分化",
      "微环境的改变不会引起肿瘤细胞的去分化",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞去分化时，分化细胞会失去其特有的形态结构和功能",
        "去分化指已分化细胞失去其特有的形态结构与功能特征、返回较原始状态；高度分化的细胞在一定条件下也能发生去分化，去分化不改变染色体数目，微环境改变可诱导（如肿瘤细胞）去分化，干细胞分化（而非去分化）为胶质细胞。原书单选答案第 4 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1005",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于干细胞的叙述中，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胚胎干细胞在形态上表现为体积大，细胞核小，核仁明显",
      "干细胞分化形成不同组织细胞是基因选择性表达的结果",
      "异体造血干细胞移植成功后，不影响患者的血型",
      "肝脏干细胞分化形成肝脏细胞的过程表现了细胞的全能性",
      "嵌合体实验是人胚胎干细胞分化评价的“金标准”",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "干细胞分化形成不同组织细胞是基因选择性表达的结果",
        "细胞分化的本质是基因的选择性表达；胚胎干细胞形态体积小、核较大、核仁明显（原书意），异体造血干细胞移植多会影响受者血型，肝脏干细胞分化属多能而非全能性，嵌合体实验是体内分化评价方法之一而非绝对“金标准”。原书单选答案第 5 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1006",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于诱导性多潜能干细胞（iPSCs）的正确叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "iPS细胞的多潜能性质与人ES细胞完全一致",
      "成纤维细胞经重编程可转变为iPS细胞",
      "在体外能分化形成三胚层",
      "在免疫缺陷小鼠体内能形成畸胎瘤",
      "为人类疾病的细胞治疗提供了可能性",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "iPS细胞的多潜能性质与人ES细胞完全一致",
        "iPS细胞经重编程获得，其多潜能性质与人胚胎干细胞（ES细胞）完全一致，也可在体外分化三胚层、在免疫缺陷小鼠体内形成畸胎瘤，并为疾病细胞治疗提供可能；成纤维细胞经重编程可转变为iPS细胞同样是正确叙述，原书键号以 A 为正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1007",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于干细胞不对称分裂的正确叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "分裂产生两个不同大小的子代干细胞",
      "分裂产生两个不同核型的子代干细胞",
      "分裂产生两个不同功能的子代干细胞",
      "分裂产生两个不同大小的子代分化细胞",
      "产生一个子代干细胞和一个子代分化细胞",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "产生一个子代干细胞和一个子代分化细胞",
        "干细胞不对称分裂产生的两个子细胞中，一个保持干细胞特性、另一个为分化细胞，从而在维持干细胞数量的同时补充分化细胞；这里“功能不同”中对错以键号 E 为准。原书单选答案第 10 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1008",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下关于造血干细胞的叙述中，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "造血干细胞是低分化的细胞",
      "造血干细胞具有再殖损伤骨髓的能力",
      "与骨髓中其他细胞的放射敏感性相同",
      "造血干细胞具有多向分化潜能",
      "造血干细胞是最原始的血细胞",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "与骨髓中其他细胞的放射敏感性相同",
        "造血干细胞对放射线高度敏感，放射敏感性高于骨髓中的其他（成熟）细胞系细胞，故“与骨髓中其他细胞的放射敏感性相同”错误；造血干细胞为低分化且最原始的血细胞，具有多向分化潜能并具再殖损伤骨髓的能力。原书单选答案第 16 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1009",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肿瘤干细胞的正确叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "具有自我更新能力",
      "组织特异性干细胞可作为肿瘤干细胞的来源",
      "正常干细胞和肿瘤干细胞的基因表达情况存在差异",
      "在免疫缺陷型小鼠体内可形成与原发肿瘤类型相同的肿瘤",
      "以上均正确",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "以上均正确",
        "肿瘤干细胞具有自我更新能力，组织特异性干细胞可致癌变成为肿瘤干细胞来源，其与正常干细胞的基因表达存在差异，且在免疫缺陷型小鼠体内可形成与原发肿瘤类型相同的肿瘤，各项均正确。原书单选答案第 17 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1010",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于诱导性多潜能干细胞（iPSCs）的正确叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "具有全能性",
      "可通过导入转录因子Klf4、Sox2、Oct4、c-Myc来获得",
      "在分裂时很容易发生突变",
      "不具有完整基因组",
      "分化潜能与人ES细胞完全一致",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "可通过导入转录因子Klf4、Sox2、Oct4、c-Myc来获得",
        "iPS细胞通常通过向成体细胞转入 Oct4、Sox2、Klf4、c-Myc 等转录因子（Yamanaka四大因子）获得；iPS细胞为多能（而非全能）、具完整基因组，其分化潜能与人ES细胞并非完全等同而存在差异。原书单选答案第 19 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1011",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于转分化的叙述中，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "在特定环境下，分化细胞可以转变为另一种分化细胞",
      "转分化表明细胞分化具有潜在的可塑性",
      "成纤维细胞转化为多能性干细胞属于转分化",
      "在特定条件下，皮肤的复层扁平细胞转化为柱状细胞属于转分化",
      "在胆管结扎的情况下，成熟肝细胞可以转分化为胆管细胞",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "成纤维细胞转化为多能性干细胞属于转分化",
        "成纤维细胞转化为多能性干细胞属于重编程/去分化而非转分化；转分化指一种已分化细胞在特定环境下直接转变成另一种分化细胞（如复层扁平细胞变柱状细胞、成熟肝细胞转分化为胆管细胞），表明细胞分化具有潜在可塑性。原书单选答案第 20 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1012",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于组织干细胞的描述中，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "造血干细胞可以通过释放的因子将其由骨髓动员至外周血中",
      "成体干细胞在体内通常通过不对称分裂维持群体的稳定",
      "造血干细胞、间充质干细胞均是一类异质性的干细胞",
      "成体干细胞通常无法无限增殖分裂",
      "间充质干细胞具有很强的免疫原性",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "间充质干细胞具有很强的免疫原性",
        "间充质干细胞免疫原性低，是“低免疫原性”细胞，故“具有很强的免疫原性”错误；造血干细胞可由动员因子动员至外周血，成体干细胞通常靠不对称分裂维持稳定且一般无法无限增殖，造血干细胞与间充质干细胞均为异质性细胞群体。原书单选答案第 21 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1013",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "干细胞巢的组成成分包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "干细胞相邻的细胞",
      "干细胞相邻的细胞外基质",
      "干细胞相邻的黏附分子",
      "干细胞周围的细胞外基质中的调控因子",
      "以上都正确",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "以上都正确",
        "干细胞巢（微环境）由与干细胞相邻的外围细胞、黏附分子、细胞外基质及其中的细胞因子等调控因子组成，各项均属于其组成成分。原书单选答案第 22 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1014",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胚胎干细胞和成体组织干细胞均可分化形成多种类型细胞，下列关于细胞分化的叙述中，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "多能干细胞分化程度高于专能干细胞",
      "干细胞分化的过程是不可逆转的",
      "细胞分化是基因的选择性表达造成的",
      "细胞分化只发生在胚胎时期",
      "成年个体组织中无细胞分化现象",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细胞分化是基因的选择性表达造成的",
        "细胞分化的根本原因是基因的选择性表达；专能干细胞分化程度高于多能干细胞（而非相反），分化在一定条件下可被逆转（如重编程），分化不仅发生在胚胎期、成体组织中也存在细胞分化（如补充更新）。原书单选答案第 23 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1015",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列有关过渡放大细胞的叙述中，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "是干细胞经过不对称分裂产生的",
      "可用于增加分化细胞的数目",
      "不具有分化潜能",
      "增殖速率显著高于干细胞",
      "对维持组织稳态有重要作用",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "不具有分化潜能",
        "过渡放大细胞（TAC）具有一定（有限）的分化潜能，是干细胞与分化细胞之间的过渡细胞，「不具有分化潜能」错误；TAC由干细胞经不对称分裂产生、增殖速率显著高于干细胞、可增加分化细胞数目并参与组织稳态维持。原书单选答案第 25 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1016",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于干细胞巢的正确叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "是干细胞赖以生存和维持功能的微环境",
      "干细胞周围的细胞外基质是干细胞巢的重要组成成分",
      "干细胞巢中的分泌因子参与调控干细胞的增殖与分化",
      "干细胞具有调控干细胞巢的功能",
      "以上都正确",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "以上都正确",
        "干细胞巢是干细胞赖以生存和维持功能的微环境，含细胞外基质、分泌因子等成分，参与调控干细胞增殖分化，且干细胞也能对干细胞巢进行反馈调控，各项均正确。原书单选答案第 27 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1017",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于干细胞的正确叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "细胞分化改变干细胞的遗传信息",
      "造血干细胞分化成红细胞的过程是可逆的",
      "干细胞不会发生衰老和凋亡",
      "组织干细胞发生癌变可形成肿瘤干细胞",
      "干细胞中内质网、高尔基复合体比较发达",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "组织干细胞发生癌变可形成肿瘤干细胞",
        "干细胞在自我更新/分化时遗传信息一般不改变；造血干细胞分化为红细胞沿不可逆方向进行；干细胞也会发生衰老和凋亡；干细胞往往表现为增殖旺盛。组织干细胞（成体干细胞）在一定条件下发生癌变可形成肿瘤干细胞。原书单选答案第 29 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1018",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于正常干细胞和肿瘤干细胞差异的叙述中，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "正常干细胞的增殖过程受到基因调控，肿瘤干细胞的增殖过程不受基因调控",
      "正常干细胞只能迁移到特定组织，而肿瘤干细胞可迁移到很多部位",
      "二者都失去了正常分化的能力",
      "二者的遗传信息都没有发生改变",
      "二者具有快速增殖能力",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "正常干细胞只能迁移到特定组织，而肿瘤干细胞可迁移到很多部位",
        "正常干细胞受控地迁移到特定组织，肿瘤干细胞则易发生转移、可迁移到很多部位；肿瘤干细胞增殖同样受（异常）基因调控、其遗传信息多已改变，正常干细胞仍能正常分化，二者增殖特性不同。原书单选答案第 30 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1019",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "研究发现直肠癌中存在癌细胞和肿瘤干细胞。姜黄素治疗可诱发癌细胞凋亡，而肿瘤干细胞膜上高表达ABCG2转运体蛋白，可排出姜黄素使细胞逃避凋亡并增殖分化形成癌细胞。由此可推测",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肿瘤干细胞与癌细胞中基因的表达不尽相同",
      "联合使用ABCG2转运体蛋白抑制剂和姜黄素治疗大肠癌，可促进肿瘤干细胞的凋亡",
      "治疗肿瘤的关键是杀死肿瘤干细胞",
      "肿瘤干细胞是化疗后肿瘤复发的主要原因",
      "以上都正确",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "以上都正确",
        "肿瘤干细胞与癌细胞基因表达存在差异；联合 ABCG2 抑制剂与姜黄素可解除耐药促进肿瘤干细胞凋亡；治疗需靶向杀死肿瘤干细胞，肿瘤干细胞是化疗后复发的关键原因，各项推测均成立。原书单选答案第 32 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1020",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "干细胞治疗是一项很新的生物治疗技术，这类干细胞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "具有分裂能力，但不能进一步分化成不同类型的细胞",
      "不具有分裂能力，也不能进一步分化成不同类型的细胞",
      "不具有分裂能力，但能进一步分化成不同类型的细胞",
      "具有分裂能力，也能进一步分化成不同类型的细胞",
      "以上特点都不具有",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "具有分裂能力，也能进一步分化成不同类型的细胞",
        "用于干细胞治疗的干细胞既具有（自我更新）分裂增殖能力，又能进一步分化成不同类型的细胞，这正是其能修复、替换受损组织的基础。原书单选答案第 33 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1021",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "临床上应用最多的造血干细胞标志物是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["CD34", "CD38", "SSEA-3", "CD133", "CD44"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CD34",
        "CD34 是造血干细胞表面最常用、临床应用最多的标志物，用于造血干/祖细胞的分离与鉴定。原书单选答案第 34 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-a1022",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于乳腺癌干细胞的正确叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "具有自我更新能力",
      "易于形成转移灶",
      "可在免疫缺陷型小鼠体内形成与原发肿瘤类型相同的肿瘤",
      "是乳腺癌治疗的重要目标",
      "以上均正确",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "以上均正确",
        "乳腺癌干细胞具有自我更新能力、易形成转移灶、可在免疫缺陷型小鼠体内再现原发肿瘤类型，且是乳腺癌治疗的重点靶标，各项叙述均正确。原书单选答案第 35 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-x001",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "干细胞具有的特征之一是（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "干细胞本身不是终末分化细胞",
      "干细胞具有自我更新的能力",
      "干细胞的分化是不可逆的",
      "干细胞可连续分裂几代，也可较长时间处于静息状态",
      "干细胞分裂产生的子细胞或者保持为干细胞或者分化为特定细胞",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "干细胞本身不是终末分化细胞",
        "原书多选答案第 1 题为 ABDE（干细胞非终末分化细胞、具自我更新能力、可连续分裂或较长期静息、其子细胞或保持为干细胞或分化为特定细胞）。此处取其中一个正确项「干细胞本身不是终末分化细胞」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-x002",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "干细胞根据发育潜能分为的类型之一是（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: ["全能干细胞", "胚胎干细胞", "多能干细胞", "单能干细胞", "组织干细胞"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "全能干细胞",
        "原书多选答案第 2 题为 ACD（按发育潜能分为全能、多能和单能干细胞）。此处取其中一个正确项「全能干细胞」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-x003",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胚胎干细胞具有的特点之一是（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "能分化成三个胚层的细胞",
      "核质比比较大",
      "胚胎干细胞植入免疫缺陷小鼠皮下可产生畸胎瘤",
      "端粒酶活性高",
      "细胞内碱性磷酸酶活性高",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "能分化成三个胚层的细胞",
        "原书多选答案第 3 题为 ABCDE（能分化三个胚层、核质比大、可致畸胎瘤、端粒酶活性高、碱性磷酸酶活性高，各项均正确）。此处取其中一个正确项「能分化成三个胚层的细胞」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-x004",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于过渡放大细胞的正确叙述之一是（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "过渡放大细胞的分化程度低于干细胞",
      "过渡放大细胞是由干细胞通过对称分裂产生的子代细胞",
      "过渡放大细胞是介于干细胞和分化细胞之间的过渡细胞",
      "过渡放大细胞的增殖速率显著高于干细胞",
      "过渡放大细胞具有一定的分化潜能",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "过渡放大细胞是介于干细胞和分化细胞之间的过渡细胞",
        "原书多选答案第 4 题为 CDE（TAC介于干细胞与分化细胞之间、增殖速率显著高于干细胞、具有一定分化潜能）。此处取其中一个正确项「过渡放大细胞是介于干细胞和分化细胞之间的过渡细胞」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch17-stem-cell-x005",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于间充质干细胞特性的正确叙述之一是（原题为多项选择题，此处取其中一个正确项）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "具有强大的增殖能力",
      "具有多向分化潜能",
      "具有免疫调节功能",
      "广泛分布于骨髓、脂肪和肌肉等多种组织中",
      "间充质干细胞是一类异质性的干细胞",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "具有强大的增殖能力",
        "原书多选答案第 5 题为 ABCDE（强大的增殖能力、多向分化潜能、免疫调节功能、广泛分布、异质性，各项均正确，作者于兵）。此处取其中一个正确项「具有强大的增殖能力」。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B 型配伍题：本书无 B1/B2 型，置空数组 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];