import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学细胞生物学实验指导与习题集（第4版）— 第4章 细胞膜与物质的穿膜运输 题库提取（等比取样）
 * 来源：《医学细胞生物学实验指导与习题集》第4版（人民卫生出版社）
 *
 * == 统计报告（本文件题量 = 章节等比缩放预算）==
 * - 名词解释：13 题
 * - 单项选择题（a1-single）：27 题（其中多项选择题映射 3 题）
 * - 独立记分题合计：40 题（等于本文件预算 40）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含名词解释 13、单项选择题 55、多项选择题 15，无配伍/填空/简答。
 *   55 道单选键号齐全，所选单选题均锚定源参考答案键号并与选项文本一一对照；多项选择题按项目
 *   规约映射为 a1-single 并只取其中一个正确项。原书为双栏排版，题干/选项/题号交错散落，已按
 *   细胞生物学医学语义重建完整选项集合（单选/映射 4~5 项），数值与结构（3Na⁺/2K⁺、侧向扩散、
 *   网格蛋白、脂双层等）均保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "cell-bio-ch04-membrane-transport";
const locatorBase =
  "《医学细胞生物学实验指导与习题集》第4版 第4章 细胞膜与物质的穿膜运输 习题集（核对PDF 第122–129页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），13 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch04-membrane-transport-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：脂质体（liposome）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脂质体",
        "脂质体是根据磷脂分子可以在水相中自我装配成稳定的脂双层膜的球形结构的趋势而制备的人工球形脂质小囊。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：囊泡运输（vesicular transport）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "囊泡运输",
        "大分子和颗粒物质被运输时并不直接穿过细胞膜，都是由膜包围形成囊泡，通过一系列膜囊泡的形成和融合来完成转运过程，故称为囊泡运输。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：流动镶嵌模型（fluid mosaic model）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "流动镶嵌模型",
        "流动镶嵌模型由 Singer 和 Nicolson 于 1972 年提出，认为生物膜是嵌有蛋白质的脂类二维排列的液态体，是一种动态的、不对称的、具有流动性特点的结构，膜中蛋白质以不同形式与脂双分子层结合。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：脂筏（lipid rafts）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脂筏",
        "脂筏是脂双层内局部较厚、富含胆固醇、鞘磷脂及特定类型膜蛋白的、流动性较低的微区，参与信号转导、受体介导的胞吞以及胆固醇代谢运输等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：主动运输（active transport）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "主动运输",
        "主动运输是载体蛋白介导的、直接或间接消耗能量的物质逆浓度梯度或电化学梯度进行的穿膜运输方式。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：易化扩散（facilitated diffusion）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "易化扩散",
        "易化扩散是由载体蛋白介导的、不消耗能量、顺物质浓度梯度或电化学梯度进行的穿膜运输方式。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：协同运输（cotransport）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "协同运输",
        "协同运输即一种物质的运输依赖另一种物质同时转运的穿膜运输方式。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：受体介导的胞吞作用（receptor-mediated endocytosis）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "受体介导的胞吞作用",
        "受体介导的胞吞作用指细胞通过受体的介导选择性高效摄取细胞外特定大分子物质的过程，可使细胞特异性地摄取细胞外含量很低的成分。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：简单扩散（simple diffusion）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "简单扩散",
        "简单扩散是无需膜运输蛋白参与、小分子靠热运动通过膜脂分子间隙、从高浓度向低浓度一侧进行的穿膜扩散方式。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：被动运输（passive transport）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "被动运输",
        "被动运输是无需消耗能量、小分子或离子通过简单扩散、离子通道扩散、易化扩散实现物质顺浓度梯度或电化学梯度的穿膜运输。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-term011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：单位膜（unit membrane）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单位膜",
        "单位膜是膜性结构或细胞器的膜具有的相似结构，电镜下呈内外两层致密的深色带和中间的浅色带（两暗一明）结构。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-term012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：连续性分泌（continuous secretion）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "连续性分泌",
        "连续性分泌又称固有分泌，指外输性蛋白质在糙面内质网合成之后，转运至高尔基复合体，经修饰、浓缩、分选，形成分泌泡，随即被运送至细胞膜，与质膜融合将分泌物排出细胞外的过程。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-term013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：受调分泌（regulated secretion）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "受调分泌",
        "受调分泌见于特定类型细胞中，分泌性蛋白合成后先储存于分泌囊泡中，只有当细胞接受到细胞外信号（如激素）的刺激，引起分泌囊泡与细胞膜融合，将分泌物释放到细胞外。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 单项选择题（含多项选择题的映射），27 道（单选 24 + 多选映射 3） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1001",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "生物膜的主要化学成分是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["蛋白质与核酸", "蛋白质与脂类", "蛋白质与糖类", "糖脂", "糖蛋白"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "蛋白质与脂类",
        "生物膜的主要化学成分是蛋白质与脂类（脂质），另有少量糖类。原书单项选择题答案第 1 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1002",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "乙酰胆碱的出胞方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["受调分泌", "固有分泌", "被动运输", "易化扩散", "离子通道扩散"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "受调分泌",
        "神经递质乙酰胆碱储存在突触小泡中，受信号刺激随囊泡与突触前膜融合而释放，属受调分泌（规律性分泌）。原书单项选择题答案第 2 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1003",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "蛋白聚糖的出胞方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["固有分泌", "受调分泌", "协同运输", "易化扩散", "离子通道扩散"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "固有分泌",
        "蛋白聚糖等细胞外基质成分通常由细胞持续、连续地分泌（固有/连续性分泌）。原书单项选择题答案第 3 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1004",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "膜脂分子最主要的运动方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["侧向扩散", "翻转运动", "旋转运动", "弯曲运动", "伸缩振荡运动"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "侧向扩散",
        "膜脂分子最主要、最常见的运动方式是脂分子在膜平面内的侧向扩散（横向移动），翻转运动最为少见。原书单项选择题答案第 4 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1005",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞吞噬过程中，参与伪足形成与伸出的蛋白质主要是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["肌动蛋白", "微管蛋白", "肌球蛋白", "波形蛋白", "角蛋白"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌动蛋白",
        "吞噬作用中伪足的形成与伸出依赖肌动蛋白（actin）及其聚合/解聚。原书单项选择题答案第 5 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1006",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胞吞过程中，提供牵动质膜内陷的包被蛋白是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["COPII 蛋白", "肌动蛋白", "COPI 蛋白", "网格蛋白", "肌球蛋白"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "网格蛋白",
        "网格蛋白（clathrin）在有被小泡的形成中包被质膜内存区，提供牵动质膜内陷的动力。原书单项选择题答案第 6 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1007",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "葡萄糖穿红细胞膜的运输过程中，载体蛋白发生",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "在脂双层中来回移动",
      "可逆的构象改变",
      "形成通道",
      "在脂双层中翻转",
      "在脂双层中扩散",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "可逆的构象改变",
        "葡萄糖经红细胞膜上的载体蛋白（GLUT）以易化扩散方式转运，载体蛋白通过可逆的构象改变“跨膜”转运底物，自身不移动。原书单项选择题答案第 8 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1008",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "构成动物细胞细胞外被的主要是细胞膜表面的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "细胞壁",
      "糖蛋白与糖脂外伸的糖链",
      "血影蛋白",
      "膜内在蛋白",
      "胆固醇",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "糖蛋白与糖脂外伸的糖链",
        "细胞外被（糖衣）是细胞膜表面糖蛋白与糖脂分子外伸的寡糖链共同构成的覆盖层。原书单项选择题答案第 10 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1009",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞膜的流动镶嵌模型认为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "两层蛋白质分子中间夹着一层类脂",
      "脂双分子层两侧附着蛋白质",
      "脂双分子层中间夹着一层蛋白质",
      "脂分子与蛋白质间隔排列",
      "脂双分子层镶嵌着蛋白质",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脂双分子层镶嵌着蛋白质",
        "流动镶嵌模型认为膜由流动的脂双分子层构成基本框架，蛋白质以镶嵌（插入、贯穿等）形式分布于其中。原书单项选择题答案第 11 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1010",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "物质不需要膜蛋白帮助、不消耗能量、顺浓度梯度通过膜的自由扩散称为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["简单扩散", "易化扩散", "主动运输", "胞吞作用", "胞吐作用"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "简单扩散",
        "简单扩散无需膜蛋白参与、不消耗能量，仅靠物质顺浓度梯度通过膜脂双层。原书单项选择题答案第 12 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1011",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以简单扩散方式快速通过细胞膜的物质有",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["Na⁺", "CO₂", "氨基酸", "葡萄糖", "甘油"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CO₂",
        "CO₂ 等非极性小分子气体可经简单扩散快速透过细胞膜；Na⁺、氨基酸、葡萄糖等需依赖膜转运蛋白。原书单项选择题答案第 13 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1012",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "由载体蛋白参与而不消耗代谢能、顺浓度梯度进行的穿膜运输方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["简单扩散", "主动运输", "易化扩散", "胞吞作用", "胞吐作用"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "易化扩散",
        "易化扩散由载体蛋白介导、不消耗能量、顺浓度梯度（电化学梯度）进行。原书单项选择题答案第 14 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1013",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "载体蛋白顺浓度梯度转运 Na⁺ 入胞的同时，将葡萄糖逆浓度梯度一起带入胞内，此种穿膜运输方式为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["被动运输", "单运输", "同向协同运输", "胞吞作用", "对向协同运输"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "同向协同运输",
        "Na⁺ 与葡萄糖沿同一方向共同转运，属同向协同（共）运输。原书单项选择题答案第 21 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1014",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "葡萄糖经载体蛋白的介导，进入大多数动物细胞内的方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["简单扩散", "易化扩散", "离子泵", "协同运输", "通道运输"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "易化扩散",
        "多数动物细胞通过载体蛋白以易化扩散（GLUT 族）从胞外摄取葡萄糖。原书单项选择题答案第 22 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1015",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞膜中的脂锚定蛋白与膜脂类相结合的化学键是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["氢键", "肽键", "共价键", "疏水键", "磷酸二酯键"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "共价键",
        "脂锚定蛋白以共价键（如 GPI 锚）与膜脂类（脂双层内脂分子）结合。原书单项选择题答案第 23 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1016",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "低密度脂蛋白（LDL）进入细胞的方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "协同运输",
      "易化扩散",
      "主动运输",
      "吞噬作用",
      "受体介导的胞吞作用",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "受体介导的胞吞作用",
        "LDL 借助其表面载脂蛋白 B 与细胞膜 LDL 受体特异性结合，经受体介导的胞吞作用被选择性摄取。原书单项选择题答案第 25 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1017",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "小肠和肾小管上皮细胞摄取葡萄糖的转运方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["共运输", "对向运输", "被动运输", "易化扩散", "简单扩散"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "共运输",
        "小肠和肾小管上皮细胞经顶面以 Na⁺-葡萄糖协同共运输（同向转运）逆浓度摄取葡萄糖。原书单项选择题答案第 26 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1018",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "人体内 O₂、CO₂、N₂、水和甘油等进出细胞膜的穿膜运输方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["简单扩散", "易化扩散", "主动运输", "胞吞作用", "胞吐作用"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "简单扩散",
        "O₂、CO₂、N₂ 等小分子气体及水、甘油等主要由简单扩散透过细胞膜。原书单项选择题答案第 28 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1019",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在细胞膜的物质转运中，Na⁺ 穿膜运输的方式有",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "简单扩散和易化扩散",
      "简单扩散和主动运输",
      "易化扩散和主动运输",
      "易化扩散和离子通道扩散",
      "离子通道扩散和主动运输",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "离子通道扩散和主动运输",
        "Na⁺ 可经离子通道（被动扩散）内流，亦可由 Na⁺-K⁺ 泵（主动运输）泵出，故其穿膜运输方式为离子通道扩散和主动运输。原书单项选择题答案第 30 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1020",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "膜脂分子最不容易发生的运动方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["旋转运动", "侧向扩散", "翻转运动", "弯曲运动", "伸缩振荡运动"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "翻转运动",
        "脂分子从膜单层翻转到另一单层（翻转运动）需要亲水头部穿越疏水核心，能量上最不利、最难发生。原书单项选择题答案第 33 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1021",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "Na⁺-K⁺ 泵水解 1 分子 ATP 可转运",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "3 个 Na⁺、2 个 K⁺",
      "3 个 K⁺、2 个 Na⁺",
      "2 个 Na⁺、2 个 K⁺",
      "3 个 Na⁺、3 个 K⁺",
      "3 个 Na⁺、1 个 K⁺",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "3 个 Na⁺、2 个 K⁺",
        "Na⁺-K⁺ 泵（Na⁺-K⁺ ATPase）每水解 1 分子 ATP，泵出 3 个 Na⁺、泵入 2 个 K⁺。原书单项选择题答案第 34 题为 A，比值保留原值。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1022",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "处于持续开放状态的膜通道蛋白是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "乙酰胆碱受体",
      "K⁺ 通道",
      "Ca²⁺ 通道",
      "应力激活阳离子通道",
      "水通道",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "水通道",
        "水通道（如 AQP 水孔蛋白）通常持续开放，允许水分子持续通过；多数离子通道为门控、非持续开放。原书单项选择题答案第 35 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1023",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "细胞吞入固体颗粒物质的过程为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["胞吞作用", "吞噬作用", "吞饮作用", "受体介导的内吞作用", "胞吐作用"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "吞噬作用",
        "细胞吞入较大的固体颗粒物质（如细菌、碎片）的过程称为吞噬作用。原书单项选择题答案第 36 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-a1024",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列过程中，不属于小分子和离子穿膜运输的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["胞吞作用", "简单扩散", "易化扩散", "主动运输", "离子通道扩散"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胞吞作用",
        "胞吞作用用于摄取大分子或颗粒（非小分子/离子的穿膜运输）；简单扩散、易化扩散、主动运输与离子通道扩散均属小分子/离子的穿膜运输。原书单项选择题答案第 38 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-x001",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（原多选题）关于细胞膜上的钠钾泵，正确的叙述是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "具有 ATP 酶的活性",
      "钠离子的结合位点位于胞膜外侧",
      "只能顺浓度梯度转运物质",
      "介导被动运输",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "具有 ATP 酶的活性",
        "原题为多项选择题，钠钾泵（Na⁺-K⁺ ATPase）具有 ATP 酶活性、由大小两种亚基组成、乌本苷为其抑制剂、介导逆浓度梯度运输（源参考答案键号 1.ABDE）。本项映射为单选并按规约只取其中一个正确项（具有 ATP 酶活性）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-x002",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（原多选题）载体蛋白介导的穿膜运输的特点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "通过构象改变介导物质运输",
      "均介导顺浓度梯度运输溶质",
      "对被转运物质进行共价修饰",
      "扩散速率随溶质浓度的升高可无限增大",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "通过构象改变介导物质运输",
        "原题为多项选择题，载体蛋白介导运输的特点是通过构象改变介导物质运输、有选择性地转运特异性分子、对被转运物质不进行共价修饰（源参考答案键号 12.BDE）。本项映射为单选并按规约只取其中一个正确项。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-cell-bio-ch04-membrane-transport-x003",
    order: 40,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "（原多选题）通道蛋白介导的跨膜运输的特点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: xMapNote,
      sourceIds: [],
    },
    choices: [
      "转运速度快",
      "逆电化学梯度转运物质",
      "多数通道持续开放",
      "通道蛋白形成贯穿膜脂双层的疏水孔道",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "转运速度快",
        "原题为多项选择题，通道蛋白介导跨膜运输的特点是转运速度快、选择性地转运特定物质、形成贯穿脂双层的亲水孔道、多数通道不持续开放（源参考答案键号 13.BCDE）。本项映射为单选并按规约只取其中一个正确项（转运速度快）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 本书无 B 型配伍题，bGroups 为空数组 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];