import type { LearnerCourseState } from "@/types/learning";

export const tcmDiagnosticsDemoLearnerState = {
  id: "demo-state-tcm-diagnostics",
  courseId: "course-tcm-diagnostics",
  dataMode: "demo",
  demoLabel: "当前为结构演示",
  profile: {
    displayName: "张同学",
    major: "中西医结合临床",
    avatarLabel: "N",
  },
  overallProgress: 38,
  learnedUnits: 32,
  totalUnits: 85,
  currentStage: {
    id: "stage-diagnostic-methods-to-eight-principles",
    label: "闻诊 → 八纲辨证",
    chapterIds: [
      "chapter-listening-smelling",
      "chapter-inquiry",
      "chapter-pulse",
      "chapter-eight-principles",
    ],
    assessmentLabel: "9 天后",
  },
  currentChapterId: "chapter-inquiry",
  currentKnowledgePointId: "kp-inquiry-diet-taste",
  defaultRouteId: "understand",
  chapterProgress: [
    {
      chapterId: "chapter-introduction",
      progress: 100,
      learnedUnits: 4,
      totalUnits: 4,
      completedKnowledgePointIds: [
        "kp-introduction-content",
        "kp-introduction-diagnosis-pattern",
        "kp-introduction-principles",
        "kp-introduction-rules",
      ],
    },
    {
      chapterId: "chapter-inspection",
      progress: 100,
      learnedUnits: 8,
      totalUnits: 8,
      completedKnowledgePointIds: [
        "kp-inspection-spirit",
        "kp-inspection-complexion",
        "kp-inspection-body",
        "kp-inspection-posture",
      ],
    },
    {
      chapterId: "chapter-tongue",
      progress: 75,
      learnedUnits: 6,
      totalUnits: 8,
      completedKnowledgePointIds: [
        "kp-tongue-method",
        "kp-tongue-body",
        "kp-tongue-coating",
      ],
    },
    {
      chapterId: "chapter-listening-smelling",
      progress: 60,
      learnedUnits: 3,
      totalUnits: 5,
      completedKnowledgePointIds: [
        "kp-listening-sounds",
        "kp-listening-language",
        "kp-listening-breath-cough",
      ],
    },
    {
      chapterId: "chapter-inquiry",
      progress: 42,
      learnedUnits: 5,
      totalUnits: 12,
      completedKnowledgePointIds: [
        "kp-inquiry-cold-heat",
        "kp-inquiry-sweat",
        "kp-inquiry-pain",
      ],
    },
    {
      chapterId: "chapter-pulse",
      progress: 18,
      learnedUnits: 2,
      totalUnits: 11,
      completedKnowledgePointIds: [
        "kp-pulse-method",
        "kp-pulse-normal",
      ],
    },
    {
      chapterId: "chapter-eight-principles",
      progress: 0,
      learnedUnits: 0,
      totalUnits: 9,
      completedKnowledgePointIds: [],
    },
    {
      chapterId: "chapter-disease-nature",
      progress: 0,
      learnedUnits: 0,
      totalUnits: 11,
      completedKnowledgePointIds: [],
    },
    {
      chapterId: "chapter-organs",
      progress: 0,
      learnedUnits: 0,
      totalUnits: 14,
      completedKnowledgePointIds: [],
    },
  ],
  sessionDurationMinutes: 45,
  sessionSteps: [
    {
      id: "session-understand",
      order: 1,
      routeId: "understand",
      minutes: 12,
      title: "双视角理解",
      detail: "拆解证据与概念关系",
      drawerTitle: "建立双视角概念",
    },
    {
      id: "session-express",
      order: 2,
      routeId: "express",
      minutes: 15,
      title: "主观题输出",
      detail: "默写并补齐采分点",
      drawerTitle: "完成一道主观题",
    },
    {
      id: "session-apply",
      order: 3,
      routeId: "apply",
      minutes: 18,
      title: "案例迁移",
      detail: "完成一条辨证推理链",
      drawerTitle: "完成一个辨证案例",
    },
  ],
} satisfies LearnerCourseState;
