import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学遗传学 学习指导与习题集（第4版）— 第9章 染色体畸变 题库提取（等比取样）
 * 来源：《医学遗传学学习指导与习题集》第4版（人民卫生出版社，主编：张咸宁、杨玲）
 *
 * == 统计报告（本文件题量 = 按“每教材 600、章节等比缩放”预算）==
 * - 名词解释：10 题
 * - A1/A2/X 型选择题（统一映射为 a1-single 单选）：17 题（A1 前10 道 + A2 病例型前7 道）
 * - 简答题 / 病例（映射 short-answer 或 case）：2 题（均为 short-answer；本章无非选择型 case）
 * - B1 共用备选答案配伍题：3 组、共 10 个成员
 * - 独立记分题合计：39 题（含 B1 组成员；须等于本文件预算 39）
 * - 缺失答案：0 题；无法可靠提取：0 题
 * - 说明：本章原书依序含名词解释 10、A1 型选择题 20、A2 病例型选择题 10、
 *   B1 型共用备选答案配伍题 3 组（31~34、35~38、39~40）与简答题 2；合计 52 道独立
 *   记分题。本文件按 39 道预算等比取材：全部 10 道名词解释、A1 前 10 道、A2 前 7 道
 *   （含 Turner / Klinefelter / Edwards / 猫叫 5p- / 多X 综合征与 14/21、21/21 罗氏易位
 *   风险计算等病例），以及全部 3 组 B1 与 2 道简答题。本章无 X 型多选，故无需 xMapNote；
 *   亦无非选择型病案解析题，故无 case。A2 病例型选择题按规约仍映射为 a1-single。
 *   OCR 错字已按语义恢复（如“染色体筠变”→染色体畸变、核型符号中的全角/半角破折号统一）、
 *   全部畸变类型、核型符号、断裂点位（arms·band，如 46,XY,t(4;6)(q35;q21)、inv(9)
 *   (p12q31)、del(1)(pter→q21:) 等）与风险数值（1、1/2 等）均按原值保留，未捏造。
 *   选项顺序已随机重排并同步 correctChoiceIndex（0 起），正确项逐一对齐源参考答案。
 *
 * 解析内容位于 answer.content 数组的第二个元素。
 */

const topic = "medical-genetics-ch9-chromosome-aberrations";
const locatorBase =
  "《医学遗传学学习指导与习题集》第4版 第9章 染色体畸变 复习思考题 习题（PDF 第53–59页）";
const promptNote =
  "题干改写；原题来自用户提供的题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原书为X型多选题，按项目规约映射为a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据上传题集整理并改写，尚未与权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），10 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：染色体畸变（chromosomal aberration）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "染色体畸变",
        "染色体畸变是指在某些条件下，染色体的形态结构发生异常改变的现象。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：三倍体（triploid）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "三倍体",
        "三倍体（triploid）指在 2n 的基础上增加了一个染色体组（n），使得染色体总数为 3n 的个体或细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：亚二倍体（hypodiploid）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "亚二倍体",
        "亚二倍体（hypodiploid）指比正常二倍体（2n）少一条或几条染色体或染色体片段的细胞或个体。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：超二倍体（hyperdiploid）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "超二倍体",
        "超二倍体（hyperdiploid）指细胞或个体中的染色体数目多了一条或数条的现象。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：假二倍体（pseudodiploid）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "假二倍体",
        "假二倍体（pseudodiploid）指由于染色体重排而破坏了连锁关系所形成的异常染色体组型，如由 14/21 易位造成的易位型 21 三体综合征。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：嵌合体（mosaic / chimera）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "嵌合体",
        "嵌合体（mosaic 或 chimera）指同一个体同时存在 2 种或以上核型的细胞系。需注意：同源嵌合体（mosaic）指由遗传上不同的细胞类型或组织组成的生物体；异源嵌合体（chimera）指由来自不同基因型的合子演变而来的两个或多个不同细胞系混合构成的个体。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：罗氏易位（Robertsonian translocation）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "罗氏易位",
        "罗氏易位（Robertsonian translocation）指 2 条近端着丝粒染色体在着丝粒部位或其附近发生断裂后，两者的长臂在着丝粒处接合在一起，形成一条由长臂构成的衍生染色体。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：缺失（deletion）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "缺失",
        "缺失（deletion）指染色体片段的丢失，位于该片段的基因也随之发生丢失。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：重复（duplication）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "重复",
        "重复（duplication）指一条染色体上某一片段增加了一份以上，使这些片段的基因多了一份或几份的现象。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：易位（translocation）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "易位",
        "易位（translocation）指 2 条染色体同时发生断裂，一条染色体的断片移接到另一条非同源染色体的臂上的现象。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2 型选择题（统一映射为 a1-single），17 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1001",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于染色体断裂（chromosomal break），下列哪一项是错误的？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "染色体断裂在染色体组中随机发生",
      "染色体断裂后，可形成不稳定的黏性末端（sticky end）",
      "BRCA1 蛋白参与染色体断裂的修复",
      "电离辐射可增高染色体断裂发生的频率，在Fanconi贫血中可见染色体断裂",
      "染色体断裂后，可能导致染色体结构畸变（如易位）",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "染色体断裂在染色体组中随机发生",
        "原书 A1 型选择题答案第一题为 E。“染色体断裂在染色体组中随机发生”是错误的：染色体的脆性位点并非随机分布，某些区域更易发生断裂；其余选项均为关于染色体断裂的正确描述。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1002",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "如果在某一体细胞中，染色体的数目在二倍体的基础上增加一条，可形成",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["单倍体", "三倍体", "二倍体", "三体", "部分三体"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "三体",
        "原书 A1 型选择题答案第二题为 D。染色体数目在二倍体基础上增加一条（2n+1）形成三体（trisomy）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1003",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "形成含有 3 种细胞系的嵌合体的可能原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "受精卵第一次卵裂时染色体不分离",
      "受精卵第二次卵裂之后染色体丢失",
      "受精卵第二次卵裂之后染色体不分离",
      "减数分裂 II 发生染色体不分离",
      "减数分裂 I 发生染色体不分离",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "受精卵第二次卵裂之后染色体不分离",
        "原书 A1 型选择题答案第三题为 D。胚胎卵裂期染色体不分离可产生多种核型的细胞系；早期卵裂中的不分离可形成 3 种细胞系的嵌合体。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1004",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "如果染色体的数目在二倍体的基础上减少一条，则形成",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["三倍体", "单体", "二倍体", "三体", "部分三体"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "单体",
        "原书 A1 型选择题答案第四题为 A。染色体数目在二倍体基础上减少一条（2n-1）形成单体（monosomy）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1005",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列关于平衡性相互易位的描述，哪一项正确？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "携带者通常具有显著的学习困难症状",
      "某些携带者生育染色体非平衡子代的风险大于 10%",
      "平衡性相互易位要么累及染色体的长臂，要么累及染色体的短臂",
      "平衡性相互易位不累及 X 染色体",
      "携带者配子形成时染色体配对形成四价体，原因是2条染色体总是分配至2个子细胞中",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "某些携带者生育染色体非平衡子代的风险大于 10%",
        "原书 A1 型选择题答案第五题为 B。平衡性相互易位携带者本身常无临床异常，但生育染色体不平衡子代的风险显著增高，部分可达 10% 以上；其余选项描述均有误。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1006",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "四倍体的形成原因可能是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "核内复制或核内有丝分裂",
      "双雌受精",
      "染色体不分离",
      "双雄受精",
      "不等交换",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "核内复制或核内有丝分裂",
        "原书 A1 型选择题答案第六题为 C。四倍体的形成机制是核内复制或核内有丝分裂（endoreduplication / endomitosis）；双雄、双雌受精主要导致三倍体。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1007",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "嵌合体形成的原因可能是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "生殖细胞形成过程中发生了染色体的丢失",
      "生殖细胞形成过程中发生了染色体的不分离",
      "卵裂过程中发生了染色体不分离",
      "卵裂过程中发生了同源染色体的错误配对",
      "生殖细胞形成过程中发生了染色体的错误配对",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "卵裂过程中发生了染色体不分离",
        "原书 A1 型选择题答案第七题为 B。嵌合体常因受精后卵裂过程中发生染色体不分离（有丝分裂不分离）而形成，产生 2 种或以上核型的细胞系。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1008",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "若某个体的核型为 46,XY,t(4;6)(q35;q21)，则表明",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "某一女性体内发生了染色体的插入",
      "某一男性体内发生了染色体的易位",
      "某一男性带有等臂染色体",
      "某一女性个体带有易位型的畸变染色体",
      "某一男性个体含有缺失型的畸变染色体",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "某一男性体内发生了染色体的易位",
        "原书 A1 型选择题答案第八题为 B。核型 46,XY,t(4;6)(q35;q21) 表明某一男性（46,XY）携带 4 号与 6 号染色体间的相互易位（t），断裂点位分别为 q35 与 q21。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1009",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "若某一个体的核型为 46,XX/47,XX,+21，则表明该个体为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "常染色体数目异常的嵌合体",
      "常染色体结构异常",
      "性染色体结构异常",
      "常染色体结构异常的嵌合体",
      "性染色体数目异常的嵌合体",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常染色体数目异常的嵌合体",
        "原书 A1 型选择题答案第九题为 E。核型 46,XX/47,XX,+21 同时含有正常二倍体与 21 三体两种细胞系，属于常染色体数目异常的嵌合体。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1010",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "近端着丝粒染色体之间通过着丝粒融合而形成的易位称为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["复杂易位", "串联易位", "单方易位", "罗氏易位", "不平衡易位"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "罗氏易位",
        "原书 A1 型选择题答案第十题为 C。两条近端着丝粒染色体通过着丝粒融合（断裂后长臂接合）形成的易位称为罗氏易位（Robertsonian translocation）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1011",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某女性患者，原发闭经，乳房发育不良，并伴有先天性心脏病、髋臼脱位，智力稍低。染色体检查发现核型为 48,XXXX，临床诊断为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "Klinefelter 综合征",
      "Turner 综合征",
      "两性畸形",
      "多 X 综合征",
      "Down 综合征",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多 X 综合征",
        "原书 A2 型选择题答案第二十一题为 D。核型 48,XXXX 为 X 染色体呈四体的多 X 综合征（女性多 X 综合征），表现为原发闭经、乳房发育不良等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1012",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某高龄孕妇经产前诊断发现胎儿染色体核型为 46,XX,-14,+t(14q21q)。为确认额外第 21 号染色体的来源，对孕妇及其丈夫进行了染色体检查。核型分析结果显示孕妇为 14/21 平衡易位携带者。该孕妇最可能的核型是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "45,XX,-14,-21,+t(14q21q)",
      "47,XX,+21",
      "46,XX,-14,+t(14q21q)",
      "46,XX,-14,-21,+t(14q21q)",
      "46,XX/47,XX,+21",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "45,XX,-14,-21,+t(14q21q)",
        "原书 A2 型选择题答案第二十二题为 C。14/21 平衡易位携带者核型为 45,XX,-14,-21,+t(14q21q)，即第 14、21 号各缺失一条并由罗氏易位衍生染色体（t(14q21q)）代偿。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1013",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某对夫妇婚后自发流产两次。染色体检查结果显示，妻子为 21/21 平衡易位携带者，丈夫核型正常。他们生下的活婴为先天愚型患儿的风险是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["1/4", "1/2", "1/3", "1", "3/4"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "1",
        "原书 A2 型选择题答案第二十三题为 A。为 21/21 罗氏易位携带者时，其产生的全部配子携带 21 号缺失或额外拷贝，所有活婴均为 21 三体（先天愚型），故风险为 1（100%）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1014",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某女性患者，原发闭经，身高 145cm，肘外翻，后发际低，有蹼颈等。染色体检查示核型为 45,X。临床诊断为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "Klinefelter 综合征",
      "两性畸形",
      "Edwards 综合征",
      "Turner 综合征",
      "Down 综合征",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Turner 综合征",
        "原书 A2 型选择题答案第二十四题为 D。核型 45,X 为性染色体单体，临床表现为 Turner 综合征（原发闭经、身材矮小、肘外翻、后发际低、蹼颈）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1015",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某男性患者，30 岁，临床表现为不育，第二性征发育不明显且呈女性化，睾丸小，阴茎发育不良，乳房女性化等。核型为 47,XXY。临床诊断为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "Klinefelter 综合征",
      "Down 综合征",
      "Edwards 综合征",
      "Turner 综合征",
      "两性畸形",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Klinefelter 综合征",
        "原书 A2 型选择题答案第二十五题为 B。核型 47,XXY 为性染色体异常，临床表现为 Klinefelter 综合征（不育、第二性征女性化、睾丸小、乳房女性化）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1016",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某男性新生儿，主要临床表现有精神发育迟缓、生长发育迟缓、肌张力亢进、特殊的握拳姿势和摇椅型足。临床诊断为 Edwards 综合征。可能的核型为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["47,XY,-18", "47,XX,+18", "46,XX,-18", "47,XY,+18", "46,XY,+18"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "47,XY,+18",
        "原书 A2 型选择题答案第二十六题为 C。男性新生儿患 Edwards 综合征（18 三体综合征）的核型为 47,XY,+18。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-a1017",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某 2 岁女性患儿，生长发育迟缓、精神发育迟缓、头小、外眼角下斜、语言障碍、先天性心脏病，出生时体重低，哭声似猫叫。染色体检查发现核型为 46,XX,del(5)(p15)。临床诊断为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "5 三体综合征",
      "Down 综合征",
      "5p-综合征",
      "Turner 综合征",
      "Edwards 综合征",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "5p-综合征",
        "原书 A2 型选择题答案第二十七题为 B。核型 46,XX,del(5)(p15) 为 5 号染色体短臂末端缺失，临床表现为 5p-综合征（猫叫综合征），哭声似猫叫。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），2 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-short001",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "人类的染色体多倍体主要有哪些类型？请分别简述其产生的机制。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多倍体的类型及其产生机制",
        "人类染色体多倍体主要有三倍体（3n）和四倍体（4n）两类，多见于流产的胚胎中。三倍体的形成机制主要为双雄受精和双雌受精：①双雄受精，即同时有 2 个精子进入卵细胞使卵子受精，每个精子带有一个染色体组，与卵细胞中原有的一个染色体组共同形成三倍体受精卵；②双雌受精，即含有 1 个染色体组的精子与含有 2 个染色体组的异常卵细胞受精，即可形成三倍体受精卵。四倍体的形成机制是核内复制或核内有丝分裂，即在一次细胞分裂时 DNA 复制了 2 次，这样形成的 2 个子细胞均为四倍体。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-short002",
    order: 29,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述倒位染色体携带者出现习惯性流产的原因。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "倒位携带者习惯性流产的原因",
        "由于倒位发生时一般没有遗传物质的丢失，倒位携带者本身并无表型改变；但在减数分裂同源染色体配对联会时，由于基因顺序的颠倒，倒位的染色体无法与另一条正常染色体正常配对，而是形成特殊的结构——倒位环。若同源染色体在倒位环内发生重组，将产生 4 种类型的配子：①一种完全正常，与正常配子受精所形成的受精卵正常；②一种含有一条倒位染色体，受精后发育为倒位染色体携带者；③④其余 2 种均含有染色体部分片段的缺失和重复，与正常配子结合后可形成部分单体、部分三体的胚胎，这类胚胎由于遗传物质严重失衡，常引发自然流产。因此倒位染色体携带者在生育子女时常有发生习惯性流产的情况。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 病例 / 病案分析（case，非选择型）：本章无（A2 病例型选择已映射为 a1-single） */
const caseItems: readonly AssessmentItemDefinition[] = [];

/** B1 共用备选答案配伍题，3 组 × 共 10 成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-b001",
    order: 30,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["缺失", "臂内倒位", "臂间倒位", "易位", "重复"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-medical-genetics-ch9-chromosome-aberrations-b001m1",
        order: 30,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "若某个体的核型为 46,XX,dup(3)(q12q21)，则表明在其体内的染色体发生了",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "重复",
            "原书 B1 型题答案第三十一题为 E。核型 46,XX,dup(3)(q12q21) 中 dup 表示 3 号染色体长臂 q12 至 q21 片段发生重复。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-medical-genetics-ch9-chromosome-aberrations-b001m2",
        order: 31,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "若某个体的核型为 46,XX,inv(9)(p12q31)，则表明在其体内的染色体发生了",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "臂间倒位",
            "原书 B1 型题答案第三十二题为 C。核型 46,XX,inv(9)(p12q31) 中 inv 表示倒位，其断裂点分别位于 p12 与 q31（长短臂各一），属臂间倒位（pericentric inversion）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-medical-genetics-ch9-chromosome-aberrations-b001m3",
        order: 32,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "若某个体的核型为 46,XX,del(1)(pter→q21:)，则表明在其体内的染色体发生了",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "缺失",
            "原书 B1 型题答案第三十三题为 A。核型 46,XX,del(1)(pter→q21:) 中 del 表示缺失，从短臂端粒（pter）至长臂 q21 的片段缺失，属末端缺失。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-medical-genetics-ch9-chromosome-aberrations-b001m4",
        order: 33,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "若某个体的核型为 46,XX,t(4;5)(q35;p11)，则表明在其体内的染色体发生了",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "易位",
            "原书 B1 型题答案第三十四题为 D。核型 46,XX,t(4;5)(q35;p11) 中 t 表示 4 号与 5 号染色体间发生相互易位，断裂点分别为 q35 与 p11。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-b002",
    order: 34,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "45,X",
      "47,XX,+21",
      "46,XY,-14,+t(14q21q)",
      "46,XY,-14,-21,+t(14q21q)",
      "45,XX,-14,-21,+t(14q21q)",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-medical-genetics-ch9-chromosome-aberrations-b002m1",
        order: 34,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "某女性的第 21 号染色体多了一条，其核型描述为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "47,XX,+21",
            "原书 B1 型题答案第三十五题为 B。女性 21 三体的核型为 47,XX,+21（游离型 21 三体）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-medical-genetics-ch9-chromosome-aberrations-b002m2",
        order: 35,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "某女性的 X 染色体少了一条，其核型描述为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "45,X",
            "原书 B1 型题答案第三十六题为 A。女性 X 染色体缺一条（性染色体单体）的核型为 45,X（Turner 综合征）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-medical-genetics-ch9-chromosome-aberrations-b002m3",
        order: 36,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt:
          "某男性为易位型 21 三体综合征患者，核型分析显示，其额外的一条第 21 号和第 14 号染色体发生了罗氏易位，其核型描述为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "46,XY,-14,+t(14q21q)",
            "原书 B1 型题答案第三十七题为 C。男性易位型 21 三体（14/21 罗氏易位）的核型为 46,XY,-14,+t(14q21q)，即缺一条 14 号、多出的 21 号与 14 号构成罗氏易位衍生染色体。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-medical-genetics-ch9-chromosome-aberrations-b002m4",
        order: 37,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "经染色体核型分析表明，某女性为 14/21 染色体平衡易位携带者，其核型是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "45,XX,-14,-21,+t(14q21q)",
            "原书 B1 型题答案第三十八题为 E。女性 14/21 平衡易位携带者核型为 45,XX,-14,-21,+t(14q21q)。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch9-chromosome-aberrations-b003",
    order: 38,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["等臂染色体", "双着丝粒染色体", "环状染色体", "罗氏易位染色体", "倒位染色体"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-medical-genetics-ch9-chromosome-aberrations-b003m1",
        order: 38,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt:
          "当染色体的长臂和短臂的末端同时缺失时，两断端有可能连接而形成的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "环状染色体",
            "原书 B1 型题答案第三十九题为 C。当染色体长臂与短臂的末端同时缺失时，两个断端末端相连接可形成环状染色体（ring chromosome）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-medical-genetics-ch9-chromosome-aberrations-b003m2",
        order: 39,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt:
          "当 D 组或 G 组的两条染色体同时在近着丝粒的位置断裂时，如发生两条长臂相连接，有可能形成的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "罗氏易位染色体",
            "原书 B1 型题答案第四十题为 D。当 D 组（13–15 号）或 G 组（21–22 号）两条近端着丝粒染色体在近着丝粒位置断裂、两条长臂相连接时，可形成罗氏易位染色体。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
  ...caseItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];