import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学遗传学 学习指导与习题集（第4版）— 第20章 遗传咨询 题库提取（等比取样）
 * 来源：《医学遗传学学习指导与习题集》第4版（人民卫生出版社，主编：张咸宁、杨玲）
 *
 * == 统计报告（本文件题量 = 按“每教材 600、章节等比缩放”预算）==
 * - 名词解释：5 题
 * - A1/A2/X 型选择题（统一映射为 a1-single 单选）：20 题（A1 型 1~10、A2 型 11~20）
 * - 简答题 / 病例（映射 short-answer 或 case）：0 题（本章简答位于真题位次之后，预算按原书顺序截断，未纳入）
 * - B1 共用备选答案配伍题：3 组、共 5 个成员（第 21、22、23、24、25 题；第 5 组仅取前 1 位成员至预算满）
 * - 独立记分题合计：30 题（含 B1 组成员；须等于本文件预算 30）
 * - 缺失答案：0 题；无法可靠提取：0 题
 * - 说明：本章原书依序含名词解释 5、A1 型选择题 10、A2 型选择题 10、B1 配伍题
 *   5 组（21~30 题，共 10 个成员）、简答题 4；本文件按 30 道预算以原书顺序覆盖取材，取满预算，
 *   因此 B1 只取前 5 个成员（21/22/23/24/25，其中第 25 为第 5 组首成员，至预算 30 满即止），
 *   简答 4 道（含遗传伦理原则与优生科学辨析）未纳入预算。A1/A2 均为单选选择题，正确项逐一对齐
 *   源参考答案（A1：1.A 2.D 3.A 4.C 5.E 6.C 7.B 8.D 9.A 10.E；A2：11.B 12.A 13.C 14.D 15.B
 *   16.D 17.D 18.B 19.B 20.A；B1：21.C 22.E 23.A 24.B 25.A）。全部选择题选项顺序已随机重排并
 *   同步 correctChoiceIndex（0 起）。OCR 错字已按语义恢复（如“筛査/筛査”→筛查、“巢”→卵巢、
 *   “U型腿”→O型腿、“狗偻病”→佝偻病、“喊性”→碱性、“蛙”→卦等）。再现风险率、
 *   血友病/DMD/多指聋哑、Huntington 外显率、平衡易位核型等概率与数值均按原值保留，未捏造。
 *
 * 解析内容位于 answer.content 数组的第二个元素。
 */

const topic = "medical-genetics-ch20-genetic-counseling";
const locatorBase =
  "《医学遗传学学习指导与习题集》第4版 第20章 遗传咨询 复习思考题 习题（PDF 第116–121页）";
const promptNote =
  "题干改写；原题来自用户提供的题集，未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原书为X型多选题，按项目规约映射为a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据上传题集整理并改写，尚未与权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），5 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：遗传咨询（genetic counseling）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "遗传咨询",
        "遗传咨询（genetic counseling）又称“遗传商谈”，是指用遗传学和临床医学的基本原理和技术，与遗传病患者、亲属以及有关社会服务人员讨论遗传病的发病原因、遗传方式、诊断、治疗和预后等问题，解答来访者所提出的有关遗传学方面的问题，并在权衡对个人、家庭、社会的利弊基础上，给予婚姻、生育、防治、预防等方面的医学指导。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：新生儿筛查（newborn screening）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "新生儿筛查",
        "新生儿筛查（newborn screening; neonatal screening）是对已出生的新生儿进行某些遗传病的症状前诊断，是出生后预防和治疗某些遗传病的有效方法。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：携带者筛查（carrier screening）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "携带者筛查",
        "携带者筛查（carrier screening）是基因诊断的一部分，意即当某种遗传病在某一群体中有高发病率，为了预防该病在群体中的发生，采用经济实用、准确可靠的方法在群体中进行筛查，筛出携带者后则进行婚育指导，即可达到预期目标。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：遗传伦理学（genetic ethics）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "遗传伦理学",
        "遗传伦理学（genetic ethics）或译为“基因伦理学”，是运用伦理学方法研究和评估由于遗传学发展所产生的伦理问题的一门新兴学科。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：Bayes 定理（Bayes theorem）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Bayes 定理",
        "Bayes 定理（Bayes theorem）由英国学者 Thomas Bayes 提出，是一种用于计算概率的数理公式，用来估算 2 个“非此即彼”事件各自发生的相对概率，认为概率的大小随条件的变化而改变。估算再现风险是遗传咨询的中心任务，通常使用 Bayes 定理估算遗传病的再现风险。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2 型选择题（统一映射为 a1-single），20 道（A1 型 1~10、A2 型 11~20） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1001",
    order: 6,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "在先证者所患遗传病较严重且难于治疗、再现风险高，但患儿父母又迫切希望有一个健康孩子的情况下，可运用",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "遗传咨询",
      "产前诊断",
      "婚前咨询",
      "一般咨询",
      "产前咨询",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "产前诊断",
        "在先证者所患遗传病较严重而难于治疗、再现风险高、但父母又迫切希望有健康孩子时，可在妊娠期对胎儿进行产前诊断，从而避免患儿的出生。原书 A1 型选择题答案第 1 题为 A（产前诊断）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1002",
    order: 7,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "对某些危害严重、致残的遗传病，目前尚无有效疗法，又不能进行产前诊断，再次生育时的再现风险很高，宜采取的对策是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "遗传咨询",
      "出生后诊断",
      "不再生育",
      "人工受精",
      "药物控制",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "不再生育",
        "对危害严重、致残且目前无有效疗法、又不能进行产前诊断、再次生育再现风险又很高的遗传病，宜采取不再生育的对策。原书 A1 型选择题答案第 2 题为 D（不再生育）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1003",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "曾生育过一个或几个遗传病患儿，再生育本病患儿的风险或概率，称为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "患病率",
      "发病率",
      "再现风险",
      "条件概率",
      "遗传风险",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "再现风险",
        "曾生育过一个或几个遗传病患儿，再生育本病患儿的风险或概率称为再现风险（复发风险）。原书 A1 型选择题答案第 3 题为 A（再现风险）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1004",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "遗传病再现风险率为 4%～6%，属于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "低风险",
      "高风险",
      "较低风险",
      "中度再现风险",
      "较高风险",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中度再现风险",
        "再现风险一般为 10% 以上属高风险，1%~10% 属中度风险，<1% 属低风险；4%~6% 属于中度再现风险。原书 A1 型选择题答案第 4 题为 C（中度再现风险）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1005",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "遗传咨询通常分为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "青春期咨询、婚前咨询、产前咨询",
      "青春期咨询、生育期咨询、更年期咨询",
      "产前咨询、产后咨询、更年期咨询",
      "婚前咨询、生育期咨询、一般遗传咨询",
      "婚前咨询、产前咨询、一般遗传咨询",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "婚前咨询、产前咨询、一般遗传咨询",
        "遗传咨询通常分为婚前咨询、产前咨询、一般遗传咨询三类。原书 A1 型选择题答案第 5 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1006",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "女方患有血友病，应建议其最好采取的措施为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "可以结婚及生育",
      "暂缓结婚",
      "可以结婚，限制生育",
      "可以结婚，禁止生育",
      "不能结婚",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "可以结婚，限制生育",
        "血友病属 X 连锁隐性遗传病，女方患病时生育子女风险较高，遗传咨询建议其可以结婚、限制生育。原书 A1 型选择题答案第 6 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1007",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "用细菌抑制法可以筛查",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "半乳糖血症",
      "甲状腺肿",
      "苯丙酮尿症",
      "G6PD缺乏症",
      "Gaucher 病",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "苯丙酮尿症",
        "苯丙酮尿症可用细菌抑制法（如 Guthrie 法）进行筛查。原书 A1 型选择题答案第 7 题为 B（苯丙酮尿症）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1008",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在遗传咨询过程中，下列哪一项并非正确的遗传咨询内容？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "确立咨询者是否为遗传病患者",
      "对咨询者的婚育问题提出建议和指导",
      "解答遗传病的再现风险率",
      "为咨询者决定是否生育",
      "解答遗传疾病的发病原因、遗传方式、诊断预防等问题",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "为咨询者决定是否生育",
        "遗传咨询是告诉咨询者风险、提供建议和指导，但绝不代替咨询者作决定，是非指令性的；故“为咨询者决定是否生育”并非正确的咨询内容。原书 A1 型选择题答案第 8 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1009",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "大多数三体综合征的发生与母龄呈正相关，其中一个重要原因就是随着母亲年龄的增高，卵巢开始退化，从而导致卵细胞形成过程中",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "父亲高发染色体不分离",
      "母亲高发染色体不分离",
      "有丝分裂染色体不分离",
      "将有丝分裂变为无丝分裂",
      "1个卵细胞与2个精子进行受精",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "母亲高发染色体不分离",
        "随母亲年龄增高，卵巢衰退、卵细胞形成过程中易发生减数分裂不分离，母亲高发染色体不分离，故多数三体综合征的发生与母龄呈正相关。原书 A1 型选择题答案第 9 题为 A（母亲高发染色体不分离）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1010",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "以下哪一项不会引起人类基因组学研究中涉及的遗传信息隐私权的伦理问题？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "不理会携带“不良”遗传基因的个体可能受到歧视的问题",
      "如何保障提供样本的个体的利益的问题",
      "样本提供者自愿地参与人类基因组学的研究，签署有“书面知情同意书”",
      "是否应该把研究结果告诉提供样本的人群的问题",
      "是否可以提供有关疾病的遗传检测信息给保险公司或用人单位的问题",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "样本提供者自愿地参与人类基因组学的研究，签署有“书面知情同意书”",
        "样本提供者自愿参与研究并签署书面知情同意书，不构成遗传信息隐私权伦理问题；A、B、D、E 均涉及遗传信息隐私权及其可能带来歧视、滥用等伦理问题。原书 A1 型选择题答案第 10 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1011",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某夫妇，男方患多指，女方正常。婚后生了一个手指正常的聋哑女儿。他们再次生育时，生育一个完全正常的儿子的概率为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["1/2", "1/8", "3/16", "1/4", "3/8"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "3/16",
        "多指为常染色体显性遗传，男方多指（杂合）、女方正常，子代手指正常概率为 1/2；聋哑为另一常染色体隐性遗传病，其聋哑女儿（aa）说明父母均为携带者，子代非聋哑（正常）概率为 3/4。生育完全正常的儿子概率＝正常手指（1/2）×非聋哑（3/4）×为儿子（1/2）＝3/16。原书 A2 型选择题答案第 11 题为 B（3/16）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1012",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某 2 岁男孩，因精神发育迟缓查染色体，核型为 46,XY,-14,+t(14q21q)。再查其母后，发现为平衡易位染色体携带者。其母的核型应为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "46,XX/47,XX,+21",
      "45,XX,-15,-21,+t(15q21q)",
      "46,XX,-14,+t(14q21q)",
      "45,XX,-14,+t(14q21q)",
      "46,XX,-21,+t(14q21q)",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "45,XX,-14,+t(14q21q)",
        "男孩核型为 46,XY,-14,+t(14q21q)（罗伯逊易位伴 21 三体），其母为平衡易位携带者，核型应为 45,XX,-14,+t(14q21q)——少 1 条 14 号、代之以 14q21q 易位染色体，表型正常。原书 A2 型选择题答案第 12 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1013",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "如果科学家通过转基因技术成功地将某未婚女性血友病患者的造血干细胞进行改造，使其凝血功能恢复正常，则她与正常个体婚后生育患血友病男孩的风险为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["0%", "100%", "50%", "25%", "20%"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "100%",
        "血友病为 X 连锁隐性遗传病，未婚女性患者（XhXh）经体细胞基因治疗虽使造血细胞凝血功能恢复，但生殖细胞的致病基因未改变（仍为 XhXh）。她与正常男性（XY）婚后所生男孩均从其获得一条 Xh，故生育患血友病男孩的风险为 100%。原书 A2 型选择题答案第 13 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1014",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "DMD 是一种严重的致死性 X 连锁隐性遗传病。某青年女性的哥哥患 DMD 而夭亡，她前来遗传咨询。其婚后所生子女的发病风险是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "所生子女全部正常",
      "生男孩的发病风险是1/4,女孩有1/4是携带者",
      "生男孩的发病风险是1/2,女孩有1/4是携带者",
      "生男孩的发病风险是1/2,女孩有1/2是携带者",
      "所生子女的发病风险均为100%",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "生男孩的发病风险是1/4,女孩有1/4是携带者",
        "该青年女性有患 DMD（X 连锁隐性）而夭亡的哥哥，说明其母为肯定的携带者；她本人为携带者的概率为 1/2。若为携带者，其儿子 1/2 患病、女儿 1/2 为携带者，故生男孩发病风险＝1/2×1/2＝1/4，女孩为携带者的风险＝1/2×1/2＝1/4。原书 A2 型选择题答案第 14 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1015",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某 23 岁的男青年，患严重的佝偻病，并有骨骼畸形、骨痛而行走困难。查体可见身材矮小，下肢进行性弯曲，O 型腿，实验室检查表明血钙正常，血磷低、尿磷高、血清碱性磷酸酶增高，服用维生素 D 制剂并不能提高血磷，则初步诊断为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "维生素D缺乏性佝偻病",
      "抗维生素D佝偻病",
      "维生素D依赖性佝偻病",
      "肾性佝偻病",
      "软骨营养不良",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗维生素D佝偻病",
        "本例血钙正常、血磷低、尿磷高、服维生素 D 不能提高血磷，符合 X 连锁显性遗传的抗维生素 D 佝偻病（家族性低血磷性佝偻病）的特点。原书 A2 型选择题答案第 15 题为 B（抗维生素 D 佝偻病）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1016",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某放射科女医生，婚后生了一个小头畸形的精神发育迟缓患儿。担心下一个孩子还会罹患相同的疾病而前来进行遗传咨询。咨询医师可建议采取以下哪一项对策降低患儿的出生风险？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "人工受精",
      "不再生育",
      "产前诊断",
      "冒险再次生育",
      "借卵怀胎",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "产前诊断",
        "该患儿为小头畸形伴精神发育迟缓，再次怀孕前及孕期可建议进行产前诊断，以降低下一胎患儿出生风险。原书 A2 型选择题答案第 16 题为 D（产前诊断）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1017",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某遗传病的男性先证者，父母、外祖父母、一个舅母、弟弟均正常，但另一个舅舅罹患本病。判断该遗传病的遗传方式为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "常染色体隐性遗传病",
      "X-连锁显性遗传病",
      "Y-连锁遗传病",
      "常染色体显性遗传病",
      "X-连锁隐性遗传病",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "X-连锁隐性遗传病",
        "男性先证者的舅舅患病而父母、祖辈、弟弟均正常，致病基因经母亲（其母为携带者）隔代传递、男性发病，符合 X 连锁隐性遗传的特点。原书 A2 型选择题答案第 17 题为 D（X-连锁隐性遗传病）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1018",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "Huntington 病为常染色体显性遗传病，如其外显率为 80%，则 1 例杂合性患者与一个正常个体婚后生育患儿的风险为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["20%", "40%", "50%", "60%", "100%"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "40%",
        "Huntington 病为常染色体显性遗传，杂合患者（Aa）与正常个体（aa）婚后，子代携带致病基因的概率为 1/2；其外显率为 80%，故生育患儿的风险＝1/2×80%＝40%。原书 A2 型选择题答案第 18 题为 B（40%）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1019",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "钱币状掌跖角化症（keratosis palmoplantaris nummularis）为一种遗传病，患者一般从幼儿学会走路时开始脚掌部发病。随着年龄增长，患处损伤逐步加重；手掌发病多见于手工劳动者。下列有关描述不正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "由家系图判断此病最可能属于常染色体显性遗传病",
      "家系调查与群体调查相结合，可推断本病的遗传特点",
      "第4代中患者与正常个体婚配,生育女儿可避免本病的遗传",
      "本病症状的表现其实是基因与环境因素共同作用的结果",
      "避免或减少摩擦可预防或减轻发病",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第4代中患者与正常个体婚配,生育女儿可避免本病的遗传",
        "该病最可能为常染色体显性遗传病，患者与正常个体婚配时，无论生育儿子还是女儿均有约 1/2 发病风险，生育女儿并不能避免本病的遗传；手掌发病多见于手工劳动者说明摩擦等环境因素参与，故选“生育女儿可避免本病的遗传”为不正确描述。原书 A2 型选择题答案第 19 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-a1020",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某男性患儿，2 岁。眼距宽，眼裂小，鼻梁低平，舌常伸出口外，流涎多，有通贯掌，合并先天性心脏病。其最有确诊意义的检查为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "染色体检查",
      "胸部X-射线检查",
      "肝功能测定",
      "听力测定",
      "腹部B型超声检查",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "染色体检查",
        "患儿眼距宽、眼裂小、鼻梁低平、舌外伸、通贯掌、合并先天性心脏病等表现高度提示 21 三体综合征（先天愚型），确诊最有意义的是染色体检查。原书 A2 型选择题答案第 20 题为 A（染色体检查）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer）：本章按预算截断，未纳入（0 道） */
const shortItems: readonly AssessmentItemDefinition[] = [];

/** 病例 / 病案分析（case）：本章无（0 道） */
const caseItems: readonly AssessmentItemDefinition[] = [];

/** B1 共用备选答案配伍题，3 组、共 5 个成员（第 21、22、23、24、25 题） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-b001",
    order: 26,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "孤独症",
      "Gaucher 病",
      "家族性甲状腺肿",
      "G6PD缺乏症",
      "半乳糖血症",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-medical-genetics-ch20-genetic-counseling-b001m1",
        order: 26,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "可以用血斑滤纸的提取液筛查的新生儿疾病是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "家族性甲状腺肿",
            "新生儿血斑（足跟血）滤纸提取液可用于新生儿遗传病筛查，题中可据此筛查的疾病按源参考答案为家族性甲状腺肿。原书 B1 型参考答案第 21 题为 C（家族性甲状腺肿）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-medical-genetics-ch20-genetic-counseling-b001m2",
        order: 27,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "可以用嗜菌体抗性检测法筛查的新生儿疾病是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "半乳糖血症",
            "半乳糖血症可用嗜菌体（细菌）抗性检测法进行新生儿筛查。原书 B1 型参考答案第 22 题为 E（半乳糖血症）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-b002",
    order: 28,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "细胞遗传学诊断",
      "超声波检查",
      "X-射线摄片检查",
      "酶学诊断",
      "基因诊断",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-medical-genetics-ch20-genetic-counseling-b002m1",
        order: 28,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "生育过先天愚型患儿的孕妇，为防止患儿出生可采取",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "细胞遗传学诊断",
            "生育过先天愚型（21 三体）患儿的孕妇，为防止患儿出生可采取细胞遗传学诊断，即产前抽取羊水或绒毛做染色体核型分析以确诊。原书 B1 型参考答案第 23 题为 A（细胞遗传学诊断）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-medical-genetics-ch20-genetic-counseling-b002m2",
        order: 29,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "怀疑胎儿为无脑儿，且孕妇有先兆流产的倾向，此时应采取",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "超声波检查",
            "怀疑胎儿为无脑儿且孕妇有先兆流产倾向时，应采用无创且对胎儿相对安全的超声波检查来观察胎儿神经管畸形情况。原书 B1 型参考答案第 24 题为 B（超声波检查）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-medical-genetics-ch20-genetic-counseling-b003",
    order: 30,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "苯丙酮尿症的筛查和诊断",
      "进行性肌营养不良的筛查和诊断",
      "新生儿黄疸的筛查和诊断",
      "新生儿脑膜炎的筛查和诊断",
      "遗传病携带者的筛查和诊断",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-medical-genetics-ch20-genetic-counseling-b003m1",
        order: 30,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "新生儿疾病筛查包括对",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "苯丙酮尿症的筛查和诊断",
            "新生儿疾病筛查包括了苯丙酮尿症的筛查和诊断。原书 B1 型参考答案第 25 题为 A（苯丙酮尿症的筛查和诊断）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
  ...caseItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];