import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学影像学学习指导与习题集 第3版 — 第13章 血管疾病的介入治疗 题库提取（等比取样）
 * 来源：《医学影像学学习指导与习题集》第3版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：4 题
 * - 填空题（fill）：4 题
 * - 选择题（a1-single）：18 题（均为 A1 型，A2 型未纳入）
 * - 简答题（short-answer）：5 题
 * - B1 配伍题：1 组 / 4 成员
 * - 独立记分题合计：35 题（须等于本文件预算 35）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书含名词解释、填空题、选择题（A1/A2/B1）、简答题；本文件按 35 道预算在
 *   原书顺序内取材：名词解释取第 1–4 题、填空题取第 1–4 题、A1 型取第 1–18 题（A2 型
 *   未纳入）、B 型取第 1 组（原书 46–49 题共用备选答案，共 4 成员）、简答题取第 1–5 题；
 *   未纳入的题因预算所限。正确项对齐章末参考答案键号（A1/A2/B1 全书连续编号），选项已
 *   随机重排并同步 correctChoiceIndex。OCR 错字已按医学影像学医学语义恢复（如 介人→介入、
 *   黄疽→黄疸、5mi/min→5ml/min、60000/mm’→60000/mm³ 等），数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "radiology-bank-ch13-ir-vascular";
const locatorBase =
  "《医学影像学学习指导与习题集》第3版 第13章 血管疾病的介入治疗 习题（核对PDF 第176–186页）";
const promptNote =
  "题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），4 道（原书第 1–4 题） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：TIPS",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "TIPS（transjugular intrahepatic portosystemic shunt，经颈静脉肝内门体分流术）：采用特殊的介入治疗器械，在 DSA 导引下，经颈静脉入路，在肝实质内建立的肝静脉及门静脉主要分支之间的人工分流通道，并以金属内支架维持其永久性通畅，从而降低门静脉压力，并控制食道胃底静脉曲张破裂出血，促进腹水吸收。",
        "TIPS 即在肝实质内建立肝静脉-门静脉人工分流通道并以内支架维持其通畅，从而降低门静脉压力、控制食管胃底静脉曲张破裂出血、促进腹水吸收。原书第13章名词解释第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：布-加综合征",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "布-加综合征：是由多种原因引起的主要肝静脉分支和（或）肝段及肝上段下腔静脉膜性或节段性狭窄、闭塞或肝小静脉狭窄、闭塞所导致的肝静脉回流受阻，继而形成肝脏淤血、门静脉高压、肝功能受损，以及因此所产生的以肝大、腹胀（痛）、腹水及下肢水肿等为主要临床表现的一组综合病征。",
        "布-加综合征的核心为肝静脉和（或）肝段及肝上段下腔静脉狭窄闭塞致肝静脉回流受阻，表现为肝大、腹胀（痛）、腹水及下肢水肿等。原书第13章名词解释第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：上腔静脉综合征",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "上腔静脉综合征：是上腔静脉狭窄、闭塞导致头面部、上肢及胸壁静脉回流受阻，并由此引发的一系列临床症状与体征。",
        "上腔静脉综合征由上腔静脉狭窄、闭塞致头面部、上肢及胸壁静脉回流受阻引起。原书第13章名词解释第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：球囊阻塞逆行性静脉曲张消融术（B-RTO）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "球囊阻塞逆行性静脉曲张消融术（B-RTO）：是经门静脉高压后形成的自发性胃-肾分流道向胃底静脉曲张血管内注入硬化剂进行消融治疗的介入技术。",
        "B-RTO 利用门静脉高压形成的自发性胃-肾分流道，逆行向胃底静脉曲张血管内注入硬化剂进行消融治疗。原书第13章名词解释第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），4 道（原书第 1–4 题） */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-fill001",
    order: 5,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "动脉出血速度在___以上时才能被 DSA 发现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "0.5ml/min",
        "动脉出血速度达 0.5ml/min 以上时血管造影方可显示对比剂外溢。原书第13章填空题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-fill002",
    order: 6,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "支气管动脉化疗术治疗肺癌最危险的并发症是___，其原因是___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①截瘫；②支气管动脉与脊髓动脉共干",
        "支气管动脉常与脊髓动脉共干，化疗药或栓塞剂进入脊髓动脉可致截瘫，为最危险的并发症。原书第13章填空题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-fill003",
    order: 7,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "下腔静脉滤器置入绝对适应证为___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗凝治疗中静脉血栓栓塞复发；存在抗凝治疗禁忌证；抗凝治疗出现并发症；抗凝治疗失败",
        "下腔静脉滤器置入的绝对适应证包括抗凝治疗中静脉血栓栓塞复发、存在抗凝禁忌证、抗凝治疗出现并发症及抗凝治疗失败。原书第13章填空题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-fill004",
    order: 8,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "颈动脉支架后再灌注损伤常表现___和___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①头痛；②癫痫发作",
        "颈动脉支架术后脑过度灌注（再灌注）损伤常表现为头痛和癫痫发作。原书第13章填空题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），18 道（A1 型原书第 1–18 题） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1001",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列有关 TIPSS 的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "扩张肝内通道之前，应常规栓塞胃冠状静脉和胃短静脉，目的是巩固疗效，有助于防止术后分流通道，限制肝性脑病的发生",
      "选择至胃冠状静脉后要再次造影，显示其走行、大小，以便估计栓塞剂用量并尽可能予以彻底栓塞",
      "关于栓塞静脉范围，因胃底食道静脉曲张供血血管常有多支参与，故主张尽可能栓塞全部胃冠状静脉、胃短静脉及胃后静脉，如不行，应将胃冠状静脉作为常规栓塞血管",
      "当支架植入位置欠佳时，亦不能同时放置两个内支架",
      "除用 Cobra 导管栓塞胃冠状静脉外，导丝始终应注意不要拖出门静脉，以保证整个操作圆满完成",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "当支架植入位置欠佳时，亦不能同时放置两个内支架",
        "TIPSS 术中支架植入位置欠佳时可同时放置两个内支架以保证分流道通畅，该说法错误。原书第13章 A1 型题第 1 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1002",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "为预防肺动脉栓塞，常采用下列哪种介入放射学方法进行治疗",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "血管内支架治疗",
      "下腔静脉滤器置放术",
      "经导管溶栓法",
      "钳取法",
      "TAE",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "下腔静脉滤器置放术",
        "下腔静脉滤器可阻止下肢深静脉血栓脱落进入肺动脉，用于预防肺动脉栓塞。原书第13章 A1 型题第 2 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1003",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "脾动脉栓塞术的关键",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "栓塞剂的选择",
      "栓塞前的脾动脉造影",
      "栓塞后的脾动脉造影",
      "术中控制栓塞程度",
      "超选靶血管",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "术中控制栓塞程度",
        "脾动脉栓塞术的关键是术中控制栓塞程度，避免过度栓塞。原书第13章 A1 型题第 3 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1004",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "小肠出血止血栓塞哪级动脉分支效果好而不会引起肠坏死",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "1 级分支",
      "2 级分支",
      "3 级分支",
      "直动脉及末支动脉弓",
      "直动脉及末支动脉弓前一级分支",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "直动脉及末支动脉弓前一级分支",
        "栓塞直动脉及末支动脉弓前一级分支既可止血又不易引起肠坏死。原书第13章 A1 型题第 4 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1005",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "血管栓塞造成靶器官或肿瘤坏死的主要栓塞部位",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "毛细血管床",
      "小动脉",
      "动脉主干",
      "毛细血管床、小动脉、动脉主干同时被栓塞",
      "静脉栓塞",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "毛细血管床、小动脉、动脉主干同时被栓塞",
        "毛细血管床、小动脉、动脉主干同时被栓塞才能造成靶器官或肿瘤坏死。原书第13章 A1 型题第 5 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1006",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "经导管动脉内药物溶栓治疗，术中监测凝血酶原时间在正常___倍以上时，须减少药物剂量或停止溶栓",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["1", "1.5", "2", "3", "3.5"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "2",
        "溶栓治疗中凝血酶原时间超过正常 2 倍以上时须减少药物剂量或停止溶栓。原书第13章 A1 型题第 6 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1007",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "球囊血管成形术的主要机理不包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "血管壁内、中膜局限性撕裂",
      "血管壁外膜组织局限性过度伸展",
      "血管壁中膜组织过度伸展",
      "内膜损伤",
      "粥样硬化斑块撕裂",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血管壁外膜组织局限性过度伸展",
        "球囊血管成形术的机理包括内膜损伤、血管壁内中膜局限性撕裂、中膜组织过度伸展及粥样硬化斑块撕裂，不包括外膜组织过度伸展。原书第13章 A1 型题第 7 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1008",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "当出血速度达到多少时血管造影方可显示对比剂外溢",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["0.3ml/min", "0.5ml/min", "0.7ml/min", "2ml/min", "5ml/min"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "0.5ml/min",
        "出血速度达 0.5ml/min 以上时血管造影方可显示对比剂外溢；OCR「5mi/min」已恢复为「5ml/min」。原书第13章 A1 型题第 8 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1009",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "精索静脉曲张的首选栓塞剂是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["聚乙烯醇", "明胶海绵", "鱼肝油酸钠", "丝线", "钢圈"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "鱼肝油酸钠",
        "精索静脉曲张首选硬化剂鱼肝油酸钠栓塞。原书第13章 A1 型题第 9 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1010",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下述髂股动脉 PTA 入路哪项正确",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "股动脉分叉部病变的最佳入路是经对侧股动脉穿刺",
      "股动脉分叉部病变如行同侧顺行股动脉穿刺则穿刺点应位于腹股沟韧带下方",
      "股浅动脉中段病变行同侧股动脉顺行穿刺是最佳入路",
      "髂动脉病变多数经对侧股动脉顺行插管",
      "髂动脉病变延及腹主动脉者应由对侧股动脉穿刺",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "股动脉分叉部病变的最佳入路是经对侧股动脉穿刺",
        "股动脉分叉部病变的最佳入路为经对侧股动脉穿刺，其余说法均不正确。原书第13章 A1 型题第 10 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1011",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "血管内支架具有一定几何形状的圆筒状支撑物，用于支撑血管狭窄处，使血流保持通畅，临床应用广泛，但不用于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "颈动脉狭窄",
      "冠状动脉狭窄",
      "肾动脉分支狭窄",
      "颅外动脉狭窄",
      "下腔静脉狭窄",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肾动脉分支狭窄",
        "肾动脉分支狭窄病变细小、不适用血管内支架；支架主要用于主干狭窄性病变。原书第13章 A1 型题第 11 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1012",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于动脉内溶栓，叙述不正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脑动脉内溶栓治疗适用于病史超过 6 小时脑梗死病人",
      "再通率明显高于静脉内溶栓",
      "动脉内溶栓治疗失败时，可借溶栓通路应用血管内支架治疗",
      "原则上，病史在 3 个月以内的四肢动脉栓塞均可采用动脉内溶栓治疗",
      "已知出血倾向者是动脉内溶栓的禁忌证",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑动脉内溶栓治疗适用于病史超过 6 小时脑梗死病人",
        "脑动脉内溶栓治疗有严格时间窗（一般不超过 6 小时），该说法不正确。原书第13章 A1 型题第 12 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1013",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "空肠大面积出血性炎症患者，行肠系膜上动脉选择性插管灌注加压素后，较为常见的并发症是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["痉挛性腹痛", "心肌梗死", "高血压", "肠缺血坏死", "外周血管缺血"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "痉挛性腹痛",
        "加压素灌注后可致肠管平滑肌痉挛，出现痉挛性腹痛，为较常见并发症。原书第13章 A1 型题第 13 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1014",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于内科性脾切除叙述不正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "内科性脾切除是通过导管栓塞术来消除脾功能",
      "可用于治疗不同原因引起的脾大、脾功能亢进",
      "现多用部分脾动脉栓塞术",
      "栓塞脾下极较栓塞上极安全性大",
      "不适用于特发性血小板减少性紫癜",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "不适用于特发性血小板减少性紫癜",
        "内科性脾切除（部分脾动脉栓塞术）亦适用于特发性血小板减少性紫癜，该说法不正确。原书第13章 A1 型题第 14 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1015",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不可试用血管内栓塞术控制的出血为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "外伤性出血",
      "肿瘤出血",
      "胃十二指肠溃疡出血",
      "胃食管静脉曲张出血",
      "脑出血",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑出血",
        "脑出血一般不作血管内栓塞控制，为不可试用栓塞术控制的出血。原书第13章 A1 型题第 15 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1016",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不适用于血管内栓塞治疗的外伤性出血为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "外伤性脾破裂出血",
      "外伤性肝破裂出血",
      "外伤性肾破裂出血",
      "骨盆骨折所致的盆腔大出血",
      "骨盆骨折所致的直肠破裂出血",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "骨盆骨折所致的直肠破裂出血",
        "直肠破裂出血可经肠腔污染、不适合血管内栓塞，通常需外科处理。原书第13章 A1 型题第 16 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1017",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下腔静脉滤器植入术可有效阻止血栓进入肺动脉，植入滤器的位置应为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肾静脉开口水平",
      "肾静脉开口水平以上 2cm",
      "下腔静脉邻近右心房处",
      "肾静脉开口水平以下",
      "肾静脉上缘 1cm",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肾静脉开口水平以下",
        "下腔静脉滤器应置于肾静脉开口水平以下，以免影响肾静脉回流。原书第13章 A1 型题第 17 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-a1018",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "鱼精蛋白硫酸盐可与体内肝素结合而使肝素失去抗凝血能力，适用于肝素过量而引起的出血。1mg 鱼精蛋白硫酸盐可中和肝素",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["10U", "500", "1000", "1000U", "1ml"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "1000",
        "按参考答案键号 C 归位为「1000」；OCR 选项中该数值后单位疑似缺失（键号行「18.C」清晰），未另作推断。原书第13章 A1 型题第 18 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），5 道（原书第 1–5 题） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-short001",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述门脉高压症的介入治疗方法及原理。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "门脉高压症的主要治疗方法有：部分性脾动脉栓塞术，经颈静脉肝内门体静脉分流术，经皮经肝食道胃底曲张静脉栓塞术，球囊阻塞逆行性静脉曲张消融术。原理：通过脾动脉部分栓塞、门腔静脉之间分流道的建立或食管胃底静脉异常血管的栓塞消融达到降低门静脉压力，减少食管胃底静脉的出血及促进难治性腹水的吸收。",
        "门脉高压症介入治疗以降门脉压、减少食管胃底静脉出血及促进腹水吸收为原理，方法包括部分性脾动脉栓塞术、TIPS、经皮经肝食道胃底曲张静脉栓塞术及 B-RTO。原书第13章简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-short002",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述 TIPS 手术的适应证。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①门脉高压性胃底静脉曲张及异位静脉曲张（十二指肠、空肠、脾肾及直肠）；②成功内镜硬化或结扎治疗后上消化道出血病情再发；③门脉高压性食管胃底静脉曲张破裂出血内镜治疗失败；④存在上消化道出血复发高风险因素者；⑤大量难治性腹水及肝性胸腔积液。",
        "TIPS 适应证包括门脉高压性胃底及异位静脉曲张、内镜治疗后上消化道出血再发或内镜治疗失败、上消化道出血复发高风险及大量难治性腹水、肝性胸腔积液。原书第13章简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-short003",
    order: 29,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述 TIPS 手术的方法。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "右侧颈内静脉入路，穿刺成功后插入导管鞘；将 TIPS 穿刺套装中的外套管插入下腔静脉；成功穿刺门静脉，置入导管测量门静脉压力；引入导丝及球囊扩张分流道；置入支架；再次测量门静脉压力及适当栓塞胃冠状静脉。",
        "TIPS 经右侧颈内静脉入路，穿刺门静脉建立分流道后置入支架，并再次测量门静脉压力、适当栓塞胃冠状静脉。原书第13章简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-short004",
    order: 30,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述经导管溶栓术的适应证及禁忌证。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "经导管溶栓术是指经导管向靶血管的血栓性病变局部灌注溶血栓药物，适用于动脉内急性血栓形成、急性深静脉血栓形成、急性肺栓塞等的微创治疗。禁忌证包括：已知出血倾向；消化性溃疡活动性出血期；近期颅内出血及发病时间超过 48 小时的脑血栓形成；严重高血压；近期接受过外科手术治疗；严重心、肝、肾功能不全等。",
        "经导管溶栓适用于动脉内急性血栓、急性深静脉血栓及急性肺栓塞，禁忌证以出血倾向、近期颅内出血及手术、严重高血压和严重脏器功能不全为主。原书第13章简答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-short005",
    order: 31,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述上腔静脉综合征的介入手术方法。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "选择股静脉入路或右侧颈内静脉入路；将造影导管置于狭窄、闭塞段的远心端进行造影，并将导丝穿过狭窄、闭塞段；如静脉管腔内有继发性血栓形成，可在经皮球囊导管成形术和血管内支架置入术前进行经导管溶栓治疗；对静脉狭窄、闭塞性病变，特别是良性病变进行 PTA 治疗；若 PTA 效果不佳，可行内支架置入术。",
        "上腔静脉综合征介入经股静脉或右侧颈内静脉入路，先造影并导丝通过狭窄闭塞段，继发血栓先行溶栓，再行 PTA，效果不佳者置入内支架。原书第13章简答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 配伍题（bGroups），1 组 / 4 成员（原书 46–49 题共用备选答案） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch13-ir-vascular-b001",
    order: 32,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "主髂动脉闭塞症",
      "肾动脉狭窄",
      "膝下动脉狭窄、闭塞",
      "弓上动脉狭窄、闭塞",
      "支气管动脉出血",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch13-ir-vascular-b001m1",
        order: 32,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "并发症「远端分支动脉栓塞」最常见于下列哪种疾病的介入治疗",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "主髂动脉闭塞症",
            "主髂动脉闭塞症介入治疗（PTA/支架）后远端分支动脉栓塞为常见并发症。原书第13章 B 型题第 46 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch13-ir-vascular-b001m2",
        order: 33,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "并发症「动脉内膜撕脱」最常见于下列哪种疾病的介入治疗",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肾动脉狭窄",
            "肾动脉狭窄介入治疗（球囊扩张/支架）时动脉内膜撕脱为常见并发症。原书第13章 B 型题第 47 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch13-ir-vascular-b001m3",
        order: 34,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "并发症「心动过缓与低血压」最常见于下列哪种疾病的介入治疗",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "弓上动脉狭窄、闭塞",
            "弓上动脉（颈动脉区）介入治疗时刺激颈动脉窦可致心动过缓与低血压。原书第13章 B 型题第 48 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch13-ir-vascular-b001m4",
        order: 35,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "并发症「血管痉挛」最常见于下列哪种疾病的介入治疗",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "膝下动脉狭窄、闭塞",
            "膝下动脉狭窄、闭塞介入治疗中导丝导管操作易诱发血管痉挛。原书第13章 B 型题第 49 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems, ...fillItems, ...a1Items, ...shortItems,
];
export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
