import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学影像学学习指导与习题集 第3版 — 第04章 呼吸系统 题库提取（等比取样）
 * 来源：《医学影像学学习指导与习题集》第3版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：4 题
 * - 填空题（fill）：5 题
 * - 选择题（a1-single）：30 题（A1 型 30、A2 型病例题 0）
 * - 简答题（short-answer）：5 题
 * - B1 配伍题：2 组 / 5 成员
 * - 独立记分题合计：49 题（须等于本文件预算 49）
 * - 缺失答案：0；无法可靠提取：0（填空题原书第 2 题 OCR 残缺、答案无法可靠锚定，换取第 6 题）
 * - 说明：本章原书含名词解释 12 题、填空题 13 题、选择题（A1 型 1–80、A2 型 81–85、
 *   B 型 86–100）、简答题 10 题；本文件按 49 道预算在原书顺序内等比取材：名词解释取第
 *   1–4 题、填空题取第 1、3、4、5、6 题（第 2 题“肺段构成”OCR 残缺换第 6 题）、A1 型取
 *   第 1–30 题（A2 型因预算所限未取）、B 型取第 86–90 题（组 86~88、89~90）、简答题取第
 *   1–5 题；未纳入的题因预算所限。正确项对齐章末参考答案键号；参考答案区键号与题号存在
 *   错位（参考答案区 A1 键号 1–76 直接对应 A1 题号 1–76；其后键号 77–80 实际对应 A1
 *   77–80 题；键号 81–85 对应 A2 81–85 题；键号 86–100 对应 B1 86–100 题），本文件取样
 *   范围（A1 1–30、B1 86–90）键号与题号一致、直接对照；键号 18.F 按医学语义恢复为 E
 *   （以上都是）、键号 89.G 恢复为 C（胸壁向肺野突出的凸镜形液体样密度影）。选项与共用
 *   备选答案已随机重排并同步 correctChoiceIndex。OCR 错字已按医学影像学医学语义恢复
 *   （如 又线→X线、CIT→CT、星→呈、力→为、乡隔→纵隔、問围→周围、T,WI→T1WI、
 *   TWI→T2WI、胸肉甲状腺→胸内甲状腺 等），数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "radiology-bank-ch04-resp";
const locatorBase =
  "《医学影像学学习指导与习题集》第3版 第04章 呼吸系统 习题（核对PDF 第55–70页）";
const promptNote =
  "题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），4 道（原书第 1–4 题） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch04-resp-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肺小叶",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺小叶（Miller 次级肺小叶）是肺的基本解剖单位，直径约 10~25mm，主要由三部分构成：小叶核心（小叶肺动脉和细支气管组成）、小叶实质（主要为肺腺泡结构）和小叶间隔（疏松结缔组织组成，有小叶静脉及淋巴管走行）。",
        "肺小叶是肺的基本解剖单位，X线胸片上的间质改变常以肺小叶为基本单位理解。原书第04章名词解释第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：奇叶",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "奇叶（azygos lobe）是肺叶间裂的变异（奇叶副裂）所致；正位胸片上表现为自右肺尖部向奇静脉方向走行的弧线状致密影，以小圆点状的奇静脉影为终止点，其内侧肺组织即为奇叶。",
        "奇叶是常见的肺叶间裂变异，由奇静脉副裂分隔形成。原书第04章名词解释第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肺空洞与空腔",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺空洞是指肺内病变组织发生坏死液化并经引流支气管排出后所形成，包括厚壁空洞、薄壁空洞、无壁空洞（虫蚀样空洞）等；肺空腔是指肺内生理腔隙的病理性扩大，如肺大疱、含气肺囊肿及肺气囊等。",
        "空洞与空腔形成的机制不同：空洞由坏死组织经引流支气管排出形成，空腔为生理腔隙的病理性扩大。原书第04章名词解释第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：包裹性胸腔积液",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "包裹性胸腔积液是脏、壁层胸膜发生粘连而使积液局限于胸膜腔的某一部位而成；X线表现为自胸壁向肺野突出的半圆形或扁丘状均匀致密影，边缘清楚，与胸壁呈钝角相交。",
        "包裹性胸腔积液属于局限性胸腔积液，注意与肺底积液、叶间积液等鉴别。原书第04章名词解释第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），5 道（原书第 1、3、4、5、6 题；第 2 题 OCR 残缺换第 6 题） */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch04-resp-fill001",
    order: 5,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：X线胸片上常见的肋骨变异包括____、____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈肋；叉状肋；肋骨联合",
        "X线胸片常见肋骨变异包括颈肋、叉状肋和肋骨联合三种类型。原书第04章填空题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-fill002",
    order: 6,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：Miller 次级肺小叶简称肺小叶，是肺的基本解剖单位，直径约 10~25mm，主要包括以下三部分：____、____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "小叶核心；小叶实质；小叶间隔",
        "肺小叶由小叶核心（小叶肺动脉和细支气管）、小叶实质（肺腺泡结构）和小叶间隔（疏松结缔组织）三部分构成。原书第04章填空题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-fill003",
    order: 7,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：厚壁空洞是指洞壁的厚度____；临床上常见的三种疾病为____、____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "≥3mm；肺结核；肺脓肿（周围型）；肺癌",
        "厚壁空洞洞壁厚度≥3mm，常见于肺结核、肺脓肿（周围型）和肺癌。原书第04章填空题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-fill004",
    order: 8,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：胸腔积液的X线表现与____、____和____有关。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "积液量；体位；包裹或粘连",
        "胸腔积液的X线表现取决于积液量多少、检查时体位以及有无胸膜包裹或粘连。原书第04章填空题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-fill005",
    order: 9,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：广泛的胸膜增厚粘连可导致肋间隙____、引起脊柱____、横膈____、纵隔向____移位。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "变窄；侧弯；升高；患侧",
        "广泛的胸膜增厚粘连使患侧胸廓收缩：肋间隙变窄、脊柱向患侧侧弯、横膈升高、纵隔向患侧移位。原书第04章填空题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），30 道（A1 型第 1–30 题） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1001",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于胸部影像学检查，下列哪项是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "MRI 有助于了解纵隔与大血管关系",
      "最常用的是X线片和CT 扫描",
      "超声简便易行，也是常用的检查方法",
      "PET/CT 可用于肿瘤性病变检查",
      "CT 检查优于X线片",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "超声简便易行，也是常用的检查方法",
        "胸部影像学检查最常用X线片和CT，超声受肺内气体干扰，不是胸部常用的检查方法。原书第04章 A1 型题第 1 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1002",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胸部X线摄片的最常用体位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["前弓位", "后前位", "斜位", "侧位", "前屈位"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "后前位",
        "胸部X线摄片最常用后前位，辅以侧位、斜位、前弓位等。原书第04章 A1 型题第 2 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1003",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关X线胸片的描述，下列错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "一般第6肋骨前端相当于第10肋后端高度",
      "常规胸部正位片上均可见水平裂胸膜",
      "肋骨先天性变异主要包括三种类型",
      "乳头在两肺下野第5前肋间处，小圆形致密影",
      "斜裂胸膜侧位片上表现为自后上第4、第5胸椎水平斜向前下方的线状影",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常规胸部正位片上均可见水平裂胸膜",
        "水平裂胸膜并非在常规正位片上均可见，仅当其与X线束相切时方能显示，故“均可见”错误。原书第04章 A1 型题第 3 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1004",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肺部疾病最理想的影像学检查方法是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["X线胸片", "MRI", "CT", "ECT", "超声"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT",
        "CT 密度分辨力高、无重叠，是目前肺部疾病最理想的影像学检查方法。原书第04章 A1 型题第 4 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1005",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "对肺部小病灶细节显示最好的检查技术是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "增强CT 扫描",
      "HRCT",
      "常规CT 扫描",
      "胸部 MRI",
      "CT 仿真内镜",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "HRCT",
        "高分辨力 CT（HRCT）采用薄层、高空间频率算法重建，对肺部小病灶细节显示最好。原书第04章 A1 型题第 5 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1006",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "所谓中肺野是指上肺野以下至",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "第4肋骨下缘的最低点",
      "第4肋骨前端下缘的最低点",
      "第4肋骨前端下缘的最低点水平线",
      "第4肋骨下缘的水平线以上",
      "第4肋骨前缘下缘水平线",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第4肋骨前端下缘的最低点水平线",
        "肺野分为上、中、下三带：上肺野为第2前肋下缘水平线以上，中肺野为上肺野以下至第4肋骨前端下缘最低点水平线，其下为下肺野。原书第04章 A1 型题第 6 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1007",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胸部X线片上肺纹理主要解剖成分是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["肺静脉", "肺动脉", "支气管", "肺动脉、静脉", "肺静脉、支气管"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺动脉",
        "肺纹理主要由肺动脉分支构成，肺静脉及支气管也参与组成肺门影。原书第04章 A1 型题第 7 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1008",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肺叶中肺段支气管数量的说法，下列哪项是正确的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "左右上肺叶各3个",
      "左肺有8个",
      "左右肺总共有20个",
      "右肺有12个",
      "左下肺叶有5个",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "左肺有8个",
        "右肺有10个肺段（上叶3、中叶2、下叶5），左肺有8个肺段（上叶4、下叶4）。原书第04章 A1 型题第 8 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1009",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列的有关描述中，哪项是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肺门影主要由肺动脉、肺静脉及伴行支气管等构成",
      "肺纹理为自肺门向肺野呈放射状分布的树枝状影",
      "胸部正位片上右肺门影比左肺门高1~2cm",
      "肺野是胸片上均匀一致较为透明的区域",
      "通常下肺野的肺纹理较上野粗而明显",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸部正位片上右肺门影比左肺门高1~2cm",
        "正位胸片上左肺门影较右肺门高 1~2cm，故“右肺门比左肺门高”错误。原书第04章 A1 型题第 9 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1010",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "右主支气管的特点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["细而长", "粗而短", "较水平", "细而短", "粗而长"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "粗而短",
        "右主支气管粗而短、走行较陡直，异物易落入右主支气管。原书第04章 A1 型题第 10 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1011",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于横膈的描述，下面哪项是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胸腔及腹腔压力的改变可影响横膈的位置",
      "膈局部发育薄弱向上局限性隆起称局限性膈膨升，好发于左侧",
      "横膈上有多个裂孔，如主动脉裂孔、食管裂孔和腔静脉裂孔",
      "双侧横膈形态呈内高外低、前高后低",
      "膈是分隔胸、腹腔的一块扁肌，右膈顶较左侧高1~2cm",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "膈局部发育薄弱向上局限性隆起称局限性膈膨升，好发于左侧",
        "局限性膈膨升好发于右侧，故该项错误。原书第04章 A1 型题第 11 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1012",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肺部MRI表现的描述中，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "较大的肺动、静脉均呈管状的无信号影",
      "肺血管与支气管之间的脂肪与结缔组织可呈高信号影",
      "快速梯度回波序列时，肺动、静脉也均呈低信号",
      "无论是肺野还是肺纹理的显示均远不及CT",
      "肺门部的支气管也表现为无信号影",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "快速梯度回波序列时，肺动、静脉也均呈低信号",
        "快速梯度回波序列中流动的血液呈高信号而非低信号，故该项错误。原书第04章 A1 型题第 12 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1013",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列肺实变的病因中，哪项是正确的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "各种肺炎",
      "肺泡癌",
      "肺泡性肺水肿",
      "以上都是",
      "肺出血",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "以上都是",
        "各种肺炎、肺泡性肺水肿、肺出血、肺泡癌等均可引起肺实变。原书第04章 A1 型题第 13 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1014",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于空洞或空腔描述错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "空洞壁可由坏死组织、肉芽组织、纤维组织、肿瘤组织所构成",
      "空洞多见于结核、肺癌、肺脓肿",
      "空腔与空洞形成的机制也是相同的",
      "肺大疱、含气肺囊肿及肺气囊属于空腔",
      "空洞为肺内病变组织发生坏死后经引流支气管排出后而形成",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "空腔与空洞形成的机制也是相同的",
        "空洞由病变组织坏死经引流支气管排出形成，空腔为生理腔隙病理性扩大，二者机制不同。原书第04章 A1 型题第 14 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1015",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于空洞的描述，哪项是正确的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "厚壁空洞是指洞壁厚超过3mm者",
      "干酪性肺炎所形成的空洞很少有液平面",
      "空洞壁的厚度可分厚壁空洞与薄壁空洞",
      "以上都是",
      "癌性空洞内壁不规则，可有壁结节",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "以上都是",
        "厚壁空洞洞壁>3mm，干酪性肺炎形成的空洞少有液平面，癌性空洞内壁不规则可有壁结节，各选项均正确。原书第04章 A1 型题第 15 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1016",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肺部结节与肿块区分的大小为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["≥2.5cm", "<3cm", "≥2cm", "≤3cm", ">2cm"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "≤3cm",
        "肺内直径≤3cm 的病灶称结节，>3cm 者称肿块。原书第04章 A1 型题第 16 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1017",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肺内2.5cm 结节灶伴钙化及“卫星灶”，最可能是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["炎性假瘤", "结核瘤", "错构瘤", "肺囊肿", "转移瘤"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "结核瘤",
        "结核瘤（结核球）常表现为肺内结节伴钙化及周围“卫星灶”。原书第04章 A1 型题第 17 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1018",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肺部CT上显示有钙化的结节灶可见于哪种疾病",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "寄生虫病",
      "转移性骨肉瘤",
      "结核瘤",
      "以上都是",
      "错构瘤",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "以上都是",
        "结核瘤、错构瘤、寄生虫病（如肺包虫）及转移性骨肉瘤的肺转移灶均可出现钙化。原书第04章 A1 型题第 18 题，参考答案键号 E（OCR 误作 F，按语义恢复）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1019",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪种征象最能提示肺错构瘤的诊断",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "边缘呈分叶状",
      "周围见“卫星灶”",
      "病灶内高密度钙化影",
      "病灶内钙化伴-78HU 低密度影",
      "边缘光滑呈类圆形",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "病灶内钙化伴-78HU 低密度影",
        "肺错构瘤典型 CT 表现为病灶内爆米花样钙化伴脂肪密度（约-78HU），为最具提示性的征象。原书第04章 A1 型题第 19 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1020",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肺间质性病变的描述错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "特发性肺纤维化是较为常见的肺间质性病变之一",
      "肺部网状、细线状及条索状影是间质性病变的表现",
      "不同病因所致的肺间质性病变表现也是相同的",
      "小叶间隔线也称Kerley B 线",
      "肺间质病变是指侵犯肺间质为主的病变",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "不同病因所致的肺间质性病变表现也是相同的",
        "不同病因所致的肺间质性病变影像表现可不相同，如特发性肺纤维化、结节病等各有特点。原书第04章 A1 型题第 20 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1021",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在后前位X线胸片上见外侧肋膈角变钝，说明液体量大约有",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["200ml", "300ml", "100ml", "250ml", "400ml"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "250ml",
        "少量胸腔积液首先积聚于后肋膈角，后前位胸片见外侧肋膈角变钝时液体量约 250ml。原书第04章 A1 型题第 21 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1022",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关肺底积液的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肋膈角可存在",
      "左侧较右侧多见",
      "位于肺底与横膈之间",
      "属于局限性胸腔积液",
      "易误认为横膈抬高",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "左侧较右侧多见",
        "肺底积液右侧较左侧多见（右侧膈下为肝脏，肺底积液易与膈肌抬高混淆）。原书第04章 A1 型题第 22 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1023",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列有关气胸的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肺组织有不同程度的受压萎陷",
      "纵隔向患侧移位，横膈下降",
      "带状无肺纹理的极低密度区",
      "内侧可见与胸壁平行的弧形脏层胸膜影",
      "多房气胸常提示有胸膜粘连",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "纵隔向患侧移位，横膈下降",
        "气胸时胸膜腔压力增高，纵隔应移向健侧、患侧横膈下降，故“纵隔向患侧移位”错误。原书第04章 A1 型题第 23 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1024",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胸膜肥厚、粘连的X线表现，下列哪项是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "膈上缘的幕状突起",
      "肋间隙增宽",
      "肋膈角变浅、变平",
      "纵隔向患侧移位",
      "呼吸时膈运动受限",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肋间隙增宽",
        "胸膜肥厚粘连使患侧胸廓收缩，肋间隙变窄而非增宽。原书第04章 A1 型题第 24 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1025",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列有关胸膜肿块的描述中错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "可伴或不伴有胸腔积液",
      "弥漫性多见于良性，也可为恶性",
      "肿块合并胸水多为恶性",
      "胸膜肿瘤可为局限性或弥漫性",
      "T1WI 上多呈高信号",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "弥漫性多见于良性，也可为恶性",
        "弥漫性胸膜肿块多见于恶性（如弥漫性胸膜间皮瘤），故“弥漫性多见于良性”错误。原书第04章 A1 型题第 25 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1026",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "引起纵隔增宽最常见的病变",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["炎症性", "血管性", "淋巴性", "脂肪性", "肿瘤性"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤性",
        "引起纵隔增宽最常见的病变是肿瘤性病变（纵隔肿瘤及肿瘤样病变）。原书第04章 A1 型题第 26 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1027",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "纵隔向健侧移位见于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "一侧广泛胸膜增厚",
      "张力性气胸",
      "一侧肺切除",
      "大叶性肺炎",
      "肺不张",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "张力性气胸",
        "张力性气胸患侧胸腔压力显著增高，推挤纵隔向健侧移位。原书第04章 A1 型题第 27 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1028",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可引起纵隔向患侧移位的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "气胸",
      "胸腔积液",
      "较大肺肿瘤",
      "广泛性胸膜增厚",
      "一侧性肺气肿",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "广泛性胸膜增厚",
        "广泛胸膜增厚使患侧胸廓收缩、牵拉纵隔向患侧移位。原书第04章 A1 型题第 28 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1029",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关纵隔病变的CT强化表现，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "良性实性病变强化多均匀",
      "囊性病变仅有轻度强化",
      "脂肪密度病变常不强化",
      "血管性病变的强化程度最显著",
      "恶性实性病变常不均匀强化",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "囊性病变仅有轻度强化",
        "囊性病变囊壁可轻度强化而囊内液体不强化，故“仅有轻度强化”的表述错误。原书第04章 A1 型题第 29 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-a1030",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "产生液气胸的常见原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["出血", "感染", "肿瘤", "外伤", "胸膜粘连"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "外伤",
        "液气胸常见于外伤（胸壁穿透伤或肺撕裂）使气体与液体同时进入胸膜腔。原书第04章 A1 型题第 30 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），5 道（原书第 1–5 题） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch04-resp-short001",
    order: 40,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述支气管阻塞后继发改变及其主要X线表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "支气管阻塞后继发改变包括：①阻塞性肺气肿，分为局限性（一侧、一叶或一段）与弥漫性，主要X线表现为病变部位肺野透明度增加、体积增大，肺纹理稀疏，纵隔移向健侧，患侧横膈下降等；②阻塞性肺炎，X线表现与普通肺炎类似，但临床治疗效果差，同一部位反复发作；③阻塞性肺不张，可发生于一侧、一叶或一段，共同X线表现为病变处肺体积减小、密度增高，叶间裂向心性移位，纵隔与横膈也不同程度向患处移位。",
        "支气管阻塞的三个后继改变（阻塞性肺气肿、阻塞性肺炎、阻塞性肺不张）及各自X线表现。原书第04章简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-short002",
    order: 41,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述肺良性结节与恶性结节的X线与CT鉴别要点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "X线上：肺良性结节多有包膜，边缘光滑锐利，呈圆形或类圆形，内部多见钙化，周围可见“卫星灶”；肺恶性结节多呈浸润性生长，边缘不锐利，常有短细毛刺和分叶状，靠近胸膜时可见胸膜凹陷征。CT上与X线表现类似，主要从形态轮廓（分叶、毛刺）、内部结构（小泡征、钙化、脂肪等）、边缘征象（胸膜凹陷征、卫星灶）及增强改变等方面鉴别；CT增强中肺恶性结节常较明显均匀强化或中心强化，良性结节无强化、轻度强化或周边环状强化。",
        "肺良性结节与恶性结节的鉴别主要围绕边缘、内部结构、周围征象与增强表现展开。原书第04章简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-short003",
    order: 42,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述气胸的X线表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①少量气胸时，气胸区呈线状或带状无纹理区，可见被压缩肺的边缘，呼气时显示较为清楚；②大量气胸时，气胸区可占据肺野的中外带，内带为压缩的肺，呈密度均匀软组织影，同侧肋间隙增宽、横膈下降、纵隔向健侧移位；③液气胸时，立位片可见气-液平面，严重时气-液平面横贯患侧整个胸腔；④如脏、壁层胸膜粘连，可形成局限性或多房性气胸或液气胸。",
        "气胸X线表现按少量、大量、液气胸及粘连分隔等不同情形分别描述。原书第04章简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-short004",
    order: 43,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述肺挫伤的CT表现类型。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "轻微肺挫伤表现为边缘模糊的磨玻璃样密度影，常呈外围性非段性分布，多位于邻近肋骨骨折和胸壁血肿处。依其表现可分为四型：①外围型的含气或气-液囊腔，此型多见；②肺底脊柱旁的含气-液囊腔，为肺组织压向脊柱引起的肺撕裂伤；③周围型小的含气囊腔或线样透亮影，常伴肋骨骨折；④胸膜粘连后发生的肺撕裂伤，此型不易显示。肺血肿表现为类圆形均匀高密度影，周围可因肺挫伤的存在而边缘模糊。",
        "肺挫伤CT表现分为磨玻璃密度影及四种类型的肺撕裂伤/肺血肿表现。原书第04章简答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-short005",
    order: 44,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：肺部空洞性病变见于哪几种疾病，如何鉴别？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺部空洞性病变常见于肺癌、肺结核、肺脓肿三种疾病。鉴别要点：①癌性空洞多位于上叶前段及下叶基底段，空洞外壁不规则呈分叶状，空洞直径多大于 3cm，多为偏心空洞，洞壁凹凸不规则，可见内壁结节；②肺结核空洞多见于上叶尖段、后段或下叶背段，洞壁薄（多小于 4mm），洞壁多光滑，病灶周围可见“卫星灶”；③肺脓肿多占据一个或多个肺段，病灶周围模糊，多为厚壁空洞，空洞壁多较光滑，洞内可见气-液平面。",
        "肺部空洞性病变主要见于肺癌、肺结核和肺脓肿，鉴别围绕空洞部位、洞壁厚度与形态、内外壁表现及周围病灶特征展开。原书第04章简答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 配伍题，2 组 / 5 成员（B 型第 86~88 题、89~90 题） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch04-resp-b001",
    order: 45,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "肺实变病灶中呈现含气的支气管分支影",
      "洞壁厚度>3mm，伴内壁结节影，外缘见毛刺",
      "肺内正常生理腔隙的病理性扩大",
      "肺结节边缘多个弧形凸起形成分叶状",
      "病灶周围出现结节状或斑片状“卫星灶”",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch04-resp-b001m1",
        order: 45,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "分叶征",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肺结节边缘多个弧形凸起形成分叶状",
            "分叶征指肺结节边缘多个弧形凸起形成分叶状轮廓。原书第04章 B 型题第 86 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch04-resp-b001m2",
        order: 46,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "空气支气管征",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肺实变病灶中呈现含气的支气管分支影",
            "空气支气管征指肺实变病灶中可见含气的支气管分支影。原书第04章 B 型题第 87 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch04-resp-b001m3",
        order: 47,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "肺空腔",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肺内正常生理腔隙的病理性扩大",
            "肺空腔指肺内生理腔隙的病理性扩大，如肺大疱、含气肺囊肿及肺气囊。原书第04章 B 型题第 88 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch04-resp-b002",
    order: 48,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "胸壁向肺野突出的凸镜形液体样密度影",
      "胸壁下弧形窄带状或新月形液体样密度影",
      "叶裂处条带状的液体密度影",
      "“横膈升高”圆顶最高点位于偏外 1/3",
      "整个胸腔为液体样密度影占据",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch04-resp-b002m1",
        order: 48,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "包裹性胸腔积液表现为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "胸壁向肺野突出的凸镜形液体样密度影",
            "包裹性胸腔积液表现为胸壁向肺野突出的凸镜形（半圆形或扁丘状）液体样密度影。原书第04章 B 型题第 89 题，参考答案键号 C（OCR 误作 G，按语义恢复）。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch04-resp-b002m2",
        order: 49,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "肺底积液表现为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "“横膈升高”圆顶最高点位于偏外 1/3",
            "肺底积液表现为“横膈升高”而圆顶最高点位于偏外 1/3，为与真性膈肌抬高的鉴别要点。原书第04章 B 型题第 90 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...fillItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
