import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学影像学学习指导与习题集 第3版 — 第05章 循环系统 题库提取（等比取样）
 * 来源：《医学影像学学习指导与习题集》第3版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：6 题
 * - 填空题（fill）：7 题
 * - 选择题（a1-single）：23 题（A1 型 23、A2 型病例题 0）
 * - 简答题（short-answer）：7 题
 * - B1 配伍题：1 组 / 5 成员
 * - 独立记分题合计：48 题（须等于本文件预算 48）
 * - 缺失答案：0；无法可靠提取：0（A1 型原书第 19 题 OCR 缺失选项 D、无法可靠重建，
 *   换取第 24 题）
 * - 说明：本章原书含名词解释 18 题、填空题 21 题、选择题（A1 型 1–63、A2 型 64–66、
 *   B 型 67–81）、简答题 19 题；本文件按 48 道预算在原书顺序内等比取材：名词解释取第
 *   1–6 题、填空题取第 1–7 题、A1 型取第 1–18、20–24 题（第 19 题“急性心肌梗死 MRI
 *   表现”OCR 缺失选项 D 换第 24 题“主动脉瘤管腔扩张倍数”；A2 型因预算所限未取）、
 *   B 型取第 67–71 题（1 组）、简答题取第 1–7 题；未纳入的题因预算所限。正确项对齐章末
 *   参考答案键号（A1 1–63、A2 64–66、B1 67–81 全书连续编号，参考答案区键号即对应题号）；
 *   键号 15.G 按医学语义恢复为 C（左心房、右心室增大）。选项与共用备选答案已随机重排并
 *   同步 correctChoiceIndex。OCR 错字已按医学影像学医学语义恢复（如 又线→X线、CI→CT、
 *   分辦率→分辨率、星→呈、石心室→右心室、王动脉→主动脉、偣→倍、面级→Ⅲ级、沩→为
 *   等），数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "radiology-bank-ch05-circ";
const locatorBase =
  "《医学影像学学习指导与习题集》第3版 第05章 循环系统 习题（核对PDF 第71–85页）";
const promptNote =
  "题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），6 道（原书第 1–6 题） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch05-circ-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：镜面右位心",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "镜面右位心是相对多见的一种先天性心脏异常，是右位心合并内脏转位，即心脏房室和大动脉的位置关系以及胸腹脏器完全倒转，如正常左位心成镜面像，心尖指向右侧。",
        "镜面右位心是右位心合并内脏转位（完全倒转），心尖指向右侧。原书第05章名词解释第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肺栓塞",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺栓塞是肺动脉分支被外源性血栓或栓子堵塞后引起的相应肺组织供血障碍。大多数肺栓塞患者的栓子源自下肢深静脉的血栓，久病卧床、妊娠、外科手术后、心肌梗死、心功能不全和抗血凝因子缺乏可发生深静脉血栓，是发生肺栓塞的主要病因。",
        "肺栓塞的栓子多来源于下肢深静脉血栓，属心血管系统常见急症。原书第05章名词解释第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：双腔主动脉",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "双腔主动脉是主动脉夹层的影像所见，由于内膜撕裂形成内膜片，将主动脉分为真腔和假腔，通常假腔大于真腔。",
        "双腔主动脉是主动脉夹层在 CTA/MRA 等影像上的典型表现，由内膜片分隔真假腔。原书第05章名词解释第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：Kerley B 线",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "当肺静脉压升高，引起渗出液存留在小叶间隔内，X线表现为在肋膈角附近见到与外侧胸壁垂直的间隔线，称 Kerley B 线。",
        "Kerley B 线为小叶间隔线，见于肺静脉高压，是间质性肺水肿的重要征象。原书第05章名词解释第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肺血减少",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "当右心室流出道梗阻和右心输出量减少时，肺门血管阴影和肺野内血管纹理普遍变细变少，使得肺门影变小而结构清楚，肺野异常清晰，称为肺少血或肺血减少。",
        "肺血减少（肺少血）常见于右心流出道梗阻性疾病，如法洛四联症、肺动脉狭窄等。原书第05章名词解释第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：双心房影",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "当左心房增大，心底部出现圆形或椭圆形密度增高影，常略偏右，与右心房重叠，在正位片上显示呈双心房影。",
        "双心房影是左心房增大的重要X线征象，为增大左房与右房重叠所致。原书第05章名词解释第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），7 道（原书第 1–7 题） */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch05-circ-fill001",
    order: 7,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：法洛四联症的主要畸形包括____、____、____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺动脉、肺动脉瓣或（和）瓣下狭窄；室间隔缺损；主动脉骑跨；右心室肥厚",
        "法洛四联症基本畸形包括肺动脉狭窄、室间隔缺损、主动脉骑跨和右心室肥厚。原书第05章填空题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-fill002",
    order: 8,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：测量____是确定心脏有无增大最简单的方法。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心胸比率",
        "心胸比率为心影最大横径与胸廓最大横径之比，正常不超过 0.5，是确定心脏有无增大最简单的方法。原书第05章填空题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-fill003",
    order: 9,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：在MRI自旋回波序列中，心肌呈____信号强度，与横纹肌相似。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中等",
        "MRI 自旋回波序列中心肌呈中等信号强度，与横纹肌相似。原书第05章填空题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-fill004",
    order: 10,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：心包在SE序列上呈____信号，周围可见高信号为心包外及心外膜下脂肪。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "低",
        "心包为纤维组织，在 SE 序列上呈低信号，其内外脂肪呈高信号形成对比。原书第05章填空题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-fill005",
    order: 11,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：二尖瓣狭窄时心影增大呈____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "梨型（二尖瓣型）",
        "二尖瓣狭窄时心影呈二尖瓣型（梨型）：肺动脉段突出、心尖圆隆上翘。原书第05章填空题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-fill006",
    order: 12,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：冠心病时冠状动脉狭窄在____以下时，休息及运动状态冠状动脉供血充足。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "50%",
        "冠状动脉狭窄在 50% 以下时，休息及运动状态下冠状动脉供血仍充足。原书第05章填空题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-fill007",
    order: 13,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：心肌缺血但未发生心肌梗死时，MR心肌灌注首过期成像病变区信号强度____正常心肌。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "低于",
        "心肌缺血区灌注减低，MR 心肌灌注首过期成像病变区信号强度低于正常心肌。原书第05章填空题第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），23 道（A1 型第 1–18、20–24 题；第 19 题 OCR 缺失换第 24 题） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1001",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪种不是左向右分流的先天性心脏病",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "心内膜垫缺损",
      "法洛四联症",
      "室间隔缺损",
      "动脉导管未闭",
      "房间隔缺损",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "法洛四联症",
        "法洛四联症为右向左分流（发绀型）先天性心脏病，其余均为左向右分流型。原书第05章 A1 型题第 1 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1002",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪种先天性心脏病肺血减少",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "动脉导管未闭",
      "法洛四联症",
      "房间隔缺损",
      "室间隔缺损",
      "艾森曼格氏综合征",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "法洛四联症",
        "法洛四联症因肺动脉狭窄致肺血减少，其余疾病多表现为肺血增多。原书第05章 A1 型题第 2 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1003",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "诊断缩窄性心包炎的特征性X线表现是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "心缘僵直、不规则",
      "左心室肥厚",
      "心包钙化",
      "心搏动消失或明显减弱",
      "心瓣膜钙化",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心包钙化",
        "心包钙化是诊断缩窄性心包炎的特征性X线表现，钙化多分布于右室前缘、膈面和房室沟。原书第05章 A1 型题第 3 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1004",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "通常法洛四联症不包括下述哪一项",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "右位主动脉弓及降主动脉",
      "肺动脉漏斗部兼有瓣膜部狭窄",
      "右心室肥厚",
      "主动脉骑跨",
      "室间隔高位缺损",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "右位主动脉弓及降主动脉",
        "法洛四联症的基本畸形为肺动脉狭窄、室间隔缺损、主动脉骑跨和右心室肥厚，通常不包括右位主动脉弓。原书第05章 A1 型题第 4 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1005",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪种疾病可使右心室增大，肺动脉段凹陷",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肺动脉狭窄",
      "肺源性心脏病",
      "房间隔缺损",
      "二尖瓣狭窄",
      "法洛四联症",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "法洛四联症",
        "法洛四联症因肺动脉狭窄（漏斗部狭窄）致肺动脉段凹陷，同时右心室增大。原书第05章 A1 型题第 5 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1006",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "主动脉瘤的定义，哪项是正确的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "主动脉局限狭窄，伴远侧端扩张",
      "主动脉粥样硬化，呈弥漫迂曲扩张",
      "主动脉内径增大，呈梭形或囊形扩张，其内径为相应正常部位内径的1.5倍以上",
      "主动脉内径增大，呈梭形或囊形扩张，其内径为相应正常部位内径的1倍以上",
      "主动脉内径增大，呈梭形或囊形扩张，其内径为相应正常部位内径的2.0倍以上",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "主动脉内径增大，呈梭形或囊形扩张，其内径为相应正常部位内径的1.5倍以上",
        "主动脉瘤定义为主动脉内径呈梭形或囊形扩张，内径达相应正常部位内径的 1.5 倍以上。原书第05章 A1 型题第 6 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1007",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "急性主动脉夹层最常见的临床表现是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脑血管意外或截瘫",
      "心率增快，心底部可闻及杂音",
      "心悸、气短",
      "突发剧烈胸、背疼痛",
      "肢体血压与脉搏不对称",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "突发剧烈胸、背疼痛",
        "急性主动脉夹层最常见的临床表现是突发剧烈胸、背疼痛。原书第05章 A1 型题第 7 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1008",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胸部透视用于心脏检查，下列哪一项是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "可留下永久记录",
      "可作为补偿检查手段",
      "接受X线剂量较大",
      "可不作为常规应用",
      "可以多体位、动态观察",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "可留下永久记录",
        "透视不能留下永久记录，摄片才能留下永久记录，故该项错误。原书第05章 A1 型题第 8 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1009",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一项不是心脏超声检查的优势",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "二维超声心动图是较为理想的冠状动脉无创检查方法",
      "M型超声时间分辨力较好，二维超声空间分辨力好",
      "对于某些先天性心脏病和瓣膜病，超声心动图可取代心血管造影检查",
      "经食道超声心动图检查法显示左房内血栓优于常规经胸超声检查",
      "二维超声心动图能清晰直观、实时显示心脏的结构",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "二维超声心动图是较为理想的冠状动脉无创检查方法",
        "超声对冠状动脉显示有限，冠状动脉检查以 CT 血管成像或造影为佳，故该项不是超声优势。原书第05章 A1 型题第 9 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1010",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一项的叙述是正确的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "M型超声能清晰直观、实时显示心脏的结构",
      "心脏超声检查是有创的心血管检查方法",
      "多普勒超声心动图应用多普勒效应对心血管内血流方向、速度和状态进行显示",
      "心脏超声检查一般不用于先天性心脏病的诊断",
      "心脏超声检查一般在立位下进行",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多普勒超声心动图应用多普勒效应对心血管内血流方向、速度和状态进行显示",
        "多普勒超声心动图利用多普勒效应显示血流方向、速度与状态，为正确叙述。原书第05章 A1 型题第 10 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1011",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一项叙述是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "常规心脏摄片要求在立位下进行",
      "心血管MRI的主要优点之一是：具有良好的组织对比",
      "胸部透视的影像清晰度差",
      "普通CT 可以用于心脏血管疾病诊断",
      "心脏超声检查有多种方法，综合应用能提高诊断的正确性",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "普通CT 可以用于心脏血管疾病诊断",
        "普通 CT 时间分辨率低，难以用于心脏血管疾病诊断，需 MSCT 等高速扫描。原书第05章 A1 型题第 11 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1012",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "CT用于心血管影像检查，哪一项叙述不正确",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "MSCT 能发现冠状动脉的钙化",
      "MSCT 不应用对比剂也能进行冠状动脉成像，从而直观地发现冠状动脉狭窄",
      "普通CT 的空间分辨率和时间分辨率都低",
      "MSCT 可用于心血管疾病的诊断",
      "MSCT 能观察心脏大血管的形态、运动状态，还可评价心功能",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "MSCT 不应用对比剂也能进行冠状动脉成像，从而直观地发现冠状动脉狭窄",
        "MSCT 冠状动脉成像需经静脉注射对比剂增强，不注射对比剂不能显示冠状动脉狭窄。原书第05章 A1 型题第 12 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1013",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于MRI心血管检查，下列哪一项叙述是正确的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "MRI 是利用X线进行成像的，因此有射线损伤",
      "目前尚不能获得心血管的三维图像",
      "能够准确显示运动心脏功能",
      "MRI 检查通常要向血管内注射含碘对比剂进行成像",
      "用于冠状动脉成像目前已非常成熟",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "能够准确显示运动心脏功能",
        "MRI 能准确显示心功能、血流灌注及心肌活性；MRI 无射线、无需含碘对比剂，冠脉成像尚在发展中。原书第05章 A1 型题第 13 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1014",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一项属于有创的心血管检查方法",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "常规心脏超声检查",
      "CT 心血管检查",
      "MRI 心血管检查",
      "常规心脏摄片",
      "心血管造影检查",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心血管造影检查",
        "心血管造影需经导管插管注入对比剂，属有创检查。原书第05章 A1 型题第 14 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1015",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "单纯二尖瓣狭窄主要的X线表现",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "右心房、右心室增大",
      "左心房、右心室增大",
      "左心房、左心室增大",
      "以上都不是",
      "右心房、左心室增大",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "左心房、右心室增大",
        "单纯二尖瓣狭窄导致左心房增大（左房压力升高）及右心室增大（肺循环高压），左心室不大。原书第05章 A1 型题第 15 题，参考答案键号 C（OCR 误作 G，按语义恢复）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1016",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "普通X线在发现冠心病重要并发症方面可提供有价值的资料，哪些并发症早于临床",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "左室乳头肌断裂和功能不全",
      "室间隔穿孔",
      "以上都不是",
      "室壁瘤",
      "发现冠心病引起的左心功能不全",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "发现冠心病引起的左心功能不全",
        "普通X线可通过肺淤血、间质性肺水肿等表现较早发现冠心病引起的左心功能不全，可早于临床。原书第05章 A1 型题第 16 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1017",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "心肌梗死后综合征不包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "心包积液",
      "肺下叶渗出改变",
      "心包钙化",
      "胸腔积液",
      "以上都是",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心包钙化",
        "心肌梗死后综合征包括心包积液、胸腔积液及肺下叶渗出性改变，不包括心包钙化。原书第05章 A1 型题第 17 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1018",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "心肌梗死时超声心动图表现不包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "收缩期心肌增厚率减低",
      "病变区局部运动增强",
      "心肌变薄",
      "以上都是",
      "室壁运动异常",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "病变区局部运动增强",
        "心肌梗死区超声心动图表现为心肌变薄、收缩期增厚率减低及室壁运动异常，不发生局部运动增强。原书第05章 A1 型题第 18 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1019",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "对冠心病室壁瘤诊断最可靠的方法是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "冠状动脉造影",
      "X线片",
      "右心室造影",
      "透视",
      "左心室造影",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "左心室造影",
        "左心室造影可直接显示室壁瘤的部位、大小及反常运动，是诊断室壁瘤最可靠的方法。原书第05章 A1 型题第 20 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1020",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪项不符合于肺充血的改变",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肺动脉段突出",
      "透视下肺门动脉搏动增强",
      "上肺静脉扩张、下肺静脉不扩张",
      "肺纹理增粗、增多、边缘清楚",
      "肺野透光度正常",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "上肺静脉扩张、下肺静脉不扩张",
        "上肺静脉扩张、下肺静脉不扩张是肺淤血（肺静脉高压）的表现，不符合肺充血改变。原书第05章 A1 型题第 21 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1021",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "常规心脏投照体位哪项是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "右前斜位服钡",
      "前弓位",
      "后前位",
      "左前斜位",
      "左侧位服钡",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前弓位",
        "常规心脏投照体位包括后前位、右前斜位（服钡）、左前斜位和左侧位（服钡），前弓位不是常规心脏投照体位。原书第05章 A1 型题第 22 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1022",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "正常人心胸比率应小于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["0.40", "0.60", "0.38", "0.50", "0.45"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "0.50",
        "正常人心胸比率应小于 0.50，超过 0.5 提示心脏增大。原书第05章 A1 型题第 23 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-a1023",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "主动脉瘤指主动脉管腔扩张大于正常主动脉的____倍以上",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["3.0", "1.0", "1.5", "2.5", "2.0"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "1.5",
        "主动脉管腔扩张达正常主动脉内径的 1.5 倍以上可诊断主动脉瘤。原书第05章 A1 型题第 24 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），7 道（原书第 1–7 题） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch05-circ-short001",
    order: 37,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述心血管MRI的主要优点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心血管MRI的主要优点包括：良好的组织对比；可迅速获得三维图像；对血流有特殊敏感性；无射线损害，无需含碘对比剂；能准确显示心功能、血流灌注及心肌活性。",
        "心血管MRI以无射线、组织对比好、可三维成像及血流敏感性为突出优点。原书第05章简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-short002",
    order: 38,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：大血管病变影像学检查方法分为有创性和无创性两种，无创性影像学方法有什么？请简述有创性和无创性影像学方法的优缺点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "（1）应用于大血管病变的无创性影像学方法有经胸超声心动图、经食道超声心动图、CT 和 MRI。（2）有创性影像学方法指X线血管造影，目前仍被视为血管疾病诊断的“金标准”，其主要优点是时间分辨力和空间分辨力高、可同时进行介入治疗，主要缺点是属有创检查、因缺少横断影像对某些病变显示差；无创性影像学方法主要优点是无需穿刺插管、适应证广，横断影像可同时显示血管腔、血管壁和血管周围结构，目前基本取代有创检查用于大血管疾病诊断。",
        "无创影像方法（超声/CT/MRI）与有创X线血管造影的优缺点对比。原书第05章简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-short003",
    order: 39,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述房间隔缺损的血流动力学改变和X线表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血流动力学：正常情况下左房压力高于右房，房水平分流呈左向右分流，右心房同时接受体循环回流的静脉血和异常分流的血液，血容量增加、心房增大；右心室、肺动脉血流量相应增加，右心负荷加重，室壁肥厚，肺循环阻力增加即出现肺动脉高压；当右房压力逐渐接近并超过左房时出现双向或右向左分流，临床出现发绀。X线表现：肺血增多；心影呈二尖瓣型，主动脉结正常或缩小，肺动脉段突出，右心房、室增大。",
        "房间隔缺损的基本血流动力学为房水平左向右分流及继发肺动脉高压，X线表现为肺血增多与右心房室增大。原书第05章简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-short004",
    order: 40,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述急性心肌梗死与陈旧性心肌梗死的MRI表现的相同点和不同点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "不同点：急性心肌梗死梗死心肌信号强度增高，尤其在 T2WI 更明显；陈旧性心肌梗死时梗死心肌信号强度减弱，尤其在 T2WI。相同点：①心肌灌注首过成像显示灌注减低或缺损，延迟期成像显示梗死心肌呈明显高信号；②梗死心肌壁变薄；③节段性室壁运动减弱、消失，收缩期室壁增厚减低或消失。",
        "急性与陈旧性心肌梗死 MRI 的主要差异在于梗死心肌 T2WI 信号高低，其余（灌注缺损、室壁变薄、运动异常）表现相同。原书第05章简答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-short005",
    order: 41,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：简述二尖瓣关闭不全X线表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "二尖瓣关闭不全所致轻度反流时，左房可轻度增大，无肺静脉高压；中度以上反流时，左房、室明显增大，出现肺淤血、肺静脉高压表现，左房、室搏动增强。",
        "二尖瓣关闭不全的X线表现随反流程度加重而明显：左房室增大、肺淤血及搏动增强。原书第05章简答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-short006",
    order: 42,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：叙述法洛四联症的X线表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "法洛四联症的X线表现为：肺血少；心脏呈靴型，主动脉增宽，肺动脉段凹陷，右心室增大。",
        "法洛四联症X线呈典型“靴型心”：肺血少、肺动脉段凹陷、主动脉增宽、右室增大。原书第05章简答题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch05-circ-short007",
    order: 43,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简答题：心包积液时X线有哪些表现？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "少量心包积液时，心影大小、形态以及心脏搏动可无明显改变；当积液在 300~500ml 以上时，X线检查才能发现异常。中等量和大量心包积液时，心影向两侧普遍扩大，正常心缘各曲度消失，呈烧瓶状改变；合并心功能不全时表现为肺淤血。",
        "心包积液X线以心影烧瓶状扩大、心缘弧度消失为特征，少量积液可无异常。原书第05章简答题第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 配伍题，1 组 / 5 成员（B 型第 67~71 题） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch05-circ-b001",
    order: 44,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "肺动脉段突出",
      "左心室膈面延长",
      "胸骨后间隙缩小",
      "气管隆嵴角度增大",
      "心右缘下段膨隆延长",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch05-circ-b001m1",
        order: 44,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "左心房增大的胸片表现是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "气管隆嵴角度增大",
            "左心房增大压迫气管分叉使气管隆嵴角度增大。原书第05章 B 型题第 67 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch05-circ-b001m2",
        order: 45,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "左心室增大的胸片表现是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "左心室膈面延长",
            "左心室增大时心左缘下段向左下延伸，膈面延长。原书第05章 B 型题第 68 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch05-circ-b001m3",
        order: 46,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "右心房增大的胸片表现是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "心右缘下段膨隆延长",
            "右心房增大表现为心右缘下段膨隆延长。原书第05章 B 型题第 69 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch05-circ-b001m4",
        order: 47,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "右心室增大的胸片表现是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "胸骨后间隙缩小",
            "右心室增大时心前缘向前凸出，左侧位片上胸骨后间隙缩小。原书第05章 B 型题第 70 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch05-circ-b001m5",
        order: 48,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "肺动脉高压的胸片表现是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肺动脉段突出",
            "肺动脉高压时肺动脉段突出，肺门动脉扩张、外周纹理纤细。原书第05章 B 型题第 71 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...fillItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
