import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学影像学学习指导与习题集 第3版 — 第01章 影像诊断学总论 题库提取（等比取样）
 * 来源：《医学影像学学习指导与习题集》第3版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：14 题
 * - 填空题（fill）：12 题
 * - 选择题（a1-single）：24 题（A1 型 24、A2 型病例题 0）
 * - 简答题（short-answer）：9 题
 * - B1 配伍题：4 组 / 12 成员
 * - 独立记分题合计：71 题（须等于本文件预算 71）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书含名词解释、填空题、选择题（A1/A2/B1）、简答题；本文件按 71 道预算在
 *   原书顺序内取材：名词解释取第 1–14 题、填空题取第 1–12 题、A1 型取第 1–24 题（A2 型
 *   因预算所限未取）、B 型取第 68–79 题（组 68~69、70~71、72~74、75~79）、简答题取第
 *   1–9 题；未纳入的题因预算所限。正确项对齐章末参考答案键号（A1 1–61、A2 62–67、
 *   B1 68–96 全书连续编号，参考答案区键号即对应题号），选项与共用备选答案已随机重排并
 *   同步 correctChoiceIndex。OCR 错字已按医学影像学医学语义恢复（如 丁解→了解、介人→
 *   介入、分辦力→分辨力、星→呈、包转→包括、CIT/CT→CT、T,WI→T1WI 等），数值与单位
 *   保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "radiology-bank-ch01-intro";
const locatorBase =
  "《医学影像学学习指导与习题集》第3版 第01章 影像诊断学总论 习题（核对PDF 第2–21页）";
const promptNote =
  "题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），14 道（原书第 1–14 题） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：数字化X线成像",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "数字化X线成像包括 CR 和 DR，成像过程中均需将透过人体的 X 线信息进行像素化和数字化，再经计算机系统进行各种处理，最后转换成模拟X线图像。",
        "数字化X线成像是相对传统屏-片系统而言，以像素化和数字化为核心处理环节。原书第01章名词解释第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：自然对比",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "X线检查时，基于人体组织结构固有的密度和厚度差异所形成的灰度对比，称之为自然对比。",
        "自然对比是X线成像的基础之一，不同组织因密度、厚度差异形成灰度对比。原书第01章名词解释第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：人工对比",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对于缺乏自然对比的组织或器官，可以人为引入密度高于或低于该组织或器官的物质，使之产生灰度对比，称之为人工对比。",
        "人工对比通过引入对比剂（高密度或低密度）制造灰度差异，是造影检查的基础。原书第01章名词解释第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：X线造影检查",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "通过人工对比方法进行的X线检查即为X线造影检查。",
        "X线造影检查依赖人工对比，将对比剂引入体内使缺乏自然对比的结构显影。原书第01章名词解释第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：CT（X线计算机体层成像）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 即X线计算机体层成像，是由英国工程师 Hounsfield 设计并于 1971 年应用于临床的一种现代医学成像技术。CT 的应用明显提高了病变的检出率和诊断的准确率，显著扩大了医学影像诊断的应用领域，从而极大地促进了医学影像诊断学的发展。",
        "CT 以断层图像、密度分辨力高为特点，是影像诊断学发展的重要里程碑。原书第01章名词解释第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：体素",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 成像中，需将扫描层面分为若干体积相同的立方体或长方体，称之体素。",
        "体素是CT扫描层面的三维体积单元，与二维像素概念相区别。原书第01章名词解释第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：像素",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 成像中，需将扫描层面的数字矩阵，依其数值的高低赋予不同的灰阶，进而转换成黑白不同灰度的方形单元，称之为像素。",
        "像素是构成CT图像的二维显示单元，其灰度反映相应体素的X线吸收系数。原书第01章名词解释第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：CT平扫",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 平扫指不用对比剂（不包括应用胃肠道对比剂）的扫描，常规先行平扫。",
        "平扫是CT检查的基础步骤，一般不使用对比剂，必要时再行增强检查。原书第01章名词解释第 8 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：CT对比增强检查",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 对比增强检查指经静脉注入水溶性有机碘对比剂后再行扫描的方法，常简称为CT增强检查。",
        "CT增强检查通过对比剂改变组织结构与病灶的对比，常用于病变定性。原书第01章名词解释第 9 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：CT动态增强扫描",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 动态增强扫描指注射对比剂后对某一选定层面或区域、在一定时间范围内进行连续多期扫描（常用三期扫描，即动脉期、静脉期和实质期），主要用于了解组织、器官或病变的血液供应状况。",
        "CT动态增强通过多期扫描观察病灶强化随时间的变化，反映其血供特点。原书第01章名词解释第 10 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：CT灌注成像",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 灌注成像指在静脉注射对比剂的同时对选定的层面进行连续多次动态扫描，以获得该层面内每一体素的时间-密度曲线，然后根据曲线利用不同的数学模型计算出组织血流灌注的各项参数，并通过色阶赋值形成灌注图像，以此来评价组织器官的灌注状态。",
        "CT灌注成像属于功能成像，能够反映毛细血管水平的血流灌注状况，可用于脑梗死等疾病诊断。原书第01章名词解释第 11 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：CT造影",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 造影指对某一器官或结构进行造影再行扫描的方法，它能更好地显示结构和发现病变。",
        "CT造影（如CT脊髓造影、CT关节造影）借助造影剂使特定结构显示更清晰。原书第01章名词解释第 12 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：CT血管造影",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 血管造影采用静脉团注的方式注入含碘对比剂，当对比剂流经靶区血管时，利用多层螺旋CT进行快速连续扫描，再行多平面及三维CT重组获得血管成像的一种方法。",
        "CTA属无创血管成像，常用于冠状动脉狭窄等血管疾病诊断。原书第01章名词解释第 13 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-term014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：CT脊髓造影",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 脊髓造影指在椎管脊髓蛛网膜下腔内注射非离子型水溶性碘对比剂，让患者翻动体位，使对比剂混匀后，再行CT扫描，以显示椎管内病变。",
        "CT脊髓造影用于显示椎管内病变，多与脊髓造影配合使用。原书第01章名词解释第 14 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），12 道（原书第 1–12 题） */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch01-intro-fill001",
    order: 15,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：与X线成像有关的X线特性为____、____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：穿透性；第2空：荧光效应；第3空：感光效应。",
        "X线的穿透性、荧光效应和感光效应是与X线成像有关的三种基本性质。原书第01章填空题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-fill002",
    order: 16,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：X线成像时，高密度组织如骨对X线吸收____、透过的X线____，在X线片上呈____影；低密度组织如肺对X线吸收____、透过的X线____，在X线片上呈____影。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：多；第2空：少；第3空：白；第4空：少；第5空：多；第6空：黑。",
        "高密度组织（如骨）吸收X线多、透过少，在X线片上呈白影；低密度组织（如肺）吸收少、透过多，呈黑影。原书第01章填空题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-fill003",
    order: 17,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：数字化X线成像时，CR是以____代替胶片，作为透过人体X线信息的载体，而DR则用____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：影像板；第2空：平板探测器。",
        "CR 以影像板（IP）作为X线信息载体，DR 直接采用平板探测器（FPD）。原书第01章填空题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-fill004",
    order: 18,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：软X线摄影是用钼靶或铑靶X线管的摄影技术，专门用于____X线检查。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：乳腺。",
        "软X线（低能X线）摄影利用钼靶或铑靶X线管，专门用于乳腺X线检查。原书第01章填空题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-fill005",
    order: 19,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：X线检查时应遵循辐射防护的三项基本原则，即____、____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：屏蔽防护；第2空：距离防护；第3空：时间防护。",
        "X线辐射防护三项基本原则为屏蔽防护、距离防护和时间防护。原书第01章填空题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-fill006",
    order: 20,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：CT图像上，为了使感兴趣组织结构达到最佳显示效果，需根据其CT值范围，选用不同的____，其中包括____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：窗设置；第2空：窗位；第3空：窗宽。",
        "窗技术（窗位、窗宽）是CT图像显示的重要调节手段，使感兴趣组织达到最佳显示效果。原书第01章填空题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-fill007",
    order: 21,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：CT图像后处理中，三维显示技术包括：____、____、____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：MIP；第2空：MPR；第3空：SSD；第4空：VR。",
        "CT 三维显示技术包括最大密度投影（MIP）、多平面重组（MPR）、表面遮盖显示（SSD）和容积再现（VR）等。原书第01章填空题第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-fill008",
    order: 22,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：CT增强检查依对比剂注入后的延迟时间和扫描次数，分为____、____、____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：普通增强检查；第2空：多期增强检查；第3空：CTA；第4空：CT灌注成像。",
        "CT 增强检查按延迟时间和扫描次数分为普通增强、多期增强、CTA 和 CT 灌注成像等。原书第01章填空题第 8 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-fill009",
    order: 23,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：CT检查的X线辐射剂量____传统X线检查。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：显著高于。",
        "CT 检查辐射剂量显著高于传统X线检查，是传统X线检查的数十倍甚至上百倍。原书第01章填空题第 9 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-fill010",
    order: 24,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：超声成像是利用____和____进行的成像技术。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：超声波的物理特性；第2空：人体组织声学参数。",
        "超声成像利用超声波的物理特性与人体组织声学参数差异进行成像。原书第01章填空题第 10 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-fill011",
    order: 25,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：在M型声像图上，纵坐标代表____，横坐标代表____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：回声深度（距离）；第2空：时间。",
        "M 型超声纵坐标代表回声深度（距离），横坐标代表时间。原书第01章填空题第 11 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-fill012",
    order: 26,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：在CDFI声像图上，朝向探头的血流以____表示，背向探头者以____表示，湍流方向复杂、多变，呈____或____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：红色；第2空：蓝色；第3空：五彩镶嵌；第4空：绿色。",
        "CDFI 中朝向探头的血流以红色显示，背向探头者以蓝色显示，湍流呈五彩镶嵌或绿色。原书第01章填空题第 12 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），24 道（A1 型原书第 1–24 题） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1001",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与X线成像有关的X线基本性质是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "X线的穿透性、荧光效应和生物效应",
      "X线的穿透性、荧光效应和感光效应",
      "X线的荧光效应、感光效应和生物效应",
      "X线的穿透性、感光效应和生物效应",
      "以上各项均是正确的",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "X线的穿透性、荧光效应和感光效应",
        "与X线成像有关的X线基本性质为穿透性、荧光效应和感光效应。原书第01章 A1 型题第 1 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1002",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与X线成像有关的人体组织结构存在固有的差异，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "含水量和含气量差异",
      "厚度和含水量差异",
      "密度和厚度差异",
      "密度和含水量差异",
      "厚度和含气量差异",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "密度和厚度差异",
        "人体组织结构固有的密度和厚度差异是X线成像的基础之一。原书第01章 A1 型题第 2 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1003",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于X线片上组织结构密度与影像表现的关系，下列哪项是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "高密度组织结构在X线片上呈白影",
      "低密度组织结构在X线片上呈黑影",
      "组织结构的厚度越小，X线片上的影像越黑",
      "组织结构的厚度越大，X线片上的影像越黑",
      "中等密度组织结构在X线片上呈灰影",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "组织结构的厚度越大，X线片上的影像越黑",
        "组织厚度越大，透过X线越少，影像应越白而非越黑，故该项错误。原书第01章 A1 型题第 3 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1004",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于X线成像的优点，下列哪项是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "图像的密度分辨力高",
      "检查的射线辐射量相对较低",
      "图像的空间分辨力高",
      "检查费用较低廉",
      "能够整体显示大范围的组织结构",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "图像的密度分辨力高",
        "传统X线成像的密度分辨力较低，密度差别小的组织不能形成灰度对比，故该项错误。原书第01章 A1 型题第 4 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1005",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于X线成像的局限性，下列哪项是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "组织结构影像相互重叠",
      "图像的空间分辨力低",
      "摄片参数要求严格",
      "患者接受一定的辐射量",
      "难以同时显示不同密度的组织结构",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "图像的空间分辨力低",
        "传统X线成像的空间分辨力较高而非较低，故该项错误。原书第01章 A1 型题第 5 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1006",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于对数字化X线成像的认识，下列哪项是正确的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "CR成像中，透过人体的X线信息载体是FPD",
      "数字化X线成像中，需将透过人体的X线信息进行像素化和数字化",
      "DR设备能与原有X线设备兼容",
      "CR设备不能与原有X线设备兼容",
      "DR成像中，透过人体的X线信息载体是IP",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "数字化X线成像中，需将透过人体的X线信息进行像素化和数字化",
        "CR、DR 成像均需将透过人体的X线信息像素化和数字化。原书第01章 A1 型题第 6 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1007",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于数字化X线成像的优点，错误的认识是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "提高了图像的空间分辨力",
      "便于图像资料存储",
      "降低了X线辐射量",
      "可通过PACS进行图像传输",
      "提高了图像质量",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "提高了图像的空间分辨力",
        "数字化X线成像可降低辐射量、提高图像质量并便于存储传输，但并不直接提高图像空间分辨力。原书第01章 A1 型题第 7 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1008",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于DSA的认识，以下哪项是正确的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "DSA检查可消除骨与软组织影像，仅留有血管影像",
      "目前DSA设备多采用X线影像增强器和高分辨力的摄像管",
      "DSA仅用于心血管疾病诊断",
      "DSA设备不属于数字化X线成像设备",
      "DSA检查常用的减影方法是能量减影法",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "DSA检查可消除骨与软组织影像，仅留有血管影像",
        "DSA（数字减影血管造影）通过减影消除骨与软组织影像，仅保留血管影像。原书第01章 A1 型题第 8 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1009",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于X线对比剂，以下哪项认识是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "医用硫酸钡仅用于食管和胃肠道造影检查",
      "水溶性有机碘对比剂可引起不良反应，其中非离子型对比剂易发生不良反应",
      "肾功能严重受损、甲状腺功能亢进、过敏性体质者，应禁用或慎用水溶性有机碘对比剂",
      "X线检查常用对比剂为医用硫酸钡和水溶性有机碘对比剂",
      "水溶性有机碘对比剂常用于血管造影、血管内介入治疗、尿路造影等",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "水溶性有机碘对比剂可引起不良反应，其中非离子型对比剂易发生不良反应",
        "非离子型碘对比剂不良反应发生率低于离子型，故该项错误。原书第01章 A1 型题第 9 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1010",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关X线防护问题，以下哪项认识是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "早孕妇女属于X线检查禁忌证",
      "X线具有穿透性，故可导致放射性损伤",
      "X线辐射防护的三项基本原则为：屏蔽防护、距离防护和时间防护",
      "短期内应尽量减少X线检查的照射次数",
      "含铅防护服属于屏蔽防护",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "X线具有穿透性，故可导致放射性损伤",
        "X线穿透性本身并不等同于导致放射性损伤，防护在于控制照射剂量与时间，故该项错误。原书第01章 A1 型题第 10 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1011",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关X线图像特点，下列哪项认识是不正确的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "影像密度不能反映组织结构的固有密度",
      "X线图像上的黑白灰度反映的是组织结构的密度",
      "X线图像上的影像叠加可使一些病变影像显示不清",
      "影像密度与组织结构固有密度属于不同的概念",
      "X线图像是组织结构影像的叠加图像",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "影像密度不能反映组织结构的固有密度",
        "影像密度在一定程度上反映组织结构固有密度，只是二者属不同概念，故该项错误。原书第01章 A1 型题第 11 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1012",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于识别X线图像的要点，以下哪种认识是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "X线图像上，骨皮质呈高密度白影",
      "X线图像上，脂肪组织为高密度白影",
      "X线图像上，肌肉呈中等密度灰影",
      "X线图像上，组织结构影像相互重叠",
      "X线图像上，气体呈极低密度黑影",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "X线图像上，脂肪组织为高密度白影",
        "脂肪组织密度较低，在X线片上呈较低密度灰影而非高密度白影，故该项错误。原书第01章 A1 型题第 12 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1013",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于CT成像的基本原理，以下认识正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "广义上，CT成像也属于数字化X线成像",
      "首先，通过X线束环绕人体某一解剖断面进行扫描，获得透过X线信息，并转化为数字信息",
      "依吸收系数值的高至低，赋予像素不同辉度的光点",
      "基于各个体素辉度不同，通过模/数转换，即可重建为CT图像",
      "取得的数字信息，输入计算机处理，通过不同算法，获得该断面各个像素的X线吸收系数",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "广义上，CT成像也属于数字化X线成像",
        "CT 成像过程本质上也是X线信息的数字化处理，故广义上属于数字化X线成像。原书第01章 A1 型题第 13 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1014",
    order: 40,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "对于CT成像主要优势的认识，下列哪项是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "CT成像的密度分辨力高，因而密度差别小的组织结构或病灶，也能清楚显示",
      "CT成像的空间分辨力高，要显著高于常规X线成像",
      "可行多种图像后处理，拓展了CT的应用领域",
      "能够应用量化指标即CT值，对组织结构和病变进行密度定量分析",
      "CT图像上，组织结构的影像无重叠，因而明显提高了病变的检出率",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT成像的空间分辨力高，要显著高于常规X线成像",
        "CT 的优势在于密度分辨力高，其空间分辨力并不显著高于常规X线成像，故该项错误。原书第01章 A1 型题第 14 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1015",
    order: 41,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于CT成像的局限性，以下哪项认识是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "CT成像通常不能整体显示器官结构和病变",
      "CT成像受到部分容积效应影响，从而干扰了小病灶的显示",
      "CT成像常常不能区分密度差别小的组织结构与病变",
      "CT检查具有较高的X线辐射剂量，是传统X线检查的数十倍，甚至上百倍",
      "一次CT检查，常常获取上百幅横断层图像，不利于快速全面、仔细观察",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT成像常常不能区分密度差别小的组织结构与病变",
        "CT 的密度分辨力高，恰恰能够区分密度差别小的组织结构与病变，故该项错误。原书第01章 A1 型题第 15 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1016",
    order: 42,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "CT增强检查有不同方法，各有其临床应用范围，以下哪项认识是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "所有平扫检查发现的病变，均应行多期增强检查",
      "多期增强检查主要用于腹、盆部疾病的诊断",
      "CTA用于血管疾病的诊断，如冠状动脉狭窄",
      "普通增强检查常用于颅脑疾病的诊断",
      "CT灌注成像能够反映毛细血管水平的血流灌注状况，属于功能成像，可用于脑梗死诊断",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "所有平扫检查发现的病变，均应行多期增强检查",
        "增强检查方法的选择需依病变部位和临床需要而定，并非所有平扫发现的病变均需多期增强，故该项错误。原书第01章 A1 型题第 16 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1017",
    order: 43,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于CT检查辐射剂量的认识，以下哪项是正确的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "CT检查不具有辐射",
      "CT检查辐射剂量略高于传统X线检查",
      "CT检查辐射剂量显著高于传统X线检查",
      "CT检查辐射剂量低于传统X线检查",
      "CT检查辐射剂量类似传统X线检查",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT检查辐射剂量显著高于传统X线检查",
        "CT 检查辐射剂量显著高于传统X线检查，可达其数十倍甚至上百倍。原书第01章 A1 型题第 17 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1018",
    order: 44,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于CT图像的特点，以下哪项认识是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "CT图像上的黑白灰度反映的是组织结构的含水量",
      "CT图像上黑白灰度对比受窗设置的影响",
      "CT图像可由于不同的后处理技术，改变了常规横断层的显示模式",
      "CT图像常规为横断层图像，组织结构影像无重叠",
      "CT图像上，增强检查可以改变组织结构与病灶的黑白灰度对比",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT图像上的黑白灰度反映的是组织结构的含水量",
        "CT 图像黑白灰度反映的是组织结构的密度（X线吸收系数）而非含水量，故该项错误。原书第01章 A1 型题第 18 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1019",
    order: 45,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于识别CT图像的认识，以下哪项是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "CT图像常规显示的是多幅横断层图像，组织结构影像清晰，无重叠",
      "增强CT检查图像上，血管结构明显强化，呈高密度白影",
      "CTVE图像表现类似内镜检查的图像",
      "CT图像上，骨皮质呈低密度黑影，脂肪组织呈较高密度灰白影",
      "经CT后处理的CPR图像，能够整体显示弯曲走行的结构，如冠状动脉",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT图像上，骨皮质呈低密度黑影，脂肪组织呈较高密度灰白影",
        "CT 图像上骨皮质密度最高呈白影，脂肪组织呈低密度黑影，该项描述相反，故错误。原书第01章 A1 型题第 19 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1020",
    order: 46,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于CT检查的临床应用，以下错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "骨骼肌肉疾病",
      "中枢神经系统疾病",
      "关节软骨病变",
      "胸部疾病",
      "腹盆部疾病",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "关节软骨病变",
        "CT 对关节软骨显示不佳，关节软骨病变首选MRI，故该项错误。原书第01章 A1 型题第 20 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1021",
    order: 47,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "当胸部X线片发现肺内孤立性结节时，需进一步选用的影像检查是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "CT平扫检查",
      "超声检查",
      "X线造影检查",
      "MRI检查",
      "DSA检查",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT平扫检查",
        "肺内孤立性结节发现后需进一步行CT平扫观察细节，为综合应用中的合理选择。原书第01章 A1 型题第 21 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1022",
    order: 48,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "CT成像的主要优势不包括以下哪项",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "空间分辨力高",
      "密度分辨力高",
      "组织结构影像无重叠",
      "可行多种图像后处理",
      "可应用CT值进行量化分析",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "空间分辨力高",
        "CT 的主要优势是密度分辨力高，空间分辨力并非其主要优势，故不包括空间分辨力高。原书第01章 A1 型题第 22 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1023",
    order: 49,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪种病变平扫CT检查通常不能明确诊断",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "急性脑梗死",
      "游离气腹",
      "肝囊肿",
      "支气管扩张",
      "阳性肾结石",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "急性脑梗死",
        "急性脑梗死早期（24小时内）平扫CT常无明显异常，需结合DWI或随访复查。原书第01章 A1 型题第 23 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-a1024",
    order: 50,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于CT图像特点，不包括以下哪项",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "常规为多幅横断层图像，组织结构相互重叠",
      "图像上的黑白灰度反映的是组织结构的密度",
      "图像后处理技术改变了常规横断层显示模式",
      "增强检查改变了组织结构的对比",
      "图像上黑白灰度对比受窗技术影响",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常规为多幅横断层图像，组织结构相互重叠",
        "CT 为断层图像，组织结构影像无重叠，故该项不属于CT图像特点。原书第01章 A1 型题第 24 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），9 道（原书第 1–9 题） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch01-intro-short001",
    order: 51,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述X线成像的基本原理。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "X线之所以能够使人体组织结构成像，基于以下两方面原因的相互作用：①X线的基本性质，即X线的穿透性、可吸收性、荧光效应和感光效应；②人体各部位的组织结构之间存在着固有的密度和厚度差异。",
        "X线成像的基本原理可概括为X线基本性质与人体组织固有密度、厚度差异两者的结合。原书第01章简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-short002",
    order: 52,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述传统X线检查的优势和限度。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "传统X线检查的优势：①图像的空间分辨力较高；②能够整体显示较大范围的组织结构；③X线辐射剂量相对较低；④检查费用也较为低廉。限度：①摄片条件要求严格；②图像的密度分辨力较低，密度差别小的两种组织不能形成灰度对比；③组织结构影像相互重叠，对病变显示有一定影响；④图像灰度无法调节；⑤X线胶片的利用和管理也有诸多不便。",
        "传统X线检查优势在于空间分辨力较高、整体显示、辐射较低和费用低廉，限度主要在密度分辨力低、影像重叠、灰度不可调等。原书第01章简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-short003",
    order: 53,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述数字化X线成像的优点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "数字化X线成像的优点是：①摄片条件的宽容度大，可最大限度降低X线辐射剂量；②提高了图像质量，可使不同密度的组织结构同时达到清晰显示的效果；③具有测量、边缘锐化、减影等多种图像处理功能；④图像的数字化信息既可经转换打印成照片或在监视屏上视读，也可存储在光盘、硬盘中，还可通过PACS进行传输。",
        "数字化X线成像的四大优点：宽容度大、辐射低；图像质量高；多种图像处理功能；数字化信息便于存储传输。原书第01章简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-short004",
    order: 54,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述X线对比剂类型、应用和引入方法。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "X线对比剂类型及应用：①医用硫酸钡，仅用于食管和胃肠道造影检查；②水溶性有机碘对比剂，又分为离子型和非离子型，主要用于血管造影、血管内介入治疗、尿路造影、子宫输卵管造影、窦道和瘘管及T型管造影等。引入途径：①直接引入法：口服（如上消化道钡餐检查）、灌注（如钡剂灌肠、逆行尿路造影、子宫输卵管造影等）、穿刺（如血管造影、经皮经肝胆管造影等）；②间接引入法：经静脉注入行排泄性尿路造影。",
        "X线对比剂主要包括医用硫酸钡与水溶性有机碘对比剂两大类；引入途径分为直接引入（口服、灌注、穿刺）与间接引入（静脉注入）。原书第01章简答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-short005",
    order: 55,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述X线检查时辐射防护的三项基本原则。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "辐射防护的三项基本原则：①屏蔽防护，用高密度物质，如含铅的防护服、眼罩、脖套和三角裤等，作为屏蔽物，遮挡敏感部位和器官；②距离防护，利用X线量与距离的平方成反比的原理，适当扩大检查室的空间，减少散射线的辐射；③时间防护，每次检查的照射次数不宜过多，并尽量避免重复检查。",
        "辐射防护三项基本原则为屏蔽防护、距离防护和时间防护，分别从遮挡、距离和照射时间入手降低受照剂量。原书第01章简答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-short006",
    order: 56,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述CT成像的基本原理。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 成像的基本原理：CT用X线束对人体检查部位一定厚度的层面进行扫描，由探测器接收该层面上各个不同方向的人体组织对X线的衰减值，经模/数转换输入计算机，通过计算机处理后得到扫描断面的组织衰减系数的数字矩阵，再将矩阵内的数值通过数/模转换，用黑白不同的灰度等级在荧光屏上显示出来，即构成CT图像。根据检查部位的组织成分和密度差异，CT图像重建要使用合适的数学演算方式，常用的有标准演算法、软组织演算法和骨演算法等，图像演算方式选择不当会降低图像的分辨率。",
        "CT 成像原理可概括为：X线束扫描→探测器接收衰减值→模/数转换→计算机重建数字矩阵→数/模转换→灰度显示；重建需选择合适的数学演算方式。原书第01章简答题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-short007",
    order: 57,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "CT成像的主要优势有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 成像的主要优势：密度分辨力高，可行密度量化分析，组织结构影像无重叠，可行多种图像后处理。",
        "CT 成像四大优势：密度分辨力高、密度可量化分析、影像无重叠、多种后处理。原书第01章简答题第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-short008",
    order: 58,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "CT图像后处理包括哪些技术？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 图像后处理技术涵盖各种二维显示技术、三维显示技术及其他多种分析、处理和显示技术。其中二维显示技术包括电影显示、多平面重组和曲面重组；三维显示技术有最大密度投影、最小密度投影、表面遮盖显示、容积再现技术、CT仿真内镜和组织透明投影；其他分析、处理和显示技术包括各种分离技术、肺结节分析技术、骨密度分析技术、心脏（包括冠状动脉、心肌灌注）分析技术、CT灌注分析和显示技术以及各种叠加显示技术等。",
        "CT 后处理技术分三类：二维显示（电影、MPR、CPR）、三维显示（MIP、MinIP、SSD、VR、CTVE、组织透明投影）及其他分析处理显示技术。原书第01章简答题第 8 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-short009",
    order: 59,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "CT图像具有哪些特点？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 图像的主要特点有：①CT图像是数字化模拟灰度图像；②CT图像具有较高的密度分辨力；③CT图像的密度能够进行量化评估；④CT图像为断层图像。",
        "CT 图像四大特点：数字化模拟灰度图像、密度分辨力高、密度可量化评估、断层图像。原书第01章简答题第 9 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，4 组 / 12 成员（原书第 68–79 题） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch01-intro-b001",
    order: 60,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "碘对比剂",
      "氧气",
      "二氧化碳",
      "硫酸钡",
      "碘油",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch01-intro-b001m1",
        order: 60,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "CT增强检查常用的对比剂是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "碘对比剂",
            "CT 增强检查常用水溶性有机碘对比剂。原书第01章 B 型题第 68 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch01-intro-b001m2",
        order: 61,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "CT关节造影常用的对比剂是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "二氧化碳",
            "CT 关节造影可在关节内注入气体（如空气、二氧化碳）或不透X线的对比剂后进行扫描。原书第01章 B 型题第 69 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-b002",
    order: 62,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "薄层扫描",
      "高分辨率扫描",
      "靶扫描",
      "图像堆积扫描",
      "重叠扫描",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch01-intro-b002m1",
        order: 62,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "对孤立性肺结节扫描的方法是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "高分辨率扫描",
            "对孤立性肺结节常采用高分辨率扫描以显示结节细节。原书第01章 B 型题第 70 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch01-intro-b002m2",
        order: 63,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "对感兴趣局部放大再行扫描的方法是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "靶扫描",
            "靶扫描是对感兴趣局部放大后再行扫描的方法。原书第01章 B 型题第 71 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-b003",
    order: 64,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "Doppler效应",
      "机械效应",
      "反射",
      "折射",
      "散射",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch01-intro-b003m1",
        order: 64,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "反射回声的频率随反射体的运动而发生改变的现象称",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "Doppler效应",
            "反射回声频率随反射体运动而改变的现象即多普勒（Doppler）效应。原书第01章 B 型题第 72 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch01-intro-b003m2",
        order: 65,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "超声束从一个介质穿透到另一个传播速度不同的介质，声束方向将发生变化，该现象称为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "折射",
            "超声束进入声速不同的介质时传播方向改变的现象称为折射。原书第01章 B 型题第 73 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch01-intro-b003m3",
        order: 66,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "超声波入射到比自身波长大的大界面时，入射声波的较大部分能量被该界面阻挡而返回，这种现象称之",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "反射",
            "超声入射到大于自身波长的大界面时较大部分能量被阻挡而返回，称为反射。原书第01章 B 型题第 74 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch01-intro-b004",
    order: 67,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "T1WI高信号，T2WI低信号",
      "T1WI低信号，T2WI高信号",
      "T1WI高信号，T2WI高信号",
      "T1WI中低信号，T2WI中高信号",
      "T1WI低信号，T2WI低信号",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch01-intro-b004m1",
        order: 67,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "脂肪的MRI信号特点",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "T1WI高信号，T2WI高信号",
            "脂肪组织 T1WI 呈高信号、T2WI 亦呈高信号（T1WI 更明显）。原书第01章 B 型题第 75 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch01-intro-b004m2",
        order: 68,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "脑脊液的MRI信号特点",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "T1WI低信号，T2WI高信号",
            "脑脊液含水丰富，T1WI 呈低信号、T2WI 呈高信号。原书第01章 B 型题第 76 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch01-intro-b004m3",
        order: 69,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "骨皮质的MRI信号特点",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "T1WI低信号，T2WI低信号",
            "骨皮质含氢质子少，T1WI、T2WI 均呈低信号。原书第01章 B 型题第 77 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch01-intro-b004m4",
        order: 70,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "亚急性血肿的MRI信号特点为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "T1WI高信号，T2WI高信号",
            "亚急性晚期血肿 T1WI 及 T2WI 均呈高信号（正铁血红蛋白）。原书第01章 B 型题第 78 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch01-intro-b004m5",
        order: 71,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "脑灰质的MRI信号特点",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "T1WI中低信号，T2WI中高信号",
            "脑灰质 T1WI 呈中低信号、T2WI 呈中高信号，介于白质与脑脊液之间。原书第01章 B 型题第 79 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...fillItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
