import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学影像学学习指导与习题集 第3版 — 第02章 中枢神经系统 题库提取（等比取样）
 * 来源：《医学影像学学习指导与习题集》第3版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：7 题
 * - 填空题（fill）：8 题
 * - 选择题（a1-single）：27 题（A1 型 25、A2 型病例题 2）
 * - 简答题（short-answer）：7 题
 * - B1 配伍题：3 组 / 6 成员
 * - 独立记分题合计：55 题（须等于本文件预算 55）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书含名词解释、填空题、选择题（A1/A2/B1）、简答题；本文件按 55 道预算在
 *   原书顺序内取材：名词解释取第 1–7 题、填空题取第 1–8 题、A1 型取第 1–25 题、A2 型取
 *   第 64–65 题、B 型取第 69–74 题（组 69~70、71~72、73~74）、简答题取第 1–7 题；未纳入的
 *   题因预算所限。正确项对齐章末参考答案键号（A1 1–63、A2 64–68、B1 69–87 全书连续编号，
 *   参考答案区键号即对应题号），选项与共用备选答案已随机重排并同步 correctChoiceIndex。
 *   OCR 错字已按医学影像学医学语义恢复（如 祝觉→视觉、TWI/IWI/T2W1/TWI→T1WI/T2WI、
 *   菱缩→萎缩、多内→髓内、力→为、丁解→了解 等），数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "radiology-bank-ch02-cns";
const locatorBase =
  "《医学影像学学习指导与习题集》第3版 第02章 中枢神经系统 习题（核对PDF 第22–37页）";
const promptNote =
  "题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），7 道（原书第 1–7 题） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch02-cns-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：脑血管造影",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑血管造影：将有机碘剂引入脑血管中，使脑血管显影的方法，分颈动脉造影及椎动脉造影。用于诊断脑动脉瘤、血管发育异常和了解肿瘤的供血等。",
        "脑血管造影属有创检查，对血管性病变的诊断价值高。原书第02章名词解释第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：腔隙性脑梗死",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腔隙性脑梗死：是由深部髓质小动脉闭塞所致的基底节、丘脑、小脑和脑干的梗死灶，直径在 10~15mm 以内，称为腔隙性脑梗死。",
        "腔隙性脑梗死病灶小而多发，位于脑深部穿支动脉供血区。原书第02章名词解释第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：模糊效应",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "模糊效应：脑梗死发病 2~3 周左右时，梗死区因脑水肿消失和吞噬细胞的浸润，密度相对增高而呈等密度，称之为“模糊效应”。",
        "模糊效应期梗死灶在 CT 上可呈等密度，易漏诊，需结合增强或 MRI 判断。原书第02章名词解释第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：垂体微腺瘤",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "垂体微腺瘤：局限于蝶鞍内、直径小于 1cm 的垂体腺瘤。",
        "垂体微腺瘤多伴泌乳素等激素水平增高，MRI 动态增强对检出有帮助。原书第02章名词解释第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：脑脓肿",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑脓肿：是化脓性细菌进入脑组织引起的炎性改变，进一步形成脓肿。分为急性炎症期、化脓坏死期和脓肿形成期。",
        "脑脓肿形成期增强呈环形强化，DWI 脓腔呈明显高信号，可与其他环状强化病变鉴别。原书第02章名词解释第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：脑膜尾征",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑膜尾征：脑膜瘤多以广基底与硬膜相连、边界清楚，MRI 增强后肿瘤均一性强化，邻近脑膜亦强化似尾，称为“脑膜尾征”，具有一定特征。",
        "脑膜尾征是脑膜瘤的常见增强表现，但并非其独有，少数其他脑膜相关病变也可出现。原书第02章名词解释第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：多发性硬化",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多发性硬化：是中枢神经系统以髓鞘脱失为主要病理改变的疾病，病因不明，以脑室周围髓质和半卵圆中心多发性硬化斑为主。多表现为多灶性脑脊髓损害症状，病程缓解与发作交替且进行性加重。",
        "多发性硬化具有时间与空间多发性，病灶常与侧脑室壁垂直排列。原书第02章名词解释第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），8 道（原书第 1–8 题） */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch02-cns-fill001",
    order: 8,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：脑梗死 MRI 特征表现为 T1WI 呈____信号，T2WI 呈____信号。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "低；高",
        "脑梗死灶因组织含水量增多，T1WI 呈低信号、T2WI 呈高信号，急性期 DWI 呈明显高信号。原书第02章填空题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-fill002",
    order: 9,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：硬膜下血肿血液居____之间，血肿范围较____，一般呈____形。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "硬膜与蛛网膜；广泛；新月",
        "硬膜下血肿沿脑表面广泛分布，可跨越颅缝，CT 呈新月形高密度影。原书第02章填空题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-fill003",
    order: 10,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：硬膜外血肿血液居____间隙，血肿范围____，一般呈____形。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "硬膜外；较局限；梭",
        "硬膜与颅骨内板附着紧密，硬膜外血肿较局限、一般不跨越颅缝，CT 呈梭形高密度影。原书第02章填空题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-fill004",
    order: 11,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：亚急性脑内血肿 MRI 特征性表现为 T1WI 呈____信号，T2WI 呈____信号。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "高；高",
        "亚急性期血肿内正铁血红蛋白形成，T1WI 与 T2WI 均呈高信号。原书第02章填空题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-fill005",
    order: 12,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：脑动静脉畸形是由____、____和____所构成。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "供血动脉；畸形血管团；引流静脉",
        "脑动静脉畸形由供血动脉、畸形血管团与引流静脉构成，血管造影可显示其全貌。原书第02章填空题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-fill006",
    order: 13,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：CT 增强扫描呈“环形征”的脑内病变可能为____、____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑脓肿；脑胶质瘤；脑转移瘤",
        "脑脓肿、脑胶质瘤与脑转移瘤增强均可呈环形强化，需结合 DWI 及临床鉴别。原书第02章填空题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-fill007",
    order: 14,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：脑膜瘤的好发部位为____、____及____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "矢状窦旁；大脑凸面；蝶骨嵴",
        "脑膜瘤好发于矢状窦旁、大脑凸面及蝶骨嵴等硬膜返折及静脉窦附近。原书第02章填空题第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-fill008",
    order: 15,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "填空题：脑梗死分____、____和____三种。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "缺血性脑梗死；出血性脑梗死；腔隙性脑梗死",
        "脑梗死按病理与临床分为缺血性脑梗死、出血性脑梗死和腔隙性脑梗死三种类型。原书第02章填空题第 8 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），27 道（A1 型第 1–25 题、A2 型第 64–65 题） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1001",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪一项不属于基底节结构",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "杏仁核",
      "丘脑",
      "尾状核",
      "屏状核",
      "豆状核",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "丘脑",
        "基底节包括尾状核、豆状核（壳核与苍白球）、屏状核和杏仁核，丘脑属于间脑。原书第02章 A1 型题第 1 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1002",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胶质瘤的 CT 表现为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "可呈囊样低密度",
      "可为不规则低密度",
      "以上均正确",
      "可不强化",
      "可强化",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "以上均正确",
        "胶质瘤 CT 表现多样，可为不规则低密度、囊样低密度，增强可强化亦可不强化。原书第02章 A1 型题第 2 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1003",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不属于脑室系统的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "左右侧脑室",
      "第四脑室",
      "中脑脚间窝",
      "第三脑室",
      "中脑导水管",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中脑脚间窝",
        "脑室系统包括左右侧脑室、第三脑室、第四脑室及中脑导水管，中脑脚间窝属于蛛网膜下腔结构。原书第02章 A1 型题第 3 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1004",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "脑梗死是按什么分布的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脑实质",
      "脑血管分布区",
      "脑叶",
      "脑白质",
      "脑沟",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑血管分布区",
        "缺血性脑梗死按受累血管供血分布区分布，如大脑中动脉供血区等。原书第02章 A1 型题第 4 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1005",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "高血压出血常见的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "尾状核头出血",
      "壳核出血",
      "内囊出血",
      "基底节出血",
      "丘脑出血",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "基底节出血",
        "高血压性脑出血多见于基底节区（壳核常见），其次为丘脑、脑干及小脑。原书第02章 A1 型题第 5 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1006",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "颅咽管瘤的钙化呈",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "块状",
      "爆米花样",
      "散在钙化",
      "蛋壳样",
      "毛线团样",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "蛋壳样",
        "颅咽管瘤钙化常见，呈斑块样或蛋壳样钙化为其特征之一。原书第02章 A1 型题第 6 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1007",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "颅内最常见的肿瘤是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "髓母细胞瘤",
      "转移瘤",
      "星形细胞肿瘤",
      "脑膜瘤",
      "生殖细胞瘤",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "星形细胞肿瘤",
        "颅内最常见的原发性肿瘤是星形细胞肿瘤。原书第02章 A1 型题第 7 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1008",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "梗死后往往可以见到“模糊效应”，常出现在",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "第1周",
      "第3~4周",
      "第4周",
      "第2~3周",
      "第2周",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第2~3周",
        "脑梗死发病 2~3 周左右，梗死区密度相对增高而呈等密度，即“模糊效应”。原书第02章 A1 型题第 8 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1009",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "蛛网膜下腔出血的主要 CT 表现是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "基底节区见高密度影",
      "外侧裂池见高密度影",
      "三脑室呈高密度影",
      "枕叶见高密度影",
      "侧脑室呈高密度影",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "外侧裂池见高密度影",
        "蛛网膜下腔出血 CT 表现为脑沟、脑池（如外侧裂池、鞍上池）内高密度影。原书第02章 A1 型题第 9 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1010",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "脑肿瘤的间接征象是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "大小",
      "密度",
      "脑水肿",
      "数量",
      "形态",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脑水肿",
        "脑肿瘤的直接征象包括密度、大小、形态、数量等，脑水肿及占位效应属间接征象。原书第02章 A1 型题第 10 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1011",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "星形细胞瘤分四级，属 1 级星形细胞瘤的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "团状增强",
      "花冠状增强",
      "有占位效应",
      "瘤周水肿明显",
      "常无增强",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常无增强",
        "1 级星形细胞瘤分化良好，增强检查多数不强化或仅轻度强化。原书第02章 A1 型题第 11 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1012",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不发生脑膜瘤的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "大脑凸面",
      "幕切迹",
      "侧脑室外侧白质区",
      "桥小脑角区",
      "大脑镰旁",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "侧脑室外侧白质区",
        "脑膜瘤起源于蛛网膜帽状细胞，多发生于脑外硬膜相关部位，脑白质内不发生。原书第02章 A1 型题第 12 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1013",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于听神经瘤描述错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "常有强化",
      "内耳道口扩大",
      "脑外肿瘤",
      "可坏死、囊变",
      "一般不影响第四脑室",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "一般不影响第四脑室",
        "听神经瘤位于桥小脑角池，肿瘤较大时可压迫脑干及小脑，使第四脑室受压变窄、移位，并可伴幕上脑积水，故“不影响第四脑室”错误。原书第02章 A1 型题第 13 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1014",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "垂体瘤的 CT 表现不正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "蝶鞍扩大",
      "垂体柄移位",
      "瘤周水肿",
      "鞍底下陷",
      "肿瘤有强化",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "瘤周水肿",
        "垂体瘤位于鞍区，一般无瘤周水肿表现；蝶鞍扩大、鞍底下陷、垂体柄移位及强化为其常见表现。原书第02章 A1 型题第 14 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1015",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于颅咽管瘤 CT 表现错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "常见瘤周水肿",
      "圆形或椭圆形低密度影",
      "位于脑外",
      "斑块样或蛋壳样钙化",
      "可造成脑积水",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常见瘤周水肿",
        "颅咽管瘤为鞍上区脑外肿瘤，多为囊性伴钙化，可致脑积水，但瘤周水肿少见。原书第02章 A1 型题第 15 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1016",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与转移瘤常见 CT 表现不符的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "多发散在的环形等密度影",
      "无强化",
      "灶旁水肿明显",
      "位置较表浅",
      "多发的结节影",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "无强化",
        "脑转移瘤增强后多呈结节状或环形强化，“无强化”与其常见表现不符。原书第02章 A1 型题第 16 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1017",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于“脑梗死”，下列观点哪项不对",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "发病 24 小时内，MRI 可有阳性发现",
      "发病 24 小时内 CT 可正常",
      "对小脑、脑干小病变，MRI 优于 CT",
      "发病 24 小时强化最明显",
      "发病 24 小时后，出现边缘模糊低密度影",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "发病 24 小时强化最明显",
        "脑梗死增强多见于梗死后 1~3 周（侧支循环建立期），并非发病 24 小时强化最明显。原书第02章 A1 型题第 17 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1018",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列等密度硬膜下血肿征象中错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "单侧脑沟、脑裂变窄，甚至消失",
      "白质挤压征",
      "额板下出现梭形影",
      "脑室受压变形，中线结构移位",
      "增强扫描血肿无增强",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "额板下出现梭形影",
        "等密度硬膜下血肿多呈新月形占位表现（脑沟变窄、中线移位、白质挤压征等），梭形影为硬膜外血肿的特征，且增强后血肿包膜可有强化。原书第02章 A1 型题第 18 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1019",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不是硬膜外血肿特点的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "内缘光滑锐利",
      "可越过颅缝",
      "常有骨折",
      "呈梭形",
      "中线结构移位较轻",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "可越过颅缝",
        "硬膜外血肿因硬膜与颅骨内板附着紧密而较局限，一般不跨越颅缝；硬膜下血肿才可跨越颅缝。原书第02章 A1 型题第 19 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1020",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于“脑出血”MRI 表现，下列描述哪项不对",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "亚急性晚期血肿，T1WI 和 T2WI 均表现为高信号",
      "急性期血肿，T1WI 呈等信号，T2WI 呈稍低信号",
      "亚急性及慢性期血肿，MRI 显示不如 CT 清楚",
      "血肿囊变期，T1WI 呈低信号，T2WI 呈高信号，周边可见含铁血黄素沉积所致低信号环",
      "急性期血肿，MRI 显示不如 CT 清楚",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "亚急性及慢性期血肿，MRI 显示不如 CT 清楚",
        "急性期血肿 MRI 显示不如 CT 清楚，但亚急性及慢性期血肿 MRI 对信号演变显示优于 CT。原书第02章 A1 型题第 20 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1021",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，男性，58 岁，近 6 小时突感头痛、头晕，伴左侧肢体麻木。既往无高血压病史及肿瘤病史。以下哪种检查方法较好",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "CT",
      "脑血管造影",
      "头颅X线正侧位片",
      "MR",
      "其他",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "MR",
        "急性期脑梗死（尤其发病 6 小时内）MRI（DWI）可较早显示病灶，优于 CT。原书第02章 A1 型题第 21 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1022",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，女性，32 岁，既往月经正常，近一年月经量少，有溢乳现象，临床化验检查示泌乳素明显增高。采用何种检查方法最好",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "X线",
      "DSA 检查",
      "CT 检查",
      "其他",
      "MRI 检查",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "MRI 检查",
        "泌乳素明显增高提示垂体微腺瘤可能，MRI 是检出垂体微腺瘤的最佳影像学方法。原书第02章 A1 型题第 22 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1023",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "头颅 CT 示左颞叶和额叶内有一轮廓模糊的片状占位性病变，呈低密度，不均匀，周围可见明显脑水肿，中线结构右移，增强扫描呈不规则花环状强化。最可能的诊断为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脑膜瘤",
      "脑炎",
      "脑梗死",
      "脑脓肿",
      "胶质母细胞瘤",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胶质母细胞瘤",
        "片状低密度占位伴明显瘤周水肿、中线移位，增强呈不规则花环状强化，符合胶质母细胞瘤表现。原书第02章 A1 型题第 23 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1024",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "除了脑外伤以外，中青年致残的最常见原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脑炎",
      "脑肿瘤",
      "脑梗死",
      "先天性脑发育异常",
      "多发性硬化",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多发性硬化",
        "多发性硬化好发于中青年，反复发作可致残疾，是除脑外伤外中青年致残的常见原因。原书第02章 A1 型题第 24 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1025",
    order: 40,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于“多发性硬化”，下列观点哪项不对",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脑白质内多发病灶",
      "脊髓病灶常大于3个椎体节段",
      "常反复发作",
      "可累及脑灰质",
      "好发于中青年女性",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "脊髓病灶常大于3个椎体节段",
        "多发性硬化脊髓病灶多局限在 1~3 个椎体节段，一般不超过 3 个椎体节段；脊髓长节段受累多见于视神经脊髓炎，故“脊髓病灶常大于 3 个椎体节段”不正确。原书第02章 A1 型题第 25 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1026",
    order: 41,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，女性，25 岁，癫痫。CT 示侧脑室旁多发低密度灶，结节样或块状增强。最大可能是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脑囊虫",
      "髓鞘形成异常",
      "转移瘤",
      "多发性硬化",
      "脑脓肿",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多发性硬化",
        "年轻女性癫痫，侧脑室旁多发低密度灶伴结节样或块状增强，符合多发性硬化活动期表现。原书第02章 A2 型题第 64 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-a1027",
    order: 42,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，男性，26 岁，头颅外伤 4 小时。CT 轴位平扫示右颞骨骨折，头皮血肿，右颞部梭形不均匀高密度，中线结构左移。最可能的诊断为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "右颞叶脑挫裂伤伴硬膜下血肿",
      "右颞部急性硬膜外血肿",
      "右颞部亚急性硬膜外血肿",
      "右颞叶急性脑血肿",
      "右颞部急性硬膜下血肿",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "右颞部急性硬膜外血肿",
        "外伤后 4 小时 CT 示右颞部梭形不均匀高密度影，伴颞骨骨折、中线结构左移，符合急性硬膜外血肿（梭形、常伴骨折）；亚急性期血肿密度随时间逐渐减低。原书第02章 A2 型题第 65 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），7 道（原书第 1–7 题） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch02-cns-short001",
    order: 43,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述弥漫浸润生长的星形细胞肿瘤的分级，CT 及 MRI 表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "2016 版 WHO 中枢神经系统肿瘤分类引入分子病理诊断，将弥漫浸润生长的星形细胞肿瘤分为弥漫型星形细胞瘤（II 级）、间变型星形细胞瘤（III 级）和多形性胶质母细胞瘤（IV 级），并据 IDH1 表达类型分为 IDH1 突变型、野生型和未定型。CT 表现：肿瘤多位于白质，以低密度为主，可有瘤内出血，钙化少见，高级别肿瘤可出现坏死；肿块形态不规则、边界不清，有不同程度占位效应和瘤周水肿；增强检查 II 级肿瘤多数不强化或轻度强化，III、IV 级多数强化明显。MRI 表现：病变 T1WI 呈稍低或混杂信号，T2WI 呈均匀或不均匀高信号；增强表现与 CT 类似，高级别肿瘤强化更常见、更明显；DWI 低级别肿瘤无明显改变或弥散加快，高级别肿瘤实质部分可有弥散受限；MRS 示 NAA 及 Cr 峰不同程度减低，Cho 峰升高，NAA/Cho 倒置，Cho/Cr 升高，高级别肿瘤可出现脂质（Lip）峰和乳酸（Lac）峰；PWI 低级别肿瘤 rCBV 无明显变化甚至减低，高级别肿瘤常见 rCBV 增高。",
        "分级结合组织学与 IDH1 分子分型，影像上以强化程度、DWI 弥散受限及 rCBV 增高提示高级别。原书第02章简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-short002",
    order: 44,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "脑膜瘤的 CT 及 MRI 表现特点有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 表现：①发生部位常见于矢状窦旁、大脑凸面、蝶骨嵴、桥小脑角等处；②平扫呈等密度或略高密度，类圆形，边界清，其内常见斑点状钙化，瘤周水肿轻或无，静脉或静脉窦受压时可出现中或重度水肿；③增强后呈明显均匀强化；④以广基底与颅骨内板或脑膜相连；⑤骨改变为局限性骨增生或破坏。MRI 表现：①T1WI 上呈等或稍低信号，T2WI 上呈等或稍高信号，钙化呈低信号，坏死、囊变、出血少见，邻近脑组织受压，肿瘤与脑组织间可见脑脊液间隙；②增强扫描 I 级脑膜瘤呈均一明显强化，非典型性脑膜瘤和间变型脑膜瘤可见斑片状不均匀强化并侵犯正常脑组织，邻近脑膜增厚并强化称为“脑膜尾征”；③MRV 能明确肿瘤对静脉（窦）的压迫程度及静脉（窦）内有无血栓。",
        "脑膜瘤为脑外富血供肿瘤，均匀显著强化、广基底及脑膜尾征为其特点。原书第02章简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-short003",
    order: 45,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述垂体微腺瘤 MRI 表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "垂体微腺瘤 MRI 表现：①垂体增大，高度 ≥8mm；②垂体上缘膨胀，正常为凹面；③垂体柄向对侧移位；④瘤体偏于一侧呈 T1WI 局限性低信号，T2WI 高信号。Gd-DTPA 增强扫描，早期病灶呈充盈缺损，低于正常垂体，延迟期病灶强化，高于正常垂体。",
        "动态增强早期病灶相对低信号是垂体微腺瘤的重要特征。原书第02章简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-short004",
    order: 46,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述听神经瘤的 CT 及 MRI 表现特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 表现：①平扫，表现为桥小脑角池内等、低或混杂密度肿块，内可见囊变或出血，瘤周轻至中度水肿；多伴同侧内听道扩大；肿瘤增大可压迫脑干及小脑，出现第四脑室受压变窄、移位，伴幕上脑积水；②增强检查，肿块呈均匀、不均匀或环形强化。MRI 表现：肿瘤实性部分于 T1WI 上呈等信号或稍低信号，T2WI 上信号增高，增强后肿瘤实性部分呈明显均匀或不均匀强化，囊变后呈明显环形强化；内听道与桥小脑池强化肿块可形成“冰激凌”样外观；增强及薄层扫描还可检出和诊断内耳道内 3mm 的微小肿瘤。",
        "听神经瘤为桥小脑角区最常见肿瘤，内听道扩大及“冰激凌”样外观有特征性。原书第02章简答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-short005",
    order: 47,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述脑转移瘤 CT 及 MRI 表现特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "CT 表现：①平扫，可见脑内多发或单发结节，单发者可较大，常位于皮髓质交界区；呈等或低密度灶，中心多有坏死、囊变，出血时密度增高；瘤周水肿较重，有“小病灶、大水肿”的特征；②增强检查，病变呈结节状或环形强化，多发者可呈不同形式强化。MRI 表现：增强 MRI 对诊断早期、较小的转移灶、脑干和小脑的转移灶较 CT 更敏感；普通检查 T1WI 上一般呈低信号，T2WI 为高信号，瘤内出血 T1WI 呈高信号（与出血期龄有关）；增强 T1WI 表现同 CT 增强检查，对小转移瘤的检出更敏感。",
        "脑转移瘤好发于皮髓质交界区，呈多发结节、小病灶大水肿，增强结节状或环形强化。原书第02章简答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-short006",
    order: 48,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述急性硬膜外血肿的病理特点及 CT 特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "急性硬膜外血肿的病理特点：多由脑膜血管损伤所致，脑膜中动脉常见；血液聚集硬膜外间隙，由于硬膜与颅骨内板附着紧密，故血肿较局限，呈梭形。CT 特点：①颅骨内板下方梭形或半圆形高密度区，CT 值 40~100HU，边界清楚锐利；②范围局限，一般不跨越颅缝；③占位征象较硬膜下血肿轻；④伴有颅骨骨折时可在骨窗下观察到低密度骨折线；⑤开放性骨折血肿内可见低密度气体影。",
        "急性硬膜外血肿呈梭形、不跨越颅缝、常伴骨折，CT 呈边界锐利的高密度影。原书第02章简答题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-short007",
    order: 49,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述硬膜下血肿的病理特点及 CT 特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "硬膜下血肿的病理特点：多由桥静脉或静脉窦损伤出血所致，血液聚集于硬膜下腔，沿脑表面广泛分布。CT 特点：①颅板下新月形或半月形高密度影，常跨越颅缝；②占位效应明显，常导致中线结构偏移，脑室受压变窄，严重者可形成脑疝并危及生命；③可伴有脑挫裂伤或脑内血肿、广泛脑水肿。",
        "硬膜下血肿呈新月形、可跨越颅缝，占位效应明显。原书第02章简答题第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 配伍题，3 组 / 6 成员（原书第 69–74 题） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch02-cns-b001",
    order: 50,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "颅骨内板下方双凸形高密度区",
      "颅骨内板下方新月形高密度区",
      "颅骨内板下方新月形低密度区",
      "颅骨内板下方双凹形高密度区",
      "颅骨内板下方双凸形低密度区",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch02-cns-b001m1",
        order: 50,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "急性硬膜外出血典型的 CT 表现是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "颅骨内板下方双凸形高密度区",
            "急性硬膜外血肿呈梭形（双凸形）高密度，一般不跨越颅缝。原书第02章 B 型题第 69 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch02-cns-b001m2",
        order: 51,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "急性硬膜下出血典型的 CT 表现是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "颅骨内板下方新月形高密度区",
            "急性硬膜下血肿沿脑表面分布，呈新月形高密度，可跨越颅缝。原书第02章 B 型题第 70 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-b002",
    order: 52,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "脑沟密度增高",
      "最常见的位置是基底节区",
      "颅内肿块",
      "脑水肿",
      "颅骨内板下新月形高密度影",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch02-cns-b002m1",
        order: 52,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "蛛网膜下腔出血的 CT 征象是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "脑沟密度增高",
            "蛛网膜下腔出血 CT 表现为脑沟、脑池密度增高。原书第02章 B 型题第 71 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch02-cns-b002m2",
        order: 53,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "高血压脑出血的 CT 征象",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "最常见的位置是基底节区",
            "高血压脑出血最常见于基底节区，CT 呈团块状高密度影。原书第02章 B 型题第 72 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch02-cns-b003",
    order: 54,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "儿童",
      "青壮年",
      "中老年",
      "老年",
      "中年",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch02-cns-b003m1",
        order: 54,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "颅咽管瘤好发于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "儿童",
            "颅咽管瘤多见于儿童和青年，多为囊性伴钙化。原书第02章 B 型题第 73 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch02-cns-b003m2",
        order: 55,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "髓母细胞瘤都好发于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "儿童",
            "髓母细胞瘤为儿童期最常见的恶性后颅窝肿瘤。原书第02章 B 型题第 74 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...fillItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
