import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学影像学学习指导与习题集 第3版 — 第07章 消化系统与腹膜腔 题库提取（等比取样）
 * 来源：《医学影像学学习指导与习题集》第3版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：7 题
 * - 填空题（fill）：15 题
 * - 选择题（a1-single）：43 题（A1 型 42、A2 型病例题 1）
 * - 简答题（short-answer）：9 题
 * - B1 配伍题：3 组 / 11 成员
 * - 独立记分题合计：85 题（须等于本文件预算 85）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书含四节（第一节食管与胃肠道、第二节肝脏胆系胰腺和脾、第三节腹膜腔和
 *   肠系膜、第四节急腹症），每节自带复习思考题与参考答案，选择题键号每节从 1 重新编号。
 *   本文件按 85 道预算在原书顺序内取材：名词解释取第一节第 1–5 题、第二节第 1–2 题；
 *   填空题取第一节第 1–5 题、第二节第 1–10 题；A1 型取第一节第 1–14 题、第二节第 1–28
 *   题；A2 型取第一节第 15 题；B 型取第一节第 16–17 题（1 组）、第二节第 59–67 题（2 组，
 *   共 11 成员）；简答题取第一节第 1–5 题、第二节第 1–4 题；未纳入的题因预算所限。正确项
 *   对齐各节参考答案键号（A1/A2/B1 各节独立编号），选项与共用备选答案已随机重排并同步
 *   correctChoiceIndex。OCR 错字已按医学影像学医学语义恢复（如 介人→介入、钆（Cd）→钆
 *   （Gd）、T,WI→T1WI、T2WI、MRCP、CT值、快进快出、三明治征、皮革胃 等），数值与单位
 *   保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "radiology-bank-ch07-digestive";
const locatorBase =
  "《医学影像学学习指导与习题集》第3版 第07章 消化系统与腹膜腔 习题（核对PDF 第93–119页）";
const promptNote =
  "题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），7 道（第一节原书第 1–5 题、第二节原书第 1–2 题） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：上消化道气钡双重造影",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "上消化道气钡双重造影：口服产气粉，使食管及胃充分扩展，快速口服少量钡剂观察食管后，嘱患者翻身使钡剂均匀涂布在胃黏膜表面，显示胃腔表面的细微结构，在透视的同时拍摄必要的点片，获得双对比相。随后嘱患者口服较多的钡剂填充胃腔，不同体位观察胃十二指肠，透视和摄片结合，获得充盈相，完成上消化道气钡双重造影检查。",
        "上消化道气钡双重造影通过产气粉与钡剂结合获得双对比相与充盈相，显示胃腔表面细微结构。原书第一节（食管与胃肠道）名词解释第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：龛影",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "龛影：指钡剂涂布的轮廓有局限性外突的影像。消化性溃疡及肿瘤坏死性溃疡形成的凹陷，使钡剂充填滞留，轴位观溃疡呈火山口状。",
        "龛影为钡剂充填于溃疡或坏死凹陷内形成的局限性外突影像，是消化道溃疡的直接征象。原书第一节（食管与胃肠道）名词解释第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：充盈缺损",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "充盈缺损：指钡剂涂布的轮廓有局限性向内凹陷的表现。为管壁局限性肿块向腔内突出，造成局部钡剂不能充盈所致。",
        "充盈缺损与龛影方向相反，为腔内占位性病变（如肿瘤、息肉）造成的钡剂不能充盈区。原书第一节（食管与胃肠道）名词解释第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：“三明治征”",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "“三明治征”：CT 和 MRI 图像上，肿块和（或）肿大的淋巴结相融合，包绕血管，强化明显的血管从肿块中穿行，似“三明治”样，是胃肠道淋巴瘤特征性表现。",
        "“三明治征”为胃肠道淋巴瘤的特征性影像表现，指肿块或肿大淋巴结包绕强化明显的血管穿行。原书第一节（食管与胃肠道）名词解释第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：“皮革胃”",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "“皮革胃”：浸润型胃癌沿胃壁浸润生长，侵犯胃壁各层，侵及胃大部或全部，导致胃壁增厚、僵硬，蠕动消失，形态固定，似“皮革囊”样。",
        "“皮革胃”即弥漫浸润型胃癌，胃壁弥漫增厚僵硬、蠕动消失、形态固定如皮革囊。原书第一节（食管与胃肠道）名词解释第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：“环征”",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "“环征”：肝脓肿表现低密度的脓腔和环形强化的脓肿壁以及周围的无强化的低密度水肿带的环状影像。",
        "“环征”由低密度脓腔、环形强化脓肿壁及周围无强化水肿带构成，为肝脓肿的特征性表现之一。原书第二节（肝脏、胆系、胰腺和脾）名词解释第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：“灯泡”征",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "“灯泡”征：肝海绵状血管瘤在 T2WI 上，随着回波时间延长，信号强度增高，在低信号的肝实质背景衬托下，肿瘤表现为边缘锐利的极高信号灶。",
        "“灯泡征”为肝海绵状血管瘤在重 T2WI 上的特征性表现，随回波时间延长信号强度增高。原书第二节（肝脏、胆系、胰腺和脾）名词解释第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），15 道（第一节原书第 1–5 题、第二节原书第 1–10 题） */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill001",
    order: 8,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：黏膜皱襞破坏：正常的____，代之以杂乱不规则的____，多为____所致。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：黏膜皱襞消失；第2空：钡斑影；第3空：恶性肿瘤侵犯。",
        "黏膜皱襞破坏表现为正常黏膜皱襞消失，代之以杂乱不规则的钡斑影，多为恶性肿瘤侵犯所致。原书第一节（食管与胃肠道）填空题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill002",
    order: 9,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：十二指肠溃疡好发____，多系____所致；也可表现____，易造成球部____，钡剂到达后不易停留。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：球部；第2空：变形；第3空：激惹征；第4空：幽门梗阻。",
        "十二指肠溃疡好发于球部，可致球部变形、激惹征及幽门梗阻等表现。原书第一节（食管与胃肠道）填空题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill003",
    order: 10,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：胃溃疡的直接征象是____，多见于____，切线位呈____，边缘____，底部较____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：龛影；第2空：胃小弯；第3空：火山口状；第4空：光滑整齐；第5空：平整。",
        "胃溃疡的直接征象为龛影，多见于胃小弯，切线位呈火山口状，边缘光滑整齐，底部较平整。原书第一节（食管与胃肠道）填空题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill004",
    order: 11,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：MSCT 增强扫描多数可显示胃壁的三层结构，即腔内面强化明显的____，其下强化不明显的____，及最外侧稍强化的____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：黏膜层；第2空：黏膜下层和肌层；第3空：浆膜层。",
        "MSCT 增强扫描可显示胃壁黏膜层、黏膜下层和肌层、浆膜层的三层结构。原书第一节（食管与胃肠道）填空题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill005",
    order: 12,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：空肠与回肠没有明确的分界，空肠位于____，富于____；回肠位于____，皱襞____，轮廓____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：左上腹；第2空：环形皱襞；第3空：右下腹和盆腔；第4空：少而浅；第5空：光滑。",
        "空肠位于左上腹、富于环形皱襞；回肠位于右下腹和盆腔，皱襞少而浅、轮廓光滑。原书第一节（食管与胃肠道）填空题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill006",
    order: 13,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：肝脏螺旋 CT 多期扫描于静脉高压注射对比剂后，分别在 25~35 秒、50~70 秒、110~120 秒进行扫描，可获得肝____、____和____的 CT 图像。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：动脉期；第2空：门脉期；第3空：平衡期。",
        "肝脏螺旋 CT 多期扫描按 25~35 秒、50~70 秒、110~120 秒分别获得动脉期、门脉期和平衡期图像。原书第二节（肝脏、胆系、胰腺和脾）填空题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill007",
    order: 14,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：肝脏 MRI 特殊对比剂增强后，通常延迟 20 分钟左右进行____期扫描。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：肝胆特异期。",
        "肝脏特异性对比剂（如 Gd-EOB-DTPA）增强后延迟约 20 分钟为肝胆特异期。原书第二节（肝脏、胆系、胰腺和脾）填空题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill008",
    order: 15,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：在脂肪肝 MRI 定性诊断中，常用化学位移 GRE 序列，获得____和____图像。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：正相；第2空：反相。",
        "化学位移 GRE 序列通过正相与反相成像判断肝内脂质，反相信号减低提示脂肪浸润。原书第二节（肝脏、胆系、胰腺和脾）填空题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill009",
    order: 16,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：肝脓肿的影像学诊断的特异性征象为____和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：“环征”；第2空：脓肿内的小气泡。",
        "肝脓肿影像学诊断的特异性征象为“环征”及脓肿内的小气泡。原书第二节（肝脏、胆系、胰腺和脾）填空题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill010",
    order: 17,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：原发性肝癌分为巨块型、结节型和弥漫型，其中结节型肿块大小直径____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：<5cm。",
        "原发性肝癌结节型肿块直径小于 5cm。原书第二节（肝脏、胆系、胰腺和脾）填空题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill011",
    order: 18,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：小肝癌的 CT 诊断依据是单个肿瘤的直径或两个肿瘤的直径总和____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：<3cm。",
        "小肝癌指单个肿瘤直径或两个肿瘤直径总和小于 3cm。原书第二节（肝脏、胆系、胰腺和脾）填空题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill012",
    order: 19,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：肝脏常见富血供肿瘤有____、____、____等。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：肝海绵状血管瘤；第2空：肝细胞癌；第3空：肝腺瘤。",
        "肝脏常见富血供肿瘤包括肝海绵状血管瘤、肝细胞癌和肝腺瘤等。原书第二节（肝脏、胆系、胰腺和脾）填空题第 7 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill013",
    order: 20,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：肝脏海绵状血管瘤典型 CT 表现为“____”动态增强特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：“快进慢出”。",
        "肝海绵状血管瘤动脉期边缘结节状强化、延迟期持续充填，呈“快进慢出”特点。原书第二节（肝脏、胆系、胰腺和脾）填空题第 8 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill014",
    order: 21,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：胆总管直径超过____，CT 或 MRI 检查可认为胆管扩张。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：1.0cm。",
        "胆总管直径超过 1.0cm 可认为胆管扩张。原书第二节（肝脏、胆系、胰腺和脾）填空题第 9 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-fill015",
    order: 22,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "填空题：胆总管下段低位梗阻性胆管扩张的病因可能为____、____、____。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "第1空：结石；第2空：炎症；第3空：肿瘤。",
        "胆总管下段低位梗阻性胆管扩张的病因可为结石、炎症和肿瘤等。原书第二节（肝脏、胆系、胰腺和脾）填空题第 10 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），43 道（第一节 A1 原书第 1–14 题、A2 原书第 15 题、第二节 A1 原书第 1–28 题） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1001",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "出现吞咽困难，首先影像学检查方法是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "硫酸钡造影",
      "CT检查",
      "MRI检查",
      "超声检查",
      "X线片",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "硫酸钡造影",
        "吞咽困难首先应行食管钡剂造影检查，直接显示管腔及黏膜改变。原书第一节（食管与胃肠道）A1 型题第 1 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1002",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "食管钡餐造影时食管癌的影像学表现，哪项描述不正确",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "管腔狭窄",
      "管腔内半圆形充盈缺损、边缘光滑",
      "不规则形或长条形龛影",
      "受累段食管壁局限性僵硬",
      "黏膜皱襞消失、中断、破坏",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "管腔内半圆形充盈缺损、边缘光滑",
        "食管癌的充盈缺损形态不规则、边缘不光滑，半圆形边缘光滑的充盈缺损多见于良性肿瘤，故该项描述不正确。原书第一节（食管与胃肠道）A1 型题第 2 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1003",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪项不属于消化道功能性改变",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "蠕动的改变",
      "黏膜皱襞的改变",
      "运动力的改变",
      "分泌功能的改变",
      "张力的改变",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "黏膜皱襞的改变",
        "消化道功能性改变包括张力、蠕动、运动力和分泌功能的改变，黏膜皱襞的改变属器质性改变。原书第一节（食管与胃肠道）A1 型题第 3 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1004",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "腔外龛影与憩室相同之处是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "均管壁薄弱所致",
      "均为良性病变",
      "均有黏膜进入",
      "均有管壁的破坏",
      "均突出于胃肠壁外",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "均突出于胃肠壁外",
        "腔外龛影与憩室均突出于胃肠壁轮廓之外，但二者成因、性质及黏膜改变不同。原书第一节（食管与胃肠道）A1 型题第 4 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1005",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "十二指肠溃疡的影像学表现，哪项描述不正确",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "十二指肠球部龛影",
      "激惹征",
      "幽门松弛",
      "球部固定压痛",
      "十二指肠球部变形",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "幽门松弛",
        "十二指肠溃疡可致球部变形、龛影、激惹征及球部固定压痛，幽门松弛不是其特征表现。原书第一节（食管与胃肠道）A1 型题第 5 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1006",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胃癌的影像学表现，哪项描述不正确",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "龛影",
      "胃腔狭窄，管壁僵硬",
      "局部蠕动消失",
      "龛影口部可见黏膜线",
      "充盈缺损，形态不规则",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "龛影口部可见黏膜线",
        "黏膜线为良性溃疡龛影口部水肿表现，胃癌龛影口部多呈环堤、指压痕及裂隙征，故该项描述不正确。原书第一节（食管与胃肠道）A1 型题第 6 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1007",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪项是关于胃癌的描述是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "CT 可表现为局部胃壁增厚",
      "CT 可表现局部胃壁溃疡",
      "CT 可帮助评估胃癌分期",
      "常伴有胃周淋巴结转移",
      "可起源于肌层",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "可起源于肌层",
        "胃癌起源于胃黏膜上皮，不起源于肌层，故该项描述错误。原书第一节（食管与胃肠道）A1 型题第 7 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1008",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "结肠癌的影像学表现，哪项描述不正确",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "管壁僵硬",
      "广泛性肠腔狭窄，边缘整齐",
      "肠壁增厚，近段肠梗阻",
      "局部蠕动消失",
      "腔内充盈缺损，形态不规则",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "广泛性肠腔狭窄，边缘整齐",
        "结肠癌所致肠腔狭窄多呈局限性不规则狭窄，边缘不整齐，广泛边缘整齐的狭窄不符合结肠癌表现。原书第一节（食管与胃肠道）A1 型题第 8 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1009",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下面关于 GIST 的描述哪项不正确",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "腔内、外肿块",
      "临床表现多见消化道出血",
      "肿瘤可液化、坏死及囊变",
      "肿瘤可均匀强化",
      "常见淋巴结转移",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "常见淋巴结转移",
        "胃肠道间质瘤（GIST）少见淋巴结转移，故该项描述不正确。原书第一节（食管与胃肠道）A1 型题第 9 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1010",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下面关于十二指肠癌的描述哪项是正确的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "局部肠壁的增厚或肿块",
      "肠梗阻少见",
      "局部侵犯不累及胰腺",
      "局部侵犯不累及胆总管",
      "起源于黏膜下层",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "局部肠壁的增厚或肿块",
        "十二指肠癌影像上常表现为局部肠壁增厚或肿块，并可侵犯胰腺、胆总管等邻近结构。原书第一节（食管与胃肠道）A1 型题第 10 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1011",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于胃肠淋巴瘤的描述，下列哪项不正确",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "以胃淋巴瘤最多见，其次是小肠，结肠较少见",
      "病变肠管可呈动脉瘤样扩张",
      "特征性的“三明治征”",
      "肿块常有出血、坏死及钙化",
      "病理上以非霍奇金淋巴瘤多见",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿块常有出血、坏死及钙化",
        "胃肠淋巴瘤以非霍奇金淋巴瘤多见，胃最常见，可呈动脉瘤样扩张及“三明治征”，肿块出血、坏死及钙化少见。原书第一节（食管与胃肠道）A1 型题第 11 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1012",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下面关于克罗恩病哪项描述是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "是一种缓解与复发交替发生的慢性疾病",
      "MRI 小肠造影可以帮助明确病变范围及炎性活动情况",
      "CT 小肠造影可以帮助明确病变范围及炎性活动情况",
      "由于 CT 较 MRI 检查时间短，推荐使用 CT 小肠造影检查",
      "克罗恩病多见于年轻人",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "由于 CT 较 MRI 检查时间短，推荐使用 CT 小肠造影检查",
        "克罗恩病多见于年轻人，缓解与复发交替，CT/MRI 小肠造影均可评估病变，但并不能因 CT 时间短而普遍推荐替代 MRI，该项描述错误。原书第一节（食管与胃肠道）A1 型题第 12 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1013",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "Crohn disease 的影像表现，哪项描述是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "多节段分布，呈跳跃性",
      "炎症活动期的影像特征是肠壁增厚强化明显、黏膜下层水肿、“梳征”明显、腹腔脓肿",
      "疾病缓解期不出现肠梗阻",
      "可并发蜂窝组织炎和瘘管形成",
      "好发于回肠末端",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "疾病缓解期不出现肠梗阻",
        "克罗恩病好发于回肠末端、多节段跳跃性分布，缓解期因肠壁纤维化瘢痕收缩仍可出现肠梗阻，故该项描述错误。原书第一节（食管与胃肠道）A1 型题第 13 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1014",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于溃疡性结肠炎，下列哪项描述是错误的",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "病变肠管常呈连续性分布，主要累及肠道黏膜与黏膜下层",
      "活动期病理表现为黏膜弥漫的炎症细胞浸润，隐窝变形、破坏和脓肿形成",
      "CT 或 MRI 可表现为病变区域肠壁增厚，结肠袋消失",
      "可并发中毒性巨结肠",
      "病变只累及结直肠，可发生在结直肠的任何部位，其中以直肠、乙状结肠最为常见",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "病变只累及结直肠，可发生在结直肠的任何部位，其中以直肠、乙状结肠最为常见",
        "溃疡性结肠炎病变常自直肠开始、连续性累及结直肠，并非可发生在结直肠的任何部位，该项描述错误。原书第一节（食管与胃肠道）A1 型题第 14 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1015",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "患者，男性，63 岁，便血，无其他不适，内镜提示距肛 6cm 处肠腔内肿块，活检病理提示高分化性腺癌，MRI 显示距肛缘约 5cm 处肠壁增厚，侵犯系膜，系膜内淋巴结信号不均匀，短径约 10mm，首先考虑",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "乙状结肠癌突破浆膜面，无可疑淋巴结转移",
      "转移性肠癌",
      "直肠癌突破肌层伴直肠系膜内淋巴结转移",
      "乙状结肠癌突破浆膜面伴系膜内淋巴结转移",
      "直肠癌突破浆膜面，无可疑淋巴结转移",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "直肠癌突破肌层伴直肠系膜内淋巴结转移",
        "肿块距肛缘约 5~6cm 属直肠，MRI 示肠壁增厚侵犯系膜并系膜内淋巴结增大（短径约 10mm），首先考虑直肠癌突破肌层伴直肠系膜内淋巴结转移。原书第一节（食管与胃肠道）A2 型题第 15 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1016",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肝内肿块，螺旋 CT 多期扫描表现“快进快出”现象，最可能的疾病是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肝海绵状血管瘤",
      "肝囊肿",
      "肝脓肿",
      "肝转移瘤",
      "肝细胞癌",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝细胞癌",
        "肝细胞癌以肝动脉供血为主，增强呈动脉期明显强化、门脉期及延迟期迅速减低，即“快进快出”，为典型表现。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 1 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1017",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肝硬化的 RN 及 DN 的影像学检查中哪项最具有价值",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "CT增强",
      "MRI特异性对比剂增强扫描",
      "X线血管造影",
      "超声",
      "CT平扫",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "MRI特异性对比剂增强扫描",
        "肝硬化再生结节（RN）及增生不良结节（DN）的影像学评估以 MRI 特异性对比剂增强扫描价值最大，可结合肝胆期信号鉴别。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 2 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1018",
    order: 40,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在我国肝硬化最常见的病因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "酗酒",
      "药物中毒",
      "胆汁淤积",
      "寄生虫",
      "病毒性肝炎",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "病毒性肝炎",
        "我国肝硬化最常见的病因是病毒性肝炎（主要为乙型、丙型肝炎）。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 3 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1019",
    order: 41,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪项不属于肝癌组织学分类",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胆管细胞型",
      "混合型",
      "纤维层状型肝细胞癌",
      "鳞癌",
      "肝细胞型",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "鳞癌",
        "肝癌组织学分类包括肝细胞型、胆管细胞型、混合型及纤维层状型肝细胞癌等，鳞癌不属于肝癌组织学分类。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 4 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1020",
    order: 42,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肝血管瘤下列说法不正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肉眼呈紫红色，质地较软",
      "一般有包膜",
      "瘤内呈窦状或筛孔样，犹如海绵",
      "是最常见的肝脏肿瘤",
      "女性多于男性",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "一般有包膜",
        "肝海绵状血管瘤是肝脏最常见的良性肿瘤，肉眼呈紫红色海绵状、质地软，一般无包膜，故该项说法不正确。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 5 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1021",
    order: 43,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "典型肝细胞癌 CT 或 MRI 上表现特征是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "静脉期明显强化",
      "门脉期延迟增强",
      "增强呈“快进快出”表现",
      "三期均不强化",
      "动脉期明显强化",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "增强呈“快进快出”表现",
        "典型肝细胞癌增强呈动脉期明显强化、门脉期及延迟期迅速减退的“快进快出”表现。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 6 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1022",
    order: 44,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肝脏最常见的肝良性肿瘤或肿瘤样病变是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肝囊肿",
      "肝腺瘤",
      "海绵状血管瘤",
      "肝脏炎性肌纤维母细胞瘤",
      "局灶性结节增生",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "海绵状血管瘤",
        "海绵状血管瘤是肝脏最常见的良性肿瘤。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 7 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1023",
    order: 45,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "MRI 表现为“灯泡征”的疾病常见于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肝脏海绵状血管瘤",
      "肝腺瘤",
      "肝脏局灶性结节增生",
      "肝硬化",
      "肝癌",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝脏海绵状血管瘤",
        "肝海绵状血管瘤在重 T2WI 上呈边缘锐利的极高信号，即“灯泡征”。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 8 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1024",
    order: 46,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "Budd-Chiari 综合征的病理特点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肝静脉闭塞",
      "门静脉闭塞",
      "门静脉扩张",
      "肝静脉扩张",
      "肝动脉闭塞",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝静脉闭塞",
        "Budd-Chiari 综合征的病理基础是肝静脉和（或）肝段下腔静脉闭塞。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 9 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1025",
    order: 47,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "小肝癌确诊的首选方法是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "CT增强扫描",
      "穿刺活检",
      "MRI增强扫描",
      "PET-CT 扫描",
      "超声",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "穿刺活检",
        "小肝癌的确诊以穿刺活检病理为金标准。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 10 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1026",
    order: 48,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肝腺瘤错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "主要由正常肝细胞构成，不具有正常肝小叶的结构",
      "结构内无胆管，病灶容易出血，肿瘤实质内可见脂肪",
      "多见于女性",
      "病灶中心可见放射状分布的纤维瘢痕",
      "肝腺瘤常有包膜，与周围组织界限清楚，一般呈圆形",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "病灶中心可见放射状分布的纤维瘢痕",
        "放射状纤维瘢痕见于肝脏局灶性结节增生（FNH），肝腺瘤不具有此特征，故该项错误。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 11 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1027",
    order: 49,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肝脏局灶性结节增生错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "可以与周围肝组织分界不清",
      "主要由正常肝细胞和 Kupffer 细胞组成",
      "其内含有血管和胆管组织，中心有星芒状瘢痕组织",
      "肝脏 Gd-EOB-DTPA MRI 增强扫描，肝胆期常呈低信号",
      "不属于真正的肝脏肿瘤",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝脏 Gd-EOB-DTPA MRI 增强扫描，肝胆期常呈低信号",
        "FNH 含正常肝细胞和 Kupffer 细胞，Gd-EOB-DTPA 增强肝胆期常呈等或高信号而非低信号，故该项错误。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 12 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1028",
    order: 50,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于细菌性肝脓肿下列说法错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脓肿可以单发或多发，单房或多房",
      "脓肿壁由炎性细胞及纤维肉芽组织构成，周围肝实质可见水肿",
      "可以为革兰阳性细菌或革兰阴性细菌感染",
      "下腔静脉是其主要感染途径",
      "通常由胆道炎症所引起",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "下腔静脉是其主要感染途径",
        "细菌性肝脓肿多经胆道、肝动脉、门静脉等途径感染，下腔静脉不是其主要感染途径，故该项错误。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 13 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1029",
    order: 51,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪种肝脏疾病发病率无明显的男女性别差异",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肝腺瘤",
      "肝脏囊腺瘤",
      "胆管细胞癌",
      "肝局灶性结节增生",
      "肝血管瘤",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胆管细胞癌",
        "肝血管瘤、肝腺瘤、肝脏囊腺瘤及 FNH 均好发于女性，胆管细胞癌发病率无明显性别差异。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 14 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1030",
    order: 52,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "弥漫性脂肪肝的肝岛残留常见于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "左叶外侧段",
      "左叶内侧段",
      "右叶前段",
      "右叶后段",
      "胆囊床附近",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胆囊床附近",
        "弥漫性脂肪肝中的正常肝组织岛（肝岛）常见于胆囊床附近、肝裂旁或左叶内侧段肝被膜下。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 15 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1031",
    order: 53,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "导致肝硬化的原因不包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "酒精中毒",
      "胆汁淤积",
      "工业中毒或药物",
      "营养不良",
      "病毒性肝炎",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "营养不良",
        "肝硬化的病因包括病毒性肝炎、酒精中毒、胆汁淤积、工业中毒或药物等，营养不良不包括在内。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 16 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1032",
    order: 54,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "动态增强扫描主要是研究病灶的增强特征，常用于鉴别的疾病是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "脂肪肝和血管瘤",
      "肝炎和肝癌",
      "脂肪肝和肝硬化",
      "肝癌和血管瘤",
      "肝炎和肝硬化",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝癌和血管瘤",
        "动态增强扫描通过观察病灶增强特征，常用于肝癌（快进快出）与肝海绵状血管瘤（快进慢出）的鉴别。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 17 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1033",
    order: 55,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列不是脂肪肝的 CT 表现的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "增强扫描可见肝脏血管变形或移位",
      "局限性脂肪肝呈地图样改变",
      "平扫肝脏的 CT 值低于脾脏",
      "肝内血管影模糊或相对高密度",
      "肝脏实质密度减低",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "增强扫描可见肝脏血管变形或移位",
        "脂肪肝时肝内血管走行、排列、大小、分支正常，无受压移位或侵犯征象，故该项不是脂肪肝 CT 表现。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 18 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1034",
    order: 56,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肝脏特异性对比剂 MRI 增强扫描肝细胞癌在肝胆特异期的信号为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "稍高信号",
      "明显高信号",
      "等信号",
      "混杂信号",
      "低信号",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "低信号",
        "肝细胞癌缺乏有机阴离子转运蛋白，肝胆特异期摄取对比剂减少，常呈低信号。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 19 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1035",
    order: 57,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "Caroli 病的 CT 表现错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肝门区中心胆管无扩张",
      "肝内多个小囊状区域与肝内胆管不连接",
      "扩张的肝内胆管内可以有结石",
      "可伴有肝硬化表现",
      "肝内胆管多发扩张，右叶为主",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝内多个小囊状区域与肝内胆管不连接",
        "Caroli 病为先天性肝内胆管囊状扩张，扩张的囊状区域与肝内胆管相连通，故该项表述错误。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 20 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1036",
    order: 58,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "MRCP 示肝内外胆管扩张，部分串珠样，胆总管下段壁厚、逐渐变细，最可能的诊断是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胰头癌",
      "胆囊癌",
      "胆总管结石",
      "胆管慢性炎症",
      "胆总管癌",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胆管慢性炎症",
        "胆管慢性炎症可致肝内外胆管扩张、部分呈串珠样，胆总管下段壁厚、逐渐变细。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 21 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1037",
    order: 59,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "CT 平扫时正常肝内静脉和门静脉的密度一般",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "高于肝实质",
      "等于肝实质",
      "略高于肝实质",
      "高于或等于肝实质",
      "低于肝实质",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "低于肝实质",
        "CT 平扫时正常肝内静脉和门静脉内为血液，密度一般低于肝实质。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 22 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1038",
    order: 60,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于胆管细胞癌下列说法错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "与肝癌相比更容易形成门脉癌栓",
      "平扫呈低密度，部分病变可见不规则钙化",
      "增强后病变显示清楚，可呈多发结节状",
      "有时末梢胆管的扩张是唯一的征象",
      "起源于肝内胆管的上皮细胞",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "与肝癌相比更容易形成门脉癌栓",
        "肝细胞癌更易形成门脉癌栓，胆管细胞癌相对少见，故该项说法错误。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 23 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1039",
    order: 61,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "CT 图像上胆囊壁增厚的标准为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      ">4mm",
      ">5mm",
      ">6mm",
      ">7mm",
      ">3mm",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        ">3mm",
        "CT 图像上胆囊壁厚度超过 3mm 视为增厚。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 24 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1040",
    order: 62,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于胆总管直径的描述，下列选项正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "正常胆总管直径<8mm，>10mm 为扩张",
      "正常胆总管直径<10mm，>15mm 为扩张",
      "正常胆总管直径<15mm，>20mm 为扩张",
      "正常胆总管直径<15mm，>25mm 为扩张",
      "正常胆总管直径<5mm，>8mm 为扩张",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "正常胆总管直径<8mm，>10mm 为扩张",
        "正常胆总管直径小于 8mm，超过 10mm 认为扩张。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 25 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1041",
    order: 63,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "胆囊增大原因下列哪项正确",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "腹腔疾病如肠系膜淋巴结炎",
      "迷走神经切除术后",
      "慢性胰腺炎",
      "糖尿病和巨人症",
      "胆囊炎、胆管和胆总管梗阻，如结石、肿瘤、外压等",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胆囊炎、胆管和胆总管梗阻，如结石、肿瘤、外压等",
        "胆囊增大常见于胆囊炎、胆管和胆总管梗阻（结石、肿瘤、外压）等。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 26 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1042",
    order: 64,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "慢性胆囊炎的特征性 CT 表现为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胆囊缩小",
      "胆囊壁增厚，可钙化",
      "合并结石",
      "胆管扩张",
      "胆囊增大",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胆囊壁增厚，可钙化",
        "慢性胆囊炎特征性 CT 表现为胆囊壁增厚，可伴钙化。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 27 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-a1043",
    order: 65,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关胆管癌的描述，下列哪项不正确",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肿瘤发生于肝内胆管",
      "临床上常表现为进行性黄疸",
      "根据肿瘤的形态学分为结节型、浸润型、乳头型，以浸润型最常见",
      "CT 显示肝内外胆管不同程度扩张",
      "组织学类型 95% 为腺癌，少数鳞癌",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肿瘤发生于肝内胆管",
        "胆管癌可发生于肝内、肝门部及肝外胆管，并非仅发生于肝内胆管，故该项不正确。原书第二节（肝脏、胆系、胰腺和脾）A1 型题第 28 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），9 道（第一节原书第 1–5 题、第二节原书第 1–4 题） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-short001",
    order: 66,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述食管静脉曲张的钡剂造影表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "食管静脉曲张的钡剂造影表现主要有：食管中下段的黏膜皱襞增宽、迂曲，呈蚯蚓状或串珠状充盈缺损，管壁边缘呈锯齿状；食管张力降低，管腔扩张，钡剂排空延迟，食管壁柔软。",
        "食管静脉曲张以黏膜皱襞增宽迂曲、蚯蚓状或串珠状充盈缺损、管壁柔软为特征。原书第一节（食管与胃肠道）简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-short002",
    order: 67,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述胃良恶性溃疡的X线鉴别诊断要点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胃良恶性溃疡的X线鉴别诊断要点：①龛影形状：良性溃疡为圆形或椭圆形，边缘光滑整齐；恶性溃疡不规则、扁平，有多个尖角。②龛影位置：良性溃疡突出于胃轮廓外；恶性溃疡位于胃轮廓之内。③龛影周围和口部：良性溃疡有黏膜水肿表现，如黏膜线、项圈征、狭颈征等，黏膜皱襞向龛影集中达龛影口；恶性溃疡有不规则的环堤、指压痕、裂隙征，黏膜皱襞中断、破坏。④附近胃壁：良性溃疡胃壁柔软、有蠕动；恶性溃疡胃壁僵硬、峭直，蠕动消失。",
        "胃良恶性溃疡鉴别主要从龛影形状、位置、口部及周围改变和附近胃壁蠕动四方面进行。原书第一节（食管与胃肠道）简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-short003",
    order: 68,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述胃肠道间质瘤的CT表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胃肠道间质瘤的CT表现主要有：胃肠壁起源的实性肿块，直径小于5cm的肿块趋向于边界清楚，肿块密度或信号趋向均匀，中度或明显强化；较大的肿块常有坏死、囊变和出血，强化不均，境界欠清，当肿瘤坏死与肠管相通时，肿瘤内可见气液平；少见淋巴结肿大。",
        "GIST 为胃肠壁起源实性肿块，小者边界清楚、强化均匀，大者坏死囊变出血、强化不均，少见淋巴结肿大。原书第一节（食管与胃肠道）简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-short004",
    order: 69,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述肠癌、肠淋巴瘤及肠 GIST CT 鉴别诊断要点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肠癌、肠淋巴瘤及肠GIST CT鉴别诊断要点主要有：①肠癌：肠壁局限性增厚，肠腔不规则狭窄，肠梗阻不同程度存在。②肠淋巴瘤：肠壁可环形增厚，病变段肠管动脉瘤样扩张，肠梗阻不常见，如为肿块，肿块密度较均匀，轻中度强化，“三明治征”常为特征性表现。③肠道GIST：起源于肠壁的实性肿块，直径小于5cm的肿块趋向于边界清楚，密度或信号趋向均匀，中度或明显强化，较大的肿块常有坏死、囊变和出血，强化不均，境界欠清，当肿瘤坏死与肠管相通时可见气液平，消化道出血常见，肠梗阻少见。",
        "三者在肠壁增厚方式、肠梗阻有无、强化特点及特征性征象（三明治征、气液平等）上可资鉴别。原书第一节（食管与胃肠道）简答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-short005",
    order: 70,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述克罗恩病活动期的MRI表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "克罗恩病活动期的MRI表现主要有：病变多累及回肠末端，跳跃性多节段肠管受累，肠壁增厚伴强化明显，病变处肠系膜内小血管增多、“梳征”明显，系膜内淋巴结肿大，可有腹腔脓肿及肠管周围蜂窝组织炎。",
        "克罗恩病活动期 MRI 以回肠末端跳跃性肠壁增厚强化、“梳征”及肠系膜淋巴结肿大为特征。原书第一节（食管与胃肠道）简答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-short006",
    order: 71,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述肝硬化失代偿期的CT表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝硬化失代偿期的CT表现有：①肝脏大小的改变：早期肝脏可能增大，CT检查无特异性；中晚期可出现肝叶增大和萎缩，也可全肝萎缩，更多表现为尾叶、左叶外侧段增大，右叶、左叶内侧段萎缩，出现肝各叶大小比例失调。②肝脏形态轮廓的改变：因结节再生和纤维化收缩，肝边缘凹凸不平。③肝密度的改变：脂肪变性、纤维化可引起肝弥漫性或不均匀的密度降低，较大而多发的再生结节可表现为散在略高密度结节。④肝裂增宽：纤维组织增生、肝叶萎缩致肝裂和肝门增宽，胆囊可外移。⑤继发性改变：脾大（脾外缘超过5个肋单元或脾下缘低于肝下缘）；门静脉扩张、侧支循环形成，脾门、胃底、食管下段及腰旁静脉血管增粗扭曲，出现海绵样变；腹水。",
        "肝硬化失代偿期 CT 表现包括肝叶大小比例失调、肝缘凹凸不平、肝密度改变、肝裂增宽及脾大、门脉高压侧支循环、腹水等继发改变。原书第二节（肝脏、胆系、胰腺和脾）简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-short007",
    order: 72,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述原发性肝癌 CT 平扫及增强扫描的表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "原发性肝癌CT平扫及增强扫描表现：平扫表现为稍低密度结节或肿块，边缘一般不清楚；增强扫描：肿瘤主要是肝动脉供血，而正常肝脏组织接受动脉及门脉双重供血，动脉期正常肝实质还未出现对比增强而肝癌很快出现明显的斑片状、结节状强化，CT值迅速达到峰值；门静脉期正常肝实质对比增强密度开始升高，肿瘤对比增强密度迅速下降；平衡期肿块对比增强密度继续下降，在明显强化的肝实质内又表现为低密度病灶。",
        "原发性肝癌平扫呈稍低密度肿块，增强动脉期明显强化、门脉期及平衡期密度迅速下降，呈“快进快出”表现。原书第二节（肝脏、胆系、胰腺和脾）简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-short008",
    order: 73,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述肝脏血管瘤 MRI 平扫及增强扫描的表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①MRI平扫表现：T1WI稍低信号，边界清楚；T2WI特征性表现为明显高信号，呈“灯泡征”。②MRI增强扫描表现：动脉期从周边部开始结节状强化，信号强度接近同层大血管；门脉期强化范围不断向中央扩大；平衡期及延时期病灶长时间持续强化，最后与周围正常肝实质信号强度相等。",
        "肝血管瘤 MRI 平扫 T2WI 呈“灯泡征”，增强呈动脉期周边结节状强化、延迟期持续充填的特点。原书第二节（肝脏、胆系、胰腺和脾）简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-short009",
    order: 74,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述胆总管扩张的三种以上可能原因及其CT表现。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①胆总管癌：病灶位于胆总管末端或壶腹部，局部见软组织结节或肿块影，CT平扫呈等密度，增强扫描呈中度以上强化，病变区域胆总管截断，其上端胆管明显扩张。②胆总管结石：病灶常位于胆总管下端，局部见高密度钙化或结石影，结石嵌顿处胆总管狭窄，其上端胆总管及肝内外胆管扩张。③胆总管炎：常由胆总管结石引起，CT可见炎性区域病变呈鸟嘴样狭窄，增强扫描轻度强化，局部无软组织肿块。",
        "胆总管扩张的常见原因为胆总管癌、胆总管结石及胆总管炎，分别以截断性肿块、高密度结石影及鸟嘴样炎性狭窄为CT特征。原书第二节（肝脏、胆系、胰腺和脾）简答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，3 组 / 11 成员（第一节原书第 16–17 题、第二节原书第 59–67 题） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-b001",
    order: 75,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "肠壁哑铃型肿块，密度均匀，强化明显，周围未见肿大淋巴结",
      "肠壁肿块，密度不均，肠腔狭窄伴肠梗阻，周围可见肿大淋巴结",
      "胃壁广泛增厚，胃腔形态固定、僵硬",
      "胃壁广泛增厚，胃蠕动存在，胃腔形态可改变",
      "肠壁肿块，密度均匀，轻中度强化，周围常见淋巴结肿大",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch07-digestive-b001m1",
        order: 75,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "小肠癌常表现为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肠壁肿块，密度不均，肠腔狭窄伴肠梗阻，周围可见肿大淋巴结",
            "小肠癌为肠壁肿块伴肠腔狭窄、肠梗阻及周围淋巴结肿大，密度不均。原书第一节（食管与胃肠道）B1 型题第 16 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch07-digestive-b001m2",
        order: 76,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "胃淋巴瘤常表现为",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "胃壁广泛增厚，胃蠕动存在，胃腔形态可改变",
            "胃淋巴瘤呈胃壁广泛增厚，但胃蠕动存在、胃腔形态可改变，与浸润型胃癌（皮革胃）不同。原书第一节（食管与胃肠道）B1 型题第 17 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-b002",
    order: 77,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "原发性肝细胞癌",
      "肝海绵状血管瘤",
      "肝硬化再生结节",
      "肝囊肿",
      "肝转移瘤",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch07-digestive-b002m1",
        order: 77,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "表现“快进快出”的病变是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "原发性肝细胞癌",
            "原发性肝细胞癌增强呈动脉期明显强化、门脉期及延迟期迅速减退的“快进快出”表现。原书第二节（肝脏、胆系、胰腺和脾）B1 型题第 59 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch07-digestive-b002m2",
        order: 78,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "表现“快进慢出”的病变是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肝海绵状血管瘤",
            "肝海绵状血管瘤动脉期边缘结节状强化，延迟期持续充填，呈“快进慢出”表现。原书第二节（肝脏、胆系、胰腺和脾）B1 型题第 60 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch07-digestive-b002m3",
        order: 79,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "表现“牛眼征”的病变是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肝转移瘤",
            "肝转移瘤增强后可见边缘强化伴外周低密度环，形成“牛眼征”。原书第二节（肝脏、胆系、胰腺和脾）B1 型题第 61 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch07-digestive-b002m4",
        order: 80,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "增强扫描无强化的病变是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肝囊肿",
            "肝囊肿为水样密度、囊壁薄，增强扫描无强化。原书第二节（肝脏、胆系、胰腺和脾）B1 型题第 62 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-radiology-radiology-bank-ch07-digestive-b003",
    order: 81,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "原发性肝细胞癌",
      "肝海绵状血管瘤",
      "肝硬化再生结节",
      "肝囊肿",
      "肝转移瘤",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-radiology-radiology-bank-ch07-digestive-b003m1",
        order: 81,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "MRI 表现为 T1WI 低信号，T2WI 极高信号，增强呈渐进性强化，应首先考虑",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肝海绵状血管瘤",
            "肝海绵状血管瘤 T1WI 低信号、T2WI 极高信号（灯泡征），增强呈渐进性强化。原书第二节（肝脏、胆系、胰腺和脾）B1 型题第 63 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch07-digestive-b003m2",
        order: 82,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "MRI 表现为 T1WI 低信号，T2WI 稍高信号，应首先考虑",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "原发性肝细胞癌",
            "肝细胞癌 MRI 多呈 T1WI 低信号、T2WI 稍高信号。原书第二节（肝脏、胆系、胰腺和脾）B1 型题第 64 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch07-digestive-b003m3",
        order: 83,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "MRI 表现为 T1WI 稍高信号，T2WI 低信号，应首先考虑",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肝硬化再生结节",
            "肝硬化再生结节含铁及铜沉积，T1WI 可呈稍高信号、T2WI 低信号。原书第二节（肝脏、胆系、胰腺和脾）B1 型题第 65 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch07-digestive-b003m4",
        order: 84,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "MRI 表现为 T1WI 低信号，T2WI 极高信号，增强扫描无强化，应首先考虑",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肝囊肿",
            "肝囊肿 T1WI 低信号、T2WI 极高信号，增强扫描无强化。原书第二节（肝脏、胆系、胰腺和脾）B1 型题第 66 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-radiology-radiology-bank-ch07-digestive-b003m5",
        order: 85,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "MRI 表现为多发病灶，T1WI 低信号，T2WI 稍高信号，应首先考虑",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肝转移瘤",
            "肝转移瘤常为多发病灶，T1WI 低信号、T2WI 稍高信号。原书第二节（肝脏、胆系、胰腺和脾）B1 型题第 67 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...fillItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
