import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 局部解剖学学习指导与习题集 — 第3章 胸部 题库提取（等比取样）
 * 来源：《局部解剖学学习指导与习题集》（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：23 题
 * - 选择题（a1-single）：21 题（含 A1 型、A2 型病例题）
 * - 问答题（short-answer）：9 题（简答）
 * - B1 配伍题：6 组、共 16 个成员
 * - 独立记分题合计：69 题（须等于本文件预算 69）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书各节（第一节概述、第二节胸壁、第三节膈、第四节胸膜和胸膜腔、
 *   第五节肺、第六节纵隔）依序含名词解释、选择题（A1/A2/B1）、简答题；本文件按 69
 *   道预算在原书顺序内取材：名词解释全取 23 题（概述 1、胸壁 1、膈 1、胸膜和胸膜腔 3、
 *   肺 6、纵隔 11）；A1/A2 型题取概述 A1 第 1 题、胸壁 A1 第 1–3 题及 A2 第 4 题、
 *   膈 A1 第 1–2 题及 A2 第 3 题、胸膜和胸膜腔 A1 第 1–5 题及 A2 第 6 题、
 *   肺 A1 第 1–7 题（共 21 题）；简答题全取 9 题（胸壁 2、膈 1、胸膜和胸膜腔 1、
 *   纵隔 5；第五节肺无简答题）；B1 型取完整组 6 组共 16 成员（胸壁 5–6、胸壁 7–8、
 *   膈 4–5、胸膜和胸膜腔 7–8、纵隔 21–24、纵隔 25–28）；未纳入的题因预算所限：
 *   肺 A1 第 8–16 题与 A2 第 17–19 题、纵隔 A1 第 1–13 题与 A2 第 14–20 题
 *   （共 32 题）。正确项对齐各节参考答案键号（A1/A2/B1 各小节与各节独立编号），
 *   选项与共用备选答案已随机重排并同步 correctChoiceIndex。OCR 错字已按局部解剖学
 *   医学语义恢复（如 气管权→气管杈、位子→位于、输入管→输乳管、突→喙突、
 *   胸肉筋膜→胸内筋膜、星额状位→呈额状位、文配→支配、伯偻病→佝偻病、
 *   力静脉→静脉、音柱→脊柱、睺返→喉返、主动脉号→主动脉弓、肋.上、下缘→肋上、下缘
 *   等），数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "topographic-anatomy-ch03-thorax";
const locatorBase =
  "《局部解剖学学习指导与习题集》 第3章 胸部 习题（核对PDF 第51–70页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），23 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：胸骨角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸骨角是胸骨柄与胸骨体连接处，稍向前突。两侧连第2肋软骨，是计数肋和肋间隙的标志。经胸骨角的横断面与主动脉弓和升、降主动脉的分界处、气管杈、左主支气管和食管交叉处以及第4胸椎体下缘的横断面一致。",
        "胸骨角是胸部重要的体表标志，临床上常借其平面计数肋骨及判断纵隔内结构的平面位置。原书第一节（概述）名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：乳房悬韧带",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "乳房结缔组织中有许多纤维束，两端分别附着于皮肤和胸肌筋膜，对乳房起支持和固定作用，称乳房悬韧带或 Cooper 韧带。",
        "乳腺癌时局部纤维组织增生使乳房悬韧带相对变短，皮肤形成许多小凹陷，称“橘皮样变”。原书第二节（胸壁）名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：胸肋三角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸肋三角位于膈的胸骨部与肋部起点之间，有腹壁上血管和来自腹壁和肝上面的淋巴管通过。",
        "胸肋三角与腰肋三角同为膈的薄弱区，是膈疝的好发部位。原书第三节（膈）名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：pleural cavity（胸膜腔）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸膜腔为脏、壁胸膜在肺根处相互延续共同围成的左、右各一的密闭窄隙，腔内为负压，并有少量浆液。",
        "胸膜腔左右各一、互不相通；当气胸、胸膜腔积液或胸膜粘连时会影响呼吸功能。原书第四节（胸膜和胸膜腔）名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：pulmonary ligament（肺韧带）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺根下方脏、壁胸膜的移行部分形成的双层结构，称为肺韧带。它上连肺根，下部可达肺的下缘，有固定肺的作用。",
        "肺韧带位于肺与纵隔之间，呈冠状位，是脏、壁胸膜在肺根下方相互移行形成的胸膜皱襞。原书第四节（胸膜和胸膜腔）名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：costodiaphragmatic recess（肋膈隐窝）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肋膈隐窝位于肋胸膜与膈胸膜转折处，自剑突向后下至脊柱两侧，呈半环形，后部较深，是最大的胸膜隐窝，也是胸膜腔最低处，胸膜腔积液首先积聚于此处。",
        "肋膈隐窝在平静呼吸时的深度约为 5cm，即使深吸气肺也不能深入其间。原书第四节（胸膜和胸膜腔）名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肺根",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺纵隔面中部凹陷为肺门，出入肺门的结构有肺动脉、肺静脉、支气管、支气管动、静脉、淋巴管、神经，被结缔组织包绕称肺根。",
        "肺根内结构自前向后为上肺静脉、肺动脉、主支气管和下肺静脉；两肺根前方有膈神经和心包膈血管，后方有迷走神经。原书第五节（肺）名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肺韧带",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸膜衬贴于胸腔两侧部的内表面和肺的表面，分别称为壁胸膜和脏胸膜，在肺根下方，由纵隔外侧面与肺内侧面之间的脏、壁胸膜包绕肺根相互转折移行并向下延伸形成的双层胸膜皱襞，称为肺韧带，连于肺与纵隔之间呈冠状位，有固定肺的作用。",
        "肺韧带是脏、壁胸膜在肺根下方移行形成的结构，肺手术切断肺韧带时应注意保护肺下静脉。原书第五节（肺）名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：动脉导管三角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动脉导管三角位于主动脉弓左前方的一个三角区，前界为左膈神经，后界为左迷走神经，下界为左肺动脉，内有动脉韧带、左喉返神经和心浅丛，该三角为手术时寻找动脉导管的标志。",
        "临床在动脉导管未闭手术时，常在该三角区内寻找动脉导管。原书第五节（肺）名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：动脉韧带",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动脉韧带系连于主动脉弓下缘与左肺动脉起始处之间的一纤维结缔组织索，是胚胎时期动脉导管闭锁后的遗迹。",
        "动脉韧带内通常无血流，左喉返神经绕过主动脉弓下方经其后方上行，故动脉韧带手术时应注意勿损伤左喉返神经。原书第五节（肺）名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：支气管肺段",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "由每支肺段支气管及其所属的肺组织所形成的结构，简称肺段。通常将右肺分为 10 个肺段，即上叶分 3 段，中叶分 2 段，下叶分 5 段；左肺分为 8～10 个肺段。每一肺段有一个肺段支气管分布。在肺段内，肺动脉的分支与肺段支气管的分支相伴行进入肺段，但肺叶静脉的属支段间静脉则位于两肺段之间，接受相邻两肺段的静脉血，是肺段切除的标志。相邻的肺段之间有少量疏松结缔组织相分隔。各肺段略呈圆锥形，尖朝肺门，底部达肺表面。当肺段支气管堵塞时，此段的空气出入被阻。",
        "肺段的结构和功能有相对独立性，临床上病变局限在某肺段之内时，可作该肺段切除术。原书第五节（肺）名词解释第 5 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肺叶",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "左肺由斜裂分为上、下两叶；右肺被斜裂、水平裂分为上、中、下三个叶。",
        "左肺两叶、右肺三叶是两肺外形的重要区别之一；右肺水平裂分隔上叶与中叶。原书第五节（肺）名词解释第 6 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：副半奇静脉",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "副半奇静脉汇集左侧中、上部的肋间后静脉，沿脊柱左侧下行注入半奇静脉，或直接向右跨过脊柱前面注入奇静脉。",
        "副半奇静脉是奇静脉系的组成部分之一，位于脊柱左侧，注入半奇静脉或奇静脉。原书第六节（纵隔）名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：后纵隔",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "后纵隔位于心包后面与脊柱之间，内容有食管胸段、胸主动脉、胸导管、奇静脉和半奇静脉、左右迷走神经、交感干及其发出的内脏大、小神经、纵隔后淋巴结等。",
        "后纵隔为下纵隔的一部分，位于心包后壁与胸椎之间，内主要为纵行排列的食管、胸主动脉、胸导管等结构。原书第六节（纵隔）名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term015",
    order: 15,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：奇静脉",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "奇静脉在右膈脚处起于右腰升静脉，经膈的右内侧脚和中间脚之间向上进入胸腔，在食管后方沿胸椎体右前方上行，至第4～5胸椎高度，弓形向前跨过右肺根上方，向前注入上腔静脉。奇静脉沿途收集右肋间后静脉、食管静脉、支气管静脉及半奇静脉的血液。",
        "奇静脉是沟通上、下腔静脉系的重要途径之一；奇静脉弓跨过右肺根上方，是右肺根上方的毗邻结构。原书第六节（纵隔）名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term016",
    order: 16,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：食管丛",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "迷走神经经肺根后方下行，有分支参与心浅丛和心深丛，在肺根周围分支参与肺丛。左、右迷走神经分别在食管前面和后面构成食管前丛和后丛，向下汇合成食管前干、后干，经食管裂孔入腹腔。",
        "食管丛为迷走神经在食管胸部前、后面形成的神经丛，汇合成食管前干和后干穿膈食管裂孔进入腹腔。原书第六节（纵隔）名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term017",
    order: 17,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：心包横窦",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心包横窦是心包腔的一部分，前界为升主动脉、肺动脉干，后界为左心房前壁与上腔静脉。",
        "心包横窦位于升主动脉、肺动脉干与上腔静脉、左心房之间，心外科手术时常经此窦阻断主动脉和肺动脉血流。原书第六节（纵隔）名词解释第 5 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term018",
    order: 18,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：心包裸区",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "两侧胸膜前界在第2～4胸肋关节高度靠近，下段分开，形成一个无胸膜的三角区，称心包裸区，内有心和心包。",
        "心包裸区正对胸骨体下份左侧和左侧第4、5肋间隙，心包穿刺可经此区进行而不经过胸膜腔。原书第六节（纵隔）名词解释第 6 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term019",
    order: 19,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：心包斜窦",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "心包斜窦位于两侧肺上、下静脉，下腔静脉与左心房后壁及心包后壁之间的心包腔部分。",
        "心包斜窦是心包腔位于左心房后方的部分，心包积液时液体可积聚于此。原书第六节（纵隔）名词解释第 7 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term020",
    order: 20,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：纵隔",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "纵隔位于胸腔的中部，是左、右纵隔胸膜之间器官和结构的总称。它的边界前为胸骨和肋软骨内侧部，后为脊柱胸段，两侧为纵隔胸膜，上为胸廓上口，下为膈。",
        "纵隔内的主要结构是血管、淋巴管、神经、脂肪、气管和食管；四分法以胸骨角平面分为上纵隔与下纵隔，下纵隔又以心包前、后壁为界分为前、中、后纵隔。原书第六节（纵隔）名词解释第 8 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term021",
    order: 21,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：动脉导管三角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "动脉导管三角由左膈神经、左迷走神经和左肺动脉围成。三角内有动脉韧带、左喉返神经和心浅丛等结构。临床上手术常在该三角寻找动脉导管。",
        "动脉导管三角位于主动脉弓左前方，是寻找动脉导管的标志；三角内左喉返神经绕动脉韧带后上行。原书第六节（纵隔）名词解释第 9 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term022",
    order: 22,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：胸骨后间隙",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸骨后间隙位于胸骨与胸内筋膜之间，炎症可经该间隙向膈蔓延，甚而穿过膈扩散至腹膜外脂肪层。",
        "胸骨后间隙是纵隔间隙之一，由疏松结缔组织填充，向上与颈部结缔组织及间隙相延续。原书第六节（纵隔）名词解释第 10 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-term023",
    order: 23,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：食管后间隙",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "食管后间隙位于上纵隔内，食管与胸内筋膜之间，内有胸导管、奇静脉和副半奇静脉等结构。该间隙向上通咽后间隙，向下经膈的裂隙与腹膜后隙相通。",
        "食管后间隙是纵隔间隙之一，与咽后间隙及腹膜后隙相交通，是炎症和积液扩散的潜在通道。原书第六节（纵隔）名词解释第 11 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），21 道（含 A1 型、A2 型病例题） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1001",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于胸骨角的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "两侧接第3肋软骨",
      "平对主动脉弓与升、降主动脉的分界处",
      "平对第3胸椎体下缘",
      "是右主支气管与食管相交处",
      "相当于心包裸区高度",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "平对主动脉弓与升、降主动脉的分界处",
        "胸骨角两侧连第2肋软骨；经胸骨角的横断面与主动脉弓和升、降主动脉的分界处、气管杈、左主支气管和食管交叉处以及第4胸椎体下缘的横断面一致。原书第一节（概述）A1 型题第 1 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1002",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于女性乳房淋巴引流的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "浅组位于皮下和皮内",
      "两组之间无交通或吻合",
      "如果一侧乳房淋巴回流受阻，肿瘤细胞可转移至对侧乳房",
      "女性乳房淋巴管丰富，可分浅、深两组",
      "深组位于乳腺小叶周围和输乳管壁内",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "两组之间无交通或吻合",
        "乳房淋巴管分为浅、深两组，两组之间存在吻合或交通；若一侧乳房淋巴回流受阻，肿瘤细胞可转移至对侧乳房或肝。原书第二节（胸壁）A1 型题第 1 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1003",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肋间神经的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "在肋角和腋中线之间，肋间血管、神经自上而下为静脉、动脉、神经",
      "只分布于胸壁肌肉及皮肤",
      "肋间神经有12对",
      "走行于肋间外肌与肋间内肌之间",
      "肋间后动、静脉和肋间神经从脊柱至肋角之间的走行恒定",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "在肋角和腋中线之间，肋间血管、神经自上而下为静脉、动脉、神经",
        "在肋沟处血管神经的排列自上而下为静脉、动脉、神经，此排列在肋角和腋中线之间较恒定，故胸膜腔穿刺宜在肋角外侧下位肋的上缘进针。肋间神经共 11 对（第12胸神经前支为肋下神经）。原书第二节（胸壁）A1 型题第 2 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1004",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不穿锁胸筋膜的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胸内侧神经",
      "头静脉",
      "淋巴管",
      "胸肩峰动脉",
      "胸外侧神经",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸内侧神经",
        "锁胸筋膜位于喙突、锁骨下肌和胸小肌之间，胸肩峰动脉的分支、胸外侧神经、头静脉和淋巴管穿该筋膜；胸内侧神经经胸小肌深面走行，不穿锁胸筋膜。原书第二节（胸壁）A1 型题第 3 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1005",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "患者，女，52 岁，洗澡时发现乳腺外上方无痛性肿块就医，病理检验为黏液腺癌，如果乳腺癌淋巴转移时，通过上部的淋巴管易转移到哪组淋巴结",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "尖淋巴结",
      "胸肌间淋巴结",
      "锁骨旁淋巴结",
      "对侧乳房的淋巴结",
      "胸肌淋巴结",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "尖淋巴结",
        "乳房上部的淋巴管注入尖淋巴结和锁骨上淋巴结，故经上部淋巴管转移时易转移至尖淋巴结。原书第二节（胸壁）A2 型题第 4 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1006",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于膈（diaphragm）的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "是一平坦的薄肌",
      "各部起始点之间无肌纤维，常形成肌间裂隙",
      "中央部为肌纤维，与心包愈着",
      "腔静脉孔除下腔静脉通过外，还有腰升静脉通过",
      "隔着胸腔与肺底相邻",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "各部起始点之间无肌纤维，常形成肌间裂隙",
        "膈肌性部的各部相邻处缺乏肌纤维，形成薄弱区（胸肋三角、腰肋三角）；中央部为中心腱，与心包愈着；腔静脉孔仅有下腔静脉通过。原书第三节（膈）A1 型题第 1 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1007",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于膈（diaphragm）的功能描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "舒张时，膈穹上升，胸腔容积变小，助吸气",
      "收缩时，膈穹下降，胸腔容积变大，助呼气",
      "舒张时，膈穹下降，胸腔容积变大，助吸气",
      "收缩时，膈穹下降，胸腔容积变大，助吸气",
      "收缩时，膈穹上升，胸腔容积变小，助吸气",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "收缩时，膈穹下降，胸腔容积变大，助吸气",
        "膈为主要呼吸肌，收缩时膈穹下降，胸腔容积增大，助吸气；舒张时膈穹上升恢复原位，助呼气。原书第三节（膈）A1 型题第 2 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1008",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "患者，女，58 岁，因胸骨后有烧灼感、反酸、上腹饱胀、疼痛就诊，经内镜检查为食管裂孔疝，下列关于食管裂孔位置的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "平第8胸椎，在正中线左侧2～3cm处",
      "平第10胸椎，在正中线左侧2～3cm处",
      "平第10胸椎，在正中线右侧2～3cm处",
      "平第8胸椎，在正中线右侧2～3cm处",
      "平第11胸椎，在正中线稍左侧",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "平第10胸椎，在正中线左侧2～3cm处",
        "食管裂孔平第10胸椎，在正中线左侧2～3cm处，有食管、迷走神经前干和后干、胃左血管的食管支和来自肝后部的淋巴管通过。原书第三节（膈）A2 型题第 3 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1009",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肋膈隐窝（costodiaphragmatic recess）的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "由膈胸膜和脏胸膜围成",
      "是胸膜腔最低部分",
      "通常不含浆液",
      "由壁胸膜和脏胸膜围成",
      "深吸气时肺下缘能伸入其内",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "是胸膜腔最低部分",
        "肋膈隐窝由肋胸膜与膈胸膜转折形成，呈半环形，是最大的胸膜隐窝，也是胸膜腔最低处，胸膜腔积液首先积聚于此；深吸气时肺也不能伸入其间，且含少量浆液。原书第四节（胸膜和胸膜腔）A1 型题第 1 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1010",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于胸膜下界的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "左右侧在肩胛线与第11肋相交，近后正中线处平第12胸椎棘突",
      "右侧起自第5胸肋关节后方",
      "左右侧在腋中线与第9肋相交",
      "左右侧在锁骨中线与第7肋相交",
      "为膈胸膜与纵隔胸膜的返折线",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "左右侧在肩胛线与第11肋相交，近后正中线处平第12胸椎棘突",
        "胸膜下界在锁骨中线、腋中线和肩胛线分别与第8、10和11肋相交，在后正中线两侧平第12胸椎棘突；左侧起自第6肋软骨中点处，右侧起自第6胸肋关节后方。原书第四节（胸膜和胸膜腔）A1 型题第 2 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1011",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于胸膜的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "右胸膜前界在第5胸肋关节移行为下界",
      "分为脏胸膜和壁胸膜",
      "肺根下方脏、壁胸膜的移行部分，形成肺韧带",
      "胸膜顶上面覆以胸膜上膜，有固定和保护作用",
      "肋膈隐窝是直立位时胸膜腔最低点",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "右胸膜前界在第5胸肋关节移行为下界",
        "右侧胸膜前界至第6胸肋关节高度才移行为下界；胸膜分为脏胸膜和壁胸膜，肺根下方脏、壁胸膜移行形成肺韧带，胸膜顶上面覆以胸膜上膜。原书第四节（胸膜和胸膜腔）A1 型题第 3 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1012",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于胸膜腔的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "左、右胸膜腔经肺根相通",
      "胸膜腔呈负压状态",
      "胸膜腔与外界相通",
      "胸膜腔内有肺",
      "胸膜腔在吸气时呈负压状态，呼气时呈正压状态",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸膜腔呈负压状态",
        "胸膜腔为脏、壁胸膜之间的潜在性间隙，左右各一、互不相通，呈负压，含少量浆液，肺位于胸腔内而非胸膜腔内。原书第四节（胸膜和胸膜腔）A1 型题第 4 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1013",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "男，30 岁，因外伤引起右侧开放性气胸，出现纵隔摆动，其原因是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "破坏了左侧胸膜腔的负压状态",
      "两侧胸膜腔相通",
      "破坏了右侧胸膜腔的负压状态",
      "与开放性气胸无关",
      "两侧胸膜腔互不相通",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "破坏了右侧胸膜腔的负压状态",
        "开放性气胸使右侧胸膜腔负压消失，两侧胸膜腔内压失去平衡，随呼吸运动出现纵隔摆动。原书第四节（胸膜和胸膜腔）A1 型题第 5 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1014",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "患者，男，70 岁，吸烟史 40 年，憋喘两月余，加重 3 天入院，胸片示右肋膈隐窝处有胸腔积液，为明确积液性质拟行胸腔穿刺术，穿刺部位为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肩胛线第7或第8肋间隙，上一肋下缘",
      "腋后线第7或第8肋间隙，下一肋上缘",
      "锁骨中线第7肋间隙，下一肋上缘",
      "腋后线第7或第8肋间隙，上一肋下缘",
      "腋中线第7或第8肋间隙，上一肋下缘",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腋后线第7或第8肋间隙，下一肋上缘",
        "肋间血管、神经在肋角外侧行于肋沟内，自上而下为静脉、动脉、神经，故穿刺宜在肩胛线或腋后线第7、8肋间隙、下位肋的上缘进针，以免损伤肋间血管神经。原书第四节（胸膜和胸膜腔）A2 型题第 6 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1015",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "在右侧锁骨中线与第7肋间隙交点，以水平方向向深面刺入 10cm，穿透皮肤、浅筋膜和肌层后，再被刺破的结构依次是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肋胸膜、膈胸膜、膈",
      "肋胸膜、脏胸膜、肺",
      "肋胸膜、膈胸膜、脏胸膜、肺",
      "肋胸膜、脏胸膜、肺、脏胸膜、肋胸膜",
      "肋胸膜、脏胸膜、肺、脏胸膜、膈胸膜、膈",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肋胸膜、膈胸膜、膈",
        "锁骨中线第7肋间隙位于肺下界与胸膜下界之间，肺下缘不至此平面，故刺入时依次穿过肋胸膜、膈胸膜和膈，而不经过肺与脏胸膜。原书第五节（肺）A1 型题第 1 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1016",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关肺的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肺尖由胸廓上口向上突出伸至颈根部",
      "位于胸膜腔内",
      "右肺宽而短，有胸主动脉压迹",
      "左肺窄而长，有奇静脉压迹",
      "左、右肺借斜裂分为上、下两叶",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺尖由胸廓上口向上突出伸至颈根部",
        "肺位于胸腔内纵隔两侧，借肺根和肺韧带与纵隔相连；肺尖高出锁骨内侧 1/3 上方 2～3cm，经胸廓上口突入颈根部。奇静脉压迹在右肺，胸主动脉压迹在左肺；右肺还被水平裂分为上、中、下三叶。原书第五节（肺）A1 型题第 2 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1017",
    order: 40,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列有关肺根的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "两侧肺根均与膈神经、心包膈血管、迷走神经和肺丛相邻",
      "仅由主支气管、肺动脉、肺静脉组成",
      "左肺根前邻胸主动脉，右肺根前邻上腔静脉",
      "肺根全长被脏、壁胸膜转折部包绕",
      "各组成结构在肺根内的排列位置由上向下是肺静脉、肺动脉、主支气管",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "两侧肺根均与膈神经、心包膈血管、迷走神经和肺丛相邻",
        "肺根由出入肺门的肺动脉、肺静脉、支气管、支气管动静脉、淋巴管和神经被胸膜包绕而成；两肺根前方有膈神经和心包膈血管，后方有迷走神经，肺丛分支经肺根分布于肺。左肺根上方有主动脉弓跨过、后方为胸主动脉，右肺根前方为上腔静脉、后上方有奇静脉弓勾绕。原书第五节（肺）A1 型题第 3 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1018",
    order: 41,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关支气管肺段的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肺段间有结缔组织隔",
      "为一个一级支气管所分布",
      "肺段分界线在肺表面明显",
      "每一肺段组成一个肺小叶",
      "肺段内支气管与肺动脉、肺静脉的段支伴行",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺段间有结缔组织隔",
        "每一肺段有一个肺段支气管（三级支气管）分布；相邻肺段之间有少量疏松结缔组织相分隔，肺段分界线在肺表面不明显；肺段内肺动脉的段支与肺段支气管的分支伴行，而肺静脉属支段间静脉位于两肺段之间。原书第五节（肺）A1 型题第 4 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1019",
    order: 42,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关支气管血管的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "支气管动脉在肺门区均贴行于主支气管周缘",
      "两侧支气管动脉均直接起自胸主动脉",
      "支气管血管和肺血管在肺内无吻合支",
      "左、右侧各有2条支气管动脉",
      "支气管静脉均汇流入奇静脉",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "支气管动脉在肺门区均贴行于主支气管周缘",
        "支气管动脉起自胸主动脉或右肋间后动脉，与支气管的分支伴行入肺，在肺门区贴行于主支气管周缘；左侧通常 2 条、右侧通常 1 条；支气管静脉左侧注入半奇静脉、右侧注入奇静脉或上腔静脉；肺动脉与支气管动脉的终末支之间存在吻合。原书第五节（肺）A1 型题第 5 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1020",
    order: 43,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "有关肺的淋巴的叙述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "右上叶淋巴全部注入气管支气管上淋巴结",
      "肺的淋巴全部经与支气管伴行的集合淋巴管收集，行向肺门",
      "左上叶淋巴多注入主动脉弓淋巴结和动脉韧带淋巴结",
      "两肺下叶的淋巴均注入肺韧带淋巴结",
      "右中叶淋巴均注入气管支气管下淋巴结",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "右上叶淋巴全部注入气管支气管上淋巴结",
        "肺有浅、深两组淋巴管，浅组位于脏胸膜深面，深组位于各级支气管周围，两组在肺门处相互吻合，回流入支气管肺门淋巴结；答案以题集参考答案键号为准。原书第五节（肺）A1 型题第 6 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-a1021",
    order: 44,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肺的神经支配，不正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肺丛只分布于肺",
      "支配肺的神经包括感觉神经和运动神经，运动神经有交感和副交感两种",
      "肺的感觉神经与肺泡容积的调节有关",
      "肺前丛和肺后丛含有感觉、交感、副交感神经纤维",
      "肺的运动神经主要是支配肺血管和支气管的舒缩与腺体分泌",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肺丛只分布于肺",
        "肺由内脏神经支配，包括迷走神经和交感神经的分支，两者在肺根前、后方形成肺丛；副交感兴奋使支气管平滑肌收缩、血管扩张和腺体分泌，交感兴奋作用相反。原书第五节（肺）A1 型题第 7 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），9 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-short001",
    order: 45,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述女性乳房的淋巴回流。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "女性乳房淋巴管丰富，分为浅、深两组，两组之间存在吻合或交通，淋巴回流主要注入腋淋巴结。①乳房外侧部和中央部的淋巴管注入胸肌间淋巴结，这是乳房淋巴回流的主要途径；②乳房上部的淋巴管注入尖淋巴结和锁骨上淋巴结；③乳房内侧部的一部分淋巴管注入胸骨旁淋巴结，另一部分与对侧乳房淋巴管吻合；④深部的淋巴管注入胸肌间淋巴结或尖淋巴结；⑤乳房内下部的淋巴管注入膈上淋巴结前组，并通过腹壁和膈下的淋巴管与肝淋巴管交通。",
        "乳腺癌淋巴转移时可侵犯腋淋巴结和胸骨旁淋巴结；若淋巴回流受阻，肿瘤细胞可转移至对侧乳房或肝。原书第二节（胸壁）简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-short002",
    order: 46,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "根据肋间血管、神经的行程，简述胸膜腔穿刺进针的部位。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肋间后动脉、静脉和肋间神经在肋角至脊柱段走行时不恒定，为避免损伤肋间血管和神经，不宜在肋角内侧穿刺。肋间血管和神经在肋角和腋中线之间三者排列顺序有规律，自上而下为静脉、动脉、神经，行于肋沟内。因此，胸膜腔穿刺宜在肋角外侧于下位肋的上缘进针，但不宜紧靠肋骨上缘。在腋中线至胸骨之间，肋间前、后血管分为上、下支，分别沿肋上、下缘走行，该区穿刺应在肋间隙中部。临床常在肩胛线或腋后线第7、8肋间隙穿刺。",
        "穿刺进针部位的选择以避开肋间血管、神经为原则，故选肋角外侧、下位肋的上缘或肋间隙中部。原书第二节（胸壁）简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-short003",
    order: 47,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述膈食管裂孔的位置、结构特点和食管裂孔疝的关系。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "食管裂孔位于主动脉裂孔的左前方，约平对第10胸椎体，内有食管和迷走神经前、后干、胃左血管的食管支和来自肝后部的淋巴管通过。食管裂孔主要由右膈脚的肌束组成，部分肌纤维围绕食管形成肌环，对食管裂孔起钳制作用。在食管与裂孔之间连有膈食管韧带，有固定食管的作用。若该肌环和韧带发育不良或缺如，腹部器官可经食管裂孔突入胸腔，形成食管裂孔疝。",
        "食管裂孔的钳制机制依赖于右膈脚肌环与膈食管韧带，二者结构异常是食管裂孔疝发生的解剖学基础。原书第三节（膈）简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-short004",
    order: 48,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述胸腔和胸膜腔的异同。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸壁和膈围成胸腔。胸腔正中有纵隔，纵隔的两侧有肺及其表面的胸膜和胸膜腔。胸壁参与呼吸运动，胸腔内有呼吸系统和循环系统的主要器官。胸腔向上经胸廓上口与颈部相通，向下借膈与腹腔分隔。胸膜腔为脏、壁胸膜在肺根处相互延续围成，左、右各一，密闭，腔内负压，并有少量浆液。",
        "胸腔是容纳器官的骨肌性腔隙，与外界经胸廓上口相通；胸膜腔是脏、壁胸膜之间的密闭潜在性间隙，呈负压，二者概念不同。原书第四节（胸膜和胸膜腔）简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-short005",
    order: 49,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述从前至后上纵隔的结构。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "上纵隔的结构前层主要有胸腺，左、右头臂静脉和上腔静脉；中层有主动脉弓及其三大分支、膈神经和迷走神经；后层有食管、气管、胸导管和左喉返神经等。",
        "上纵隔器官从前向后分前、中、后三层，掌握各层内容有助于纵隔影像与手术入路的定位。原书第六节（纵隔）简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-short006",
    order: 50,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述气管胸部的毗邻。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "气管胸部前方从前向后依次有胸骨柄、胸骨甲状肌和胸骨舌骨肌的起始部、胸腺遗迹（小儿为胸腺）、左头臂静脉、主动脉弓及其分支（头臂干和左颈总动脉）和心丛等。后方邻食管，后外邻左喉返神经，右侧邻右头臂静脉、上腔静脉、奇静脉弓和右迷走神经，左侧邻左迷走神经和锁骨下动脉。",
        "气管胸部前方的重要毗邻是主动脉弓及其分支（头臂干、左颈总动脉），后方为食管，右侧有奇静脉弓勾绕。原书第六节（纵隔）简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-short007",
    order: 51,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述胸导管胸段的行程、毗邻及临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胸导管的胸段可分为上、下两段。上段在第4胸椎以上，此段胸导管在上升中逐渐偏左至第3胸椎处，于主动脉弓的上方、食管的左后方，左纵隔胸膜往往紧贴胸导管的左缘，因此上段胸导管损伤时，可出现左侧乳糜胸。下段相当于胸5～12椎体高度，该段位于脊柱和右肋间动脉之前，奇静脉与胸主动脉之间，食管的后方；右侧的纵隔胸膜在此段处于奇静脉和胸导管的前面，再转折到食管的后面，因此在胸导管下段受损时，淋巴可流入右胸膜腔，出现右侧乳糜胸。在后纵隔，胸导管的前方有食管，后方有右肋间后动脉、脊柱，左侧有胸主动脉，右侧有奇静脉和右纵隔胸膜；在上纵隔，胸导管的前方有左颈总动脉，后方有脊柱，左侧有左锁骨下动脉、左纵隔胸膜，右侧有食管、左喉返神经。",
        "胸导管上段损伤出现左侧乳糜胸、下段损伤出现右侧乳糜胸，是胸部手术中需重点保护的临床意义所在。原书第六节（纵隔）简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-short008",
    order: 52,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述奇静脉系的组成。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "奇静脉起自右腰升静脉，在右侧上升至第7～8胸椎高度，接受左侧的半奇静脉和副半奇静脉的横干。奇静脉达第4胸椎高度，形成奇静脉弓转向前行，跨越右肺根上方，注入上腔静脉。奇静脉沿途收纳食管、纵隔、心包和支气管来的静脉，还接受右侧的除第1肋间静脉以外的肋间后静脉的汇入。半奇静脉起自左腰升静脉，穿膈主动脉裂孔，上行于脊柱左前方，至第8胸椎平面转向右行注入奇静脉。副半奇静脉汇集左侧第4～7肋间静脉（上位其余肋间静脉由最上肋间静脉收集），有时收纳左主支气管静脉，副半奇静脉在脊柱左侧下行，于第7胸椎平面注入奇静脉。",
        "奇静脉系由奇静脉、半奇静脉和副半奇静脉组成，是沟通上、下腔静脉系的重要途径，也是胸膜腔积血、肿瘤等纵隔病变影像诊断的重要解剖基础。原书第六节（纵隔）简答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-short009",
    order: 53,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "肺肿瘤的首发症状可能发生声音嘶哑，其原因是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "由于喉返神经受损。胚胎发生时，左侧喉返神经由于其位置绕过左侧第6腮弓动脉被拉入胸腔，左侧第6腮弓动脉初为动脉导管，而后为动脉韧带存留。喉返神经在中纵隔的位置受许多外在因素的干扰，在支气管癌、食管癌或转移性癌侵入纵隔淋巴结时，该神经易受损害。此外，左侧喉返神经可受主动脉瘤影响而过度拉长，或受过度扩大的心脏而压向主动脉。这些都能麻痹声带主动肌，使声带不能紧张而处于弯曲或内收位，而引起声音嘶哑。",
        "左喉返神经经主动脉弓下方、动脉韧带后方绕行返至颈部，行程较长，易受纵隔病变牵拉或压迫而麻痹声带肌，故肺肿瘤累及纵隔时声音嘶哑常为首发症状。原书第六节（纵隔）简答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，6 组 × 共 16 个成员 */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b001",
    order: 54,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "乳房深部的淋巴管",
      "乳房上部的淋巴管",
      "乳房内侧部的一部分淋巴管",
      "乳房外侧部和中央部的淋巴管",
      "乳房内下部的淋巴管",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b001m1",
        order: 54,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "注入腋淋巴结的尖淋巴结和锁骨上淋巴结的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "乳房上部的淋巴管",
            "乳房上部的淋巴管注入尖淋巴结和锁骨上淋巴结。原书第二节（胸壁）B1 型题第 5 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b001m2",
        order: 55,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "注入胸骨旁淋巴结的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "乳房内侧部的一部分淋巴管",
            "乳房内侧部的一部分淋巴管注入胸骨旁淋巴结，另一部分与对侧乳房淋巴管吻合。原书第二节（胸壁）B1 型题第 6 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b002",
    order: 56,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "肋下动脉",
      "肋间后静脉",
      "肋间神经",
      "肋间后动脉",
      "肋下神经",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b002m1",
        order: 56,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "共有9对的结构是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肋间后动脉",
            "肋间后动脉共 11 对，其中起自胸主动脉者有 9 对（第3～11对），第1、2对起自肋颈干；肋下动脉仅 1 对。原书第二节（胸壁）B1 型题第 7 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b002m2",
        order: 57,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "共有11对的结构是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肋间神经",
            "肋间神经共 11 对（第1～11胸神经前支），第12胸神经前支称肋下神经。原书第二节（胸壁）B1 型题第 8 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b003",
    order: 58,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "thoracic duct（胸导管）",
      "esophagus（食管）",
      "inferior vena cava（下腔静脉）",
      "azygos vein（奇静脉）",
      "aorta（主动脉）",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b003m1",
        order: 58,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "穿过腔静脉孔的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "inferior vena cava（下腔静脉）",
            "腔静脉孔平第8胸椎，在正中线右侧2～3cm处，有下腔静脉通过。原书第三节（膈）B1 型题第 4 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b003m2",
        order: 59,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "穿过食管裂孔的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "esophagus（食管）",
            "食管裂孔平第10胸椎，有食管、迷走神经前干和后干、胃左血管的食管支和来自肝后部的淋巴管通过。原书第三节（膈）B1 型题第 5 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b004",
    order: 60,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "脏胸膜",
      "纵隔胸膜",
      "胸膜顶",
      "肋胸膜",
      "膈胸膜",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b004m1",
        order: 60,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "衬贴于胸内筋膜内面的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肋胸膜",
            "壁胸膜贴附于胸内筋膜内面的部分为肋胸膜。原书第四节（胸膜和胸膜腔）B1 型题第 7 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b004m2",
        order: 61,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "衬贴于纵隔侧面的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "纵隔胸膜",
            "壁胸膜贴附于纵隔侧面的部分为纵隔胸膜。原书第四节（胸膜和胸膜腔）B1 型题第 8 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b005",
    order: 62,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "左心房",
      "肺",
      "动脉韧带",
      "胸交感干",
      "胸腺",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b005m1",
        order: 62,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "位于动脉导管三角的结构有",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "动脉韧带",
            "动脉导管三角由左膈神经、左迷走神经和左肺动脉围成，内有动脉韧带、左喉返神经和心浅丛等结构。原书第六节（纵隔）B1 型题第 21 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b005m2",
        order: 63,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "属于上纵隔前层的结构有",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "胸腺",
            "上纵隔前层主要有胸腺，左、右头臂静脉和上腔静脉；中层有主动脉弓及其三大分支、膈神经和迷走神经；后层有食管、气管、胸导管和左喉返神经等。原书第六节（纵隔）B1 型题第 22 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b005m3",
        order: 64,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "同时走行在上纵隔和后纵隔的结构有",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "胸交感干",
            "胸交感干经胸廓上口入胸腔后纵行于脊柱两侧，同时走行于上纵隔与后纵隔。原书第六节（纵隔）B1 型题第 23 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b005m4",
        order: 65,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "不属于纵隔内的器官是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肺",
            "纵隔是左、右纵隔胸膜之间所有器官和结构的总称，肺位于纵隔两侧的胸腔内，不属于纵隔内容。原书第六节（纵隔）B1 型题第 24 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b006",
    order: 66,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "奇静脉弓",
      "右主支气管",
      "主动脉弓",
      "左心房",
      "奇静脉",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b006m1",
        order: 66,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "位于食管前方的结构有",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "左心房",
            "食管胸部前方毗邻气管、左主支气管、左心房、心包和膈等结构，其中下段前方邻左心房。原书第六节（纵隔）B1 型题第 25 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b006m2",
        order: 67,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "位于食管后方的结构有",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "奇静脉",
            "食管胸部后方毗邻奇静脉、胸导管、胸主动脉及右肋间后动脉等结构。原书第六节（纵隔）B1 型题第 26 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b006m3",
        order: 68,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "位于食管右侧的结构有",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "奇静脉弓",
            "食管胸部右侧毗邻奇静脉弓（奇静脉弓跨右肺根上方勾绕），右纵隔胸膜亦位于其右侧。原书第六节（纵隔）B1 型题第 27 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch03-thorax-b006m4",
        order: 69,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "位于食管左侧的结构有",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "主动脉弓",
            "食管胸部左侧毗邻主动脉弓及胸主动脉、左纵隔胸膜等结构。原书第六节（纵隔）B1 型题第 28 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
