import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 局部解剖学学习指导与习题集 — 第8章 下肢 题库提取（等比取样）
 * 来源：《局部解剖学学习指导与习题集》（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：13 题
 * - 选择题（a1-single）：34 题（含 A1 型 31 题、A2 型病例题 3 题）
 * - 问答题（short-answer）：16 题（简答）
 * - B1 配伍题：3 组、共 8 个成员
 * - 独立记分题合计：71 题（须等于本文件预算 71）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书各节（第一节概述、第二节臀部、第三节股部、第四节膝部、第五节小腿部、
 *   第六节踝和足部）依序含名词解释、选择题（A1/A2/B1）与简答题，各节习题与参考答案
 *   独立；本文件按 71 道预算在原书顺序内取材：名词解释全取 13 题（概述 2、臀部 2、
 *   股部 4、膝部 1、踝和足部 4）；简答题全取 16 题（概述 2、臀部 2、股部 3、膝部 2、
 *   小腿部 3、踝和足部 4）；选择题（A1+A2）与 B1 组成员按源题量占比（源 A1+A2 共
 *   67 题、B1 共 6 组 18 成员）分配剩余 42 道预算——B1 型取完整组 3 组共 8 成员
 *   （臀部 7～8 题、臀部 9～10 题、股部 33～36 题），A1+A2 型取 34 题（概述 A1 第
 *   1–2 题、臀部 A1 第 1–3 题与 A2 第 4–6 题、股部 A1 第 1–26 题）；未纳入的题因
 *   预算所限（股部 A1 第 27–30 题、A2 第 31–32 题及 B1 组 37–40 题，膝部 A1 第
 *   1–3 题，小腿部 A1 第 1–10 题、A2 第 11–12 题及 B1 组 13–15 题，踝和足部 A1
 *   第 1–11 题、A2 第 12 题及 B1 组 13–15 题）。正确项对齐各节参考答案键号（概述
 *   A1 1.D/2.E；臀部 A1 1.B/2.A/3.D、A2 4.D/5.C/6.D、B1 7.A/8.C/9.A/10.E；
 *   股部 A1 1.B、2.B、3.C、4.D、5.A、6.B、7.B、8.D、9.C、10.D、11.B、12.B、
 *   13.D、14.E、15.C、16.A、17.D、18.C、19.A、20.B、21.D、22.E、23.D、24.E、
 *   25.D、26.E、B1 33.B/34.A/35.C/36.E），选项与共用备选答案已随机重排并同步
 *   correctChoiceIndex。OCR 错字已按局部解剖学医学语义恢复（如 颈于角→颈干角、
 *   位体→体位、隐靜脉裂孔→隐静脉裂孔、膕/胭窝→腘窝、胭动脉→腘动脉、胭静脉→腘静脉、
 *   骼胫束→髂胫束、骼前上棘→髂前上棘、骼耻弓→髂耻弓、坐骨肌门窝→坐骨肛门窝、
 *   股肉侧浅静脉→股内侧浅静脉、腹橫筋膜→腹横筋膜、腱滇→跖腱膜、肋骨间隙→跖骨间隙、
 *   排总神经→腓总神经、届肌支持带→屈肌支持带、足号→足弓、蚂状肌→蚓状肌；股部 A1
 *   第 18 题选项 C 依本节简答参考答案恢复为“起自股动脉后外侧，行于长收肌和大收肌
 *   之间”），数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "topographic-anatomy-ch08-lower-limb";
const locatorBase =
  "《局部解剖学学习指导与习题集》 第8章 下肢 习题（核对PDF 第166–187页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），13 道（概述 2 + 臀部 2 + 股部 4 + 膝部 1 + 踝和足部 4，全取） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：颈干角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "股骨颈与股骨体长轴之间向内的夹角为颈干角，正常成人125°～130°（平均约127°）。大于此范围为髋外翻，小于此范围为髋内翻。",
        "颈干角是股骨颈与股骨体长轴之间向内的夹角，其大小影响髋关节的力学关系，过大为髋外翻、过小为髋内翻。原书第一节（概述）名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：膝外翻角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "股骨体长轴线与胫骨长轴线在膝关节处相交形成向外的夹角，正常约170°，其补角称膝外翻角，男性略小于女性。若外侧夹角小于170°为膝外翻（“X”形腿），大于170°为膝内翻（呈“O”形腿或“弓”形腿）。",
        "膝外翻角是膝部重要的对比关系指标，其大小反映膝关节的内外翻状态。原书第一节（概述）名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：臀筋膜",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "臀筋膜是臀部深筋膜。其上部与髂嵴骨膜愈着，在臀大肌上缘分两层包裹臀大肌，并向臀大肌肌束间发出许多纤维小隔分隔肌束。内侧部愈着于骶骨背面骨膜，外侧部移行于阔筋膜张肌，并参与形成坚韧的髂胫束。臀筋膜损伤是腰腿痛的病因之一。",
        "臀筋膜是臀部深筋膜，重点在于与髂嵴骨膜、骶骨背面骨膜愈着及外侧移行参与形成髂胫束。原书第二节（臀部）名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：臀部十字吻合",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "臀部十字吻合是位于臀大肌深面、股方肌与大转子附近的动脉网，由两侧的旋股内、外侧动脉，上部的臀上、下动脉，下部的股深动脉第1穿动脉等组成。",
        "臀部十字吻合是髋周围动脉网的重要组成，构成骨盆与股部之间的侧支循环通路。原书第二节（臀部）名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：阔筋膜",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阔筋膜即股部深筋膜，或称大腿固有筋膜。上方附于腹股沟韧带及髂嵴，与臀筋膜和会阴筋膜相续；下方与小腿筋膜和腘筋膜相续。阔筋膜坚韧致密，为全身最厚的深筋膜，其在大腿外侧明显增厚形成扁带状的髂胫束。",
        "阔筋膜为全身最厚的深筋膜，其外侧部增厚形成髂胫束，并在腹股沟韧带中、内1/3交点下方形成隐静脉裂孔（卵圆窝）。原书第三节（股部）名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肌腔隙",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肌腔隙是腹股沟韧带与髋骨间被髂耻弓分隔的外侧部腔隙：其前界为腹股沟韧带外侧部，后外侧界为髂骨，内侧界为髂耻弓；内有髂腰肌、股神经和股外侧皮神经通过。",
        "肌腔隙与血管腔隙以髂耻弓为界，肌腔隙通行髂腰肌、股神经和股外侧皮神经，血管腔隙通行股血管。原书第三节（股部）名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：血管腔隙",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血管腔隙是腹股沟韧带与髋骨间被髂耻弓分隔的内侧部腔隙：前界为腹股沟韧带内侧部，后界为耻骨肌筋膜及耻骨梳韧带，内侧界为腔隙韧带（陷窝韧带），外侧界为髂耻弓。腔隙内有股鞘及其包含的股动、静脉，生殖股神经股支和淋巴结。",
        "血管腔隙是股血管进入股部的通道，股疝亦经血管腔隙内侧的股环突出。原书第三节（股部）名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：隐静脉裂孔",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "隐静脉裂孔又称卵圆窝，为腹股沟韧带中、内1/3交点下方约1横指处阔筋膜的卵圆形薄弱区。其表面覆盖一层疏松结缔组织称筛筋膜，有大隐静脉及其属支穿入并汇入股静脉。",
        "隐静脉裂孔是阔筋膜的薄弱区，大隐静脉经此穿筛筋膜汇入股静脉，也是股疝好发部位之一。原书第三节（股部）名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：鹅足囊",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "膝前区的深筋膜是阔筋膜的延续，并与其深面的肌腱融合。其内侧部有缝匠肌腱、股薄肌腱和半腱肌腱共同形成的“鹅足”，其深面有一较大的滑液囊，称“鹅足囊”。",
        "鹅足由缝匠肌、股薄肌、半腱肌三腱止点汇合形成，鹅足囊即其深面的滑液囊。原书第四节（膝部）名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：分裂韧带",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "内踝后下方与跟骨内侧面之间的深筋膜增厚，形成屈肌支持带，又称分裂韧带，它与内踝、跟骨内侧面之间共同构成踝管。",
        "分裂韧带即屈肌支持带，与内踝、跟骨内侧面共同围成踝管。原书第六节（踝和足部）名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：内侧纵弓",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "内侧纵弓由跟骨、距骨、足舟骨、第1～3楔骨和第1～3跖骨及其间的连结构成。",
        "内侧纵弓是足弓中较高的一弓，主要由胫骨后肌腱、趾长屈肌腱、𧿹长屈肌腱、足底方肌、足底腱膜及跟舟足底韧带等结构维持。原书第六节（踝和足部）名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：足弓",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "足弓是由跗骨与跖骨借韧带、关节连结而成，可分内、外侧纵弓及横弓。足弓是人体直立、行走及负重时的装置，其弹性能缓冲地面对身体所产生的震荡，同时还有保护足底血管、神经免受压迫的作用。当足弓的结构发育不良或受损，可引起足弓塌陷，导致扁平足。",
        "足弓分为内侧纵弓、外侧纵弓和横弓，具有缓冲震荡与保护足底血管神经的作用，足弓塌陷即形成扁平足。原书第六节（踝和足部）名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-term013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：踝管",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "踝管由屈肌支持带（又称分裂韧带）与内踝、跟骨内侧面之间共同构成。支持带向深部发出三个纤维隔，将踝管分隔成四个骨纤维性管。其内容纳的结构由前向后依次有：①胫骨后肌腱；②趾长屈肌腱；③胫后动、静脉及胫神经；④𧿹长屈肌腱。上述各肌腱均被有腱鞘。踝管内有疏松结缔组织，是小腿后区通向足底的重要路径。踝后区的外伤、出血或肿胀均可压迫踝管内容物，引起踝管综合征。",
        "踝管内容纳结构由前向后依次为胫骨后肌腱、趾长屈肌腱、胫后动静脉及胫神经、𧿹长屈肌腱，掌握其排列顺序对踝管综合征的诊断有重要意义。原书第六节（踝和足部）名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），34 道（概述 A1 2 + 臀部 A1 3/A2 3 + 股部 A1 26） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1001",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "Nelaton线是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "大转子尖与坐骨结节的连线",
      "髂后上棘与坐骨结节的连线",
      "髂前上棘与坐骨结节的连线",
      "髂后下棘与大转子尖的连线",
      "髂前上棘与大转子尖的连线",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "髂前上棘与坐骨结节的连线",
        "Nelaton线是侧卧、髋关节屈90°～120°时自坐骨结节至髂前上棘的连线，正常时该线通过股骨大转子尖。原书第一节（概述）A1 型题第 1 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1002",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "坐骨结节最易触及的体位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "侧卧位",
      "屈髋位",
      "仰卧位",
      "俯卧位",
      "站立位",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "屈髋位",
        "屈髋时臀大肌松弛，坐骨结节最易触及。原书第一节（概述）A1 型题第 2 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1003",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "穿经梨状肌上孔的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "阴部内动脉",
      "臀上动脉",
      "坐骨神经",
      "阴部神经",
      "臀下动脉",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "臀上动脉",
        "梨状肌上孔穿经的结构自外侧向内侧依次为臀上神经、臀上动脉和臀上静脉。原书第二节（臀部）A1 型题第 1 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1004",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "出入梨状肌下孔的结构中，位于最外侧的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "股后皮神经",
      "阴部神经",
      "坐骨神经",
      "臀下血管",
      "阴部血管",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "坐骨神经",
        "梨状肌下孔穿经的结构自外侧向内侧依次为坐骨神经、股后皮神经、臀下神经、臀下动、静脉、阴部内动、静脉和阴部神经，最外侧者为坐骨神经。原书第二节（臀部）A1 型题第 2 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1005",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "穿经坐骨小孔的动脉是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "髂内动脉",
      "闭孔动脉",
      "臀上动脉",
      "阴部内动脉",
      "臀下动脉",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阴部内动脉",
        "阴部内动、静脉和阴部神经自梨状肌下孔最内侧穿出后，越过骶棘韧带，经坐骨小孔进入坐骨肛门窝，分布于会阴部。原书第二节（臀部）A1 型题第 3 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1006",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "某患者臀部注射后，上楼抬腿困难，检查发现小腿外侧、足背和足底皮肤感觉减弱，可能损伤了",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "阴部神经",
      "臀上神经",
      "股后皮神经",
      "坐骨神经",
      "臀下神经",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "坐骨神经",
        "臀部注射位置不当可损伤坐骨神经，表现为小腿肌群瘫痪（上楼抬腿困难）及小腿外侧、足背和足底皮肤感觉减弱。原书第二节（臀部）A2 型题第 4 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1007",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "男性，50岁，行会阴部皮肤肿物切除术，医生将麻醉药注入患侧坐骨棘处，几分钟后患者感觉会阴部麻木，其麻醉的神经是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "臀下神经",
      "坐骨神经",
      "臀上神经",
      "阴部神经",
      "股后皮神经",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阴部神经",
        "阴部神经绕坐骨棘经坐骨小孔进入坐骨肛门窝，临床常在坐骨棘处行阴部神经阻滞麻醉，麻醉后出现会阴部麻木。原书第二节（臀部）A2 型题第 5 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1008",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt:
      "女性，45岁，因腰腿疼就医。检查发现其梨状肌肿胀压迫坐骨神经，表现为梨状肌损伤综合征，该患者会出现感觉障碍的部位是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "小腿内侧面",
      "臀部",
      "股后区",
      "小腿外侧面",
      "股前内侧区",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "小腿外侧面",
        "梨状肌肿胀压迫坐骨神经时，以腓总神经成分受累多见，出现小腿外侧面（腓浅、深神经分布区）感觉障碍。原书第二节（臀部）A2 型题第 6 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1009",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于大隐静脉的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "经髌骨内缘上行",
      "与小隐静脉间无交通支",
      "经内踝前方与隐神经伴行",
      "全长与隐神经伴行",
      "在大腿部与隐神经伴行",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "经内踝前方与隐神经伴行",
        "大隐静脉起于足背静脉弓内侧，经内踝前方约1cm处上行至小腿前内侧，此段与隐神经伴行，并非全长伴行；其属支与隐神经关系亦不同。原书第三节（股部）A1 型题第 1 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1010",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下肢最长、瓣膜最多的浅静脉是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胫后静脉",
      "股静脉",
      "腘静脉",
      "大隐静脉",
      "小隐静脉",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "大隐静脉",
        "大隐静脉是全身最长的浅静脉，起于足背静脉弓内侧，经内踝前方、小腿前内侧、膝内侧上行至大腿前内侧，于隐静脉裂孔处汇入股静脉，属支多、瓣膜多。原书第三节（股部）A1 型题第 2 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1011",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "大隐静脉的属支不包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "旋髂浅静脉",
      "股内侧浅静脉",
      "腹壁浅静脉",
      "阴部内浅静脉",
      "股外侧浅静脉",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "阴部内浅静脉",
        "大隐静脉有五条属支：旋髂浅静脉、腹壁浅静脉、阴部外静脉、股内侧浅静脉和股外侧浅静脉，不包括阴部内浅静脉。原书第三节（股部）A1 型题第 3 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1012",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于腹股沟浅淋巴结的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "分三群位于腹股沟韧带下方",
      "上组沿腹壁浅静脉排列",
      "位于大隐静脉末端周围",
      "下群位于腹股沟韧带下方",
      "下群沿大隐静脉近侧段两侧纵行排列",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "下群沿大隐静脉近侧段两侧纵行排列",
        "腹股沟浅淋巴结分上、下两群：上群（斜群）斜行排列于腹股沟韧带下方，下群（纵群）沿大隐静脉末段（近侧段）两侧纵行排列。原书第三节（股部）A1 型题第 4 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1013",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "隐静脉裂孔",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "有隐神经通过",
      "内侧缘明显而锐利",
      "位于髂前上棘下方3cm处",
      "上端与耻骨肌筋膜相续",
      "是阔筋膜的薄弱处",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "是阔筋膜的薄弱处",
        "隐静脉裂孔（卵圆窝）是腹股沟韧带中、内1/3交点下方约1横指处阔筋膜的卵圆形薄弱区，表面覆有筛筋膜，有大隐静脉及其属支穿入汇入股静脉。原书第三节（股部）A1 型题第 5 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1014",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "小隐静脉",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "经外踝前方向上与腓浅神经伴行",
      "在腘窝与腓总神经伴行",
      "全长与腓肠内侧皮神经伴行",
      "经外踝后方于小腿后面正中上行",
      "在腘窝中点穿深筋膜注入腘静脉",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "经外踝后方于小腿后面正中上行",
        "小隐静脉起于足背静脉弓外侧端，伴腓肠神经绕外踝后方于小腿后区正中线上行，至腘窝下角处穿腘筋膜入腘窝，汇入腘静脉。原书第三节（股部）A1 型题第 6 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1015",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "隐神经",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "与小隐静脉伴行",
      "在股部与大隐静脉伴行",
      "是腰丛的分支",
      "在收肌管内，行于股血管前方",
      "经腘窝至小腿",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "在收肌管内，行于股血管前方",
        "隐神经是股神经最长的皮神经，入收肌管后行于股动脉前方（收肌管前方为股神经的股内侧肌肌支和隐神经，中间为股动脉），在膝关节内侧穿出，伴大隐静脉下行至小腿内侧及足内侧缘。原书第三节（股部）A1 型题第 7 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1016",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于股环结构错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "后侧界为耻骨梳韧带",
      "为股管的上口",
      "外侧界为阔筋膜",
      "前界是腹股沟韧带",
      "内界为陷窝韧带（腔隙韧带）",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "外侧界为阔筋膜",
        "股环为股管的上口，其前界为腹股沟韧带，后界为耻骨梳韧带，内侧界为腔隙韧带（陷窝韧带），外侧界为股静脉内侧的纤维隔，而非阔筋膜，故“外侧界为阔筋膜”表述错误。原书第三节（股部）A1 型题第 8 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1017",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "通过肌腔隙的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "股动脉与股静脉",
      "股鞘与股管",
      "股深淋巴结",
      "股神经与髂腰肌",
      "隐神经与大隐静脉",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "股神经与髂腰肌",
        "肌腔隙内有髂腰肌、股神经和股外侧皮神经通过；股动、静脉经血管腔隙通行。原书第三节（股部）A1 型题第 9 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1018",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在股三角内位于最外侧的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "大隐静脉",
      "股深淋巴结",
      "股静脉",
      "股动脉",
      "股神经",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "股神经",
        "股三角的内容由外侧向内侧依次为股神经、股鞘（股动脉、股静脉）、股管及股深淋巴结和脂肪等，位于最外侧者为股神经。原书第三节（股部）A1 型题第 10 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1019",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "血管腔隙",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "位于髂耻弓的外侧",
      "有闭孔血管通过",
      "有股神经与髂腰肌通过",
      "有股动、静脉通过",
      "有股血管与股神经通过",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "有股动、静脉通过",
        "血管腔隙为髂耻弓内侧的腔隙，内有股鞘及其包含的股动、静脉、生殖股神经股支和淋巴结；股神经经肌腔隙通过。原书第三节（股部）A1 型题第 11 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1020",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肌腔隙与血管腔隙位于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "耻骨梳韧带与髂骨之间",
      "腹股沟韧带与耻骨梳之间",
      "髂耻弓与腔隙韧带之间",
      "腹股沟韧带与髂骨之间",
      "腹股沟韧带与髋骨之间",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腹股沟韧带与髋骨之间",
        "腹股沟韧带与髋骨之间被髂耻弓分隔成外侧的肌腔隙和内侧的血管腔隙。原书第三节（股部）A1 型题第 12 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1021",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "组成股三角境界的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "腹股沟韧带、腹直肌和缝匠肌",
      "腹股沟韧带、大收肌和缝匠肌",
      "腹股沟韧带、耻骨肌和缝匠肌",
      "腹股沟韧带、长收肌和股薄肌",
      "腹股沟韧带、长收肌和缝匠肌",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腹股沟韧带、长收肌和缝匠肌",
        "股三角上界为腹股沟韧带，外下界为缝匠肌内侧缘，内下界为长收肌内侧缘。原书第三节（股部）A1 型题第 13 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1022",
    order: 35,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于股三角的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "内下界为长收肌内侧缘",
      "上界为腹股沟韧带",
      "后壁是股四头肌与耻骨肌及其筋膜",
      "外下界为缝匠肌内侧缘",
      "前壁是阔筋膜",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "后壁是股四头肌与耻骨肌及其筋膜",
        "股三角的后壁（底）自外侧向内侧为髂腰肌、耻骨肌和长收肌及其筋膜，而非股四头肌与耻骨肌及其筋膜，故该表述错误。原书第三节（股部）A1 型题第 14 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1023",
    order: 36,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于股三角的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "内有隐神经",
      "位于股部上1/2处",
      "内有大隐静脉",
      "由腹股沟韧带、缝匠肌、长收肌围成",
      "位于阔筋膜与髂腰肌之间",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "由腹股沟韧带、缝匠肌、长收肌围成",
        "股三角位于股前内侧区上1/3部，由腹股沟韧带、缝匠肌内侧缘和长收肌内侧缘围成，呈倒三角形凹陷，向下与收肌管相续。原书第三节（股部）A1 型题第 15 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1024",
    order: 37,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "股三角内容物由内向外的排列关系是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "股动脉、股静脉、股神经",
      "股神经、闭孔神经、股动脉、股静脉",
      "股静脉、股神经、闭孔神经、股动脉",
      "股静脉、股动脉、股神经",
      "闭孔神经、股神经、股静脉、股动脉",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "股静脉、股动脉、股神经",
        "股三角内容物由外侧向内侧依次为股神经、股动脉、股静脉、股管，故由内向外依次为股静脉、股动脉、股神经。原书第三节（股部）A1 型题第 16 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1025",
    order: 38,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "股三角内结构不含",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "股静脉及其属支",
      "股深血管",
      "大隐静脉及其属支",
      "股动脉及其分支",
      "股神经及其分支",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "大隐静脉及其属支",
        "股三角内容为股神经、股鞘及其包含的股动脉、股静脉、股管及股深淋巴结和脂肪等；大隐静脉行于浅筋膜内，不属于股三角内容。原书第三节（股部）A1 型题第 17 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1026",
    order: 39,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "股深动脉",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "发出旋髂浅、深动脉",
      "平腹股沟韧带起自股动脉",
      "下行于股动脉前方",
      "起自股动脉后外侧，行于长收肌和大收肌之间",
      "发出阴部外动脉",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "起自股动脉后外侧，行于长收肌和大收肌之间",
        "股深动脉是股动脉的最大分支，于腹股沟韧带下方3～5cm处起自股动脉后外侧，向内下行于长收肌和大收肌之间，沿途发出旋股内、外侧动脉及数条穿动脉等。原书第三节（股部）A1 型题第 18 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1027",
    order: 40,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "股静脉在股三角内",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "沿股动脉内侧上行",
      "收纳腹壁浅静脉",
      "经股动脉与股神经间上行",
      "通过股鞘外侧部",
      "通过股鞘内侧部",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "通过股鞘内侧部",
        "股静脉在股三角内位于股动脉内侧，经股鞘内侧部上行，收纳大隐静脉等属支；参考答案键号为 A。原书第三节（股部）A1 型题第 19 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1028",
    order: 41,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "股鞘",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "与肌腔隙相通",
      "包绕股血管与股神经",
      "有两个腔",
      "与腹部筋膜无关",
      "包绕股血管与股深淋巴管",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "包绕股血管与股深淋巴管",
        "股鞘为腹横筋膜及髂筋膜的延续，呈漏斗形，长3～4cm，包绕股动、静脉上段及其中的淋巴结构；参考答案键号为 B。原书第三节（股部）A1 型题第 20 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1029",
    order: 42,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "股鞘内容从内侧向外侧为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "股动脉、股静脉、股神经",
      "股动脉、股静脉、股深淋巴结",
      "股深淋巴结、股动脉、股静脉",
      "股深淋巴结、股静脉、股动脉",
      "股静脉、股动脉、股神经",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "股深淋巴结、股静脉、股动脉",
        "股鞘内三个腔自内侧向外侧依次为股管（内有腹股沟深淋巴结和脂肪）、股静脉、股动脉。原书第三节（股部）A1 型题第 21 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1030",
    order: 43,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于股管的描述，正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "内有股静脉",
      "上口为股环，下口为隐静脉裂孔",
      "内有大隐静脉",
      "内有股神经",
      "是一盲管，内有腹股沟深淋巴结",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "是一盲管，内有腹股沟深淋巴结",
        "股管长约1.3cm，下端为盲端，上口称股环；股管内有1～2个腹股沟深淋巴结和脂肪组织。原书第三节（股部）A1 型题第 22 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1031",
    order: 44,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "股疝容易发生嵌顿是由于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "股鞘坚硬",
      "股管过于狭窄",
      "下端为盲端",
      "卵圆窝的镰状缘锐利",
      "股环周围组织缺乏伸展性",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "股环周围组织缺乏伸展性",
        "股环周围结构坚韧且缺乏伸展性（后界耻骨梳韧带、内侧界腔隙韧带等均较坚硬），故股疝易发生嵌顿。原书第三节（股部）A1 型题第 23 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1032",
    order: 45,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于收肌管的描述，错误的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "位于股前区中1/3段，长约15cm",
      "外侧壁为股内侧肌",
      "前壁是缝匠肌及大收肌腱板",
      "其上口与股三角尖端不相通",
      "后壁为大收肌及长收肌",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "其上口与股三角尖端不相通",
        "收肌管（Hunter管）位于股中1/3段前内侧，长15～17cm，上口与股三角尖相通，下口为收肌腱裂孔，故“上口与股三角尖端不相通”表述错误。原书第三节（股部）A1 型题第 24 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1033",
    order: 46,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "穿收肌管的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "股血管与股神经",
      "闭孔血管与闭孔神经",
      "隐神经与大隐静脉",
      "股深血管与隐神经",
      "隐神经与股动、静脉",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "隐神经与股动、静脉",
        "收肌管内通过股神经的股内侧肌肌支和隐神经、股动脉、股静脉及淋巴管和疏松结缔组织，大隐静脉不穿收肌管。原书第三节（股部）A1 型题第 25 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-a1034",
    order: 47,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "收肌管内的结构由前向后有",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "股神经、股动脉、股静脉",
      "股动脉、股静脉、股神经",
      "隐神经、股静脉、股动脉",
      "股静脉、股动脉、股神经",
      "隐神经、股动脉、股静脉",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "隐神经、股动脉、股静脉",
        "收肌管内结构由前向后依次为股神经的股内侧肌肌支和隐神经（前方）、股动脉（中间）、股静脉（后方）。原书第三节（股部）A1 型题第 26 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），16 道（概述 2 + 臀部 2 + 股部 3 + 膝部 2 + 小腿部 3 + 踝和足部 4，全取） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short001",
    order: 48,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述Kaplan点及其意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "仰卧，两下肢并拢伸直，两侧髂前上棘处于同一水平面时，自两侧大转子尖经过同侧髂前上棘作延长线，正常时两侧延长线相交于脐或脐以上，相交点称Kaplan点。髋关节脱位或股骨颈骨折时，此点偏移至脐下并偏向健侧。",
        "Kaplan点是判断髋关节脱位或股骨颈骨折的体表对比标志，正常时相交于脐或脐以上，病变时偏移至脐下并偏向健侧。原书第一节（概述）简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short002",
    order: 49,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述坐骨神经的体表投影。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "坐骨神经出盆腔的投影点位于髂后上棘至坐骨结节连线中点外侧2～3cm处。坐骨神经干的体表投影为股骨大转子与坐骨结节连线的中、内1/3交点至股骨内、外侧髁之间中点之连线。",
        "坐骨神经体表投影由出盆腔点和神经干两点定位，是臀部注射及坐骨神经阻滞麻醉的解剖学依据。原书第一节（概述）简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short003",
    order: 50,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述梨状肌下孔穿行的结构、走行及分布。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "梨状肌下孔穿经的结构自外侧向内侧依次为坐骨神经、股后皮神经、臀下神经、臀下动、静脉、阴部内动、静脉和阴部神经。其中内侧的阴部内动、静脉和阴部神经自梨状肌下孔穿出后，越过骶棘韧带，经坐骨小孔进入坐骨肛门窝，分布于会阴部的结构。",
        "梨状肌下孔的排列关系（自外向内）是臀部考查重点，掌握阴部内血管神经经坐骨小孔入坐骨肛门窝的走行对会阴麻醉有意义。原书第二节（臀部）简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short004",
    order: 51,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述臀肌间隙脓肿可能蔓延的通道和部位。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "在臀肌之间，由于血管神经的穿行或疏松组织的填充，形成许多间隙。这些间隙形成感染蔓延的通道。其中，臀大肌深面的间隙较广泛，可沿梨状肌上、下孔通盆腔，借坐骨小孔通坐骨肛门窝，沿坐骨神经到达大腿后面。",
        "臀肌间隙借梨状肌上、下孔及坐骨小孔与盆腔、坐骨肛门窝及大腿后面相通，是感染蔓延的解剖学通道。原书第二节（臀部）简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short005",
    order: 52,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述股三角内结构及其位置关系和临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "股三角内的结构由外侧向内侧依次为股神经、股鞘及其包含的股动脉、股静脉、股管及股深淋巴结和脂肪等。股动脉居中，于腹股沟韧带中点深面，由髂外动脉延续而成。外侧为股神经，内侧为股静脉。此种关系可便于股动脉压迫止血，并有利于股动、静脉穿刺及股神经麻醉时的定位。",
        "股三角内自外向内为股神经、股动脉、股静脉、股管，股动脉居中这一关系是股动脉压迫止血及股动、静脉穿刺定位的解剖学基础。原书第三节（股部）简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short006",
    order: 53,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "股动脉在股三角内的分支有哪些？分布如何？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "股动脉起始处发三条浅动脉：腹壁浅动脉、旋髂浅动脉、阴部外动脉，分布于相应区域；股动脉的最大分支为股深动脉，其于腹股沟韧带下方3～5cm处起自股动脉的后外侧，向内下行于长收肌和大收肌之间，沿途发出旋股内、外侧动脉、数条穿动脉及肌支，同时参与髋周围及膝关节动脉网的组成。",
        "股动脉在股三角内的分支包括三条浅动脉和最大的分支股深动脉，股深动脉的分支参与髋周围及膝关节动脉网。原书第三节（股部）简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short007",
    order: 54,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述收肌管的交通和内容。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "上口与股三角尖相通，下口为收肌腱裂孔，通腘窝上角，所以收肌管又称股腘管。股三角或腘窝的炎症，可借此互相蔓延。收肌管内通过的结构，前方为股神经的股内侧肌肌支和隐神经，中间为股动脉；后方为股静脉以及淋巴管和疏松结缔组织。",
        "收肌管上通股三角、下通腘窝，是股三角与腘窝间炎症蔓延的通道；管内结构由前向后为隐神经及股内侧肌肌支、股动脉、股静脉。原书第三节（股部）简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short008",
    order: 55,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "腘窝内由浅入深有哪些结构？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腘窝内含有重要的血管和神经，由浅至深依次为胫神经、腘静脉和腘动脉。其外上还有腓总神经，血管周围还有腘深淋巴结。",
        "腘窝内容由浅至深依次为胫神经、腘静脉、腘动脉，腓总神经沿股二头肌腱内侧缘行向外下绕腓骨颈。原书第四节（膝部）简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short009",
    order: 56,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述膝关节动脉网的组成、来源及其临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "膝关节的血供十分丰富，由股动脉、腘动脉、胫前动脉和股深动脉的多个分支在膝关节周围吻合形成动脉网。主要有旋股外侧动脉降支、膝降动脉、膝上内侧动脉、膝上外侧动脉、膝中动脉、膝下内侧动脉、膝下外侧动脉、股深动脉的第3穿动脉和胫前返动脉。膝关节动脉网不仅能保证供给膝关节的营养，而且动脉损伤或栓塞时，可成为侧支循环的重要途径，以保证下肢远端的血供。",
        "膝关节动脉网由股动脉、腘动脉、胫前动脉和股深动脉的多个分支吻合形成，是膝关节营养和下肢侧支循环的重要保证。原书第四节（膝部）简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short010",
    order: 57,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述小腿的界线和分区。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "小腿上界为平胫骨粗隆的环形线，下界为内、外踝基部的环形连线。经内、外踝的垂线，可将小腿分为小腿前外侧区和小腿后区。",
        "小腿以平胫骨粗隆的环形线为上界、内、外踝基部环形连线为下界，经内、外踝的垂线分为前外侧区和后区。原书第五节（小腿部）简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short011",
    order: 58,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述胫前动脉的走行。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胫前动脉于腘肌下缘由腘动脉分出后，即向前穿骨间膜，进入小腿前骨筋膜鞘，紧贴骨间膜前面，伴腓深神经下行。上1/3段位于胫骨前肌和趾长伸肌之间，下2/3段位于胫骨前肌和𧿹长伸肌之间。主干下行至伸肌上支持带下缘处，移行为足背动脉。",
        "胫前动脉穿骨间膜入前骨筋膜鞘，伴腓深神经下行，上1/3段位于胫骨前肌与趾长伸肌之间、下2/3段位于胫骨前肌与𧿹长伸肌之间，终末移行为足背动脉。原书第五节（小腿部）简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short012",
    order: 59,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述腓肠神经的走行及分布。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腓肠神经多由腓肠内侧皮神经（来自胫神经）和腓肠外侧皮神经（来自腓总神经）于小腿后区下部吻合而成，穿出深筋膜后，经外踝后方达足背外侧，分布于小腿后区下部及足背外侧的皮肤。",
        "腓肠神经由腓肠内侧、外侧皮神经在小腿后区下部吻合而成，伴小隐静脉走行，分布于小腿后区下部及足背外侧皮肤。原书第五节（小腿部）简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short013",
    order: 60,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述内外侧纵弓的构成及维持结构。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "内侧纵弓较高，由跟骨、距骨、足舟骨、第1～3楔骨和第1～3跖骨及其间的连结共同组成。主要由胫骨后肌腱、趾长屈肌腱、𧿹长屈肌腱、足底方肌、足底腱膜及跟舟足底韧带等结构所维持。外侧纵弓较低，由跟骨、骰骨、第4、5跖骨及其间的连结共同组成。主要由腓骨长肌腱、足底长韧带及跟骰足底韧带等结构所维持。",
        "内侧纵弓较高、外侧纵弓较低，二者构成骨性不同、维持结构不同，腓骨长肌腱是维持外侧纵弓的重要结构。原书第六节（踝和足部）简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short014",
    order: 61,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "说明踝管的组成及经过踝管的结构。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "踝管由屈肌支持带（又称分裂韧带）与内踝、跟骨内侧面之间共同构成。支持带向深部发出三个纤维隔，将踝管分隔成四个骨纤维性管。其内容纳的结构由前向后依次有：①胫骨后肌腱；②趾长屈肌腱；③胫后动静脉及胫神经；④𧿹长屈肌腱。上述各个肌腱均有腱鞘。踝管内有疏松结缔组织，是小腿后区通向足底的重要路径。踝后区的外伤、出血或肿胀均可压迫踝管的内容物，引起踝管综合征。",
        "踝管由屈肌支持带与内踝、跟骨内侧面围成，内容结构由前向后为胫骨后肌腱、趾长屈肌腱、胫后动静脉及胫神经、𧿹长屈肌腱。原书第六节（踝和足部）简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short015",
    order: 62,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述足弓的构成、分类及作用。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "足弓由跗骨和跖骨借韧带和关节连接而成，足弓可分为内、外侧纵弓和横弓。足弓是人站立行走及负重时的装置，其弹性能缓冲地面对身体所产生的震荡，同时还有保护足底血管、神经免受压迫的作用。当足弓的结构发育不良或受损，可引起足弓塌陷，导致扁平足。",
        "足弓由跗骨与跖骨借韧带、关节连接而成，分为内、外侧纵弓及横弓，具有缓冲震荡、保护足底血管神经的作用。原书第六节（踝和足部）简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-short016",
    order: 63,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "什么是踝管综合征？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "踝管内有疏松结缔组织，是小腿后区通向足底的重要路径。小腿或足底感染时，可经踝管相互蔓延。踝后区的外伤、出血或肿胀均可压迫踝管的内容物，引起踝管综合征。",
        "踝管综合征是踝管内容物（主要是胫神经及胫后血管）受压所致的综合征，踝后区外伤、出血或肿胀为常见诱因。原书第六节（踝和足部）简答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，3 组 × 共 8 成员（臀部 7～8 题、臀部 9～10 题、股部 33～36 题） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-b001",
    order: 64,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "闭孔",
      "梨状肌上孔",
      "坐骨大孔",
      "坐骨小孔",
      "梨状肌下孔",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-b001m1",
        order: 64,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "梨状肌穿过",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "坐骨大孔",
            "梨状肌向外穿坐骨大孔出盆腔，与坐骨大孔上、下缘之间分别形成梨状肌上、下孔。原书第二节（臀部）B1 型题第 7 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-b001m2",
        order: 65,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "臀上血管、神经穿过",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "梨状肌上孔",
            "梨状肌上孔穿经的结构自外侧向内侧依次为臀上神经、臀上动脉和臀上静脉。原书第二节（臀部）B1 型题第 8 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-b002",
    order: 66,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "阴部内血管及股后皮神经",
      "臀下血管及神经",
      "阴部神经及阴部内血管",
      "臀上血管及神经",
      "臀下血管及阴部神经",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-b002m1",
        order: 66,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "一同出梨状肌上孔的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "臀上血管及神经",
            "梨状肌上孔穿经臀上神经、臀上动脉和臀上静脉，故一同出梨状肌上孔的是臀上血管及神经。原书第二节（臀部）B1 型题第 9 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-b002m2",
        order: 67,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "一同出梨状肌下孔、入坐骨小孔的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "阴部神经及阴部内血管",
            "阴部内动、静脉和阴部神经自梨状肌下孔最内侧穿出后，越过骶棘韧带，经坐骨小孔进入坐骨肛门窝，故一同出梨状肌下孔、入坐骨小孔的是阴部神经及阴部内血管。原书第二节（臀部）B1 型题第 10 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-b003",
    order: 68,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "血管腔隙",
      "腹股沟管",
      "隐静脉裂孔",
      "股三角",
      "肌腔隙",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-b003m1",
        order: 68,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "腹股沟斜疝经过",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "腹股沟管",
            "腹股沟斜疝经腹股沟管由腹腔突出，可进入阴囊或大阴唇。原书第三节（股部）B1 型题第 33 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-b003m2",
        order: 69,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "股鞘位于",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "股三角",
            "股鞘呈漏斗形包绕股动、静脉上段，位于股三角内，其内侧腔为股管。原书第三节（股部）B1 型题第 34 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-b003m3",
        order: 70,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "股外侧皮神经穿过",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肌腔隙",
            "肌腔隙内有髂腰肌、股神经和股外侧皮神经通过，故股外侧皮神经穿肌腔隙入股部。原书第三节（股部）B1 型题第 35 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch08-lower-limb-b003m4",
        order: 71,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "大隐静脉穿入",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "隐静脉裂孔",
            "大隐静脉及其属支经隐静脉裂孔（卵圆窝）穿筛筋膜汇入股静脉。原书第三节（股部）B1 型题第 36 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
