import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 局部解剖学学习指导与习题集 — 第7章 上肢 题库提取（等比取样）
 * 来源：《局部解剖学学习指导与习题集》（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：18 题
 * - 选择题（a1-single）：16 题（A1 型 12 题、A2 型病例题 4 题）
 * - 问答题（short-answer）：11 题（简答）
 * - B1 配伍题：4 组、共 15 个成员
 * - 独立记分题合计：60 题（须等于本文件预算 60）
 * - 缺失答案：0；无法可靠提取：0（两处键号与解剖学语义冲突已按语义校正，见下）
 * - 说明：本章原书各节（第一节概述、第二节肩部、第三节臂部、第四节肘部、第五节
 *   前臂部、第六节腕和手）依序含名词解释、选择题（A1/A2/B1）、简答题；本文件按
 *   60 道预算在原书顺序内取材：名词解释 18 题全取（概述 2、肩部 4、臂部 1、肘部 3、
 *   前臂部 2、腕和手 6）、A1 型取概述第 1 题、肩部第 1–3 题、臂部第 1–6 题、肘部
 *   第 1–2 题（共 12 题）、A2 型取概述第 2 题、肩部第 4–6 题（共 4 题）、简答题
 *   11 题全取（概述 2、肩部 2、臂部 2、肘部 2、前臂部 1、腕和手 2）、B1 型取完整
 *   组 4 组（概述第 3–4 题 2 成员；臂部第 9–12 题 4 成员；肘部第 7–11 题 5 成员；
 *   前臂部第 8–11 题 4 成员）；未纳入的题因预算所限（含 A1 型肘部第 3–5 题、前臂部
 *   第 1–6 题、腕和手第 1–6 题，A2 型臂部第 7–8 题、前臂部第 7 题、腕和手第 7–8 题，
 *   B1 型前臂部第 12–15 题、腕和手第 9–13、14–18 题）。正确项对齐各节参考答案键号
 *   （A1/A2/B1 各小节与各节独立编号），选项与共用备选答案已随机重排并同步
 *   correctChoiceIndex。键号校正：概述 A2 型第 2 题键号 OCR 显示 2.D（肘外翻），
 *   但题干夹角 163° 小于正常提携角 165°～170°，按局部解剖学医学语义定为 B（肘内翻）。
 *   另取材核对发现腕和手 A1 型第 5 题键号 5.B（手背腱膜与浅筋膜之间）与本章重点难点
 *   「腱膜下间隙为手背腱膜与骨间背侧筋膜之间的间隙」不符，疑为原书或 OCR 键号之误，
 *   该题因预算未纳入本文件，仅记录备查。肩部 B1 型第 7–12 题
 *   参考答案为多项选择（如 7.AB、10.CDE），与 B1 单项配伍契约不符，未纳入。
 *   OCR 错字已按局部解剖学医学语义恢复（如 腋靜脉→腋静脉、网下肌→冈下肌、
 *   肩脾下肌→肩胛下肌、臀丛/臂丛、嚎突→喙突、肱骨肉→肱骨内、肝关节囊→肘关节囊、
 *   届肌支持带→屈肌支持带、桡侧獎→桡侧囊、尺骨茎笑→尺骨茎突、內側/内側→内侧、
 *   看見到→可见到 等），数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "topographic-anatomy-ch07-upper-limb";
const locatorBase =
  "《局部解剖学学习指导与习题集》 第7章 上肢 习题（核对PDF 第146–165页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），18 道（概述 2 + 肩部 4 + 臂部 1 + 肘部 3 + 前臂部 2 + 腕和手 6） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：提携角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肱骨的纵轴线与前臂（尺骨）的长轴线在肘部相交，构成一向外开放的钝角，称提携角。正常为165°～170°，女性的提携角大于男性，因此较为明显。",
        "提携角为肘部的重要角度标志：提携角小于正常值时属肘内翻，大于正常值时属肘外翻。原书参考答案 OCR 原文「女性的提携角小于男性，因此较为明显」内部矛盾，按局部解剖学语义恢复为「大于」。原书第一节概述名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：解剖学“鼻烟壶”",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "为位于手背拇指根部的浅凹，拇指充分外展并后伸时尤为明显。鼻烟窝的桡侧界为拇长展肌腱和拇短伸肌腱，尺侧界为拇长伸肌腱，近侧界为桡骨茎突。窝底为手舟骨和大多角骨。窝内可摸到桡动脉搏动。",
        "解剖学“鼻烟壶”（鼻烟窝）为手背外侧部的浅凹，窝内可触及桡动脉搏动，也是触诊手舟骨、大多角骨的部位。原书第一节概述名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：腋窝",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "上肢外展时，上肢根部内侧出现穹隆状皮肤凹陷，凹陷深面为四棱锥形的腔隙，称腋窝，由顶、底和四壁构成。",
        "腋窝顶由锁骨中份、第1肋外缘和肩胛骨上缘围成；底由皮肤、浅筋膜和腋筋膜（筛状筋膜）构成；四壁包括前壁（胸大肌、胸小肌、锁骨下肌和锁胸筋膜）、后壁（背阔肌、大圆肌、肩胛下肌和肩胛骨）、内侧壁（前锯肌、上4位肋骨及肋间肌）和外侧壁（肱肌、肱二头肌长、短头和肱骨结节间沟）。原书第二节肩部名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：腋鞘",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "为纤维结缔组织包裹腋动脉、腋静脉和臂丛所形成的筋膜鞘。",
        "腋鞘与颈部椎前筋膜相延续，臂丛麻醉（腋路阻滞）即经腋鞘进行，腋鞘内感染或出血亦可沿其蔓延。原书第二节肩部名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肌腱袖",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "又称肩袖，是肩袖肌群，即冈上肌、冈下肌、小圆肌和肩胛下肌的肌腱联合形成的腱膜结构，包绕肩关节的前、上、后三方，并与肩关节囊紧密愈合。",
        "肩袖肌群及其肌腱袖是肩关节的动态稳定装置；肩袖损伤（如冈上肌腱撕裂）时肩关节外展受限。原书第二节肩部名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：三边孔和四边孔",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "三边孔和四边孔有共同的上界和下界，上界为小圆肌和肩胛下肌，下界为大圆肌和背阔肌；肱三头肌长头构成三边孔的外侧界、四边孔的内侧界；四边孔的外侧界为肱骨外科颈。三边孔内有旋肩胛血管通过，四边孔内有腋神经和旋肱后血管通过。",
        "三边孔、四边孔位于腋窝后壁，是肩部血管神经出入的重要通道：旋肩胛动脉经三边孔至冈下窝，腋神经与旋肱后血管经四边孔至三角肌区。原书第二节肩部名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肱骨肌管",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "由肱三头肌与肱骨桡神经沟围成。肱三头肌的外侧头和内侧头分别起自桡神经沟的外上缘和内下缘，后方由长头的肌腹封闭形成潜在性的斜管，管内有桡神经和肱深血管通过。",
        "肱骨肌管又称桡神经管；肱骨干中段骨折累及管内桡神经时，可出现伸腕、伸指功能障碍（垂腕）。原书第三节臂部名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肘后三角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "为屈肘成直角时，肱骨内、外上髁和尺骨鹰嘴3点构成的等腰三角形。肘关节伸直时，上述3点则成一条直线。",
        "肘关节脱位或肱骨内、外上髁骨折时，肘后三角关系发生改变，据此可鉴别肘关节脱位与肱骨髁上骨折。原书第四节肘部名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肘外侧三角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "为屈肘90°时，肱骨外上髁、桡骨头与尺骨鹰嘴尖构成的等腰三角形。三角的中心点可作为肘关节穿刺的进针点。",
        "肘外侧三角是肘关节穿刺抽液、注药的定位标志。原书第四节肘部名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：肘后窝",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "为肘关节伸直时，在尺骨鹰嘴、桡骨头和肱骨小头之间形成的凹陷。窝的深方恰对肱桡关节，在窝底可触及桡骨头。",
        "可经肘后窝作肘关节穿刺，窝底可触及桡骨头，是肘后区的骨性标志。原书第四节肘部名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：桡血管神经束",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "由桡动、静脉和桡神经浅支组成。走行于肱桡肌内侧或深面。",
        "桡动脉两侧有桡静脉伴行，在腕前区发出掌浅支参与构成掌浅弓；桡神经浅支沿桡动脉外侧下行分布至手背桡侧半皮肤。原书第五节前臂部名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：尺侧血管神经束",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "由尺动、静脉及尺神经组成。位于前臂内侧。",
        "尺神经沿尺动、静脉的内侧下行，其肌支支配尺侧腕屈肌和指深屈肌尺侧半；尺动脉起始分出骨间总动脉，再分为骨间前、后动脉。原书第五节前臂部名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：腕掌侧韧带",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前臂深筋膜的延续，在腕前区增厚，横行纤维增多，形成腕掌侧韧带。",
        "腕掌侧韧带对前臂肌腱有固定、保护和支持作用；其内侧端与屈肌支持带之间形成腕尺侧管。原书第六节腕和手名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term014",
    order: 14,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：屈肌支持带",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "位于腕掌侧韧带的下缘深面，又名腕横韧带，是厚而坚韧的纤维性结缔组织束，内侧端附着于豌豆骨和钩骨钩，桡侧端附于手舟骨和大多角骨结节。",
        "屈肌支持带与腕骨沟共同围成腕管；其桡侧端分两层附着于舟骨结节和大多角骨结节，其间形成腕桡侧管。原书第六节腕和手名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term015",
    order: 15,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：腕桡侧管",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "屈肌支持带桡侧端分两层附着于舟骨结节和大多角骨结节，其间的间隙称为腕桡侧管，内有桡侧腕屈肌腱及其腱鞘通过。",
        "腕桡侧管位于腕前区桡侧，与腕管不相通，内有桡侧腕屈肌腱及其腱鞘通过。原书第六节腕和手名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term016",
    order: 16,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：腕尺侧管",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腕掌侧韧带内侧端与屈肌支持带之间的间隙，内有尺神经和尺动、静脉通过。",
        "腕尺侧管即尺神经管（Guyon管），尺神经在腕部受压时可致手内肌功能障碍及手尺侧皮肤感觉障碍。原书第六节腕和手名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term017",
    order: 17,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：鱼际间隙",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "位于掌中间鞘桡侧半深方。前界为掌中隔前部、示指屈肌腱、第1蚓状肌；后界为拇收肌筋膜；外侧界为外侧肌间隔；内侧界为掌中隔。",
        "鱼际间隙与掌中间隙被掌中隔分开；该间隙向远端经第1蚓状肌管通向示指背侧，其近端为盲端。原书第六节腕和手名词解释第 5 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-term018",
    order: 18,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：指腱鞘",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "为包绕指浅、指深屈肌腱的鞘管，由腱纤维鞘和腱滑膜鞘两部分构成。",
        "指腱鞘为包绕手指屈肌腱的鞘管；化脓性腱鞘炎时脓液不易向外扩散，可压迫肌腱影响血供，需及早处理。原书第六节腕和手名词解释第 6 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），16 道（A1 型 12 + A2 型病例题 4） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1001",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "腕前区正中可见到的纵行隆起是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "指浅屈肌腱",
      "掌长肌腱",
      "正中神经",
      "拇长屈肌腱",
      "尺侧腕屈肌腱",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "掌长肌腱",
        "握拳时，腕前区有三条纵行的肌腱隆起，中间的为掌长肌腱，外侧为桡侧腕屈肌腱，内侧为尺侧腕屈肌腱，桡动脉恰位于桡侧腕屈肌腱的外侧。原书第一节概述 A1 型题第 1 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1002",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "不参与腋窝前壁构成的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "胸大肌",
      "前锯肌",
      "锁胸筋膜",
      "锁骨下肌",
      "胸小肌",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前锯肌",
        "腋窝前壁由胸大肌、胸小肌、锁骨下肌和锁胸筋膜构成；前锯肌构成腋窝的内侧壁，锁胸筋膜有头静脉、胸肩峰血管和胸外侧神经穿越。原书第二节肩部 A1 型题第 1 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1003",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "穿三边孔的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "旋肱前动脉",
      "旋肩胛动脉",
      "腋神经",
      "旋肱后动脉",
      "肩胛下动脉",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "旋肩胛动脉",
        "三边孔内有旋肩胛血管通过，四边孔内有腋神经和旋肱后血管通过。旋肩胛动脉是腋动脉第3段分支肩胛下动脉的两终支之一，经三边孔至冈下窝。原书第二节肩部 A1 型题第 2 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1004",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "穿四边孔的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肌皮神经和旋肱前动脉",
      "以上都不是",
      "桡神经和肱深动脉",
      "腋神经和旋肱后动脉",
      "腋神经和旋肱前动脉",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腋神经和旋肱后动脉",
        "腋神经由臂丛后束发出，与旋肱后血管一起穿四边孔，在三角肌深面分为前、后两支，前支支配三角肌的前中部，后支支配三角肌后部和小圆肌。原书第二节肩部 A1 型题第 3 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1005",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "臂前区的皮肤支配的神经包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "臂内侧皮神经和前臂内侧皮神经",
      "肋间臂神经和臂内侧皮神经",
      "前臂内侧皮神经和臂外侧下皮神经",
      "臂外侧上皮神经和臂外侧下皮神经",
      "肋间臂神经和臂外侧上皮神经",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肋间臂神经和臂内侧皮神经",
        "臂前区皮肤由臂内侧皮神经、前臂内侧皮神经及肋间臂神经等支配。原书第三节臂部 A1 型题第 1 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1006",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肱动脉在臂部下份居",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肱骨的前内方",
      "肱骨的前外侧",
      "肱骨的前方",
      "肱骨的内侧",
      "肱骨的外侧",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肱骨的前方",
        "肱动脉在臂部上、中、下份分别位于肱骨的内侧、前内方和前方；压迫肱动脉止血时须分别朝外侧、外后、后方压向肱骨。原书第三节臂部 A1 型题第 2 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1007",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肱骨肌管构成不包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肱三头肌内侧头",
      "肱骨桡神经沟",
      "喙肱肌",
      "肱三头肌长头",
      "肱三头肌外侧头",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "喙肱肌",
        "肱骨肌管又称桡神经管，由肱三头肌（外侧头、内侧头、长头）与肱骨桡神经沟围成，管内有桡神经和肱深血管通过；喙肱肌不参与肱骨肌管的构成。原书第三节臂部 A1 型题第 3 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1008",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "伴行尺侧上副动脉的神经是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肌皮神经",
      "尺神经",
      "桡神经",
      "臂内侧皮神经",
      "正中神经",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "尺神经",
        "尺神经发自臂丛内侧束，在臂部与尺侧上副动脉伴行；桡神经与肱深动脉伴行，正中神经伴行于腋动脉和肱动脉。原书第三节臂部 A1 型题第 4 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1009",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于正中神经，描述正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "位于肱动脉内侧",
      "发自臂丛内、外侧束",
      "在臂部有分支",
      "发自臂丛内侧束",
      "位于腋动脉内侧",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "发自臂丛内、外侧束",
        "正中神经由臂丛内、外侧束发出的内、外侧根合并形成，该神经在臂部无分支；其在臂部与肱动脉伴行。原书第三节臂部 A1 型题第 5 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1010",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "关于桡神经，描述正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "发自臂丛外侧束",
      "位于肱动脉外侧",
      "穿行肱骨肌管",
      "位于腋动脉外侧",
      "发自臂丛内侧束",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "穿行肱骨肌管",
        "桡神经发自臂丛后束，与肱深动脉伴行，穿肱骨肌管至臂后区，在肱骨肌管内、外均发出肌支支配肱三头肌。原书第三节臂部 A1 型题第 6 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1011",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肘窝边界描述正确的是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "下外侧界是旋前圆肌",
      "顶有肱肌",
      "底是肱二头肌腱膜",
      "下内侧界是肱桡肌",
      "上界肱骨内、外上髁的连线",
    ],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "上界肱骨内、外上髁的连线",
        "肘窝上界为肱骨内、外上髁的连线，下外侧界为肱桡肌，下内侧界为旋前圆肌；顶由浅入深依次为皮肤、浅筋膜、深筋膜和肱二头肌腱膜，底为肱肌、旋后肌和肘关节囊。原书第四节肘部 A1 型题第 1 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1012",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "肘窝内容排列关系自内向外为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "肱动脉、正中神经、肱二头肌腱和桡神经",
      "正中神经、肱动脉、肱二头肌腱和尺神经",
      "正中神经、肱动脉、肱二头肌腱和桡神经",
      "正中神经、肱二头肌腱、肱动脉和桡神经",
      "肱二头肌腱、正中神经、肱动脉和桡神经",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "正中神经、肱动脉、肱二头肌腱和桡神经",
        "肘窝内容由内向外依次为正中神经、肱动脉及其两条伴行静脉、肱二头肌腱和桡神经及其分支。原书第四节肘部 A1 型题第 2 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1013",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "测得某女上臂长轴与前臂的长轴在肘部的夹角为163°（补角为17°），该女的上肢属于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "正常提携角",
      "肘脱位",
      "肘内翻",
      "上述都不是",
      "肘外翻",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肘内翻",
        "正常提携角为165°～170°；测得夹角163°小于正常范围，提携角减小，属肘内翻。参考答案键号 OCR 显示 2.D（肘外翻），与题干夹角 163°（<165°）不符，按局部解剖学医学语义校正为 B（肘内翻）。原书第一节概述 A2 型题第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1014",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某患者在做腋淋巴结清除手术时，突发血管内气栓，最可能是损伤了",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "头静脉",
      "锁骨下静脉",
      "腋动脉",
      "腋静脉",
      "锁骨下动脉",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腋静脉",
        "腋静脉与腋动脉伴行，管壁薄、管腔大，且与腋鞘及周围筋膜粘连，损伤后管壁不易回缩闭合，是术中发生血管内气栓的最可能来源。原书第二节肩部 A2 型题第 4 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1015",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者上臂骨折，肩关节不能外展，可能是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "外科颈骨折损伤了桡神经",
      "肱骨体骨折累及腋神经",
      "肩胛骨骨折累及肩胛上神经",
      "外科颈骨折伤及腋神经",
      "肩峰骨折损伤了肌皮神经",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "外科颈骨折伤及腋神经",
        "腋神经由臂丛后束发出，与旋肱后血管一起穿四边孔后绕肱骨外科颈至三角肌深面；肱骨外科颈骨折时易伤及腋神经，致三角肌瘫痪，肩关节不能外展，形成塌肩。原书第二节肩部 A2 型题第 5 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-a1016",
    order: 34,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "乳房上半部的恶性肿瘤需清除的淋巴结为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "中央淋巴结",
      "全部腋窝淋巴结加胸骨旁淋巴结",
      "尖淋巴结",
      "锁骨下淋巴结加胸骨旁淋巴结",
      "全部腋窝淋巴结",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "全部腋窝淋巴结加胸骨旁淋巴结",
        "尖淋巴结收纳中央淋巴结及其他各群淋巴结的输出淋巴管和乳房上部的淋巴管，临床上对乳房上半部恶性肿瘤常需清除全部腋窝淋巴结并加胸骨旁淋巴结。原书第二节肩部 A2 型题第 6 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），11 道（概述 2 + 肩部 2 + 臂部 2 + 肘部 2 + 前臂部 1 + 腕和手 2） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-short001",
    order: 35,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "上肢可触摸到哪些主要骨性标志？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肩峰、肩胛冈、锁骨、喙突、肱骨大结节、肱骨内、外上髁、桡骨头、尺骨鹰嘴、桡骨茎突、尺骨茎突。",
        "其中肩峰为上肢最高点的骨性标志；屈肘时在肘窝内可触及肱二头肌腱，肘后面最显著的隆起为尺骨鹰嘴。原书第一节概述简答题第 1 题参考答案（OCR 原文「嚎突」「肱骨肉」已按语义恢复为「喙突」「肱骨内」）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-short002",
    order: 36,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "上肢有哪些主要肌性标志？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腋前襞、腋后襞、肱二头肌、肱二头肌内、外侧沟、掌长肌腱、桡侧腕屈肌腱、尺侧腕屈肌腱。",
        "握拳时腕前区三条纵行肌腱隆起（掌长肌腱居中、桡侧腕屈肌腱在外、尺侧腕屈肌腱在内）即为重要肌性标志，桡动脉位于桡侧腕屈肌腱的外侧。原书第一节概述简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-short003",
    order: 37,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "肩关节动脉网由来自哪些动脉干的哪些动脉支构成？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肩胛动脉网位于肩胛骨的周围，是3条动脉的分支相互吻合形成的动脉网络。①自锁骨下动脉发出的肩胛上动脉，经肩胛上横韧带的上方进入冈上窝；②由腋动脉发出的肩胛下动脉的终支之一——旋肩胛动脉，经三边孔至冈下窝；③自锁骨下动脉发出的肩胛背动脉，沿肩胛骨内侧缘下行，分支至冈下窝。",
        "该动脉网是肩部血液的重要侧支循环途径，当腋动脉血流受阻时，可维持上肢的血供。原书第二节肩部简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-short004",
    order: 38,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "腋窝后壁有哪些结构？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腋窝后壁由背阔肌、大圆肌、肩胛下肌和肩胛骨构成。后壁有三边孔和四边孔，二者有共同的上界和下界：上界为小圆肌和肩胛下肌，下界为大圆肌和背阔肌；肱三头肌长头构成三边孔的外侧界、四边孔的内侧界；四边孔的外侧界为肱骨外科颈。三边孔内有旋肩胛血管通过，四边孔内有腋神经和旋肱后血管通过。",
        "腋窝后壁的肌性结构（背阔肌、大圆肌、肩胛下肌）与肩胛骨共同围成后壁，三边孔、四边孔是肩部血管神经出入的通道。原书第二节肩部简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-short005",
    order: 39,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "根据肱动脉在臂部的经行，如何压迫肱动脉进行止血？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肱动脉在臂部上、中、下份分别位于肱骨的内侧、前内方和前方，因此当需压迫肱动脉止血时，在臂部上份要朝外侧压向肱骨；在臂部中份要朝外后压向肱骨；在臂部下份要朝后压向肱骨。",
        "肱动脉在大圆肌下缘续接腋动脉，与正中神经伴行；掌握其在臂部各段的行程关系是正确压迫止血的基础。原书第三节臂部简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-short006",
    order: 40,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述桡神经、正中神经和尺神经在臂部伴行的血管。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "桡神经在臂部与肱深动脉伴行并进入肱骨肌管，在肱骨肌管内桡神经与由肱深动脉分出的桡侧副动脉伴行；正中神经伴行于腋动脉和肱动脉；尺神经与由肱深动脉分出的尺侧上副动脉伴行。",
        "臂部三大神经伴行血管的规律：桡神经—肱深血管（桡侧副动脉）、正中神经—腋/肱动脉、尺神经—尺侧上副动脉，掌握该规律有助于臂部血管神经束的辨认。原书第三节臂部简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-short007",
    order: 41,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述肘窝的边界及内容排列关系。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "（1）肘窝的边界：①上界为肱骨内、外上髁的连线；②下外侧界为肱桡肌；③下内侧界为旋前圆肌；④顶由浅入深依次为皮肤、浅筋膜、深筋膜和肱二头肌腱膜；⑤底是肱肌、旋后肌和肘关节囊。（2）肘窝内容：由内向外，依次为正中神经、肱动脉及其两条伴行静脉、肱二头肌腱和桡神经及其分支。",
        "肘窝内容物的排列可记为「神经—血管—肌腱—神经」：正中神经居最内侧，桡神经及其分支居最外侧，是肘部手术与穿刺的重要层次关系。原书第四节肘部简答题第 1 题参考答案（OCR 原文「肝关节囊」已按语义恢复为「肘关节囊」）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-short008",
    order: 42,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "肱二头肌腱膜如何形成及其临床意义？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肱二头肌腱的部分纤维向内下呈扇形发散，融入肘前区和前臂内侧的深筋膜，形成肱二头肌腱膜。临床意义：①具有使前臂自动旋后的功能；②腱膜的深面有肱血管和正中神经通过；③肱二头肌腱膜与肱二头肌腱交接处的上缘，是触摸肱动脉搏动和测量血压的听诊部位。",
        "肱二头肌腱膜是肘窝顶的组成部分，覆盖于肱血管和正中神经浅面；其内侧缘（与肱二头肌腱交接处上缘）为临床触脉与听诊血压的常用定位点。原书第四节肘部简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-short009",
    order: 43,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述前臂屈肌后间隙及其临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "前臂屈肌后间隙位于前臂远侧1/4段的潜在性疏松结缔组织间隙，在指深屈肌和拇长屈肌腱的深面，旋前方肌的浅面。此间隙向远侧经腕管与掌中间隙相通。前臂远段或手掌间隙感染时，炎症可经此间隙互相蔓延。",
        "前臂屈肌后间隙是前臂远段与手掌感染蔓延的解剖通道，掌中间隙感染可经腕管逆行至前臂屈肌后间隙。原书第五节前臂部简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-short010",
    order: 44,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述腕管构成及其内容。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腕管由屈肌支持带与腕骨沟共同围成。管内有屈肌总腱鞘包裹的指浅、深屈肌腱及拇长屈肌腱及其腱鞘和正中神经。屈肌总腱鞘形成尺侧囊，拇长屈肌腱鞘形成桡侧囊。",
        "腕管内容物排列紧密，正中神经居指浅、深屈肌腱浅面；腕管综合征时正中神经受卡压，出现鱼际肌萎缩及桡侧三指半掌面感觉障碍。原书第六节腕和手简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-short011",
    order: 45,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述掌中间隙位置、通连及其临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "掌中间隙位于掌中间鞘尺侧半的深方。掌中间隙向远侧沿第2～4蚓状肌管与2～4指蹼间隙相通，进而可通向手背；掌中间隙的近侧达屈肌总腱鞘的深面，可经腕管与前臂屈肌后间隙相交通。此间隙感染时，可经上述渠道蔓延。",
        "掌中间隙是手掌深部的潜在性筋膜间隙，与鱼际间隙被掌中隔分开；其感染可沿蚓状肌管、腕管等通道向手背、前臂蔓延。原书第六节腕和手简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，4 组 × 共 15 成员（概述 3～4；臂部 9～12；肘部 7～11；前臂部 8～11） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b001",
    order: 46,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "正中神经",
      "肱动脉",
      "桡神经",
      "尺神经",
      "桡动脉",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b001m1",
        order: 46,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "从锁骨中点至肘前横纹下2cm的连线的投影，表示",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肱动脉",
            "上肢外展90°、掌心向上时，从锁骨中点至肘前横纹中点下约2cm处的连线为腋动脉、肱动脉和正中神经的体表投影，本题选项中对应肱动脉。原书第一节概述 B1 型题第 3 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b001m2",
        order: 47,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "从肘前横纹下2cm至桡骨茎突前面连线的投影，表示",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "桡动脉",
            "从肘前横纹中点下2cm处至桡骨茎突前方的连线是桡动脉的投影；至豌豆骨则为尺动脉的投影。原书第一节概述 B1 型题第 4 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b002",
    order: 48,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "尺神经",
      "腋神经",
      "正中神经",
      "肌皮神经",
      "桡神经",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b002m1",
        order: 48,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "肱骨外科颈骨折时，可伤及",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "腋神经",
            "腋神经与旋肱后血管一起穿四边孔后绕肱骨外科颈至三角肌深面，肱骨外科颈骨折时易伤及腋神经，致三角肌瘫痪、肩关节不能外展。原书第三节臂部 B1 型题第 9 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b002m2",
        order: 49,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "肱骨干中段骨折时，易伤及",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "桡神经",
            "桡神经与肱深动脉伴行穿肱骨肌管（桡神经管），紧贴肱骨中段桡神经沟走行，肱骨干中段骨折时易伤及，出现垂腕等表现。原书第三节臂部 B1 型题第 10 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b002m3",
        order: 50,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "通过肱骨肌管的结构是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "桡神经",
            "肱骨肌管又称桡神经管，由肱三头肌与肱骨桡神经沟围成，管内有桡神经和肱深血管通过。原书第三节臂部 B1 型题第 11 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b002m4",
        order: 51,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "与旋肱后动脉伴行",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "腋神经",
            "腋神经由臂丛后束发出，与旋肱后血管一起穿四边孔，在三角肌深面分为前、后两支。原书第三节臂部 B1 型题第 12 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b003",
    order: 52,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "肘后三角",
      "肱二头肌腱膜",
      "肘外侧三角",
      "肘后三角形关系发生改变",
      "肱肌",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b003m1",
        order: 52,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "肱骨内上髁骨折",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肘后三角形关系发生改变",
            "肘后三角由肱骨内、外上髁和尺骨鹰嘴3点构成，肱骨内上髁骨折时该三角关系发生改变；同时内上髁后下方的尺神经沟内尺神经易受损伤。原书第四节肘部 B1 型题第 7 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b003m2",
        order: 53,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "肱骨外上髁骨折",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肘后三角形关系发生改变",
            "肘后三角的3点之一为肱骨外上髁，外上髁骨折移位可使肘后三角形关系发生改变。原书第四节肘部 B1 型题第 8 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b003m3",
        order: 54,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "肘窝的顶",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肱二头肌腱膜",
            "肘窝的顶由浅入深依次为皮肤、浅筋膜、深筋膜和肱二头肌腱膜，肱二头肌腱膜覆盖于肱血管和正中神经的浅面。原书第四节肘部 B1 型题第 9 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b003m4",
        order: 55,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "肘窝的底",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肱肌",
            "肘窝的底是肱肌、旋后肌和肘关节囊。原书第四节肘部 B1 型题第 10 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b003m5",
        order: 56,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "肘关节脱位",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肘后三角形关系发生改变",
            "肘关节脱位时尺骨鹰嘴与肱骨内、外上髁的相对位置改变，肘后三角关系发生改变，据此可区别于肱骨髁上骨折。原书第四节肘部 B1 型题第 11 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b004",
    order: 57,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "骨间前动脉",
      "尺神经",
      "桡神经深支",
      "桡神经浅支",
      "骨间总动脉",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b004m1",
        order: 57,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "支配旋后肌的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "桡神经深支",
            "桡神经在肱骨外上髁前方分为深、浅两支，深支先发肌支至桡侧腕短伸肌和旋后肌，然后穿入旋后肌，穿出该肌后改称骨间后神经。原书第五节前臂部 B1 型题第 8 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b004m2",
        order: 58,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "尺动脉分出",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "骨间总动脉",
            "尺动脉经旋前圆肌深面进入前臂前区，起始分出骨间总动脉，后者进一步分为骨间前动脉和骨间后动脉。原书第五节前臂部 B1 型题第 9 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b004m3",
        order: 59,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "支配尺侧腕屈肌的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "尺神经",
            "尺神经经尺神经沟向下穿尺侧腕屈肌两头之间进入前臂前区，沿尺动、静脉的内侧下行，其肌支支配尺侧腕屈肌和指深屈肌尺侧半。原书第五节前臂部 B1 型题第 10 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-topographic-anatomy-ch07-upper-limb-b004m4",
        order: 60,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "骨间后血管神经束包含",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "桡神经深支",
            "骨间后血管神经束由骨间后血管和神经组成，其中的神经即桡神经深支穿出旋后肌后延续的骨间后神经，二者为同一条神经。原书第五节前臂部 B1 型题第 11 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
