import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 局部解剖学学习指导与习题集 — 第一章 头部 题库提取（等比取样）
 * 来源：《局部解剖学学习指导与习题集》（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：13 题
 * - 选择题（a1-single）：10 题（含 A1 型 8 题、A2 型病例题 2 题）
 * - 问答题（short-answer）：10 题（简答）
 * - B1 配伍题：3 组、共 8 个成员
 * - 独立记分题合计：41 题（须等于本文件预算 41）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含概述、面部、颅部三节，每节均有独立习题与参考答案；本文件按
 *   41 道预算在原书顺序内取材：名词解释全取（概述 2 + 面部 6 + 颅部 5 = 13）、简答题
 *   全取（面部 6 + 颅部 4 = 10）、选择题取概述 A1 第 1 题与 A2 第 2 题、面部 A1 第
 *   1–7 题与 A2 第 8 题共 10 道、B1 型取完整组（概述 3–5 题 3 成员、面部 15–17 题
 *   3 成员、颅部 11–12 题 2 成员共 8 成员）；未纳入的题因预算所限（面部 A2 第 9–14
 *   题、面部 B1 组 18–20/21–23/24–26、颅部 A1/A2 各题及 B1 组 13–16 等）。正确项
 *   对齐各节参考答案键号（概述 A1 1.C、A2 2.C、B1 3.D/4.E/5.C；面部 1.D、2.E、
 *   3.A、4.B、5.C、6.B、7.D、8.B、15.E、16.D、17.D；颅部 11.B、12.C），其中
 *   面部参考答案键号按题号连续编号（A1 第 1–7 题、A2 第 8 题、B1 第 15–17 题），
 *   OCR 将 2–8 号键号挤入【A2型题】标题下、11/12 与 25/26 键号挤行，已按题号与解剖
 *   学语义归位。选项与共用备选答案已随机重排并同步 correctChoiceIndex。OCR 错字已按
 *   局部解剖学医学语义恢复（如 头致→头颈、翼靜脉丛→翼静脉丛、冀下颌间隙→翼下颌间隙、
 *   颈内动、靜脉→颈内动、静脉、颧号→颧弓、肥腺咬肌筋膜→腮腺咬肌筋膜、翼外肌下缘等），
 *   数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "topographic-anatomy-ch01-head";
const locatorBase =
  "《局部解剖学学习指导与习题集》 第1章 头部 习题（核对PDF 第13–24页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），13 道（概述 2 + 面部 6 + 颅部 5，全取） */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-topographic-anatomy-ch01-head-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：翼点",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "翼点为额、顶、颞、蝶四骨汇合之处，位于颧弓中点上方约两横指（约3.8cm）处，多呈H形。此处骨质薄弱，内面有脑膜中动脉前支通过，受暴力打击时，易骨折，并常伴动脉撕裂出血，形成硬膜外血肿。",
        "翼点是颅骨最薄弱处之一，内面恰为脑膜中动脉前支经过处，故颞部受暴力打击易骨折并撕裂动脉形成硬膜外血肿。原书概述节名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：乳突",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "乳突位于耳垂后方，是颞骨向后下方的突起，其基底部前内方有茎乳孔，面神经由此孔出颅。在乳突后部的颅腔内面有乙状窦沟，容纳乙状窦。乳突根治术时，应注意勿伤及面神经和乙状窦。",
        "乳突的毗邻要点是茎乳孔（面神经出颅处）与乙状窦沟（容纳乙状窦），乳突根治术须避开二者。原书概述节名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：面部危险三角",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "面静脉与颅内的海绵窦借多条途径相交通，因此面部感染有向颅内扩散的可能，尤其是口裂以上两侧口角至鼻根的三角形区域，感染向颅内扩散的可能性更大，被称为“危险三角区”。",
        "面部危险三角区（两侧口角至鼻根）的静脉缺乏瓣膜且与海绵窦相交通，挤压该区感染灶可致感染逆行入颅。原书面部节名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：腮腺床",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腮腺的深面与茎突诸肌及深部血管神经相邻。这些肌肉和血管、神经包括颈内动、静脉，舌咽、迷走、副神经及舌下神经共同形成“腮腺床”，紧贴腮腺的深面，并借茎突与位于其浅面的颈外动脉分开。",
        "腮腺床是腮腺深面的重要结构群（颈内动、静脉，舌咽、迷走、副及舌下神经，茎突诸肌），颈外动脉位于其浅面而不属于腮腺床。原书面部节名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：翼丛",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "翼丛是位于颞下窝内，翼内、外肌与颞肌之间的静脉丛。翼丛收纳与上颌动脉分支伴行的静脉，最后汇合成上颌静脉，回流到下颌后静脉。翼丛与上颌动脉位于颞下窝的浅部；翼内、外肌、下颌神经及其分支则位于颞下窝的深部。",
        "翼丛位于颞下窝浅部，是面部静脉与颅内静脉交通的重要途径之一。原书面部节名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：咬肌间隙",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "咬肌间隙为位于咬肌深部与下颌支上部之间的间隙，咬肌的血管神经即通过下颌切迹穿入此隙，从深面进入咬肌。此间隙的前方紧邻下颌第三磨牙，许多牙源性感染如第三磨牙冠周炎、牙槽脓肿和下颌骨骨髓炎等均有可能扩散至此间隙。",
        "咬肌间隙前方紧邻下颌第三磨牙，是牙源性感染的好发扩散部位。原书面部节名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：翼下颌间隙",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "翼下颌间隙位于翼内肌与下颌支之间，与咬肌间隙仅隔以下颌支，两间隙经下颌切迹相通。此间隙内有舌神经、下牙槽神经和同名动、静脉通过。下牙槽神经阻滞，即注射麻醉药液于此间隙内。牙源性感染常累及此间隙。",
        "翼下颌间隙是下牙槽神经阻滞麻醉的注药部位，也是牙源性感染常累及的间隙。原书面部节名词解释第 5 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：腮腺咬肌筋膜",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈深筋膜浅层向上延续为腮腺咬肌筋膜，该筋膜在腮腺后缘分为深、浅两层，包绕腮腺形成腮腺鞘，覆盖于咬肌表面，称为咬肌筋膜。",
        "腮腺咬肌筋膜是颈深筋膜浅层向上的延续，在腮腺后缘分深、浅两层包绕腮腺形成腮腺鞘，两层在腮腺前缘处融合后覆盖咬肌表面。原书面部节名词解释第 6 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：头皮",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "额顶枕区的皮肤、浅筋膜（皮下组织）、帽状腱膜及颅顶肌（枕额肌）3层结构紧密连接，难以将其各自分开，因此，常将此3层合称“头皮”。",
        "头皮指额顶枕区浅部三层（皮肤、浅筋膜、帽状腱膜及颅顶肌）的合称，临床意义在于头皮撕裂伤多沿其深面的腱膜下间隙分离。原书颅部节名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：腱膜下间隙",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腱膜下间隙位于帽状腱膜与骨膜之间的薄层疏松结缔组织，又称腱膜下疏松结缔组织。此隙范围较广，前至眶上缘，后达上项线。头皮借此层与颅骨外膜疏松连接，故移动性大，头皮撕裂伤多沿此层分离。",
        "腱膜下间隙是颅顶部的“危险层”，范围广、内含导静脉，感染或血肿易沿此层扩散。原书颅部节名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-term011",
    order: 11,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：板障静脉",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "板障静脉位于颅顶骨内、外板之间骨松质的板障管内，板障管在X线片上呈裂纹状，有时可被误认为骨折线，应注意鉴别。由于板障静脉位于骨内，手术时不能结扎，常用骨蜡止血。",
        "板障静脉沟通颅内、外静脉，位于骨内故术中不能结扎，需以骨蜡止血；X线片上板障管影可被误认为骨折线。原书颅部节名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-term012",
    order: 12,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：基底动脉环",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "基底动脉环又称Willis环，环绕视交叉、漏斗以及脚间窝的其他结构，由颈内动脉、大脑前动脉、前交通动脉、大脑后动脉、后交通动脉共同组成，是调节两侧颈内动脉系和椎-基底动脉系血流的重要结构。",
        "Willis环位于颅底，是连接两侧颈内动脉系与椎-基底动脉系的吻合环，对脑血流调节和侧支循环具有重要意义。原书颅部节名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-term013",
    order: 13,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：小脑幕切迹",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "小脑幕前内侧缘游离，向前延伸附着于前床突，两侧共同围成小脑幕切迹，与鞍背形成一卵圆形的孔，环绕着中脑。当幕上颅内压显著增高时，易形成小脑幕切迹疝，使脑干受压，出现相应临床表现。",
        "小脑幕切迹环绕中脑，是幕上颅内压增高时小脑幕切迹疝（颞叶钩回疝）的发生部位。原书颅部节名词解释第 5 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），10 道（A1 型 8 + A2 型 2） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-topographic-anatomy-ch01-head-a1001",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与头颈分界无关的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "下颌角",
      "乳突基底部",
      "枕外隆凸",
      "下颌骨下缘",
      "上项线",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "乳突基底部",
        "头与颈的分界线由下颌骨下缘、下颌角、乳突尖端、上项线至枕外隆凸的连线构成；乳突基底部不在其列，故为与头颈分界无关的结构。原书概述节 A1 型题第 1 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-a1002",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某患者因面部病变需行眶下神经阻滞麻醉，药物注入的最佳位置是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "眶下缘中、内1/3交点下方0.8cm处",
      "眶下缘中点下方0.8cm处",
      "眶下缘中、外1/3交点下方0.5cm处",
      "眶下缘中点下方0.5cm处",
      "眶下缘中、外1/3交点下方0.8cm处",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "眶下缘中点下方0.8cm处",
        "眶下孔位于眶下缘中点下方约0.8cm处，是眶下神经浅出与阻滞麻醉的进针定位点。原书概述节 A2 型题第 2 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-a1003",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "面部浅层结构的特点是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "各部皮肤移动性均较大",
      "睑部浅筋膜少而疏松",
      "颊部浅筋膜缺少脂肪组织",
      "面部浅层血供较差",
      "皮肤所含皮脂腺较少",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "睑部浅筋膜少而疏松",
        "面部皮肤薄而柔软、富于弹性，移动性视连接松紧而定（睑部疏松、鼻尖部紧密），含较多皮脂腺、汗腺和毛囊；颊部浅筋膜内脂肪聚集成颊脂体；浅层血供丰富。故 A、B、C、E 均与事实相反，D 正确。原书面部节 A1 型题第 1 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-a1004",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "面静脉",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "经眼静脉与海绵窦交通",
      "起自面总静脉",
      "行于面部深筋膜深面",
      "全程无静脉瓣",
      "注入面深静脉",
    ],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "经眼静脉与海绵窦交通",
        "面静脉起自内眦静脉，与面动脉伴行，口角平面以上无静脉瓣，经眼静脉与海绵窦相交通（面部危险三角的基础），注入颈内静脉。A（起自内眦静脉而非面总静脉）、C（行于浅筋膜内而非深筋膜深面）、D（仅口角平面以上无瓣，并非全程无瓣）、E（注入颈内静脉而非面深静脉）均错。原书面部节 A1 型题第 2 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-a1005",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "腮腺鞘",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "由气管前筋膜延续",
      "与腮腺结合紧密",
      "浅层薄弱，深层致密",
      "腮腺前缘处浅、深层两层分离",
      "腮腺鞘特别致密",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "与腮腺结合紧密",
        "腮腺鞘由颈深筋膜浅层向上延续（非气管前筋膜延续），在腮腺后缘分浅、深两层包绕腮腺、于前缘处融合（非分离）；其浅层特别致密而深层薄弱且不完整（C 方向相反）；鞘与腮腺结合紧密并发出间隔深入腺实质，将腮腺分隔成许多小叶。原书面部节 A1 型题第 3 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-a1006",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "腮腺管",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "开口处平对下颌第二磨牙",
      "至颊肌前缘急转向内侧",
      "直接穿颊黏膜开口于口腔",
      "在颧弓下方一横指处行向前",
      "由腮腺深部的前缘发出",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "在颧弓下方一横指处行向前",
        "腮腺管由腮腺浅部（非深部）的前缘发出，在颧弓下一横指处向前横跨咬肌表面，至咬肌前缘（非颊肌前缘）急转向内侧，穿颊肌后开口于与上颌第二磨牙（非下颌第二磨牙）相对处的颊黏膜上。原书面部节 A1 型题第 4 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-a1007",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "与腮腺床无关的结构是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "舌咽神经和迷走神经",
      "颈内动、静脉",
      "颈外动、静脉",
      "茎突诸肌",
      "副神经和舌下神经",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈外动、静脉",
        "腮腺床由颈内动、静脉，舌咽、迷走、副及舌下神经以及茎突诸肌组成，紧贴腮腺深面；颈外动脉借茎突与之分开、位于其浅面，不属于腮腺床。原书面部节 A1 型题第 5 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-a1008",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "翼静脉丛",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "回流到颈外静脉",
      "位于翼内、外肌之间",
      "汇合成上颌静脉",
      "位于颞下窝的深层",
      "下颌神经及其分支深面",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "汇合成上颌静脉",
        "翼丛位于颞下窝内、翼内、外肌与颞肌之间（A 错，非翼内、外肌之间），位于颞下窝浅部（翼内、外肌与下颌神经及其分支位于深部），收纳与上颌动脉分支伴行的静脉后汇合成上颌静脉，回流到下颌后静脉（非直接回流颈外静脉）。原书面部节 A1 型题第 6 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-a1009",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "翼下颌间隙",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "位于翼内肌与下颌支之间",
      "后界为腮腺和下颌支后缘",
      "前界为咬肌前缘",
      "上界为翼内肌下缘",
      "与咬肌间隙不相互联通",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "后界为腮腺和下颌支后缘",
        "翼下颌间隙位于翼内肌与下颌支之间，上界为翼外肌下缘（非翼内肌下缘），前界为颞肌、颊肌（非咬肌前缘），后界为腮腺和下颌支后缘；与咬肌间隙仅隔以下颌支、经下颌切迹相通（E 与事实相反）。选项 A 亦为翼下颌间隙的正确位置描述，参考答案键号为 D，故按键号取 D。原书面部节 A1 型题第 7 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-a1010",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某患者因实施隆鼻整形手术导致鼻背区域皮肤感觉丧失，受损的神经最有可能来自",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "面神经",
      "下颌神经",
      "上颌神经",
      "眼神经",
      "副神经",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "眼神经",
        "鼻背区皮肤的感觉由三叉神经眼神经的分支（鼻睫神经的滑车下神经、筛前神经鼻外支等）支配；面神经支配面肌运动，副神经支配胸锁乳突肌和斜方肌，与鼻背皮肤感觉无关。原书面部节 A2 型题第 8 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），10 道（面部 6 + 颅部 4，全取） */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-topographic-anatomy-ch01-head-short001",
    order: 24,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述面部皮肤与浅筋膜的结构特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "面部皮肤薄而柔软，富于弹性。移动性视其与深部组织连接的松紧情况而定，睑部连接疏松，鼻尖等部连接紧密。面部皮肤含有较多的皮脂腺、汗腺和毛囊，是皮脂腺囊肿和疖肿的好发部位。浅筋膜由疏松结缔组织构成，其中颊部脂肪聚成的团块，称颊脂体。睑部皮下组织少而疏松，此部位易形成水肿。浅筋膜内有神经、血管和腮腺管穿行。由于血供丰富，面部创口愈合快，抗感染能力较强，但创伤时出血较多。面静脉与颅内的海绵窦借多条途径相交通，因此面部感染有向颅内扩散的可能，尤其是口裂以上两侧口角至鼻根的三角形区域，感染向颅内扩散的可能性更大，被称为“危险三角区”。面部的小动脉有丰富的血管运动神经分布，反应灵敏，当情绪激动或患某些疾病时，面部的色泽也随之产生明显的变化。",
        "本题从皮肤（薄而柔韧、移动性视部位而定、皮脂腺汗腺毛囊多、血供丰富）与浅筋膜（疏松结缔组织、颊脂体、睑部少而疏松）两方面作答，并注意危险三角区与血供丰富的临床意义。原书面部节简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-short002",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述腮腺鞘的结构特征和临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颈深筋膜浅层向上延续为腮腺咬肌筋膜，该筋膜在腮腺后缘分为深、浅两层，包绕腮腺形成腮腺鞘，两层在腮腺前缘处融合。腮腺鞘与腮腺结合紧密，并发出间隔，深入到腺实质内，将腮腺分隔成许多小叶。由于腮腺有致密的筋膜鞘包裹，有炎症时常引起剧痛。腮腺鞘的浅层特别致密，而深层薄弱且不完整，腮腺化脓时，脓肿不易从浅层穿透，而易穿入深部，形成咽旁脓肿或穿向颈部。由于有间隔分隔，化脓性腮腺炎多为小叶性脓肿，故在切开排脓时，应注意引流每一脓腔。",
        "腮腺鞘特点：浅层致密、深层薄弱且不完整、与腺体结合紧密并发出间隔。临床意义：炎症剧痛、脓肿易向深部穿破形成咽旁脓肿、小叶性脓肿需逐腔引流。原书面部节简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-short003",
    order: 26,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述面神经颅外段的分段和各段的特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "面神经在颅外的行程中，因穿经腮腺而分为三段。第一段：面神经干从茎乳孔穿出至进入腮腺以前的一段，适位于乳突与外耳道之间的切迹内，此段长1～1.5cm，向前经过茎突根部的浅面，此段虽被腮腺所遮盖，但尚未进入腮腺实质内，显露面神经主干可在此处进行。第二段：腮腺内段，面神经主干于腮腺后内侧面进入腮腺，在腮腺内通常分为上、下两干，再发出分支，彼此交织成丛，最后形成颞、颧、颊、下颌缘、颈五组分支，面神经位于颈外动脉和下颌后静脉的浅面。正常情况下面神经外膜与腮腺组织容易分离，但病变时二者常紧密粘连，术中分离较为困难，腮腺肿瘤可压迫面神经引起面瘫。第三段：面神经穿出腮腺以后的部分，五组分支分别由腮腺浅部的上缘、前缘和下端穿出，呈扇形分布，至各相应区域，支配面肌。",
        "面神经颅外段以腮腺为界分为三段：茎乳孔至腮腺段（位于乳突与外耳道之间的切迹内，可显露主干）、腮腺内段（分上、下两干并交织成丛，形成五组分支）、穿出腮腺段（扇形分布支配面肌）。原书面部节简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-short004",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述腮腺的形态、分部、位置及其穿经腮腺的结构。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "腮腺略呈锥体形，底向外侧，尖向内侧突向咽旁，可分为深、浅两部，位于面侧区，上缘邻接颧弓、外耳道和颞下颌关节；下平下颌角；前邻咬肌、下颌支和翼内肌的后缘，浅部向前延伸，覆盖于咬肌后份的浅面；后缘邻接乳突前缘及胸锁乳突肌前缘的上份。深部位于下颌后窝内及下颌支的深面。穿经腮腺的结构：纵行的有颈外动脉、颞浅动、静脉、下颌后静脉及耳颞神经；横行的有上颌动、静脉、面横动、静脉及面神经的分支。上述血管神经的位置关系由浅入深依次为：面神经分支、下颌后静脉、颈外动脉及耳颞神经。",
        "本题要点：腮腺形态（锥体形、分深、浅两部）、位置毗邻（面侧区，上邻颧弓、外耳道和颞下颌关节，下平下颌角，后邻乳突与胸锁乳突肌）、穿经结构（纵行颈外动脉等、横行面神经分支等）及由浅入深的层次关系。原书面部节简答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-short005",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述面侧深区的境界及其内容。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "面侧深区位于颅底下方，口腔及咽的外侧，其上部为颞窝。由顶、底和四壁围成的区域：前壁为上颌骨体的后面；后壁为腮腺深部；外侧壁为下颌支；内壁为翼突外侧板和咽侧壁；顶为蝶骨大翼的颞下面；底平下颌骨下缘。其内容有翼内、外肌及出入颅底的血管、神经通过。翼丛及上颌动脉位于颞下窝浅部，翼内肌、翼外肌、下颌神经及其分支位于深部。",
        "面侧深区境界（顶、底与四壁）与内容（翼内、外肌及出入颅底的血管神经；浅部为翼丛与上颌动脉，深部为翼内、外肌与下颌神经及其分支）。原书面部节简答题第 5 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-short006",
    order: 29,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述翼下颌间隙的构成、交通及临床意义。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "翼下颌间隙位于翼内肌与下颌支之间，与咬肌间隙仅隔以下颌支，两间隙经下颌切迹相通。上界为翼外肌下缘，下界是翼内肌在下颌支的附着处，前界为颞肌、颊肌，后界为腮腺和下颌支后缘。此间隙内有下牙槽神经和同名动、静脉及疏松结缔组织。该间隙向前与颊肌和咬肌之间的颊间隙相通，向后隔颈深筋膜浅层与咽外侧间隙相邻，向上与颞下间隙相通。翼下颌间隙的感染，常来自下颌磨牙的炎症。下牙槽神经阻滞，即注射麻醉药液于此间隙内。",
        "翼下颌间隙要点：境界（翼内肌与下颌支之间，上界翼外肌下缘、下界翼内肌在下颌支的附着处、前界颞肌颊肌、后界腮腺和下颌支后缘）、交通（经下颌切迹通咬肌间隙，向前通颊间隙、向后邻咽外侧间隙、向上通颞下间隙）、临床意义（下牙槽神经阻滞注药部位，下颌磨牙感染常累及）。原书面部节简答题第 6 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-short007",
    order: 30,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述额顶枕区的层次和各层的特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "额顶枕区由浅入深依次为皮肤、浅筋膜、帽状腱膜及颅顶肌（枕额肌）、腱膜下疏松结缔组织和颅骨外膜。皮肤厚而致密，富含毛囊、汗腺和皮脂腺，具有丰富血管。浅筋膜有许多结缔组织小梁，连于皮肤与帽状腱膜之间，将皮下脂肪分割成许多小格。帽状腱膜两侧变薄，与颞筋膜相续。浅部3层紧密连接，难以将其各自分开，因此，常将此3层合称“头皮”。腱膜下疏松结缔组织又称腱膜下间隙，范围广泛，头皮撕裂伤多沿此层分离，为颅顶部危险层。颅骨外膜由致密结缔组织构成，借少量结缔组织与颅骨表面相连，易于剥离。",
        "额顶枕区五层：皮肤、浅筋膜、帽状腱膜及颅顶肌、腱膜下间隙（颅顶部危险层）、颅骨外膜；浅部三层紧密连接合称头皮。原书颅部节简答题第 1 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-short008",
    order: 31,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述颞区浅筋膜内血管神经的分布。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "颞区浅筋膜内的血管神经可分为耳前和耳后两组。耳前组有颞浅动、静脉和耳颞神经，三者伴行，出腮腺上缘，越颧弓到达颞区。颞浅动脉在颧弓上方2~3cm处分前、后两支；颞浅静脉汇入下颌后静脉；耳颞神经是三叉神经第三支下颌神经的分支，可在耳轮脚前方进行局部阻滞麻醉。耳后组有耳后动、静脉和枕小神经，分布于颞区后部。耳后动脉起自颈外动脉；耳后静脉汇入颈外静脉；枕小神经来自第2、3颈神经，属颈丛的分支。",
        "颞区浅筋膜血管神经分耳前组（颞浅动、静脉与耳颞神经伴行）与耳后组（耳后动、静脉与枕小神经）两组。原书颅部节简答题第 2 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-short009",
    order: 32,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述颅底结构特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①颅底的各部骨质厚薄不一，由前向后逐渐增厚，颅前窝最薄，颅后窝最厚，骨质较薄的部位在外伤时易骨折；②颅底的孔、裂、管是神经血管进出的通道，而某些骨内部又形成空腔性结构，如鼻旁窦、鼓室等，这些部位都是颅底本身的薄弱点，不但外伤时容易骨折，而且常伴有脑神经和血管损伤；③颅底与颅外的一些结构不但关系密切，而且紧相连接，如翼腭窝、咽旁间隙、眼眶等，这些部位的病变，如炎症、肿瘤等可蔓延入脑；相反，颅内病变也可引起其中某些部位的症状；④颅底骨与脑膜紧密愈着，外伤后不会形成硬膜外血肿，但脑膜同时损伤，引起脑脊液外漏。",
        "颅底特点四点：骨质厚薄不一（前薄后厚）、孔裂管与骨内空腔为薄弱点、与颅外结构紧相连通、颅底骨与脑膜紧密愈着。原书颅部节简答题第 3 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-short010",
    order: 33,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述海绵窦形态和穿行的结构。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "海绵窦为一对重要的硬脑膜静脉窦，由硬脑膜两层间的腔隙构成。位于蝶鞍的两侧，前达眶上裂内侧部，后至颞骨岩部的尖端，窦内间隙有许多结缔组织小梁，将窦腔分隔成许多小的腔隙，窦中血流缓慢，感染时易形成栓塞。两侧海绵窦经鞍膈前、后的海绵间窦相交通，故一侧海绵窦的感染可蔓延到对侧。窦内有颈内动脉和展神经通行。在窦的外侧壁内，自上而下排列有动眼神经、滑车神经、眼神经与上颌神经。海绵窦一旦发生病变，可出现海绵窦综合征，表现为上述神经麻痹与神经痛，结膜充血以及水肿等症状。",
        "海绵窦形态（位于蝶鞍两侧、由硬脑膜两层间腔隙构成、结缔组织小梁分隔、血流缓慢）、窦内穿行（颈内动脉与展神经）及外侧壁自上而下排列（动眼、滑车、眼、上颌神经），病变可致海绵窦综合征。原书颅部节简答题第 4 题参考答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，3 组 × 8 成员（概述 3–5、面部 15–17、颅部 11–12） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-topographic-anatomy-ch01-head-b001",
    order: 34,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["颧弓", "眶下孔", "翼点", "颏孔", "眶上切迹"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-ch01-head-b001m1",
        order: 34,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "与脑膜中动脉关系最密切的结构是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "翼点",
            "翼点内面有脑膜中动脉前支通过，受暴力打击时易骨折并撕裂该动脉形成硬膜外血肿。原书概述节 B1 型题第 3 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-ch01-head-b001m2",
        order: 35,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "与上下颌神经阻滞麻醉进针点定位有关的结构是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "颧弓",
            "上颌神经（经翼腭窝）与下颌神经（经卵圆孔）阻滞麻醉的进针点均以颧弓为体表定位标志。原书概述节 B1 型题第 4 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-ch01-head-b001m3",
        order: 36,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "与下牙槽神经的终末支有关的结构是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "颏孔",
            "下牙槽神经的终末支为颏神经，自颏孔穿出，分布于颏部皮肤及下唇等处。原书概述节 B1 型题第 5 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-b002",
    order: 37,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["面神经", "上颌神经", "眼神经", "下颌神经", "视神经"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-ch01-head-b002m1",
        order: 37,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "与面部表情肌运动有关的神经是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "面神经",
            "面肌（表情肌）属于皮肌，由面神经支配；面神经损伤可致面瘫。原书面部节 B1 型题第 15 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-ch01-head-b002m2",
        order: 38,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "与咬肌运动有关的神经是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "下颌神经",
            "咬肌由三叉神经下颌神经的咬肌神经支配，属运动支。原书面部节 B1 型题第 16 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-ch01-head-b002m3",
        order: 39,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "与耳前和颞区皮肤感觉有关的神经是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "下颌神经",
            "耳颞神经为三叉神经第三支下颌神经的分支，分布于耳前和颞区皮肤，司感觉。原书面部节 B1 型题第 17 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-topographic-anatomy-ch01-head-b003",
    order: 40,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["眼神经", "脑膜中动脉", "下颌神经", "视神经", "上颌神经"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-topographic-anatomy-ch01-head-b003m1",
        order: 40,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "穿过眶上裂的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "眼神经",
            "眶上裂有动眼神经、滑车神经、眼神经、展神经及眼上静脉等通过。原书颅部节 B1 型题第 11 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-topographic-anatomy-ch01-head-b003m2",
        order: 41,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "穿过圆孔的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "上颌神经",
            "上颌神经经蝶骨大翼的圆孔出颅。原书颅部节 B1 型题第 12 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
