/**
 * 题库课程生成器：把 extracted 题库底稿包装成可被现有题库 UI 消费的 CourseDefinition。
 *
 * 用法（每科目一次）：
 *   QB_SUBJECT=physiology npx tsx scripts/generate-qb-course.ts
 *
 * 产出：src/content/courses/{slug}.ts（AUTO-GENERATED，勿手改）。
 * 设计：不复制题目数据——课程定义直接 import 科目目录 index.ts 聚合的
 *   {subject}ExtractedItems / {subject}ExtractedGroups（单一数据源）。
 * 章节/知识点元数据从实际题目数据推导：按 knowledgePointId 分组、
 * 章节中文名从首题 promptSource.locator（"…第五章 呼吸 复习思考题…"）解析。
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
  ChapterDefinition,
  KnowledgePointDefinition,
} from "../src/types/learning";

type SubjectCfg = {
  key: string; // 科目目录名（= extracted 前缀），如 physiology
  slug: string; // 课程 slug，如 physiology-qb
  title: string;
  catalogLabel: string;
  classification: string;
  description: string;
  ghostWordmark: string;
  curriculumMode: "western-primary" | "tcm-primary" | "integrated";
  examBlueprintMissingLabel: string;
  versionMissingLabel: string;
  textbookLabel: string;
  textbookEdition: string | null;
};

const SUBJECTS: Record<string, SubjectCfg> = {
  physiology: {
    key: "physiology",
    slug: "physiology-qb",
    title: "生理学 · 题库",
    catalogLabel: "生理学题库",
    classification: "西医基础医学",
    description:
      "《生理学学习指导与习题集》第3版（人民卫生出版社）题库底稿：12 章约 600 道独立记分题（名词解释/A1单选/简答/B1配伍），经 OCR 语义恢复与等比取样，答案未与权威教材交叉核对。",
    ghostWordmark: "PHYSIOLOGY",
    curriculumMode: "western-primary",
    examBlueprintMissingLabel: "生理学正式考纲/试卷结构待导入",
    versionMissingLabel: "生理学教材版本信息待核验",
    textbookLabel: "《生理学学习指导与习题集》第3版（人民卫生出版社）",
    textbookEdition: "第3版",
  },
};

function err(msg: string): never {
  throw new Error(`[generate-qb-course] ${msg}`);
}

function chapterTitleFromLocator(locator: string | undefined, fallback: string): string {
  if (!locator) return fallback;
  // "《…》第3版 第五章 呼吸 复习思考题 习题（PDF …）" → "第五章 呼吸"
  const m = locator.match(/第[一二三四五六七八九十百\d]+章\s*[^\s（(，。；]*/);
  if (m) return m[0].trim();
  return fallback;
}

function toIndexLabel(topic: string): string {
  const m = topic.match(/ch(?:0*)(\d+)/);
  if (!m) return topic;
  const n = Number(m[1]);
  if (n === 0) return "绪论";
  return `第${n}章`;
}

function sortTopicOrder(topic: string): number {
  const m = topic.match(/ch(?:0*)(\d+)/);
  return m ? Number(m[1]) : 9999;
}

async function generate(cfg: SubjectCfg): Promise<void> {
  // 注意：{subject}.ts（现有课程）与 {subject}/（提取目录）同名并存，
  // 模块解析优先文件，必须显式导入 {key}/index
  const mod = await import(`../src/content/courses/${cfg.key}/index`);
  const items: AssessmentItemDefinition[] =
    mod[`${cfg.key}ExtractedItems`] ?? err(`${cfg.key}ExtractedItems 未导出`);
  const groups: AssessmentItemGroupDefinition[] =
    mod[`${cfg.key}ExtractedGroups`] ?? [];

  if (items.length === 0 && groups.length === 0) {
    err(`${cfg.key}：无任何题目`);
  }

  // 按 knowledgePointId 分组（顶层题目）
  const byKp = new Map<string, AssessmentItemDefinition[]>();
  for (const item of items) {
    const list = byKp.get(item.knowledgePointId) ?? [];
    list.push(item);
    byKp.set(item.knowledgePointId, list);
  }
  // B1 组成员也计入对应知识点（用于统计与 kp 标题回退）
  for (const group of groups) {
    for (const member of group.members) {
      if (!byKp.has(member.knowledgePointId)) byKp.set(member.knowledgePointId, []);
    }
  }

  const kpIds = [...byKp.keys()].sort((a, b) => {
    const ta = a.replace(/^kp-/, "");
    const tb = b.replace(/^kp-/, "");
    return sortTopicOrder(ta) - sortTopicOrder(tb);
  });

  const chapters: ChapterDefinition[] = [];
  const knowledgePoints: KnowledgePointDefinition[] = [];

  kpIds.forEach((kpId, order) => {
    const topic = kpId.replace(/^kp-/, "");
    const chapterItems = byKp.get(kpId) ?? [];
    const first = chapterItems[0];
    const locator = first?.promptSource?.locator;
    const fallbackTitle = topic;
    const title = chapterTitleFromLocator(locator, fallbackTitle);
    const indexLabel = toIndexLabel(topic);

    const chapterId = `chapter-${cfg.slug}-${topic}`;
    chapters.push({
      id: chapterId,
      slug: topic,
      order: order + 1,
      indexLabel,
      title,
      focus: `题库：${title}（${chapterItems.length} 题）`,
      knowledgePointIds: [kpId],
    });

    knowledgePoints.push({
      id: kpId,
      slug: topic,
      order: 1,
      title,
      note: `题库章节：${title}。底稿 ${chapterItems.length} 道独立记分题，答案 confidence=unverified，未与权威教材交叉核对。`,
      emphasis: "重点",
      contentStatus: "available",
      evidenceFramework: [],
      lenses: [],
      relationships: [],
      learningMemoryCriteria: [],
      sourceIds: [],
      learningTaskIds: [],
      assessmentItemIds: chapterItems.map((i) => i.id),
      caseIds: [],
      lesson: null,
    });
  });

  const courseId = `course-${cfg.slug}`;
  const out = `// AUTO-GENERATED by scripts/generate-qb-course.ts — 请勿手改。改动请重跑生成器。
import type { CourseDefinition } from "@/types/learning";
import {
  ${cfg.key}ExtractedItems,
  ${cfg.key}ExtractedGroups,
} from "./${cfg.key}/index"; // 注意：{subject}.ts（现有课程）与 {subject}/（提取目录）同名，显式指向 index

const chapters = ${JSON.stringify(chapters, null, 2)} as const;
const knowledgePoints = ${JSON.stringify(knowledgePoints, null, 2)} as const;

// 教材来源：全部 extracted 题目出自同一本题集，统一挂此来源（题目 locator 保留章/页细节）
const QB_SOURCE_ID = ${JSON.stringify(`source-${cfg.slug}-textbook`)} as const;
const qbSource = {
  id: QB_SOURCE_ID,
  order: 1,
  role: "course-material",
  type: "question-bank",
  authority: "publisher",
  scope: "general-reference",
  displayLabel: ${JSON.stringify(cfg.textbookLabel)},
  status: "available",
  missingLabel: null,
  citation: {
    label: ${JSON.stringify(cfg.textbookLabel)},
    edition: ${JSON.stringify(cfg.textbookEdition)},
    page: null,
    slide: null,
    academicYear: null,
    url: null,
  },
  verifiedAt: null,
} as const;

// 课程边界映射：extracted 底稿按契约 sourceIds 为空，课程校验要求非空——不修改底稿，
// 在课程定义层统一补充来源引用。
const withQbSource = <T extends { promptSource: { sourceIds: readonly string[] } }>(input: readonly T[]) =>
  input.map((item) => ({
    ...item,
    promptSource: { ...item.promptSource, sourceIds: [QB_SOURCE_ID] },
  }));
const withQbSourceAndAnswer = (
  item: (typeof ${cfg.key}ExtractedItems)[number],
) => ({
  ...item,
  promptSource: { ...item.promptSource, sourceIds: [QB_SOURCE_ID] },
  answer: item.answer.status === "available"
    ? { ...item.answer, sourceIds: [QB_SOURCE_ID] }
    : item.answer,
});

export const ${cfg.key}QbCourse: CourseDefinition = {
  id: ${JSON.stringify(courseId)},
  slug: ${JSON.stringify(cfg.slug)},
  title: ${JSON.stringify(cfg.title)},
  catalogLabel: ${JSON.stringify(cfg.catalogLabel)},
  classification: ${JSON.stringify(cfg.classification)},
  description: ${JSON.stringify(cfg.description)},
  ghostWordmark: ${JSON.stringify(cfg.ghostWordmark)},
  curriculumMode: ${JSON.stringify(cfg.curriculumMode)},
  contentStatus: "available",
  version: {
    id: ${JSON.stringify(`version-${cfg.slug}`)},
    status: "pending",
    textbookEdition: { status: "pending", value: null, missingLabel: ${JSON.stringify(cfg.versionMissingLabel)}, verifiedAt: null },
    school: { status: "pending", value: null, missingLabel: "学校待确认", verifiedAt: null },
    program: { status: "pending", value: null, missingLabel: "专业待确认", verifiedAt: null },
    learnerYear: { status: "pending", value: null, missingLabel: "年级待确认", verifiedAt: null },
    teacher: { status: "pending", value: null, missingLabel: "任课教师待确认", verifiedAt: null },
    academicYear: { status: "pending", value: null, missingLabel: "学年待确认", verifiedAt: null },
    semester: { status: "pending", value: null, missingLabel: "学期待确认", verifiedAt: null },
  },
  sources: [qbSource],
  examBlueprint: {
    id: ${JSON.stringify(`exam-blueprint-${cfg.slug}`)},
    title: ${JSON.stringify(cfg.title)},
    status: "pending",
    missingLabel: ${JSON.stringify(cfg.examBlueprintMissingLabel)},
    provenance: "user-provided",
    scope: {
      school: "待确认",
      program: "待确认",
      learnerYear: "待确认",
      academicYear: "待确认",
      semester: "待确认",
      teacher: null,
    },
    sourceIds: [],
    totalPoints: 0,
    rows: [],
    summaryGroups: [],
    priorityNotice: null,
    integrity: null,
  },
  learningRoutes: [],
  chapters,
  knowledgePoints,
  learningTasks: [],
  assessmentItems: ${cfg.key}ExtractedItems.map(withQbSourceAndAnswer),
  assessmentGroups: withQbSource(${cfg.key}ExtractedGroups).map((group) => ({
    ...group,
    members: group.members.map(withQbSourceAndAnswer),
  })),
  cases: [],
};

export default ${cfg.key}QbCourse;
`;

  const target = join(process.cwd(), "src", "content", "courses", `${cfg.slug}.ts`);
  writeFileSync(target, out, "utf8");
  console.log(`✅ 已生成 ${target}`);
  console.log(
    `   章节 ${chapters.length} · 知识点 ${knowledgePoints.length} · 顶层题 ${items.length} · 组 ${groups.length}`,
  );
  chapters.forEach((c) => console.log(`   ${c.order}. ${c.title} — ${byKp.get(c.knowledgePointIds[0])?.length ?? 0} 题`));
}

const subjectKey = process.env.QB_SUBJECT;
if (!subjectKey) {
  console.error("用法：QB_SUBJECT=physiology npx tsx scripts/generate-qb-course.ts");
  process.exit(1);
}
const cfg = SUBJECTS[subjectKey];
if (!cfg) {
  console.error(`未配置科目：${subjectKey}（可用：${Object.keys(SUBJECTS).join(", ")}）`);
  process.exit(1);
}
generate(cfg).catch((e) => {
  console.error(e);
  process.exit(1);
});
