/**
 * 传染病学学习指导与习题集 第3版 — 第10章 其他 题库提取（等比取样）
 * 来源：《传染病学学习指导与习题集》第3版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：1 题
 * - 选择题（a1-single）：31 题
 * - 简答题（short-answer）：6 题
 * - 病案分析（case）：0 题
 * - B1 配伍题：2 组 / 16 成员
 * - 独立记分题合计：54 题（须等于本文件预算 54）
 * - 缺失答案：8；无法可靠提取：0
 * - 说明：本章原书含选择题 43 题（A1/A2/A3/A4/B1）、名词解释 2 题、问答题 8 题，源题总量 69。正确项对齐章末参考答案键号，选项已随机重排并同步 correctChoiceIndex。OCR 错字已按传染病学医学语义恢复（如 病原体→病原体、品性感染→显性感染、潜伏→潜伏、菜姆病→莱姆病、雀乱→霍乱 等），数值与单位保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

const topic = "infectious-diseases-ch10";
const locatorBase =
  "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页）";
const promptNote =
  "题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";
const kp = "kp-" + topic;

const termItems: AssessmentItemDefinition[] = [
  {
    id: "ext-infectious-diseases-ch10-term001",
    order: 1,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "term",
    status: "available",
    prompt: "正常微生物群\n物",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） 名词解释 第1题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "正常微生物群：是微生物与其宿主在共同的历史进化过程中形成的生态结构，包括细菌、真\n方\n菌、病毒及生物活性物质等。按来源分类：内源性菌群，外源性菌群；按生境分类：原籍菌群，外籍\n菌群；按定位分类：常驻菌，过路菌。\n在经\n主健康方向转移的微生态学分支，是微生态学、医学微生物学、免疫学与传染病学交叉而成的新兴",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 名词解释 第1题）`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  }
];

const a1Items: AssessmentItemDefinition[] = [
  {
    id: "ext-infectious-diseases-ch10-a1001",
    order: 2,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "下列属于医院感染的是",
    choices: ["化学性刺激引起的炎症", "婴儿在宫内的弓形虫感染", "新生儿经产道时发生的感染", "物理性损伤引起的炎症", "婴儿在宫内的单纯疱疹病毒感染"],
    correctChoiceIndex: 2,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第1题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "新生儿经产道时发生的感染",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第1题 参考答案 E）属于医院感染的是新生儿经产道时发生的感染。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1002",
    order: 3,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "医院感染的病原体主要是",
    choices: ["真菌", "支原体", "细菌", "病毒", "寄生虫"],
    correctChoiceIndex: 2,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第2题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "细菌",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第2题 参考答案 A）医院感染的病原体主要是细菌。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1003",
    order: 4,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "医院感染最常见的部位",
    choices: ["国内是术后感染", "国外是术后感染，国内是肺部感染", "国内是肺部感染", "国外是肺部感染，国内也是", "国内是胃肠道感染"],
    correctChoiceIndex: 2,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第3题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "国内是肺部感染",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第3题 参考答案 C）医院感染最常见的部位国内是肺部感染。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1004",
    order: 5,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "有关尿路感染的说法，不正确的是",
    choices: ["预防尿路感染的关键是严格掌握留置导尿管的指征", "拔除导尿管后无需用抗生素", "主要与留置导尿有关", "致病菌以大肠埃希菌为主", "密闭引流要比开放式引流感染率高"],
    correctChoiceIndex: 4,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第4题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "密闭引流要比开放式引流感染率高",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第4题 参考答案 C）预防尿路感染的关键是严格掌握留置导尿管的指征。
试题分析：老年患者医院感染病原菌种类变化多。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1005",
    order: 6,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "关于老年患者医院感染，不正确的是",
    choices: ["容易发生败血症", "实验室检查可以没有显著的白细胞增高", "病原体相对单—", "临床表现常不典型，发热等可不明显", "系统反应较差并常伴有某些基础疾病"],
    correctChoiceIndex: 2,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第5题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "病原体相对单—",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第5题 参考答案 C）`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1006",
    order: 7,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "关于肺部感染的病原体，不正确的是\n\n\n390\n第十章其他",
    choices: ["危重患者和免疫功能低下者可见真菌", "ICU患者中可见 MRSA:MRSE", "革兰氏阳性球菌中以金黄色葡萄球菌为较常见", "种类较多，以革兰氏阴性杆菌居多", "铜绿假单胞菌性肺炎患者往往比较容易控制，预后并不严重"],
    correctChoiceIndex: 4,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第6题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "铜绿假单胞菌性肺炎患者往往比较容易控制，预后并不严重",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第6题 参考答案 E）肺部感染中，铜绿假单胞菌性肺炎患者的病死率可高达70%。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1007",
    order: 8,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "关于医院感染抗菌药物的应用，不合理的是",
    choices: ["据病原菌的药敏情况调整用药", "首先根据临床诊断估计病原菌", "注意药物的不良反应", "严重感染者以静脉用药为主", "提倡早日联合用药"],
    correctChoiceIndex: 4,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第7题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "提倡早日联合用药",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第7题 参考答案 C）医院感染抗菌药物的应用不一定均联合用药。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1008",
    order: 9,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "医院感染难治性的原因不包括",
    choices: ["宿主免疫功能低下，影响治疗效果", "病原菌多重耐药菌", "菌群失调加重药物的不良反应", "病原体为多种致病菌"],
    correctChoiceIndex: 3,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第8题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "病原体为多种致病菌",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第8题 参考答案 B）医院感染难治性的原因不包括病原体为多种致病菌。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1009",
    order: 10,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "男，31岁，因颅脑外伤、神志不清2h人住脑外科。体检：深昏迷，T 36.7°C,R 29次/min，\n格征、布鲁津斯基征、双侧巴宾斯基征均为阳性。CT示颅内出血，外周血象 WBC 11.8×10%L,N\nP88 次/min，BP 150/90mlg，双侧瞳孔不等大，对光反射迟钝，颈抵抗，两侧呼吸音清，凯尔尼\n85%，胸片报告无异常。人院后开颅去除颅内血肿，并行气管切开，予以呼吸机辅助呼吸。术\n后体温一直波动于38~38.5°C，术后第7天神志逐渐转清，体温复常，但术后第15天，体温\n升高到39.6°，此时气管插管已拔出，患者有咳嗽、咳痰，无尿路刺激症状。胸片示两肺纹理\n增多。\n下列说法中，不属于医院感染依据的是",
    choices: ["术后胸片示两肺纹理增多", "人院时听诊两侧呼吸音清晰，术后出现咳嗽、咳痰", "人院时血象 WBC11.8×x10%L,N85%", "术后第15天出现体温升高", "有颅脑外伤、手术等易感因素"],
    correctChoiceIndex: 2,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A4型题 第9题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "人院时血象 WBC11.8×x10%L,N85%",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A4型题 第9题 参考答案 C）人院时直象 WBC`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1010",
    order: 11,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "男，31岁，因颅脑外伤、神志不清2h人住脑外科。体检：深昏迷，T 36.7°C,R 29次/min，\n格征、布鲁津斯基征、双侧巴宾斯基征均为阳性。CT示颅内出血，外周血象 WBC 11.8×10%L,N\nP88 次/min，BP 150/90mlg，双侧瞳孔不等大，对光反射迟钝，颈抵抗，两侧呼吸音清，凯尔尼\n85%，胸片报告无异常。人院后开颅去除颅内血肿，并行气管切开，予以呼吸机辅助呼吸。术\n后体温一直波动于38~38.5°C，术后第7天神志逐渐转清，体温复常，但术后第15天，体温\n升高到39.6°，此时气管插管已拔出，患者有咳嗽、咳痰，无尿路刺激症状。胸片示两肺纹理\n增多。\n要明确诊断，最重要的是",
    choices: ["结核菌素皮肤试验", "用广谱抗菌药物诊断性治疗", "血常规检查", "多次血培养及痰培养", "肺部 CT检查"],
    correctChoiceIndex: 3,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A4型题 第10题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多次血培养及痰培养",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A4型题 第10题 参考答案 B）若患者血培养及痰培养均检出不动杆菌，抗菌药物选用的原则是用对不动杆菌敏`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1011",
    order: 12,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "男，31岁，因颅脑外伤、神志不清2h人住脑外科。体检：深昏迷，T 36.7°C,R 29次/min，\n格征、布鲁津斯基征、双侧巴宾斯基征均为阳性。CT示颅内出血，外周血象 WBC 11.8×10%L,N\nP88 次/min，BP 150/90mlg，双侧瞳孔不等大，对光反射迟钝，颈抵抗，两侧呼吸音清，凯尔尼\n85%，胸片报告无异常。人院后开颅去除颅内血肿，并行气管切开，予以呼吸机辅助呼吸。术\n后体温一直波动于38~38.5°C，术后第7天神志逐渐转清，体温复常，但术后第15天，体温\n升高到39.6°，此时气管插管已拔出，患者有咳嗽、咳痰，无尿路刺激症状。胸片示两肺纹理\n增多。\n若患者血培养及痰培养均检出不动杆菌，抗菌药物选用原则正确的是",
    choices: ["选用口服抗菌药物\n\n\n第十章其", "联合应用两种以上抗菌药物", "不用抗菌药物，对症处理", "用对不动杆菌敏感的抗菌药物", "选用针对革兰氏阳性菌的抗菌药物"],
    correctChoiceIndex: 1,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A4型题 第11题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "联合应用两种以上抗菌药物",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A4型题 第11题 参考答案 B）要明确诊断，最重要的是多次进行血培养及痰培养。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1012",
    order: 13,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "引起感染性休克的常见病原体不包括",
    choices: ["乙型脑炎病毒", "脑膜炎双球菌", "肠杆菌科细菌", "痢疾杆菌", "汉坦病毒"],
    correctChoiceIndex: 0,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第1题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "乙型脑炎病毒",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第1题 参考答案 D）引起感染性休克的常见病原体不包括乙型脑炎病毒。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1013",
    order: 14,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "在感染性休克的发生中淤血缺氧期的微循环障碍特点力",
    choices: ["微动脉舒张，微静脉开放", "微动脉舒张，毛细血管收缩", "微动脉收缩，毛细血管舒张", "微动脉收缩，微静脉舒张", "微动脉舒张，毛细血管开放，微静脉仍持续收缩"],
    correctChoiceIndex: 0,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第2题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "微动脉舒张，微静脉开放",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第2题 参考答案 B）在感染性休克的淤血缺氧期，微循环障碍特点为微动脉舒张，毛细血管开放，微静
仍保持所导致。
3. F
试题分析：在感染性休克中，导致低血压的重要介质为一氧化氮。而白细胞介素-4、白细胞介
素-10、白细胞介素-13和前列腺素E2 抗炎症介质，有阻止感染性休克发生的作用。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1014",
    order: 15,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "感染性休克纠正酸中毒治疗的首选药物",
    choices: ["11.2%乳酸钠", "10%葡萄糖酸钙", "22.4%乳酸钠", "5%碳酸氢钠", "10%碳酸氢钠"],
    correctChoiceIndex: 3,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第4题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "5%碳酸氢钠",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第4题 参考答案 D）感染性休克纠正酸中毒治疗的首选药物为5%碳酸氢钠。10%碳酸氢钠碱性太强`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1015",
    order: 16,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "有解除血管痉挛、兴奋呼吸中枢、提高窦性心律、稳定溶酶体膜、抑制血小板和中性粒细胞\n集聚的抗休克药物为",
    choices: ["酚妥拉明", "多巴胺", "异丙肾上腺素", "东莨菪碱", "间羟胺"],
    correctChoiceIndex: 3,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第5题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "东莨菪碱",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第5题 参考答案 D）有解除血管痉挛、兴奋呼吸中枢、提高窦性心律、稳定溶酶体膜、抑制血小板和中性
粒细胞集聚的抗休克药物为抗胆碱能药-东莨菪碱。其他血管活性药物药理作用没有那么全面。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1016",
    order: 17,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "感染性休克补充血容量治疗，每天低分子右旋糖酐的适宜用量是",
    choices: ["不超过1000ml", "根据病情需要", "不超过1500ml", "不超过800ml", "不超过500ml"],
    correctChoiceIndex: 0,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第6题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "不超过1000ml",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第6题 参考答案 D）感染性休克补充血容量治疗，每天低分子右旋糖的用量以不超过1000ml 为宜。
小量扩容达不到效果，过量有出血倾向。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1017",
    order: 18,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "MODS 最常见的病因是",
    choices: ["输液过多", "营养不良", "吸氧浓度过高", "机体免疫力低下", "严重感染"],
    correctChoiceIndex: 4,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第7题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "严重感染",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第7题 参考答案 B）MODS最常见的病因是严重感染。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1018",
    order: 19,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "MODS的发生率最高的休克类型是",
    choices: ["失血性休克", "过敏性休克", "感染性休克", "心源性休克", "神经源性休克"],
    correctChoiceIndex: 2,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第8题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "感染性休克",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第8题 参考答案 A）感染性休克 MODS 的发生率最高。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1019",
    order: 20,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "监测休克输液量的最佳指标是",
    choices: ["心率", "动脉血压", "中心静脉压", "心输出量", "尿量"],
    correctChoiceIndex: 2,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第9题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "中心静脉压",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第9题 参考答案 D）`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1020",
    order: 21,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "选择扩血管药治疗休克应首先",
    choices: ["给予细胞保护剂", "改善心脏功能", "充分扩容", "纠正酸中毒", "应用皮质激素"],
    correctChoiceIndex: 2,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第10题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "充分扩容",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第10题 参考答案 D）监测休克输液量的最佳指标是中心静脉压。
试题分析：感染性休克治疗应用扩血管药的原则应在充分补充血容量的基础上使用扩血管
药，否则易引起血压下降。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1021",
    order: 22,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，男，38岁，工人，因寒战、高热2d，头晕、气憋半天于11 月人院。患者于2d前突感寒战、\n\n\n第十章 其他酸 395\n高热，体温高达40°，伴有头痛，高热持续不降，半天来有明显头晕，呼吸急促，并感憋气，粪便正\n常，但有尿少。\n体检：T39°CC,R 36次/min, P 130次/min,BP 34/20mmHg，嗜睡，面色苍白，口唇及指甲有发绀，\n皮肤呈花斑状，四肢厥冷，呼吸急促，上胸部和腋下皮肤有瘀点。全身浅部淋巴结不大。眼、耳、鼻检查\n正常，咽红，扁桃体不大。颈软，肺无啰音，心脏不大，心音钝，心率130次/min，律整。腹部平软，无压\n痛，肝脾不大，肠鸣音正常。两下肢无水肿。神经系统检查正常。化验：血 WBC18×101，中性粒细胞\n90%，淋巴细胞10%，血小板52×10°1，尿蛋白（+）。镜检：红细胞0~1个AP，白细胞2~3个IHP。\n此例患者可能的诊断是",
    choices: ["流行性脑脊髓膜炎", "中毒性菌痢", "钩端螺旋体病", "感染性休克", "脑型疟疾"],
    correctChoiceIndex: 3,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A3型题 第11题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "感染性休克",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A3型题 第11题 参考答案 C）患者为男性青壮年，于秋冬季节发病，有发热、出血、肾损害三大临床主症，应考虑
肾综合征出直热导致的感染性休克，目前处于低血压休克期，为确诊应检测肾综合征出血热抗体，
治疗应首选积极补充血容量抗休克治疗。流脑好发于儿童，冬春季节多见，高热、脑膜刺激征、皮
第十章其他397
肤黏膜瘀点瘀斑为主；脑型疟疾、中毒性菌痢儿童易患，均好发于夏季，以中毒性脑病表现为主；钩
端螺旋体病亦好发于夏秋季，童症患者可发生肝肾功能损害和肺出血，少见皮肤瘀点等表现。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1022",
    order: 23,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，男，38岁，工人，因寒战、高热2d，头晕、气憋半天于11 月人院。患者于2d前突感寒战、\n\n\n第十章 其他酸 395\n高热，体温高达40°，伴有头痛，高热持续不降，半天来有明显头晕，呼吸急促，并感憋气，粪便正\n常，但有尿少。\n体检：T39°CC,R 36次/min, P 130次/min,BP 34/20mmHg，嗜睡，面色苍白，口唇及指甲有发绀，\n皮肤呈花斑状，四肢厥冷，呼吸急促，上胸部和腋下皮肤有瘀点。全身浅部淋巴结不大。眼、耳、鼻检查\n正常，咽红，扁桃体不大。颈软，肺无啰音，心脏不大，心音钝，心率130次/min，律整。腹部平软，无压\n痛，肝脾不大，肠鸣音正常。两下肢无水肿。神经系统检查正常。化验：血 WBC18×101，中性粒细胞\n90%，淋巴细胞10%，血小板52×10°1，尿蛋白（+）。镜检：红细胞0~1个AP，白细胞2~3个IHP。\n为了进一步确诊应做的检查是",
    choices: ["尿培养", "肾综合征出血热抗体检测", "脑脊液细菌培养", "脑脊液找疟原虫", "钩端螺旋体凝溶试验"],
    correctChoiceIndex: 1,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A3型题 第12题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肾综合征出血热抗体检测",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A3型题 第12题 参考答案 C）为了进一步确诊，应作肾综合征出血热抗体检测。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1023",
    order: 24,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，男，38岁，工人，因寒战、高热2d，头晕、气憋半天于11 月人院。患者于2d前突感寒战、\n\n\n第十章 其他酸 395\n高热，体温高达40°，伴有头痛，高热持续不降，半天来有明显头晕，呼吸急促，并感憋气，粪便正\n常，但有尿少。\n体检：T39°CC,R 36次/min, P 130次/min,BP 34/20mmHg，嗜睡，面色苍白，口唇及指甲有发绀，\n皮肤呈花斑状，四肢厥冷，呼吸急促，上胸部和腋下皮肤有瘀点。全身浅部淋巴结不大。眼、耳、鼻检查\n正常，咽红，扁桃体不大。颈软，肺无啰音，心脏不大，心音钝，心率130次/min，律整。腹部平软，无压\n痛，肝脾不大，肠鸣音正常。两下肢无水肿。神经系统检查正常。化验：血 WBC18×101，中性粒细胞\n90%，淋巴细胞10%，血小板52×10°1，尿蛋白（+）。镜检：红细胞0~1个AP，白细胞2~3个IHP。\n针对此例患者应首选的治疗方法是",
    choices: ["应用血管活性药物升血压", "静脉点滴5%碳酸氢钠", "静脉点滴三代头孢菌素抗生素", "积极扩容治疗", "静脉点滴大剂量肾上腺皮质激素减轻中毒症状"],
    correctChoiceIndex: 3,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A3型题 第13题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "积极扩容治疗",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A3型题 第13题 参考答案 C）`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1024",
    order: 25,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "主要通过抑制细胞壁合成起抗菌作用的药物有",
    choices: ["左氧氟沙星", "头孢呋辛", "氯莓素", "红霉素", "卡那霉素"],
    correctChoiceIndex: 1,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第1题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "头孢呋辛",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第1题 参考答案 A）B-内酰胺类抗生素主要通过抑制细胞壁合成起抗菌作用，包括青霉素、头孢菌素、`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1025",
    order: 26,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "影响细菌细胞的蛋白质合成的抗菌药物是",
    choices: ["青霉素类", "大环内酯类", "头孢菌素类", "磷霉素", "糖肽类"],
    correctChoiceIndex: 1,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第2题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "大环内酯类",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第2题 参考答案 C）`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1026",
    order: 27,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "细菌耐药性可分为",
    choices: ["获得耐药性", "天然或固有的耐药性", "以上均对", "以上均错\n\n\n第十章 其", "先有天然或固有的耐药性后有获得耐葯性"],
    correctChoiceIndex: 2,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第3题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "以上均对",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第3题 参考答案 C）大环内酯类通过影响细菌蛋白质合成起抑菌作用，典型代表如红霉素。
试题分析：细菌耐药性根据其发生原因可分为获得耐药性和天然耐药性。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1027",
    order: 28,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "细菌耐药性的遗传学基础为",
    choices: ["以上均错", "质粒介导的耐药性", "以上均对", "染色体介导或突变产生的耐药性", "染色体介导或突变产生的耐药性与质粒介导的耐药性往往同时存在"],
    correctChoiceIndex: 2,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第4题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "以上均对",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第4题 参考答案 C）细菌耐药性的遗传学机制：①细菌先天固有特性即生来存在于其染色质上，有种属
构基因，也可发生于某些调节基因。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1028",
    order: 29,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "治疗脑膜炎需要同时鞘内给药的抗感染药内",
    choices: ["氟康唑\n汐", "头孢曲松", "两性霉素 B", "磷霉素", "青霉素"],
    correctChoiceIndex: 2,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第5题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "两性霉素 B",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第5题 参考答案 C）治疗脑膜炎需要同时鞘内给药的抗感染药为两性霉素B。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1029",
    order: 30,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "与细菌产生耐药性无关的酶为",
    choices: ["ESBL.", "AmpC酶", "青素酶", "钝化酶", "凝固酶"],
    correctChoiceIndex: 4,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第6题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "凝固酶",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第6题 参考答案 C）凝固酶是一种由葡萄球菌产生的酶。具有类似凝血酶原激酶的活性，能使经柠檬`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1030",
    order: 31,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "无论脑膜有无炎症，不能透人脑脊液的抗菌药物內",
    choices: ["头孢曲松", "左氧氟沙星", "氯霉素", "万古霉素", "米诺环素"],
    correctChoiceIndex: 4,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第7题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "米诺环素",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第7题 参考答案 C）四环素类药物不易透过血-脑屏障。`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-a1031",
    order: 32,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "a1-single",
    status: "available",
    prompt: "骨组织中浓度高的药物沩",
    choices: ["克拉霉素", "磷霉素", "万古霉素", "氟喹诺酮类", "红霉素"],
    correctChoiceIndex: 1,
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） A1型题 第8题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "磷霉素",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 A1型题 第8题 参考答案 B）骨组织中浓度较高的抗菌药有：林可4素、氯林可霉素、头孢替安、磷霉素、褐霉素、`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  }
];

const shortItems: AssessmentItemDefinition[] = [
  {
    id: "ext-infectious-diseases-ch10-short001",
    order: 33,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "short-answer",
    status: "available",
    prompt: "简述抗菌药物联合应用的指征。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） 问答题 第1题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "尽量减少联合用药，以免引起菌群失调。联合应用的指征：①急性严重感染病原菌未明\n确前，暂时应用；②严重混合感染，一种抗菌药不能兼顾者。",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 问答题 第1题）`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-short002",
    order: 34,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "short-answer",
    status: "available",
    prompt: "什么是医院感染？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） 问答题 第2题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "医院感染（nosocomial infection） 又称医院获得性感染（hospital acquired infection），是指\n染出院后才出现症状者。\n患者在入院时既不存在又不处于潜伏期，而是在住院过程中获得的感染，也包括在医院内获得感\n（魏来）\n第二节 感染性休克\n【学习目标】",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 问答题 第2题）`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-short003",
    order: 35,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "short-answer",
    status: "available",
    prompt: "简述抗菌葯物的作用机制。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） 问答题 第1题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗菌药物作用机制有：\n（1） 干扰细菌细胞壁的合成。\n（2）损伤细菌细胞膜。\n（3） 影响细菌蛋白质的合成。\n（4） 抑制细菌核酸的代谢。\n（5） 其他：抑制细菌叶酸代谢等。",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 问答题 第1题）`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-short004",
    order: 36,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "short-answer",
    status: "available",
    prompt: "简述联合用药的适应证。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） 问答题 第3题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗菌药物的联合应用要有明确指征：单一药物可有效治疗的感染，不需联合用药，仅在\n（1）原菌尚未查明的严重感染，包括免疫缺陷者的严重感染。\n（3） 单一抗菌药物不能有效控制的感染性心内膜炎或败血症等重症感染。\n（2）单一抗菌药物不能控制的需氧菌及厌氧菌混合感染，2种或2种以上病原菌感染。\n（5） 由于药物协同抗菌作用，联合用药时应将毒性大的抗菌药物剂量减少。联合用药时宜选\n（4）需长程洽疗，但病原菌易对某些抗菌药物产生耐药性的感染，如结核病、深部真菌病。\n用具有协同或相加抗菌作用的药物联合。联合用药通常采用2种药物联合，3种及3种以上药\n物联合仅适用于个别情况，如结核病的治疗。此外必须注意联合用药后药物不良反应将增多。",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 问答题 第3题）`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-short005",
    order: 37,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "short-answer",
    status: "available",
    prompt: "简述引起细菌耐药的主要机制。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） 问答题 第2题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "引起细菌耐药性的主要机制有：\n化酶。\n（2） 抗菌药物对细菌渗透障碍与细菌主动外排。\n\n第十章其他\n（3） 靶位改变。\n（4）其他：如细菌代谢通路变化等。",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 问答题 第2题）`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-short006",
    order: 38,
    knowledgePointId: "kp-infectious-diseases-ch10",
    questionKind: "short-answer",
    status: "available",
    prompt: "简述抗菌药物临床应用基本原则。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） 问答题 第4题",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗菌药物临床应用，必须遵照以下基本原则：\n（2） 确定感染类型、明确感染病原、了解患者病理生理状况与药物特点，制订正确的用药方案：\n①确定感染部位与类型，是开展抗菌药物治疗的前提；②了解感染病原菌种类与敏感性，正确选择\n临床和实验室证据。\n抗菌药物；③熟悉抗菌药物的药理学特征和不良反应，制订合理的治疗方案；④经验用药必须基于\n（肖永红）\n第五节人工肝脏\n【学习目标】",
        `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 问答题 第4题）`,
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  }
];

const caseItems: AssessmentItemDefinition[] = [];

const bGroups: AssessmentItemGroupDefinition[] = [
  {
    id: "ext-infectious-diseases-ch10-b001",
    order: 39,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["心源性休克", "失血性休克", "创伤性休克", "感染性休克", "过敏性休克"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第14–17题 共用备选答案",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-infectious-diseases-ch10-b001m1",
        order: 39,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "严重骨盆骨折引起",
        correctChoiceIndex: 2,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第14题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "创伤性休克",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第14题 参考答案 B）严重骨盆骨折引起休克为创伤性休克。`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b001m2",
        order: 40,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "脑膜炎双球菌败血症引起",
        correctChoiceIndex: 3,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第15题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "感染性休克",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第15题 参考答案 C）`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b001m3",
        order: 41,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "肝细胞癌向腹腔破裂引起",
        correctChoiceIndex: 1,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第16题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "失血性休克",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第16题 参考答案 E）脑膜炎双球菌败血症容易引起感染性休克。
试题分析：肝细胞癌向腹腔破裂止血比较困难，导致失血性休克。`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b001m4",
        order: 42,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "心肌梗死引起",
        correctChoiceIndex: 0,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第17题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "心源性休克",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第17题 参考答案 A）心肌梗死引起心功能不全，导致心源性休克。`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      }
    ],
    sourceIds: [],
  },
  {
    id: "ext-infectious-diseases-ch10-b002",
    order: 43,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["抗胆碱能药", "B-受体阻滞药", "缩血管药", "B-受体兴奋药", "a- 受体阻滞药"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第18–21题 共用备选答案",
      note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-infectious-diseases-ch10-b002m1",
        order: 43,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "多巴胺",
        correctChoiceIndex: 3,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第18题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "B-受体兴奋药",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第18题 参考答案 D）`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b002m2",
        order: 44,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "酚妥拉明为",
        correctChoiceIndex: 4,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第19题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "a- 受体阻滞药",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第19题 参考答案 A）多巴胺为B-受体兴奋药。详见血管活性药物的药理作用分类。
试题分析：酚妥拉明为d-受体阻滞药。`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b002m3",
        order: 45,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "东莨菪碱",
        correctChoiceIndex: 0,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第20题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "抗胆碱能药",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第20题 参考答案 C）东莨菪碱抗胆碱能药。`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b002m4",
        order: 46,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "异丙肾上腺素\n（二）间答题",
        correctChoiceIndex: 1,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第21题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "B-受体阻滞药",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第21题 参考答案 B）（二）`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b002m5",
        order: 47,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "感染性休克的基本病理生理是什么？",
        correctChoiceIndex: 0,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第1题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第1题 参考答案 ?）`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b002m6",
        order: 48,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "感染性休克常见的病原体是什么？",
        correctChoiceIndex: 0,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第2题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第2题 参考答案 ?）`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b002m7",
        order: 49,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "感染性休克时为何易诱发 DIC？发生DIC 的临床表现是什么？",
        correctChoiceIndex: 0,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第4题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第4题 参考答案 ?）`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b002m8",
        order: 50,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "预示感染性休克发生的可能征象是什么？",
        correctChoiceIndex: 0,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第3题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第3题 参考答案 ?）`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b002m9",
        order: 51,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "感染性休克的病原治疗原则是什么？\n\n396\n第十章 其\n他",
        correctChoiceIndex: 0,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第5题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第5题 参考答案 ?）`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b002m10",
        order: 52,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "感染性休克抗休克治疗的要点是什么？",
        correctChoiceIndex: 0,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第6题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第6题 参考答案 ?）`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b002m11",
        order: 53,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "感染性休克的治疗在什么情况下选用缩血管药？",
        correctChoiceIndex: 0,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第7题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第7题 参考答案 ?）`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-infectious-diseases-ch10-b002m12",
        order: 54,
        knowledgePointId: "kp-infectious-diseases-ch10",
        questionKind: "b1",
        status: "available",
        prompt: "感染性休克如何进行扩容治疗？",
        correctChoiceIndex: 0,
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: "《传染病学学习指导与习题集》第3版 第10章 其他 习题（核对PDF 第397–430页） B1型题 第8题",
          note: `题干轻度改写（同义替换/语序/句式）；原题来自用户提供的教材配套学习指导与习题集（扫描件 OCR 恢复）`,
          sourceIds: [],
        },
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "",
            `答案依据题集参考答案整理并改写，未经权威教材交叉核对（原书第10章 其他 B1型题 第8题 参考答案 ?）`,
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      }
    ],
    sourceIds: [],
  }
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems, ...a1Items, ...shortItems, ...caseItems,
];
export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
