import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 药理学学习指导与习题集（第4版，配套《药理学》第9版）— 第2章 药物代谢动力学 题库提取（等比取样）
 * 来源：《药理学学习指导与习题集》第4版（人民卫生出版社，主编：乔国芬；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：10 题
 * - 填空题（fill）：8 题
 * - 选择题（a1-single）：15 题（含 A1 型 13、A2 型病例题 2）
 * - 问答题（short-answer）：4 题（含简答 4、论述 0）
 * - B1 配伍题：1 组、共 5 个成员
 * - 独立记分题合计：42 题（须等于本文件预算 42）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含名词解释 10、填空题 8、选择题（A1 型 90 + A2 型 10 + B1 型 2 组
 *   共 10 小题）与简答题 4；本文件按 42 道预算在原书顺序内取材：名词解释、填空、简答全取，
 *   选择题取 A1 型第 1–13 题与 A2 型第 91、93 题，B1 型取第 1 组（101～105 题共用备选答案）
 *   完整 5 成员。A1/A2 均映射为 a1-single，正确项对齐章末参考答案键号（A2 型题键号 91.A、
 *   93.E 对应原书 A2 型第 91、93 题；键号 90.D 实属 A1 型第 90 题，系 OCR 归位误差）；
 *   选项已随机重排并同步 correctChoiceIndex。OCR 错字与符号已按药理学医学语义恢复
 *   （葯→药、t½/Vd/Css/Kₑ 缩写、零级动力学半衰期 0.5C₀/Kₑ、一级动力学 0.693/Kₑ 等），
 *   数值（pKa 8.4、pH=5、非解离 90.9%、半衰期 8 小时等）均保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "pharmacology-ch02-pharmacokinetics";
const locatorBase =
  "《药理学学习指导与习题集》第4版（配套《药理学》第9版） 第2章 药物代谢动力学 习题（核对PDF 第14–26页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），10 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：首过效应",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "首过效应",
        "指药物通过肠黏膜及肝脏时经过灭活代谢而使进入体循环的药量减少的现象，也称首过消除或首过代谢。原书名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：生物利用度",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "生物利用度",
        "指药物制剂给药后其中能被吸收进入体循环的药物相对分量及速度，可用相对量（以 AUC 表示）与达峰速度衡量。原书名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：时量曲线",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "时量曲线",
        "指药物在血浆中的浓度随时间的推移而发生变化所作的曲线，即药-时曲线，用于反映药物在体内的动态变化过程。原书名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：半衰期",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "半衰期",
        "指血浆药物浓度下降一半所需的时间，即药物消除半衰期（t½）。原书名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：房室模型",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "房室模型",
        "是将机体视为一个系统，系统内部按动力学特点分为若干房室；房室是一个假设空间，其划分与解剖学部位或生理学功能无关，只要体内某些部位药物的转运速率相同，均视为同一室。原书名词解释第 5 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：表观分布容积",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "表观分布容积",
        "指当血浆和组织内药物分布达到平衡后，体内药物按此时的血浆药物浓度在体内分布时所需体液容积（Vd）。原书名词解释第 6 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：稳态血药浓度",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "稳态血药浓度",
        "按照一级动力学规律消除的药物，其体内药物总量随着不断给药而逐步增多，直至从体内消除的药物量和进入体内的药物量相等时，体内药物总量不再增加而达到稳定状态，此时的血浆药物浓度称稳态浓度（Css），也称坪值。原书名词解释第 7 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：一级消除动力学",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "一级消除动力学",
        "是体内药物按恒定比例消除，在单位时间内的消除量与血浆药物浓度成正比，也称线性动力学；大多数药物在体内按一级动力学消除。原书名词解释第 8 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-term009",
    order: 9,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：零级消除动力学",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "零级消除动力学",
        "指药物在体内以恒定的速率消除，即不论血浆药物浓度高低，单位时间内消除的药物量不变，通常是因为药物在体内的消除能力达到饱和所致，也称非线性动力学。原书名词解释第 9 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-term010",
    order: 10,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：负荷剂量",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "负荷剂量",
        "指首次剂量加大，然后再给予维持剂量，使稳态血药浓度（即事先为该患者设定的靶浓度）提前产生。原书名词解释第 10 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），8 道 */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-fill001",
    order: 11,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "药物在体内的过程有___、___、___和___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "吸收；分布；代谢；排泄",
        "药物在体内的过程包括吸收、分布、代谢（生物转化）和排泄，即 ADME。原书填空题第 1 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-fill002",
    order: 12,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "经被动转运通过细胞膜的弱酸性药物，其转运环境的 pH 越大，则药物呈离子状态者越___，由于呈离子状态者脂溶性___，所以此药通过细胞膜也越___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多；小；少",
        "弱酸性药物在 pH 较大的环境中解离增多，离子型增多而脂溶性减小，故不易透过细胞膜。原书填空题第 2 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-fill003",
    order: 13,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "经被动转运通过细胞膜的弱碱性药物，其转运环境的 pH 越小，则药物呈离子状态者越___，由于呈离子状态者脂溶性___，所以此药通过细胞膜也越___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "多；小；少",
        "弱碱性药物在 pH 较小的环境中解离增多，离子型增多而脂溶性减小，故不易透过细胞膜。原书填空题第 3 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-fill004",
    order: 14,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "主动转运可___膜两侧浓度高低的影响，消耗___，有___现象。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "不受；能量；饱和性及竞争性抑制",
        "主动转运可逆电化学差（浓度梯度）转运药物，需消耗能量（能量可直接来源于 ATP 水解，或间接来源于其他离子的电化学梯度），并具有饱和性及竞争性抑制现象。原书填空题第 4 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-fill005",
    order: 15,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "生理情况下，由于机体细胞外液的 pH 为___，细胞内液的 pH 为___，故弱碱性药物较___进入细胞；当弱碱性药物中毒时，可通过___化血液，从而使药物从___转入___，并促进其经肾___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "7.4；7.0；易；酸；细胞内液；细胞外液；排泄",
        "生理情况下细胞外液 pH 约 7.4、细胞内液 pH 约 7.0，弱碱性药物在酸性较强的细胞内液中解离增多而较易进入（蓄积于）细胞；弱碱性药物中毒时可酸化血液，使药物在血液中解离增多、不易进入组织细胞，从而使药物从细胞内液转入细胞外液，并促进其经肾排泄。原书填空题第 5 题（该题语句在扫描件中错乱，按键号顺序与药理学语义重建）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-fill006",
    order: 16,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "药物通过生物转化，绝大多数成为___性高、___溶性大的产物，___于从肾排泄。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "极；水；易",
        "药物经生物转化（尤其是 II 相结合反应）后，绝大多数成为极性高、水溶性大的代谢产物，易于从肾排泄。原书填空题第 6 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-fill007",
    order: 17,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "肝药酶的特点是___性低，有个体差异___的现象。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "专一；大",
        "肝药酶（主要为肝微粒体细胞色素 P450 酶系）的特点是专一性低、活性有限、个体差异大，且易受药物的诱导和抑制（与本章 A1 型第 81 题答案一致）。原书填空题第 7 题（该题语句在扫描件中错乱，按键号与语义重建）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-fill008",
    order: 18,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "消除速率常数的缩写是___，半衰期的缩写是___，稳态血浓度的缩写是___，表观分布容积的缩写是___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Kₑ；t½；Css；Vd",
        "消除速率常数缩写为 Kₑ，消除半衰期缩写为 t½，稳态血药浓度缩写为 Css，表观分布容积缩写为 Vd。参考答案键号顺序在扫描件中错乱（Vd 与 Css 互串），已按药理学语义归位。原书填空题第 8 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），15 道（A1 型 13 + A2 型病例题 2） */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1001",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "药物代谢动力学是研究",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "药物经肝脏代谢生成无活性产物的过程",
      "药物体内过程及体内药物浓度随时间变化的规律",
      "药物进入血液循环与血浆蛋白结合及解离的规律",
      "药物从给药部位进入血液循环的过程",
      "药物吸收后在机体细胞分布变化的规律",
    ],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "药物体内过程及体内药物浓度随时间变化的规律",
        "药物代谢动力学研究药物在体内的过程（吸收、分布、代谢、排泄）及体内药物浓度随时间变化的规律；药物从给药部位进入血液循环属吸收过程的具体环节，不完整。原书 A1 型题第 1 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1002",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "按一级动力学消除的药物，其血浆消除半衰期等于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["Kₑ/0.693", "2.303/Kₑ", "0.693/Kₑ", "0.301/Kₑ", "Kₑ/2.303"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "0.693/Kₑ",
        "按一级动力学消除时 t½＝0.693/Kₑ，为一个常数，不受药物初始浓度和给药剂量的影响，仅取决于消除速率常数 Kₑ。原书 A1 型题第 2 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1003",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "一个 pKa 为 8.4 的弱酸性药物，其在血浆中的解离度为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["50%", "10%", "90%", "60%", "40%"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "10%",
        "血浆 pH 约 7.4，与药物 pKa（8.4）相差 1.0，按 Henderson-Hasselbalch 方程计算，弱酸性药物在血浆中的解离度约 10%。原书 A1 型题第 3 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1004",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "弱酸性或弱碱性药物的 pKa 都是该药在溶液中",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "80% 离子化时的 pH",
      "90% 非离子化时的 pH",
      "50% 离子化时的 pH",
      "90% 离子化时的 pH",
      "80% 非离子化时的 pH",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "50% 离子化时的 pH",
        "pKa 是弱酸性或弱碱性药物在溶液中解离 50%（即离子型与非离子型各占一半）时的 pH，是反映药物解离特性的常数。原书 A1 型题第 4 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1005",
    order: 23,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "离子障是指",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "非离子型药物可以自由穿过细胞膜，而离子型的也能穿过",
      "离子型药物可以自由穿过细胞膜，而非离子型的则不能穿过",
      "非离子型药物可以自由穿过细胞膜，而离子型的则不能穿过",
      "离子型和非离子型都只能部分穿过细胞膜",
      "非离子型药物不可以自由穿过细胞膜，而离子型的也不能穿过",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "非离子型药物可以自由穿过细胞膜，而离子型的则不能穿过",
        "离子障是指离子型药物极性大、脂溶性低，不能自由穿过细胞膜，而非离子型药物可以自由穿过细胞膜。原书 A1 型题第 5 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1006",
    order: 24,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "药物进入血液循环后首先",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["在肝脏代谢", "储存在脂肪", "与血浆蛋白结合", "作用于靶器官", "在肾脏排泄"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "与血浆蛋白结合",
        "药物进入血液循环后首先与血浆蛋白结合（多为可逆性结合），结合型药物暂时失去药理活性，游离型药物才能发挥药理作用。原书 A1 型题第 6 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1007",
    order: 25,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某药按零级动力学消除，其消除半衰期等于",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["Kₑ/0.5", "0.5/Kₑ", "0.5C₀/Kₑ", "0.693/Kₑ", "Kₑ/0.5C₀"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "0.5C₀/Kₑ",
        "按零级动力学消除时 t½＝0.5C₀/Kₑ，与血浆药物初始浓度 C₀ 成正比，即给药剂量越大半衰期越长。原书 A1 型题第 7 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1008",
    order: 26,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "药物代谢和排泄的速度决定其",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["最大效应的高低", "起效的快慢", "后遗效应的大小", "作用持续时间的长短", "副作用的多少"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "作用持续时间的长短",
        "药物在体内的代谢和排泄速度（即消除速度）决定药物作用持续时间的长短，消除速度慢则作用持续时间长。原书 A1 型题第 8 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1009",
    order: 27,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "大多数药物跨膜转运的方式是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["主动转运", "过滤", "易化扩散", "简单扩散", "胞饮"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "简单扩散",
        "绝大多数药物按简单扩散（被动扩散）方式通过生物膜，即非极性药物分子溶解于细胞膜脂质层、顺浓度差通过细胞膜。原书 A1 型题第 9 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1010",
    order: 28,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某酸性药物在 pH＝5 时的非解离部分为 90.9%，其 pKa 的近似值是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["4", "6", "2", "5", "3"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "6",
        "非解离部分 90.9% 时离子型与非离子型之比约为 1:10，由 pH－pKa＝lg([A⁻]/[HA])＝－1，可得 pKa＝pH＋1＝6。原书 A1 型题第 10 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1011",
    order: 29,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某药按一级动力学消除时，其半衰期",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["随给药剂量而变化", "固定不变", "随药物剂型而变化", "随血浆浓度而变化", "随给药次数而变化"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "固定不变",
        "按一级动力学消除的药物，t½ 为常数，不受药物初始浓度、给药剂量、剂型、给药次数及血浆浓度的影响。原书 A1 型题第 11 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1012",
    order: 30,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "某药的半衰期为 8 小时，一次给药后药物在体内基本消除的时间是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["8天", "1天", "4天", "2天", "6天"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "2天",
        "按一级动力学消除，经约 5 个 t½ 后体内药物基本消除；8 小时×5＝40 小时，约为 2 天。原书 A1 型题第 12 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1013",
    order: 31,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "在碱性尿液中，弱酸性药物",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "解离少，重吸收多，排泄慢",
      "解离多，重吸收多，排泄快",
      "解离多，重吸收少，排泄快",
      "解离少，重吸收多，排泄快",
      "解离多，重吸收少，排泄慢",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "解离多，重吸收少，排泄快",
        "弱酸性药物在碱性尿液中解离增多、脂溶性降低，肾小管重吸收减少，故排泄加快。原书 A1 型题第 13 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1014",
    order: 32,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "30 岁女性，服药过量中毒。抢救时发现应用碳酸氢钠后尿中药物浓度增加，应用氯化铵后尿中药物浓度减少，该药为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["强碱性药", "高脂溶性药", "弱酸性药物", "中性药", "弱碱性药物"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "弱酸性药物",
        "碳酸氢钠碱化尿液，弱酸性药物在碱性尿液中解离增多、重吸收减少、排泄增多，故尿中药物浓度增加；氯化铵酸化尿液则相反，由此判断该药为弱酸性药物。原书 A2 型题第 91 题，参考答案键号 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-a1015",
    order: 33,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "患者，男，28 岁，因车祸致右侧股骨开放性骨折入院，行静脉诱导麻醉下骨固定手术。患者使用静脉麻醉药后苏醒是因为",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["药物血浆蛋白结合", "药物离子化", "药物从中枢再分布", "药物血浆清除", "药物肝脏代谢"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "药物从中枢再分布",
        "静脉麻醉药脂溶性高，进入脑组织后可迅速再分布到血流丰富、容量大的组织（如脂肪、骨骼肌），使中枢神经系统内药物浓度下降而苏醒。原书 A2 型题第 93 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），4 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-short001",
    order: 34,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "某人过量服用苯巴比妥中毒，有何办法加速脑内药物排至外周，并从尿内排出？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "使用碳酸氢钠碱化血液和尿液以加速药物排泄",
        "苯巴比妥为弱酸性药物，在碱性条件下解离度高、不易跨膜转运。碳酸氢钠一方面碱化血液，可加速苯巴比妥由脑细胞向血液中转运；另一方面碱化尿液，使尿中离子型苯巴比妥增加、肾小管重吸收减少，从而促进药物从尿中排出。原书简答题第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-short002",
    order: 35,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述肝药酶对药物转化的影响以及与药物相互作用的关系。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝药酶诱导加快合用药物代谢、减弱药效；肝药酶抑制减慢合用药物代谢、增强疗效和毒性",
        "肝脏微粒体的细胞色素 P450 酶系统是肝内促进药物代谢的主要酶系统，简称肝药酶，具有活性有限、个体差异大、易受药物的诱导和抑制的特点。某些药物（如利福平、乙醇、卡马西平等）可产生酶诱导，使合用药物代谢速率加快、药理作用减弱；有些药物（如西咪替丁、保泰松等）可抑制肝微粒体酶的活性，使合用的药物代谢减慢、疗效和毒性增强。原书简答题第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-short003",
    order: 36,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "请简述药动学参数 t½、Vd 及 Css 的意义和应用。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "t½ 反映消除速度并确定给药间隔；Vd 用于计算剂量和估计分布范围；Css 是制订给药方案的重要参数",
        "t½ 即消除半衰期，指血浆药物浓度消除一半所需时间，其长短反映体内药物消除速度；据此可确定给药间隔时间（通常约为一个 t½）、预计连续给药后达到稳态血药浓度的时间（约 4～5 个 t½）及停药后药物从体内消除所需的时间（约 5 个 t½）。Vd 即表观分布容积，指分布达到平衡后体内药物按此时的血浆药物浓度分布所需体液容积，其主要应用为：（1）计算产生期望药物浓度所需要的给药剂量；（2）估计药物的分布范围。Css 即稳态血药浓度（坪值），按一级动力学消除的药物定时定量连续多次给药经约 5 个 t½ 后所达到，是制订给药方案的重要参数；任何途径给药都需经约 5 个 t½ 达 Css，停止给药经约 5 个 t½ 体内药物基本全部消除。当给药间隔为一个 t½ 时，首次剂量加倍可迅速达到 Css，此时负荷剂量等于 2 倍的维持剂量。原书简答题第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-short004",
    order: 37,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "患者病情危急，需立即达到稳态浓度以控制病情，应如何给药？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "采用负荷剂量给药法，即首次剂量加大，再给予维持剂量",
        "维持量给药需 4～5 个 t½ 才能达到稳态治疗浓度，增加剂量或缩短给药间隔时间均不能立即达到稳态浓度。病情危急时可用负荷剂量给药法迅速达到稳态浓度以控制病情：即首次剂量加大，然后再给予维持剂量，使稳态血药浓度（事先为该患者设定的靶浓度）提前产生。原书简答题第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，1 组 × 5 成员（原书 101～105 题共用备选答案） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-pharmacology-ch02-pharmacokinetics-b001",
    order: 38,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "尿素",
      "乙酰胆碱",
      "维生素B12",
      "脑垂体后叶粉剂",
      "甲氨蝶呤",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-pharmacology-ch02-pharmacokinetics-b001m1",
        order: 38,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "以外泌囊泡的形式排出细胞的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "乙酰胆碱",
            "乙酰胆碱由神经末梢以突触囊泡（外泌囊泡）形式排出细胞而释放。原书 B1 型题第 101 题，参考答案键号 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-pharmacology-ch02-pharmacokinetics-b001m2",
        order: 39,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "主动转运仅在回肠末端进行的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "维生素B12",
            "维生素B12 在回肠末端通过与内因子结合后经主动转运吸收。原书 B1 型题第 102 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-pharmacology-ch02-pharmacokinetics-b001m3",
        order: 40,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "以易化扩散方式转运进入白细胞的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "甲氨蝶呤",
            "甲氨蝶呤依靠载体以易化扩散（顺浓度梯度）方式转运进入白细胞。原书 B1 型题第 103 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-pharmacology-ch02-pharmacokinetics-b001m4",
        order: 41,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "可从鼻黏膜给药以胞饮方式吸收的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "脑垂体后叶粉剂",
            "脑垂体后叶粉剂可从鼻黏膜给药，以胞饮（膜动转运的一种）方式吸收。原书 B1 型题第 104 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-pharmacology-ch02-pharmacokinetics-b001m5",
        order: 42,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "经上皮细胞膜的水性通道进行跨膜转运的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "尿素",
            "尿素分子较小，可经上皮细胞膜的水性通道（滤过，即水溶性扩散）进行跨膜转运。原书 B1 型题第 105 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...fillItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
