import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 药理学学习指导与习题集（第4版，配套《药理学》第9版）— 第26章 治疗心力衰竭的药物 题库提取（等比取样）
 * 来源：《药理学学习指导与习题集》第4版（人民卫生出版社，主编：乔国芬；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释（term）：4 题
 * - 填空题（fill）：13 题
 * - 选择题（a1-single）：5 题（含 A1 型、A2 型病例题）
 * - 问答题（short-answer）：10 题（含简答、论述）
 * - B1 配伍题：3 组、共 6 个成员
 * - 独立记分题合计：38 题（须等于本文件预算 38）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含名词解释 4、填空题 13、选择题（A1 型 40 + A2 型 7 + B1 型 9 组共 25 小题）
 *   与简答/论述题 18；参考答案键号自 1–72 连续编号（A1 1–40、A2 41–47、B1 48–72，
 *   B1 各组题号连续：48–49、50–51、52–53、54–57、58–59、60–61、62–64、65–67、68–72），
 *   已按题号与药理学医学语义归位。本文件按 38 道预算在原书顺序内取材：名词解释全取、
 *   填空题全取、A1 型题取第 1–5 题、简答/论述题取第 1–10 题、B1 取前三组完整组
 *   （48–53 题，共 6 成员）；未取材：A1 第 6–40 题、A2 第 41–47 题、B1 第 54–72 题、
 *   简答/论述第 11–18 题（预算所限）。A1/A2/B1 按项目规约映射为 a1-single/b1，正确项对齐
 *   章末参考答案键号（A1 型题 1.B、2.C、3.B、4.E、5.D；B1 型题 48.A、49.D、50.C、51.A、
 *   52.B、53.D），选项已随机重排并同步 correctChoiceIndex（B1 组选项保持原书顺序，成员指向
 *   对应索引）。OCR 错字与双栏错序已按药理学医学语义恢复（如 葯→药、卡维地溶→卡维地洛、
 *   强心背→强心苷、诚慢→减慢、A-V→房室、阝受体→β受体、Na*-K*-ATP 酶→Na⁺-K⁺-ATP 酶、
 *   Ca？*→Ca²⁺、I～皿级→I～III 级 等）；填空题第 7 题心电图五项按参考答案键号
 *   （S-T、T、P-R、Q-T、P-P）填入，数值（33～36h、5～7d、190/100mmHg 等）均保留原值，
 *   未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "pharmacology-ch26-heart-failure-drugs";
const locatorBase =
  "《药理学学习指导与习题集》第4版（配套《药理学》第9版） 第26章 治疗心力衰竭的药物 习题（核对PDF 第168–181页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），4 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：正性肌力药物",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "正性肌力药物",
        "能够加强心肌收缩力，用于充血性心力衰竭的药物，如强心苷类（地高辛等）及非苷类正性肌力药（多巴酚丁胺、米力农等）。原书名词解释第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：强心苷",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "强心苷",
        "具有正性肌力作用的苷类，由苷元（甾核与不饱和内酯环）和糖结合而成，是治疗充血性心力衰竭的主要药物，代表药有洋地黄毒苷、地高辛、毛花苷 C 和毒毛花苷 K。原书名词解释第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：全效量",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "全效量",
        "或称洋地黄化量，即在短期内给予充分发挥疗效而又不致中毒的剂量。原书名词解释第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：隐匿传导",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "隐匿传导",
        "是指来自心房的冲动传入房室结后，因递减传导不能经房室结进入心室而隐没在房室结中，但留下不应期，阻止了其后冲动的传递。强心苷通过增加房室结中的隐匿性传导而减慢房颤患者的心室率。原书名词解释第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），13 道 */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill001",
    order: 5,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "强心苷对心肌功能影响的主要缺点是___和___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "无正性心肌舒张作用；不能纠正舒张功能障碍",
        "强心苷只能增强心肌收缩力，无正性心肌舒张作用，不能纠正舒张功能障碍，故对舒张功能不全为主的难治性心衰疗效差。原书填空题第 1 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill002",
    order: 6,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "强心苷不增加正常心脏的搏出量，是因为它还有___，因而限制了心输出量的增加。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "收缩血管提高外周阻力的作用",
        "强心苷对正常心脏除正性肌力作用外，还有直接收缩血管、提高外周阻力的作用，二者作用相抵消，故不增加正常心脏的搏出量；对衰竭心脏则因反射性交感张力降低，心输出量增加。原书填空题第 2 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill003",
    order: 7,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "强心苷常用于治疗房颤，其机制是___，因而可使___减慢。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抑制房室传导；心室率",
        "房颤时心房率可达 350～600 次/分，强心苷通过兴奋迷走神经或对心房的直接作用，增加房室结中的隐匿性传导、减慢房室传导，使过多冲动不能下传心室，从而减慢心室率。原书填空题第 3 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill004",
    order: 8,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "可用于治疗充血性心力衰竭的正性肌力药有下述三类：___、___和___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "强心苷；拟交感神经药；磷酸二酯酶抑制剂",
        "正性肌力药包括：①强心苷类（洋地黄毒苷、地高辛等）；②拟交感神经药（β 受体激动药，如多巴胺、多巴酚丁胺、异布帕明）；③磷酸二酯酶（PDE）抑制剂（如氨力农、米力农）。原书填空题第 4 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill005",
    order: 9,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "强心苷是由___和___结合而成。苷元是由___和___构成，是其发挥正性肌力作用的基本结构。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "苷元；糖；甾核；不饱和内酯环",
        "强心苷由苷元加糖组成，苷元由甾核和不饱和内酯环构成，强心苷的强心作用来自苷元，不饱和内酯环是发挥正性肌力作用的基本结构。原书填空题第 5 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill006",
    order: 10,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "强心苷类制剂的体内过程，与其化学结构中___的数目有关。数目越___，极性越___，脂溶性越___，口服吸收率越___，且越___被肝代谢失活。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "甾核羟基；少；低；高；高；易",
        "强心苷类制剂的体内过程与其化学结构中甾核上羟基的数目有关：羟基数目越少，极性越低、脂溶性越高，口服吸收率、血浆蛋白结合率和被肝代谢的程度越高（如洋地黄毒苷只有一个羟基）。原书填空题第 6 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill007",
    order: 11,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "强心苷的作用在心电图上主要表现为___段下降，___波低平或倒置，___间期延长，___间期缩短，___间期缩短。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "S-T；T；P-R；Q-T；P-P",
        "治疗量强心苷对心电图的影响为：S-T 段下降呈鱼钩状、T 波低平或倒置、P-R 间期延长、Q-T 间期缩短及 P-P 间期改变。本题末空按参考答案键号（S-T、T、P-R、Q-T、P-P）填入；其中 P-P 一项原书参考答案置于“间期缩短”处，教材通说强心苷减慢心率使 P-P 间期延长，此处按参考答案原文保留。原书填空题第 7 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill008",
    order: 12,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "强心苷对___的心力衰竭疗效最好。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "伴有房颤和心室率快",
        "强心苷对伴有房颤和心室率快的心力衰竭疗效最好，通过减慢房室传导和心室率改善心功能；对肺源性心脏病、严重贫血、甲亢等所致心衰疗效差且易中毒。原书填空题第 8 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill009",
    order: 13,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "强心苷的不良反应主要表现在以下三个方面：___、___和___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "胃肠道反应；CNS 反应和视觉障碍；心脏毒性",
        "强心苷不良反应：①胃肠道反应（厌食、恶心、呕吐、腹泻等，是最常见的早期中毒反应）；②中枢神经系统反应和视觉障碍（眩晕、头痛、失眠、疲倦、谵妄及黄视、绿视、视物模糊等，视觉异常为停药指征）；③心脏毒性（各种心律失常，常见室性早搏）。原书填空题第 9 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill010",
    order: 14,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "地高辛主要通过___消除，其半衰期大约为___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肾；33～36h",
        "地高辛主要以原形经肾小球滤过和肾小管分泌排泄，其消除半衰期约为 33～36 小时，肾功能不良者禁用或慎用。原书填空题第 10 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill011",
    order: 15,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "洋地黄毒苷主要通过___消除，其半衰期大约为___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肝；5～7d",
        "洋地黄毒苷脂溶性高，主要在肝脏代谢失活，消除半衰期约为 5～7 天，肝肠循环明显，作用最持久。原书填空题第 11 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill012",
    order: 16,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "治疗慢性心功能不全除可应用强心苷等正性肌力药外，尚可采用___和___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "利尿药；血管扩张药",
        "治疗慢性心功能不全除正性肌力药外，尚可采用利尿药（排钠利尿、降低血容量与心脏前负荷）和血管扩张药（扩张外周血管，降低心脏前、后负荷），以及 RAAS 抑制药、β 受体阻断药等。原书填空题第 12 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-fill013",
    order: 17,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "地高辛的消除半衰期为___，如每日给予维持量，约经___个半衰期后，___天之后血中可达到稳态浓度。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "33～36h；4～5；6～7",
        "地高辛消除半衰期约 33～36 小时，按每日给予维持量，约经 4～5 个半衰期后，即 6～7 天之后血中可达到稳态浓度（坪值）。原书填空题第 13 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 选择题（a1-single），5 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-a1001",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "强心苷治疗房颤的机制主要是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["缩短心房有效不应期", "减慢房室传导", "抑制窦房结", "阻断β受体", "降低浦氏纤维自律性"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "减慢房室传导",
        "房颤时心房率可达 350～600 次/分，强心苷通过增强迷走神经张力或对心房的直接作用，增加房室结中的隐匿性传导、减慢房室传导，使过多冲动不能下传心室，从而减慢心室率。原书 A1 型题第 1 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-a1002",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "血管扩张药治疗心衰的药理学基础是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["改善冠脉血流", "降低血压", "增加心肌收缩力", "扩张动静脉，降低心脏前后负荷", "降低心输出量"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "扩张动静脉，降低心脏前后负荷",
        "血管扩张药（如硝普钠、硝酸甘油、肼屈嗪、哌唑嗪等）通过扩张外周小动脉和小静脉，降低心脏前、后负荷，进而改善心脏功能：扩张静脉减少回心血量、降低前负荷，扩张动脉降低左室射血阻力、降低后负荷。原书 A1 型题第 2 题，参考答案键号 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-a1003",
    order: 20,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "强心苷治疗心衰的原发作用是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["增加心脏工作效率", "降低室壁肌张力及心肌耗氧量", "增加心肌收缩性", "减慢心率", "使已扩大的心室容积缩小"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "增加心肌收缩性",
        "强心苷对心脏的直接作用是增强心肌收缩力（正性肌力作用），这是其治疗心衰的原发作用；减慢心率（负性频率）、降低室壁肌张力及心肌耗氧量、增加心脏工作效率等均为正性肌力作用的继发结果。原书 A1 型题第 3 题，参考答案键号 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-a1004",
    order: 21,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "强心苷疗效最好的适应证是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["高血压性心衰伴有房颤", "严重贫血引起的心衰", "肺源性心脏病引起的心衰", "甲状腺功能亢进的心衰", "严重二尖瓣病引起的心衰"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "高血压性心衰伴有房颤",
        "强心苷对伴有房颤、心室率快的心衰疗效最好，如高血压性心衰伴有房颤；对肺源性心脏病、严重贫血、甲亢及严重二尖瓣狭窄（高度二尖瓣狭窄）等所致心衰疗效差，且易中毒。原书 A1 型题第 4 题，参考答案键号 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-a1005",
    order: 22,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "强心苷中毒时，哪种情况不应给钾盐",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["室上性阵发性心动过速", "房室传导阻滞", "室性早搏", "二联律", "室性心动过速"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "房室传导阻滞",
        "强心苷中毒致房室传导阻滞时不应给钾盐，因血钾过高可加重房室传导阻滞；室性早搏、室性心动过速、室上性阵发性心动过速、二联律等快速型心律失常与低血钾及迟后除极有关，可口服或缓慢静脉滴注钾盐。原书 A1 型题第 5 题，参考答案键号 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 简答题（short-answer），10 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-short001",
    order: 23,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "心衰时有哪些调节机制发生变化？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①交感神经激活；②肾素-血管紧张素-醛固酮系统激活；③精氨酸加压素分泌增加；④某些内源性调节剂增加；⑤心脏 β 受体密度下降",
        "心衰时发生变化的调节机制：①交感神经激活：心衰时交感神经系统被缓慢激活，高浓度去甲肾上腺素（NA）可直接损伤心肌；②肾素-血管紧张素-醛固酮系统（RAAS）激活；③精氨酸加压素分泌增加；④某些内源性调节剂增加；⑤心脏 β 受体密度下降。这些代偿性调节在早期可维持心功能，长期则加重心肌损伤与心室重构。原书简答题第 1 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-short002",
    order: 24,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "什么是强心苷，其基本化学结构的特点是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "强心苷由苷元加糖组成，强心作用来自苷元。结构特点：C₃ 是 β-构型的 -OH 与糖结合的位点，C₁₄ 必有 β-构型的 -OH，C₁₇ 必有 β 构型的不饱和内酯环，一般三糖苷作用最好",
        "强心苷的苷元由甾核和不饱和内酯环构成，强心作用来自苷元；C₃ 位 β-构型的羟基是与糖结合的位点，C₁₄ 位必有 β-构型羟基，C₁₇ 位必有 β 构型的不饱和内酯环，一般三糖苷作用最好。原书简答题第 2 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-short003",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "强心苷心脏外系统的作用有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①血管：直接收缩血管，使血压上升；②肾：利尿，继发于正性肌力作用；③神经系统：中毒量时兴奋延脑极后区催吐化学感受区及兴奋 CNS，增加交感活性",
        "强心苷心脏外系统的作用：①血管：直接收缩血管，使血压上升（治疗量）；②肾：利尿，继发于正性肌力作用（肾血流量及肾小球滤过率增加）；③神经系统：中毒量时兴奋延髓极后区催吐化学感受区及兴奋中枢神经系统，并增加交感活性。原书简答题第 3 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-short004",
    order: 26,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "强心苷中毒时应如何处理？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①停药；②补充 KCl；③用抗心律失常药；④中断肝肠循环；⑤用地高辛抗体等",
        "强心苷中毒时应该：①停药（停用强心苷类及排钾利尿药）；②补充 KCl（口服或静脉滴注）；③用抗心律失常药（缓慢型心律失常用阿托品，室性快速型心律失常用利多卡因、苯妥英钠）；④中断肝肠循环（用考来烯胺等）；⑤用地高辛抗体等。原书简答题第 4 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-short005",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "简述强心苷加强心肌收缩力的特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①加快心肌纤维缩短速度，使心肌收缩敏捷；②加强衰竭心肌收缩力的同时，心肌耗氧量并不增加，甚至有所降低；③增加衰竭心脏的心输出量",
        "强心苷加强心肌收缩力的特点：①加快心肌纤维缩短速度，使心肌收缩敏捷，心肌收缩期缩短、舒张期相对延长；②加强衰竭心肌收缩力的同时，心肌耗氧量并不增加甚至有所降低；③增加衰竭心脏的心输出量。原书简答题第 5 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-short006",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "能增强强心苷毒性的因素有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①离子改变：低血钾、高血钙、低血镁均能促进强心苷中毒；②缺氧状态：如阻塞性肺疾患可加重心肌细胞失钾，使心脏对强心苷更敏感；③病理状态：弥漫性心肌病、传导系统疾病、慢性肺疾患、甲亢等易招致中毒；④合并用药：与排钾利尿药、奎尼丁、Ca²⁺ 通道阻断药、拟肾上腺素药合用可增加心脏毒性",
        "能增强强心苷毒性的因素：①离子改变：低血钾、高血钙、低血镁都能促进强心苷类药物中毒；②缺氧状态：如阻塞性肺疾患能加重心肌细胞失钾，使心脏对强心苷更敏感；③病理状态：弥漫性心肌病、传导系统疾病、慢性肺疾患、甲亢等都易招致强心苷中毒；④合并用药：与排钾利尿药、奎尼丁、钙通道阻断药、拟肾上腺素药合用能增加强心苷对心脏的毒性。原书简答题第 6 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-short007",
    order: 29,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "强心苷对心脏有何作用？对心肌细胞内离子有什么影响？为什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "对心脏的作用：增强心肌收缩力（正性肌力作用），也有减慢心率和抑制传导的作用；对心肌细胞内离子的影响：K⁺ 减少、Ca²⁺ 增加；原因：强心苷抑制心肌细胞膜的 Na⁺-K⁺-ATP 酶所致",
        "强心苷对心脏的作用有：增强心肌收缩力（正性肌力作用），也有减慢心率和抑制传导的作用。在强心苷作用下，心肌细胞内 K⁺ 减少、Ca²⁺ 增加，这主要是因为强心苷抑制心肌细胞膜的 Na⁺-K⁺-ATP 酶，胞内 Na⁺ 增多后经 Na⁺-Ca²⁺ 交换使 Ca²⁺ 内流增多。原书简答题第 7 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-short008",
    order: 30,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "强心苷类的化学结构对各种不同制剂体内过程的影响。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "强心苷类的不同制剂（洋地黄毒苷、地高辛、毛花苷 C 和毒毛花苷 K）体内过程特点不尽相同，与其化学结构中甾核上羟基的数目有关：洋地黄毒苷只有一个羟基，极性最低、脂溶性最高，口服吸收率、血浆蛋白结合率和被肝代谢的程度都较高；反之亦然",
        "强心苷类不同制剂体内过程特点与其化学结构中甾核上羟基数目有关：洋地黄毒苷羟基最少，极性最低、脂溶性最高，口服吸收率、血浆蛋白结合率和被肝代谢程度都较高，半衰期最长（5～7 天）；毒毛花苷 K 羟基最多，极性高、脂溶性低，口服吸收差、经肾排泄，起效最快、维持时间短。原书简答题第 8 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-short009",
    order: 31,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "治疗慢性心功能不全的药物有几类？主要代表药是什么？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "①肾素-血管紧张素-醛固酮系统抑制药（ACEI 卡托普利、AT₁ 拮抗药氯沙坦、醛固酮拮抗药螺内酯）；②利尿药（氢氯噻嗪、呋塞米等）；③β 受体阻断药（美托洛尔、卡维地洛等）；④正性肌力药（强心苷类地高辛、非苷类米力农等）；⑤扩血管药（硝普钠、硝酸异山梨酯、肼屈嗪、哌唑嗪等）；⑥钙增敏药及钙通道阻滞药",
        "治疗慢性心功能不全的药物包括：①肾素-血管紧张素-醛固酮系统抑制药：血管紧张素Ⅰ转化酶抑制药（卡托普利等）、血管紧张素Ⅱ受体（AT₁）拮抗药（氯沙坦等）、醛固酮拮抗药（螺内酯）；②利尿药：氢氯噻嗪、呋塞米等；③β 受体阻断药：美托洛尔、卡维地洛等；④正性肌力药：强心苷类（地高辛等）与非苷类正性肌力药（米力农、维司力农等）；⑤扩血管药：硝普钠、硝酸异山梨酯、肼屈嗪、哌唑嗪等；⑥钙增敏药及钙通道阻滞药。原书简答题第 9 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-short010",
    order: 32,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "试述强心苷正性肌力作用的机制。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "强心苷抑制 Na⁺-K⁺-ATP 酶，导致胞内 Na⁺ 增多、K⁺ 减少，通过 Na⁺-Ca²⁺ 双向交换机制使胞内 Ca²⁺ 增加；肌浆网摄取 Ca²⁺ 增加使贮存 Ca²⁺ 增多，同时增强 Ca²⁺ 离子流使动作电位 2 相平台内流 Ca²⁺ 增多，经“以钙促钙”方式使肌浆网释放 Ca²⁺，最终使胞内可利用的 Ca²⁺ 增加，收缩力增加",
        "强心苷正性肌力作用的机制：强心苷抑制心肌细胞膜 Na⁺-K⁺-ATP 酶，胞内 Na⁺ 增多、K⁺ 减少，通过 Na⁺-Ca²⁺ 双向交换机制使胞内 Ca²⁺ 增加；肌浆网摄取 Ca²⁺ 也增加使贮存 Ca²⁺ 增多；同时增强 Ca²⁺ 离子流，使动作电位 2 相平台期内流 Ca²⁺ 增多，此 Ca²⁺ 通过“以钙促钙”方式使肌浆网释放 Ca²⁺，最终使胞内可利用的 Ca²⁺ 增加，心肌收缩力增加。原书简答题第 10 题。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，3 组 × 2 成员（原书 48～53 题） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-b001",
    order: 33,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "氢氯噻嗪",
      "米力农",
      "氯沙坦",
      "卡维地洛",
      "多巴酚丁胺",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-pharmacology-ch26-heart-failure-drugs-b001m1",
        order: 33,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "适用于轻、中度心力衰竭及左、右心室充盈量高患者的药物是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "氢氯噻嗪",
            "氢氯噻嗪为噻嗪类利尿药，排钠利尿、降低血容量与心脏前负荷，适用于轻、中度心力衰竭及左、右心室充盈量高的患者。原书 B1 型题第 48 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-pharmacology-ch26-heart-failure-drugs-b001m2",
        order: 34,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "只用于心功能比较稳定的 I～III 级心力衰竭患者的药物是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "卡维地洛",
            "卡维地洛为 β 受体阻断药，长期应用可阻止 CHF 临床症状恶化、改善心功能、降低猝死及心律失常发生率，适用于心功能比较稳定的 I～III 级患者，应尽早在 ACE 抑制剂和利尿药的基础上加用。原书 B1 型题第 49 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-b002",
    order: 35,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "洋地黄毒苷",
      "地高辛",
      "阿托品",
      "哌替啶",
      "考来烯胺",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-pharmacology-ch26-heart-failure-drugs-b002m1",
        order: 35,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "能治疗强心苷中毒引起的窦性心动过缓和房室传导阻滞的药物是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "阿托品",
            "阿托品为 M 胆碱受体阻断药，可解除迷走神经对心脏的抑制，用于治疗强心苷中毒引起的窦性心动过缓和房室传导阻滞等缓慢型心律失常。原书 B1 型题第 50 题，参考答案键号 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-pharmacology-ch26-heart-failure-drugs-b002m2",
        order: 36,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "具有明显肝肠循环的药物是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "洋地黄毒苷",
            "洋地黄毒苷脂溶性高，部分经胆汁排入肠道后可被重吸收，肝肠循环明显，作用持久；考来烯胺可在肠道与洋地黄毒苷结合、打断肝肠循环以减轻中毒。原书 B1 型题第 51 题，参考答案键号 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-pharmacology-ch26-heart-failure-drugs-b003",
    order: 37,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "抑制房室传导",
      "加强心肌收缩力",
      "抑制窦房结",
      "缩短心房的有效不应期",
      "加快房室传导",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-pharmacology-ch26-heart-failure-drugs-b003m1",
        order: 37,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "强心苷治疗心力衰竭的药理学基础是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "加强心肌收缩力",
            "强心苷治疗心力衰竭的药理学基础是正性肌力作用（加强心肌收缩力）：心肌收缩有力而敏捷，心肌耗氧量降低，心输出量增加，同时其负性频率、负性传导作用也有利于改善心功能。原书 B1 型题第 52 题，参考答案键号 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-pharmacology-ch26-heart-failure-drugs-b003m2",
        order: 38,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "强心苷治疗心房扑动的药理学基础是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "缩短心房的有效不应期",
            "强心苷可缩短心房的有效不应期，使心房扑动转为心房颤动，再通过增加房室结中的隐匿性传导减慢心室率，从而控制房扑。原书 B1 型题第 53 题，参考答案键号 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...fillItems,
  ...a1Items,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
