import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学微生物学学习指导与习题集（第2版）— 第08章 球菌 题库提取（等比取样）
 * 来源：《医学微生物学学习指导与习题集》第2版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：7 题
 * - 填空题（fill）：5 题
 * - 选择题（a1-single）：12 题（含 A2 病例题 0 题）
 * - 问答题（short-answer）：3 题
 * - B1 配伍题：2 组、共 9 个成员
 * - 独立记分题合计：36 题（须等于本文件预算 36）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含名词解释 7、填空题 14、选择题（A1 型 36 + A2 型 8 + B1 型 12 组
 *   42 小题）与简答题 7。本文件按 36 道预算在原书顺序内取材：名词解释全取、填空取前 5
 *   道、简答取前 3 道；选择题取 A1 第 1~12 题；B1 取第 1 组（45~50，6 成员）与第 2 组
 *   （51~53，3 成员）完整组。正确项对齐章末参考答案键号。OCR 错字与双栏错序已按微生物
 *   学医学语义恢复（如 G*→G⁺、英膜→荚膜、荬膜→荚膜、耐瑟→奈瑟、◎→O 等），数值保留
 *   原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "microbiology-ch08-cocci";
const locatorBase =
  "《医学微生物学学习指导与习题集》第2版 第08章 球菌 习题（核对PDF 第71–84页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），7 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-microbiology-ch08-cocci-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：SPA",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "SPA",
        "SPA 即葡萄球菌 A 蛋白，90% 以上金黄色葡萄球菌细胞壁表面存在 SPA 蛋白质。能与人及多种哺乳动物的 IgG1、IgG2 和 IgG4 分子 Fc 段非特异性结合，结合后的 IgG 分子 Fab 段仍能与抗原特异结合，利用此原理建立的协同凝集试验已广泛应用于多种微生物抗原检测。在体内，SPA 与 IgG 结合后所形成的复合物还具有抗吞噬、促细胞分裂、引起超敏反应、损伤血小板等多种生物活性。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：血浆凝固酶",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血浆凝固酶",
        "致病性金黄色葡萄球菌菌株大多能产生血浆凝固酶，有两种类型：①游离凝固酶，作用类似凝血酶原物质，使液态纤维蛋白原变为固态纤维蛋白，使血浆凝固；②结合凝固酶，在菌体表面并不释放，充当纤维蛋白原受体作用，能与纤维蛋白原结合使细菌凝聚。血浆凝固酶与细菌的毒力有密切关系，具有保护细菌、抵抗吞噬和杀菌物质的破坏、使感染局限化和形成血栓的作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：MRSA",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "MRSA",
        "MRSA 即耐甲氧西林金黄色葡萄球菌，是医院感染最常见的致病菌。耐药性的产生机制与细菌的质粒或与细菌细胞壁成分改变和合成的量有关，常见的机制是由质粒介导的能够水解 β-内酰胺环的 β-内酰胺酶的产生。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：链球菌溶素",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "链球菌溶素",
        "链球菌溶素是 A 群链球菌产生的一种有溶解红细胞、破坏白细胞和血小板作用的毒素。根据对氧的稳定性，可以分为两种：链球菌溶素 O（SLO）对氧敏感，对哺乳动物中性粒细胞、血小板、巨噬细胞、神经细胞及心肌等有毒性作用，活动性风湿热病人中的血清 SLO 抗体显著增高；链球菌溶素 S（SLS）对氧稳定，链球菌在血琼脂平板上菌落周围的 β 溶血环是由 SLS 所致，对白细胞和多种组织细胞有破坏作用。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：红疹毒素",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "红疹毒素",
        "红疹毒素即致热外毒素，又称猩红热毒素，是人类猩红热的主要毒性物质。由携带溶原性噬菌体的 A 群链球菌产生。化学组成是蛋白质，有 A、B、C 3 个血清型。致热外毒素抗原性强，具有超抗原作用，对兔有致热性和致死性。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：ASO 试验",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "ASO 试验",
        "ASO 试验即抗链球菌溶素 O 试验，简称抗 O 试验，常用于风湿热的辅助诊断。风湿热患者血清中抗 O 抗体比正常人显著增高，大多在 250 单位左右；活动性风湿热患者一般超过 400 单位。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：M蛋白",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "M蛋白",
        "M 蛋白是溶血性链球菌主要致病因子，具有抗吞噬与黏附上皮细胞的作用，与心肌组织、肾小球基底膜等组织有交叉抗原，可引起风湿热、急性肾小球肾炎等超敏反应性疾病。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1 型选择题（映射为 a1-single），12 道 */
const a1Items: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-microbiology-ch08-cocci-a1001",
    order: 8,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列无芽胞的细菌中，抵抗力最强的细菌是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["金黄色葡萄球菌", "乙型溶血性链球菌", "百日咳杆菌", "大肠杆菌", "肺炎链球菌"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "金黄色葡萄球菌",
        "金黄色葡萄球菌是无芽胞细菌中抵抗力最强的细菌，也是最易产生耐药性变异的细菌。原书 A1 答案第 1 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-a1002",
    order: 9,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "能产生SPA的细菌是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["粪链球菌", "乙型溶血性链球菌", "肺炎链球菌", "金黄色葡萄球菌", "表皮葡萄球菌"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "金黄色葡萄球菌",
        "SPA 存在于 90% 的金黄色葡萄球菌细胞壁表面，可与 IgG 的 Fc 段非特异性结合。原书 A1 答案第 2 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-a1003",
    order: 10,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "葡萄球菌肠毒素的作用是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "直接破坏胃黏膜细胞，导致腹泻、腹痛",
      "直接毒害肠黏膜细胞，导致腹泻、腹痛",
      "直接毒害中枢神经，引起食物中毒",
      "通过刺激呕吐中枢而导致呕吐",
      "直接破坏肠壁血管，导致出血性肠炎",
    ],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "通过刺激呕吐中枢而导致呕吐",
        "金黄色葡萄球菌肠毒素可刺激呕吐中枢，导致以呕吐为主要症状的急性胃肠炎（食物中毒）。原书 A1 答案第 3 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-a1004",
    order: 11,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "能产生脂溶性色素的细菌是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["淋病奈瑟菌", "乙型溶血性链球菌", "铜绿假单胞菌", "金黄色葡萄球菌", "肺炎链球菌"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "金黄色葡萄球菌",
        "金黄色葡萄球菌能产生脂溶性色素（金黄色），使菌落呈金黄色，是鉴定的依据之一。原书 A1 答案第 4 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-a1005",
    order: 12,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "葡萄球菌重要的表面抗原有",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["M抗原", "Vi抗原", "SPA", "OT抗原", "K抗原"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "SPA",
        "葡萄球菌有三种主要抗原：荚膜多糖抗原、多糖抗原（群特异性）和葡萄球菌表面 A 蛋白（SPA），其中 SPA 是重要的表面抗原。原书 A1 答案第 5 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-a1006",
    order: 13,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "可与IgG Fc段结合的细菌表面物质是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["M蛋白", "Vi抗原", "葡萄球菌A蛋白", "炭疽杆菌荚膜多糖抗原", "大肠埃希菌K抗原"],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "葡萄球菌A蛋白",
        "SPA 可与 IgG 的 Fc 段非特异性结合，而 Fab 段仍能与相应抗原分子特异结合，据此建立协同凝集试验。原书 A1 答案第 6 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-a1007",
    order: 14,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "血浆凝固酶可以",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: [
      "促进细菌在体内扩散",
      "由表皮葡萄球菌产生",
      "增强细菌抗吞噬能力",
      "与IgG抗体的Fc段非特异性结合",
      "水解透明质酸",
    ],
    correctChoiceIndex: 2,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "增强细菌抗吞噬能力",
        "血浆凝固酶使纤维蛋白原变为纤维蛋白并沉积于菌体表面，具有保护细菌、抵抗吞噬和杀菌物质破坏的作用，是致病性葡萄球菌的重要鉴定指标。原书 A1 答案第 7 题为 C。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-a1008",
    order: 15,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列哪种细菌是医院感染最常见的致病菌",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["肺炎链球菌", "耐甲氧西林金黄色葡萄球菌", "乙型溶血性链球菌", "腐生葡萄球菌", "脑膜炎奈瑟菌"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "耐甲氧西林金黄色葡萄球菌",
        "耐甲氧西林金黄色葡萄球菌（MRSA）是医院感染最常见的致病菌。原书 A1 答案第 8 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-a1009",
    order: 16,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "金黄色葡萄球菌引起的毒素性疾病不包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["食物中毒", "剥脱性皮炎", "毒性休克综合征", "猩红热", "烫伤样皮肤综合征"],
    correctChoiceIndex: 3,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "猩红热",
        "金黄色葡萄球菌引起的毒素性疾病包括食物中毒、烫伤样皮肤综合征（剥脱性皮炎）、毒性休克综合征（TSS）等；猩红热由 A 群链球菌引起。原书 A1 答案第 9 题为 D。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-a1010",
    order: 17,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "致病性葡萄球菌重要的鉴定依据不包括",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["金黄色色素", "血平板上溶血", "凝固酶阳性", "耐热核酸酶", "发酵葡萄糖"],
    correctChoiceIndex: 4,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "发酵葡萄糖",
        "金黄色色素、血平板上溶血、凝固酶阳性、耐热核酸酶等是致病性葡萄球菌的重要鉴定依据；发酵葡萄糖是葡萄球菌属的共性，不能作为致病性鉴别的依据。原书 A1 答案第 10 题为 E。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-a1011",
    order: 18,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "化脓性炎症，其脓汁黏稠、病灶局限，这是由于病原菌产生",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["透明质酸酶", "血浆凝固酶", "耐热核酸酶", "链道酶", "链激酶"],
    correctChoiceIndex: 1,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "血浆凝固酶",
        "血浆凝固酶使纤维蛋白原凝固形成纤维蛋白，沉积于菌体表面并形成菌栓，使病灶局限、脓汁黏稠，与周围组织界限分明。原书 A1 答案第 11 题为 B。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-a1012",
    order: 19,
    knowledgePointId: kp,
    questionKind: "a1-single",
    status: "available",
    prompt: "下列细菌中可引起食物中毒的细菌是",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    choices: ["金黄色葡萄球菌", "链球菌", "肺炎链球菌", "脑膜炎奈瑟菌", "淋病奈瑟菌"],
    correctChoiceIndex: 0,
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "金黄色葡萄球菌",
        "金黄色葡萄球菌肠毒素可引起以呕吐为主要症状的食物中毒（急性胃肠炎）。原书 A1 答案第 12 题为 A。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 填空题（fill），5 道 */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-microbiology-ch08-cocci-fill001",
    order: 20,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "金黄色葡萄球菌的毒素有五种，能引起食物中毒的是___；引起烫伤样皮肤综合征的是___；引起毒素中毒性休克综合征的是___。金黄色葡萄球菌还可以产生两种酶即___和___，均为其致病性的指标。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "肠毒素；表皮剥脱毒素；中毒性休克综合征毒素-1；血浆凝固酶；耐热核酸酶",
        "金黄色葡萄球菌的毒素中，肠毒素引起食物中毒，表皮剥脱毒素引起烫伤样皮肤综合征，中毒性休克综合征毒素-1 引起毒性休克综合征；产生的两种酶为血浆凝固酶和耐热核酸酶，均为致病性指标。原书填空题第 1 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-fill002",
    order: 21,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "不形成芽胞的细菌中___抵抗力最强。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "金黄色葡萄球菌",
        "金黄色葡萄球菌是无芽胞细菌中抵抗力最强的细菌。原书填空题第 2 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-fill003",
    order: 22,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "链球菌能产生多种侵袭性酶如___、___、___和___。这些酶类都有___、___的作用，又称___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "透明质酸酶；链激酶；链道酶；胶原酶；溶解组织成分；促进细菌及毒素扩散；扩散因子",
        "链球菌产生的侵袭性酶包括透明质酸酶、链激酶、链道酶、胶原酶等，这些酶类都有溶解组织成分、促进细菌及毒素扩散的作用，又称扩散因子。原书填空题第 3 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-fill004",
    order: 23,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt:
      "链球菌产生的溶血素有二种即___和___，其中有抗原性的是___，可刺激机体产生___，常用于___和___的辅助诊断。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "溶血素O；溶血素S；溶血素O；抗O抗体；风湿热；急性肾小球肾炎",
        "链球菌产生的两种溶血素为链球菌溶素 O（SLO）和链球菌溶素 S（SLS），其中 SLO 有抗原性，可刺激机体产生抗 O 抗体，常用于风湿热和急性肾小球肾炎的辅助诊断。原书填空题第 4 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-fill005",
    order: 24,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "猩红热由___引起，因该菌可产生___，其主要作用是___，而___是一种超敏反应。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "A群链球菌；红疹毒素；发热；皮疹",
        "猩红热由 A 群链球菌引起，因该菌可产生红疹毒素（致热外毒素），其主要作用是引起发热和皮疹。原书填空题第 5 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 问答题（short-answer），3 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-microbiology-ch08-cocci-short001",
    order: 25,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：金黄色葡萄球菌的致病物质有哪些？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "金黄色葡萄球菌的致病物质",
        "主要致病物质包括三类：（1）细菌的一些表面结构蛋白，如黏附素、荚膜、胞壁肽聚糖和 SPA 等；（2）毒素：细胞溶素（α、β、γ、δ，对多种哺乳动物红细胞有溶血作用）、杀白细胞素（攻击中性粒白细胞和巨噬细胞）、表皮剥脱毒素（引起烫伤样皮肤综合征）、毒性休克综合征毒素-1（引起机体多个器官系统的功能紊乱或毒性休克综合征）、肠毒素（刺激呕吐中枢导致以呕吐为主要症状的急性胃肠炎）等；（3）酶类：凝固酶（使加有抗凝剂的人或兔血浆凝固，可作为鉴定致病性葡萄球菌的重要指标）、纤维蛋白溶酶（血浆纤维蛋白的溶解，利于病菌的扩散）、耐热核酸酶（降解 DNA 和 RNA）、透明质酸酶（溶解细胞间质中的透明质酸，利于细菌的扩散）、脂酶等（分解血浆和机体各部位表面的脂肪和油类，有利于细菌入侵皮肤和皮下组织）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-short002",
    order: 26,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述凝固酶阴性葡萄球菌所致疾病的类型。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "凝固酶阴性葡萄球菌所致疾病的类型",
        "凝固酶阴性葡萄球菌已成为临床上常见的条件致病菌，是医源性感染最常见的致病因子。可以导致：①菌血症或败血症，凝固酶阴性葡萄球菌是败血症最常见的病原菌之一，仅次于大肠埃希菌和金黄色葡萄球菌，居第三位；②尿路感染，尿路感染的病原菌最常见的是表皮葡萄球菌，其次腐生葡萄球菌等；③修复术或导管应用于治疗过程中引起的感染；④创伤感染，常发生在患者进行外科手术或遭受贯通伤后，体内、体表各部位皆可被感染。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-short003",
    order: 27,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述A群链球菌有哪些致病物质？可引起哪些疾病？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "A群链球菌的致病物质与所致疾病",
        "致病物质：（1）胞壁成分：①黏附素，包括脂磷壁酸和 F 蛋白，与细胞膜有高度亲和力，是主要侵袭因素；②M 蛋白，主要致病因子，具有抗吞噬和抵抗吞噬细胞内杀菌作用的能力，与某些超敏反应性疾病有关；③肽聚糖，具有致热、溶解血小板、提高血管通透性等作用。（2）外毒素：①致热外毒素又称红疹毒素或猩红热毒素，是人类猩红热的主要毒性物质；②链球菌溶素，有链球菌溶素 O（SLO，抗原性强，可刺激机体产生抗体）和链球菌溶素 S（SLS，无免疫原性，对白细胞和多种组织细胞有破坏作用）。（3）侵袭性酶类：①透明质酸酶，能分解细胞间质的透明质酸，使病菌易在组织中扩散；②链激酶（SK），有利于病菌在组织中扩散；③链道酶（SD），促进病菌扩散。所致疾病可分为三种类型：（1）化脓性感染：皮肤和皮下组织感染有淋巴管炎、淋巴结炎、蜂窝织炎、痈、脓疱疮等；其他系统感染有扁桃体炎、咽炎、咽峡炎、鼻窦炎、产褥感染、中耳炎、乳突炎等。（2）中毒性疾病：猩红热。（3）变态反应性疾病：风湿热和急性肾小球肾炎等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 共用备选答案配伍题，2 组（题组 45~50 与 51~53） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-microbiology-ch08-cocci-b001",
    order: 28,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: ["金黄色葡萄球菌", "A群链球菌", "肺炎链球菌", "脑膜炎奈瑟菌", "肠球菌"],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-microbiology-ch08-cocci-b001m1",
        order: 28,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "能产生血浆凝固酶的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "金黄色葡萄球菌",
            "致病性金黄色葡萄球菌大多能产生血浆凝固酶，是鉴定致病性葡萄球菌的重要指标。原书 B1 答案第 45 题为 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-microbiology-ch08-cocci-b001m2",
        order: 29,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "在黏膜表面黏附时，可产生分解SIgA蛋白酶的细菌是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "脑膜炎奈瑟菌",
            "脑膜炎奈瑟菌和淋病奈瑟菌均可产生 IgA1 蛋白酶，破坏黏膜表面 SIgA1，使细菌黏附于细胞表面。原书 B1 答案第 46 题为 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-microbiology-ch08-cocci-b001m3",
        order: 30,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "引发猩红热的病原体是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "A群链球菌",
            "猩红热由产生红疹毒素（致热外毒素）的 A 群链球菌引起。原书 B1 答案第 47 题为 B。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-microbiology-ch08-cocci-b001m4",
        order: 31,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "具有典型荚膜结构的细菌是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "肺炎链球菌",
            "肺炎链球菌有荚膜，荚膜是其主要致病物质，具有抗吞噬作用。原书 B1 答案第 48 题为 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-microbiology-ch08-cocci-b001m5",
        order: 32,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "属于革兰阴性菌的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "脑膜炎奈瑟菌",
            "金黄色葡萄球菌、A 群链球菌、肺炎链球菌、肠球菌均为革兰阳性菌，脑膜炎奈瑟菌为革兰阴性菌。原书 B1 答案第 49 题为 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-microbiology-ch08-cocci-b001m6",
        order: 33,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "能导致烫伤样皮肤综合征的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "金黄色葡萄球菌",
            "金黄色葡萄球菌产生的表皮剥脱毒素可引起烫伤样皮肤综合征。原书 B1 答案第 50 题为 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch08-cocci-b002",
    order: 34,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "细菌细胞壁中含有大量类脂",
      "菌体的一端附着单端单根鞭毛",
      "细菌合成产物中有凝固酶",
      "革兰染色时不被95%乙醇脱色",
      "细菌细胞壁中含有SPA等物质",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-microbiology-ch08-cocci-b002m1",
        order: 34,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "葡萄球菌共同的生物学性状是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 3,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "革兰染色时不被95%乙醇脱色",
            "葡萄球菌为革兰阳性菌，革兰染色时不被 95% 乙醇脱色而呈紫色，这是葡萄球菌共同的生物学性状。原书 B1 答案第 51 题为 D。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-microbiology-ch08-cocci-b002m2",
        order: 35,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "金黄色葡萄球菌的结构特点是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "细菌细胞壁中含有SPA等物质",
            "金黄色葡萄球菌细胞壁表面含有 SPA 等物质，可与 IgG 的 Fc 段非特异性结合。原书 B1 答案第 52 题为 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-microbiology-ch08-cocci-b002m3",
        order: 36,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "金黄色葡萄球菌与表皮葡萄球菌的鉴别要点是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 2,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "细菌合成产物中有凝固酶",
            "金黄色葡萄球菌能产生血浆凝固酶，表皮葡萄球菌（凝固酶阴性葡萄球菌）不产生凝固酶，故凝固酶是两者的鉴别要点。原书 B1 答案第 53 题为 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...fillItems,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
