import type {
  AssessmentItemDefinition,
  AssessmentItemGroupDefinition,
} from "@/types/learning";

/**
 * 医学微生物学学习指导与习题集（第2版）— 第16章 其他细菌 题库提取（等比取样）
 * 来源：《医学微生物学学习指导与习题集》第2版（人民卫生出版社；扫描件 OCR 恢复）
 *
 * == 统计报告（本文件题量 = 每教材 600、章节等比缩放预算）==
 * - 名词解释：8 题
 * - 填空题（fill）：19 题
 * - 选择题（a1-single）：0 题（含 A2 病例题 0 题）
 * - 问答题（short-answer）：12 题
 * - B1 配伍题：1 组、共 3 个成员
 * - 独立记分题合计：42 题（须等于本文件预算 42）
 * - 缺失答案：0；无法可靠提取：0
 * - 说明：本章原书依序含名词解释 8、填空题 19、选择题（A1 型 44 + A2 型 7）、B1 型 5 组
 *   （16 成员）与问答题 12；本文件按 42 道预算在原书顺序内取材，名词解释、填空题与问答题全取，
 *   B1 取第一组（52~54 题，3 成员），预算内未纳入选择题。正确项对齐章末参考答案键号
 *   （B1 52.E 53.A 54.C）。OCR 错字与双栏错序已按微生物学医学语义恢复（如 力→为、英膜/荬膜→荚膜、
 *   B-棒状杆菌噬菌体→β-棒状杆菌噬菌体、素状因子→索状因子、鮑-金→鲍-金、碳氢酶烯类→碳青霉烯类、
 *   核醣核酸→核糖核酸、14×10°L→14×10⁹/L 等），数值保留原值，未捏造。
 * 解析内容位于 answer.content 的第二个元素。
 */

const topic = "microbiology-ch16-other-bacteria";
const locatorBase =
  "《医学微生物学学习指导与习题集》第2版 第16章 其他细菌 习题（核对PDF 第125–138页）";
const promptNote =
  "题干改写；原题来自用户提供的章节习题集（扫描件 OCR 恢复），未经第三方授权审核";
const xMapNote =
  "题干改写并映射为单选；原题为多项选择题，按项目规约映射为 a1-single，原题来自用户题集，未经第三方授权审核";
const answerNotice =
  "答案依据题集参考答案整理并改写，未经权威教材交叉核对";

const kp = `kp-${topic}`;

/** 名词解释（term），8 道 */
const termItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-microbiology-ch16-other-bacteria-term001",
    order: 1,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：异染颗粒",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "异染颗粒",
        "棒状杆菌属细菌用 Neisser 或 Albert 等法染色时，菌体内出现节段浓染或深染的颗粒，与菌体着染颜色不同，称异染颗粒。主要成分核糖核酸和多磷酸盐，嗜碱性强。异染颗粒是白喉棒状杆菌形态上的主要特征，有重要的鉴别意义。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-term002",
    order: 2,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：白喉抗毒素",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白喉抗毒素",
        "是用白喉类毒素免疫动物得到的抗血清，用于治疗或紧急预防白喉。使用前需作皮肤试验，以避免超敏反应的发生。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-term003",
    order: 3,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：假膜",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "假膜",
        "呼吸道感染白喉棒状杆菌时，细菌和毒素使感染局部的黏膜上皮细胞产生渗出性炎症和坏死性炎症，血管扩张引起纤维蛋白原渗出。炎性细胞、纤维蛋白、坏死组织及白喉棒状杆菌等积聚在一起，形成的灰白色点状或片状物称为假膜。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-term004",
    order: 4,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：DPT（白百破三联疫苗）",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "DPT（白百破三联疫苗）",
        "由白喉类毒素、百日咳菌苗和破伤风类毒素组成的混合制剂疫苗，可用于预防白喉、百日咳和破伤风。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-term005",
    order: 5,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：白喉毒素",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白喉毒素",
        "是白喉棒状杆菌的主要致病物质，由 β-棒状杆菌噬菌体基因编码产生的一种毒性较强的外毒素。完整的白喉毒素是一条大量含精氨酸的多肽链，经蛋白酶水解后，分为 A 和 B 两个片段。B 链与心肌细胞、神经细胞上受体结合，协助 A 链进入易感细胞，使 EF2 失活，抑制宿主细胞蛋白质合成。白喉毒素具有强烈的细胞毒作用，能抑制敏感细胞正常合成蛋白质，引起组织细胞变性坏死。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-term006",
    order: 6,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：白喉",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白喉",
        "是由白喉棒状杆菌引起的一种人类急性呼吸道传染病，主要表现为患者咽喉部出现灰白色的假膜。该菌能产生强烈外毒素，可入血侵犯心肌细胞、外周神经末梢等敏感细胞，引起中毒性心肌炎和外周神经麻痹，严重的甚至引起患者死亡。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-term007",
    order: 7,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：军团病",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "军团病",
        "由嗜肺军团菌引起，经飞沫传播进入下呼吸道引起以肺为主的全身性感染，临床表现可分流感样型、肺炎型和肺外感染型。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-term008",
    order: 8,
    knowledgePointId: kp,
    questionKind: "term",
    status: "available",
    prompt: "名词解释：Pontiac fever",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "Pontiac fever",
        "庞蒂亚克热，由嗜肺军团菌引起的一种轻型、自限性疾病，临床表现为发热、寒战、肌肉酸痛等类似流感症状。因 1968 年流行于美国庞蒂亚克市而得名。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** A1/A2 型选择题（统一映射为 a1-single），本章预算内未纳入 —— 置空 */
const a1Items: readonly AssessmentItemDefinition[] = [];

/** 填空题（fill），19 道 */
const fillItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-microbiology-ch16-other-bacteria-fill001",
    order: 9,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "具有选择鉴别白喉棒状杆菌的培养基是___，因___能抑制杂菌，可使白喉棒状杆菌在此培养基上形成的菌落呈___色。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "亚碲酸钾血琼脂培养基；亚碲酸钾；黑",
        "亚碲酸钾血琼脂培养基为白喉棒状杆菌的选择鉴别培养基，亚碲酸钾能抑制杂菌，白喉棒状杆菌在此培养基上菌落呈黑色。原书填空题第 1 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill002",
    order: 10,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "可以使白喉棒状杆菌快速生长的培养基是___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "吕氏血清培养基",
        "白喉棒状杆菌在吕氏血清斜面（Loeffler）上生长迅速。原书填空题第 2 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill003",
    order: 11,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "白喉棒状杆菌的主要致病物质是___，其致病机制主要是___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白喉毒素；抑制宿主细胞蛋白质合成",
        "白喉毒素是白喉棒状杆菌的主要致病物质，A 亚单位灭活延伸因子 2（EF-2），抑制宿主细胞蛋白质合成。原书填空题第 3 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill004",
    order: 12,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "白喉毒素由___产生，其结合片段是___；其毒性片段是___。能使___灭活，从而抑制易感细胞___的合成。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "携带β-棒状杆菌噬菌体基因的白喉棒状杆菌；B 亚单位；A 亚单位；EF2/延伸因子2；蛋白质",
        "白喉毒素由携带 β-棒状杆菌噬菌体基因的白喉棒状杆菌产生，B 亚单位为结合片段、A 亚单位为毒性片段，A 亚单位使延伸因子 2（EF-2）灭活，抑制易感细胞蛋白质合成。原书填空题第 4 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill005",
    order: 13,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "白喉抗毒素可用于___和___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "紧急预防；治疗",
        "白喉抗毒素用于白喉的治疗和紧急预防，使用前需作皮肤试验。原书填空题第 5 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill006",
    order: 14,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "对白喉患者的治疗，除使用___外，更应___注射抗毒素。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "抗生素；尽早、足量",
        "对白喉患者的治疗应及早足量注射白喉抗毒素，同时服用或注射抗生素。原书填空题第 6 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill007",
    order: 15,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "白喉棒状杆菌是___的病原菌，在患者的喉部位可出现有灰白色的___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白喉；假膜",
        "白喉棒状杆菌是白喉的病原菌，在患者咽喉部可出现灰白色假膜。原书填空题第 7 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill008",
    order: 16,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "白喉早期死亡的主要原因是___，晚期死亡的主要原因是___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "假膜脱落阻塞气管；心肌损伤",
        "白喉假膜易脱落阻塞气道导致患者窒息（早期死亡主要原因），外毒素侵犯心肌细胞引起中毒性心肌炎（晚期死亡主要原因）。原书填空题第 8 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill009",
    order: 17,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "鉴定产毒型白喉棒状杆菌与其他棒状杆菌的重要试验是___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "毒力鉴定试验",
        "产毒型白喉棒状杆菌的鉴定需做毒力鉴定试验（如 Elek 平板毒力试验、豚鼠体内中和试验等）。原书填空题第 9 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill010",
    order: 18,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "白喉棒状杆菌在形态上的主要特征是有___，其主要成分是___和___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "异染颗粒；核糖核酸/RNA；多偏磷酸盐",
        "白喉棒状杆菌形态上的主要特征是有异染颗粒，其主要成分是核糖核酸（RNA）和多偏磷酸盐。原书填空题第 10 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill011",
    order: 19,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "白喉的人工主动免疫需接种___，白喉的人工被动免疫则注射___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白喉类毒素/百白破三联疫苗（DPT）；白喉抗毒素",
        "白喉的人工主动免疫接种白喉类毒素或百白破三联疫苗（DPT），人工被动免疫注射白喉抗毒素。原书填空题第 11 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill012",
    order: 20,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "调查人群对白喉有无免疫力的皮内试验称为___试验，其原理是___。出现___反应者表明无免疫力，需进行免疫接种。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "锡克/Schick；毒素抗毒素中和试验；阳性",
        "锡克（Schick）试验用白喉毒素作皮内试验调查人群对白喉的免疫力，其原理是毒素抗毒素中和试验，出现阳性反应者表明无免疫力，需进行免疫接种。原书填空题第 12 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill013",
    order: 21,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "嗜肺军团菌广泛存在于各种___中，侵入人体可寄生在___细胞内。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "水环境；巨噬",
        "嗜肺军团菌广泛存在于各种水环境中，侵入人体可寄生在巨噬细胞内，是胞内寄生菌。原书填空题第 13 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill014",
    order: 22,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "治疗嗜肺军团菌的首选药物是___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "红霉素",
        "治疗嗜肺军团菌感染首选红霉素。原书填空题第 14 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill015",
    order: 23,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "嗜肺军团菌在临床上有___、___、___三种感染型。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "流感样型；肺炎型；肺外感染型",
        "军团病临床上有流感样型（轻型，即庞蒂亚克热）、肺炎型（重病型）和肺外感染型三种感染类型。原书填空题第 15 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill016",
    order: 24,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "嗜肺军团菌是引起___的病原体。分离培养时需提供___和铁时才能生长。主要通过___传播。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "军团病；L-半胱氨酸；飞沫/呼吸道",
        "嗜肺军团菌是引起军团病的病原体，分离培养时需提供 L-半胱氨酸和铁才能生长，主要通过飞沫（呼吸道）传播。原书填空题第 16 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill017",
    order: 25,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "铜绿假单胞菌属于___菌属，是重要的___致病菌，在其致病物质中，可抑制蛋白质合成的是___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "假单胞；条件；铜绿假单胞菌外毒素 A",
        "铜绿假单胞菌属于假单胞菌属，是重要的条件致病菌，其致病物质中铜绿假单胞菌外毒素 A 可抑制蛋白质合成。原书填空题第 17 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill018",
    order: 26,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "预防百日咳可接种___或___。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "百日咳死菌苗；白百破三联疫苗/DPT",
        "预防百日咳可接种百日咳死菌苗或白百破三联疫苗（DPT）。原书填空题第 18 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-fill019",
    order: 27,
    knowledgePointId: kp,
    questionKind: "fill",
    status: "available",
    prompt: "培养百日咳杆菌的培养基常用___。该菌主要通过___传播，引起___。病后可获___免疫力。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "鲍金培养基/B-G 培养基；呼吸道；百日咳；牢固",
        "培养百日咳杆菌常用鲍-金（Bordet-Gengou，B-G）培养基，该菌主要通过呼吸道（飞沫）传播引起百日咳，病后可获牢固免疫力。原书填空题第 19 题答案。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** 问答题（short-answer），12 道 */
const shortItems: readonly AssessmentItemDefinition[] = [
  {
    id: "ext-microbiology-ch16-other-bacteria-short001",
    order: 28,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：患者小云，女性，4岁，随母由农村迁来城区幼儿园（免疫接种史不详），近日突然发热，喉痛，体乏。体检：体温38.2°C，P100次/分钟，鼻咽部有灰白色膜状物，拭之不易除去。试述小云可能患了什么疾病？对小云及幼儿园其他小朋友应采取什么防治措施？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白喉病例分析",
        "（1）小云可能得了白喉。（2）对小云的处理：隔离，尽早、足量注射抗毒素，使用抗生素，亦可加上白喉类毒素。（3）对其他小朋友的处理：如果已有基础免疫，注射类毒素；如果未有免疫，使用抗生素（抗毒素）。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-short002",
    order: 29,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述白喉杆菌的主要生物学特性。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白喉杆菌的主要生物学特性",
        "（1）形态与染色：菌体一端或两端膨大呈棒状，排列呈 V、L 等文字形，用 Neisser 或 Albert 等法染色可见异染颗粒。（2）培养特性：需氧或兼性厌氧，在吕氏血清斜面上生长迅速，且异染颗粒明显，在含亚碲酸钾的血平板上培养菌落呈黑色。（3）抵抗力：该菌对寒冷、干燥抵抗力强，对某些抗生素、热抵抗力弱。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-short003",
    order: 30,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：试述白喉毒素的作用机制及在临床上的可能用途。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白喉毒素的作用机制及临床可能用途",
        "（1）白喉毒素为 AB 型毒素，其中 B 亚单位与易感细胞表面受体结合，介导 A 亚单位进入易感细胞；A 亚单位可灭活细胞内肽链延长因子 2，抑制蛋白质的合成。（2）利用白喉毒素对肿瘤细胞的毒性作用，以及肿瘤单克隆抗体与相应的肿瘤抗原（或肿瘤相关抗原）特异性结合的特性，可构建成免疫毒素（“生物导弹”），用于肿瘤的靶向治疗，即将白喉毒素 A 亚单位与肿瘤单克隆抗体结合，借助抗体的特异性将毒素带至肿瘤细胞内杀死肿瘤细胞。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-short004",
    order: 31,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述白喉的特异性预防及治疗原则。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白喉的特异性预防及治疗原则",
        "（1）人工主动免疫：一般人群注射白喉类毒素作预防，儿童接种白百破三联疫苗作预防。（2）人工被动免疫：注射足量白喉抗毒素。对与白喉患者密切接触的易感儿童，一般主张立即服用抗菌药物作紧急预防。（3）治疗：对白喉患者的治疗，应及时注射白喉抗毒素，同时服用抗生素。对严重白喉患者，应密切注意观察，必要时作气管切开手术，取出假膜。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-short005",
    order: 32,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述白喉棒状杆菌的致病性。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "白喉棒状杆菌的致病性",
        "（1）白喉棒状杆菌的致病性与其产生的白喉外毒素有关。白喉外毒素属于细胞毒素，含有 A 和 B 两个亚单位，B 亚单位起着与细胞表面受体结合的作用，使具有酶活性的 A 亚单位进入细胞，发挥毒性作用；通过对细胞内延伸因子 2 的灭活，影响蛋白质的合成。（2）白喉棒状杆菌存在于患者及带菌者的鼻咽腔中，随飞沫或污染的物品传播。感染后的白喉杆菌在局部鼻咽黏膜上繁殖并分泌外毒素，使局部黏膜上皮细胞产生炎症、渗出性和坏死性反应，形成灰白色假膜。（3）白喉棒状杆菌一般不入血，但其外毒素可入血与易感的组织细胞结合，引起各种临床症状，如心肌炎、声嘶、肾上腺功能障碍和外周神经炎等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-short006",
    order: 33,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述产毒白喉棒状杆菌与其他棒状杆菌的鉴别方法。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "产毒白喉棒状杆菌与其他棒状杆菌的鉴别方法",
        "（1）体内法：通过豚鼠体内中和试验测定毒力。豚鼠皮下注射待检菌液，2~4 天观察结果，若实验组动物死亡而对照组没有死亡，则该菌为产毒菌。（2）体外法：Elek 平板毒力试验。在含有肉汤的琼脂平板上，平行接种待检菌和阳性对照菌，然后垂直铺一条浸有白喉抗毒素的滤纸条。37°C 培养 24~48 小时，若在纸条与待检菌交界处出现白色沉淀线则该待检菌为产毒菌。（3）此外，尚可用对流免疫电泳或 SPA 协同凝集试验检测待检菌培养物上清液中的毒素。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-short007",
    order: 34,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：百日咳杆菌的致病物质包括哪些？各有何毒性作用？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "百日咳杆菌的致病物质及毒性作用",
        "百日咳杆菌的致病物质除了菌体结构中的菌毛、荚膜和内毒素外，还有：（1）不耐热毒素，可引起气管和支气管纤毛上皮细胞炎症和坏死；（2）百日咳毒素（百日咳原），使呼吸道分泌物增多、淋巴细胞增多、抑制巨噬细胞的吞噬功能、并使细菌黏附在气管和支气管纤毛上皮细胞表面生长，造成细胞的损伤和坏死而出现阵发性咳嗽；（3）丝状血凝素，可帮助细菌黏附并使淋巴细胞增多。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-short008",
    order: 35,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：百日咳的临床病程可分为几期？试述其各期的特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "百日咳的临床病程分期及特点",
        "百日咳是由百日咳鲍特菌引起的一种呼吸道传染病，主要侵犯婴幼儿呼吸道。临床病程可分为三期：①卡他期，表现为普通感冒症状，低热、打喷嚏、轻度咳嗽，此期传染性强。②痉咳期，出现阵发性痉挛性咳嗽，常伴吸气吼声（如鸡鸣样吼声），同时常有呕吐、呼吸困难、发绀等症状。③恢复期，阵咳逐渐减轻，完全恢复需要数周数月不等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-short009",
    order: 36,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：哪些人易患军团病？如何防治嗜肺军团菌感染及军团病？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "军团病的易感人群及防治",
        "（1）军团病以 55 岁以上男性发病率最高，老年人、吸烟酗酒者以及免疫功能低下者易患此病。有流感样型、肺炎型和肺外感染型三大类。肺炎型军团病出现以肺部感染为主的继发性感染。（2）防治原则：目前尚无军团菌特异性疫苗，加强水源管理及人工输水管道和设施的消毒处理，防止军团菌造成空气和水源的污染，是预防军团菌病扩散的主要措施。治疗首选红霉素。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-short010",
    order: 37,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述军团菌病的类型及各类型的主要特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "军团菌病的类型及各类型的主要特点",
        "临床军团菌病主要有三种亚型：流感样型、肺炎型和肺外感染型。（1）流感样型又称庞蒂亚克热，是一种轻型、自限性疾病，症状表现为发热、寒战、肌肉酸痛等，通常无需治疗。（2）肺炎型又称军团病，表现为亚急性或急性重症肺炎，除肺部症状和体征外，还可表现出中枢神经系统和消化系统的症状。未经治疗病死率可高达 15% 以上。（3）肺外感染型，为继发性感染，出现脑、肾、肝等多脏器感染症状。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-short011",
    order: 38,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：铜绿假单胞菌的致病特点有哪些？如何进行治疗？",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "铜绿假单胞菌的致病特点及治疗",
        "（1）铜绿假单胞菌是一种常见的条件致病菌，广泛存在于医院的潮湿环境中，主要通过污染的医疗器具（如静脉导管）和带菌医护人员接触引起医源性感染，易感染皮肤黏膜受损部位，引起烧伤、创伤和手术切口感染等。此外，也见于长期化疗或使用免疫抑制剂的患者，表现为局部化脓性炎症或全身感染，以及中耳炎、角膜炎、心内膜炎等。（2）铜绿假单胞菌产生带荧光的水溶性色素（绿脓菌素和青脓菌素），感染后使感染部位或敷料出现绿色。（3）该菌呈多重耐药性，是医院感染的常见致病菌之一。（4）治疗主要可选用哌拉西林、头孢他啶、头孢吡肟、碳青霉烯类、阿米卡星等。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
  {
    id: "ext-microbiology-ch16-other-bacteria-short012",
    order: 39,
    knowledgePointId: kp,
    questionKind: "short-answer",
    status: "available",
    prompt: "问答题：简述铜绿假单胞菌的生物学性状以及感染特点。",
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    answer: {
      status: "available",
      authority: "nur-platform",
      confidence: "unverified",
      content: [
        "铜绿假单胞菌的生物学性状及感染特点",
        "（1）生物学性状：该菌为直或微弯杆菌，革兰染色阴性，有菌毛和单端鞭毛。营养要求不高，可产生蓝绿色水溶性色素，氧化酶试验阳性。42°C 可生长。（2）感染特点：①条件致病菌，当机体免疫力低下时可引起机体各部位的感染，可以是内源性的也可以是外源性的。该菌通过接触传染，是医源性感染的常见病原菌。②具有多种毒素和酶，有较强的蛋白分解能力，可感染人体的任何部位和组织，引起化脓性感染，脓液稀薄带绿色，并常引起败血症。③抵抗力较强，对多种抗生素耐药，因此治疗时应选用敏感抗生素。",
      ],
      notice: answerNotice,
      sourceIds: [],
    },
    scoring: null,
    sourceIds: [],
  },
];

/** B1 型配伍题（bGroups），1 组 × 3 成员（题组52-54；取材预算内未纳入后四组55-58、59-61、62-64、65-67） */
const bGroups: readonly AssessmentItemGroupDefinition[] = [
  {
    id: "ext-microbiology-ch16-other-bacteria-b001",
    order: 40,
    questionKind: "b1",
    status: "available",
    groupPrompt: null,
    sharedChoices: [
      "Elek 琼脂平板",
      "吕氏血清斜面培养基",
      "Lowenstein-Jensen 培养基",
      "SS 琼脂平板",
      "亚碲酸钾血琼脂平板",
    ],
    promptSource: {
      authority: "nur-editorial",
      wording: "nur-adapted",
      locator: locatorBase,
      note: promptNote,
      sourceIds: [],
    },
    members: [
      {
        id: "ext-microbiology-ch16-other-bacteria-b001m1",
        order: 40,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "白喉棒状杆菌的选择鉴别培养基是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 4,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "亚碲酸钾血琼脂平板",
            "亚碲酸钾血琼脂平板是白喉棒状杆菌的选择鉴别培养基，菌落呈黑色。原书 B1 答案第 52 题为 E。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-microbiology-ch16-other-bacteria-b001m2",
        order: 41,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "白喉棒状杆菌可在其上快速生长的是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 1,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "吕氏血清斜面培养基",
            "白喉棒状杆菌在吕氏血清斜面（Loeffler）上生长迅速。原书 B1 答案第 53 题为 A。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
      {
        id: "ext-microbiology-ch16-other-bacteria-b001m3",
        order: 42,
        knowledgePointId: kp,
        questionKind: "b1",
        status: "available",
        prompt: "可用于测定白喉棒状杆菌毒力的培养基是",
        promptSource: {
          authority: "nur-editorial",
          wording: "nur-adapted",
          locator: locatorBase,
          note: promptNote,
          sourceIds: [],
        },
        correctChoiceIndex: 0,
        answer: {
          status: "available",
          authority: "nur-platform",
          confidence: "unverified",
          content: [
            "Elek 琼脂平板",
            "Elek 平板毒力试验是体外测定白喉棒状杆菌毒力的方法。原书 B1 答案第 54 题为 C。",
          ],
          notice: answerNotice,
          sourceIds: [],
        },
        scoring: null,
        sourceIds: [],
      },
    ],
    sourceIds: [],
  },
];

export const extractedItems: readonly AssessmentItemDefinition[] = [
  ...termItems,
  ...a1Items,
  ...fillItems,
  ...shortItems,
];

export const extractedGroups: readonly AssessmentItemGroupDefinition[] = [
  ...bGroups,
];
